export interface MigrationTableSpec {
  /** PostgreSQL target table name and stable CLI/checkpoint identifier. */
  table: string;
  /** Unprefixed MySQL source table name when it differs from the target. */
  sourceTable?: string;
  key: string[];
  /**
   * Keyless source tables are copied as an append-only full-row multiset. The
   * target must contain exactly the rows already recorded by this run before
   * every batch, so unrelated/pre-existing rows are never guessed or merged.
   */
  copyStrategy?: "keyset" | "append_multiset";
  phase: "identity" | "catalog" | "commerce" | "finance" | "activity";
  /** Explicit source-column to target-column renames; no implicit guessing. */
  columnMappings?: Readonly<Record<string, string>>;
  /** Explicit conversions for legacy columns whose declared type hides their stored semantics. */
  columnConversions?: Readonly<
    Record<string, "numeric_string_to_integer" | "epoch_string_to_timestamp">
  >;
  note?: string;
}

/**
 * Explicit order for the logical tables currently shared or explicitly mapped
 * between the PHP install schema and PostgreSQL migrations. Live schema inspection is still the
 * authority: a table is blocked when source columns would be discarded, a
 * required target column has no source/default, or the key strategy is unsafe.
 */
export const MIGRATION_TABLES: readonly MigrationTableSpec[] = [
  {
    table: "cache",
    key: ["key"],
    phase: "identity",
    note: "Database-backed JSON documents use the source varchar primary key; the migrator pages scalar text keys in binary UTF-8 order and checkpoints them as JSON.",
  },
  { table: "system_config", key: ["id"], phase: "identity" },
  {
    table: "system_timer",
    key: ["id"],
    phase: "identity",
    note: "Legacy dynamic schedule definitions are retained for audit. Only auto_take and auto_comment have independent Worker scheduled implementations; imported rows never configure or dispatch Cloudflare jobs.",
  },
  {
    table: "system_group",
    key: ["id"],
    phase: "identity",
    note: "Legacy composite configuration definitions; fields stays text so invalid historical JSON is never silently rewritten.",
  },
  {
    table: "system_group_data",
    key: ["id"],
    phase: "identity",
    note: "Composite configuration values remain separate from system_config and retain their source JSON text verbatim.",
  },
  {
    table: "system_config_tab",
    key: ["id"],
    phase: "identity",
    note: "Hierarchical navigation for system_config.config_tab_id; it is not configuration value storage.",
  },
  {
    table: "system_form",
    key: ["id"],
    phase: "identity",
    note: "Dynamic form definitions remain separate from product references and order custom_form snapshots; JSON text is preserved verbatim.",
  },
  {
    table: "system_form_data",
    key: ["id"],
    phase: "identity",
    note: "Collected form submissions preserve the source VARCHAR system_form_id and remain separate historical rows.",
  },
  {
    table: "system_sign_reward",
    key: ["id"],
    phase: "identity",
    note: "Continuous and cumulative milestone rewards retain historical duplicate (type, days) rows; runtime admin writes reject new duplicates.",
  },
  { table: "agreement", key: ["id"], phase: "identity" },
  { table: "system_notification", key: ["id"], phase: "identity" },
  { table: "system_notice", key: ["id"], phase: "identity" },
  { table: "system_notice_admin", key: ["id"], phase: "identity" },
  { table: "system_city", key: ["id"], phase: "identity" },
  {
    table: "city_area",
    key: ["id"],
    phase: "identity",
    note: "The PHP order path expands city_area.path into ancestor IDs for shipping rules; create_time is converted from timestamp to epoch seconds.",
  },
  { table: "system_role", key: ["id"], phase: "identity" },
  { table: "system_menus", key: ["id"], phase: "identity" },
  { table: "system_admin", key: ["id"], phase: "identity" },
  {
    table: "out_account",
    key: ["id"],
    phase: "identity",
    note: "Third-party API identities remain source-shaped for import. Worker authentication uses only the bcrypt appsecret verifier; apppwd and push credentials are never returned or executed.",
  },
  { table: "system_user_level", key: ["id"], phase: "identity" },
  { table: "agent_level", key: ["id"], phase: "identity" },
  {
    table: "agent_level_task",
    key: ["id"],
    phase: "identity",
    note: "Distributor upgrade requirements retain source soft-delete and status semantics; runtime writes serialize catalog validation.",
  },
  {
    table: "agent_level_task_record",
    key: ["id"],
    phase: "identity",
    note: "The source has no composite uniqueness constraint; historical duplicate completion evidence remains importable while runtime writes lock per user.",
  },
  {
    table: "member_right",
    key: ["id"],
    phase: "identity",
    note: "The target uses id as its primary key; live planning rejects source id duplicates.",
  },
  { table: "member_card_batch", key: ["id"], phase: "identity" },
  {
    table: "member_card",
    key: ["id", "card_batch_id"],
    phase: "identity",
    note: "Activation secrets remain source-shaped; the source composite primary key is retained and ambiguous historical card numbers are rejected by runtime redemption.",
  },
  { table: "member_ship", key: ["id"], phase: "identity" },
  {
    table: "system_store",
    key: ["id"],
    phase: "identity",
    note: "Pickup-store location and payout metadata remain source-shaped; no phone uniqueness or foreign keys are invented.",
  },
  { table: "user", key: ["uid"], phase: "identity" },
  {
    table: "system_store_staff",
    key: ["id"],
    phase: "identity",
    note: "Store login and verification identities retain legacy password hashes and role strings; management responses never expose pwd or last_ip.",
  },
  {
    table: "store_user",
    key: ["id"],
    phase: "identity",
    note: "Historical store-customer duplicates remain importable; new relationships are serialized by store and user.",
  },
  {
    table: "store_config",
    key: ["id"],
    phase: "identity",
    note: "Store and supplier scoped overrides preserve historical duplicates; Worker writes use authenticated relation scopes and reject ambiguous keys.",
  },
  {
    table: "supplier_ticket_print",
    key: ["id"],
    phase: "identity",
    note: "Superseded single-printer supplier configuration retained for historical import only; active management uses print_document and never exposes api_key.",
  },
  {
    table: "print_document",
    key: ["id"],
    phase: "identity",
    note: "Active platform and supplier printer definitions; runtime access always scopes by supplier_id and masks provider secrets.",
  },
  {
    table: "system_user_apply",
    key: ["id"],
    phase: "identity",
    note: "Supplier onboarding applications preserve legacy review history; runtime writes enforce authenticated ownership and approved applications require SMS-backed password activation.",
  },
  {
    table: "sms_record",
    key: ["id"],
    phase: "identity",
    note: "SMS provider audit history remains source-shaped; new verification codes are generated with Web Crypto, stored only in expiring Redis entries, and never written to this table.",
  },
  {
    table: "system_attachment",
    key: ["att_id"],
    phase: "identity",
    note: "Attachment metadata and legacy object locations remain source-shaped; new runtime objects use R2 image_type=8 and all mutations are scoped by authenticated owner.",
  },
  {
    table: "system_attachment_category",
    key: ["id"],
    phase: "identity",
    note: "Platform and supplier category trees retain historical rows; runtime traversal and writes enforce type, relation_id and file_type scope.",
  },
  {
    table: "system_file",
    key: ["id"],
    phase: "identity",
    note: "PHP filesystem-integrity snapshots are retained as history only because Workers have no mutable application filesystem to compare.",
  },
  {
    table: "system_storage",
    key: ["id"],
    phase: "identity",
    note: "Legacy provider bucket rows are imported for audit only, access_key is never returned, and live object storage uses the generated ASSETS_BUCKET R2 binding.",
  },
  {
    table: "user_search",
    key: ["id"],
    phase: "identity",
    note: "Search history and cached product-id JSON remain source-shaped; historical duplicate rows stay importable while runtime updates serialize per user and keyword.",
  },
  {
    table: "user_visit",
    key: ["id"],
    phase: "identity",
    note: "Page and login visit evidence retains epoch seconds and channel/province strings for existing traffic analytics.",
  },
  {
    table: "promoter_apply",
    key: ["id"],
    phase: "identity",
    note: "Distributor applications preserve soft-deletion and review state; source duplicates remain importable while runtime mutations verify ownership under locks.",
  },
  {
    table: "user_spread",
    key: ["id"],
    phase: "identity",
    note: "Append-only distributor relationship history; the source has no composite uniqueness constraint and runtime bindings add audit rows transactionally.",
  },
  {
    table: "user_friends",
    key: ["id"],
    phase: "identity",
    note: "Bidirectional friend evidence derived from referral bindings; historical pair duplicates remain importable while runtime writes reject new duplicates under the relationship lock.",
  },
  { table: "user_level", key: ["id"], phase: "identity" },
  {
    table: "user_group",
    key: ["id"],
    phase: "identity",
    note: "User.group_id references this administrative segmentation catalog; runtime deletion is blocked while users still reference a group.",
  },
  { table: "user_address", key: ["id"], phase: "identity" },
  { table: "user_relation", key: ["id"], phase: "identity" },
  { table: "user_sign", key: ["id"], phase: "identity" },
  { table: "user_recharge", key: ["id"], phase: "identity" },
  { table: "user_invoice", key: ["id"], phase: "identity" },
  {
    table: "user_label",
    key: ["id"],
    phase: "identity",
    columnMappings: { label_name: "name" },
  },
  {
    table: "user_label_relation",
    key: ["id"],
    phase: "identity",
    note: "The source has no composite uniqueness constraint; historical duplicate assignments remain distinct rows during import.",
  },
  { table: "wechat_user", key: ["id"], phase: "identity" },
  { table: "system_supplier", key: ["id"], phase: "identity" },
  { table: "division_apply", key: ["id"], phase: "identity" },
  {
    table: "work_department",
    key: ["id"],
    phase: "identity",
    note: "Enterprise WeChat departments retain source IDs, parent identifiers, and the legacy srot spelling; imports do not trigger remote directory synchronization.",
  },
  {
    table: "work_member",
    key: ["id"],
    phase: "identity",
    note: "Enterprise member PII is Admin-only. The source userid uniqueness is preserved, while imported rows never configure Worker authentication or call Enterprise WeChat.",
  },
  {
    table: "work_member_other",
    key: ["member_id"],
    phase: "identity",
    note: "The source unique member_id is the stable cursor; extattr and external_profile stay nullable text so malformed historical JSON remains importable.",
  },
  {
    table: "work_member_relation",
    key: [],
    copyStrategy: "append_multiset",
    phase: "identity",
    note: "Copied as a full-row multiset so duplicate member/department assignments are preserved exactly; initial copy requires an empty target and every batch rechecks target row-count ownership.",
  },
  {
    table: "work_client",
    key: ["id"],
    phase: "identity",
    note: "Enterprise external-contact PII and commerce bindings are retained for Admin diagnosis only; public Work routes are not restored by import.",
  },
  { table: "work_client_follow", key: ["id"], phase: "identity" },
  {
    table: "work_client_follow_tags",
    key: [],
    copyStrategy: "append_multiset",
    phase: "identity",
    note: "Copied as a full-row multiset because repeated historical tag snapshots are valid evidence; initial copy requires an empty target.",
  },
  { table: "work_label", key: ["id"], phase: "identity" },

  {
    table: "category",
    key: ["id"],
    phase: "catalog",
    note: "Polymorphic taxonomy for label categories, product parameter templates, speechcraft, and channel metadata; do not merge with store_product_category.",
  },
  {
    table: "out_interface",
    key: ["id"],
    phase: "catalog",
    note: "Legacy interface IDs remain the account ACL contract. Only explicitly registered read routes are executable; importing documentation never enables an unimplemented write endpoint.",
  },
  { table: "store_brand", key: ["id"], phase: "catalog" },
  { table: "store_product_category", key: ["id"], phase: "catalog" },
  { table: "store_product_label", key: ["id"], phase: "catalog" },
  {
    table: "store_product_category_brand",
    key: ["id"],
    phase: "catalog",
    note: "Historical category-brand cache has no PHP runtime consumer; retain rows for audit without restoring it as a write authority.",
  },
  {
    table: "store_product_cate",
    key: ["id"],
    phase: "catalog",
    note: "Superseded category auxiliary rows remain importable; active category writes use store_product_relation and preserve each selected category's immediate pid.",
  },
  {
    table: "store_product_label_auxiliary",
    key: ["id"],
    phase: "catalog",
    note: "Superseded label auxiliary rows remain historical evidence only; active label writes use store_product_relation.",
  },
  { table: "store_product", key: ["id"], phase: "catalog" },
  {
    table: "store_branch_product",
    key: ["id"],
    phase: "catalog",
    note: "Dormant branch-product snapshot retained for historical import only; the PHP service path actually uses the main store_product table.",
  },
  {
    table: "store_branch_product_attr_value",
    key: ["id"],
    phase: "catalog",
    note: "Dormant branch-SKU snapshot retained for historical import only; it is not an active inventory authority.",
  },
  { table: "store_product_relation", key: ["id"], phase: "catalog" },
  { table: "store_product_attr", key: ["id"], phase: "catalog" },
  { table: "store_product_attr_result", key: ["id"], phase: "catalog" },
  { table: "store_product_attr_value", key: ["id"], phase: "catalog" },
  {
    table: "store_newcomer",
    key: ["id"],
    phase: "catalog",
    note: "Newcomer catalog rows retain source soft deletion and pricing; type=7 SKU rows map by suk to type=0 base SKUs, which remain the stock authority.",
  },
  { table: "store_product_unit", key: ["id"], phase: "catalog" },
  {
    table: "store_product_rule",
    key: ["id"],
    phase: "catalog",
    note: "Reusable SKU dimension templates remain distinct from per-product store_product_attr snapshots.",
  },
  {
    table: "store_product_specs",
    key: ["id"],
    phase: "catalog",
    note: "Parameter rows reference category(group=3) templates by temp_id; historical orphans are preserved for live review.",
  },
  {
    table: "store_product_virtual",
    key: ["id"],
    phase: "catalog",
    note: "Sensitive virtual-card inventory and historical assignment state; data is preserved exactly, while paid-order fulfillment claims cards only inside the retryable payment-outbox transaction.",
  },
  {
    table: "store_product_description",
    key: ["product_id", "type"],
    phase: "catalog",
    note: "The target unique index defines this logical key; live planning rejects source duplicates.",
  },
  { table: "store_product_stock_record", key: ["id"], phase: "catalog" },
  {
    table: "store_product_ensure",
    key: ["id"],
    phase: "catalog",
    note: "Assurance definitions remain separate from type=5 product relations and are shown on product detail pages.",
  },
  {
    table: "store_product_log",
    key: ["id"],
    phase: "catalog",
    note: "Append-only visit, cart, order, pay, collect and refund evidence; delete_time remains a nullable soft-delete timestamp.",
  },
  {
    table: "store_visit",
    key: ["id"],
    phase: "catalog",
    note: "The source has no user/product uniqueness constraint; historical duplicates remain importable while runtime updates serialize by scope.",
  },
  { table: "store_product_words", key: ["id"], phase: "catalog" },
  {
    table: "system_article",
    sourceTable: "article",
    key: ["id"],
    phase: "catalog",
    columnConversions: {
      cid: "numeric_string_to_integer",
      visit: "numeric_string_to_integer",
      add_time: "numeric_string_to_integer",
    },
    note: "Article body content is imported separately from PHP article_content and used as the fallback until a new-system edit mirrors it into both representations.",
  },
  {
    table: "article_category",
    key: ["id"],
    phase: "catalog",
    columnConversions: { add_time: "numeric_string_to_integer" },
  },
  {
    table: "article_content",
    key: ["nid"],
    phase: "catalog",
    note: "The PHP unique nid is promoted to the target primary key for deterministic one-to-one body import.",
  },
  {
    table: "system_dise",
    sourceTable: "diy",
    key: ["id"],
    phase: "catalog",
    note: "The TypeScript admin renamed DIY pages; every legacy visual-layout field remains separately represented.",
  },
  {
    table: "page_category",
    key: ["id"],
    phase: "catalog",
    note: "DIY page-link hierarchy remains source-shaped; runtime traversal starts at pid=0 and intentionally does not filter historical status values.",
  },
  {
    table: "page_link",
    key: ["id"],
    phase: "catalog",
    note: "Static and custom DIY navigation targets preserve historical duplicates and orphans; runtime writes validate category existence without inventing uniqueness.",
  },
  {
    table: "notification_template",
    sourceTable: "template_message",
    key: ["id"],
    phase: "catalog",
    columnMappings: {
      type: "legacy_type",
      tempkey: "mark",
      name: "title",
    },
    columnConversions: { add_time: "numeric_string_to_integer" },
    note: "Legacy numeric channel semantics are preserved in legacy_type while the Worker retains its textual type field.",
  },
  {
    table: "wechat_media",
    key: ["id"],
    phase: "catalog",
    note: "Legacy official-account media identifiers remain importable; 0071 never re-uploads local paths or invokes the external WeChat API.",
  },
  {
    table: "wechat_news_category",
    key: ["id"],
    phase: "catalog",
    note: "The comma-separated article IDs and varchar add_time remain source-shaped; runtime edits update owned article bodies atomically.",
  },
  {
    table: "wechat_reply",
    key: ["id"],
    phase: "catalog",
    note: "Reply JSON remains nullable source text; runtime writes validate text/image/news/voice snapshots and serialize the reply catalog.",
  },
  {
    table: "wechat_key",
    key: ["id"],
    phase: "catalog",
    note: "Historical duplicate keyword links remain importable; new Admin writes reject ambiguous keys inside a transaction.",
  },
  {
    table: "wechat_message",
    key: ["id"],
    phase: "catalog",
    note: "Inbound official-account history is imported for redacted Admin review; callback writes remain disabled until the complete listener graph is migrated.",
  },
  {
    table: "qrcode",
    key: ["id"],
    phase: "catalog",
    note: "Legacy official-account tickets retain the source unique (third_type, third_id) key; new permanent codes are provisioned asynchronously and retries upsert the same row.",
  },
  {
    table: "wechat_qrcode_cate",
    key: ["id"],
    phase: "catalog",
    note: "Channel-code categories preserve historical duplicate names; new active names are serialized and checked by the Admin service.",
  },
  {
    table: "wechat_qrcode",
    key: ["id"],
    phase: "catalog",
    note: "Channel reply snapshots, comma-separated label IDs and pre-generated image URLs remain source-shaped; no foreign keys are invented.",
  },
  {
    table: "wechat_qrcode_record",
    key: ["id"],
    phase: "catalog",
    note: "Every historical scan remains importable, including repeated users; Admin user lists deduplicate only at read time.",
  },
  {
    table: "work_channel_code",
    key: ["id"],
    phase: "catalog",
    note: "Contact-way configuration IDs and QR URLs are historical snapshots; imported rows never create, update, or delete remote Enterprise WeChat contact ways.",
  },
  {
    table: "work_channel_cycle",
    key: [],
    copyStrategy: "append_multiset",
    phase: "catalog",
    note: "Copied as a full-row multiset with the legacy wokr_time spelling retained; initial copy requires an empty target.",
  },
  {
    table: "work_channel_limit",
    key: [],
    copyStrategy: "append_multiset",
    phase: "catalog",
    note: "Copied as a full-row multiset so duplicate channel/member limits remain distinct; initial copy requires an empty target.",
  },
  {
    table: "work_group_chat_auth",
    key: ["id"],
    phase: "catalog",
    note: "Join-way QR configuration remains a local snapshot; remote create, update, and delete operations require an idempotent outbox before activation.",
  },
  {
    table: "work_media",
    key: ["id"],
    phase: "catalog",
    note: "Remote media identifiers are historical references. Import never uploads files or refreshes temporary media.",
  },
  {
    table: "work_welcome",
    key: ["id"],
    phase: "catalog",
    note: "Welcome-message payloads remain nullable source text; importing them does not send a message.",
  },
  {
    table: "work_welcome_relation",
    key: [],
    copyStrategy: "append_multiset",
    phase: "catalog",
    note: "Copied as a full-row multiset so duplicate welcome/member assignments are not collapsed; initial copy requires an empty target.",
  },

  {
    table: "queue_list",
    key: ["id", "type", "status"],
    phase: "commerce",
    note: "Legacy batch headers preserve the source composite primary key and Redis execution metadata for read-only diagnosis; Cloudflare Queues remain the execution authority.",
  },
  {
    table: "queue_auxiliary",
    key: ["id"],
    phase: "commerce",
    note: "Legacy per-item batch and delivery results remain importable without foreign keys; importing a row never retries external work.",
  },
  { table: "store_cart", key: ["id"], phase: "commerce" },
  {
    table: "express_company",
    sourceTable: "express",
    key: ["id"],
    phase: "commerce",
  },
  { table: "store_promotions", key: ["id"], phase: "commerce" },
  { table: "store_promotions_auxiliary", key: ["id"], phase: "commerce" },
  { table: "store_order", key: ["id"], phase: "commerce" },
  { table: "store_order_cart_info", key: ["id"], phase: "commerce" },
  {
    table: "store_order_economize",
    key: ["id"],
    phase: "commerce",
    note: "MySQL declares a composite primary key even though id is AUTO_INCREMENT; live planning verifies id uniqueness before copy and preserves the source order_id/uid unique rule.",
  },
  { table: "store_order_invoice", key: ["id"], phase: "commerce" },
  { table: "store_order_promotions", key: ["id"], phase: "commerce" },
  { table: "store_order_writeoff", key: ["id"], phase: "commerce" },
  { table: "store_delivery_order", key: ["id"], phase: "commerce" },
  {
    table: "delivery_service",
    key: ["id"],
    phase: "commerce",
    note: "Platform, store, and supplier delivery identities share one source table; historical duplicates remain importable while new active identities are scope-serialized.",
  },
  {
    table: "other_order",
    key: ["id"],
    phase: "commerce",
    note: "Membership purchase, free-trial, activation-card, cashier, and admin-grant records remain separate from merchandise orders.",
  },
  {
    table: "other_order_status",
    key: [],
    copyStrategy: "append_multiset",
    phase: "commerce",
    note: "Append-only membership-order status rows use the duplicate-preserving full-row multiset strategy and require an empty target on initial copy.",
  },
  {
    table: "store_integral_order",
    key: ["id"],
    phase: "commerce",
    note: "Historical pre-unification integral orders; current PHP and Worker writes use store_order type=4.",
  },
  {
    table: "store_integral_order_status",
    key: [],
    copyStrategy: "append_multiset",
    phase: "commerce",
    note: "Append-only historical status rows use the duplicate-preserving full-row multiset strategy and require an empty target on initial copy.",
  },
  {
    table: "store_order_status",
    key: [],
    copyStrategy: "append_multiset",
    phase: "commerce",
    note: "The PHP table has no primary key; full-row multiset copy preserves identical status rows instead of inventing a deduplication key.",
  },
  { table: "store_order_refund", key: ["id"], phase: "commerce" },
  { table: "store_product_reply", key: ["id"], phase: "commerce" },
  {
    table: "store_product_reply_comment",
    key: ["id"],
    phase: "commerce",
    columnMappings: { create_time: "add_time" },
  },
  { table: "store_service", key: ["id"], phase: "commerce" },
  {
    table: "store_service_feedback",
    key: ["id"],
    phase: "commerce",
    note: "User feedback remains a separate moderation inbox; content, processing status and operator note are preserved.",
  },
  {
    table: "store_service_speechcraft",
    key: ["id"],
    phase: "commerce",
    note: "Platform and per-customer-service quick replies retain their kefu/category scopes and historical duplicates.",
  },
  { table: "store_service_log", key: ["id"], phase: "commerce" },
  { table: "store_service_record", key: ["id"], phase: "commerce" },

  { table: "user_bill", key: ["id"], phase: "finance" },
  { table: "user_brokerage", key: ["id"], phase: "finance" },
  {
    table: "user_brokerage_frozen",
    key: ["id"],
    phase: "finance",
    note: "Deprecated PHP freeze evidence retained for historical import only; active Worker balances use user_brokerage.frozen_time and never double-count this table.",
  },
  { table: "user_extract", key: ["id"], phase: "finance" },
  { table: "user_money", key: ["id"], phase: "finance" },
  {
    table: "capital_flow",
    key: ["id"],
    phase: "finance",
    note: "Platform external cash movement; keep separate from user_bill internal balance/integral entries.",
  },
  {
    table: "store_finance_flow",
    key: ["id"],
    phase: "finance",
    note: "Dormant store ledger retained for history; do not merge into active platform or supplier finance tables.",
  },
  { table: "supplier_flowing_water", key: ["id"], phase: "finance" },
  { table: "supplier_transactions", key: ["id"], phase: "finance" },
  { table: "supplier_extract", key: ["id"], phase: "finance" },
  {
    table: "store_extract",
    key: ["id"],
    phase: "finance",
    note: "Dormant store withdrawal history retained without merging it into active supplier or user finance flows.",
  },

  {
    table: "store_coupon_issue",
    key: ["id"],
    phase: "activity",
    columnMappings: {
      type: "coupon_type",
      coupon_type: "type",
      coupon_time: "day",
      product_id: "legacy_product_ids",
      category_id: "legacy_category_id",
      brand_id: "legacy_brand_id",
      start_use_time: "use_start_time",
      end_use_time: "use_end_time",
    },
    note: "PHP type is scope and coupon_type is discount mode; preserve fixed-use timestamps separately from the claim window.",
  },
  {
    table: "store_coupon_user",
    key: ["id"],
    phase: "activity",
    columnMappings: {
      cid: "issue_coupon_id",
      add_time: "receive_time",
      type: "receive_source",
    },
    note: "Preserve the PHP acquisition method separately from the Worker numeric coupon type snapshot.",
  },
  {
    table: "store_coupon_issue_user",
    key: [],
    copyStrategy: "append_multiset",
    phase: "activity",
    note: "The keyless claim-evidence table is copied as a full-row multiset so duplicate rows are preserved; initial copy requires an empty target.",
  },
  {
    table: "store_coupon_product",
    key: [],
    copyStrategy: "append_multiset",
    phase: "activity",
    note: "The keyless coupon-scope relation is copied as a full-row multiset so duplicate rows are preserved; initial copy requires an empty target.",
  },
  {
    table: "store_product_coupon",
    key: ["id"],
    phase: "activity",
    note: "Product-to-issue links drive transactional post-payment coupon grants; duplicate links remain distinct source rows.",
  },
  { table: "store_discounts", key: ["id"], phase: "activity" },
  { table: "store_discounts_products", key: ["id"], phase: "activity" },
  { table: "store_activity", key: ["id"], phase: "activity" },
  { table: "store_activity_relation", key: ["id"], phase: "activity" },
  {
    table: "store_seckill",
    key: ["id"],
    phase: "activity",
    columnMappings: { title: "store_name" },
    columnConversions: {
      start_time: "epoch_string_to_timestamp",
      stop_time: "epoch_string_to_timestamp",
      add_time: "numeric_string_to_integer",
    },
  },
  { table: "store_seckill_time", key: ["id"], phase: "activity" },
  {
    table: "store_combination",
    key: ["id"],
    phase: "activity",
    columnMappings: { title: "store_name" },
    columnConversions: { add_time: "numeric_string_to_integer" },
  },
  {
    table: "store_pink",
    key: ["id"],
    phase: "activity",
    columnMappings: { cid: "combination_id", pid: "product_id" },
    columnConversions: {
      add_time: "numeric_string_to_integer",
      stop_time: "epoch_string_to_timestamp",
    },
    note: "PHP declares epoch seconds as varchar; preflight validates numeric strings before explicit conversion.",
  },
  {
    table: "store_bargain",
    key: ["id"],
    phase: "activity",
    columnMappings: { people_num: "people" },
  },
  { table: "store_bargain_user", key: ["id"], phase: "activity" },
  {
    table: "store_bargain_user_help",
    key: ["id"],
    phase: "activity",
    note: "Historical duplicate helper-participation rows remain importable; runtime writes prevent new duplicates under a participation lock.",
  },
  {
    table: "store_integral",
    key: ["id"],
    phase: "activity",
    columnMappings: { title: "store_name" },
    columnConversions: { add_time: "numeric_string_to_integer" },
  },
  {
    table: "work_group_chat",
    key: ["id"],
    phase: "activity",
    note: "Enterprise group snapshots are Admin-only and never authorize public group access or remote synchronization.",
  },
  { table: "work_group_chat_member", key: ["id"], phase: "activity" },
  { table: "work_group_chat_statistic", key: ["id"], phase: "activity" },
  {
    table: "work_group_msg_relation",
    key: [],
    copyStrategy: "append_multiset",
    phase: "activity",
    note: "Template/message relations use full-row multiset copy so duplicates remain distinct; initial copy requires an empty target.",
  },
  { table: "work_group_msg_send_result", key: ["id"], phase: "activity" },
  { table: "work_group_msg_task", key: ["id"], phase: "activity" },
  {
    table: "work_group_template",
    key: ["id"],
    phase: "activity",
    note: "Imported group-send templates and delivery failures are read-only history; they never enqueue or poll a remote send.",
  },
  {
    table: "work_moment",
    key: ["id"],
    phase: "activity",
    note: "Imported moment tasks retain remote job and moment IDs as history; scheduling and polling stay disabled until durable idempotency exists.",
  },
  { table: "work_moment_send_result", key: ["id"], phase: "activity" },
  {
    table: "live_anchor",
    key: ["id"],
    phase: "activity",
    note: "Mini-program anchor identities remain source-shaped; no uniqueness is invented for wechat or phone, and runtime synchronization only reads the remote role catalog.",
  },
  {
    table: "live_goods",
    key: ["id"],
    phase: "activity",
    note: "Remote goods and audit identifiers remain local snapshots; scheduled synchronization is read-only toward WeChat and external create/audit/delete operations stay disabled until an idempotent outbox protocol exists.",
  },
  {
    table: "live_room",
    key: ["id", "phone"],
    phase: "activity",
    note: "Uses the exact source (id, phone) primary key. Mixed integer/text keyset pagination compares phone in binary UTF-8 order and checkpoints both values; no assumption that id alone is unique is required.",
  },
  {
    table: "live_room_goods",
    key: [],
    copyStrategy: "append_multiset",
    phase: "activity",
    note: "The non-unique room/goods relation uses full-row multiset copy so duplicate evidence is preserved; initial copy requires an empty target.",
  },
  { table: "luck_lottery", key: ["id"], phase: "activity" },
  { table: "luck_prize", key: ["id"], phase: "activity" },
  {
    table: "luck_lottery_record",
    key: ["id"],
    phase: "activity",
    note: "Prize and delivery snapshots remain source text so historical JSON and non-JSON values stay importable.",
  },
  { table: "community_topic", key: ["id"], phase: "activity" },
  { table: "community_user", key: ["id"], phase: "activity" },
  { table: "community", key: ["id"], phase: "activity" },
  { table: "community_comment", key: ["id"], phase: "activity" },
  {
    table: "community_relevance",
    key: ["id"],
    phase: "activity",
    note: "Preserve the PHP polymorphic type strings; legacy duplicate triples remain visible for live-data review instead of being silently collapsed.",
  },
  {
    table: "shipping_templates",
    key: ["id"],
    phase: "activity",
    columnMappings: {
      type: "owner_type",
      group: "type",
    },
    note: "PHP type is the owner scope; PHP group is the billing mode used by the Worker type column.",
  },
  {
    table: "shipping_templates_region",
    key: ["id"],
    phase: "activity",
    columnMappings: {
      temp_id: "template_id",
      city_id: "region_id",
      group: "billing_group",
    },
    note: "Preserve legacy province/city grouping while leaving Worker-only region_name at its default.",
  },
  { table: "shipping_templates_free", key: ["id"], phase: "activity" },
  { table: "shipping_templates_no_delivery", key: ["id"], phase: "activity" },
  { table: "user_notice", key: ["id"], phase: "activity" },
  { table: "user_notice_see", key: ["id"], phase: "activity" },
  { table: "system_log", key: ["id"], phase: "activity" },
  {
    table: "system_message",
    key: ["id"],
    phase: "activity",
    columnMappings: { uid: "user_id" },
  },
  {
    table: "user_enter",
    key: ["id"],
    phase: "identity",
    note: "Superseded merchant-application history. system_user_apply owns the current workflow; imported rows remain read-only and the source uid uniqueness is preserved by schema.",
  },
  {
    table: "wechat_card",
    key: ["id"],
    phase: "catalog",
    note: "Official-account member-card configuration and remote IDs are imported as read-only history; import never creates, updates, or queries a remote WeChat card.",
  },
  {
    table: "user_card",
    key: ["id"],
    phase: "activity",
    note: "Sensitive member-card codes and openids are preserved for migration but only exposed through masked admin diagnostics; callback replay and remote activation stay disabled.",
  },
] as const;

export const MIGRATION_MANIFEST_VERSION = "2026-08-11.57";
