<template><view class="delivery-card" data-delivery="quantity-panel"><text class="delivery-label">{{ preview.product_type===4?'次卡核销数量':'本次送达商品' }}</text><text v-if="!preview.actions.writeoff.available" class="delivery-reason">{{ preview.actions.writeoff.reason||'当前订单不能确认送达' }}</text><text class="delivery-muted">订单 {{ preview.order_id }} · 请核对商品及实际送达数量</text><view v-for="cart in preview.cart_info" :key="cart.id" class="delivery-cart"><view class="delivery-check" :class="{on:!!quantities[cart.id]}" @tap="toggle(cart)">{{ quantities[cart.id]?'✓':'' }}</view><image v-if="cart.cart_info.productInfo.attrInfo.image||cart.cart_info.productInfo.image" :src="userCenterMedia(cart.cart_info.productInfo.attrInfo.image||cart.cart_info.productInfo.image)" class="delivery-cart-image" mode="aspectFill" /><view class="delivery-cart-copy"><text>{{ cart.cart_info.productInfo.store_name }} <text v-if="cart.is_gift" class="delivery-status">赠品</text></text><text class="delivery-muted">{{ cart.cart_info.productInfo.attrInfo.suk }} · ¥{{ cart.cart_info.productInfo.attrInfo.price }}</text><text>订单数量 {{ cart.cart_num }} · 总次数 {{ cart.write_times }} · 已核销 {{ cart.write_times-cart.write_surplus_times }} · 剩余 {{ cart.write_surplus_times }}</text><text v-if="cart.write_start||cart.write_end" class="delivery-muted">有效期 {{ deliveryDate(cart.write_start)||'未设置起始日期' }} 至 {{ deliveryDate(cart.write_end)||'未设置截止日期' }}</text><text v-if="reason(cart)" class="delivery-reason">{{ reason(cart) }}</text><view class="delivery-quantity"><button :disabled="!editable(cart)||!quantities[cart.id]" @tap="adjust(cart,-1)">−</button><input type="number" :value="quantities[cart.id]||0" :disabled="!editable(cart)" maxlength="8" @input="quantityInput(cart,$event)" /><button :disabled="!editable(cart)||(quantities[cart.id]||0)>=cart.write_surplus_times" @tap="adjust(cart,1)">＋</button></view></view></view><view class="delivery-controls"><button :disabled="!preview.actions.writeoff.available||controller.busy.value||freshRequired" @tap="selectAll">{{ allSelected?'取消全选':'全选可核销商品' }}</button><text>本次共 {{ total }} 件 / 次</text></view><text v-if="localError" class="delivery-reason">{{ localError }}</text><text v-if="freshRequired" class="delivery-warning">本次操作已有确认结果。继续核销前请重新读取当前订单与剩余数量。</text><button :disabled="!preview.actions.writeoff.available||!total||controller.busy.value||freshRequired" class="delivery-full-button" @tap="submit">确认本次送达</button></view></template>
<script setup lang="ts">
import {computed,ref,watch,onMounted,onBeforeUnmount} from 'vue';import {userCenterMedia} from '@/utils/userCenter';import {deliveryCartReason,deliveryDate,deliveryInt} from '@/utils/deliveryWorkbench';import type {DeliveryController} from '@/composables/useDeliveryWorkbench';import type {DeliveryWriteoffPreview,DeliveryWriteoffCart,DeliveryOperationInput} from '@/types/deliveryWorkbench';
const props=defineProps<{controller:DeliveryController;preview:DeliveryWriteoffPreview;freshRequired?:boolean}>(),emit=defineEmits<{(event:'confirmed',outcome:string):void;(event:'expired'):void}>(),quantities=ref<Record<number,number>>({}),localError=ref(''),clock=ref(Math.floor(Date.now()/1000));let timer:ReturnType<typeof setInterval>|undefined;
const reason=(cart:DeliveryWriteoffCart)=>deliveryCartReason(cart,clock.value);function editable(cart:DeliveryWriteoffCart){return props.controller.current()&&props.preview.actions.writeoff.available&&!props.controller.busy.value&&!props.freshRequired&&!reason(cart);}
const total=computed(()=>Object.values(quantities.value).reduce((sum,value)=>sum+value,0)),allSelected=computed(()=>props.preview.cart_info.filter(cart=>!reason(cart)).every(cart=>quantities.value[cart.id]===cart.write_surplus_times));
function toggle(cart:DeliveryWriteoffCart){if(!editable(cart))return;quantities.value[cart.id]=quantities.value[cart.id]?0:1;localError.value='';}function adjust(cart:DeliveryWriteoffCart,delta:number){if(!editable(cart))return;quantities.value[cart.id]=Math.max(0,Math.min(cart.write_surplus_times,(quantities.value[cart.id]||0)+delta));localError.value='';}
function setQuantity(cart:DeliveryWriteoffCart,value:string){if(!editable(cart))return;if(!/^\d{1,8}$/u.test(value)||!deliveryInt(Number(value))||Number(value)>cart.write_surplus_times){localError.value='数量必须是剩余范围内的整数';quantities.value[cart.id]=0;return;}quantities.value[cart.id]=Number(value);localError.value='';}
function quantityInput(cart:DeliveryWriteoffCart,event:unknown){const value=(event as {detail?:{value?:unknown}})?.detail?.value;setQuantity(cart,String(value??''));}
function selectAll(){if(!props.preview.actions.writeoff.available||props.controller.busy.value||props.freshRequired)return;const clear=allSelected.value;quantities.value=Object.fromEntries(props.preview.cart_info.filter(cart=>!reason(cart)).map(cart=>[cart.id,clear?0:cart.write_surplus_times]));localError.value='';}
async function submit(){localError.value='';if(props.freshRequired)return;const authority=props.controller.context.value,scope=props.controller.selected.value;if(!authority||!scope||!props.preview.actions.writeoff.available)return;const items=props.preview.cart_info.filter(cart=>quantities.value[cart.id]>0).map(cart=>({order_cart_id:cart.id,quantity:quantities.value[cart.id]!}));if(!items.length){localError.value='请选择本次实际送达的商品及数量';return;}if(items.some(item=>{const cart=props.preview.cart_info.find(cart=>cart.id===item.order_cart_id)!;return !!reason(cart)||!deliveryInt(item.quantity,1)||item.quantity>cart.write_surplus_times;})){localError.value='商品数量或有效时间已变化，请重新读取';return;}
  const body:DeliveryOperationInput={version:'delivery-writeoff-operation-v1',scope_kind:scope.kind,delivery_id:scope.delivery_id,store_id:scope.store_id,scope_key:authority.scope_key,order_id:props.preview.id,expected_order_revision:props.preview.revision,payload:{code:props.preview.verify_code,items}};
  try{const receipt=await props.controller.execute(body,props.preview.actions.writeoff);if(receipt&&['partial-delivered','delivered'].includes(receipt.outcome)){quantities.value={};emit('confirmed',receipt.outcome);}}catch(failure){if(props.controller.current())localError.value=failure instanceof Error?failure.message:'原操作结果需核对';}
}
watch(()=>props.preview.revision,()=>{quantities.value={};localError.value='';},{flush:'sync'});watch(clock,(now,before)=>{for(const cart of props.preview.cart_info)if(reason(cart))quantities.value[cart.id]=0;const crossed=props.preview.cart_info.some(cart=>cart.write_start>before&&cart.write_start<=now||cart.write_end>=before&&cart.write_end<now);if(crossed&&!props.freshRequired&&!props.controller.pending.value.some(intent=>intent.body.order_id===props.preview.id)){quantities.value={};emit('expired');}},{flush:'sync'});onMounted(()=>{timer=setInterval(()=>{clock.value=Math.floor(Date.now()/1000);},1000);});onBeforeUnmount(()=>{if(timer)clearInterval(timer);});
</script>
