<template><MerchantShell title="门店订单管理" :manager="manager"><view class="merchant-card"><view class="merchant-controls"><input v-model="keyword" maxlength="128" placeholder="电话 / 昵称 / 订单号 / 商品名称" @confirm="search" /><button @tap="search">搜索</button></view><view class="merchant-tabs"><button v-for="tab in tabs" :key="String(tab.status)" :class="{active:status===tab.status}" @tap="chooseStatus(tab.status)">{{ tab.name }}</button></view><view class="merchant-controls"><picker :range="dateLabels" :value="dateIndex" @change="changeDate"><view>日期：{{ dateLabels[dateIndex] }} ⌄</view></picker><picker :range="paymentLabels" :value="paymentIndex" @change="changePayment"><view>付款：{{ paymentLabels[paymentIndex] }} ⌄</view></picker></view><text class="merchant-muted">当前筛选共 {{ total }} 笔订单</text></view><view v-for="order in orders" :key="order.id" class="merchant-card" data-merchant="order-card"><view class="merchant-order-header merchant-click" @tap="openDetail(order)"><view class="merchant-stack"><text class="strong">{{ order.order_id }}</text><text class="merchant-muted">{{ order._add_time }} · {{ order.type_name }}</text></view><text class="merchant-status">{{ order._status._title }}</text></view><view class="merchant-divider" /><MerchantCart v-for="cart in order.cartInfo" :key="cart.id" :cart="cart" /><view class="merchant-row"><text>共 {{ order.total_num }} 件</text><text class="merchant-money">实付 ¥{{ order.pay_price }}</text></view><text v-if="order.is_all_refund" class="merchant-muted">全部退款</text><text v-else-if="order.refund.length" class="merchant-muted">包含部分退款申请</text><MerchantActions :item="order" :capabilities="manager.context.value?.data.capabilities" :busy="manager.busy.value" @action="action => openAction(order,action)" /><button class="merchant-full-button" :disabled="status===-4" @tap="openDetail(order)">{{ status===-4 ? '已删除订单仅保留列表记录' : '查看完整详情' }}</button></view><view v-if="!orders.length" class="merchant-empty">当前筛选暂无订单</view><button v-if="hasMore" class="merchant-full-button" :disabled="paging" @tap="more">{{ paging ? '读取中…' : '加载更多订单' }}</button><MerchantOperationPanel v-if="editing" :manager="manager" :order="editing" :action="editingAction" @close="editing=null" @saved="saved" /></MerchantShell></template>
<script setup lang="ts">
import { ref } from 'vue';import { onReachBottom } from '@dcloudio/uni-app';
import MerchantShell from '@/components/merchantOrders/MerchantShell.vue';import MerchantCart from '@/components/merchantOrders/MerchantCart.vue';import MerchantActions from '@/components/merchantOrders/MerchantActions.vue';import MerchantOperationPanel from '@/components/merchantOrders/MerchantOperationPanel.vue';
import { useMerchantOrders } from '@/composables/useMerchantOrders';import { isMerchantOrder,isMerchantPaged,merchantDateRange } from '@/utils/merchantOrders';import type { MerchantOrderListItem,MerchantOrderAction,MerchantOrderSelector } from '@/types/merchantOrders';
const orders=ref<MerchantOrderListItem[]>([]),status=ref<MerchantOrderSelector>(''),keyword=ref(''),dateIndex=ref(0),paymentIndex=ref(0),total=ref(0),hasMore=ref(false),paging=ref(false),editing=ref<MerchantOrderListItem|null>(null),editingAction=ref<MerchantOrderAction>('remark');let page=1;
const tabs=[{name:'全部',status:'' as const},{name:'待付款',status:0 as const},{name:'待发货',status:1 as const},{name:'待收货 / 核销',status:2 as const},{name:'待评价',status:3 as const},{name:'已完成',status:4 as const},{name:'待核销',status:5 as const},{name:'已核销',status:6 as const},{name:'部分发货',status:7 as const},{name:'自提订单',status:8 as const},{name:'已收货',status:9 as const},{name:'退款中',status:-1 as const},{name:'已退款',status:-2 as const},{name:'全部售后',status:-3 as const},{name:'已删除',status:-4 as const}],dateLabels=['全部日期','三天内','一个月内','三个月内','半年内'],paymentLabels=['全部支付方式','微信','支付宝','余额','线下'],paymentValues=['','1','4','2','3'];
const filters=()=>({status:status.value,is_del:status.value===-4?1:0,keyword:keyword.value.trim(),data:merchantDateRange(dateIndex.value),pay_type:paymentValues[paymentIndex.value],page,limit:10});
const manager=useMerchantOrders({query(query){const raw=query.status??query.types;if(raw!==undefined&&raw!==''&&Number.isInteger(Number(raw))&&Number(raw)>=-4&&Number(raw)<=9)status.value=Number(raw) as MerchantOrderSelector;},clear(){orders.value=[];total.value=0;hasMore.value=false;paging.value=false;editing.value=null;page=1;},async load(controller){const valid=controller.fence(),rows=await controller.read('list',isMerchantPaged(isMerchantOrder),filters());if(!valid())return;if(rows.data.page!==1)throw Error('订单分页响应不匹配');orders.value=rows.data.list;total.value=rows.data.count;hasMore.value=rows.data.has_more;}});
function search(){if(!manager.loading.value)void manager.load();}function chooseStatus(value:MerchantOrderSelector){status.value=value;search();}function changeDate(event:{detail:{value:string|number}}){dateIndex.value=Number(event.detail.value);search();}function changePayment(event:{detail:{value:string|number}}){paymentIndex.value=Number(event.detail.value);search();}
function openAction(order:MerchantOrderListItem,action:MerchantOrderAction){if(!order.actions[action].available||!manager.context.value?.data.capabilities[action]||manager.busy.value)return;if(action==='manual_delivery')manager.go('delivery',{orderId:order.order_id});else if(action==='tracking')manager.go('logistics',{orderId:order.order_id});else if(action==='writeoff'){manager.operationError.value='请以独立核销身份进入核销工作台，当前管理身份不授予核销权限。';}else{editing.value=order;editingAction.value=action;}}
function openDetail(order:MerchantOrderListItem){if(status.value!==-4)manager.go('orderDetail',{orderId:order.order_id});}function saved(){editing.value=null;void manager.load();}
async function more(){if(paging.value||!hasMore.value||manager.loading.value)return;paging.value=true;const valid=manager.fence();try{const rows=await manager.read('list',isMerchantPaged(isMerchantOrder),{...filters(),page:page+1});if(!valid())return;if(rows.data.page!==page+1||rows.data.list.some(row=>orders.value.some(old=>old.id===row.id)))throw Error('订单分页数据已变化，请重新读取');orders.value.push(...rows.data.list);page++;total.value=rows.data.count;hasMore.value=rows.data.has_more;}catch(failure){if(valid()){orders.value=[];manager.error.value=failure instanceof Error?failure.message:'分页读取失败';}}finally{if(valid())paging.value=false;}}onReachBottom(()=>{void more();});
</script>
