<template><MerchantShell title="门店经营统计" :manager="manager"><view class="merchant-warning">本页按当前门店履约订单统计，包含拆单子订单，不含拆单支付头。个人中心的三张卡为订单汇总。</view><view class="merchant-controls"><picker :range="periodLabels" :value="periodIndex" @change="changePeriod"><view class="merchant-card">统计周期：{{ periodLabels[periodIndex] }} ⌄</view></picker><button @tap="manager.go('orders')">管理订单</button></view><view v-if="period" class="merchant-card"><text class="merchant-subtitle">已支付订单金额</text><text class="merchant-amount">¥{{ period.after_price }}</text><view class="merchant-divider" /><text>{{ period.increase_time }} {{ period.increase_time_status === 1 ? '增长' : '下降' }} {{ period.growth_rate }}%</text></view><view v-if="period" class="merchant-grid"><view class="merchant-metric"><text class="merchant-amount">{{ period.after_number }}</text><text>已支付订单数</text></view><view class="merchant-metric"><text class="merchant-amount">{{ period.after_pay_number }}</text><text>付款人数</text></view><view class="merchant-metric"><text class="merchant-amount">{{ period.today_visits }}</text><text>门店商品访问量</text></view></view><view class="merchant-card" style="margin-top:24rpx"><text class="merchant-subtitle">销售金额趋势</text><view v-if="chart.length" class="merchant-chart" data-merchant="trend"><view v-for="point in chart" :key="point.date" class="merchant-chart-column"><view class="merchant-chart-bar" :style="{height:barHeight(point.price)}" /><text class="merchant-chart-label">{{ point.time }}</text></view></view><view v-else class="merchant-muted">暂无趋势数据</view><view v-for="point in chart" :key="`price-${point.date}`" class="merchant-row merchant-muted"><text>{{ point.date }}</text><text>¥{{ point.price }} · {{ point.num }} 单</text></view></view><view v-if="summary" class="merchant-card"><text class="merchant-subtitle">当前门店订单</text><view class="merchant-grid"><view v-for="card in summaryCards" :key="card.label" class="merchant-metric merchant-click" @tap="manager.go('orders',{status:card.status})"><text class="merchant-amount">{{ card.count }}</text><text>{{ card.label }}</text></view></view></view><view class="merchant-card"><text class="merchant-subtitle">本月每日明细</text><view class="merchant-table-row merchant-table-head"><text>日期</text><text>订单数</text><text>销售额</text><text>商品访问</text></view><view v-for="row in daily" :key="row.date" class="merchant-table-row"><text>{{ row.time }}</text><text>{{ row.count }}</text><text>¥{{ row.price }}</text><text>{{ row.visit }}</text></view><text v-if="!daily.length" class="merchant-muted">本月暂无明细</text><button v-if="hasMore" class="merchant-full-button" :disabled="paging" @tap="more">{{ paging ? '读取中…' : '加载更多明细' }}</button></view></MerchantShell></template>
<script setup lang="ts">
import { computed,ref } from 'vue';
import MerchantShell from '@/components/merchantOrders/MerchantShell.vue';
import { useMerchantOrders } from '@/composables/useMerchantOrders';
import { isMerchantStatistics,isMerchantPeriod,isMerchantChart,isMerchantDaily,isMerchantPaged } from '@/utils/merchantOrders';
import type { MerchantOrderStatistics,MerchantOrderPeriod,MerchantOrderChartPoint,MerchantOrderDailyRow } from '@/types/merchantOrders';
const summary=ref<MerchantOrderStatistics|null>(null),period=ref<MerchantOrderPeriod|null>(null),chart=ref<MerchantOrderChartPoint[]>([]),daily=ref<MerchantOrderDailyRow[]>([]),periodIndex=ref(0),hasMore=ref(false),paging=ref(false);let page=1;
const periodLabels=['今天','近 7 天','近 30 天'],periodValues=[1,7,30];
const manager=useMerchantOrders({clear(){summary.value=null;period.value=null;chart.value=[];daily.value=[];hasMore.value=false;paging.value=false;page=1;},async load(controller){
  const valid=controller.fence();
  const [stats,time,trend,rows]=await Promise.all([controller.read('statistics',isMerchantStatistics),controller.read('time',isMerchantPeriod,{type:periodValues[periodIndex.value]}),controller.read('time/chart',isMerchantChart,{type:periodValues[periodIndex.value]}),controller.read('data',isMerchantPaged(isMerchantDaily),{page:1,limit:15})]);
  if(!valid())return;if(time.data.type!==periodValues[periodIndex.value]||rows.data.page!==1)throw Error('统计周期响应不匹配，请重新读取');summary.value=stats.data;period.value=time.data;chart.value=trend.data;daily.value=rows.data.list;hasMore.value=rows.data.has_more;
}});
const summaryCards=computed(()=>{const stats=summary.value;return stats?[{label:'待付款',status:0,count:stats.unpaid_count},{label:'待发货',status:1,count:stats.unshipped_count},{label:'待收货',status:2,count:stats.received_count},{label:'待评价',status:3,count:stats.evaluated_count},{label:'待核销',status:5,count:stats.unwritoff_count},{label:'退款中',status:-1,count:stats.refunding_count}]:[];});
function changePeriod(event:{detail:{value:string|number}}){const index=Number(event.detail.value);if(index<0||index>2||manager.loading.value)return;periodIndex.value=index;void manager.load();}
function barHeight(price:string){const maximum=Math.max(...chart.value.map(point=>Number(point.price)),1);return `${Math.max(1,Number(price)/maximum*85)}%`;}
async function more(){if(paging.value||!hasMore.value)return;paging.value=true;const valid=manager.fence();try{const rows=await manager.read('data',isMerchantPaged(isMerchantDaily),{page:page+1,limit:15});if(!valid())return;if(rows.data.page!==page+1||rows.data.list.some(row=>daily.value.some(old=>old.date===row.date)))throw Error('分页结果已变化，请重新读取');daily.value.push(...rows.data.list);page++;hasMore.value=rows.data.has_more;}catch(failure){if(valid()){daily.value=[];manager.error.value=failure instanceof Error?failure.message:'分页读取失败';}}finally{if(valid())paging.value=false;}}
</script>
