<template><view class="cw-dialog" data-financial-dialog="editor"><view class="cw-dialog-panel"><text class="cw-subtitle">{{ CUSTOMER_FINANCIAL_NAMES[props.kind] }}</text><text class="cw-scope">订单 {{ props.basis.order_no }}<template v-if="'refund_no'in props.basis"> · 申请 {{ props.basis.refund_no }}</template></text><view v-if="props.kind==='change_price'" class="cw-form-field"><text>修改后的实付款（元）</text><input v-model="amount" type="digit" maxlength="13" placeholder="最多两位小数，可为零" /><text class="cw-muted">当前金额 ¥{{ 'pay_price'in props.basis?props.basis.pay_price:'' }}。确认后修改当前未支付订单。</text></view><view v-else-if="props.kind==='confirm_offline'"><text class="cw-scope">确认线下收款后会更新真实订单与账务，请先核对实际款项。</text><view class="cw-quantity"><checkbox :checked="received" @tap="received=!received" /><text>我已实际收到本订单款项</text></view></view><view v-else-if="props.kind==='refund_remark'" class="cw-form-field"><text>退款管理备注</text><textarea v-model="remark" :maxlength="510" placeholder="填写 1 至 255 字的备注" /></view><template v-else><text v-if="props.kind==='refund_return'" class="cw-scope">同意退货只确认申请，收到并验收商品后还需另行执行资金退款。</text><view v-if="props.kind==='refund_execute'" class="cw-form-field"><text>本申请确认退款金额（元）</text><input v-model="amount" type="digit" maxlength="13" /><text class="cw-muted">须与本申请已核对金额 ¥{{ 'refund_price'in props.basis?props.basis.refund_price:'' }} 一致。其他金额请重新核对商品数量并创建独立申请。</text></view><view v-if="props.kind==='refund_execute'&&'requires_received_confirmation'in props.basis&&props.basis.requires_received_confirmation" class="cw-quantity"><checkbox :checked="received" @tap="received=!received" /><text>我已实际收到并验收此次退货商品</text></view><view v-if="props.kind==='refund_refuse'" class="cw-form-field"><text>拒绝退款原因</text><textarea v-model="reason" :maxlength="510" placeholder="填写 1 至 255 字的拒绝原因" /></view><text v-if="props.kind==='refund_execute'" class="cw-scope">渠道“已受理”不代表款项已退回，资金结果以原操作核验为准。</text></template><text v-if="error" class="cw-error">{{ error }}</text><view class="cw-dialog-buttons"><button :disabled="props.operations.busy.value" @tap="emit('close')">取消</button><button :disabled="props.operations.busy.value||!props.basis.readiness.writes||!props.basis.actions[props.kind].available" @tap="save">{{ props.operations.busy.value?'处理中…':'核对并提交' }}</button></view></view></view></template>
<script setup lang="ts">
import {ref,watch} from 'vue';
import type {CustomerFinancialOperations} from '@/composables/useCustomerWorkFinancialOperations';
import type {CustomerFinancialOrder,CustomerFinancialRefundReview,CustomerFinancialKind,CustomerFinancialJson,CustomerFinancialResult} from '@/types/customerWorkFinancial';
import {CUSTOMER_FINANCIAL_NAMES,financialAmount,financialReason,customerFinancialNotice} from '@/utils/customerWorkFinancial';
const props=defineProps<{operations:CustomerFinancialOperations;kind:Exclude<CustomerFinancialKind,'refund_create'>;basis:CustomerFinancialOrder|CustomerFinancialRefundReview}>(),emit=defineEmits<{close:[];saved:[result:CustomerFinancialResult]}>();
const amount=ref(''),reason=ref(''),remark=ref(''),received=ref(false),error=ref('');
watch([()=>props.kind,()=>props.basis.order_id,()=>props.basis.order_revision,()=>props.basis.financial_revision,()=>('refund_id'in props.basis?props.basis.refund_id:0),()=>('refund_revision'in props.basis?props.basis.refund_revision:'')],()=>{amount.value=props.kind==='change_price'&&'pay_price'in props.basis?props.basis.pay_price:props.kind==='refund_execute'&&'refund_price'in props.basis?props.basis.refund_price:'';remark.value='remark'in props.basis?props.basis.remark:'';reason.value='';received.value=false;error.value='';},{immediate:true});
async function save(){if(props.operations.busy.value)return;error.value='';try{let payload:Record<string,CustomerFinancialJson>={};const basis=props.basis;
 if(props.kind==='change_price')payload={price:financialAmount(amount.value)};
 else if(props.kind==='confirm_offline'){if(!received.value)throw Error('请先确认已实际收到本订单款项');}
 else{if(!('refund_id'in basis))throw Error('请重新读取当前退款申请');payload={refund_id:basis.refund_id,refund_no:basis.refund_no,expected_refund_revision:basis.refund_revision,review_fingerprint:basis.review_fingerprint};if(props.kind==='refund_remark')payload.remark=financialReason(remark.value);else{payload.decision={apply_type:basis.apply_type,refund_type:basis.refund_type,received:received.value};if(props.kind==='refund_refuse')payload.reason=financialReason(reason.value);if(props.kind==='refund_execute'){if(basis.requires_received_confirmation&&!received.value)throw Error('请先实际收到并验收退货商品，再勾选确认');const price=financialAmount(amount.value);if(price!==basis.refund_price)throw Error('执行金额须与本申请已核对金额一致，其他金额请创建独立申请');payload.refund_price=price;}}}
 const result=await props.operations.submit(props.kind,basis,payload);if(!props.operations.current())return;if(result?.receipt&&!['rollback-rejected','abandoned'].includes(result.receipt.outcome))emit('saved',result);else error.value=props.operations.error.value||'原结果尚未确认，请查询原操作。';
 }catch(failure){if(props.operations.current())error.value=failure instanceof Error?customerFinancialNotice(failure.message):'财务编辑内容需核对';}}
</script>
