<template><view v-show="props.visible" class="cw-dialog" role="dialog" :aria-label="props.mode==='grant'?'赠送优惠券':'用户优惠券'" @tap.self="emit('close')"><view class="cw-dialog-panel"><text class="cw-subtitle">{{ props.mode==='grant'?'赠送优惠券':'用户优惠券' }}</text><text class="cw-scope">{{ props.mode==='grant'?`向已核对的 ${props.targetIds.length} 位用户赠送；按优惠券发放记录与当前余量确认。`:`UID ${props.uid} · 未使用券记录与实际可用状态分别显示。` }}</text>
 <view v-if="props.mode==='grant'" class="cw-controls"><input v-model="keyword" placeholder="搜索优惠券标题" aria-label="优惠券搜索" :disabled="props.operations.busy.value" confirm-type="search" @confirm="search" /><button :disabled="props.operations.busy.value" @tap="search">搜索</button></view><text v-if="error" class="cw-error" role="alert">{{ error }}</text><view v-if="loading&&!rows.length" class="cw-empty">正在读取优惠券…</view>
 <view v-for="row in rows" :key="row.id" class="cw-card"><text class="cw-subtitle">{{ row.coupon_title }}</text><text class="cw-scope">{{ row.type===1?'金额优惠':'折扣优惠' }} · {{ scopeName(row.coupon_type) }}</text><view class="cw-row"><text>{{ row.type===1?'优惠金额':'折扣值' }}</text><text>{{ row.coupon_price }}</text></view><text class="cw-muted">最低消费 ¥{{ row.use_min_price }}</text>
  <template v-if="isCandidate(row)"><text class="cw-muted">{{ row.is_permanent?'不限发行数量':`剩余 ${row.remain_count}/${row.total_count}` }} · {{ row.coupon_time }}</text><text v-if="row.action.reason" class="cw-error">{{ customerWorkUserNotice(row.action.reason,'coupon') }}</text><button :disabled="!row.action.available||props.operations.busy.value||loading" @tap="grant(row)">赠送这张券</button></template><template v-else><text class="cw-status">{{ availabilityName(row.availability) }}</text><text class="cw-muted">{{ customerWorkUserNotice(row.availability_message,'coupon') }}</text><text class="cw-muted">使用期限 {{ displayDate(row.start_time) }} 至 {{ displayDate(row.end_time) }}</text></template>
 </view><text v-if="!rows.length&&!loading&&!error" class="cw-muted">暂无符合条件的优惠券</text><button v-if="data?.has_more" :disabled="loading||props.operations.busy.value" @tap="loadMore">加载更多</button><view class="cw-dialog-buttons"><button :disabled="props.operations.busy.value" @tap="emit('close')">关闭</button></view>
 </view></view></template>
<script setup lang="ts">
import { customerWorkUserNotice } from '@/utils/customerWorkUsers';
import { computed,ref,watch } from 'vue';import type { CustomerWorkUserOperations } from '@/composables/useCustomerWorkUserOperations';import type { CustomerWorkUserCouponCandidate,CustomerWorkUserCoupon,CustomerWorkUserCouponCandidates,CustomerWorkUserCoupons,CustomerWorkUserMeta } from '@/types/customerWorkUsers';import { isCustomerWorkUserCouponCandidates,isCustomerWorkUserCoupons } from '@/utils/customerWorkUsersContract';
const props=defineProps<{visible:boolean;mode:'grant'|'wallet';uid:number;targetIds:number[];operations:CustomerWorkUserOperations}>(),emit=defineEmits<{close:[];grant:[row:CustomerWorkUserCouponCandidate,meta:CustomerWorkUserMeta]} >();
const keyword=ref(''),error=ref(''),loading=ref(false),data=ref<CustomerWorkUserCouponCandidates|CustomerWorkUserCoupons|null>(null),rows=computed<(CustomerWorkUserCouponCandidate|CustomerWorkUserCoupon)[]>(()=>data.value?.list??[]);let epoch=0,appliedKeyword='',targetStamp='';
function reset(){epoch++;keyword.value='';error.value='';loading.value=false;data.value=null;appliedKeyword='';targetStamp='';}
watch([()=>props.visible,()=>props.mode,()=>props.uid,()=>props.targetIds.join(',')],()=>{reset();if(props.visible){targetStamp=props.mode==='wallet'?'wallet:'+props.uid:'grant:'+props.targetIds.join(',');void load(1);}},{immediate:true});
function isCandidate(row:CustomerWorkUserCouponCandidate|CustomerWorkUserCoupon):row is CustomerWorkUserCouponCandidate{return 'action'in row;}
function scopeName(type:number|null){return type===0?'通用券':type===1?'指定商品':type===2?'指定品类':type===3?'会员券':'原券范围未知';}
function availabilityName(value:string){return({available:'当前可用',future:'尚未到使用时间',expired:'已过期',invalid:'当前不可用'}as Record<string,string>)[value]??value;}
function displayDate(value:string|null){return value?value.replace('T',' ').replace('.000Z',' UTC'):'未设置';}
async function load(page:number){if(!props.visible||loading.value||!props.operations.current())return;const version=epoch,stamp=targetStamp,mode=props.mode,uid=props.uid,valid=props.operations.manager.fence();loading.value=true;error.value='';try{if(mode==='grant'&&(!props.targetIds.length||props.targetIds.length>100))throw Error('赠券目标必须为1至100位用户');if(mode==='wallet'&&(!Number.isInteger(uid)||uid<1))throw Error('优惠券用户无效');const response=mode==='grant'?await props.operations.read('/mobile/work/users/coupon-grants',isCustomerWorkUserCouponCandidates,{page,limit:20,coupon_title:appliedKeyword}):await props.operations.read(`/mobile/work/users/${uid}/coupons`,isCustomerWorkUserCoupons,{page,limit:20});if(!valid()||version!==epoch||stamp!==targetStamp||!props.visible)return;const result=response.data;if(mode==='wallet'&&(!('uid'in result)||result.uid!==uid))throw Error('优惠券归属用户已变化');if(result.page!==page||result.limit!==20||page>1&&(result.count!==data.value?.count||result.list.some(row=>data.value?.list.some(old=>old.id===row.id))))throw Error('优惠券分页已变化，请重新读取');data.value={...result,list:[...(page>1?data.value?.list??[]:[]),...result.list]} as CustomerWorkUserCouponCandidates|CustomerWorkUserCoupons;}catch(failure){if(valid()&&version===epoch){error.value=failure instanceof Error?failure.message:'优惠券读取失败';data.value=null;}}finally{if(valid()&&version===epoch)loading.value=false;}}
function search(){if(loading.value||props.operations.busy.value)return;if(Array.from(keyword.value).length>100||/[\u0000-\u001f\u007f]/u.test(keyword.value)){error.value='优惠券标题无效或超过100字';return;}epoch++;data.value=null;appliedKeyword=keyword.value;void load(1);}
function loadMore(){if(data.value?.has_more)void load(data.value.page+1);}
function grant(row:CustomerWorkUserCouponCandidate){if(props.mode==='grant'&&props.visible&&data.value&&row.action.available&&!loading.value&&!props.operations.busy.value&&data.value.list.some(item=>item.id===row.id))emit('grant',row,data.value);}
</script>
