<template><view v-if="props.operations.current()&&props.operations.pending.value.length" class="cw-recovery" data-financial-recovery="pending"><text class="cw-subtitle">财务原操作结果</text><text>保留原编号和全部原内容。渠道受理或结果未知时，请继续核对原操作，勿另发一次退款。</text><view v-for="intent in props.operations.pending.value" :key="intent.request_key" class="cw-recovery-row" :data-financial-key="intent.request_key"><text>{{ CUSTOMER_FINANCIAL_NAMES[intent.kind] }} · {{ intent.order_no }}</text><text class="cw-request-key cw-muted">{{ intent.request_key }}</text><text>{{ customerFinancialResultMessage(props.operations.states.value[intent.request_key]?.result??null) }}</text><text v-if="props.operations.states.value[intent.request_key]?.error" class="cw-error">{{ props.operations.states.value[intent.request_key]?.error }}</text><view class="cw-controls"><button :disabled="props.operations.busy.value" @tap="props.operations.check(intent)">查询原结果</button><button v-if="!props.operations.states.value[intent.request_key]?.result?.receipt" :disabled="!props.operations.canRestore(intent)" @tap="props.operations.restore(intent)">恢复原财务意图</button><button v-if="props.operations.states.value[intent.request_key]?.result?.receipt?.outcome==='provider-admitted'&&!terminal(intent)" :disabled="!props.operations.canResume(intent)" @tap="props.operations.resume(intent)">核对原退款渠道</button><button v-if="!props.operations.states.value[intent.request_key]?.result?.receipt" :disabled="!props.operations.canAbandon(intent)" @tap="props.operations.abandon(intent)">放弃尚未执行的意图</button><button v-if="terminal(intent)" :disabled="props.operations.busy.value" @tap="props.operations.acknowledge(intent)">已核对，关闭记录</button><button v-if="created(intent)&&props.operations.manager.context.value" :disabled="props.operations.busy.value" @tap="openCreated(intent)">核对新申请并退款</button></view></view></view></template>
<script setup lang="ts">
import type {CustomerFinancialOperations} from '@/composables/useCustomerWorkFinancialOperations';
import type {CustomerFinancialIntent} from '@/types/customerWorkFinancial';
import {CUSTOMER_FINANCIAL_NAMES,customerFinancialResultMessage,customerFinancialTerminal,financialNumber} from '@/utils/customerWorkFinancial';
const props=defineProps<{operations:CustomerFinancialOperations}>();
function terminal(intent:CustomerFinancialIntent){const result=props.operations.states.value[intent.request_key]?.result;return !!result&&customerFinancialTerminal(result);}
function created(intent:CustomerFinancialIntent){const receipt=props.operations.states.value[intent.request_key]?.result?.receipt;return receipt?.outcome==='refund-created'&&financialNumber(receipt.evidence.refund_no);}
function openCreated(intent:CustomerFinancialIntent){if(!created(intent))return;const receipt=props.operations.states.value[intent.request_key]!.result!.receipt!;props.operations.manager.go('refundDetail',{refundOrderId:receipt.evidence.refund_no as string});}
</script>
