<template>
 <view v-show="props.visible" class="cw-dialog" role="dialog" aria-label="筛选用户" @tap.self="emit('close')"><view class="cw-dialog-panel"><text class="cw-subtitle">筛选全站用户</text><text v-if="props.loading" class="cw-muted">正在读取目录…</text><text v-if="props.error" class="cw-error">{{ props.error }}</text>
  <label class="cw-form-field"><text>用户分组</text><picker :range="groups" range-key="name" :value="groupIndex" :disabled="props.busy||props.loading" @change="group_id=String(groups[Number($event.detail.value)]?.id??0)"><view>{{ groups[groupIndex]?.name }}</view></picker></label>
  <label class="cw-form-field"><text>用户等级</text><picker :range="levels" range-key="name" :value="levelIndex" :disabled="props.busy||props.loading" @change="level=String(levels[Number($event.detail.value)]?.id??0)"><view>{{ levels[levelIndex]?.name }}</view></picker></label>
  <label class="cw-form-field"><text>付费会员标记</text><picker :range="members" range-key="name" :value="memberIndex" :disabled="props.busy" @change="isMember=members[Number($event.detail.value)]?.id??''"><view>{{ members[memberIndex]?.name }}</view></picker></label><text class="cw-muted">会员标记按账户记录筛选，实际有效期另列显示。</text>
  <label class="cw-form-field"><text>搜索平台标签</text><input v-model="keyword" :disabled="props.busy" placeholder="输入标签名称" /></label><checkbox-group @change="change"><view v-for="group in visibleLabels" :key="group.id"><text class="cw-subtitle">{{ group.name }}</text><label v-for="label in group.label" :key="label.id" class="cw-user-filter-label"><checkbox :value="String(label.id)" :checked="chosen.includes(label.id)" :disabled="props.busy" /><text>{{ label.label_name }}</text></label></view></checkbox-group><text class="cw-muted">已选 {{ chosen.length }}/100</text>
  <text v-if="localError" class="cw-error">{{ localError }}</text><view class="cw-dialog-buttons"><button :disabled="props.busy" @tap="reset">清除筛选</button><button :disabled="props.busy" @tap="emit('close')">取消</button><button :disabled="props.loading||props.busy||!!props.error" @tap="submit">应用筛选</button></view>
 </view></view>
</template>
<script setup lang="ts">
import { computed,ref,watch } from 'vue';
import type { CustomerWorkUserGroups,CustomerWorkUserLevels,CustomerWorkUserLabels } from '@/types/customerWorkUsers';
const props=defineProps<{visible:boolean;groups:CustomerWorkUserGroups['list'];levels:CustomerWorkUserLevels['list'];labels:CustomerWorkUserLabels['list'];value:Record<string,string>;loading:boolean;busy:boolean;error:string}>(),emit=defineEmits<{close:[];submit:[value:Record<string,string>]} >();
const group_id=ref('0'),level=ref('0'),isMember=ref(''),chosen=ref<number[]>([]),keyword=ref(''),localError=ref('');
const groups=computed(()=>[{id:0,name:'全部分组'},...props.groups.map(row=>({id:row.id,name:row.group_name}))]),levels=computed(()=>[{id:0,name:'全部等级'},...props.levels.map(row=>({id:row.id,name:row.name}))]),members=[{id:'',name:'全部'},{id:'0',name:'无付费会员标记'},{id:'1',name:'有付费会员标记'}],groupIndex=computed(()=>Math.max(0,groups.value.findIndex(row=>String(row.id)===group_id.value))),levelIndex=computed(()=>Math.max(0,levels.value.findIndex(row=>String(row.id)===level.value))),memberIndex=computed(()=>Math.max(0,members.findIndex(row=>row.id===isMember.value)));
const visibleLabels=computed(()=>props.labels.map(group=>({...group,label:group.label.filter(label=>group.name.includes(keyword.value.trim())||label.label_name.includes(keyword.value.trim()))})).filter(group=>group.label.length));
watch(()=>[props.visible,props.value],()=>{group_id.value=props.visible?props.value.group_id??'0':'0';level.value=props.visible?props.value.level??'0':'0';isMember.value=props.visible?props.value.isMember??'':'';chosen.value=props.visible&&props.value.label_ids?props.value.label_ids.split(',').map(Number):[];keyword.value='';localError.value='';},{immediate:true});
function reset(){group_id.value='0';level.value='0';isMember.value='';chosen.value=[];localError.value='';}
function change(event:{detail:{value:string[]}}){const visible=new Set(visibleLabels.value.flatMap(group=>group.label.map(label=>label.id)));chosen.value=[...new Set([...chosen.value.filter(id=>!visible.has(id)),...event.detail.value.map(Number)])];}
function submit(){if(props.busy||props.loading||props.error)return;const ids=props.labels.flatMap(group=>group.label.map(label=>label.id));if(chosen.value.length>100||chosen.value.some(id=>!ids.includes(id))||!groups.value.some(row=>String(row.id)===group_id.value)||!levels.value.some(row=>String(row.id)===level.value)){localError.value='筛选目录已变化或标签超过100项，请重新选择';return;}emit('submit',{group_id:group_id.value,level:level.value,label_ids:[...chosen.value].sort((a,b)=>a-b).join(','),isMember:isMember.value});}
</script>
<style scoped>.cw-user-filter-label{display:flex;align-items:center;gap:14rpx;padding:18rpx 0}</style>
