-- Generated legacy schema authority: column and primary-key shape only.
-- Source SHA-256: 0096d86464b81935106311e4bb4092b647ab3acaf2bab0febe5695f8f66c593a
-- Source table count: 201
-- Regenerate only from the reviewed cinashop-php public/install/crmeb.sql authority.

CREATE TABLE `eb_agent_level` (
  `add_time` TEXT,
  `color` TEXT,
  `grade` TEXT,
  `id` TEXT,
  `image` TEXT,
  `is_del` TEXT,
  `name` TEXT,
  `one_brokerage` TEXT,
  `status` TEXT,
  `two_brokerage` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_agent_level_task` (
  `add_time` TEXT,
  `desc` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `is_must` TEXT,
  `level_id` TEXT,
  `name` TEXT,
  `number` TEXT,
  `sort` TEXT,
  `status` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_agent_level_task_record` (
  `add_time` TEXT,
  `id` TEXT,
  `level_id` TEXT,
  `status` TEXT,
  `task_id` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_agreement` (
  `add_time` TEXT,
  `content` TEXT,
  `id` TEXT,
  `sort` TEXT,
  `status` TEXT,
  `title` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_article` (
  `add_time` TEXT,
  `admin_id` TEXT,
  `author` TEXT,
  `cid` TEXT,
  `hide` TEXT,
  `id` TEXT,
  `image_input` TEXT,
  `is_banner` TEXT,
  `is_hot` TEXT,
  `likes` TEXT,
  `mer_id` TEXT,
  `product_id` TEXT,
  `share_synopsis` TEXT,
  `share_title` TEXT,
  `sort` TEXT,
  `status` TEXT,
  `synopsis` TEXT,
  `title` TEXT,
  `url` TEXT,
  `visit` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_article_category` (
  `add_time` TEXT,
  `hidden` TEXT,
  `id` TEXT,
  `image` TEXT,
  `intr` TEXT,
  `is_del` TEXT,
  `pid` TEXT,
  `sort` TEXT,
  `status` TEXT,
  `title` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_article_content` (
  `content` TEXT,
  `nid` TEXT
);
CREATE TABLE `eb_cache` (
  `add_time` TEXT,
  `expire_time` TEXT,
  `key` TEXT,
  `result` TEXT,
  PRIMARY KEY (`key`)
);
CREATE TABLE `eb_capital_flow` (
  `add_time` TEXT,
  `flow_id` TEXT,
  `id` TEXT,
  `mark` TEXT,
  `nickname` TEXT,
  `order_id` TEXT,
  `pay_type` TEXT,
  `phone` TEXT,
  `price` TEXT,
  `store_id` TEXT,
  `trading_type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_category` (
  `add_time` TEXT,
  `group` TEXT,
  `id` TEXT,
  `integral_max` TEXT,
  `integral_min` TEXT,
  `is_show` TEXT,
  `name` TEXT,
  `other` TEXT,
  `owner_id` TEXT,
  `pid` TEXT,
  `relation_id` TEXT,
  `sort` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_city_area` (
  `code` TEXT,
  `create_time` TEXT,
  `id` TEXT,
  `level` TEXT,
  `name` TEXT,
  `parent_id` TEXT,
  `path` TEXT,
  `snum` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_community` (
  `add_time` TEXT,
  `collect_num` TEXT,
  `comment_num` TEXT,
  `content` TEXT,
  `content_type` TEXT,
  `id` TEXT,
  `image` TEXT,
  `is_del` TEXT,
  `is_recommend` TEXT,
  `is_verify` TEXT,
  `like_num` TEXT,
  `play_num` TEXT,
  `product_id` TEXT,
  `refusal` TEXT,
  `relation_id` TEXT,
  `share_num` TEXT,
  `slider_image` TEXT,
  `sort` TEXT,
  `star` TEXT,
  `status` TEXT,
  `title` TEXT,
  `topic_id` TEXT,
  `type` TEXT,
  `verify_time` TEXT,
  `video_url` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_community_comment` (
  `add_time` TEXT,
  `avatar` TEXT,
  `city` TEXT,
  `comment_num` TEXT,
  `comment_reply_id` TEXT,
  `comment_reply_uid` TEXT,
  `community_id` TEXT,
  `content` TEXT,
  `id` TEXT,
  `ip` TEXT,
  `is_del` TEXT,
  `is_reply` TEXT,
  `is_show` TEXT,
  `is_verify` TEXT,
  `like_num` TEXT,
  `nickname` TEXT,
  `reply_id` TEXT,
  `reply_uid` TEXT,
  `type` TEXT,
  `uid` TEXT,
  `update_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_community_relevance` (
  `id` TEXT,
  `left_id` TEXT,
  `right_id` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_community_topic` (
  `add_time` TEXT,
  `icon` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `is_recommend` TEXT,
  `name` TEXT,
  `sort` TEXT,
  `status` TEXT,
  `use_num` TEXT,
  `view_num` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_community_user` (
  `add_time` TEXT,
  `avatar` TEXT,
  `community_num` TEXT,
  `desc` TEXT,
  `fans_num` TEXT,
  `follow_num` TEXT,
  `friend_num` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `like_num` TEXT,
  `nickname` TEXT,
  `relation_id` TEXT,
  `status` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_delivery_service` (
  `add_time` TEXT,
  `avatar` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `nickname` TEXT,
  `phone` TEXT,
  `relation_id` TEXT,
  `status` TEXT,
  `type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_division_apply` (
  `add_time` TEXT,
  `division_id` TEXT,
  `division_invite` TEXT,
  `division_name` TEXT,
  `id` TEXT,
  `images` TEXT,
  `is_del` TEXT,
  `name` TEXT,
  `phone` TEXT,
  `refusal_reason` TEXT,
  `status` TEXT,
  `status_time` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_diy` (
  `add_time` TEXT,
  `bg_pic` TEXT,
  `bg_tab_val` TEXT,
  `color_picker` TEXT,
  `cover_image` TEXT,
  `default_value` TEXT,
  `id` TEXT,
  `is_bg_color` TEXT,
  `is_bg_pic` TEXT,
  `is_del` TEXT,
  `is_diy` TEXT,
  `is_show` TEXT,
  `menu_status` TEXT,
  `my_banner_status` TEXT,
  `name` TEXT,
  `order_status` TEXT,
  `service_status` TEXT,
  `status` TEXT,
  `template_name` TEXT,
  `title` TEXT,
  `type` TEXT,
  `update_time` TEXT,
  `value` TEXT,
  `version` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_express` (
  `account` TEXT,
  `check_man` TEXT,
  `code` TEXT,
  `code_name` TEXT,
  `courier_name` TEXT,
  `customer_name` TEXT,
  `id` TEXT,
  `is_code` TEXT,
  `is_show` TEXT,
  `key` TEXT,
  `name` TEXT,
  `net` TEXT,
  `net_name` TEXT,
  `partner_id` TEXT,
  `partner_key` TEXT,
  `partner_name` TEXT,
  `sort` TEXT,
  `status` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_live_anchor` (
  `add_time` TEXT,
  `cover_img` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `is_show` TEXT,
  `name` TEXT,
  `phone` TEXT,
  `wechat` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_live_goods` (
  `add_time` TEXT,
  `audit_id` TEXT,
  `audit_status` TEXT,
  `cost_price` TEXT,
  `cover_img` TEXT,
  `goods_id` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `is_show` TEXT,
  `name` TEXT,
  `price` TEXT,
  `price_type` TEXT,
  `price2` TEXT,
  `product_id` TEXT,
  `sort` TEXT,
  `third_part_tag` TEXT,
  `url` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_live_room` (
  `add_time` TEXT,
  `anchor_name` TEXT,
  `anchor_wechat` TEXT,
  `close_comment` TEXT,
  `close_goods` TEXT,
  `close_like` TEXT,
  `cover_img` TEXT,
  `end_time` TEXT,
  `error_msg` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `is_show` TEXT,
  `live_status` TEXT,
  `mark` TEXT,
  `name` TEXT,
  `phone` TEXT,
  `replay_status` TEXT,
  `room_id` TEXT,
  `screen_type` TEXT,
  `share_img` TEXT,
  `sort` TEXT,
  `start_time` TEXT,
  `status` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`, `phone`)
);
CREATE TABLE `eb_live_room_goods` (
  `live_goods_id` TEXT,
  `live_room_id` TEXT
);
CREATE TABLE `eb_luck_lottery` (
  `add_time` TEXT,
  `attends_user` TEXT,
  `content` TEXT,
  `desc` TEXT,
  `end_time` TEXT,
  `factor` TEXT,
  `factor_num` TEXT,
  `id` TEXT,
  `image` TEXT,
  `is_all_record` TEXT,
  `is_content` TEXT,
  `is_del` TEXT,
  `is_personal_record` TEXT,
  `is_svip` TEXT,
  `lottery_num` TEXT,
  `lottery_num_term` TEXT,
  `name` TEXT,
  `prize_num` TEXT,
  `sort` TEXT,
  `spread_num` TEXT,
  `start_time` TEXT,
  `status` TEXT,
  `total_lottery_num` TEXT,
  `type` TEXT,
  `user_label` TEXT,
  `user_level` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_luck_lottery_record` (
  `add_time` TEXT,
  `deliver_info` TEXT,
  `deliver_time` TEXT,
  `id` TEXT,
  `is_deliver` TEXT,
  `is_receive` TEXT,
  `lottery_id` TEXT,
  `oid` TEXT,
  `prize_id` TEXT,
  `prize_info` TEXT,
  `receive_info` TEXT,
  `receive_time` TEXT,
  `type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_luck_prize` (
  `add_time` TEXT,
  `chance` TEXT,
  `coupon_id` TEXT,
  `id` TEXT,
  `image` TEXT,
  `is_del` TEXT,
  `lottery_id` TEXT,
  `name` TEXT,
  `num` TEXT,
  `product_id` TEXT,
  `prompt` TEXT,
  `sort` TEXT,
  `status` TEXT,
  `total` TEXT,
  `type` TEXT,
  `unique` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_member_card` (
  `add_time` TEXT,
  `card_batch_id` TEXT,
  `card_number` TEXT,
  `card_password` TEXT,
  `id` TEXT,
  `status` TEXT,
  `update_time` TEXT,
  `use_time` TEXT,
  `use_uid` TEXT,
  PRIMARY KEY (`id`, `card_batch_id`)
);
CREATE TABLE `eb_member_card_batch` (
  `add_time` TEXT,
  `id` TEXT,
  `qrcode` TEXT,
  `remark` TEXT,
  `sort` TEXT,
  `status` TEXT,
  `title` TEXT,
  `total_num` TEXT,
  `update_time` TEXT,
  `use_day` TEXT,
  `use_end_time` TEXT,
  `use_num` TEXT,
  `use_start_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_member_right` (
  `add_time` TEXT,
  `content` TEXT,
  `explain` TEXT,
  `id` TEXT,
  `image` TEXT,
  `number` TEXT,
  `right_type` TEXT,
  `show_title` TEXT,
  `sort` TEXT,
  `status` TEXT,
  `title` TEXT,
  PRIMARY KEY (`id`, `right_type`)
);
CREATE TABLE `eb_member_ship` (
  `add_time` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `is_label` TEXT,
  `pre_price` TEXT,
  `price` TEXT,
  `sort` TEXT,
  `title` TEXT,
  `type` TEXT,
  `vip_day` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_other_order` (
  `add_time` TEXT,
  `channel_type` TEXT,
  `code` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `is_free` TEXT,
  `is_permanent` TEXT,
  `member_price` TEXT,
  `member_type` TEXT,
  `money` TEXT,
  `order_id` TEXT,
  `overdue_time` TEXT,
  `paid` TEXT,
  `pay_price` TEXT,
  `pay_time` TEXT,
  `pay_type` TEXT,
  `remarks` TEXT,
  `staff_id` TEXT,
  `store_id` TEXT,
  `trade_no` TEXT,
  `type` TEXT,
  `uid` TEXT,
  `vip_day` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_other_order_status` (
  `change_message` TEXT,
  `change_time` TEXT,
  `change_type` TEXT,
  `oid` TEXT,
  `shop_type` TEXT
);
CREATE TABLE `eb_out_account` (
  `add_time` TEXT,
  `appid` TEXT,
  `apppwd` TEXT,
  `appsecret` TEXT,
  `id` TEXT,
  `ip` TEXT,
  `is_del` TEXT,
  `last_time` TEXT,
  `order_create_push` TEXT,
  `order_pay_push` TEXT,
  `push_account` TEXT,
  `push_open` TEXT,
  `push_password` TEXT,
  `push_token_url` TEXT,
  `refund_cancel_push` TEXT,
  `refund_create_push` TEXT,
  `rules` TEXT,
  `status` TEXT,
  `title` TEXT,
  `user_update_push` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_out_interface` (
  `describe` TEXT,
  `error_code` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `method` TEXT,
  `name` TEXT,
  `pid` TEXT,
  `request_example` TEXT,
  `request_params` TEXT,
  `return_example` TEXT,
  `return_params` TEXT,
  `type` TEXT,
  `url` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_page_category` (
  `add_time` TEXT,
  `id` TEXT,
  `name` TEXT,
  `pid` TEXT,
  `sort` TEXT,
  `status` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_page_link` (
  `add_time` TEXT,
  `cate_id` TEXT,
  `example` TEXT,
  `id` TEXT,
  `name` TEXT,
  `param` TEXT,
  `sort` TEXT,
  `status` TEXT,
  `type` TEXT,
  `url` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_print_document` (
  `add_time` TEXT,
  `fey_sn` TEXT,
  `fey_ukey` TEXT,
  `fey_user` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `print_content` TEXT,
  `print_name` TEXT,
  `print_type` TEXT,
  `status` TEXT,
  `supplier_id` TEXT,
  `times` TEXT,
  `type` TEXT,
  `yly_app_id` TEXT,
  `yly_app_secret` TEXT,
  `yly_sn` TEXT,
  `yly_user_id` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_promoter_apply` (
  `add_time` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `nickname` TEXT,
  `phone` TEXT,
  `real_name` TEXT,
  `refusal_reason` TEXT,
  `status` TEXT,
  `status_time` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_qrcode` (
  `add_time` TEXT,
  `expire_seconds` TEXT,
  `id` TEXT,
  `qrcode_url` TEXT,
  `scan` TEXT,
  `status` TEXT,
  `third_id` TEXT,
  `third_type` TEXT,
  `ticket` TEXT,
  `type` TEXT,
  `url` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_queue_auxiliary` (
  `add_time` TEXT,
  `binding_id` TEXT,
  `id` TEXT,
  `other` TEXT,
  `relation_id` TEXT,
  `status` TEXT,
  `type` TEXT,
  `update_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_queue_list` (
  `add_time` TEXT,
  `again_time` TEXT,
  `execute_key` TEXT,
  `finish_time` TEXT,
  `first_time` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `queue_in_value` TEXT,
  `sort` TEXT,
  `source` TEXT,
  `status` TEXT,
  `surplus_num` TEXT,
  `title` TEXT,
  `total_num` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`, `type`, `status`)
);
CREATE TABLE `eb_shipping_templates` (
  `add_time` TEXT,
  `appoint` TEXT,
  `group` TEXT,
  `id` TEXT,
  `name` TEXT,
  `no_delivery` TEXT,
  `relation_id` TEXT,
  `sort` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_shipping_templates_free` (
  `city_id` TEXT,
  `group` TEXT,
  `id` TEXT,
  `number` TEXT,
  `price` TEXT,
  `province_id` TEXT,
  `temp_id` TEXT,
  `uniqid` TEXT,
  `value` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_shipping_templates_no_delivery` (
  `city_id` TEXT,
  `id` TEXT,
  `province_id` TEXT,
  `temp_id` TEXT,
  `uniqid` TEXT,
  `value` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_shipping_templates_region` (
  `city_id` TEXT,
  `continue` TEXT,
  `continue_price` TEXT,
  `first` TEXT,
  `first_price` TEXT,
  `group` TEXT,
  `id` TEXT,
  `province_id` TEXT,
  `temp_id` TEXT,
  `uniqid` TEXT,
  `value` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_sms_record` (
  `add_ip` TEXT,
  `add_time` TEXT,
  `content` TEXT,
  `id` TEXT,
  `phone` TEXT,
  `record_id` TEXT,
  `resultcode` TEXT,
  `template` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_activity` (
  `add_time` TEXT,
  `applicable_store_id` TEXT,
  `applicable_type` TEXT,
  `discount` TEXT,
  `end_day` TEXT,
  `end_time` TEXT,
  `id` TEXT,
  `image` TEXT,
  `is_del` TEXT,
  `is_recommend` TEXT,
  `link_id` TEXT,
  `name` TEXT,
  `num` TEXT,
  `once_num` TEXT,
  `start_day` TEXT,
  `start_time` TEXT,
  `status` TEXT,
  `time_id` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_activity_relation` (
  `activity_id` TEXT,
  `id` TEXT,
  `product_id` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_bargain` (
  `add_time` TEXT,
  `bargain_max_price` TEXT,
  `bargain_min_price` TEXT,
  `bargain_num` TEXT,
  `cost` TEXT,
  `custom_form` TEXT,
  `delivery_type` TEXT,
  `ensure_id` TEXT,
  `freight` TEXT,
  `give_integral` TEXT,
  `id` TEXT,
  `image` TEXT,
  `images` TEXT,
  `info` TEXT,
  `is_del` TEXT,
  `is_hot` TEXT,
  `is_postage` TEXT,
  `is_support_refund` TEXT,
  `look` TEXT,
  `min_price` TEXT,
  `num` TEXT,
  `people_num` TEXT,
  `postage` TEXT,
  `price` TEXT,
  `product_id` TEXT,
  `product_type` TEXT,
  `quota` TEXT,
  `quota_show` TEXT,
  `relation_id` TEXT,
  `rule` TEXT,
  `sales` TEXT,
  `share` TEXT,
  `sort` TEXT,
  `specs` TEXT,
  `start_time` TEXT,
  `status` TEXT,
  `stock` TEXT,
  `stop_time` TEXT,
  `store_label_id` TEXT,
  `store_name` TEXT,
  `system_form_id` TEXT,
  `temp_id` TEXT,
  `title` TEXT,
  `type` TEXT,
  `unit_name` TEXT,
  `volume` TEXT,
  `weight` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_bargain_user` (
  `add_time` TEXT,
  `bargain_id` TEXT,
  `bargain_price` TEXT,
  `bargain_price_min` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `price` TEXT,
  `status` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_bargain_user_help` (
  `add_time` TEXT,
  `bargain_id` TEXT,
  `bargain_user_id` TEXT,
  `id` TEXT,
  `price` TEXT,
  `type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_branch_product` (
  `add_time` TEXT,
  `bar_code` TEXT,
  `cate_id` TEXT,
  `id` TEXT,
  `image` TEXT,
  `is_del` TEXT,
  `is_show` TEXT,
  `keyword` TEXT,
  `label_id` TEXT,
  `product_id` TEXT,
  `sales` TEXT,
  `sort` TEXT,
  `stock` TEXT,
  `store_id` TEXT,
  `store_info` TEXT,
  `store_name` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_branch_product_attr_value` (
  `bar_code` TEXT,
  `code` TEXT,
  `id` TEXT,
  `product_id` TEXT,
  `sales` TEXT,
  `stock` TEXT,
  `store_id` TEXT,
  `type` TEXT,
  `unique` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_brand` (
  `add_time` TEXT,
  `brand_name` TEXT,
  `fid` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `is_show` TEXT,
  `pid` TEXT,
  `sort` TEXT,
  `store_id` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_cart` (
  `activity_id` TEXT,
  `add_time` TEXT,
  `cart_num` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `is_new` TEXT,
  `is_pay` TEXT,
  `product_attr_unique` TEXT,
  `product_id` TEXT,
  `product_type` TEXT,
  `staff_id` TEXT,
  `status` TEXT,
  `store_id` TEXT,
  `tourist_uid` TEXT,
  `type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_combination` (
  `add_time` TEXT,
  `attr` TEXT,
  `browse` TEXT,
  `combination` TEXT,
  `cost` TEXT,
  `custom_form` TEXT,
  `delivery_type` TEXT,
  `effective_time` TEXT,
  `ensure_id` TEXT,
  `freight` TEXT,
  `id` TEXT,
  `image` TEXT,
  `images` TEXT,
  `info` TEXT,
  `is_del` TEXT,
  `is_host` TEXT,
  `is_postage` TEXT,
  `is_show` TEXT,
  `is_support_refund` TEXT,
  `mer_id` TEXT,
  `mer_use` TEXT,
  `num` TEXT,
  `once_num` TEXT,
  `people` TEXT,
  `postage` TEXT,
  `price` TEXT,
  `product_id` TEXT,
  `product_type` TEXT,
  `quota` TEXT,
  `quota_show` TEXT,
  `relation_id` TEXT,
  `sales` TEXT,
  `sort` TEXT,
  `specs` TEXT,
  `start_time` TEXT,
  `stock` TEXT,
  `stop_time` TEXT,
  `store_label_id` TEXT,
  `system_form_id` TEXT,
  `temp_id` TEXT,
  `title` TEXT,
  `type` TEXT,
  `unit_name` TEXT,
  `virtual` TEXT,
  `volume` TEXT,
  `weight` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_config` (
  `add_time` TEXT,
  `id` TEXT,
  `key_name` TEXT,
  `relation_id` TEXT,
  `type` TEXT,
  `value` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_coupon_issue` (
  `add_time` TEXT,
  `brand_id` TEXT,
  `category` TEXT,
  `category_id` TEXT,
  `cid` TEXT,
  `coupon_price` TEXT,
  `coupon_time` TEXT,
  `coupon_title` TEXT,
  `coupon_type` TEXT,
  `end_time` TEXT,
  `end_use_time` TEXT,
  `full_reduction` TEXT,
  `id` TEXT,
  `integral` TEXT,
  `is_del` TEXT,
  `is_full_give` TEXT,
  `is_give_subscribe` TEXT,
  `is_permanent` TEXT,
  `product_id` TEXT,
  `receive_type` TEXT,
  `remain_count` TEXT,
  `rule` TEXT,
  `sort` TEXT,
  `start_time` TEXT,
  `start_use_time` TEXT,
  `status` TEXT,
  `title` TEXT,
  `total_count` TEXT,
  `type` TEXT,
  `use_min_price` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_coupon_issue_user` (
  `add_time` TEXT,
  `issue_coupon_id` TEXT,
  `uid` TEXT
);
CREATE TABLE `eb_store_coupon_product` (
  `coupon_id` TEXT,
  `product_id` TEXT
);
CREATE TABLE `eb_store_coupon_user` (
  `add_time` TEXT,
  `cid` TEXT,
  `coupon_price` TEXT,
  `coupon_title` TEXT,
  `end_time` TEXT,
  `id` TEXT,
  `is_fail` TEXT,
  `start_time` TEXT,
  `status` TEXT,
  `type` TEXT,
  `uid` TEXT,
  `use_min_price` TEXT,
  `use_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_delivery_order` (
  `add_time` TEXT,
  `cargo_price` TEXT,
  `city_code` TEXT,
  `deduct_fee` TEXT,
  `delivery_no` TEXT,
  `distance` TEXT,
  `fee` TEXT,
  `finish_code` TEXT,
  `from_address` TEXT,
  `from_lat` TEXT,
  `from_lng` TEXT,
  `id` TEXT,
  `mark` TEXT,
  `mer_id` TEXT,
  `oid` TEXT,
  `order_id` TEXT,
  `reason` TEXT,
  `receiver_phone` TEXT,
  `relation_id` TEXT,
  `station_type` TEXT,
  `status` TEXT,
  `to_address` TEXT,
  `to_lat` TEXT,
  `to_lng` TEXT,
  `type` TEXT,
  `uid` TEXT,
  `user_name` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_discounts` (
  `add_time` TEXT,
  `custom_form` TEXT,
  `delivery_type` TEXT,
  `free_shipping` TEXT,
  `freight` TEXT,
  `id` TEXT,
  `image` TEXT,
  `is_del` TEXT,
  `is_limit` TEXT,
  `is_support_refund` TEXT,
  `is_time` TEXT,
  `limit_num` TEXT,
  `link_ids` TEXT,
  `product_ids` TEXT,
  `sort` TEXT,
  `start_time` TEXT,
  `status` TEXT,
  `stop_time` TEXT,
  `title` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_discounts_products` (
  `discount_id` TEXT,
  `id` TEXT,
  `image` TEXT,
  `product_id` TEXT,
  `product_type` TEXT,
  `temp_id` TEXT,
  `title` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_extract` (
  `add_time` TEXT,
  `admin_id` TEXT,
  `alipay_account` TEXT,
  `balance` TEXT,
  `bank_address` TEXT,
  `bank_code` TEXT,
  `extract_price` TEXT,
  `extract_type` TEXT,
  `fail_msg` TEXT,
  `fail_time` TEXT,
  `id` TEXT,
  `mark` TEXT,
  `pay_status` TEXT,
  `qrcode_url` TEXT,
  `status` TEXT,
  `store_id` TEXT,
  `store_mark` TEXT,
  `store_staff_id` TEXT,
  `voucher_image` TEXT,
  `voucher_title` TEXT,
  `wechat` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_finance_flow` (
  `add_time` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `link_id` TEXT,
  `mark` TEXT,
  `number` TEXT,
  `order_id` TEXT,
  `pay_price` TEXT,
  `pay_type` TEXT,
  `pm` TEXT,
  `rate` TEXT,
  `remark` TEXT,
  `staff_id` TEXT,
  `store_id` TEXT,
  `total_price` TEXT,
  `trade_time` TEXT,
  `trade_type` TEXT,
  `type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_integral` (
  `add_time` TEXT,
  `custom_form` TEXT,
  `delivery_type` TEXT,
  `ensure_id` TEXT,
  `freight` TEXT,
  `id` TEXT,
  `image` TEXT,
  `images` TEXT,
  `integral` TEXT,
  `is_del` TEXT,
  `is_host` TEXT,
  `is_show` TEXT,
  `num` TEXT,
  `once_num` TEXT,
  `postage` TEXT,
  `price` TEXT,
  `product_id` TEXT,
  `product_type` TEXT,
  `quota` TEXT,
  `quota_show` TEXT,
  `relation_id` TEXT,
  `sales` TEXT,
  `sort` TEXT,
  `specs` TEXT,
  `stock` TEXT,
  `store_label_id` TEXT,
  `system_form_id` TEXT,
  `temp_id` TEXT,
  `title` TEXT,
  `type` TEXT,
  `unit_name` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_integral_order` (
  `add_time` TEXT,
  `cart_info` TEXT,
  `channel_type` TEXT,
  `custom_form` TEXT,
  `delivery_code` TEXT,
  `delivery_id` TEXT,
  `delivery_name` TEXT,
  `delivery_type` TEXT,
  `delivery_uid` TEXT,
  `express_dump` TEXT,
  `fictitious_content` TEXT,
  `id` TEXT,
  `image` TEXT,
  `integral` TEXT,
  `is_del` TEXT,
  `is_mer_check` TEXT,
  `is_remind` TEXT,
  `is_system_del` TEXT,
  `kuaidi_label` TEXT,
  `mark` TEXT,
  `mer_id` TEXT,
  `order_id` TEXT,
  `paid` TEXT,
  `pay_time` TEXT,
  `pay_type` TEXT,
  `price` TEXT,
  `product_id` TEXT,
  `product_type` TEXT,
  `province` TEXT,
  `real_name` TEXT,
  `remark` TEXT,
  `status` TEXT,
  `store_name` TEXT,
  `suk` TEXT,
  `total_integral` TEXT,
  `total_num` TEXT,
  `total_price` TEXT,
  `trade_no` TEXT,
  `uid` TEXT,
  `unique` TEXT,
  `user_address` TEXT,
  `user_phone` TEXT,
  `verify_code` TEXT,
  `virtual_info` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_integral_order_status` (
  `change_message` TEXT,
  `change_time` TEXT,
  `change_type` TEXT,
  `oid` TEXT
);
CREATE TABLE `eb_store_newcomer` (
  `add_time` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `ot_price` TEXT,
  `price` TEXT,
  `product_id` TEXT,
  `product_type` TEXT,
  `relation_id` TEXT,
  `sales` TEXT,
  `type` TEXT,
  `update_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_order` (
  `activity_append` TEXT,
  `activity_id` TEXT,
  `add_time` TEXT,
  `back_integral` TEXT,
  `cart_id` TEXT,
  `change_price` TEXT,
  `channel_type` TEXT,
  `clerk_id` TEXT,
  `cost` TEXT,
  `coupon_id` TEXT,
  `coupon_price` TEXT,
  `custom_form` TEXT,
  `deduction_price` TEXT,
  `delivery_code` TEXT,
  `delivery_id` TEXT,
  `delivery_name` TEXT,
  `delivery_type` TEXT,
  `delivery_uid` TEXT,
  `division_agent_brokerage` TEXT,
  `division_agent_id` TEXT,
  `division_brokerage` TEXT,
  `division_id` TEXT,
  `division_staff_brokerage` TEXT,
  `division_staff_id` TEXT,
  `erp_id` TEXT,
  `erp_order_id` TEXT,
  `express_dump` TEXT,
  `fictitious_content` TEXT,
  `first_order_price` TEXT,
  `freight_price` TEXT,
  `gain_integral` TEXT,
  `give_coupon` TEXT,
  `give_integral` TEXT,
  `id` TEXT,
  `is_channel` TEXT,
  `is_del` TEXT,
  `is_remind` TEXT,
  `is_stock_up` TEXT,
  `is_system_del` TEXT,
  `kuaidi_label` TEXT,
  `kuaidi_order_id` TEXT,
  `kuaidi_task_id` TEXT,
  `mark` TEXT,
  `mer_id` TEXT,
  `one_brokerage` TEXT,
  `order_id` TEXT,
  `paid` TEXT,
  `pay_integral` TEXT,
  `pay_postage` TEXT,
  `pay_price` TEXT,
  `pay_time` TEXT,
  `pay_type` TEXT,
  `pid` TEXT,
  `pink_id` TEXT,
  `product_type` TEXT,
  `promotions_give` TEXT,
  `promotions_price` TEXT,
  `province` TEXT,
  `real_name` TEXT,
  `refund_express` TEXT,
  `refund_price` TEXT,
  `refund_reason` TEXT,
  `refund_reason_time` TEXT,
  `refund_reason_wap` TEXT,
  `refund_reason_wap_explain` TEXT,
  `refund_reason_wap_img` TEXT,
  `refund_status` TEXT,
  `refund_type` TEXT,
  `remark` TEXT,
  `shipping_type` TEXT,
  `spread_two_uid` TEXT,
  `spread_uid` TEXT,
  `staff_id` TEXT,
  `status` TEXT,
  `store_id` TEXT,
  `supplier_id` TEXT,
  `total_num` TEXT,
  `total_postage` TEXT,
  `total_price` TEXT,
  `trade_no` TEXT,
  `two_brokerage` TEXT,
  `type` TEXT,
  `uid` TEXT,
  `unique` TEXT,
  `use_integral` TEXT,
  `user_address` TEXT,
  `user_location` TEXT,
  `user_phone` TEXT,
  `verify_code` TEXT,
  `virtual_info` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_order_cart_info` (
  `add_time` TEXT,
  `cart_id` TEXT,
  `cart_info` TEXT,
  `cart_num` TEXT,
  `delivery_id` TEXT,
  `id` TEXT,
  `is_advent_sms` TEXT,
  `is_expire_sms` TEXT,
  `is_gift` TEXT,
  `is_support_refund` TEXT,
  `is_writeoff` TEXT,
  `oid` TEXT,
  `old_cart_id` TEXT,
  `product_id` TEXT,
  `product_type` TEXT,
  `promotions_id` TEXT,
  `refund_num` TEXT,
  `relation_id` TEXT,
  `sku_unique` TEXT,
  `split_status` TEXT,
  `split_surplus_num` TEXT,
  `staff_id` TEXT,
  `surplus_num` TEXT,
  `type` TEXT,
  `uid` TEXT,
  `unique` TEXT,
  `write_end` TEXT,
  `write_start` TEXT,
  `write_surplus_times` TEXT,
  `write_times` TEXT,
  `writeoff_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_order_economize` (
  `add_time` TEXT,
  `coupon_price` TEXT,
  `id` TEXT,
  `member_price` TEXT,
  `offline_price` TEXT,
  `order_id` TEXT,
  `order_type` TEXT,
  `pay_price` TEXT,
  `postage_price` TEXT,
  `status` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`, `order_id`, `uid`)
);
CREATE TABLE `eb_store_order_invoice` (
  `add_time` TEXT,
  `address` TEXT,
  `bank` TEXT,
  `card_number` TEXT,
  `category` TEXT,
  `drawer_phone` TEXT,
  `duty_number` TEXT,
  `email` TEXT,
  `header_type` TEXT,
  `id` TEXT,
  `invoice_amount` TEXT,
  `invoice_id` TEXT,
  `invoice_number` TEXT,
  `invoice_time` TEXT,
  `is_del` TEXT,
  `is_invoice` TEXT,
  `is_pay` TEXT,
  `is_refund` TEXT,
  `name` TEXT,
  `order_id` TEXT,
  `remark` TEXT,
  `tell` TEXT,
  `type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_order_promotions` (
  `add_time` TEXT,
  `id` TEXT,
  `oid` TEXT,
  `product_id` TEXT,
  `promotions_id` TEXT,
  `promotions_price` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_order_refund` (
  `add_time` TEXT,
  `apply_price` TEXT,
  `apply_type` TEXT,
  `cart_info` TEXT,
  `id` TEXT,
  `is_cancel` TEXT,
  `is_del` TEXT,
  `order_id` TEXT,
  `refund_explain` TEXT,
  `refund_express` TEXT,
  `refund_express_name` TEXT,
  `refund_goods_explain` TEXT,
  `refund_goods_img` TEXT,
  `refund_goods_type` TEXT,
  `refund_img` TEXT,
  `refund_num` TEXT,
  `refund_phone` TEXT,
  `refund_price` TEXT,
  `refund_reason` TEXT,
  `refund_type` TEXT,
  `refunded_price` TEXT,
  `refunded_time` TEXT,
  `refuse_reason` TEXT,
  `remark` TEXT,
  `store_id` TEXT,
  `store_order_id` TEXT,
  `supplier_id` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_order_status` (
  `change_message` TEXT,
  `change_time` TEXT,
  `change_type` TEXT,
  `oid` TEXT
);
CREATE TABLE `eb_store_order_writeoff` (
  `add_time` TEXT,
  `admin_id` TEXT,
  `id` TEXT,
  `is_admin` TEXT,
  `oid` TEXT,
  `order_cart_id` TEXT,
  `product_id` TEXT,
  `product_type` TEXT,
  `relation_id` TEXT,
  `staff_id` TEXT,
  `type` TEXT,
  `uid` TEXT,
  `writeoff_code` TEXT,
  `writeoff_num` TEXT,
  `writeoff_price` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_pink` (
  `add_time` TEXT,
  `avatar` TEXT,
  `cid` TEXT,
  `id` TEXT,
  `is_refund` TEXT,
  `is_tpl` TEXT,
  `is_virtual` TEXT,
  `k_id` TEXT,
  `nickname` TEXT,
  `order_id` TEXT,
  `order_id_key` TEXT,
  `people` TEXT,
  `pid` TEXT,
  `price` TEXT,
  `status` TEXT,
  `stop_time` TEXT,
  `total_num` TEXT,
  `total_price` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product` (
  `activity` TEXT,
  `add_time` TEXT,
  `auto_off_time` TEXT,
  `auto_on_time` TEXT,
  `bar_code` TEXT,
  `brand_com` TEXT,
  `brand_id` TEXT,
  `browse` TEXT,
  `cate_id` TEXT,
  `code` TEXT,
  `code_path` TEXT,
  `collect` TEXT,
  `command_word` TEXT,
  `cost` TEXT,
  `custom_form` TEXT,
  `delivery_type` TEXT,
  `ensure_id` TEXT,
  `ficti` TEXT,
  `freight` TEXT,
  `give_integral` TEXT,
  `id` TEXT,
  `image` TEXT,
  `is_bargain` TEXT,
  `is_benefit` TEXT,
  `is_best` TEXT,
  `is_del` TEXT,
  `is_good` TEXT,
  `is_hot` TEXT,
  `is_limit` TEXT,
  `is_new` TEXT,
  `is_police` TEXT,
  `is_postage` TEXT,
  `is_presale_product` TEXT,
  `is_seckill` TEXT,
  `is_show` TEXT,
  `is_sold` TEXT,
  `is_sub` TEXT,
  `is_support_refund` TEXT,
  `is_verify` TEXT,
  `is_vip` TEXT,
  `is_vip_product` TEXT,
  `keyword` TEXT,
  `label_id` TEXT,
  `limit_num` TEXT,
  `limit_type` TEXT,
  `mer_id` TEXT,
  `mer_use` TEXT,
  `ot_price` TEXT,
  `pid` TEXT,
  `postage` TEXT,
  `presale_day` TEXT,
  `presale_end_time` TEXT,
  `presale_start_time` TEXT,
  `price` TEXT,
  `product_type` TEXT,
  `recommend_image` TEXT,
  `recommend_list` TEXT,
  `refusal` TEXT,
  `relation_id` TEXT,
  `sales` TEXT,
  `settle_price` TEXT,
  `slider_image` TEXT,
  `sort` TEXT,
  `soure_link` TEXT,
  `spec_type` TEXT,
  `specs` TEXT,
  `specs_id` TEXT,
  `spu` TEXT,
  `star` TEXT,
  `stock` TEXT,
  `store_info` TEXT,
  `store_label_id` TEXT,
  `store_name` TEXT,
  `system_form_id` TEXT,
  `temp_id` TEXT,
  `type` TEXT,
  `unit_name` TEXT,
  `video_link` TEXT,
  `video_open` TEXT,
  `vip_price` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_attr` (
  `attr_name` TEXT,
  `attr_values` TEXT,
  `id` TEXT,
  `product_id` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_attr_result` (
  `change_time` TEXT,
  `id` TEXT,
  `product_id` TEXT,
  `result` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_attr_value` (
  `bar_code` TEXT,
  `brokerage` TEXT,
  `brokerage_two` TEXT,
  `code` TEXT,
  `cost` TEXT,
  `disk_info` TEXT,
  `id` TEXT,
  `image` TEXT,
  `integral` TEXT,
  `ot_price` TEXT,
  `price` TEXT,
  `product_id` TEXT,
  `product_type` TEXT,
  `quota` TEXT,
  `quota_show` TEXT,
  `sales` TEXT,
  `settle_price` TEXT,
  `stock` TEXT,
  `suk` TEXT,
  `sum_stock` TEXT,
  `type` TEXT,
  `unique` TEXT,
  `vip_price` TEXT,
  `volume` TEXT,
  `weight` TEXT,
  `write_days` TEXT,
  `write_end` TEXT,
  `write_start` TEXT,
  `write_times` TEXT,
  `write_valid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_cate` (
  `add_time` TEXT,
  `cate_id` TEXT,
  `cate_pid` TEXT,
  `id` TEXT,
  `product_id` TEXT,
  `status` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_category` (
  `add_time` TEXT,
  `adv_link` TEXT,
  `adv_pic` TEXT,
  `big_pic` TEXT,
  `cate_name` TEXT,
  `id` TEXT,
  `is_show` TEXT,
  `level` TEXT,
  `path` TEXT,
  `pic` TEXT,
  `pid` TEXT,
  `relation_id` TEXT,
  `sort` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_category_brand` (
  `add_time` TEXT,
  `brand_id` TEXT,
  `brand_name` TEXT,
  `cate_id` TEXT,
  `id` TEXT,
  `product_id` TEXT,
  `status` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_coupon` (
  `add_time` TEXT,
  `id` TEXT,
  `issue_coupon_id` TEXT,
  `product_id` TEXT,
  `title` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_description` (
  `description` TEXT,
  `product_id` TEXT,
  `type` TEXT
);
CREATE TABLE `eb_store_product_ensure` (
  `add_time` TEXT,
  `desc` TEXT,
  `id` TEXT,
  `image` TEXT,
  `name` TEXT,
  `relation_id` TEXT,
  `sort` TEXT,
  `status` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_label` (
  `add_time` TEXT,
  `bg_color` TEXT,
  `border_color` TEXT,
  `color` TEXT,
  `icon` TEXT,
  `id` TEXT,
  `is_show` TEXT,
  `label_cate` TEXT,
  `label_name` TEXT,
  `relation_id` TEXT,
  `sort` TEXT,
  `status` TEXT,
  `style_type` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_label_auxiliary` (
  `id` TEXT,
  `label_id` TEXT,
  `product_id` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_log` (
  `add_time` TEXT,
  `cart_num` TEXT,
  `collect_num` TEXT,
  `cost_price` TEXT,
  `delete_time` TEXT,
  `id` TEXT,
  `order_num` TEXT,
  `pay_num` TEXT,
  `pay_price` TEXT,
  `pay_uid` TEXT,
  `product_id` TEXT,
  `refund_num` TEXT,
  `refund_price` TEXT,
  `type` TEXT,
  `uid` TEXT,
  `visit_num` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_relation` (
  `add_time` TEXT,
  `id` TEXT,
  `product_id` TEXT,
  `relation_id` TEXT,
  `relation_pid` TEXT,
  `status` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_reply` (
  `add_time` TEXT,
  `avatar` TEXT,
  `comment` TEXT,
  `delivery_score` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `is_reply` TEXT,
  `merchant_reply_content` TEXT,
  `merchant_reply_time` TEXT,
  `nickname` TEXT,
  `oid` TEXT,
  `pics` TEXT,
  `praise` TEXT,
  `product_id` TEXT,
  `product_score` TEXT,
  `relation_id` TEXT,
  `reply_score` TEXT,
  `reply_type` TEXT,
  `service_score` TEXT,
  `sku` TEXT,
  `sku_unique` TEXT,
  `type` TEXT,
  `uid` TEXT,
  `unique` TEXT,
  `views_num` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_reply_comment` (
  `content` TEXT,
  `create_time` TEXT,
  `id` TEXT,
  `pid` TEXT,
  `praise` TEXT,
  `relation_id` TEXT,
  `reply_id` TEXT,
  `type` TEXT,
  `uid` TEXT,
  `update_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_rule` (
  `id` TEXT,
  `relation_id` TEXT,
  `rule_name` TEXT,
  `rule_value` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_specs` (
  `add_time` TEXT,
  `id` TEXT,
  `name` TEXT,
  `relation_id` TEXT,
  `sort` TEXT,
  `status` TEXT,
  `temp_id` TEXT,
  `type` TEXT,
  `value` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_stock_record` (
  `add_time` TEXT,
  `cost_price` TEXT,
  `id` TEXT,
  `number` TEXT,
  `pm` TEXT,
  `product_id` TEXT,
  `store_id` TEXT,
  `unique` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_unit` (
  `add_time` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `name` TEXT,
  `relation_id` TEXT,
  `sort` TEXT,
  `status` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_virtual` (
  `attr_unique` TEXT,
  `card_no` TEXT,
  `card_pwd` TEXT,
  `card_unique` TEXT,
  `id` TEXT,
  `order_id` TEXT,
  `order_type` TEXT,
  `product_id` TEXT,
  `store_id` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_product_words` (
  `add_time` TEXT,
  `bg_color` TEXT,
  `border_color` TEXT,
  `color` TEXT,
  `icon` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `is_hot` TEXT,
  `is_search` TEXT,
  `is_show` TEXT,
  `name` TEXT,
  `relation_id` TEXT,
  `sort` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_promotions` (
  `add_time` TEXT,
  `desc` TEXT,
  `discount` TEXT,
  `discount_type` TEXT,
  `give_coupon_id` TEXT,
  `give_integral` TEXT,
  `give_product_id` TEXT,
  `give_product_unique` TEXT,
  `id` TEXT,
  `image` TEXT,
  `is_del` TEXT,
  `is_limit` TEXT,
  `label_id` TEXT,
  `limit_num` TEXT,
  `n_piece_n_discount` TEXT,
  `name` TEXT,
  `overlay` TEXT,
  `pid` TEXT,
  `product_id` TEXT,
  `product_partake_type` TEXT,
  `promotions_cate` TEXT,
  `promotions_type` TEXT,
  `sort` TEXT,
  `start_time` TEXT,
  `status` TEXT,
  `stop_time` TEXT,
  `store_id` TEXT,
  `threshold` TEXT,
  `threshold_type` TEXT,
  `title` TEXT,
  `type` TEXT,
  `update_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_promotions_auxiliary` (
  `brand_id` TEXT,
  `coupon_id` TEXT,
  `id` TEXT,
  `is_all` TEXT,
  `limit_num` TEXT,
  `product_id` TEXT,
  `product_partake_type` TEXT,
  `promotions_id` TEXT,
  `store_label_id` TEXT,
  `surplus_num` TEXT,
  `type` TEXT,
  `unique` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_seckill` (
  `activity_id` TEXT,
  `add_time` TEXT,
  `cost` TEXT,
  `custom_form` TEXT,
  `delivery_type` TEXT,
  `description` TEXT,
  `ensure_id` TEXT,
  `freight` TEXT,
  `give_integral` TEXT,
  `id` TEXT,
  `image` TEXT,
  `images` TEXT,
  `info` TEXT,
  `is_del` TEXT,
  `is_hot` TEXT,
  `is_postage` TEXT,
  `is_show` TEXT,
  `is_support_refund` TEXT,
  `num` TEXT,
  `once_num` TEXT,
  `ot_price` TEXT,
  `postage` TEXT,
  `price` TEXT,
  `product_id` TEXT,
  `product_type` TEXT,
  `quota` TEXT,
  `quota_show` TEXT,
  `relation_id` TEXT,
  `sales` TEXT,
  `sort` TEXT,
  `specs` TEXT,
  `start_time` TEXT,
  `status` TEXT,
  `stock` TEXT,
  `stop_time` TEXT,
  `store_label_id` TEXT,
  `system_form_id` TEXT,
  `temp_id` TEXT,
  `time_id` TEXT,
  `title` TEXT,
  `type` TEXT,
  `unit_name` TEXT,
  `volume` TEXT,
  `weight` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_seckill_time` (
  `add_time` TEXT,
  `describe` TEXT,
  `end_time` TEXT,
  `id` TEXT,
  `pic` TEXT,
  `start_time` TEXT,
  `status` TEXT,
  `title` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_service` (
  `account` TEXT,
  `account_status` TEXT,
  `add_time` TEXT,
  `avatar` TEXT,
  `customer` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `mer_id` TEXT,
  `nickname` TEXT,
  `notify` TEXT,
  `online` TEXT,
  `password` TEXT,
  `phone` TEXT,
  `status` TEXT,
  `uid` TEXT,
  `uniqid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_service_feedback` (
  `add_time` TEXT,
  `content` TEXT,
  `id` TEXT,
  `make` TEXT,
  `phone` TEXT,
  `rela_name` TEXT,
  `status` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_service_log` (
  `add_time` TEXT,
  `id` TEXT,
  `is_tourist` TEXT,
  `mer_id` TEXT,
  `msn` TEXT,
  `msn_type` TEXT,
  `remind` TEXT,
  `time_node` TEXT,
  `to_uid` TEXT,
  `type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_service_record` (
  `add_time` TEXT,
  `avatar` TEXT,
  `id` TEXT,
  `is_tourist` TEXT,
  `message` TEXT,
  `message_type` TEXT,
  `mssage_num` TEXT,
  `nickname` TEXT,
  `online` TEXT,
  `to_uid` TEXT,
  `type` TEXT,
  `update_time` TEXT,
  `user_id` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_service_speechcraft` (
  `add_time` TEXT,
  `cate_id` TEXT,
  `id` TEXT,
  `kefu_id` TEXT,
  `message` TEXT,
  `sort` TEXT,
  `title` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_user` (
  `add_time` TEXT,
  `id` TEXT,
  `label_id` TEXT,
  `status` TEXT,
  `store_id` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_store_visit` (
  `add_time` TEXT,
  `cate_id` TEXT,
  `content` TEXT,
  `count` TEXT,
  `id` TEXT,
  `product_id` TEXT,
  `product_type` TEXT,
  `type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_supplier_extract` (
  `add_time` TEXT,
  `admin_id` TEXT,
  `alipay_account` TEXT,
  `balance` TEXT,
  `bank_address` TEXT,
  `bank_code` TEXT,
  `extract_price` TEXT,
  `extract_type` TEXT,
  `fail_msg` TEXT,
  `fail_time` TEXT,
  `id` TEXT,
  `mark` TEXT,
  `pay_status` TEXT,
  `qrcode_url` TEXT,
  `status` TEXT,
  `supplier_id` TEXT,
  `supplier_mark` TEXT,
  `voucher_image` TEXT,
  `voucher_title` TEXT,
  `wechat` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_supplier_flowing_water` (
  `add_time` TEXT,
  `finish_time` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `link_id` TEXT,
  `mark` TEXT,
  `number` TEXT,
  `order_id` TEXT,
  `pay_postage` TEXT,
  `pay_price` TEXT,
  `pay_type` TEXT,
  `pm` TEXT,
  `remark` TEXT,
  `status` TEXT,
  `supplier_id` TEXT,
  `total_price` TEXT,
  `trade_time` TEXT,
  `type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_supplier_ticket_print` (
  `api_key` TEXT,
  `client_id` TEXT,
  `develop_id` TEXT,
  `id` TEXT,
  `status` TEXT,
  `supplier_id` TEXT,
  `terminal_number` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_supplier_transactions` (
  `add_time` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `link_id` TEXT,
  `mark` TEXT,
  `order_id` TEXT,
  `pay_postage` TEXT,
  `pay_price` TEXT,
  `pay_type` TEXT,
  `pm` TEXT,
  `remark` TEXT,
  `supplier_id` TEXT,
  `total_price` TEXT,
  `trade_time` TEXT,
  `type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_admin` (
  `account` TEXT,
  `add_time` TEXT,
  `admin_type` TEXT,
  `division_id` TEXT,
  `head_pic` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `is_way` TEXT,
  `last_ip` TEXT,
  `last_time` TEXT,
  `level` TEXT,
  `login_count` TEXT,
  `phone` TEXT,
  `pwd` TEXT,
  `real_name` TEXT,
  `relation_id` TEXT,
  `roles` TEXT,
  `status` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_attachment` (
  `att_dir` TEXT,
  `att_id` TEXT,
  `att_size` TEXT,
  `att_type` TEXT,
  `file_type` TEXT,
  `image_type` TEXT,
  `module_type` TEXT,
  `name` TEXT,
  `pid` TEXT,
  `real_name` TEXT,
  `relation_id` TEXT,
  `satt_dir` TEXT,
  `scan_token` TEXT,
  `time` TEXT,
  `type` TEXT,
  PRIMARY KEY (`att_id`)
);
CREATE TABLE `eb_system_attachment_category` (
  `enname` TEXT,
  `file_type` TEXT,
  `id` TEXT,
  `name` TEXT,
  `pid` TEXT,
  `relation_id` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_city` (
  `area_code` TEXT,
  `city_id` TEXT,
  `id` TEXT,
  `is_show` TEXT,
  `lat` TEXT,
  `level` TEXT,
  `lng` TEXT,
  `merger_name` TEXT,
  `name` TEXT,
  `parent_id` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_config` (
  `config_tab_id` TEXT,
  `desc` TEXT,
  `high` TEXT,
  `id` TEXT,
  `info` TEXT,
  `input_type` TEXT,
  `is_store` TEXT,
  `menu_name` TEXT,
  `parameter` TEXT,
  `required` TEXT,
  `sort` TEXT,
  `status` TEXT,
  `type` TEXT,
  `upload_type` TEXT,
  `value` TEXT,
  `width` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_config_tab` (
  `eng_title` TEXT,
  `icon` TEXT,
  `id` TEXT,
  `info` TEXT,
  `is_store` TEXT,
  `pid` TEXT,
  `sort` TEXT,
  `status` TEXT,
  `title` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_file` (
  `atime` TEXT,
  `cthash` TEXT,
  `ctime` TEXT,
  `filename` TEXT,
  `id` TEXT,
  `mtime` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_form` (
  `add_time` TEXT,
  `cover_image` TEXT,
  `default_value` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `name` TEXT,
  `status` TEXT,
  `update_time` TEXT,
  `value` TEXT,
  `version` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_form_data` (
  `add_time` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `relation_id` TEXT,
  `system_form_id` TEXT,
  `type` TEXT,
  `uid` TEXT,
  `value` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_group` (
  `cate_id` TEXT,
  `config_name` TEXT,
  `fields` TEXT,
  `id` TEXT,
  `info` TEXT,
  `name` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_group_data` (
  `add_time` TEXT,
  `gid` TEXT,
  `id` TEXT,
  `sort` TEXT,
  `status` TEXT,
  `value` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_log` (
  `add_time` TEXT,
  `admin_id` TEXT,
  `admin_name` TEXT,
  `id` TEXT,
  `ip` TEXT,
  `merchant_id` TEXT,
  `method` TEXT,
  `page` TEXT,
  `path` TEXT,
  `store_id` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_menus` (
  `access` TEXT,
  `action` TEXT,
  `api_url` TEXT,
  `auth_type` TEXT,
  `controller` TEXT,
  `header` TEXT,
  `icon` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `is_header` TEXT,
  `is_show` TEXT,
  `is_show_path` TEXT,
  `menu_name` TEXT,
  `menu_path` TEXT,
  `methods` TEXT,
  `module` TEXT,
  `params` TEXT,
  `path` TEXT,
  `pid` TEXT,
  `sort` TEXT,
  `type` TEXT,
  `unique_auth` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_message` (
  `add_time` TEXT,
  `content` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `look` TEXT,
  `mark` TEXT,
  `title` TEXT,
  `type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_notice` (
  `icon` TEXT,
  `id` TEXT,
  `push_admin` TEXT,
  `status` TEXT,
  `table_title` TEXT,
  `template` TEXT,
  `title` TEXT,
  `type` TEXT,
  `url` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_notice_admin` (
  `add_time` TEXT,
  `admin_id` TEXT,
  `id` TEXT,
  `is_click` TEXT,
  `is_visit` TEXT,
  `link_id` TEXT,
  `notice_type` TEXT,
  `table_data` TEXT,
  `visit_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_notification` (
  `add_time` TEXT,
  `app_id` TEXT,
  `ent_wechat_text` TEXT,
  `id` TEXT,
  `is_app` TEXT,
  `is_ent_wechat` TEXT,
  `is_routine` TEXT,
  `is_sms` TEXT,
  `is_system` TEXT,
  `is_wechat` TEXT,
  `mark` TEXT,
  `name` TEXT,
  `routine_id` TEXT,
  `sms_id` TEXT,
  `sms_text` TEXT,
  `system_text` TEXT,
  `system_title` TEXT,
  `title` TEXT,
  `type` TEXT,
  `url` TEXT,
  `variable` TEXT,
  `wechat_id` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_role` (
  `id` TEXT,
  `level` TEXT,
  `relation_id` TEXT,
  `role_name` TEXT,
  `rules` TEXT,
  `status` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_sign_reward` (
  `days` TEXT,
  `exp` TEXT,
  `id` TEXT,
  `point` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_storage` (
  `access_key` TEXT,
  `acl` TEXT,
  `add_time` TEXT,
  `cname` TEXT,
  `domain` TEXT,
  `id` TEXT,
  `is_delete` TEXT,
  `is_ssl` TEXT,
  `name` TEXT,
  `region` TEXT,
  `status` TEXT,
  `type` TEXT,
  `update_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_store` (
  `add_time` TEXT,
  `address` TEXT,
  `alipay_account` TEXT,
  `alipay_qrcode_url` TEXT,
  `area` TEXT,
  `bank_address` TEXT,
  `bank_code` TEXT,
  `city` TEXT,
  `day_end` TEXT,
  `day_start` TEXT,
  `day_time` TEXT,
  `detailed_address` TEXT,
  `erp_shop_id` TEXT,
  `id` TEXT,
  `image` TEXT,
  `introduction` TEXT,
  `is_del` TEXT,
  `is_show` TEXT,
  `is_store` TEXT,
  `latitude` TEXT,
  `longitude` TEXT,
  `name` TEXT,
  `oblong_image` TEXT,
  `phone` TEXT,
  `province` TEXT,
  `street` TEXT,
  `valid_range` TEXT,
  `valid_time` TEXT,
  `wechat` TEXT,
  `wechat_qrcode_url` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_store_staff` (
  `account` TEXT,
  `add_time` TEXT,
  `avatar` TEXT,
  `id` TEXT,
  `is_admin` TEXT,
  `is_cashier` TEXT,
  `is_del` TEXT,
  `is_manager` TEXT,
  `last_ip` TEXT,
  `last_time` TEXT,
  `level` TEXT,
  `login_count` TEXT,
  `notify` TEXT,
  `order_status` TEXT,
  `phone` TEXT,
  `pwd` TEXT,
  `roles` TEXT,
  `staff_name` TEXT,
  `status` TEXT,
  `store_id` TEXT,
  `uid` TEXT,
  `verify_status` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_supplier` (
  `add_time` TEXT,
  `address` TEXT,
  `admin_id` TEXT,
  `alipay_account` TEXT,
  `alipay_qrcode_url` TEXT,
  `area` TEXT,
  `avatar` TEXT,
  `bank_address` TEXT,
  `bank_code` TEXT,
  `business` TEXT,
  `city` TEXT,
  `city_shop_id` TEXT,
  `detailed_address` TEXT,
  `email` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `is_show` TEXT,
  `mark` TEXT,
  `name` TEXT,
  `phone` TEXT,
  `province` TEXT,
  `sort` TEXT,
  `street` TEXT,
  `supplier_name` TEXT,
  `wechat` TEXT,
  `wechat_qrcode_url` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_timer` (
  `add_time` TEXT,
  `cycle` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `is_open` TEXT,
  `last_execution_time` TEXT,
  `mark` TEXT,
  `name` TEXT,
  `title` TEXT,
  `type` TEXT,
  `update_execution_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_user_apply` (
  `add_time` TEXT,
  `fail_msg` TEXT,
  `id` TEXT,
  `images` TEXT,
  `is_del` TEXT,
  `mark` TEXT,
  `name` TEXT,
  `phone` TEXT,
  `relation_id` TEXT,
  `status` TEXT,
  `status_time` TEXT,
  `system_name` TEXT,
  `type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_system_user_level` (
  `add_time` TEXT,
  `color` TEXT,
  `discount` TEXT,
  `exp_num` TEXT,
  `explain` TEXT,
  `grade` TEXT,
  `icon` TEXT,
  `id` TEXT,
  `image` TEXT,
  `is_del` TEXT,
  `is_forever` TEXT,
  `is_pay` TEXT,
  `is_show` TEXT,
  `mer_id` TEXT,
  `money` TEXT,
  `name` TEXT,
  `valid_date` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_template_message` (
  `add_time` TEXT,
  `content` TEXT,
  `example` TEXT,
  `id` TEXT,
  `kid` TEXT,
  `name` TEXT,
  `notification_id` TEXT,
  `status` TEXT,
  `tempid` TEXT,
  `tempkey` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user` (
  `account` TEXT,
  `add_ip` TEXT,
  `add_time` TEXT,
  `addres` TEXT,
  `adminid` TEXT,
  `agent_id` TEXT,
  `agent_level` TEXT,
  `area` TEXT,
  `avatar` TEXT,
  `bar_code` TEXT,
  `birthday` TEXT,
  `brokerage_price` TEXT,
  `card_id` TEXT,
  `city` TEXT,
  `clean_time` TEXT,
  `delete_time` TEXT,
  `division_change_time` TEXT,
  `division_end_time` TEXT,
  `division_id` TEXT,
  `division_invite` TEXT,
  `division_name` TEXT,
  `division_percent` TEXT,
  `division_status` TEXT,
  `division_type` TEXT,
  `exp` TEXT,
  `extend_info` TEXT,
  `group_id` TEXT,
  `integral` TEXT,
  `is_del` TEXT,
  `is_ever_level` TEXT,
  `is_first_order` TEXT,
  `is_money_level` TEXT,
  `is_newcomer` TEXT,
  `is_promoter` TEXT,
  `last_ip` TEXT,
  `last_time` TEXT,
  `level` TEXT,
  `level_extend_info` TEXT,
  `level_status` TEXT,
  `login_city` TEXT,
  `login_type` TEXT,
  `mark` TEXT,
  `nickname` TEXT,
  `now_money` TEXT,
  `overdue_time` TEXT,
  `partner_id` TEXT,
  `pay_count` TEXT,
  `phone` TEXT,
  `province` TEXT,
  `provincials` TEXT,
  `pwd` TEXT,
  `rand_code` TEXT,
  `real_name` TEXT,
  `record_phone` TEXT,
  `replace_order_num` TEXT,
  `sex` TEXT,
  `sign_num` TEXT,
  `sign_remind` TEXT,
  `spread_count` TEXT,
  `spread_lottery` TEXT,
  `spread_open` TEXT,
  `spread_time` TEXT,
  `spread_uid` TEXT,
  `staff_id` TEXT,
  `status` TEXT,
  `street` TEXT,
  `uid` TEXT,
  `uniqid` TEXT,
  `user_type` TEXT,
  `work_uid` TEXT,
  `work_userid` TEXT,
  PRIMARY KEY (`uid`)
);
CREATE TABLE `eb_user_address` (
  `add_time` TEXT,
  `city` TEXT,
  `city_id` TEXT,
  `detail` TEXT,
  `district` TEXT,
  `id` TEXT,
  `is_default` TEXT,
  `is_del` TEXT,
  `latitude` TEXT,
  `longitude` TEXT,
  `phone` TEXT,
  `post_code` TEXT,
  `province` TEXT,
  `real_name` TEXT,
  `street` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_bill` (
  `add_time` TEXT,
  `balance` TEXT,
  `category` TEXT,
  `frozen_time` TEXT,
  `id` TEXT,
  `link_id` TEXT,
  `mark` TEXT,
  `number` TEXT,
  `pm` TEXT,
  `status` TEXT,
  `take` TEXT,
  `title` TEXT,
  `type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_brokerage` (
  `add_time` TEXT,
  `balance` TEXT,
  `frozen_time` TEXT,
  `id` TEXT,
  `link_id` TEXT,
  `mark` TEXT,
  `number` TEXT,
  `pm` TEXT,
  `status` TEXT,
  `take` TEXT,
  `title` TEXT,
  `type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_brokerage_frozen` (
  `add_time` TEXT,
  `frozen_time` TEXT,
  `id` TEXT,
  `order_id` TEXT,
  `price` TEXT,
  `status` TEXT,
  `uid` TEXT,
  `uill_id` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_card` (
  `add_time` TEXT,
  `card_id` TEXT,
  `code` TEXT,
  `del_time` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `is_submit` TEXT,
  `openid` TEXT,
  `spread_uid` TEXT,
  `staff_id` TEXT,
  `store_id` TEXT,
  `submit_time` TEXT,
  `uid` TEXT,
  `wechat_card_id` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_enter` (
  `add_time` TEXT,
  `address` TEXT,
  `apply_time` TEXT,
  `charter` TEXT,
  `city` TEXT,
  `district` TEXT,
  `fail_message` TEXT,
  `fail_time` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `is_lock` TEXT,
  `link_tel` TEXT,
  `link_user` TEXT,
  `merchant_name` TEXT,
  `province` TEXT,
  `status` TEXT,
  `success_time` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_extract` (
  `add_time` TEXT,
  `alipay_code` TEXT,
  `balance` TEXT,
  `bank_address` TEXT,
  `bank_code` TEXT,
  `extract_fee` TEXT,
  `extract_price` TEXT,
  `extract_type` TEXT,
  `fail_msg` TEXT,
  `fail_time` TEXT,
  `id` TEXT,
  `mark` TEXT,
  `qrcode_url` TEXT,
  `real_name` TEXT,
  `status` TEXT,
  `uid` TEXT,
  `wechat` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_friends` (
  `add_time` TEXT,
  `friends_uid` TEXT,
  `id` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_group` (
  `group_name` TEXT,
  `id` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_invoice` (
  `add_time` TEXT,
  `address` TEXT,
  `bank` TEXT,
  `card_number` TEXT,
  `drawer_phone` TEXT,
  `duty_number` TEXT,
  `email` TEXT,
  `header_type` TEXT,
  `id` TEXT,
  `is_default` TEXT,
  `is_del` TEXT,
  `name` TEXT,
  `tell` TEXT,
  `type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_label` (
  `id` TEXT,
  `label_cate` TEXT,
  `label_name` TEXT,
  `relation_id` TEXT,
  `tag_id` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_label_relation` (
  `id` TEXT,
  `label_id` TEXT,
  `relation_id` TEXT,
  `type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_level` (
  `add_time` TEXT,
  `discount` TEXT,
  `grade` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `is_forever` TEXT,
  `level_id` TEXT,
  `mark` TEXT,
  `mer_id` TEXT,
  `remind` TEXT,
  `status` TEXT,
  `uid` TEXT,
  `valid_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_money` (
  `add_time` TEXT,
  `balance` TEXT,
  `id` TEXT,
  `link_id` TEXT,
  `mark` TEXT,
  `number` TEXT,
  `pm` TEXT,
  `status` TEXT,
  `title` TEXT,
  `type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_notice` (
  `add_time` TEXT,
  `content` TEXT,
  `id` TEXT,
  `is_send` TEXT,
  `send_time` TEXT,
  `title` TEXT,
  `type` TEXT,
  `uid` TEXT,
  `user` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_notice_see` (
  `add_time` TEXT,
  `id` TEXT,
  `nid` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_recharge` (
  `add_time` TEXT,
  `auth_code` TEXT,
  `channel_type` TEXT,
  `give_price` TEXT,
  `id` TEXT,
  `order_id` TEXT,
  `paid` TEXT,
  `pay_time` TEXT,
  `price` TEXT,
  `recharge_type` TEXT,
  `refund_price` TEXT,
  `remarks` TEXT,
  `staff_id` TEXT,
  `store_id` TEXT,
  `trade_no` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_relation` (
  `add_time` TEXT,
  `category` TEXT,
  `id` TEXT,
  `relation_id` TEXT,
  `type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_search` (
  `add_time` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `keyword` TEXT,
  `num` TEXT,
  `result` TEXT,
  `uid` TEXT,
  `vicword` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_sign` (
  `add_time` TEXT,
  `balance` TEXT,
  `exp_balance` TEXT,
  `exp_num` TEXT,
  `id` TEXT,
  `number` TEXT,
  `title` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_spread` (
  `admin_id` TEXT,
  `id` TEXT,
  `spread_time` TEXT,
  `spread_uid` TEXT,
  `staff_id` TEXT,
  `store_id` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_user_visit` (
  `add_time` TEXT,
  `channel_type` TEXT,
  `id` TEXT,
  `ip` TEXT,
  `province` TEXT,
  `stay_time` TEXT,
  `uid` TEXT,
  `url` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_wechat_card` (
  `add_time` TEXT,
  `background_pic_url` TEXT,
  `brand_name` TEXT,
  `card_id` TEXT,
  `card_type` TEXT,
  `center_sub_title` TEXT,
  `center_title` TEXT,
  `center_url` TEXT,
  `code_type` TEXT,
  `color` TEXT,
  `description` TEXT,
  `especial` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  `logo_url` TEXT,
  `notice` TEXT,
  `prerogative` TEXT,
  `service_phone` TEXT,
  `status` TEXT,
  `title` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_wechat_key` (
  `id` TEXT,
  `keys` TEXT,
  `reply_id` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_wechat_media` (
  `add_time` TEXT,
  `id` TEXT,
  `media_id` TEXT,
  `path` TEXT,
  `temporary` TEXT,
  `type` TEXT,
  `url` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_wechat_message` (
  `add_time` TEXT,
  `id` TEXT,
  `openid` TEXT,
  `result` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_wechat_news_category` (
  `add_time` TEXT,
  `cate_name` TEXT,
  `id` TEXT,
  `new_id` TEXT,
  `sort` TEXT,
  `status` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_wechat_qrcode` (
  `add_time` TEXT,
  `cate_id` TEXT,
  `content` TEXT,
  `continue_time` TEXT,
  `data` TEXT,
  `end_time` TEXT,
  `follow` TEXT,
  `id` TEXT,
  `image` TEXT,
  `is_del` TEXT,
  `label_id` TEXT,
  `name` TEXT,
  `scan` TEXT,
  `status` TEXT,
  `type` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_wechat_qrcode_cate` (
  `add_time` TEXT,
  `cate_name` TEXT,
  `id` TEXT,
  `is_del` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_wechat_qrcode_record` (
  `add_time` TEXT,
  `id` TEXT,
  `is_follow` TEXT,
  `qid` TEXT,
  `uid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_wechat_reply` (
  `data` TEXT,
  `hide` TEXT,
  `id` TEXT,
  `status` TEXT,
  `type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_wechat_user` (
  `add_time` TEXT,
  `city` TEXT,
  `country` TEXT,
  `groupid` TEXT,
  `headimgurl` TEXT,
  `id` TEXT,
  `is_complete` TEXT,
  `is_del` TEXT,
  `language` TEXT,
  `nickname` TEXT,
  `openid` TEXT,
  `province` TEXT,
  `remark` TEXT,
  `second` TEXT,
  `sex` TEXT,
  `subscribe` TEXT,
  `subscribe_time` TEXT,
  `tagid_list` TEXT,
  `uid` TEXT,
  `unionid` TEXT,
  `user_type` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_work_channel_code` (
  `add_upper_limit` TEXT,
  `cate_id` TEXT,
  `client_num` TEXT,
  `config_id` TEXT,
  `create_time` TEXT,
  `delete_time` TEXT,
  `id` TEXT,
  `label_id` TEXT,
  `name` TEXT,
  `qrcode_url` TEXT,
  `reserve_userid` TEXT,
  `skip_verify` TEXT,
  `status` TEXT,
  `type` TEXT,
  `update_time` TEXT,
  `userids` TEXT,
  `welcome_type` TEXT,
  `welcome_words` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_work_channel_cycle` (
  `channel_id` TEXT,
  `end_time` TEXT,
  `start_time` TEXT,
  `userids` TEXT,
  `wokr_time` TEXT
);
CREATE TABLE `eb_work_channel_limit` (
  `channel_id` TEXT,
  `max` TEXT,
  `userid` TEXT
);
CREATE TABLE `eb_work_client` (
  `avatar` TEXT,
  `corp_full_name` TEXT,
  `corp_id` TEXT,
  `corp_name` TEXT,
  `create_time` TEXT,
  `delete_time` TEXT,
  `external_profile` TEXT,
  `external_userid` TEXT,
  `gender` TEXT,
  `id` TEXT,
  `name` TEXT,
  `position` TEXT,
  `remark` TEXT,
  `type` TEXT,
  `uid` TEXT,
  `unionid` TEXT,
  `update_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_work_client_follow` (
  `add_way` TEXT,
  `client_id` TEXT,
  `create_time` TEXT,
  `createtime` TEXT,
  `description` TEXT,
  `id` TEXT,
  `is_del_user` TEXT,
  `oper_userid` TEXT,
  `remark` TEXT,
  `remark_corp_name` TEXT,
  `remark_mobiles` TEXT,
  `state` TEXT,
  `update_time` TEXT,
  `userid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_work_client_follow_tags` (
  `create_time` TEXT,
  `follow_id` TEXT,
  `group_name` TEXT,
  `tag_id` TEXT,
  `tag_name` TEXT,
  `type` TEXT
);
CREATE TABLE `eb_work_department` (
  `corp_id` TEXT,
  `create_time` TEXT,
  `department_id` TEXT,
  `department_leader` TEXT,
  `id` TEXT,
  `name` TEXT,
  `name_en` TEXT,
  `parentid` TEXT,
  `srot` TEXT,
  `update_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_work_group_chat` (
  `admin_list` TEXT,
  `chat_id` TEXT,
  `corp_id` TEXT,
  `create_time` TEXT,
  `group_create_time` TEXT,
  `id` TEXT,
  `member_num` TEXT,
  `name` TEXT,
  `notice` TEXT,
  `owner` TEXT,
  `retreat_group_num` TEXT,
  `status` TEXT,
  `update_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_work_group_chat_auth` (
  `auth_group_chat` TEXT,
  `chat_id` TEXT,
  `config_id` TEXT,
  `create_time` TEXT,
  `delete_time` TEXT,
  `group_name` TEXT,
  `group_num` TEXT,
  `id` TEXT,
  `label` TEXT,
  `name` TEXT,
  `qr_code` TEXT,
  `update_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_work_group_chat_member` (
  `chat_sum` TEXT,
  `create_time` TEXT,
  `group_id` TEXT,
  `group_nickname` TEXT,
  `id` TEXT,
  `invitor_userid` TEXT,
  `join_scene` TEXT,
  `join_time` TEXT,
  `name` TEXT,
  `retreat_chat_num` TEXT,
  `state` TEXT,
  `status` TEXT,
  `type` TEXT,
  `unionid` TEXT,
  `update_time` TEXT,
  `userid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_work_group_chat_statistic` (
  `chat_return_sum` TEXT,
  `chat_sum` TEXT,
  `create_time` TEXT,
  `group_id` TEXT,
  `id` TEXT,
  `today_return_sum` TEXT,
  `today_sum` TEXT,
  `update_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_work_group_msg_relation` (
  `msg_id` TEXT,
  `template_id` TEXT
);
CREATE TABLE `eb_work_group_msg_send_result` (
  `chat_id` TEXT,
  `create_time` TEXT,
  `external_userid` TEXT,
  `id` TEXT,
  `msg_id` TEXT,
  `send_time` TEXT,
  `status` TEXT,
  `update_time` TEXT,
  `userid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_work_group_msg_task` (
  `create_time` TEXT,
  `id` TEXT,
  `msg_id` TEXT,
  `send_time` TEXT,
  `status` TEXT,
  `userid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_work_group_template` (
  `client_type` TEXT,
  `create_time` TEXT,
  `fail_external_userid` TEXT,
  `fail_message` TEXT,
  `id` TEXT,
  `name` TEXT,
  `send_time` TEXT,
  `send_type` TEXT,
  `template_type` TEXT,
  `type` TEXT,
  `update_time` TEXT,
  `userids` TEXT,
  `welcome_words` TEXT,
  `where_label` TEXT,
  `where_not_label` TEXT,
  `where_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_work_label` (
  `corp_id` TEXT,
  `create_time` TEXT,
  `group_id` TEXT,
  `group_name` TEXT,
  `id` TEXT,
  `name` TEXT,
  `sort` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_work_media` (
  `create_time` TEXT,
  `id` TEXT,
  `md5_path` TEXT,
  `media_id` TEXT,
  `path` TEXT,
  `temporary` TEXT,
  `type` TEXT,
  `update_time` TEXT,
  `upload_type` TEXT,
  `url` TEXT,
  `valid_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_work_member` (
  `address` TEXT,
  `alias` TEXT,
  `avatar` TEXT,
  `biz_mail` TEXT,
  `corp_id` TEXT,
  `create_time` TEXT,
  `direct_leader` TEXT,
  `email` TEXT,
  `enable` TEXT,
  `external_position` TEXT,
  `gender` TEXT,
  `hide_mobile` TEXT,
  `id` TEXT,
  `is_leader` TEXT,
  `main_department` TEXT,
  `mobile` TEXT,
  `name` TEXT,
  `open_userid` TEXT,
  `position` TEXT,
  `qr_code` TEXT,
  `status` TEXT,
  `telephone` TEXT,
  `thumb_avatar` TEXT,
  `uid` TEXT,
  `update_time` TEXT,
  `userid` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_work_member_other` (
  `extattr` TEXT,
  `external_profile` TEXT,
  `member_id` TEXT
);
CREATE TABLE `eb_work_member_relation` (
  `create_time` TEXT,
  `department` TEXT,
  `is_leader_in_dept` TEXT,
  `member_id` TEXT,
  `srot` TEXT
);
CREATE TABLE `eb_work_moment` (
  `client_tag_list` TEXT,
  `client_type` TEXT,
  `create_time` TEXT,
  `id` TEXT,
  `invalid_external_contact_list` TEXT,
  `invalid_sender_list` TEXT,
  `jobid` TEXT,
  `moment_id` TEXT,
  `name` TEXT,
  `send_time` TEXT,
  `send_type` TEXT,
  `type` TEXT,
  `update_time` TEXT,
  `user_ids` TEXT,
  `welcome_words` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_work_moment_send_result` (
  `create_time` TEXT,
  `external_userid` TEXT,
  `id` TEXT,
  `moment_id` TEXT,
  `status` TEXT,
  `user_id` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_work_welcome` (
  `attachments` TEXT,
  `content` TEXT,
  `create_time` TEXT,
  `delete_time` TEXT,
  `id` TEXT,
  `sort` TEXT,
  `type` TEXT,
  `update_time` TEXT,
  PRIMARY KEY (`id`)
);
CREATE TABLE `eb_work_welcome_relation` (
  `userid` TEXT,
  `welcome_id` TEXT
);
