import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {eq} from 'drizzle-orm';
import {systemDise,systemLog} from '../src/models/schema';
import {cloneProductDetailDesign} from '../../view/common/productDetailDesign';
import {productDetailDesignFixture} from './helpers/productDetailDesignFixture';
import {ProductDetailDesignRejected,ProductDetailDesignStaleVersion} from '../src/services/admin/AdminProductDetailDesignInput';
describe.runIf(Boolean(process.env.TEST_FINANCE_POSTGRES_URL))('native product detail design mutation authority',()=>{
  let f:Awaited<ReturnType<typeof productDetailDesignFixture>>,guard:ReturnType<typeof vi.spyOn>;
  beforeEach(async()=>{f=await productDetailDesignFixture();guard=vi.spyOn(globalThis,'fetch').mockRejectedValue(Error('No design provider HTTP'));},30000);
  afterEach(async()=>{try{expect(guard).not.toHaveBeenCalled();}finally{guard?.mockRestore();await f?.close();}},30000);
  const request=(revision:string,value=cloneProductDetailDesign())=>({operationId:crypto.randomUUID(),revision,value});
  const profiles=(run:(app:any,admin:any)=>Promise<void>)=>f.withRuntimeRole(app=>f.withRuntimeRole(async admin=>{await f.installSlice(app,admin);await run(app,admin);}));
  it('reads status0 and historical ordinals without DML, initializes only explicit save, and preserves all opaque fields',async()=>{await profiles(async(_app,admin)=>{
    const service=f.designFor(admin.db),before=await f.settingsSnapshot(),initial=await service.read();expect(initial).toMatchObject({configured:true,editable:true,value:{isOpen:[3,4,5,1,2,0]}});expect(await f.settingsSnapshot()).toEqual(before);
    const value=cloneProductDetailDesign(initial.value!);value.showCart=0;await service.save(request(initial.revision,value),{id:7});const [row]=await f.db.select().from(systemDise).where(eq(systemDise.id,5));expect(JSON.parse(row.value!)).toMatchObject({showCart:0,opaque:{number:1.25,note:'完整扩展保留'},future:[true,null]});expect(row).toMatchObject({status:0,isShow:0,addTime:100,content:'PRIVATE OPAQUE METADATA'});
    await f.db.delete(systemDise).where(eq(systemDise.id,5));const missing=await service.read(),empty=await f.settingsSnapshot();expect(missing.configured).toBe(false);expect(await f.settingsSnapshot()).toEqual(empty);await service.save(request(missing.revision),{id:7});expect((await service.read()).configured).toBe(true);
  });});
  it('replays only the same actor UUID and canonical body, and rejects stale snapshots before all DML',async()=>{await profiles(async(_app,admin)=>{const service=f.designFor(admin.db),initial=await service.read(),body=request(initial.revision),saved=await service.save(body,{id:7}),before=await f.settingsSnapshot();expect(await service.save(body,{id:7})).toEqual(saved);expect(await service.receipt(body.operationId,{id:7})).toEqual(saved);await expect(service.save(body,{id:8})).rejects.toThrow();await expect(service.save({...body,value:{...body.value,showCart:0}},{id:7})).rejects.toThrow();await expect(service.save(request(initial.revision),{id:7})).rejects.toBeInstanceOf(ProductDetailDesignStaleVersion);await expect(service.receipt(body.operationId,{id:8})).rejects.toThrow();expect(await f.settingsSnapshot()).toEqual(before);});});
  it('diagnoses the entire normalized catalog, rejecting alias/deleted/wrong-type/duplicate and corrupt singleton writes',async()=>{await profiles(async(_app,admin)=>{const service=f.designFor(admin.db);for(const patch of[{templateName:' PRODUCT_DETAIL '},{isDel:1},{type:1},{value:'{"replyNum":0}'},{value:'{"showCart":1,"showCart":0}'}]){await f.db.update(systemDise).set({templateName:'product_detail',type:3,isDel:0,value:'{}',...patch}).where(eq(systemDise.id,5));const read=await service.read(),before=await f.settingsSnapshot();expect(read.editable).toBe(false);await expect(service.save(request(read.revision),{id:7})).rejects.toBeInstanceOf(ProductDetailDesignRejected);expect(await f.settingsSnapshot()).toEqual(before);}await f.db.update(systemDise).set({templateName:'product_detail',type:3,isDel:0,value:'{}'}).where(eq(systemDise.id,5));await f.db.insert(systemDise).values({templateName:' product_detail ',type:1,value:'{}'});expect((await service.read()).issues).toContain('product_detail_duplicate');});});
  it('serializes same-revision concurrent sessions with one commit and one stale proof',async()=>{await f.withRuntimeRole(app=>f.withRuntimeRole(admin=>f.withRuntimeRole(async other=>{await f.installSlice(app,admin);await f.installSlice(app,other);const revision=(await f.designFor(admin.db).read()).revision;const results=await Promise.allSettled([f.designFor(admin.db).save(request(revision),{id:7}),f.designFor(other.db).save(request(revision,{...cloneProductDetailDesign(),showCart:0}),{id:8})]);expect(results.filter(row=>row.status==='fulfilled')).toHaveLength(1);expect(results.filter(row=>row.status==='rejected')).toHaveLength(1);expect((results.find(row=>row.status==='rejected') as PromiseRejectedResult).reason).toBeInstanceOf(ProductDetailDesignStaleVersion);expect((await f.db.select().from(systemLog).where(eq(systemLog.type,'product_detail_design')))).toHaveLength(1);})));});
  it('rolls back effective settings when the journal INSERT fails after the real update',async()=>{await profiles(async(_app,admin)=>{const service=f.designFor(admin.db),body=request((await service.read()).revision),before=await f.settingsSnapshot();await f.exec("CREATE FUNCTION reject_design_journal() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.type='product_detail_design' THEN RAISE EXCEPTION 'owned journal failure'; END IF; RETURN NEW; END $$");await f.exec('CREATE TRIGGER owned_reject_design_journal BEFORE INSERT ON system_log FOR EACH ROW EXECUTE FUNCTION reject_design_journal()');let failure:unknown;try{await service.save(body,{id:7});}catch(error){failure=error;}const chain:{message:string;code:unknown}[]=[],seen=new Set<unknown>();while(failure&&typeof failure==='object'&&!seen.has(failure)&&seen.size<10){seen.add(failure);chain.push({message:String(Reflect.get(failure,'message')??''),code:Reflect.get(failure,'code')});failure=Reflect.get(failure,'cause');}expect(chain).toEqual(expect.arrayContaining([{message:expect.stringContaining('owned journal failure'),code:'P0001'}]));expect(await f.settingsSnapshot()).toEqual(before);});});
  it('keeps the restricted App LOGIN SELECT-only while Admin uses exact existing table and sequence privileges',async()=>{await profiles(async(app,admin)=>{expect((await app.exec('SELECT current_user,session_user'))[0]).toEqual({current_user:app.role,session_user:app.role});expect((await admin.exec('SELECT current_user,session_user'))[0]).toEqual({current_user:admin.role,session_user:admin.role});expect(await f.designFor(app.db).read()).toMatchObject({configured:true});for(const command of["UPDATE system_dise SET value='{}' WHERE id=5","INSERT INTO system_log(type) VALUES('product_detail_design')"])await expect(app.exec(command)).rejects.toMatchObject({code:'42501'});const saved=await f.designFor(admin.db).save(request((await f.designFor(admin.db).read()).revision),{id:7});expect(saved.id).toBe(5);});});
});
