import{afterEach,beforeEach,describe,it,expect,vi}from'vitest';
import{eq}from'drizzle-orm';
import{createApp}from'../src/app';
import{createContainerFromDb,type Container}from'../src/lib/di';
import type{Env}from'../src/env';
import{systemAdmin,systemRole,systemMenus,systemDise,user,systemConfig,systemStoreStaff}from'../src/models/schema';
import{AdminPermissionService}from'../src/services/admin/AdminPermissionService';
import{userCenterDesignInput}from'../src/services/admin/AdminUserCenterDesignInput';
import{themeHash}from'../src/services/content/ThemeReadService';
import{cloneUserCenterDesign}from'../../view/common/userCenterDesign';
import{createToken,md5}from'../src/utils/jwt';
import{userCenterDesignFixture,userCenterEnv}from'./helpers/userCenterDesignFixture';
const wiring=vi.hoisted(()=>({container:undefined as Container|undefined}));
vi.mock('../src/lib/di',async original=>({...await original<typeof import('../src/lib/di')>(),createContainer:()=>{if(!wiring.container)throw Error('Owned user-center HTTP unavailable');return wiring.container;}}));
describe.runIf(Boolean(process.env.TEST_FINANCE_POSTGRES_URL))('registered complete user-center HTTP authority',()=>{
 let f:Awaited<ReturnType<typeof userCenterDesignFixture>>,guard:ReturnType<typeof vi.spyOn>;const app=createApp(),env={...userCenterEnv},tokens=new Map<number,string>(),actors={manager:1,reader:2,legacy:3,generic:4,forged:5,second:8};
 beforeEach(async()=>{f=await userCenterDesignFixture();await f.db.insert(systemMenus).values([{id:1592,type:1,authType:1,access:1,menuPath:'/admin/setting/pages/home',uniqueAuth:'admin-setting-pages-home'},{id:91001,type:1,authType:1,access:1,menuPath:'/admin/setting/pages/home',uniqueAuth:'admin-setting-pages-home'}]);const rules:Record<string,string>={manager:'user_center_design.manage',reader:'user_center_design.view',legacy:'1592',generic:'config.manage,dise.manage,fab_settings.manage',forged:'91001',second:'user_center_design.manage'};await f.db.insert(systemRole).values(Object.entries(actors).map(([name,id])=>({id,type:1,roleName:name,rules:rules[name]})));await f.db.insert(systemAdmin).values(Object.entries(actors).map(([name,id])=>({id,account:`usercenter-${name}`,pwd:'owned-center-password',level:1,roles:String(id),adminType:1,status:1,isDel:0})));for(const id of Object.values(actors))tokens.set(id,(await createToken(id,'admin',md5('owned-center-password'),env.APP_KEY)).token);guard=vi.spyOn(globalThis,'fetch').mockRejectedValue(Error('No user-center HTTP provider'));},30000);
 afterEach(async()=>{try{expect(guard).not.toHaveBeenCalled();}finally{guard?.mockRestore();wiring.container=undefined;tokens.clear();await f?.close();}},30000);
 const profiles=(run:(admin:any)=>Promise<void>)=>f.withRuntimeRole(appPeer=>f.withRuntimeRole(async admin=>{await f.installSlice(appPeer,admin);wiring.container=createContainerFromDb(appPeer.db);Object.assign(env,{HYPERDRIVE:{connectionString:appPeer.connectionString}as Env['HYPERDRIVE'],HYPERDRIVE_ADMIN:{connectionString:admin.connectionString}as Env['HYPERDRIVE_ADMIN']});try{await run(admin);}finally{wiring.container=undefined;}}));
 async function request(prefix:string,actor:number|null,suffix='',method='GET',body?:unknown,path='/config/user-center-design'){const response=await app.request(prefix+path+suffix,{method,headers:{...(actor===null?{}:{Authorization:`Bearer ${tokens.get(actor)}`}),...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})},env);return{response,body:await response.json<{status:number;msg:string;data:any}>()};}
 const input=(read:any)=>({operationId:crypto.randomUUID(),revision:read.revision,value:cloneUserCenterDesign(read.value)});
 it.each(['/adminapi','/api/admin'])('executes real editor read save replay and actor-bound lost-reply receipt on %s',async prefix=>{await profiles(async()=>{const initial=await request(prefix,actors.reader),body=input(initial.body.data);expect(initial.body).toMatchObject({status:200,data:{configured:true,editable:true,value:{member:{property:[0,1,2,3,4]}}}});expect(initial.response.headers.get('Cache-Control')).toContain('no-store');const saved=await request(prefix,actors.manager,'/save','POST',body);expect(saved.body.data).toEqual({operation:'update',id:88,operationId:body.operationId,payloadHash:await themeHash(userCenterDesignInput(body).canonical)});const before=await f.settingsSnapshot();expect((await request(prefix,actors.manager,'/save','POST',body)).body.data).toEqual(saved.body.data);expect((await request(prefix,actors.manager,`/receipt/${body.operationId}`)).body.data).toEqual(saved.body.data);expect((await request(prefix,actors.second,`/receipt/${body.operationId}`)).response.status).toBe(404);expect(await f.settingsSnapshot()).toEqual(before);});});
 it('grants only exact installed1592 read and keeps generic DIY or FAB permissions away from selector and save',async()=>{await profiles(async admin=>{const before=await f.settingsSnapshot();for(const prefix of['/adminapi','/api/admin']){const read=(await request(prefix,actors.reader)).body.data,body=input(read);for(const actor of[actors.reader,actors.legacy]){expect((await request(prefix,actor)).body.status).toBe(200);expect((await request(prefix,actor,'/save','POST',body)).body.status).toBe(400011);}for(const actor of[actors.generic,actors.forged]){expect((await request(prefix,actor)).body.status).toBe(400011);expect((await request(prefix,actor,'/assets')).body.status).toBe(400011);}expect((await request(prefix,null)).body.status).toBe(410000);}const service=new AdminPermissionService(createContainerFromDb(admin.db));expect(await service.resolveRulePermissionKeys('1592')).toEqual(['user_center_design.view']);expect(await service.resolveManyRulePermissionKeys(['1592','91001'])).toEqual([['user_center_design.view'],[]]);for(const patch of[{authType:2},{access:0},{isDel:1},{type:2}]){await f.db.update(systemMenus).set({authType:1,type:1,access:1,isDel:0,...patch}).where(eq(systemMenus.id,1592));expect(await service.resolveRulePermissionKeys('1592')).toEqual([]);}expect(await f.settingsSnapshot()).toEqual(before);});});
 it('blocks normalized wrong-type generic DIY updates deletes and raw list publication for both prefixes',async()=>{await profiles(async()=>{await f.db.update(systemDise).set({type:1,templateName:' MEMBER '}).where(eq(systemDise.id,88));const before=await f.settingsSnapshot();for(const prefix of['/adminapi','/api/admin']){const list=await request(prefix,actors.generic,'','GET',undefined,'/dise/list');expect(JSON.stringify(list.body.data)).not.toContain('PRIVATE USER CENTER');expect((await request(prefix,actors.generic,'','POST',{id:88,name:'旁路',value:'{}'},'/dise/save')).body.status).not.toBe(200);expect((await request(prefix,actors.generic,'','DELETE',undefined,'/dise/del/88')).body.status).not.toBe(200);}expect(await f.settingsSnapshot()).toEqual(before);});});
 it('returns exact pre-DML stale proofs and real asset catalog under independent user-center view',async()=>{await profiles(async()=>{const read=(await request('/adminapi',actors.manager)).body.data,body=input(read);await request('/adminapi',actors.manager,'/save','POST',body);const stale=input(read),before=await f.settingsSnapshot(),response=await request('/adminapi',actors.manager,'/save','POST',stale);expect(response.response.status).toBe(409);expect(response.body.data).toMatchObject({code:'USER_CENTER_DESIGN_STALE_VERSION',operationId:stale.operationId,payloadHash:await themeHash(userCenterDesignInput(stale).canonical)});expect(await f.settingsSnapshot()).toEqual(before);const assets=await request('/adminapi',actors.reader,'/assets?page=1&limit=20');expect(assets.body.data.list.map((item:any)=>item.id)).toEqual([41]);expect(assets.body.data.list[0]).toMatchObject({canonical_url:'/api/assets/41',preview_url:expect.stringMatching(/^\/api\/assets\/41\?expires=/)});expect((await request('/adminapi',actors.reader,'/link-categories')).body.data.list).toHaveLength(13);for(const query of['?page=0','?page=1&page=2','?owner=3'])expect((await request('/adminapi',actors.reader,'/assets'+query)).body.status).not.toBe(200);for(const suffix of['?ignored=1','?revision=a&revision=b'])expect((await request('/adminapi',actors.reader,suffix)).body.status).not.toBe(200);});});
 it('fences real consecutive public HTTP snapshots by actor capabilities configuration and current output while ignoring auth bookkeeping',async()=>{await profiles(async()=>{const token=(await createToken(11,'api',md5('owned-integral-password'),env.APP_KEY)).token;const get=async(path:string)=>{const response=await app.request('/api'+path,{headers:{Authorization:`Bearer ${token}`}},env);expect(response.headers.get('Cache-Control')).toContain('no-store');return(await response.json<{status:number;data:any}>()).data;};const menu=await get('/menu/user'),data=await get('/menu/date');expect(menu.actor_uid).toBe(11);expect(menu.consistency_key).toMatch(/^[a-f0-9]{64}$/);expect(data.consistency_key).toBe(menu.consistency_key);await f.db.update(user).set({lastTime:999}).where(eq(user.uid,11));expect((await get('/menu/date')).consistency_key).toBe(menu.consistency_key);await f.db.update(systemConfig).set({value:'0'}).where(eq(systemConfig.menuName,'balance_func_status'));expect((await get('/menu/date')).consistency_key).not.toBe(menu.consistency_key);const changed=await get('/menu/user');expect((await get('/menu/date')).consistency_key).toBe(changed.consistency_key);await f.db.update(systemStoreStaff).set({status:0}).where(eq(systemStoreStaff.id,1));expect((await get('/menu/date')).consistency_key).not.toBe(changed.consistency_key);const noRole=await get('/menu/user');expect(noRole.capabilities).toMatchObject({merchant:false,writeoff:false});expect((await get('/menu/date')).consistency_key).toBe(noRole.consistency_key);await f.db.update(user).set({status:0}).where(eq(user.uid,11));const anonymous=await get('/menu/date');expect(anonymous.actor_uid).toBe(0);expect(anonymous.consistency_key).not.toBe(noRole.consistency_key);});});
});
