/** Actual registered application, JWT and independent restricted LOGINs. */
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {eq} from 'drizzle-orm';
import {createApp} from '../src/app';
import {createContainerFromDb,type Container} from '../src/lib/di';
import type {Env} from '../src/env';
import {systemAdmin,systemRole,systemMenus,systemDise} from '../src/models/schema';
import {AdminPermissionService} from '../src/services/admin/AdminPermissionService';
import {productDetailDesignInput} from '../src/services/admin/AdminProductDetailDesignInput';
import {themeHash} from '../src/services/content/ThemeReadService';
import {cloneProductDetailDesign} from '../../view/common/productDetailDesign';
import {createToken,md5} from '../src/utils/jwt';
import {productDetailDesignFixture,detailDesignEnv} from './helpers/productDetailDesignFixture';
const wiring=vi.hoisted(()=>({container:undefined as Container|undefined}));
vi.mock('../src/lib/di',async original=>({...await original<typeof import('../src/lib/di')>(),createContainer:()=>{if(!wiring.container)throw Error('Owned detail design HTTP unavailable');return wiring.container;}}));
describe.runIf(Boolean(process.env.TEST_FINANCE_POSTGRES_URL))('registered product detail design HTTP',()=>{
  let f:Awaited<ReturnType<typeof productDetailDesignFixture>>,guard:ReturnType<typeof vi.spyOn>;const app=createApp(),env={...detailDesignEnv},tokens=new Map<number,string>();
  const actors={manager:1,reader:2,legacy:3,generic:4,wrongPath:5,wrongAuth:6,second:8};
  beforeEach(async()=>{f=await productDetailDesignFixture();await f.db.insert(systemMenus).values([{id:1594,type:1,authType:1,access:1,menuPath:'/admin/setting/pages/product_detail',uniqueAuth:'admin-setting-pages-product_detail'},
    {id:91001,type:1,authType:1,access:1,menuPath:'/admin/setting/wrong',uniqueAuth:'admin-setting-pages-product_detail'},{id:91002,type:1,authType:1,access:1,menuPath:'/admin/setting/pages/product_detail',uniqueAuth:'wrong-auth'}]);
    const rules:Record<string,string>={manager:'product_detail_design.manage',reader:'product_detail_design.view',legacy:'1594',generic:'config.manage,dise.manage,product_category_style.manage',wrongPath:'91001',wrongAuth:'91002',second:'product_detail_design.manage'};
    await f.db.insert(systemRole).values(Object.entries(actors).map(([name,id])=>({id,type:1,roleName:name,rules:rules[name]})));
    await f.db.insert(systemAdmin).values(Object.entries(actors).map(([name,id])=>({id,account:`detail-${name}`,pwd:'owned-detail-password',level:1,roles:String(id),adminType:1,status:1,isDel:0})));
    for(const id of Object.values(actors))tokens.set(id,(await createToken(id,'admin',md5('owned-detail-password'),env.APP_KEY)).token);
    guard=vi.spyOn(globalThis,'fetch').mockRejectedValue(Error('No product design HTTP provider'));},30000);
  afterEach(async()=>{try{expect(guard).not.toHaveBeenCalled();}finally{guard?.mockRestore();wiring.container=undefined;tokens.clear();await f?.close();}},30000);
  const profiles=(run:(admin:any)=>Promise<void>)=>f.withRuntimeRole(appPeer=>f.withRuntimeRole(async admin=>{await f.installSlice(appPeer,admin);wiring.container=createContainerFromDb(appPeer.db);Object.assign(env,{HYPERDRIVE:{connectionString:appPeer.connectionString} as Env['HYPERDRIVE'],HYPERDRIVE_ADMIN:{connectionString:admin.connectionString} as Env['HYPERDRIVE_ADMIN']});try{await run(admin);}finally{wiring.container=undefined;}}));
  async function request(prefix:string,actor:number|null,suffix='',method='GET',body?:unknown,path='/config/product-detail-design'){
    const response=await app.request(prefix+path+suffix,{method,headers:{...(actor===null?{}:{Authorization:`Bearer ${tokens.get(actor)}`}),...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})},env);return{response,body:await response.json<{status:number;msg:string;data:any}>()};}
  const input=(revision:string)=>({operationId:crypto.randomUUID(),revision,value:cloneProductDetailDesign()});
  it.each(['/adminapi','/api/admin'])('uses the dedicated route before generic config, preserving exact save and actor receipt on %s',async prefix=>{await profiles(async()=>{const initial=await request(prefix,actors.reader),body=input(initial.body.data.revision);expect(initial.body).toMatchObject({status:200,data:{configured:true,editable:true,value:{isOpen:[3,4,5,1,2,0]}}});expect(initial.response.headers.get('Cache-Control')).toContain('no-store');const saved=await request(prefix,actors.manager,'/save','POST',body);expect(saved.body.data).toEqual({operation:'update',id:5,operationId:body.operationId,payloadHash:await themeHash(productDetailDesignInput(body).canonical)});expect((await request(prefix,actors.manager,`/receipt/${body.operationId}`)).body.data).toEqual(saved.body.data);const committed=await f.settingsSnapshot();expect((await request(prefix,actors.manager,'/save','POST',body)).body.data).toEqual(saved.body.data);expect(await f.settingsSnapshot()).toEqual(committed);expect((await request(prefix,actors.second,`/receipt/${body.operationId}`)).response.status).toBe(404);});});
  it('maps only the exact installed1594 path/auth to view and denies borrowed generic privileges and forged pairs',async()=>{await profiles(async admin=>{const before=await f.settingsSnapshot();for(const prefix of['/adminapi','/api/admin']){const initial=await request(prefix,actors.reader),body=input(initial.body.data.revision);for(const actor of[actors.reader,actors.legacy]){expect((await request(prefix,actor)).body.status).toBe(200);expect((await request(prefix,actor,'/save','POST',body)).body.status).toBe(400011);}for(const actor of[actors.generic,actors.wrongPath,actors.wrongAuth])expect((await request(prefix,actor)).body.status).toBe(400011);expect((await request(prefix,null)).body.status).toBe(410000);}const permissions=new AdminPermissionService(createContainerFromDb(admin.db));expect(await permissions.resolveRulePermissionKeys('1594')).toEqual(['product_detail_design.view']);expect(await permissions.resolveManyRulePermissionKeys(['1594','91001','91002'])).toEqual([['product_detail_design.view'],[],[]]);for(const patch of[{type:2},{authType:2},{access:0},{isDel:1}]){await f.db.update(systemMenus).set({type:1,authType:1,access:1,isDel:0,...patch}).where(eq(systemMenus.id,1594));expect(await permissions.resolveRulePermissionKeys('1594')).toEqual([]);}expect(await f.settingsSnapshot()).toEqual(before);});});
  it('closes normalized wrong-type generic save/delete and hides raw opaque design from generic listing',async()=>{await profiles(async()=>{await f.db.update(systemDise).set({type:1,templateName:' PRODUCT_DETAIL '}).where(eq(systemDise.id,5));const before=await f.settingsSnapshot();for(const prefix of['/adminapi','/api/admin']){const list=await request(prefix,actors.generic,'','GET',undefined,'/dise/list');expect(JSON.stringify(list.body.data)).not.toContain('PRIVATE OPAQUE');const saved=await request(prefix,actors.generic,'','POST',{id:5,name:'旁路',value:'{}'},'/dise/save');expect(saved.body.status).not.toBe(200);const deleted=await request(prefix,actors.generic,'','DELETE',undefined,'/dise/del/5');expect(deleted.body.status).not.toBe(200);}expect(await f.settingsSnapshot()).toEqual(before);});});
  it('emits only matching pre-DML stale/invalid catalog proofs and keeps SQL failure outcomes unknown',async()=>{await profiles(async()=>{const initial=(await request('/adminapi',actors.manager)).body.data,body=input(initial.revision);await request('/adminapi',actors.manager,'/save','POST',body);const stale=input(initial.revision),before=await f.settingsSnapshot(),response=await request('/adminapi',actors.manager,'/save','POST',stale);expect(response.response.status).toBe(409);expect(response.body).toMatchObject({status:409,data:{code:'PRODUCT_DETAIL_DESIGN_STALE_VERSION',operation:'update',operationId:stale.operationId,payloadHash:await themeHash(productDetailDesignInput(stale).canonical)}});expect(await f.settingsSnapshot()).toEqual(before);await f.db.update(systemDise).set({value:'{"replyNum":0}'}).where(eq(systemDise.id,5));const bad=input((await request('/adminapi',actors.manager)).body.data.revision),rejected=await request('/adminapi',actors.manager,'/save','POST',bad);expect(rejected.response.status).toBe(400);expect(rejected.body.data.code).toBe('PRODUCT_DETAIL_DESIGN_REJECTED');
    await f.db.update(systemDise).set({value:JSON.stringify(cloneProductDetailDesign())}).where(eq(systemDise.id,5));const pending=input((await request('/adminapi',actors.manager)).body.data.revision),stable=await f.settingsSnapshot();await f.exec("CREATE FUNCTION reject_detail_http_journal() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.type='product_detail_design' THEN RAISE EXCEPTION 'owned late HTTP journal failure'; END IF; RETURN NEW; END $$");await f.exec('CREATE TRIGGER owned_reject_detail_http_journal BEFORE INSERT ON system_log FOR EACH ROW EXECUTE FUNCTION reject_detail_http_journal()');const unknown=await request('/adminapi',actors.manager,'/save','POST',pending);expect(unknown.body.status).not.toBe(200);expect(JSON.stringify(unknown.body.data??{})).not.toMatch(/PRODUCT_DETAIL_DESIGN_(?:REJECTED|STALE_VERSION)/);expect(await f.settingsSnapshot()).toEqual(stable);expect((await request('/adminapi',actors.manager,`/receipt/${pending.operationId}`)).response.status).toBe(404);
  });});
  it('returns the public nineteen-key intersection while real community HTTP pages exclude unrelated or unpublished posts',async()=>{await profiles(async()=>{const named=await request('/api/v2',null,'','GET',undefined,'/diy/get_diy/product_detail');expect(Object.keys(named.body.data)).toHaveLength(19);expect(JSON.stringify(named.body.data)).not.toMatch(/opaque|PRIVATE/);const first=await request('/api',null,'?page=1&limit=1','GET',undefined,'/product/70/community'),second=await request('/api',null,'?page=2&limit=1','GET',undefined,'/product/70/community');expect(first.body).toMatchObject({status:200,data:{list:[{id:201}],count:2}});expect(second.body).toMatchObject({status:200,data:{list:[{id:202}],count:2}});for(const q of['?page=0','?limit=101','?page=1&page=2','?owner=11'])expect((await request('/api',null,q,'GET',undefined,'/product/70/community')).body.status).not.toBe(200);});});
});
