import{describe,it,expect}from'vitest';
import{cloneUserCenterDesign,isUserCenterDesignValue}from'../../view/common/userCenterDesign';
import{userCenterDesignInput}from'../src/services/admin/AdminUserCenterDesignInput';
import{requiredAdminPermission,normalizeRoleRules}from'../src/services/admin/AdminPermissionService';
describe('complete user-center transport and exact capability',()=>{
  it('keeps historical video ordinal4 and validates all six modules without accepting opaque input',()=>{const value=cloneUserCenterDesign();expect(value.member.property).toEqual([0,1,2,3,4]);expect(isUserCenterDesignValue(value)).toBe(true);for(const bad of[{...value,member:{...value.member,style:2}},{...value,menu:{...value.menu,style:4}},{...value,opaque:'bad'}])expect(isUserCenterDesignValue(bad)).toBe(false);});
  it('binds fixed deep canonical order and UUID separate from full collection revision',()=>{const value=cloneUserCenterDesign(),revision='a'.repeat(64),operationId=crypto.randomUUID();expect(userCenterDesignInput({operationId,revision,value}).canonical).toEqual({operation:'update',revision,value});for(const body of[{operationId,revision,value,unknown:1},{operationId:'bad',revision,value},{operationId,revision:'stale',value},{operationId,revision,value:{...value,member:{...value.member,property:[4,4]}}}])expect(()=>userCenterDesignInput(body)).toThrow();});
  it('resolves dedicated view and manage ahead of generic config and rejects borrowed grants',()=>{for(const prefix of['/adminapi','/api/admin']){expect(requiredAdminPermission('GET',prefix+'/config/user-center-design')).toBe('user_center_design.view');expect(requiredAdminPermission('GET',prefix+'/config/user-center-design/assets')).toBe('user_center_design.view');expect(requiredAdminPermission('POST',prefix+'/config/user-center-design/save')).toBe('user_center_design.manage');}expect(normalizeRoleRules('user_center_design.manage')).toContain('user_center_design.view');expect(normalizeRoleRules('dise.manage')).not.toContain('user_center_design');});
});
