import {beforeAll,afterAll,beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {and,asc,eq,sql} from 'drizzle-orm';
import {Hono} from 'hono';
import {customerWorkWriteoffFixture} from './helpers/customerWorkWriteoffFixture';
import {createContainerFromDb,type DbClient} from '../src/lib/di';
import {storeOrder,storeOrderCartInfo,storeOrderWriteoff,storeOrderRefund,storeOrderStatus,storeOrderOutbox,storeService,storeServiceRecord,storePink,storeProduct,storeProductAttrValue,systemConfig,user,userBill,userBrokerage,supplierFlowingWater,supplierTransactions,systemSupplier,storePromotions,storeOrderPromotions} from '../src/models/schema';
import {CustomerWorkWriteoffService} from '../src/services/customer-work/CustomerWorkWriteoffService';
import {CUSTOMER_WRITEOFF_READ_VERSION,prepareWriteoff,type WriteoffInput} from '../src/services/customer-work/CustomerWorkWriteoffProtocol';
import {customerWriteoffLinePrice} from '../src/services/customer-work/CustomerWorkWriteoffSalePrice';
import {authorizeCustomerWorkActor} from '../src/services/customer-work/CustomerWorkScope';
import {StoreMobileOrderService} from '../src/services/store/StoreMobileOrderService';
import {StoreOrderWriteoffService} from '../src/services/order/StoreOrderWriteoffService';
import {applyOrderRefund,applyOrderRefundWithMaterialization,applyCashierZeroRefundWithMaterialization,StoreOrderRefundService} from '../src/services/order/StoreOrderRefundService';
import {CustomerWorkFinancialService} from '../src/services/customer-work/CustomerWorkFinancialService';
import {financialRevisions} from '../src/services/customer-work/CustomerWorkFinancialReadService';
import {CUSTOMER_FINANCIAL_QUOTE_VERSION} from '../src/services/customer-work/CustomerWorkFinancialProtocol';
import {customerWriteoffOperationReadiness,inspectCustomerWriteoffOperation} from '../src/migrations/runCustomerWriteoffOperation';
import {readCashierSecondCardOrigin,prepareCashierZeroRefund,type CashierZeroRefundCapability} from '../src/services/order/CashierSecondCardOrigin';
import {authMiddleware} from '../src/middleware/auth';
import {createToken,md5} from '../src/utils/jwt';
import {ApiException} from '../src/utils/errors';
import * as Controller from '../src/controllers/api/v1/CustomerWorkWriteoffController';
import type {Env,AppVariables} from '../src/env';
import {storeOrderRefundSplit} from '../src/models/schema/order_refund_split';
import type {CustomerWorkWriteoffRowEvidence} from '../../view/common/customerWorkWriteoff';

/** Every N01..N32 binding is exercised against a registered owned PG16
 * database and independently authenticated ordinary LOGIN. No provider HTTP,
 * fabricated core return value or seed masquerading as a creation is accepted. */
describe.runIf(Boolean(process.env.TEST_FINANCE_POSTGRES_URL))('native ordinary customer scan and partial writeoff',()=>{
 let f:Awaited<ReturnType<typeof customerWorkWriteoffFixture>>,service:CustomerWorkWriteoffService,guard:ReturnType<typeof vi.spyOn>;
 beforeAll(async()=>{f=await customerWorkWriteoffFixture();},60000);afterAll(async()=>{await f?.close();},30000);
 beforeEach(async()=>{await f.reset();service=f.service();guard=vi.spyOn(globalThis,'fetch').mockRejectedValue(Error('No external HTTP is accepted by native writeoff'));});
 afterEach(()=>{try{expect(guard).not.toHaveBeenCalled();}finally{vi.restoreAllMocks();}});
 const context=(key=crypto.randomUUID(),uid=101)=>({actor:f.actor(uid),request_key:key});
 const carts=(id=1)=>f.db.select().from(storeOrderCartInfo).where(eq(storeOrderCartInfo.oid,id)).orderBy(asc(storeOrderCartInfo.id));
 const records=(id=1)=>f.db.select().from(storeOrderWriteoff).where(eq(storeOrderWriteoff.oid,id)).orderBy(asc(storeOrderWriteoff.id));
 const receiptRows=()=>f.db.execute(sql`SELECT * FROM public.customer_writeoff_operation_request ORDER BY actor_uid,request_key`);
 const target=async(id=1)=>{const o=await f.order(id),s=await f.scope();return(await service.reader.order(f.actor(),id,{scope_key:s.scope_key,order_no:o.orderId})).data;};
 const lookup=async(namespace:'auto'|'order-code'|'member-barcode'|'legacy-order-id',value:string)=>(await service.reader.lookup(f.actor(),{version:CUSTOMER_WRITEOFF_READ_VERSION,scope_key:(await f.scope()).scope_key,namespace,value})).data;
 async function rejected(work:()=>Promise<unknown>){const before=await f.effects();let result:unknown,error:unknown;try{result=await work();}catch(e){error=e;}expect(error||result&&typeof result==='object'&&'receipt' in result&&(result as {receipt?:{outcome?:string}}).receipt?.outcome==='rollback-rejected').toBeTruthy();expect(await f.effects()).toEqual(before);}
 const execute=(body:WriteoffInput,key=crypto.randomUUID())=>service.execute(context(key),body);
 async function held<T>(lock:(db:DbClient)=>Promise<void>,work:()=>Promise<T>,ordinary=false){const run=async(db:DbClient)=>{let acquired!:()=>void,release!:()=>void;const ready=new Promise<void>(r=>acquired=r),gate=new Promise<void>(r=>release=r);const owner=db.transaction(async tx=>{await lock(tx as unknown as DbClient);acquired();await gate;});await ready;try{return await work();}finally{release();await owner;}};return ordinary?f.withPeer(async peer=>run(peer)):run(f.maintenanceDb);}
 async function configuration(values:Record<string,string>){for(const[menuName,value]of Object.entries(values)){await f.maintenanceDb.delete(systemConfig).where(eq(systemConfig.menuName,menuName));await f.maintenanceDb.insert(systemConfig).values({menuName,value});await f.env.CONFIG_KV.delete('cfg_'+menuName);}}
 async function waitForBlocking(pid:number){const deadline=Date.now()+5000;while(Date.now()<deadline){const[row]=await f.maintenanceDb.execute<{blockers:number[]}>(sql`SELECT pg_blocking_pids(${pid}) AS blockers`);if(row.blockers.length){console.log('NATIVE_WRITEOFF_ORDER_WAIT',JSON.stringify({pid,blockers:row.blockers}));return row.blockers;}await new Promise(resolve=>setTimeout(resolve,20));}throw Error('Actual order-lock waiting was not observed');}
 async function cashierTwoGenerations(){
  const genuine=await f.cashier(11,'0.00',3),originalOrder=genuine.order,originalOrigin=await f.db.execute(sql`SELECT order_id,request_key,origin_hash,origin FROM public.cashier_second_card_origin_v1 WHERE order_id=${originalOrder.id}`),originalPayment=await f.db.execute(sql`SELECT order_id,request_key,request_hash,evidence FROM public.cashier_second_card_payment_v1 WHERE order_id=${originalOrder.id}`);let current=originalOrder;
  const promotionBoundary=async(generation:number)=>{const rows=await carts(current.id),snapshots=rows.map(row=>JSON.parse(row.cartInfo!)),[authority]=await f.db.execute<{runtime:string;ledger_count:string;delete_privilege:boolean}>(sql`SELECT current_user::text AS runtime,(SELECT count(*)::text FROM public.store_order_promotions WHERE oid=${current.id}) AS ledger_count,pg_catalog.has_table_privilege(current_user,'public.store_order_promotions','DELETE') AS delete_privilege`);expect(authority.runtime).toBe(f.role);expect(authority.ledger_count).toBe('0');expect(authority.delete_privilege).toBe(false);for(const snapshot of snapshots){expect(snapshot).not.toHaveProperty('promotion_quote_version');expect(snapshot).not.toHaveProperty('promotion_allocations');expect(snapshot).not.toHaveProperty('promotion_segments');}console.log('NATIVE_WRITEOFF_ZERO_PROMOTION',JSON.stringify({generation,order_id:current.id,runtime:authority.runtime,ledger_count:authority.ledger_count,delete_privilege:authority.delete_privilege,cart_info:rows.map(row=>({cart_row_id:row.id,cart_info:row.cartInfo}))}));};
  await promotionBoundary(0);
  for(let generation=0;generation<2;generation++){
   const row=(await carts(current.id))[0],scope=await f.scope(),params={uid:current.uid,orderId:current.orderId,applyType:4,privilegedActor:'customer-work' as const,selectorNamespace:'row' as const,refundReason:'原生零元次卡真实退款',refundExplain:'真实选一张卡',cartSelections:[{cartId:row.id,cartNum:1}],expectedRefundAmountCents:0,requestedRefundAmountCents:0,resolveRefundTimeDays:async()=>0,authorizeApplication:async(db:DbClient,locked:typeof current)=>{const authority=await authorizeCustomerWorkActor(db,f.actor());expect(authority.scope_key).toBe(scope.scope_key);expect(locked.id).toBe(current.id);}};
   await expect(applyOrderRefundWithMaterialization(f.container,params,0)).rejects.toThrow();
   await expect(applyCashierZeroRefundWithMaterialization(f.container,params,{} as CashierZeroRefundCapability,0)).rejects.toThrow();
   const capability=await prepareCashierZeroRefund(f.db,f.actor(),scope.scope_key,current.id),application=await applyCashierZeroRefundWithMaterialization(f.container,params,capability,0);
   const actualRefund=(await f.db.select().from(storeOrderRefund).where(eq(storeOrderRefund.id,application.refundId)))[0];
   await new StoreOrderRefundService(f.container,f.env).agreeRefund(application.refundId,{expectedStoreOrderId:current.id,expectedRefundOrderId:actualRefund.orderId,expectedRefundAmountCents:0,requireSystemVisible:true,requirePaid:true,authorizeLockedDecision:async(db,refund,order)=>{const authority=await authorizeCustomerWorkActor(db,f.actor());expect(authority.scope_key).toBe(scope.scope_key);expect(refund.id).toBe(application.refundId);expect(order.id).toBe(current.id);}});
   const split=(await f.db.select().from(storeOrderRefundSplit).where(eq(storeOrderRefundSplit.refundId,application.refundId)))[0];expect(split?.remainingOrderId).toBeGreaterThan(0);current=await f.order(split.remainingOrderId!);const remaining=await carts(current.id),proof=await readCashierSecondCardOrigin(f.db,current,remaining);expect(proof).toMatchObject({root_order_id:originalOrder.id,root_order_no:originalOrder.orderId,creator_kind:'customer',creator_id:101});expect(remaining.reduce((n,c)=>n+c.cartNum,0)).toBe(2-generation);await promotionBoundary(generation+1);
  }
  expect(await f.db.execute(sql`SELECT order_id,request_key,origin_hash,origin FROM public.cashier_second_card_origin_v1 WHERE order_id=${originalOrder.id}`)).toEqual(originalOrigin);expect(await f.db.execute(sql`SELECT order_id,request_key,request_hash,evidence FROM public.cashier_second_card_payment_v1 WHERE order_id=${originalOrder.id}`)).toEqual(originalPayment);expect((await execute(await f.input(current.id))).execution).toMatchObject({verified:true,order_completed:true});
  const scope=await f.scope();await expect(prepareCashierZeroRefund(f.db,f.actor(),scope.scope_key,1)).rejects.toThrow();
  const guest=await f.cashier(0,'0.00',3),guestRow=(await carts(guest.order.id))[0];await expect(prepareCashierZeroRefund(f.db,f.actor(),scope.scope_key,guest.order.id)).rejects.toThrow();const guestParams={uid:guest.order.uid,orderId:guest.order.orderId,applyType:4,privilegedActor:'customer-work' as const,selectorNamespace:'row' as const,refundReason:'游客不能伪造账户退款',refundExplain:'真实游客来源',cartSelections:[{cartId:guestRow.id,cartNum:1}],expectedRefundAmountCents:0,requestedRefundAmountCents:0};await expect(applyOrderRefundWithMaterialization(f.container,guestParams,0)).rejects.toThrow();await expect(applyCashierZeroRefundWithMaterialization(f.container,{...guestParams,uid:11},{} as CashierZeroRefundCapability,0)).rejects.toThrow();
 }
 async function refundWriteoffRace(){await f.reset();const o=await f.ordinary(),row=(await carts(o.id))[0],body=await f.input(o.id),results=await f.withPeer(async peer=>Promise.allSettled([execute(body),applyOrderRefundWithMaterialization(createContainerFromDb(peer),{uid:11,orderId:o.orderId,applyType:4,privilegedActor:'customer-work',selectorNamespace:'row',refundReason:'独立LOGIN真实退款竞争',refundExplain:'同支付结算锁',cartSelections:[{cartId:row.id,cartNum:1}],authorizeApplication:async(db,current)=>{await authorizeCustomerWorkActor(db,f.actor());expect(current.id).toBe(o.id);}},0)]));const successes=results.filter(r=>r.status==='fulfilled'&&('refundId' in r.value||'receipt' in r.value&&r.value.receipt?.outcome==='written-off'));expect(successes).toHaveLength(1);const applications=await f.db.select().from(storeOrderRefund).where(eq(storeOrderRefund.storeOrderId,o.id));expect((await records(o.id)).length+applications.length).toBe(1);}
 async function windowEdges(id:number,start:number,end:number){const clock=vi.spyOn(Date,'now');try{for(const at of [start,end]){clock.mockReturnValue(at*1000);expect((await target(id)).actions.writeoff.available).toBe(true);const row=(await carts(id))[0];expect((await execute(await f.input(id,[{cart_row_id:row.id,writeoff_num:1}]))).execution?.verified).toBe(true);}for(const at of [start-1,end+1]){clock.mockReturnValue(at*1000);expect((await target(id)).actions.writeoff.available).toBe(false);await rejected(async()=>execute(await f.input(id,[{cart_row_id:(await carts(id))[0].id,writeoff_num:1}])));}}finally{clock.mockRestore();}}

 it('N01 genuine unique customer1/chat0 UserJWT uses an independent ordinary LOGIN and actual core',async()=>{const[role]=await f.db.execute<{current:string;session:string;super:boolean;forge:boolean}>(sql`SELECT current_user AS current,session_user AS session,(SELECT rolsuper FROM pg_roles WHERE rolname=current_user) AS super,has_column_privilege(current_user,'store_service','customer','UPDATE') AS forge`);expect(role).toEqual({current:f.role,session:f.role,super:false,forge:false});const result=await execute(await f.input(1,[{cart_row_id:1,writeoff_num:2}]));expect(result.receipt).toMatchObject({actor_uid:101,service_id:1,outcome:'partial-writtenoff'});expect(result.execution).toMatchObject({state:'SQL_COMMITTED',verified:true,committed:true});expect((await records())[0]).toMatchObject({uid:11,staffId:0,isAdmin:0,adminId:0,writeoffNum:2,writeoffPrice:'10.00'});});
 it('N02 rejects role/account/delete/duplicate, expired digest and changed original scope',async()=>{for(const patch of [{customer:0},{accountStatus:0},{isDel:1},{merId:8}]){const body=await f.input();await f.maintenanceDb.update(storeService).set(patch).where(eq(storeService.id,1));await rejected(()=>execute(body));await f.maintenanceDb.update(storeService).set({customer:1,accountStatus:1,isDel:0,merId:0}).where(eq(storeService.id,1));}const body=await f.input();await f.maintenanceDb.insert(storeService).values({id:8,uid:101,customer:1,accountStatus:1,status:0});await rejected(()=>execute(body));await f.maintenanceDb.delete(storeService).where(eq(storeService.id,8));for(const actor of [{...f.actor(),auth_version:md5('wrong')},{...f.actor(),expires_at:1}])await rejected(()=>service.execute({actor,request_key:crypto.randomUUID()},body));await f.maintenanceDb.update(user).set({deleteTime:new Date()}).where(eq(user.uid,101));await rejected(()=>execute(body));});
 it('N03 rejects legacy auth0 and every client operator/forged kind without granting another realm',async()=>{const old=new StoreMobileOrderService(f.container,f.env);await expect(old.writeoffInfo(101,0,'123456789001',f.actor())).rejects.toThrow('仅支持手机订单管理员或配送员');const body=await f.input();for(const field of ['actor','adminId','staffId','delivery_id','kind'])await rejected(()=>service.execute(context(),{...body,[field]:field==='kind'?'admin':1}));expect(await receiptRows()).toEqual([]);});
 it('N04 treats colliding twelve digit member and order codes as explicit distinct namespaces',async()=>{await f.maintenanceDb.update(user).set({barCode:'123456789001'}).where(eq(user.uid,11));await expect(lookup('auto','123456789001')).rejects.toThrow('歧义');expect((await lookup('order-code','123456789001')).orders.map(o=>o.id)).toEqual([1]);expect((await lookup('member-barcode','123456789001')).orders.map(o=>o.id).sort()).toEqual([1,2,3]);expect(await receiptRows()).toEqual([]);});
 it('N05 fails closed for duplicate codes/barcodes and returns all zero/100 member orders or refuses 101',async()=>{await f.maintenanceDb.update(storeOrder).set({verifyCode:'123456789001'}).where(eq(storeOrder.id,2));await expect(lookup('order-code','123456789001')).rejects.toThrow('不唯一');await f.maintenanceDb.update(storeOrder).set({verifyCode:'123456789002'}).where(eq(storeOrder.id,2));await f.maintenanceDb.update(user).set({barCode:'owned-member'}).where(sql`${user.uid} IN(11,102)`);await expect(lookup('member-barcode','owned-member')).rejects.toThrow('多个');await f.maintenanceDb.update(user).set({barCode:'empty-member'}).where(eq(user.uid,102));expect((await lookup('member-barcode','empty-member')).orders).toEqual([]);for(let id=4;id<=100;id++)await f.maintenanceDb.insert(storeOrder).values({id,orderId:'member-order-'+id,unique:'member-unique-'+id,uid:11,paid:1,payType:'yue',status:0,shippingType:2,storeId:1});expect((await lookup('member-barcode','owned-member')).orders).toHaveLength(100);await f.maintenanceDb.insert(storeOrder).values({id:101,orderId:'member-order-101',unique:'member-unique-101',uid:11,paid:1,payType:'yue',status:0,shippingType:2,storeId:1});await expect(lookup('member-barcode','owned-member')).rejects.toThrow('超过完整读取容量');},30000);
 it('N06 binds actual physical PK/SN/root and only physical cart PK despite opaque and foreign aliases',async()=>{await f.maintenanceDb.update(storeOrder).set({pid:-1}).where(eq(storeOrder.id,2));await f.maintenanceDb.update(storeOrder).set({pid:2}).where(eq(storeOrder.id,1));const t=await target();expect(t).toMatchObject({id:1,order_no:'native-physical-1',root_order_id:2,root_order_no:'native-physical-2'});expect((await lookup('legacy-order-id','1')).orders[0]).toMatchObject({id:1,order_no:'native-physical-1'});await rejected(async()=>execute(await f.input(1,[{cart_row_id:2,writeoff_num:1}])));const body=await f.input(1,[{cart_row_id:1,writeoff_num:1}]);const result=await execute(body);expect(result.receipt?.evidence.writeoff_rows).toMatchObject([{cart_row_id:1,opaque_cart_id:'opaque-card-1'}]);await rejected(()=>execute({...body,payload:{...body.payload,items:[{cart_row_id:1,writeoff_num:1},{cart_row_id:1,writeoff_num:1}]}}));});
 it('N07 keeps target/records read-only, dual-bound, complete at 500 and refuses row/byte overflow',async()=>{const initial=await f.effects(),s=await f.scope();await expect(service.reader.order(f.actor(),1,{scope_key:s.scope_key,order_no:'foreign-SN'})).rejects.toThrow();await expect(service.reader.records(f.actor(),1,{scope_key:s.scope_key,order_no:'foreign-SN'})).rejects.toThrow();expect(await f.effects()).toEqual(initial);const original=(await carts())[0];for(let id=4;id<=502;id++)await f.maintenanceDb.insert(storeOrderCartInfo).values({...original,id,cartId:'cart-'+id,unique:'cart-'+id,cartInfo:JSON.stringify({...JSON.parse(original.cartInfo!),id:'cart-'+id})});expect((await target()).carts).toHaveLength(500);await f.maintenanceDb.insert(storeOrderCartInfo).values({...original,id:503,cartId:'cart-503',unique:'cart-503'});await expect(target()).rejects.toThrow('超过完整');await f.maintenanceDb.delete(storeOrderCartInfo).where(sql`${storeOrderCartInfo.id}>3`);await f.maintenanceDb.update(storeOrderCartInfo).set({cartInfo:' '.repeat(262145)}).where(eq(storeOrderCartInfo.id,1));await expect(target()).rejects.toThrow('超过完整');await f.maintenanceDb.update(storeOrderCartInfo).set({cartInfo:'{'}).where(eq(storeOrderCartInfo.id,1));expect((await target()).actions.writeoff.available).toBe(false);expect(await receiptRows()).toEqual([]);},30000);
 it('N08 actual checkout/balance/outbox uses sale7.00 and ignores later live SKU999',async()=>{const o=await f.ordinary(),row=(await carts(o.id))[0];expect(JSON.parse(row.cartInfo!)).toMatchObject({financial_version:'checkout-line-finance-v1',sum_price:'7.00'});await f.maintenanceDb.update(storeProductAttrValue).set({price:'999.00'}).where(eq(storeProductAttrValue.id,1));const result=await execute(await f.input(o.id,[{cart_row_id:row.id,writeoff_num:2}]));expect(result.execution?.verified).toBe(true);expect((await records(o.id))[0]).toMatchObject({writeoffNum:2,writeoffPrice:'14.00'});expect((await f.db.select().from(storeOrderOutbox).where(eq(storeOrderOutbox.aggregateId,o.id))).filter(r=>r.eventType==='order.paid')).toHaveLength(1);});
 it('N09 exact promotion/penny/member/coupon snapshot cannot fall back to a price or missing evidence',async()=>{
  const actual=await f.ordinary(),cart=(await carts(actual.id))[0],raw=JSON.parse(cart.cartInfo!);expect(customerWriteoffLinePrice(cart,1)).toBe('7.00');for(const key of ['sum_true_price','coupon_price','member_savings_version']){const damaged={...raw};delete damaged[key];await f.maintenanceDb.update(storeOrderCartInfo).set({cartInfo:JSON.stringify(damaged)}).where(eq(storeOrderCartInfo.id,cart.id));expect((await target(actual.id)).actions.writeoff.available).toBe(false);await f.maintenanceDb.update(storeOrderCartInfo).set({cartInfo:cart.cartInfo}).where(eq(storeOrderCartInfo.id,cart.id));}const corrupt={...raw,member_postage_price:'99.00',price_type:'member',paid_member:0};expect(()=>customerWriteoffLinePrice({...cart,cartInfo:JSON.stringify(corrupt)},1)).toThrow();
  await f.reset();const now=Math.floor(Date.now()/1000),[promotion]=await f.maintenanceDb.insert(storePromotions).values({pid:0,type:1,storeId:0,promotionsType:1,name:'真实首张次卡九折',discount:'90.00',productPartakeType:1,isLimit:1,limitNum:1,startTime:now-60,stopTime:now+3600,status:1,isDel:0,updateTime:now}).returning();
  const genuine=await f.cashier(11,'7.00',2),order=genuine.order,purchased=(await carts(order.id))[0],snapshot=JSON.parse(purchased.cartInfo!),paidEvents=await f.db.select().from(storeOrderOutbox).where(eq(storeOrderOutbox.eventType,'order.paid')).orderBy(asc(storeOrderOutbox.id));
  expect(order).toMatchObject({paid:1,payType:'cash',payPrice:'13.30',promotionsPrice:'0.70'});expect(purchased).toMatchObject({cartNum:2,writeTimes:6,writeSurplusTimes:6});expect(snapshot).toMatchObject({financial_version:'checkout-line-finance-v1',promotion_quote_version:'order-promotion-quote-v1',sum_true_price:'13.30',promotion_line_price:'13.30',promotion_line_savings:'0.70',promotion_discount_quantity:1,promotion_segments:[{quantity:1,totalPriceCents:630,unitPriceCents:630,promotionIds:[promotion.id]},{quantity:1,totalPriceCents:700,unitPriceCents:700,promotionIds:[]}]});expect(paidEvents).toHaveLength(1);expect(await readCashierSecondCardOrigin(f.db,order,[purchased])).toMatchObject({root_order_id:order.id,root_order_no:order.orderId});
  const booked=await f.db.select().from(storeOrderPromotions).where(eq(storeOrderPromotions.oid,order.id)).orderBy(asc(storeOrderPromotions.id)),beforeLockDenials=await f.effects(),[identity]=await f.db.execute<{runtime:string}>(sql`SELECT current_user::text AS runtime`);expect(identity.runtime).toBe(f.role);expect(booked).toHaveLength(1);expect(booked[0]).toMatchObject({oid:order.id,uid:11,promotionsId:promotion.id,productId:purchased.productId,promotionsPrice:'0.70'});
  const denied=async(work:()=>Promise<unknown>)=>{let error:unknown;try{await work();}catch(actual){error=actual;}let code:unknown;for(let depth=0;depth<8&&error&&typeof error==='object';depth++){if('code' in error){code=error.code;break;}if(!('cause' in error))break;error=error.cause;}expect(code).toBe('42501');};
  await denied(()=>f.db.execute(sql`UPDATE public.store_order_promotions SET id=id WHERE id=${booked[0].id}`));await denied(()=>f.db.execute(sql`UPDATE public.store_order_promotions SET promotions_price='99.00' WHERE id=${booked[0].id}`));expect(await f.db.select().from(storeOrderPromotions).where(eq(storeOrderPromotions.oid,order.id)).orderBy(asc(storeOrderPromotions.id))).toEqual(booked);expect(await f.effects()).toEqual(beforeLockDenials);expect(await f.db.select().from(storeOrderOutbox).where(eq(storeOrderOutbox.eventType,'order.paid')).orderBy(asc(storeOrderOutbox.id))).toEqual(paidEvents);expect((await f.order(order.id)).payPrice).toBe('13.30');
  const expected=['6.30','6.30','6.30','7.00','7.00','7.00'],keys:string[]=[];
  for(let index=0;index<expected.length;index++){
   const key=crypto.randomUUID(),body=await f.input(order.id,[{cart_row_id:purchased.id,writeoff_num:1}]),result=await execute(body,key),evidence=result.receipt!.evidence,rowEvidence=evidence.writeoff_rows as unknown as CustomerWorkWriteoffRowEvidence[];keys.push(key);expect(result.execution).toMatchObject({state:'SQL_COMMITTED',verified:true,order_completed:index===5});expect(rowEvidence).toMatchObject([{cart_row_id:purchased.id,quantity:1,before_remaining:6-index,after_remaining:5-index,writeoff_price:expected[index]}]);expect(rowEvidence[0].snapshot_hash).toMatch(/^[a-f0-9]{64}$/);expect(rowEvidence[0].sale_price_hash).toMatch(/^[a-f0-9]{64}$/);expect((await records(order.id))[index]).toMatchObject({writeoffNum:1,writeoffPrice:expected[index]});expect((await carts(order.id))[0].cartInfo).toBe(purchased.cartInfo);
   if(index<5)expect(evidence.settlement).toBeNull();else expect(evidence.settlement).toMatchObject({version:'customer-writeoff-settlement-v1',new_paid_outbox_count:0,paid_root:{order_id:order.id,order_no:order.orderId,pay_price:'13.30',paid:1},paid_outbox_rows:[{row_id:paidEvents[0].id,event_key:paidEvents[0].eventKey}]});
   const effects=await f.effects();expect((await execute(body,key))).toMatchObject({replayed:true,receipt:result.receipt,execution:{verified:true}});expect(await f.effects()).toEqual(effects);
  }
  expect((await records(order.id)).map(r=>r.writeoffPrice)).toEqual(expected);expect((await f.order(order.id))).toMatchObject({status:2,verifyCode:''});for(const key of keys)expect((await service.status(f.actor(),key)).execution?.verified).toBe(true);expect(await f.db.select().from(storeOrderOutbox).where(eq(storeOrderOutbox.eventType,'order.paid')).orderBy(asc(storeOrderOutbox.id))).toEqual(paidEvents);
 },30000);
 it('N10 genuine cashier create/cash/original paidoutbox/window supports member, guest0 and zero price',async()=>{for(const[buyer,price]of [[11,'7.00'],[0,'7.00'],[0,'0.00'],[11,'0.00']] as const){await f.reset();const before=(await f.db.select().from(storeProductAttrValue).where(eq(storeProductAttrValue.id,1)))[0].stock,genuine=await f.cashier(buyer,price),o=genuine.order,row=(await carts(o.id))[0],proof=await readCashierSecondCardOrigin(f.db,o,[row]);expect(o).toMatchObject({uid:buyer,paid:1,payType:'cash',shippingType:2,storeId:0,productType:4});expect(proof).toMatchObject({creator_kind:'customer',creator_id:101,root_order_id:o.id,root_order_no:o.orderId});expect((await f.db.select().from(storeProductAttrValue).where(eq(storeProductAttrValue.id,1)))[0].stock).toBe(before-2);const result=await execute(await f.input(o.id,[{cart_row_id:row.id,writeoff_num:6}]));expect(result.execution).toMatchObject({verified:true,order_completed:true});expect((await records(o.id))[0].writeoffPrice).toBe(price==='0.00'?'0.00':'42.00');const s=result.receipt!.evidence.settlement as unknown as {paid_root:{uid:number};account_deltas:Array<{uid:number}>};expect(s.paid_root.uid).toBe(buyer);expect(s.account_deltas.every(a=>a.uid>0)).toBe(true);}},60000);
 it('N11 rejects invented store0/virtual/integral/unpaid/cart ownership and corrupt origin',async()=>{for(const patch of [{storeId:0},{shippingType:1,productType:1,deliveryType:''},{type:4},{paid:0},{uid:0}]){const body=await f.input();await f.maintenanceDb.update(storeOrder).set(patch).where(eq(storeOrder.id,1));if(patch.type===4){expect((await target()).actions.writeoff).toMatchObject({available:false,reason:'积分兑换订单不属于普通用户核销范围'});await rejected(async()=>execute(await f.input()));}else await rejected(()=>execute(body));await f.maintenanceDb.update(storeOrder).set({storeId:1,shippingType:2,productType:4,type:0,paid:1,uid:11,deliveryType:''}).where(eq(storeOrder.id,1));}const genuine=await f.cashier(),body=await f.input(genuine.order.id);await f.maintenanceDb.update(storeOrderCartInfo).set({uid:102}).where(eq(storeOrderCartInfo.oid,genuine.order.id));await rejected(()=>execute(body));});
 it('N12 true qty2/sku3 gives six entitlements: partial2, partial3, final1',async()=>{const code=(await f.order()).verifyCode;for(const[q,remaining,outcome]of [[2,4,'partial-writtenoff'],[3,1,'partial-writtenoff'],[1,0,'written-off']] as const){const result=await execute(await f.input(1,[{cart_row_id:1,writeoff_num:q}]));expect(result.receipt?.outcome).toBe(outcome);expect((await carts())[0].writeSurplusTimes).toBe(remaining);expect((await f.order()).status).toBe(remaining?5:2);expect((await f.order()).verifyCode).toEqual(remaining?expect.stringMatching(/^\d{12}$/):'');expect((await f.order()).verifyCode).not.toBe(code);}expect((await records()).map(r=>r.writeoffPrice)).toEqual(['10.00','15.00','5.00']);});
 it('N13 actual paid activation of unlimited/days/fixed windows preserves exact boundaries and replay',async()=>{for(const valid of [1,2,3]){await f.reset();const now=Math.floor(Date.now()/1000);await f.maintenanceDb.update(storeProductAttrValue).set({writeValid:valid,writeDays:2,writeStart:now-10,writeEnd:now+3600}).where(eq(storeProductAttrValue.id,1));const genuine=await f.cashier(),o=genuine.order,row=(await carts(o.id))[0];if(valid===1)expect([row.writeStart,row.writeEnd]).toEqual([0,0]);else if(valid===2)expect([row.writeStart,row.writeEnd]).toEqual([o.payTime,o.payTime+2*86400]);else expect([row.writeStart,row.writeEnd]).toEqual([now-10,now+3600]);expect(await genuine.consumer.processMessage(genuine.message)).toBe('already-completed');expect(await carts(o.id)).toEqual([row]);if(valid!==1)await windowEdges(o.id,row.writeStart,row.writeEnd);else expect((await execute(await f.input(o.id,[{cart_row_id:row.id,writeoff_num:1}]))).execution?.verified).toBe(true);}},60000);
 it('N14 multiple carts complete only when all remaining reach zero; strict quantity/selection rejects',async()=>{const first=(await carts())[0];await f.maintenanceDb.insert(storeOrderCartInfo).values({...first,id:4,cartId:'second-card',unique:'second-card',cartInfo:JSON.stringify({...JSON.parse(first.cartInfo!),id:'second-card'})});const a=await execute(await f.input(1,[{cart_row_id:1,writeoff_num:6}]));expect(a.receipt?.outcome).toBe('partial-writtenoff');expect((await f.order()).status).toBe(5);const b=await f.input(1,[{cart_row_id:4,writeoff_num:6}]);for(const q of [0,-1,7,1.5])await rejected(()=>execute({...b,payload:{...b.payload,items:[{cart_row_id:4,writeoff_num:q}]}}));await rejected(()=>execute({...b,payload:{...b.payload,items:[]}}));expect((await execute(b)).receipt?.outcome).toBe('written-off');});
 it('N15 read and write reject unpaid/deleted/split/allocation or incorrect shipping assignment',async()=>{for(const patch of [{paid:0},{isDel:1},{isSystemDel:1},{pid:-1},{supplierAllocationStatus:1},{shippingType:1,deliveryType:'express'},{shippingType:1,deliveryType:'send',deliveryUid:0}]){const body=await f.input();await f.maintenanceDb.update(storeOrder).set(patch).where(eq(storeOrder.id,1));await rejected(()=>execute(body));await f.maintenanceDb.update(storeOrder).set({paid:1,isDel:0,isSystemDel:0,pid:0,supplierAllocationStatus:0,shippingType:2,deliveryType:'',deliveryUid:0}).where(eq(storeOrder.id,1));}});
 it('N16 a genuine active refund application and a held real settlement lock forbid late writeoff',async()=>{const o=await f.ordinary();await applyOrderRefund(f.container,{uid:11,orderId:o.orderId,applyType:1,refundReason:'原生顾客申请',refundExplain:'真实申请',cartSelections:[{cartId:(await carts(o.id))[0].id,cartNum:1}]});expect((await f.db.select().from(storeOrderRefund).where(eq(storeOrderRefund.storeOrderId,o.id)))).toHaveLength(1);expect((await target(o.id)).actions.writeoff.available).toBe(false);const body=await f.input(1,[{cart_row_id:1,writeoff_num:1}]);await held(db=>db.execute(sql`SELECT pg_advisory_xact_lock(63842,1)`).then(()=>undefined),async()=>{await f.withPeer(async peer=>{const loser=new CustomerWorkWriteoffService(createContainerFromDb(peer),f.env);await rejected(()=>loser.execute(context(),body));});});await refundWriteoffRace();},30000);
 it('N17 real financial refund materialization leaves a provable modern remaining generation',async()=>{const o=await f.ordinary(),finance=new CustomerWorkFinancialService(f.container,f.env),scope=await f.scope(),revision=await financialRevisions(f.db,o),q=(await finance.reader.quote(f.actor(),{version:CUSTOMER_FINANCIAL_QUOTE_VERSION,scope_key:scope.scope_key,order_id:o.id,expected_order_revision:revision.order_revision,expected_financial_revision:revision.financial_revision,mode:'items',items:[{cart_row_id:(await carts(o.id))[0].id,cart_num:1}]})).data;const created=await finance.create(context(),{version:'customer-work-financial-operation-v1',scope_key:scope.scope_key,order_id:o.id,expected_order_revision:revision.order_revision,expected_financial_revision:revision.financial_revision,payload:{mode:'items',items:q.items.map(i=>({cart_row_id:i.cart_row_id,cart_num:i.cart_num})),quoted_price:q.quoted_price,refund_price:q.quoted_price,quote_fingerprint:q.quote_fingerprint,reason:'真实退款后继续核销'}});const rid=Number(created.receipt!.evidence.refund_id),r=(await f.db.select().from(storeOrderRefund).where(eq(storeOrderRefund.id,rid)))[0],review=(await finance.reader.review(f.actor(),rid,{refund_no:r.orderId})).data,current=await financialRevisions(f.db,await f.order(o.id));await finance.execute('refund_execute',context(),{version:'customer-work-financial-operation-v1',scope_key:scope.scope_key,order_id:o.id,expected_order_revision:current.order_revision,expected_financial_revision:current.financial_revision,payload:{refund_id:rid,refund_no:r.orderId,expected_refund_revision:review.refund_revision,review_fingerprint:review.review_fingerprint,decision:{apply_type:review.apply_type,refund_type:review.refund_type,received:false},refund_price:review.refund_price}});const children=await f.db.select().from(storeOrder).where(eq(storeOrder.pid,o.id)),remaining=children.find(c=>c.refundPrice==='0.00'&&c.status!==2);expect(remaining).toBeTruthy();const t=await target(remaining!.id);expect(t.actions.writeoff.available).toBe(true);expect((await execute(await f.input(remaining!.id))).execution?.verified).toBe(true);await cashierTwoGenerations();},60000);
 it('N18 real group pending and presale boundary disable dispatch; completed group allows core',async()=>{
  const app=new Hono<{Bindings:Env;Variables:AppVariables}>();app.use('*',async(c,next)=>{c.set('container',f.container);await next();});app.use('*',authMiddleware({force:true}));app.post('/writeoff/execute',Controller.writeoffExecute);app.onError((e,c)=>c.json({status:e instanceof ApiException?e.code:500,msg:e.message,data:null},400));const token=(await createToken(101,'api',md5('owned-financial-password'),f.env.APP_KEY)).token;
  const integralApiReject=async()=>{expect((await target()).actions.writeoff).toMatchObject({available:false,reason:'积分兑换订单不属于普通用户核销范围'});const body=await f.input(1,[{cart_row_id:1,writeoff_num:1}]),before=await f.effects(),response=await app.request('/writeoff/execute',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(body)},f.env);expect(response.status).toBe(200);expect(await response.json()).toMatchObject({status:200,data:{receipt:{kind:'writeoff',outcome:'rollback-rejected'},execution:null}});expect(await f.effects()).toEqual(before);};
  await f.maintenanceDb.update(storeOrder).set({type:4}).where(eq(storeOrder.id,1));await integralApiReject();await f.maintenanceDb.update(storeOrder).set({type:0,pid:2}).where(eq(storeOrder.id,1));await f.maintenanceDb.update(storeOrder).set({type:4,pid:-1}).where(eq(storeOrder.id,2));await integralApiReject();await f.maintenanceDb.update(storeOrder).set({type:0,pid:0}).where(sql`${storeOrder.id} IN(1,2)`);
  await f.maintenanceDb.insert(storePink).values({id:701,uid:11,status:1});await f.maintenanceDb.update(storeOrder).set({type:3,pinkId:701}).where(eq(storeOrder.id,1));expect((await target()).actions.writeoff.available).toBe(false);await f.maintenanceDb.update(storePink).set({status:2}).where(eq(storePink.id,701));expect((await execute(await f.input(1,[{cart_row_id:1,writeoff_num:1}]))).execution?.verified).toBe(true);await f.reset();const row=(await carts())[0],info=JSON.parse(row.cartInfo!);info.productInfo.presale_end_time=String(Math.floor(Date.now()/1000)+3600);await f.maintenanceDb.update(storeOrderCartInfo).set({cartInfo:JSON.stringify(info)}).where(eq(storeOrderCartInfo.id,1));await f.maintenanceDb.update(storeOrder).set({type:6}).where(eq(storeOrder.id,1));expect((await target()).actions.writeoff.available).toBe(false);info.productInfo.presale_end_time=String(Math.floor(Date.now()/1000)-1);await f.maintenanceDb.update(storeOrderCartInfo).set({cartInfo:JSON.stringify(info)}).where(eq(storeOrderCartInfo.id,1));expect((await execute(await f.input(1,[{cart_row_id:1,writeoff_num:1}]))).execution?.verified).toBe(true);
 });
 it('N19 original full-intent UUID replay changes SQL once; stale rotated code under a new UUID fails',async()=>{const key=crypto.randomUUID(),body=await f.input(1,[{cart_row_id:1,writeoff_num:1}]),first=await execute(body,key),after=await f.effects();const again=await execute(body,key);expect(again).toMatchObject({replayed:true,receipt:first.receipt,execution:{verified:true}});expect(await f.effects()).toEqual(after);await rejected(()=>execute(body));expect(await records()).toHaveLength(1);});
 it('N20 exact UUID/fullbody binding rejects conflicting body/order and foreign owner sees no receipt',async()=>{const key=crypto.randomUUID(),body=await f.input(1,[{cart_row_id:1,writeoff_num:1}]);await execute(body,key);await expect(execute(await f.input(2),key)).rejects.toMatchObject({httpStatus:409});await expect(service.abandon(f.actor(),key,{kind:'admin',input:body},key)).rejects.toThrow();expect((await service.status(f.actor(102),key)).receipt).toBeNull();expect((await service.status(f.actor(),key)).execution?.verified).toBe(true);});
 it('N21 two real independent LOGINs serialize the same code; fresh current code permits exactly one next selection',async()=>{const body=await f.input(1,[{cart_row_id:1,writeoff_num:1}]),a=context(),b=context();const outcomes=await f.withPeer(async(peer,pid)=>{const[current]=await f.db.execute<{pid:number}>(sql`SELECT pg_backend_pid() AS pid`);expect(pid).not.toBe(current.pid);return Promise.allSettled([service.execute(a,body),new CustomerWorkWriteoffService(createContainerFromDb(peer),f.env).execute(b,body)]);});console.log('NATIVE_WRITEOFF_CONCURRENT',JSON.stringify(outcomes.map(r=>r.status==='fulfilled'?{status:r.status,outcome:r.value.receipt?.outcome,execution:r.value.execution}: {status:r.status,message:String(r.reason?.message??r.reason),code:r.reason?.code,cause:{message:r.reason?.cause?.message,code:r.reason?.cause?.code},stack:r.reason?.stack})));expect(outcomes.filter(r=>r.status==='fulfilled'&&r.value.receipt?.outcome==='partial-writtenoff')).toHaveLength(1);expect(await records()).toHaveLength(1);expect((await execute(await f.input(1,[{cart_row_id:1,writeoff_num:1}]))).execution?.verified).toBe(true);expect(await records()).toHaveLength(2);});
 it('N22 late role revoke while waiting on the actual order lock rolls back and original absent key can abandon',async()=>{const body=await f.input(1,[{cart_row_id:1,writeoff_num:1}]),key=crypto.randomUUID(),[identity]=await f.db.execute<{pid:number}>(sql`SELECT pg_backend_pid() AS pid`);await held(db=>db.select({id:storeOrder.id}).from(storeOrder).where(eq(storeOrder.id,1)).for('update').then(()=>undefined),async()=>{const pending=execute(body,key).then(value=>({value,error:null}),error=>({value:null,error}));await waitForBlocking(identity.pid);await f.maintenanceDb.update(storeService).set({customer:0}).where(eq(storeService.id,1));await rejected(async()=>{const settled=await pending;if(settled.error)throw settled.error;return settled.value;});},true);await f.maintenanceDb.update(storeService).set({customer:1}).where(eq(storeService.id,1));const prior=await service.status(f.actor(),key);if(prior.receipt)expect(prior.receipt.outcome).toBe('rollback-rejected');else expect((await service.abandon(f.actor(),key,{kind:'writeoff',input:body},key)).receipt?.outcome).toBe('abandoned');},10000);
 it('N23 held maintenance ledger table gives bounded refusal; release recovers with original UUID',async()=>{const body=await f.input(1,[{cart_row_id:1,writeoff_num:1}]),key=crypto.randomUUID();await held(db=>db.execute(sql`LOCK TABLE public.customer_writeoff_operation_request IN ACCESS EXCLUSIVE MODE`).then(()=>undefined),async()=>{await expect(execute(body,key)).rejects.toThrow();});expect((await execute(body,key)).execution?.verified).toBe(true);const committed=await service.status(f.actor(),key);expect(committed.receipt?.request_key).toBe(key);},15000);
 it('N24 genuine SQL phase faults in record/operator/quantity/price/cart counters roll back the complete transaction',async()=>{
  const business=async()=>({effects:await f.effects(),audit:await f.db.select().from(storeOrderStatus).orderBy(asc(storeOrderStatus.id)),outbox:await f.db.select().from(storeOrderOutbox).orderBy(asc(storeOrderOutbox.id)),accounts:await f.db.select().from(user).orderBy(asc(user.uid)),rewards:await f.db.select().from(userBill).orderBy(asc(userBill.id)),brokerage:await f.db.select().from(userBrokerage).orderBy(asc(userBrokerage.id)),supplier:await f.db.select().from(supplierFlowingWater).orderBy(asc(supplierFlowingWater.id)),transactions:await f.db.select().from(supplierTransactions).orderBy(asc(supplierTransactions.id))});
  const faults=[...['NEW.uid:=102','NEW.order_cart_id:=2','NEW.product_id:=71','NEW.staff_id:=901','NEW.writeoff_num:=NEW.writeoff_num+1','NEW.writeoff_price:=99','NEW.writeoff_code:=\'999999999999\''].map(body=>({table:'store_order_writeoff',event:'INSERT',body:body+';RETURN NEW;'})),{table:'store_order_writeoff',event:'INSERT',body:'RETURN NULL;'},{table:'store_order_cart_info',event:'UPDATE',body:'NEW.write_surplus_times:=NEW.write_surplus_times+1;RETURN NEW;'},{table:'store_order_status',event:'INSERT',body:"IF NEW.change_type='customer_order_writeoff' THEN NEW.change_message:='真实SQL审计故障';END IF;RETURN NEW;"}];
  for(const fault of faults){
   const body=await f.input(1,[{cart_row_id:1,writeoff_num:1}]),key=crypto.randomUUID(),before=await business();
   await f.exec(`CREATE FUNCTION public.native_writeoff_fault() RETURNS trigger LANGUAGE plpgsql AS $body$ BEGIN ${fault.body}END $body$;CREATE TRIGGER native_writeoff_fault BEFORE ${fault.event} ON public.${fault.table} FOR EACH ROW EXECUTE FUNCTION public.native_writeoff_fault()`);
   try{await rejected(()=>execute(body,key));}finally{await f.exec(`DROP TRIGGER native_writeoff_fault ON public.${fault.table};DROP FUNCTION public.native_writeoff_fault()`);}
   expect(await business()).toEqual(before);let original=await service.status(f.actor(),key);
   if(!original.receipt)original=await service.abandon(f.actor(),key,{kind:'writeoff',input:body},key);
   expect(['rollback-rejected','abandoned']).toContain(original.receipt!.outcome);expect(original.execution).toBeNull();
   const ledger=(await receiptRows()).filter((r:Record<string,unknown>)=>r.request_key===key);expect(ledger).toHaveLength(1);expect(ledger[0]).toMatchObject({actor_uid:101,order_id:1,request_hash:original.receipt!.request_hash,intent:body});
   expect((await service.status(f.actor(),key)).receipt).toEqual(original.receipt);expect(await business()).toEqual(before);expect((await receiptRows()).filter((r:Record<string,unknown>)=>r.request_key===key)).toEqual(ledger);
  }
  expect(await records()).toEqual([]);
 },30000);
 it('N25 partial never settles; final atomically records actual rewards/commission/accounts/status once',async()=>{await configuration({order_give_integral:'1',order_give_exp:'1',brokerage_func_status:'1',store_brokerage_statu:'1'});await f.maintenanceDb.update(storeOrder).set({gainIntegral:'2',spreadUid:102,oneBrokerage:'1.00'}).where(eq(storeOrder.id,1));await f.maintenanceDb.update(user).set({isPromoter:1,spreadOpen:1}).where(eq(user.uid,102));await execute(await f.input(1,[{cart_row_id:1,writeoff_num:1}]));expect(await f.db.select().from(userBill)).toEqual([]);expect(await f.db.select().from(userBrokerage)).toEqual([]);expect(await f.db.select().from(storeOrderStatus).where(eq(storeOrderStatus.changeType,'take_delivery'))).toEqual([]);const key=crypto.randomUUID(),body=await f.input(),final=await execute(body,key),s=final.receipt!.evidence.settlement as unknown as {reward_rows:unknown[];brokerage_rows:unknown[];account_deltas:unknown[];take_delivery_status_id:number};expect(s.reward_rows.length).toBeGreaterThan(0);expect(s.brokerage_rows.length).toBeGreaterThan(0);expect(s.take_delivery_status_id).toBeGreaterThan(0);const bills=await f.db.select().from(userBill),commissions=await f.db.select().from(userBrokerage);await execute(body,key);expect(await f.db.select().from(userBill)).toEqual(bills);expect(await f.db.select().from(userBrokerage)).toEqual(commissions);});
 it('N26 retains genuine paid event/digest and supplier settlement without creating a second paid event',async()=>{
  const o=await f.ordinary(),event=(await f.db.select().from(storeOrderOutbox).where(and(eq(storeOrderOutbox.aggregateId,o.id),eq(storeOrderOutbox.eventType,'order.paid'))))[0];const result=await execute(await f.input(o.id)),s=result.receipt!.evidence.settlement as unknown as {paid_outbox_rows:Array<{row_id:number;event_key:string}>;new_paid_outbox_count:number};expect(s).toMatchObject({new_paid_outbox_count:0,paid_outbox_rows:[{row_id:event.id,event_key:event.eventKey}]});expect(await f.db.select().from(storeOrderOutbox).where(eq(storeOrderOutbox.eventType,'order.paid'))).toHaveLength(1);expect(await f.db.select().from(supplierFlowingWater)).toEqual([]);
  await f.reset();await f.maintenanceDb.insert(systemSupplier).values({id:88,supplierName:'真实次卡供应商',isShow:1,isDel:0}).onConflictDoNothing();await f.maintenanceDb.update(storeProduct).set({type:2,relationId:88}).where(eq(storeProduct.id,70));await f.maintenanceDb.update(storeProductAttrValue).set({settlePrice:'4.00'}).where(eq(storeProductAttrValue.id,1));
  const supplierOrder=await f.ordinary(),row=(await carts(supplierOrder.id))[0],flows=()=>f.db.select().from(supplierFlowingWater).where(eq(supplierFlowingWater.linkId,supplierOrder.orderId)).orderBy(asc(supplierFlowingWater.id)),transactions=()=>f.db.select().from(supplierTransactions).where(eq(supplierTransactions.linkId,supplierOrder.orderId)).orderBy(asc(supplierTransactions.id)),originalFlow=await flows(),originalTransactions=await transactions(),paidBefore=await f.db.select().from(storeOrderOutbox).where(eq(storeOrderOutbox.eventType,'order.paid')).orderBy(asc(storeOrderOutbox.id));
  expect(supplierOrder).toMatchObject({supplierId:88,supplierAllocationStatus:2,uid:11,paid:1});expect(row.settlePrice).toBe('4.00');expect(originalFlow).toHaveLength(1);expect(originalFlow[0]).toMatchObject({supplierId:88,uid:11,linkId:supplierOrder.orderId,orderId:'P'+supplierOrder.orderId,number:'8.00',pm:1,type:1,status:0,finishTime:0,isDel:0});expect(originalTransactions).toHaveLength(1);expect(originalTransactions[0]).toMatchObject({supplierId:88,uid:11,orderId:'P'+supplierOrder.orderId,linkId:supplierOrder.orderId});expect(paidBefore).toHaveLength(1);
  const partial=await execute(await f.input(supplierOrder.id,[{cart_row_id:row.id,writeoff_num:1}]));expect(partial.execution?.verified).toBe(true);expect(partial.receipt!.evidence.settlement).toBeNull();expect(await flows()).toEqual(originalFlow);expect(await transactions()).toEqual(originalTransactions);
  const key=crypto.randomUUID(),body=await f.input(supplierOrder.id),final=await execute(body,key),settlement=final.receipt!.evidence.settlement as unknown as {supplier_rows:Array<{row_id:number;before_status:number;after_status:number;amount:string;pm:number;type:number}>;new_paid_outbox_count:number};expect(final.execution).toMatchObject({state:'SQL_COMMITTED',verified:true,order_completed:true});expect(settlement.supplier_rows).toEqual([{row_id:originalFlow[0].id,before_status:0,after_status:1,amount:'8.00',pm:1,type:1}]);expect(settlement.new_paid_outbox_count).toBe(0);
  const finishedFlow=await flows(),businessAfter=await f.effects();expect(finishedFlow).toHaveLength(1);expect(finishedFlow[0]).toEqual({...originalFlow[0],status:1,finishTime:expect.any(Number)});expect(finishedFlow[0].finishTime).toBeGreaterThan(0);expect(await transactions()).toEqual(originalTransactions);expect(await f.db.select().from(storeOrderOutbox).where(eq(storeOrderOutbox.eventType,'order.paid')).orderBy(asc(storeOrderOutbox.id))).toEqual(paidBefore);
  const recovered=await service.status(f.actor(),key);expect(recovered.receipt).toEqual(final.receipt);expect(recovered.execution?.verified).toBe(true);expect((await execute(body,key))).toMatchObject({replayed:true,receipt:final.receipt,execution:{verified:true}});expect(await flows()).toEqual(finishedFlow);expect(await transactions()).toEqual(originalTransactions);expect(await f.effects()).toEqual(businessAfter);expect(await f.db.select().from(storeOrderOutbox).where(eq(storeOrderOutbox.eventType,'order.paid')).orderBy(asc(storeOrderOutbox.id))).toEqual(paidBefore);
 },30000);
 it('N27 all earlier partial UUIDs retain immutable SQL proof after final and legitimate later metadata changes',async()=>{
  const keys: string[]=[];for(const q of [1,2,3]){const key=crypto.randomUUID();keys.push(key);await execute(await f.input(1,[{cart_row_id:1,writeoff_num:q}]),key);}
  await f.maintenanceDb.update(storeOrder).set({mark:'顾客后来补充备注'}).where(eq(storeOrder.id,1));for(const key of keys)expect((await service.status(f.actor(),key)).execution?.verified).toBe(true);expect(await records()).toHaveLength(3);
  const ledgerBefore=await receiptRows(),effectsBefore=await f.effects(),original=(await service.status(f.actor(),keys[0])).receipt,actualRecord=(await records())[0],actualCart=(await carts())[0];
  const assertUnknown=async()=>{const result=await service.status(f.actor(),keys[0]);expect(result.receipt).toEqual(original);expect(result.execution).toMatchObject({request_key:keys[0],request_hash:original!.request_hash,state:'UNKNOWN',committed:false,verified:false,order_completed:false});expect(result.execution!.reason.length).toBeGreaterThan(0);expect(await receiptRows()).toEqual(ledgerBefore);};
  await f.maintenanceDb.update(storeOrderWriteoff).set({writeoffPrice:'99.00'}).where(eq(storeOrderWriteoff.id,actualRecord.id));try{await assertUnknown();}finally{await f.maintenanceDb.update(storeOrderWriteoff).set({writeoffPrice:actualRecord.writeoffPrice}).where(eq(storeOrderWriteoff.id,actualRecord.id));}
  expect((await service.status(f.actor(),keys[0])).execution).toMatchObject({state:'SQL_COMMITTED',committed:true,verified:true});expect(await f.effects()).toEqual(effectsBefore);
  const damaged=JSON.parse(actualCart.cartInfo!);damaged.productInfo.store_name='维护检测真实快照损坏';await f.maintenanceDb.update(storeOrderCartInfo).set({cartInfo:JSON.stringify(damaged)}).where(eq(storeOrderCartInfo.id,actualCart.id));try{await assertUnknown();}finally{await f.maintenanceDb.update(storeOrderCartInfo).set({cartInfo:actualCart.cartInfo}).where(eq(storeOrderCartInfo.id,actualCart.id));}
  expect((await service.status(f.actor(),keys[0])).execution).toMatchObject({state:'SQL_COMMITTED',committed:true,verified:true});expect(await receiptRows()).toEqual(ledgerBefore);expect(await f.effects()).toEqual(effectsBefore);
 },15000);
 it('N28 records bind the actual customer operator distinct from buyer; unproven legacy zeros stay unknown',async()=>{await execute(await f.input(1,[{cart_row_id:1,writeoff_num:1}]));const s=await f.scope(),o=await f.order(),data=(await service.reader.records(f.actor(),1,{scope_key:s.scope_key,order_no:o.orderId})).data;expect(data.list[0].operator).toMatchObject({kind:'customer',actor_uid:101,service_id:1});expect(data.list[0].operator.actor_uid).not.toBe(o.uid);await f.maintenanceDb.insert(storeOrderWriteoff).values({uid:11,oid:1,orderCartId:1,productId:70,productType:4,writeoffNum:1,writeoffPrice:'5.00',writeoffCode:'000000000000'});const after=(await service.reader.records(f.actor(),1,{scope_key:s.scope_key,order_no:o.orderId})).data;expect(after.list.find(r=>r.operator.kind==='unknown')?.operator.actor_uid).toBeNull();});
 it('N29 all six real HTTP handlers enforce UserJWT/private/UTF8/query/UUID original-path contract',async()=>{const app=new Hono<{Bindings:Env;Variables:AppVariables}>();app.use('*',async(c,next)=>{c.set('container',f.container);await next();});app.use('*',authMiddleware({force:true}));app.post('/writeoff/lookup',Controller.writeoffLookup);app.get('/writeoff/orders/:id',Controller.writeoffOrder);app.get('/writeoff/orders/:id/records',Controller.writeoffRecords);app.post('/writeoff/execute',Controller.writeoffExecute);app.get('/writeoff/operations/:key',Controller.writeoffOperationStatus);app.post('/writeoff/operations/:key/abandon',Controller.abandonWriteoffOperation);app.onError((e,c)=>c.json({status:e instanceof ApiException?e.code:500,msg:e.message,data:null},400));const token=(await createToken(101,'api',md5('owned-financial-password'),f.env.APP_KEY)).token,admin=(await createToken(101,'admin',md5('owned-financial-password'),f.env.APP_KEY)).token,s=await f.scope(),body=await f.input(1,[{cart_row_id:1,writeoff_num:1}]),key=crypto.randomUUID(),headers={Authorization:'Bearer '+token,'Content-Type':'application/json','Idempotency-Key':key};const read=await app.request('/writeoff/lookup',{method:'POST',headers:{Authorization:headers.Authorization,'Content-Type':'application/json'},body:JSON.stringify({version:CUSTOMER_WRITEOFF_READ_VERSION,scope_key:s.scope_key,namespace:'legacy-order-id',value:'1'})},f.env);expect(read.status).toBe(200);expect(read.headers.get('Cache-Control')).toBe('private, no-store');for(const path of ['/writeoff/orders/1?scope_key='+s.scope_key+'&order_no=native-physical-1','/writeoff/orders/1/records?scope_key='+s.scope_key+'&order_no=native-physical-1'])expect((await app.request(path,{headers},f.env)).status).toBe(200);for(const patch of [{Authorization:'Bearer '+admin},{'Content-Type':'text/plain'},{'Content-Encoding':'gzip'},{'Idempotency-Key':'00000000-0000-0000-0000-000000000000'}] as Record<string,string>[])expect((await app.request('/writeoff/execute',{method:'POST',headers:{...headers,...patch},body:JSON.stringify(body)},f.env)).status).not.toBe(200);expect((await app.request('/writeoff/orders/1?scope_key='+s.scope_key+'&scope_key='+s.scope_key+'&order_no=native-physical-1',{headers},f.env)).status).not.toBe(200);expect((await app.request('/writeoff/execute',{method:'POST',headers,body:JSON.stringify(body)},f.env)).status).toBe(200);expect((await app.request('/writeoff/operations/'+key,{headers},f.env)).status).toBe(200);expect((await app.request('/writeoff/operations/'+key+'/abandon',{method:'POST',headers,body:JSON.stringify({kind:'writeoff',input:body})},f.env)).status).toBe(200);});
 it('N30 exact13-column catalog/two validators/append ACL rejects direct malformed SQL and mutation authority',async()=>{expect((await inspectCustomerWriteoffOperation(f.db)).complete).toBe(true);expect((await customerWriteoffOperationReadiness(f.db)).ready).toBe(true);const[shape]=await f.db.execute<{columns:number;validators:number;mutate:boolean}>(sql`SELECT(SELECT count(*)::integer FROM pg_attribute WHERE attrelid='public.customer_writeoff_operation_request'::regclass AND attnum>0 AND NOT attisdropped) AS columns,(SELECT count(*)::integer FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname IN('customer_writeoff_intent_valid_v1','customer_writeoff_evidence_valid_v1')) AS validators,has_table_privilege(current_user,'public.customer_writeoff_operation_request','UPDATE,DELETE,TRUNCATE') AS mutate`);expect(shape).toEqual({columns:13,validators:2,mutate:false});const body=await f.input(),p=await prepareWriteoff(context(),body);await expect(f.db.execute(sql`INSERT INTO public.customer_writeoff_operation_request(actor_uid,request_key,request_hash,service_id,order_id,kind,outcome,scope_key,expected_revision,expected_writeoff_revision,intent,evidence) VALUES(101,${p.key}::uuid,${p.hash},0,1,'writeoff','abandoned',${body.scope_key},${body.expected_order_revision},${body.expected_writeoff_revision},'{}'::jsonb,'{}'::jsonb)`)).rejects.toThrow();await expect(f.db.execute(sql`UPDATE public.customer_writeoff_operation_request SET order_id=2`)).rejects.toThrow();});
 it('N31 mature staff/admin/delivery/kefu default actors and numeric/opaque selector behavior remain actual',async()=>{const core=new StoreOrderWriteoffService(f.container,f.env);expect((await core.info({kind:'admin',adminId:9},'123456789001')).id).toBe(1);expect((await core.info({kind:'staff',uid:104},'123456789001')).id).toBe(1);await f.maintenanceDb.update(storeOrder).set({shippingType:1,status:1,deliveryType:'send',deliveryUid:105}).where(eq(storeOrder.id,2));expect((await core.info({kind:'delivery',uid:105},'123456789002')).id).toBe(2);await f.maintenanceDb.insert(storeServiceRecord).values({id:901,userId:101,toUid:11,isTourist:0});expect((await core.info({kind:'kefu',kefuId:1,kefuUid:101},'123456789001')).id).toBe(1);const old=await core.execute({kind:'admin',adminId:9},{code:'123456789001',items:[{cartId:'opaque-card-1',quantity:1}]});expect(old.completed).toBe(false);expect((await records())[0]).toMatchObject({isAdmin:1,adminId:9,writeoffPrice:'10.00'});expect((await new StoreMobileOrderService(f.container,f.env).writeoffInfo(101,1,(await f.order()).verifyCode,f.actor()))[0].actor_kind).toBe('customer');});
 it('N32 historical store0 without genuine provenance explicitly refuses and cannot mint capability or success',async()=>{await f.maintenanceDb.update(storeOrder).set({storeId:0,payType:'cash',staffId:101,isChannel:2}).where(eq(storeOrder.id,1));const t=await target();expect(t.cashier_origin).toMatchObject({eligible:false,proof_hash:null});expect(t.actions.writeoff.available).toBe(false);expect(t.cashier_origin.reason.length).toBeGreaterThan(0);await rejected(async()=>execute(await f.input()));expect(await records()).toEqual([]);expect((await receiptRows()).every((r:Record<string,unknown>)=>r.outcome!=='written-off'&&r.outcome!=='partial-writtenoff')).toBe(true);});
});
