import {afterAll,beforeAll,beforeEach,describe,expect,it,vi} from 'vitest';
import {eq} from 'drizzle-orm';
import {createContainerFromDb,type DbClient} from '../src/lib/di';
import {createToken} from '../src/utils/jwt';
import {storeProduct,storeProductAttrValue,storeProductRelation,storeProductCategory,storeProductLabel,legacyCategory,storeCart,storeProductStockRecord,storeService,user,systemLog} from '../src/models/schema';
import {customerWorkProductFixture} from './helpers/customerWorkProductFixture';
import {observeIntegralReadDb} from './helpers/integralProductReadFixture';
import {CustomerWorkProductReadService,readCustomerProductState} from '../src/services/customer-work/CustomerWorkProductReadService';
import {prepareCustomerProductOperation,CUSTOMER_PRODUCT_OPERATION_VERSION,type CustomerProductOperationBody,type CustomerProductOperationKind} from '../src/services/customer-work/CustomerWorkProductOperationRequest';
import * as Core from '../src/services/product/MobileProductManagementCore';
import * as Frontend from '../../view/uniapp-ts/src/utils/customerWorkProductsContract';
import type {CustomerWorkProductBody,CustomerWorkProductIntent} from '../../view/uniapp-ts/src/types/customerWorkProducts';

describe.skipIf(!process.env.TEST_FINANCE_POSTGRES_URL)('customer products seven contracts ordinary LOGIN native PG16',()=>{
 let f:Awaited<ReturnType<typeof customerWorkProductFixture>>;
 beforeAll(async()=>{f=await customerWorkProductFixture();},60000);
 afterAll(async()=>{vi.restoreAllMocks();await f?.close();},60000);
 beforeEach(async()=>{vi.restoreAllMocks();await f.reset();},30000);
 const context=(key=crypto.randomUUID(),uid=101)=>({actor:f.actor(uid),request_key:key});
 const state=async()=>({products:await f.db.select().from(storeProduct),skus:await f.db.select().from(storeProductAttrValue),relations:await f.db.select().from(storeProductRelation),carts:await f.db.select().from(storeCart),stocks:await f.db.select().from(storeProductStockRecord),logs:await f.db.select().from(systemLog)});
 async function body(db:DbClient,payload:unknown,ids=[1]):Promise<CustomerProductOperationBody>{const reads=[];for(const id of ids)reads.push(await f.reader(db).skus(f.actor(),id));return{version:CUSTOMER_PRODUCT_OPERATION_VERSION,scope_key:reads[0].scope_key,targets:reads.map(r=>({product_id:r.data.product.id,expected_product_revision:r.data.product.product_revision})),expected_catalog_revision:reads[0].data.catalog_revision,payload:payload as CustomerProductOperationBody['payload']};}
 async function frontendIntent(kind:CustomerProductOperationKind,input:CustomerProductOperationBody,key:string):Promise<CustomerWorkProductIntent>{const wire=JSON.parse(JSON.stringify(input)) as CustomerWorkProductBody;return{version:'customer-work-product-pending-v1',actor_uid:101,service_id:1,scope_key:wire.scope_key,kind,request_key:key,request_hash:await Frontend.customerWorkProductIntentHash(101,kind,wire),body:wire,endpoint:Frontend.customerWorkProductEndpoint(kind,wire.targets.map(t=>t.product_id)),method:'POST',created_at:Date.now()};}
 const skuPayload=(unique='sku00001',stock=8)=>({attr_value:[{unique,price:'12.34',cost:'2.34',ot_price:'22.34',stock}]});
 async function reachedOrFinished(reached:Promise<void>,pending:Promise<unknown>){let timer:ReturnType<typeof setTimeout>|undefined;try{await Promise.race([reached,pending.then(()=>{throw Error('Actual write completed before the core-entry pause');}),new Promise<never>((_resolve,reject)=>{timer=setTimeout(()=>reject(Error('Actual core-entry pause was not reached')),7000);})]);}finally{if(timer)clearTimeout(timer);}}
 it('uses exact ordinary LOGIN, global ownership and actual base stock and real sales through all four actual frontend guards',async()=>f.app(async(db,role,peer)=>{
  expect((await peer.exec('SELECT current_user AS role,session_user AS session'))[0]).toEqual({role,session:role});
  const list=await f.reader(db).list(f.actor());expect(list.data.readiness).toEqual({writes:true,reason:''});expect(list.data.list.map(p=>p.id).sort()).toEqual([1,2,3,4,5,6]);
  const p=list.data.list.find(p=>p.id===1)!;expect(p).toMatchObject({stock:5,branch_stock:5,sales:3,branch_sales:3,sku_count:1,attr_value:{unique:'sku00001'}});expect(list.data.list.find(p=>p.id===2)).toMatchObject({type:1,relation_id:77,pid:1,stock:7,plate_name:'门店：真实门店'});expect(list.data.list.find(p=>p.id===3)).toMatchObject({type:2,relation_id:88,plate_name:'供应商：真实供应商'});
  const categories=await f.reader(db).categories(f.actor()),labels=await f.reader(db).labels(f.actor()),skus=await f.reader(db).skus(f.actor(),1);expect(Frontend.parseCustomerWorkProductEnvelope(list,101,Frontend.isCustomerWorkProductList,undefined,list.consistency_key)).toBe(list);expect(Frontend.parseCustomerWorkProductEnvelope(categories,101,Frontend.isCustomerWorkProductCategories,undefined,list.consistency_key)).toBe(categories);expect(Frontend.parseCustomerWorkProductEnvelope(labels,101,Frontend.isCustomerWorkProductLabels,undefined,list.consistency_key)).toBe(labels);expect(Frontend.parseCustomerWorkProductEnvelope(skus,101,Frontend.isCustomerWorkProductSkus,undefined,list.consistency_key)).toBe(skus);
  expect(JSON.stringify(skus)).not.toMatch(/diskInfo|disk_info|pwd|auth_version|PRIVATE/);expect(categories.data.categories.map(c=>c.id)).toEqual([10]);expect(categories.data.categories[0].children.map(c=>c.id)).toEqual([11]);expect(labels.data.labels.map(g=>g.id)).toEqual([1]);expect(labels.data.labels[0].children.map(l=>l.id)).toEqual([20]);
 }));
 it('reads real large taxonomy and derived association fields without borrowing any write-only limits',async()=>{
  const categoryIds=Array.from({length:24},(_,i)=>i+1),labelIds=Array.from({length:51},(_,i)=>1000+i),longName='分'.repeat(100);
  await f.db.insert(storeProductCategory).values(categoryIds.map(id=>({id,pid:0,cateName:longName,type:0,relationId:0,isShow:1}))).onConflictDoUpdate({target:storeProductCategory.id,set:{pid:0,cateName:longName,type:0,relationId:0,isShow:1}});
  await f.db.insert(storeProductCategory).values(Array.from({length:4977},(_,i)=>({id:1000+i,pid:i>0&&i<22?999+i:0,cateName:`真实目录${i}`,type:0,relationId:0,isShow:1})));
  await f.db.update(storeProductCategory).set({pic:'/legacy/category-first.png',bigPic:'/legacy/category-first-big.png'}).where(eq(storeProductCategory.id,1));await f.db.update(storeProductCategory).set({pic:'/legacy/category-last.png',bigPic:'/legacy/category-last-big.png',cateName:'😀'.repeat(100)}).where(eq(storeProductCategory.id,5976));
  await f.db.insert(legacyCategory).values(Array.from({length:1000},(_,i)=>({id:1000+i,name:`真实标签组${i}`,group:2,type:0,relationId:0,isShow:1})));
  await f.db.insert(storeProductLabel).values(Array.from({length:1000},(_,i)=>({id:1000+i,labelCate:1,labelName:`真实标签${i}`,type:0,relationId:0,status:1,isShow:1})));
  await f.db.update(legacyCategory).set({name:'😀'.repeat(255)}).where(eq(legacyCategory.id,1000));await f.db.update(storeProductLabel).set({labelName:'😀'.repeat(255),color:'😀'.repeat(32),bgColor:'😀'.repeat(32),borderColor:'😀'.repeat(32)}).where(eq(storeProductLabel.id,1000));
  await f.db.update(storeProductAttrValue).set({suk:'😀'.repeat(512),barCode:'😀'.repeat(50)}).where(eq(storeProductAttrValue.id,2));await f.db.update(storeProductAttrValue).set({unique:'😀'.repeat(8)}).where(eq(storeProductAttrValue.id,3));
  await f.db.update(storeProduct).set({cateId:categoryIds.join(','),storeLabelId:labelIds.join(','),storeName:'😀'.repeat(256)}).where(eq(storeProduct.id,2));
  await f.app(async db=>{
   const categories=await f.reader(db).categories(f.actor()),labels=await f.reader(db).labels(f.actor()),product=await f.reader(db).skus(f.actor(),2),rows=Frontend.customerWorkProductCategoryRows(categories.data.categories);
   expect(rows).toHaveLength(5001);expect(Math.max(...rows.map(row=>row.depth))).toBe(21);expect(labels.data.labels).toHaveLength(1001);expect(labels.data.labels.find(group=>group.id===1)?.children).toHaveLength(1001);
   expect(Frontend.parseCustomerWorkProductEnvelope(categories,101,Frontend.isCustomerWorkProductCategories)).toBe(categories);expect(Frontend.parseCustomerWorkProductEnvelope(labels,101,Frontend.isCustomerWorkProductLabels)).toBe(labels);expect(Frontend.parseCustomerWorkProductEnvelope(product,101,Frontend.isCustomerWorkProductSkus)).toBe(product);
   expect(categories.data.categories.find(node=>node.id===1)).toMatchObject({pic:'/legacy/category-first.png',big_pic:'/legacy/category-first-big.png'});expect(categories.data.categories.find(node=>node.id===5976)).toMatchObject({pic:'/legacy/category-last.png',big_pic:'/legacy/category-last-big.png',cate_name:'😀'.repeat(100)});
   expect(product.data.skus.find(row=>row.id===2)).toMatchObject({suk:'😀'.repeat(512),bar_code:'😀'.repeat(50)});expect(product.data.skus.find(row=>row.id===3)?.unique).toBe('😀'.repeat(8));expect(product.data.product).toMatchObject({actions:{skus:false},sku_policy:'invalid_sku_identity',store_name:'😀'.repeat(256)});expect(labels.data.labels.find(group=>group.id===1000)?.label_name).toBe('😀'.repeat(255));expect(labels.data.labels.find(group=>group.id===1)?.children.find(label=>label.id===1000)).toMatchObject({label_name:'😀'.repeat(255),color:'😀'.repeat(32),bg_color:'😀'.repeat(32),border_color:'😀'.repeat(32)});
   expect(product.data.product.store_label_id).toEqual(labelIds);expect(product.data.product.cate_name).toHaveLength(2423);expect(categoryIds.join(',')).toHaveLength(62);
   const before=await state();await expect(f.writer(db).batch(context(),await body(db,{store_label_id:labelIds},[2]))).rejects.toThrow('关联编号');await expect(f.writer(db).batch(context(),await body(db,{cate_id:Array.from({length:14},(_,i)=>1000+i)},[2]))).rejects.toThrow('历史字段容量');await expect(f.writer(db).updateSkus(context(),2,await body(db,skuPayload('😀'.repeat(8)),[2]))).rejects.toThrow('规格编号');expect(await state()).toEqual(before);expect(await f.exec('SELECT actor_uid FROM customer_product_operation_request')).toHaveLength(0);
  });
 },30000);
 it.each([['1',[1,2,4,5]],['2',[3]],['4',[5]],['5',[4]]] as const)('implements real old tab %s without imposing platform owner or inventory threshold',async(type,expected)=>f.app(async db=>expect((await f.reader(db).list(f.actor(),{type})).data.list.map(p=>p.id).sort()).toEqual([...expected])));
 it.each(['BASE-BAR','ACTIVITY-BAR'])('matches actual SKU barcode %s across activity types while listing only active base inventory',async keyword=>f.app(async db=>{const result=await f.reader(db).list(f.actor(),{store_name:keyword});expect(result.data.list.map(p=>p.id)).toEqual([1]);expect(result.data.list[0].stock).toBe(5);}));
 it('uses fuzzy product ID and store description search and deterministic paging without page reset',async()=>{await f.db.update(storeProduct).set({storeInfo:'needle actual description'}).where(eq(storeProduct.id,3));await f.app(async db=>{expect((await f.reader(db).list(f.actor(),{store_name:'3'})).data.list.map(p=>p.id)).toContain(3);expect((await f.reader(db).list(f.actor(),{store_name:'needle'})).data.list.map(p=>p.id)).toEqual([3]);const page=await f.reader(db).list(f.actor(),{page:'10',limit:'1'});expect(page.data).toMatchObject({list:[],count:6,page:10,limit:1,has_more:false});await expect(f.reader(db).list(f.actor(),{supplier_id:'88'})).rejects.toThrow();});});
 it('renders actual store static product and SKU pictures while refusing to sign assets under a synthetic platform owner',async()=>{await f.db.update(storeProduct).set({image:'https://example.test/store-product.png'}).where(eq(storeProduct.id,2));await f.db.update(storeProductAttrValue).set({image:'/legacy/store-sku.png'}).where(eq(storeProductAttrValue.id,2));await f.db.insert((await import('../src/models/schema')).systemAttachment).values({attId:41,type:1,relationId:0,moduleType:1,fileType:1,imageType:8,name:'attachments/admin/1/private.png',attDir:'/api/assets/41',attType:'image/png'});await f.app(async db=>{const first=await f.reader(db).skus(f.actor(),2);expect(first.data.product.image).toBe('https://example.test/store-product.png');expect(first.data.skus[0].image).toBe('/legacy/store-sku.png');expect(Frontend.isCustomerWorkProductSkus(first.data)).toBe(true);await f.db.update(storeProduct).set({image:'/api/assets/41'}).where(eq(storeProduct.id,2));await f.db.update(storeProductAttrValue).set({image:'/api/assets/41'}).where(eq(storeProductAttrValue.id,2));const blocked=await f.reader(db).skus(f.actor(),2);expect(blocked.data.product.image).toBe('');expect(blocked.data.skus[0].image).toBe('');});});
 it('atomically sets show on global explicit products and mirrors unpaid carts/category relations with actual customer receipt',async()=>f.app(async db=>{const input=await body(db,{is_show:0},[1,2,3]),ctx=context(),before=await state(),result=await f.writer(db).setShow(ctx,input);expect(result.receipt).toMatchObject({service_id:1,kind:'set_show',product_ids:[1,2,3],outcome:'products-updated',evidence:{changed:3,verified:true}});const after=await state();expect(after.products.filter(p=>[1,2,3].includes(p.id)).every(p=>p.isShow===0)).toBe(true);expect(after.carts.find(c=>c.id===1)?.status).toBe(0);expect(after.carts.find(c=>c.id===2)?.status).toBe(1);expect(after.relations.find(r=>r.id===1)?.status).toBe(0);expect(after.logs).toEqual(before.logs);expect(Frontend.parseCustomerWorkProductReceipt(result.receipt,await frontendIntent('set_show',input,ctx.request_key))).toEqual(result.receipt);}));
 it('rejects unreviewed show and deleted targets with no partial cart/product changes and owned rejection receipts',async()=>f.app(async db=>{const before=await state(),input=await body(db,{is_show:1},[1,6]),result=await f.writer(db).setShow(context(),input);expect(result.receipt).toMatchObject({service_id:0,outcome:'rollback-rejected'});expect(await state()).toEqual(before);}));
 it('replaces platform categories and labels on all owners and allows label clear while preserving unrelated relation types',async()=>f.app(async db=>{expect((await f.writer(db).batch(context(),await body(db,{cate_id:[11]},[1,2,3]))).receipt.outcome).toBe('products-updated');const categories=(await state()).relations.filter(r=>r.type===1);expect(categories.map(r=>[r.productId,r.relationId,r.relationPid]).sort()).toEqual([[1,11,10],[2,11,10],[3,11,10]]);expect((await f.writer(db).batch(context(),await body(db,{store_label_id:[]},[1]))).receipt.outcome).toBe('products-updated');const after=await state();expect(after.relations.filter(r=>r.productId===1&&r.type===3)).toHaveLength(0);expect(after.relations.filter(r=>r.productId===1&&r.type===1)).toHaveLength(1);expect(after.products.find(p=>p.id===1)?.storeLabelId).toBe('');}));
 it.each([{cate_id:[12]},{cate_id:[13]},{store_label_id:[21]},{store_label_id:[22]}])('rejects foreign/hidden taxonomy or a label belonging to a foreign group %j',async payload=>f.app(async db=>{const before=await state(),input=await body(db,payload);expect((await f.writer(db).batch(context(),input)).receipt.outcome).toBe('rollback-rejected');expect(await state()).toEqual(before);}));
 it('partially edits exact existing SKU unique while retaining other rows/activity/retirement and writes true stock difference',async()=>f.app(async db=>{const before=await state(),input=await body(db,skuPayload('sku00002',7),[2]),ctx=context(),result=await f.writer(db).updateSkus(ctx,2,input);expect(result.receipt).toMatchObject({kind:'update_skus',outcome:'skus-updated',evidence:{changed:1,verified:true}});const after=await state(),p=after.products.find(p=>p.id===2)!;expect(p).toMatchObject({stock:11,price:'15.00',cost:'3.00',otPrice:'25.00'});expect(after.skus.find(s=>s.id===2)).toMatchObject({stock:7,sumStock:7,sales:4,unique:'sku00002',suk:'实际规格2'});expect(after.skus.find(s=>s.id===3)).toEqual(before.skus.find(s=>s.id===3));expect(after.skus.filter(s=>s.type!==0||s.isRetired)).toEqual(before.skus.filter(s=>s.type!==0||s.isRetired));expect(after.stocks).toMatchObject([{storeId:77,productId:2,unique:'sku00002',number:4,pm:1}]);expect(Frontend.parseCustomerWorkProductReceipt(result.receipt,await frontendIntent('update_skus',input,ctx.request_key))).toEqual(result.receipt);}));
 it('records decrease with pm zero and omits zero stock delta records',async()=>f.app(async db=>{await f.writer(db).updateSkus(context(),1,await body(db,skuPayload('sku00001',2)));expect((await state()).stocks).toMatchObject([{number:3,pm:0,storeId:0}]);await f.writer(db).updateSkus(context(),1,await body(db,skuPayload('sku00001',2)));expect((await state()).stocks).toHaveLength(1);}));
 it('reads all 501 active base SKUs through the actual frontend guard and limits only each selected write batch',async()=>{
  await f.db.insert(storeProductAttrValue).values(Array.from({length:499},(_,i)=>f.sku(100+i,2)));
  await f.app(async db=>{
   const read=await f.reader(db).skus(f.actor(),2);expect(read.data.skus).toHaveLength(501);expect(read.data.product.actions.skus).toBe(true);expect(Frontend.parseCustomerWorkProductEnvelope(read,101,Frontend.isCustomerWorkProductSkus)).toBe(read);
   const all={attr_value:read.data.skus.map(s=>({unique:s.unique,price:s.price,cost:s.cost,ot_price:s.ot_price,stock:s.stock}))},before=await state();
   await expect(f.writer(db).updateSkus(context(),2,await body(db,all,[2]))).rejects.toThrow('有效规格');expect(await state()).toEqual(before);expect(await f.exec('SELECT actor_uid FROM customer_product_operation_request')).toHaveLength(0);
   const last=read.data.skus.at(-1)!,input=await body(db,{attr_value:[{unique:last.unique,price:last.price,cost:last.cost,ot_price:last.ot_price,stock:last.stock+1}]},[2]),ctx=context(),result=await f.writer(db).updateSkus(ctx,2,input);
   expect(result.receipt).toMatchObject({outcome:'skus-updated',evidence:{changed:1,verified:true}});expect(Frontend.parseCustomerWorkProductReceipt(result.receipt,await frontendIntent('update_skus',input,ctx.request_key))).toEqual(result.receipt);
   const after=await state();expect(after.skus.filter(s=>s.id!==last.id)).toEqual(before.skus.filter(s=>s.id!==last.id));expect(after.skus.find(s=>s.id===last.id)?.stock).toBe(last.stock+1);expect(after.products.find(p=>p.id===2)?.stock).toBe(read.data.product.stock+1);expect(after.stocks).toHaveLength(1);
  });
 },30000);
 it('rejects untouched corrupt negative inventory even when the remaining SKU sum is positive',async()=>f.app(async db=>{const input=await body(db,skuPayload('sku00002',7),[2]);await f.db.update(storeProductAttrValue).set({stock:-1}).where(eq(storeProductAttrValue.id,3));await expect(f.reader(db).skus(f.actor(),2)).rejects.toThrow('库存');const fresh=await readCustomerProductState(db,2),reviewed={...input,targets:[{product_id:2,expected_product_revision:fresh.revision}]},before=await state();expect((await f.writer(db).updateSkus(context(),2,reviewed)).receipt.outcome).toBe('rollback-rejected');expect(await state()).toEqual(before);}));
 it('rejects foreign/activity/retired SKU, stock overflow and price format without mutating stock ledgers',async()=>f.app(async db=>{const before=await state();for(const unique of['sku00002','sku00009','sku00010'])expect((await f.writer(db).updateSkus(context(),1,await body(db,skuPayload(unique)))).receipt.outcome).toBe('rollback-rejected');const overflow=await body(db,skuPayload('sku00002',2147483647),[2]);expect((await f.writer(db).updateSkus(context(),2,overflow)).receipt.outcome).toBe('rollback-rejected');const invalid=await body(db,{attr_value:[{unique:'sku00001',price:'1',cost:'2.00',ot_price:'3.00',stock:5}]});await expect(f.writer(db).updateSkus(context(),1,invalid)).rejects.toThrow('两位');expect(await state()).toEqual(before);}));
 it('keeps managed card quantity authoritative while allowing price changes and retaining historical sumStock',async()=>{await f.db.update(storeProduct).set({productType:1}).where(eq(storeProduct.id,1));await f.app(async db=>{const read=await f.reader(db).skus(f.actor(),1);expect(read.data.skus[0].stock_editable).toBe(false);expect(read.data.product.actions.skus).toBe(true);expect((await f.writer(db).updateSkus(context(),1,await body(db,skuPayload('sku00001',6)))).receipt.outcome).toBe('rollback-rejected');expect((await f.writer(db).updateSkus(context(),1,await body(db,skuPayload('sku00001',5)))).receipt.outcome).toBe('skus-updated');expect((await state()).skus.find(s=>s.id===1)).toMatchObject({stock:5,sumStock:12,price:'12.34'});});});
 it.each([1,2,3,4])('supports legitimate fixed card/coupon/virtual/times-card type %s quick stock edit without changing disk metadata',async type=>{await f.db.update(storeProduct).set({productType:type}).where(eq(storeProduct.id,1));if(type===1)await f.db.update(storeProductAttrValue).set({diskInfo:'PRIVATE-FIXED-DELIVERY'}).where(eq(storeProductAttrValue.id,1));await f.app(async db=>{expect((await f.reader(db).skus(f.actor(),1)).data.skus[0].stock_editable).toBe(true);expect((await f.writer(db).updateSkus(context(),1,await body(db,skuPayload('sku00001',6)))).receipt.outcome).toBe('skus-updated');expect((await state()).skus.find(s=>s.id===1)?.diskInfo).toBe(type===1?'PRIVATE-FIXED-DELIVERY':null);});});
 it.each(['missing','multiple','unique','suk'] as const)('shows malformed %s SKU topology without silently selecting a first SKU and refuses editing',async mode=>{if(mode==='missing')await f.db.update(storeProductAttrValue).set({isRetired:1}).where(eq(storeProductAttrValue.id,1));else await f.db.insert(storeProductAttrValue).values(f.sku(100,1,mode==='unique'?{unique:'sku00001'}:mode==='suk'?{suk:'实际规格1'}:{}));await f.app(async db=>{const read=await f.reader(db).skus(f.actor(),1);expect(read.data.product).toMatchObject({attr_value:null,actions:{skus:false}});expect(read.data.product.sku_policy).not.toBe('');expect((await f.writer(db).updateSkus(context(),1,await body(db,skuPayload()))).receipt.outcome).toBe('rollback-rejected');});});
 it.each(['product','sku','relation'] as const)('rejects actual %s same-row ABA using tuple versions in reviewed product revision',async source=>f.app(async db=>{const input=await body(db,{is_show:0});if(source==='product'){await f.db.update(storeProduct).set({price:'11.00'}).where(eq(storeProduct.id,1));await f.db.update(storeProduct).set({price:'10.00'}).where(eq(storeProduct.id,1));}if(source==='sku'){await f.db.update(storeProductAttrValue).set({stock:6}).where(eq(storeProductAttrValue.id,1));await f.db.update(storeProductAttrValue).set({stock:5}).where(eq(storeProductAttrValue.id,1));}if(source==='relation'){await f.db.update(storeProductRelation).set({status:0}).where(eq(storeProductRelation.id,1));await f.db.update(storeProductRelation).set({status:1}).where(eq(storeProductRelation.id,1));}const before=await state(),result=await f.writer(db).setShow(context(),input);expect(result.receipt).toMatchObject({outcome:'rollback-rejected',evidence:{code:'412'}});expect(await state()).toEqual(before);}));
 it('does not confuse colliding activity IDs with base SKU authority or wait for an unrelated activity SKU lock',async()=>f.app(async db=>f.app(async(_activityDb,_role,peer)=>{const input=await body(db,skuPayload()),reviewed=input.targets[0].expected_product_revision;await peer.exec('BEGIN');let open=true;try{await peer.exec('UPDATE store_product_attr_value SET stock=777 WHERE id=9 AND type=2');expect((await f.reader(db).skus(f.actor(),1)).data.product.product_revision).toBe(reviewed);expect((await f.writer(db).updateSkus(context(),1,input)).receipt.outcome).toBe('skus-updated');await peer.exec('COMMIT');open=false;expect((await state()).skus.find(s=>s.id===9)).toMatchObject({type:2,stock:777,price:'10.00',unique:'sku00009'});}finally{if(open)await peer.exec('ROLLBACK');}})));
 it('rejects fresh catalog changes for all four kinds even when selected rows and product values are unchanged',async()=>f.app(async db=>{for(const kind of['set_show','replace_categories','replace_labels','update_skus'] as const){const payload=kind==='set_show'?{is_show:0}:kind==='replace_categories'?{cate_id:[11]}:kind==='replace_labels'?{store_label_id:[20]}:skuPayload(),input=await body(db,payload);await f.db.update(storeProductCategory).set({cateName:`hidden drift ${kind}`}).where(eq(storeProductCategory.id,13));const before=await state(),result=kind==='set_show'?await f.writer(db).setShow(context(),input):kind==='update_skus'?await f.writer(db).updateSkus(context(),1,input):await f.writer(db).batch(context(),input);expect(result.receipt).toMatchObject({outcome:'rollback-rejected',evidence:{code:'412'}});expect(await state()).toEqual(before);}}),20000);
 it('replays the same immutable UUID exactly once, conflicts on changed intent and isolates owner receipts from another current user',async()=>f.app(async db=>{const input=await body(db,skuPayload()),ctx=context(),first=await f.writer(db).updateSkus(ctx,1,input);expect((await f.writer(db).updateSkus(ctx,1,input))).toEqual({...first,replayed:true});expect((await state()).stocks).toHaveLength(1);await expect(f.writer(db).updateSkus(ctx,1,{...input,payload:skuPayload('sku00001',9)})).rejects.toThrow('不同');expect((await f.writer(db).outcome(f.actor(102),ctx.request_key)).receipt).toBeNull();expect((await f.writer(db).outcome(f.actor(),ctx.request_key)).receipt).toEqual(first.receipt);}));
 it('preserves minimal owner outcome and same-key abandonment after role revocation while rejecting fresh writes',async()=>f.app(async db=>{const input=await body(db,{is_show:0}),ctx=context(),first=await f.writer(db).setShow(ctx,input);await f.db.update(storeService).set({customer:0}).where(eq(storeService.id,1));expect((await f.writer(db).outcome(f.actor(),ctx.request_key)).receipt).toEqual(first.receipt);expect((await f.writer(db).setShow(context(),input)).receipt).toMatchObject({service_id:0,outcome:'rollback-rejected'});const pending=context();expect((await f.writer(db).abandon(f.actor(),pending.request_key,{kind:'set_show',input})).receipt).toMatchObject({service_id:0,outcome:'abandoned'});expect((await f.writer(db).setShow(pending,input)).receipt.outcome).toBe('abandoned');}));
 it.each([102,103,104,105,106,107,110])('denies real kefu/manager/verifier/courier/disabled/deleted/ordinary role uid %s global products',async uid=>f.app(async db=>{const input=await body(db,{is_show:0}),before=await state();await expect(f.reader(db).list(f.actor(uid))).rejects.toThrow();expect((await f.writer(db).setShow(context(undefined,uid),input)).receipt).toMatchObject({service_id:0,outcome:'rollback-rejected'});expect(await state()).toEqual(before);}));
 it('rejects duplicate customer identities rather than widening product scope',async()=>{await f.db.insert(storeService).values({id:100,uid:101,account:'duplicate-customer',customer:1,accountStatus:1});await f.app(async db=>{await expect(f.reader(db).list(f.actor())).rejects.toThrow('重复');});});
 it.each(['status','deleted','soft_deleted','password','expiry','missing'] as const)('denies actual invalidated owner account %s for mutations, outcome and abandonment',async reason=>f.app(async db=>{const input=await body(db,{is_show:0}),ctx=context(),saved=await f.writer(db).setShow(ctx,input),owner=reason==='expiry'?{...f.actor(),expires_at:1}:f.actor();if(reason==='status')await f.db.update(user).set({status:0}).where(eq(user.uid,101));if(reason==='deleted')await f.db.update(user).set({deleteTime:new Date()}).where(eq(user.uid,101));if(reason==='soft_deleted')await f.db.update(user).set({isDel:1}).where(eq(user.uid,101));if(reason==='password')await f.db.update(user).set({pwd:'changed'}).where(eq(user.uid,101));if(reason==='missing')await f.db.delete(user).where(eq(user.uid,101));const before=await state();await expect(f.writer(db).setShow({...context(),actor:owner},input)).rejects.toThrow();await expect(f.writer(db).outcome(owner,saved.receipt.request_key)).rejects.toThrow();await expect(f.writer(db).abandon(owner,crypto.randomUUID(),{kind:'set_show',input})).rejects.toThrow();expect(await state()).toEqual(before);}));
 it('uses actual RR readonly snapshot then fresh role verification to reject an in-flight role removal',async()=>f.app(async db=>{let changed=false;const observed=observeIntegralReadDb(db,async(_tx,command)=>{if(!changed&&command.includes('from "store_product_category"')){changed=true;await f.db.update(storeService).set({customer:0}).where(eq(storeService.id,1));}}),reader=new CustomerWorkProductReadService(createContainerFromDb(observed),f.env);await expect(reader.categories(f.actor())).rejects.toThrow('权限');expect(changed).toBe(true);}));
 it.each(['store_product_category','store_product_label','category'] as const)('holds actual %s table fence against an independent taxonomy writer phantom until original write commit',async table=>f.app(async(db,_role,writerPeer)=>f.taxonomyWriter(async taxonomyPeer=>{
  const input=await body(db,{is_show:0}),original=Core.applyMobileProductShow;let signal!:()=>void,release!:()=>void,open=false,pending:ReturnType<ReturnType<typeof f.writer>['setShow']>|undefined;const reached=new Promise<void>(r=>{signal=r;}),wait=new Promise<void>(r=>{release=r;});
  const spy=vi.spyOn(Core,'applyMobileProductShow').mockImplementation(async(...args)=>{signal();await wait;return original(...args);});
  try{const write=f.writer(db).setShow(context(),input);pending=write;await reachedOrFinished(reached,write);expect(writerPeer.pid).not.toBe(taxonomyPeer.pid);await taxonomyPeer.exec('BEGIN');open=true;await taxonomyPeer.exec("SET LOCAL lock_timeout='200ms'");const insertion=table==='category'?`INSERT INTO category(id,name,"group") VALUES(900,'actual phantom',2)`:table==='store_product_category'?`INSERT INTO store_product_category(id,cate_name) VALUES(900,'actual phantom')`:`INSERT INTO store_product_label(id,label_name) VALUES(900,'actual phantom')`;await expect(taxonomyPeer.exec(insertion)).rejects.toMatchObject({code:'55P03'});await taxonomyPeer.exec('ROLLBACK');open=false;release();expect((await write).receipt.outcome).toBe('products-updated');await taxonomyPeer.exec(insertion);expect((await f.exec(`SELECT id FROM ${table} WHERE id=900`))).toHaveLength(1);
  }finally{release();try{if(open)await taxonomyPeer.exec('ROLLBACK');}finally{await pending?.catch(()=>undefined);spy.mockRestore();}}
 })),15000);
 it('rejects a busy taxonomy writer before mutation and leaves all product/cart/stock effects rolled back',async()=>f.app(async db=>f.taxonomyWriter(async peer=>{const input=await body(db,{is_show:0}),before=await state();await peer.exec('BEGIN');try{await peer.exec("UPDATE store_product_category SET cate_name='busy current writer' WHERE id=10");expect((await f.writer(db).setShow(context(),input)).receipt.outcome).toBe('rollback-rejected');expect(await state()).toEqual(before);}finally{await peer.exec('ROLLBACK');}})));
 it.each(['store_cart','store_product_attr_value'] as const)('rolls back the full management transaction on a real busy %s row without replaying stock input',async table=>f.app(async db=>f.app(async(_otherDb,_role,peer)=>{const input=await body(db,{is_show:0}),before=await state();await peer.exec('BEGIN');try{await peer.exec(`SELECT id FROM ${table} WHERE id=1 FOR UPDATE NOWAIT`);expect((await f.writer(db).setShow(context(),input)).receipt.outcome).toBe('rollback-rejected');expect(await state()).toEqual(before);}finally{await peer.exec('ROLLBACK');}})));
 it('keeps actual actor account FOR SHARE until product write commit, then honors account revocation',async()=>f.app(async(db,role,writerPeer)=>f.app(async(_revokerDb,revokerRole,revoker)=>{
  const input=await body(db,{is_show:0}),original=Core.applyMobileProductShow;let signal!:()=>void,release!:()=>void,open=false;const reached=new Promise<void>(r=>{signal=r;}),wait=new Promise<void>(r=>{release=r;}),spy=vi.spyOn(Core,'applyMobileProductShow').mockImplementation(async(...args)=>{signal();await wait;return original(...args);});let pending:ReturnType<ReturnType<typeof f.writer>['setShow']>|undefined;
  try{pending=f.writer(db).setShow(context(),input);await reachedOrFinished(reached,pending);expect(role).not.toBe(revokerRole);expect(writerPeer.pid).not.toBe(revoker.pid);await revoker.exec('BEGIN');open=true;await expect(revoker.exec('SELECT uid FROM public."user" WHERE uid=101 FOR UPDATE NOWAIT')).rejects.toMatchObject({code:'55P03'});await revoker.exec('ROLLBACK');open=false;release();expect((await pending).receipt.outcome).toBe('products-updated');await revoker.exec('UPDATE public."user" SET status=0 WHERE uid=101');await expect(f.writer(db).setShow(context(),input)).rejects.toThrow('会话');
  }finally{release();try{if(open)await revoker.exec('ROLLBACK');}finally{await pending?.catch(()=>undefined);spy.mockRestore();}}
 })),15000);
 it.each([['show','base'],['show','relation'],['sku','base'],['sku','relation']] as const)('refuses observed direct SQL topology phantom after CAS at actual %s core entry: %s',async(kind,entity)=>f.app(async db=>f.app(async(_peerDb,_role,peer)=>{
  const input=await body(db,kind==='show'?{is_show:0}:skuPayload());let signal!:()=>void,release!:()=>void;const reached=new Promise<void>(r=>{signal=r;}),wait=new Promise<void>(r=>{release=r;});const originalShow=Core.applyMobileProductShow,originalSku=Core.applyMobileProductSkus,showSpy=kind==='show'?vi.spyOn(Core,'applyMobileProductShow').mockImplementation(async(...args)=>{signal();await wait;return originalShow(...args);}):null,skuSpy=kind==='sku'?vi.spyOn(Core,'applyMobileProductSkus').mockImplementation(async(...args)=>{signal();await wait;return originalSku(...args);}):null;let pending:ReturnType<ReturnType<typeof f.writer>['setShow']>|undefined;
  try{pending=kind==='show'?f.writer(db).setShow(context(),input):f.writer(db).updateSkus(context(),1,input);await reachedOrFinished(reached,pending);if(entity==='base')await peer.db.insert(storeProductAttrValue).values(f.sku(100,1,{unique:'phantom1'}));else await peer.db.insert(storeProductRelation).values({id:100,productId:1,type:5,relationId:55,status:1});const afterPeer=await state();release();expect((await pending).receipt).toMatchObject({outcome:'rollback-rejected',evidence:{code:'412'}});expect(await state()).toEqual(afterPeer);
  }finally{release();try{await pending?.catch(()=>undefined);}finally{showSpy?.mockRestore();skuSpy?.mockRestore();}}
 })),15000);
 it('accepts only ordinary UserJWT HTTP seven routes and rejects anonymous/AdminJWT, unknown/duplicate query and SKU path substitution',async()=>f.app(async db=>{const h=f.http(db),token=await createToken(101,'api',f.actor().auth_version,f.env.APP_KEY),admin=await createToken(101,'admin',f.actor().auth_version,f.env.APP_KEY),authorization={'Authori-zation':`Bearer ${token.token}`};for(const path of['/products','/products/categories','/products/labels','/products/1/skus']){const response=await h.request(path,{headers:authorization},f.env);expect(response.status).toBe(200);expect(response.headers.get('Cache-Control')).toBe('private, no-store');}expect((await h.request('/products',{},f.env)).status).toBe(400);expect((await h.request('/products',{headers:{'Authori-zation':`Bearer ${admin.token}`}},f.env)).status).toBe(400);expect((await h.request('/products?page=1&page=2',{headers:authorization},f.env)).status).toBe(400);expect((await h.request('/products?store_id=77',{headers:authorization},f.env)).status).toBe(400);const input=await body(db,skuPayload()),headers={...authorization,'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()};expect((await h.request('/products/2/skus',{method:'POST',headers,body:JSON.stringify(input)},f.env)).status).toBe(400);const show=await body(db,{is_show:0});expect((await h.request('/products/show',{method:'POST',headers:{...headers,'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(show)},f.env)).status).toBe(200);const batch=await body(db,{cate_id:[11]});expect((await h.request('/products/batch',{method:'POST',headers:{...headers,'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(batch)},f.env)).status).toBe(200);expect((await h.request('/products/1/skus',{method:'POST',headers:{...headers,'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(await body(db,skuPayload()))},f.env)).status).toBe(200);}),20000);
 it('uses independent product version hash and exact immutable body instead of order intent namespace',async()=>f.app(async db=>{const input=await body(db,{is_show:0}),ctx=context(),prepared=await prepareCustomerProductOperation('set_show',ctx,input),intent=await frontendIntent('set_show',input,ctx.request_key);expect(prepared.hash).toBe(intent.request_hash);expect(Frontend.isCustomerWorkProductBody(input,'set_show')).toBe(true);await expect(prepareCustomerProductOperation('set_show',ctx,{...input,order_id:1})).rejects.toThrow('字段');await expect(prepareCustomerProductOperation('set_show',ctx,{...input,targets:[input.targets[0],input.targets[0]]})).rejects.toThrow('排序');expect((await f.writer(db).outcome(f.actor(),ctx.request_key)).receipt).toBeNull();}));
});
