import {beforeAll,afterAll,beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {asc,eq,sql} from 'drizzle-orm';
import {Hono} from 'hono';
import {customerWorkFinancialFixture} from './helpers/customerWorkFinancialFixture';
import {createContainerFromDb,withTx,type DbClient} from '../src/lib/di';
import {storeOrder,storeOrderCartInfo,storeOrderRefund,storeOrderRefundPayment,storeOrderOutbox,storeOrderInvoice,storeProduct,storeProductAttrValue,storeProductVirtual,storeSeckill,storeBargain,storeBargainUser,storeCombination,storeIntegral,storeDiscounts,storeService,systemConfig,user,userBill,userBrokerage,supplierFlowingWater,supplierTransactions,storeOrderEconomize,agentLevelTaskRecord,storeOrderStatus} from '../src/models/schema';
import {storeOrderRefundSplit} from '../src/models/schema/order_refund_split';
import {CustomerWorkFinancialService} from '../src/services/customer-work/CustomerWorkFinancialService';
import {authorizeCustomerWorkActor,customerWorkConsistency} from '../src/services/customer-work/CustomerWorkScope';
import {CUSTOMER_FINANCIAL_VERSION,CUSTOMER_FINANCIAL_QUOTE_VERSION,prepareFinancialOperation,type FinancialInput,type FinancialContext} from '../src/services/customer-work/CustomerWorkFinancialProtocol';
import {appendFinancialOperation,authorizeFinancialOperation,checkFinancialOperation} from '../src/services/customer-work/CustomerWorkFinancialOperationRequest';
import {financialRevisions} from '../src/services/customer-work/CustomerWorkFinancialReadService';
import {auditCheckoutPricingLockRuntime} from '../src/migrations/checkoutPricingLock';
import {applyOrderRefund,applyOrderRefundWithMaterialization,lockRefundExecution} from '../src/services/order/StoreOrderRefundService';
import {applyStoreOrderPayment,PayType} from '../src/services/order/StoreOrderPayService';
import {readRefundQuantityReservation,CUSTOMER_ROW_REFUND_VERSION} from '../src/services/order/RefundQuantityReservation';
import {readPurchaseQuotaRefundFamily} from '../src/services/order/PurchaseQuotaRefundReceipt';
import {readPurchaseQuotaPaymentLedger} from '../src/services/order/PurchaseQuotaPaymentLedger';
import {WechatPayService} from '../src/services/wechat/WechatPayService';
import {AlipayRefundService} from '../src/services/payment/AlipayRefundService';
import type {RefundProviderRequest} from '../src/services/payment/RefundGateway';
import {enqueueOrderPaidEvent,OrderOutboxService} from '../src/services/order/OrderOutboxService';
import * as PaidOutbox from '../src/services/order/OrderOutboxService';
import * as RefundNotice from '../src/services/order/OrderNotificationOutboxService';
import {preparePresalePaidRecovery} from '../src/services/activity/PresalePaidRecovery';
import {PRESALE_DELIVERY_EVENT} from '../src/services/activity/PresaleDeliveryIntent';
import {authMiddleware} from '../src/middleware/auth';
import {changePrice,financialOperationStatus} from '../src/controllers/api/v1/CustomerWorkFinancialController';
import {ApiException} from '../src/utils/errors';
import {createToken,md5} from '../src/utils/jwt';
import type {Env,AppVariables} from '../src/env';
import type {CustomerJson} from '../src/services/customer-work/CustomerWorkOperationRequest';

/** A registered disposable database, a real independent ordinary LOGIN, and
 * real mature core transactions. Only the external provider boundary is stubbed;
 * this suite neither accepts production credentials nor claims provider HTTP. */
describe.runIf(Boolean(process.env.TEST_FINANCE_POSTGRES_URL))('native ordinary customer financial contract',()=>{
 let f:Awaited<ReturnType<typeof customerWorkFinancialFixture>>,service:CustomerWorkFinancialService,fetchGuard:ReturnType<typeof vi.spyOn>;
 beforeAll(async()=>{f=await customerWorkFinancialFixture();},60000);
 afterAll(async()=>{await f?.close();},30000);
 beforeEach(async()=>{await f.reset();service=f.service();fetchGuard=vi.spyOn(globalThis,'fetch').mockRejectedValue(Error('No external provider HTTP is accepted by this native fixture'));});
 afterEach(()=>{try{expect(fetchGuard).not.toHaveBeenCalled();}finally{vi.restoreAllMocks();}});
 const ctx=(key=crypto.randomUUID(),uid=101):FinancialContext=>({actor:f.actor(uid),request_key:key});
 const tx=<T>(fn:(db:DbClient)=>Promise<T>)=>withTx(f.container,fn);
 const quotaRead=<T>(fn:(db:DbClient)=>Promise<T>)=>withTx(f.container,async db=>{await db.execute(sql`SET TRANSACTION ISOLATION LEVEL REPEATABLE READ, READ ONLY`);return fn(db);});
 const order=async(id=1)=>(await f.db.select().from(storeOrder).where(eq(storeOrder.id,id)))[0];
 const refund=async(id:number)=>(await f.db.select().from(storeOrderRefund).where(eq(storeOrderRefund.id,id)))[0];
 const ledger=()=>f.db.execute(sql`SELECT * FROM public.customer_financial_operation_request ORDER BY actor_uid,request_key`);
 async function corruptOwnedSplit(id:number,patch:Partial<typeof storeOrderRefundSplit.$inferInsert>){await f.maintenanceDb.transaction(async db=>{await db.execute(sql`ALTER TABLE public.store_order_refund_split DISABLE TRIGGER USER`);await db.update(storeOrderRefundSplit).set(patch).where(eq(storeOrderRefundSplit.refundId,id));await db.execute(sql`ALTER TABLE public.store_order_refund_split ENABLE TRIGGER USER`);});}
 const effects=async()=>({orders:await f.db.select().from(storeOrder).orderBy(asc(storeOrder.id)),carts:await f.db.select().from(storeOrderCartInfo).orderBy(asc(storeOrderCartInfo.id)),refunds:await f.db.select().from(storeOrderRefund).orderBy(asc(storeOrderRefund.id)),users:await f.db.select().from(user).orderBy(asc(user.uid)),bills:await f.db.select().from(userBill).orderBy(asc(userBill.id)),outbox:await f.db.select().from(storeOrderOutbox).orderBy(asc(storeOrderOutbox.id)),payments:await f.db.select().from(storeOrderRefundPayment).orderBy(asc(storeOrderRefundPayment.id)),splits:await f.db.select().from(storeOrderRefundSplit).orderBy(asc(storeOrderRefundSplit.refundId)),invoices:await f.db.select().from(storeOrderInvoice).orderBy(asc(storeOrderInvoice.id)),skus:await f.db.select().from(storeProductAttrValue).orderBy(asc(storeProductAttrValue.id)),products:await f.db.select().from(storeProduct).orderBy(asc(storeProduct.id)),seckill:await f.db.select().from(storeSeckill).orderBy(asc(storeSeckill.id)),bargain:await f.db.select().from(storeBargain).orderBy(asc(storeBargain.id)),combination:await f.db.select().from(storeCombination).orderBy(asc(storeCombination.id)),integral:await f.db.select().from(storeIntegral).orderBy(asc(storeIntegral.id)),packages:await f.db.select().from(storeDiscounts).orderBy(asc(storeDiscounts.id))});
  // Include actual paid-accounting rows as well as all existing financial and
  // outbox facts when proving retries do not repeat any committed effect.
  const paidReplayEffects=async()=>({...await effects(),financialReceipts:await ledger(),
   orderAudit:await f.db.select().from(storeOrderStatus).orderBy(asc(storeOrderStatus.id)),brokerage:await f.db.select().from(userBrokerage).orderBy(asc(userBrokerage.id)),
   supplierFlows:await f.db.select().from(supplierFlowingWater).orderBy(asc(supplierFlowingWater.id)),
   supplierTransactions:await f.db.select().from(supplierTransactions).orderBy(asc(supplierTransactions.id)),
   economize:await f.db.select().from(storeOrderEconomize).orderBy(asc(storeOrderEconomize.id)),
   agentTasks:await f.db.select().from(agentLevelTaskRecord).orderBy(asc(agentLevelTaskRecord.id))});
 async function input(payload:CustomerJson,id=1):Promise<FinancialInput>{const actual=await order(id),scope=await authorizeCustomerWorkActor(f.db,f.actor()),state=await financialRevisions(f.db,actual);return{version:CUSTOMER_FINANCIAL_VERSION,scope_key:scope.scope_key,order_id:id,expected_order_revision:state.order_revision,expected_financial_revision:state.financial_revision,payload};}
 async function readOrder(id=1){const actual=await order(id);return service.reader.order(f.actor(),id,{order_no:actual.orderId});}
 async function review(id:number){const actual=await refund(id);return service.reader.review(f.actor(),id,{refund_no:actual.orderId});}
 async function decision(id:number,kind:'refund_return'|'refund_refuse'|'refund_execute',received=false){const current=await review(id),d=current.data;return input({refund_id:id,refund_no:d.refund_no,expected_refund_revision:d.refund_revision,review_fingerprint:d.review_fingerprint,decision:{apply_type:d.apply_type,refund_type:d.refund_type,received},...(kind==='refund_refuse'?{reason:'已核实的拒绝原因'}:kind==='refund_execute'?{refund_price:d.refund_price}:{})},d.order_id);}
 async function note(id:number,text='已核对的实际备注'){const current=(await review(id)).data;return input({refund_id:id,refund_no:current.refund_no,expected_refund_revision:current.refund_revision,review_fingerprint:current.review_fingerprint,remark:text},current.order_id);}
 async function quote(id=1,items:Array<{cart_row_id:number;cart_num:number}>=[]){const body=await input({},id);return service.reader.quote(f.actor(),{version:CUSTOMER_FINANCIAL_QUOTE_VERSION,scope_key:body.scope_key,order_id:id,expected_order_revision:body.expected_order_revision,expected_financial_revision:body.expected_financial_revision,mode:items.length?'items':'remaining',items});}
 async function create(id=1,items:Array<{cart_row_id:number;cart_num:number}>=[],context=ctx()){const displayed=(await quote(id,items)).data,body=await input({mode:items.length?'items':'remaining',items,quoted_price:displayed.quoted_price,refund_price:displayed.quoted_price,quote_fingerprint:displayed.quote_fingerprint,reason:'顾客已确认的主动退款'},id),result=await service.create(context,body);expect(result.receipt?.outcome).toBe('refund-created');return{id:Number(result.receipt!.evidence.refund_id),context,body,result};}
 async function application(applyType=1,count=1,materialized=false,id=1){const current=await order(id),cart=(await f.db.select().from(storeOrderCartInfo).where(eq(storeOrderCartInfo.oid,id)))[0],params={uid:11,orderId:current.orderId,applyType,applicationOrderId:'N'+crypto.randomUUID().replaceAll('-','').slice(0,30),refundReason:'真实既有申请',refundExplain:'保持原申请类型',cartSelections:[{cartId:Number(cart.cartId),cartNum:count}]};return (await(materialized?applyOrderRefundWithMaterialization(f.container,params,0):applyOrderRefund(f.container,params,0))).refundId;}
 async function execute(id:number,context=ctx()){const body=await decision(id,'refund_execute'),result=await service.execute('refund_execute',context,body);return{body,context,result};}
 async function provider(kind:'wechat'|'alipay',id=1){await f.maintenanceDb.update(storeOrder).set({payType:kind==='wechat'?'weixin':'alipay',tradeNo:'owned-original-transaction'}).where(eq(storeOrder.id,id));const values:Record<string,string>={ali_pay_status:'1',pay_weixin_open:'1',pay_weixin_mchid:'1234567890',pay_weixin_serial_no:'A'.repeat(32),wechat_appid:'wx1234567890abcdef',site_url:'https://fixture.invalid'};for(const[name,value]of Object.entries(values)){await f.maintenanceDb.delete(systemConfig).where(eq(systemConfig.menuName,name));await f.maintenanceDb.insert(systemConfig).values({menuName:name,value});}Object.assign(f.env,{WECHAT_MCH_PRIVATE_KEY:'owned-synthetic-provider-key',WECHAT_API_V3_KEY:'x'.repeat(32),WECHAT_PLATFORM_PUBLIC_KEY:'-----BEGIN PUBLIC KEY-----\nowned-fixture\n-----END PUBLIC KEY-----',ALIPAY_APP_ID:'owned-fixture',ALIPAY_PRIVATE_KEY:'owned-fixture',ALIPAY_PUBLIC_KEY:'owned-fixture',ALIPAY_SELLER_ID:'owned-fixture',ALIPAY_NOTIFY_URL:'https://fixture.invalid/notify',ALIPAY_RETURN_URL:'https://fixture.invalid/return'});}
 const gateway=(kind:'wechat'|'alipay')=>kind==='wechat'?WechatPayService.prototype:AlipayRefundService.prototype;
 async function activityOrder(type:1|2|3|4,pureIntegral=false){
  const activityId=170,skuId=700+type,table=type===1?storeSeckill:type===2?storeBargain:type===3?storeCombination:storeIntegral,cart=(await f.maintenanceDb.select().from(storeOrderCartInfo).where(eq(storeOrderCartInfo.id,1)))[0],raw=JSON.parse(cart.cartInfo!);
  await f.maintenanceDb.insert(table).values({id:activityId,productId:70,stock:10,quota:10,sales:2});await f.maintenanceDb.insert(storeProductAttrValue).values({id:skuId,productId:activityId,type,unique:'qafina0'+type,price:pureIntegral?'0.00':'5.00',stock:10,quota:10,sales:2});
  if(type===2)await f.maintenanceDb.insert(storeBargainUser).values({id:270,uid:11,bargainId:activityId});
  if(pureIntegral){await f.maintenanceDb.update(storeIntegral).set({integral:10,price:'0.00'}).where(eq(storeIntegral.id,activityId));await f.maintenanceDb.update(storeProductAttrValue).set({price:'0.00'}).where(eq(storeProductAttrValue.id,1));}
  await f.maintenanceDb.update(storeOrder).set({type,activityId,...(pureIntegral?{paid:0,payType:PayType.INTEGRAL,totalPrice:'0.00',payPrice:'0.00',payIntegral:20}:{})}).where(eq(storeOrder.id,1));
  await f.maintenanceDb.update(storeOrderCartInfo).set({cartInfo:JSON.stringify({...raw,sku:{...raw.sku,id:1,price:pureIntegral?'0.00':'5.00'},activitySku:{id:skuId,price:pureIntegral?'0.00':'5.00'},...(type===2?{bargainParticipation:{version:1,participantId:270,activityId,uid:11}}:{}),...(pureIntegral?{sum_price:'0.00',sum_true_price:'0.00',integral:10,use_integral:'0'}:{})})}).where(eq(storeOrderCartInfo.id,1));
  return{activityId,skuId,table};
 }
 async function presaleOrder(){
  const cart=(await f.maintenanceDb.select().from(storeOrderCartInfo).where(eq(storeOrderCartInfo.id,1)))[0],raw=JSON.parse(cart.cartInfo!),opaque='预售:原始商品',presale={version:'presale-full-payment-v1',productId:70,startsAt:0,endsAt:100,shippingDaysAfterEnd:7,paidMemberOnly:false,perOrderLimit:null};
  await f.maintenanceDb.update(storeOrder).set({type:6,productType:1,payTime:100,supplierAllocationStatus:2}).where(eq(storeOrder.id,1));await f.maintenanceDb.update(storeOrderCartInfo).set({cartId:opaque,type:0,productType:1,cartInfo:JSON.stringify({...raw,id:opaque,presale,sku:{...raw.sku,id:1,disk_info:''}})}).where(eq(storeOrderCartInfo.id,1));await f.maintenanceDb.update(storeProduct).set({productType:1,isPresaleProduct:1}).where(eq(storeProduct.id,70));await f.maintenanceDb.insert(storeProductVirtual).values([1,2].map(n=>({productId:70,attrUnique:'qared001',cardNo:'OWNED-PRESALE-'+n,cardPwd:'OWNED-SECRET-'+n})));
 }

 it('uses the actual separate LOGIN and append-only receipt ACL with no customer-role forgery',async()=>{const [identity]=await f.db.execute(sql`SELECT current_user AS role,session_user AS session,has_column_privilege(current_user,'store_service','customer','UPDATE') AS forge_role,has_table_privilege(current_user,'customer_financial_operation_request','UPDATE,DELETE,TRUNCATE') AS mutate_receipt`);expect(identity).toEqual({role:f.role,session:f.role,forge_role:false,mutate_receipt:false});await expect(f.db.execute(sql`UPDATE public.store_service SET customer=1 WHERE id=2`)).rejects.toThrow();});
 it('rejects a newly reachable unreviewed definer while preserving exact customer pricing authority checks',async()=>{
  await f.maintenanceDb.update(storeOrder).set({paid:0}).where(eq(storeOrder.id,1));const body=await input({price:'7.00'}),before=await effects();await f.exec('CREATE FUNCTION public.owned_financial_unreviewed_definer() RETURNS integer LANGUAGE sql SECURITY DEFINER AS $$ SELECT 1 $$');
  try{const pricing=await auditCheckoutPricingLockRuntime(f.db,'public','customer-work');expect(pricing).toMatchObject({ready:false,catalogReady:true,callerSafe:true,requiredPrivileges:true,noUnreviewedDefinerRoutine:false});expect((await readOrder()).data.actions.change_price.available).toBe(false);expect((await service.price(ctx(),body)).receipt?.outcome).toBe('rollback-rejected');expect(await effects()).toEqual(before);}finally{await f.exec('DROP FUNCTION public.owned_financial_unreviewed_definer()');}
 });
 it('does not exempt a customer scope routine after its real catalog definition drifts',async()=>{
  await f.maintenanceDb.update(storeOrder).set({paid:0}).where(eq(storeOrder.id,1));const body=await input({price:'7.00'}),before=await effects();await f.exec('ALTER FUNCTION public.customer_work_lock_scope_v1(integer) SET search_path=public');
  try{const pricing=await auditCheckoutPricingLockRuntime(f.db,'public','customer-work');expect(pricing.ready).toBe(false);expect(pricing.noUnreviewedDefinerRoutine).toBe(false);expect((await readOrder()).data.actions.change_price.available).toBe(false);await expect(service.price(ctx(),body)).rejects.toThrow();expect(await effects()).toEqual(before);expect(await ledger()).toEqual([]);}finally{await f.exec('ALTER FUNCTION public.customer_work_lock_scope_v1(integer) SET search_path=pg_catalog,pg_temp');}
 });
 it('denies a real caller configuration UPDATE grant while its reviewed lock functions remain exact',async()=>{
  await f.maintenanceDb.update(storeOrder).set({paid:0}).where(eq(storeOrder.id,1));const body=await input({price:'7.00'}),before=await effects();await f.exec(`GRANT UPDATE(value) ON public.system_config TO "${f.role}"`);
  try{const pricing=await auditCheckoutPricingLockRuntime(f.db,'public','customer-work');expect(pricing).toMatchObject({ready:false,catalogReady:true,callerSafe:false,requiredPrivileges:true,noUnreviewedDefinerRoutine:true});expect((await readOrder()).data.actions.change_price.available).toBe(false);expect((await service.price(ctx(),body)).receipt?.outcome).toBe('rollback-rejected');expect(await effects()).toEqual(before);}finally{await f.exec(`REVOKE UPDATE(value) ON public.system_config FROM "${f.role}"`);}
 });
 it('keeps the actual base work consistency key and reads a quote without any durable effects',async()=>{const before=await effects(),displayed=await readOrder(),scope=await authorizeCustomerWorkActor(f.db,f.actor());expect(displayed.consistency_key).toBe(await customerWorkConsistency(f.db,scope));const quoted=await quote(1,[{cart_row_id:1,cart_num:1}]);expect(quoted.data.items).toMatchObject([{cart_row_id:1,cart_id:'501',cart_num:1,max_num:2,line_price:'5.00'}]);expect(quoted.consistency_key).toBe(displayed.consistency_key);expect(await effects()).toEqual(before);expect(await ledger()).toEqual([]);});
 it('commits actual price effects once and binds the full original body to one UUID',async()=>{await f.maintenanceDb.update(storeOrder).set({paid:0}).where(eq(storeOrder.id,1));const body=await input({price:'7.00'}),context=ctx(),saved=await service.price(context,body);expect(saved.receipt).toMatchObject({actor_uid:101,service_id:1,outcome:'price-changed',evidence:{changed:1,verified:true}});expect(await order()).toMatchObject({payPrice:'7.00',changePrice:'3.00'});expect((await service.price(context,body)).receipt).toEqual(saved.receipt);await expect(service.price(context,{...body,payload:{price:'8.00'}})).rejects.toMatchObject({code:409});expect(await ledger()).toHaveLength(1);});
 it('writes actual offline payment and its canonical paid outbox in the same receipt transaction',async()=>{await f.maintenanceDb.update(storeOrder).set({paid:0}).where(eq(storeOrder.id,1));const saved=await service.offline(ctx(),await input({}));expect(saved.receipt?.outcome).toBe('offline-paid');expect(await order()).toMatchObject({paid:1,payType:'offline'});const rows=await f.db.select().from(storeOrderOutbox);expect(rows).toHaveLength(1);expect(rows[0]).toMatchObject({id:saved.receipt!.evidence.outbox_id,eventKey:'order.paid:1',aggregateType:'order',aggregateId:1,eventType:'order.paid',payload:{orderId:1,orderNo:'customer-financial-1'}});});
 it('rolls offline paid and its receipt back when the core returns a non-persisted outbox identifier',async()=>{await f.maintenanceDb.update(storeOrder).set({paid:0}).where(eq(storeOrder.id,1));vi.spyOn(PaidOutbox,'enqueueOrderPaidEvent').mockResolvedValue({id:123,eventKey:'order.paid:1'});const before=await effects(),result=await service.offline(ctx(),await input({}));expect(result.receipt?.outcome).toBe('rollback-rejected');expect(await effects()).toEqual(before);});
 it('rolls refusal and held quantity back when its required actual notice is absent',async()=>{const id=await application(1);vi.spyOn(RefundNotice,'enqueueOrderRefundRefusedNoticeEvent').mockResolvedValue({id:123,eventKey:'order.refund.refused.notice:'+id});const before=await effects(),result=await service.execute('refund_refuse',ctx(),await decision(id,'refund_refuse'));expect(result.receipt?.outcome).toBe('rollback-rejected');expect(await effects()).toEqual(before);});
 it('separates refund application from funds and persists a true row-PK/opaque v3 claim',async()=>{const before=(await f.db.select().from(user).where(eq(user.uid,11)))[0],created=await create(1,[{cart_row_id:1,cart_num:1}]),actual=await refund(created.id),claim=readRefundQuantityReservation(actual);expect(actual).toMatchObject({applyType:4,refundType:0,refundedPrice:'0.00'});expect(claim).toMatchObject({version:CUSTOMER_ROW_REFUND_VERSION,items:[{rowId:1,cartId:1,sourceCartId:'501',cartNum:1,totalNum:2,beforeRefundNum:0}]});expect((await f.db.select().from(user).where(eq(user.uid,11)))[0].nowMoney).toBe(before.nowMoney);const final=await execute(created.id);expect(final.result).toMatchObject({receipt:{outcome:'balance-settled'},execution:{status:'BALANCE_SUCCESS',completed:true,verified:true}});expect((await f.db.select().from(user).where(eq(user.uid,11)))[0].nowMoney).toBe('105.00');expect(await service.status(f.actor(),final.context.request_key)).toEqual(final.result);});
 it('preserves mature approval, refusal, quantity release and actual refusal notification',async()=>{const id=await application(2),initial=(await f.db.select().from(user).where(eq(user.uid,11)))[0].nowMoney,approved=await service.execute('refund_return',ctx(),await decision(id,'refund_return'));expect(approved.receipt?.outcome).toBe('return-approved');expect((await refund(id)).refundType).toBe(4);const refused=await service.execute('refund_refuse',ctx(),await decision(id,'refund_refuse'));expect(refused.receipt?.outcome).toBe('refused');expect((await refund(id)).refuseReason).toBe('已核实的拒绝原因');expect((await f.db.select().from(storeOrderCartInfo).where(eq(storeOrderCartInfo.id,1)))[0].refundNum).toBe(0);expect((await f.db.select().from(user).where(eq(user.uid,11)))[0].nowMoney).toBe(initial);expect((await f.db.select().from(storeOrderOutbox))[0]).toMatchObject({eventKey:'order.refund.refused.notice:'+id,eventType:'order.refund.refused.notice',payload:{orderId:1,orderNo:'customer-financial-1',refundId:id,userId:11,payPrice:'10.00'}});});
 it('requires received confirmation and never advertises unapproved return funding',async()=>{const id=await application(2),displayed=await review(id);expect(displayed.data.actions.refund_execute.available).toBe(false);expect(displayed.data.actions.refund_return.available).toBe(true);await expect(service.execute('refund_execute',ctx(),await decision(id,'refund_execute'))).rejects.toThrow('必须先审批');expect(await ledger()).toEqual([]);expect((await refund(id)).refundType).toBe(0);});
 it('reads, remarks and safely refuses actual legacy apply_type zero without assigning type one',async()=>{const id=await application(2);await f.maintenanceDb.update(storeOrderRefund).set({applyType:0}).where(eq(storeOrderRefund.id,id));const displayed=await review(id);expect(displayed.data.apply_type).toBe(0);expect(displayed.data.actions.refund_refuse.available).toBe(true);expect(displayed.data.actions.refund_execute.available).toBe(false);expect((await service.remark(ctx(),await note(id))).receipt?.outcome).toBe('refund-remark-saved');const before=await effects();await expect(service.execute('refund_execute',ctx(),await decision(id,'refund_execute'))).rejects.toThrow('历史售后类型');expect(await effects()).toEqual(before);expect((await service.execute('refund_refuse',ctx(),await decision(id,'refund_refuse'))).receipt?.outcome).toBe('refused');expect(await refund(id)).toMatchObject({applyType:0,refundType:3});});
 it.each(['cancelled','completed'] as const)('allows an actual %s application management remark while funds remain constrained',async state=>{const id=await application(1);if(state==='cancelled'){await f.maintenanceDb.update(storeOrderRefund).set({isCancel:1}).where(eq(storeOrderRefund.id,id));}else await execute(id);expect((await review(id)).data.actions.refund_remark.available).toBe(true);const saved=await service.remark(ctx(),await note(id));expect(saved.receipt?.outcome).toBe('refund-remark-saved');expect((await refund(id)).remark).toBe('已核对的实际备注');expect((await review(id)).data.actions.refund_execute.available).toBe(false);});
 it('accepts 255 Unicode code points and rejects noncanonical text or typed intent before any receipt',async()=>{const id=await application(1),body=await note(id,'😀'.repeat(255));expect((await service.remark(ctx(),body)).receipt?.outcome).toBe('refund-remark-saved');for(const text of ['😀'.repeat(256),' x','x ','\u00a0x','x\ufeff','x\u0000','x\u007f'])await expect(service.remark(ctx(),await note(id,text))).rejects.toThrow('无效');const rows=await ledger();expect(rows).toHaveLength(1);for(const patch of[{order_id:'1'},{scope_key:[body.scope_key]},{expected_order_revision:[body.expected_order_revision]}])await expect(service.remark(ctx(),{...body,...patch})).rejects.toThrow();expect(await ledger()).toHaveLength(1);});
 it('rejects array selection mode and noncanonical amounts before reservation or receipt',async()=>{const base=await input({}),before=await effects();await expect(service.reader.quote(f.actor(),{version:CUSTOMER_FINANCIAL_QUOTE_VERSION,scope_key:base.scope_key,order_id:1,expected_order_revision:base.expected_order_revision,expected_financial_revision:base.expected_financial_revision,mode:['items'],items:[{cart_row_id:1,cart_num:1}]})).rejects.toThrow();for(const price of ['01.00','1.0','1e2',1,-1,'-0.00'])await expect(service.price(ctx(),{...base,payload:{price}})).rejects.toThrow();expect(await effects()).toEqual(before);expect(await ledger()).toEqual([]);});
 it('denies kefu-only, manager-only, writeoff and courier ordinary actors without granting customer scope',async()=>{for(const uid of[102,103,104,105])await expect(service.reader.order(f.actor(uid),1,{order_no:'customer-financial-1'})).rejects.toThrow();expect(await ledger()).toEqual([]);});
 it('uses actual UserJWT Controller authentication and rejects an Admin token',async()=>{await f.maintenanceDb.update(storeOrder).set({paid:0}).where(eq(storeOrder.id,1));const body=await input({price:'7.00'}),key=crypto.randomUUID(),app=new Hono<{Bindings:Env;Variables:AppVariables}>();app.use('*',async(c,next)=>{c.set('container',f.container);await next();});app.post('/financial/change-price',authMiddleware({force:true}),changePrice);app.get('/financial/operations/:key',authMiddleware({force:true}),financialOperationStatus);app.onError((error,c)=>c.json({status:error instanceof ApiException?error.code:500,msg:error.message,data:null},400));const ordinary=(await createToken(101,'api',md5('owned-financial-password'),f.env.APP_KEY)).token,admin=(await createToken(101,'admin',md5('owned-financial-password'),f.env.APP_KEY)).token,send=(token:string)=>app.request('/financial/change-price',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','Idempotency-Key':key},body:JSON.stringify(body)},f.env);expect((await(await send(admin)).json() as {status:number}).status).not.toBe(200);expect(await ledger()).toEqual([]);const response=await send(ordinary);expect(await response.json()).toMatchObject({status:200,data:{receipt:{actor_uid:101,request_key:key,outcome:'price-changed'}}});expect(response.headers.get('Cache-Control')).toBe('private, no-store');});
 it('keeps an unknown rolled-back callback absent until explicit original-body abandonment',async()=>{await f.maintenanceDb.update(storeOrder).set({paid:0}).where(eq(storeOrder.id,1));const body=await input({price:'7.00'}),context=ctx(),before=await effects();await expect(service.ledger.local('change_price',context,body,async db=>{await db.update(storeOrder).set({payPrice:'7.00'}).where(eq(storeOrder.id,1));throw Error('Actual SQL transaction failure before commit');})).rejects.toThrow('before commit');expect(await effects()).toEqual(before);expect((await service.status(f.actor(),context.request_key)).receipt).toBeNull();const abandoned=await service.abandon(f.actor(),context.request_key,{kind:'change_price',input:body},context.request_key);expect(abandoned.receipt?.outcome).toBe('abandoned');expect((await service.price(context,body)).receipt).toEqual(abandoned.receipt);expect(await effects()).toEqual(before);});
 it('deduplicates a true same-UUID race across two independently authenticated LOGIN sessions',async()=>{await f.maintenanceDb.update(storeOrder).set({paid:0}).where(eq(storeOrder.id,1));const body=await input({price:'7.00'}),context=ctx();await f.withPeer(async(db,pid)=>{expect(pid).toBeGreaterThan(0);const peer=new CustomerWorkFinancialService(createContainerFromDb(db),f.env),results=await Promise.all([service.price(context,body),peer.price(context,body)]);expect(results[0].receipt).toEqual(results[1].receipt);expect(results.filter(x=>x.replayed)).toHaveLength(1);});expect(await ledger()).toHaveLength(1);});
 it('rechecks revoked customer authority after a real order wait and freezes the original intent',async()=>{await f.maintenanceDb.update(storeOrder).set({paid:0}).where(eq(storeOrder.id,1));const body=await input({price:'7.00'}),context=ctx();let pending:ReturnType<typeof service.price>|undefined;await f.maintenanceDb.transaction(async db=>{await db.execute(sql`SELECT id FROM public.store_order WHERE id=1 FOR UPDATE`);pending=service.price(context,body);const deadline=Date.now()+1200;let blocked=false;while(Date.now()<deadline){const rows=await db.execute(sql`SELECT pid FROM pg_stat_activity WHERE usename=${f.role} AND wait_event_type='Lock'`);if(rows.length){blocked=true;break;}await new Promise(r=>setTimeout(r,10));}expect(blocked).toBe(true);(body.payload as {price:string}).price='9.00';await db.update(storeService).set({customer:0}).where(eq(storeService.id,1));});const result=await pending!;expect(result.receipt?.outcome).toBe('rollback-rejected');expect(await order()).toMatchObject({payPrice:'10.00'});const original=await service.ledger.original(f.actor(),context.request_key);expect(original?.p.input.payload).toEqual({price:'7.00'});});
 it('waits for the mature refund fence before taking an order lock for a remark',async()=>{const id=await application(1),body=await note(id),context=ctx();let pending:ReturnType<typeof service.remark>|undefined;await withTx(createContainerFromDb(f.maintenanceDb),async db=>{await lockRefundExecution(db,id);await db.select().from(storeOrderRefund).where(eq(storeOrderRefund.id,id)).for('update');pending=service.remark(context,body);const deadline=Date.now()+1000;let blocked=false;while(Date.now()<deadline){const rows=await db.execute(sql`SELECT pid FROM pg_stat_activity WHERE usename=${f.role} AND wait_event_type='Lock'`);if(rows.length){blocked=true;break;}await new Promise(r=>setTimeout(r,10));}expect(blocked).toBe(true);await db.execute(sql`SELECT id FROM public.store_order WHERE id=1 FOR UPDATE NOWAIT`);});expect((await pending!).receipt?.outcome).toBe('refund-remark-saved');});
 it('selects the exact physical row when a peer opaque numeric ID collides with that PK',async()=>{const original=(await f.maintenanceDb.select().from(storeOrderCartInfo).where(eq(storeOrderCartInfo.id,1)))[0],raw=JSON.parse(original.cartInfo!);await f.maintenanceDb.update(storeOrderCartInfo).set({cartNum:1,splitSurplusNum:1,writeTimes:1,writeSurplusTimes:1,cartInfo:JSON.stringify({...raw,cart_num:1,sum_true_price:'5.00'})}).where(eq(storeOrderCartInfo.id,1));await f.maintenanceDb.insert(storeOrderCartInfo).values({...original,id:4,oid:1,cartId:'1',unique:'collision-peer',cartNum:1,splitSurplusNum:1,writeTimes:1,writeSurplusTimes:1,cartInfo:JSON.stringify({...raw,id:'1',cart_num:1,sum_true_price:'5.00'})});const created=await create(1,[{cart_row_id:1,cart_num:1}]),claim=readRefundQuantityReservation(await refund(created.id));expect(claim?.items).toMatchObject([{rowId:1,sourceCartId:'501'}]);expect((await f.db.select().from(storeOrderCartInfo).where(eq(storeOrderCartInfo.id,4)))[0].refundNum).toBe(0);expect((await execute(created.id)).result.execution?.completed).toBe(true);});
 it('retains the old mature numeric alias collision rejection while customer row v3 is exact',async()=>{const original=(await f.maintenanceDb.select().from(storeOrderCartInfo).where(eq(storeOrderCartInfo.id,1)))[0];await f.maintenanceDb.insert(storeOrderCartInfo).values({...original,id:4,oid:1,cartId:'1',unique:'default-collision'});await f.maintenanceDb.update(storeOrder).set({totalNum:4,totalPrice:'20.00',payPrice:'20.00'}).where(eq(storeOrder.id,1));await expect(applyOrderRefund(f.container,{uid:11,orderId:'customer-financial-1',applyType:1,refundReason:'Mature default remains numeric',refundExplain:'Mature default alias collision must stay rejected',cartSelections:[{cartId:1,cartNum:1}]},0)).rejects.toThrow();expect(await ledger()).toEqual([]);});
 it('binds a nonnumeric opaque source to stock, quota receipt and the actual paid payment family',async()=>{
  const cart=(await f.maintenanceDb.select().from(storeOrderCartInfo).where(eq(storeOrderCartInfo.id,1)))[0];
  await f.maintenanceDb.update(storeOrderCartInfo).set({cartId:'opaque:原商品-A',cartInfo:JSON.stringify({...JSON.parse(cart.cartInfo!),id:'opaque:原商品-A'})}).where(eq(storeOrderCartInfo.id,1));
  const created=await create(1,[{cart_row_id:1,cart_num:1}]),completed=await execute(created.id);expect(completed.result.execution?.completed).toBe(true);
  const proof=await tx(db=>readPurchaseQuotaRefundFamily(db,{paymentOrderId:1,buyerId:11}));expect(proof[0].lines[0].sourceCartId).toBe('opaque:原商品-A');
  // Real legacy refund/stock remains supported, but no immutable checkout origin
  // exists for this seed. It cannot certify original purchased quantity.
  await expect(quotaRead(db=>readPurchaseQuotaPaymentLedger(db,{paymentOrderId:1,buyerId:11}))).rejects.toThrow('累计限购购买与退款归属不一致');
  expect((await f.db.select().from(storeProductAttrValue).where(eq(storeProductAttrValue.productId,70)))[0].stock).toBe(11);
  const actual=await f.realPurchase();expect(actual.origin.lines[0].cartId).toMatch(/^[1-9]\d*$/);
  const paidBefore=await paidReplayEffects();expect(actual.order).toMatchObject({pid:0,paid:1,supplierAllocationStatus:2});
  expect(await actual.consumer.processMessage(actual.message)).toBe('already-completed');expect(await paidReplayEffects()).toEqual(paidBefore);
  expect(await quotaRead(db=>readPurchaseQuotaPaymentLedger(db,{paymentOrderId:actual.order.id,buyerId:11})))
    .toMatchObject({products:[{productId:70,purchased:2,refunded:0,pending:0,remaining:2}]});
  const next=await create(actual.order.id,[{cart_row_id:actual.line.id,cart_num:1}]),returned=await execute(next.id);
  expect(returned.result.execution).toMatchObject({status:'BALANCE_SUCCESS',completed:true,verified:true});
  expect(await quotaRead(db=>readPurchaseQuotaPaymentLedger(db,{paymentOrderId:actual.order.id,buyerId:11})))
    .toMatchObject({products:[{productId:70,purchased:2,refunded:1,pending:0,remaining:1}]});
  expect(await order(actual.order.id)).toMatchObject({pid:-1,type:0});const lateBefore=await paidReplayEffects();
  await expect(actual.consumer.processMessage(actual.message)).rejects.toThrow('Distributor upgrade requires the actual paid root order');
  expect(await paidReplayEffects()).toEqual(lateBefore);expect((await service.status(f.actor(),returned.context.request_key)).execution?.verified).toBe(true);
 },60000);
 it('shares the actual one-open-application fence and quantity capacity across mature v1 and customer v3',async()=>{const old=await application(1,1);await expect(quote(1,[{cart_row_id:1,cart_num:1}])).rejects.toThrow('进行中');expect((await f.db.select().from(storeOrderCartInfo).where(eq(storeOrderCartInfo.id,1)))[0].refundNum).toBe(1);expect((await service.execute('refund_refuse',ctx(),await decision(old,'refund_refuse'))).receipt?.outcome).toBe('refused');const created=await create(1,[{cart_row_id:1,cart_num:1}]);expect(readRefundQuantityReservation(await refund(created.id))?.items[0].beforeRefundNum).toBe(0);await expect(application(1,1)).rejects.toThrow('进行中');expect((await f.db.select().from(storeOrderCartInfo).where(eq(storeOrderCartInfo.id,1)))[0].refundNum).toBe(1);});
 it.each([false,true])('proves mature reservation-v1 completion for whole=%s without inventing a split',async whole=>{const id=await application(1,whole?2:1),completed=await execute(id);expect(completed.result.execution).toMatchObject({status:'BALANCE_SUCCESS',completed:true,verified:true});expect(await f.db.select().from(storeOrderRefundSplit)).toEqual([]);if(!whole){const later=await application(1,1),second=await execute(later);expect(second.result.execution?.completed).toBe(true);expect((await service.status(f.actor(),completed.context.request_key)).execution?.completed).toBe(true);}});
 it('proves an existing materialized-v2 claim through the same ordinary financial execution',async()=>{const id=await application(1,1,true),completed=await execute(id);expect(readRefundQuantityReservation(await refund(id))?.version).toBe('refund-quantity-materialization-v2');expect(completed.result.execution).toMatchObject({status:'BALANCE_SUCCESS',completed:true,verified:true});expect(await f.db.select().from(storeOrderRefundSplit)).toHaveLength(1);});
 it('follows two successor splits and invoice allocations, then quotes and completes the third generation',async()=>{
  const actual=await f.realPurchase(3),paidBefore=await paidReplayEffects();
  expect(actual.order).toMatchObject({pid:0,paid:1,supplierAllocationStatus:2});
  expect(await actual.consumer.processMessage(actual.message)).toBe('already-completed');expect(await paidReplayEffects()).toEqual(paidBefore);
  await f.maintenanceDb.insert(storeOrderInvoice).values({orderId:actual.order.id,uid:11,category:'order',invoiceAmount:'15.00',isPay:1,isInvoice:0});
  const first=await create(actual.order.id,[{cart_row_id:actual.line.id,cart_num:1}]),one=await execute(first.id),
    a=(await f.db.select().from(storeOrderRefundSplit).where(eq(storeOrderRefundSplit.refundId,first.id)))[0],
    row=(await f.db.select().from(storeOrderCartInfo).where(eq(storeOrderCartInfo.oid,a.remainingOrderId!)))[0],
    second=await create(a.remainingOrderId!,[{cart_row_id:row.id,cart_num:1}]),two=await execute(second.id),
    b=(await f.db.select().from(storeOrderRefundSplit).where(eq(storeOrderRefundSplit.refundId,second.id)))[0];
  expect(b.remainingOrderId).toBe(a.remainingOrderId);expect((await quote(b.remainingOrderId!)).data.quoted_price).toBe('5.00');
  const third=await create(b.remainingOrderId!),three=await execute(third.id);
  for(const operation of[one,two,three])expect((await service.status(f.actor(),operation.context.request_key)).execution).toMatchObject({status:'BALANCE_SUCCESS',completed:true,verified:true});
  expect(await quotaRead(db=>readPurchaseQuotaPaymentLedger(db,{paymentOrderId:actual.order.id,buyerId:11})))
    .toMatchObject({products:[{productId:70,purchased:3,refunded:3,remaining:0}]});
  expect(await order(actual.order.id)).toMatchObject({pid:-1,type:0});const lateBefore=await paidReplayEffects();
  await expect(actual.consumer.processMessage(actual.message)).rejects.toThrow('Distributor upgrade requires the actual paid root order');
  expect(await paidReplayEffects()).toEqual(lateBefore);
  for(const operation of[one,two,three])expect((await service.status(f.actor(),operation.context.request_key)).execution?.verified).toBe(true);
  },60000);
 it('restores retired SKU quantity while preserving the mature retired product stock policy',async()=>{await f.maintenanceDb.update(storeProductAttrValue).set({isRetired:1}).where(eq(storeProductAttrValue.productId,70));const created=await create(1,[{cart_row_id:1,cart_num:1}]);expect((await execute(created.id)).result.execution?.completed).toBe(true);expect((await f.db.select().from(storeProduct).where(eq(storeProduct.id,70)))[0].stock).toBe(10);expect((await f.db.select().from(storeProductAttrValue).where(eq(storeProductAttrValue.productId,70)))[0].stock).toBe(11);});
 it.each([1,2,3,4] as const)('proves actual type %s base and activity stock/quota/sales, with one original execution',async type=>{
  const activity=await activityOrder(type),id=type===3?await application(1,1):(await create(1,[{cart_row_id:1,cart_num:1}])).id,completed=await execute(id);expect(completed.result.execution).toMatchObject({status:'BALANCE_SUCCESS',completed:true,verified:true});
  expect((await f.db.select().from(activity.table).where(eq(activity.table.id,activity.activityId)))[0]).toMatchObject({stock:11,quota:11,sales:1});expect((await f.db.select().from(storeProductAttrValue).where(eq(storeProductAttrValue.id,activity.skuId)))[0]).toMatchObject({productId:170,type,stock:11,quota:11,sales:1});expect((await f.db.select().from(storeProductAttrValue).where(eq(storeProductAttrValue.id,1)))[0]).toMatchObject({stock:11,sales:1});expect((await f.db.select().from(storeProduct).where(eq(storeProduct.id,70)))[0]).toMatchObject({stock:11,sales:1});const before=await effects();expect((await service.execute('refund_execute',completed.context,completed.body)).execution?.completed).toBe(true);expect(await effects()).toEqual(before);
 });
 it('resolves the actual owner-scoped legacy bargain participant alias to its canonical activity',async()=>{
  const activity=await activityOrder(2),cart=(await f.maintenanceDb.select().from(storeOrderCartInfo).where(eq(storeOrderCartInfo.id,1)))[0],raw=JSON.parse(cart.cartInfo!);delete raw.bargainParticipation;await f.maintenanceDb.update(storeOrderCartInfo).set({cartInfo:JSON.stringify(raw)}).where(eq(storeOrderCartInfo.id,1));await f.maintenanceDb.update(storeOrder).set({activityId:270}).where(eq(storeOrder.id,1));const id=await application(1,1),completed=await execute(id);expect(completed.result.execution?.completed).toBe(true);expect((await f.db.select().from(storeBargain).where(eq(storeBargain.id,activity.activityId)))[0]).toMatchObject({stock:11,quota:11,sales:1});expect((await f.db.select().from(storeProductAttrValue).where(eq(storeProductAttrValue.id,activity.skuId)))[0]).toMatchObject({productId:170,type:2,stock:11,quota:11,sales:1});
 });
 it.each([1,2,3] as const)('preserves the exact type %s missing-main legacy snapshot exception without inventing activity returns',async type=>{
  const activity=await activityOrder(type),cart=(await f.maintenanceDb.select().from(storeOrderCartInfo).where(eq(storeOrderCartInfo.id,1)))[0],raw=JSON.parse(cart.cartInfo!);delete raw.activitySku;delete raw.bargainParticipation;await f.maintenanceDb.update(storeOrderCartInfo).set({cartInfo:JSON.stringify(raw)}).where(eq(storeOrderCartInfo.id,1));await f.maintenanceDb.delete(activity.table).where(eq(activity.table.id,activity.activityId));if(type===2)await f.maintenanceDb.update(storeOrder).set({activityId:270}).where(eq(storeOrder.id,1));const id=await application(1,1),completed=await execute(id);expect(completed.result.execution?.completed).toBe(true);expect(await f.db.select().from(activity.table)).toEqual([]);expect((await f.db.select().from(storeProductAttrValue).where(eq(storeProductAttrValue.id,activity.skuId)))[0]).toMatchObject({stock:10,quota:10,sales:2});expect((await f.db.select().from(storeProductAttrValue).where(eq(storeProductAttrValue.id,1)))[0]).toMatchObject({stock:11,sales:1});
 });
 it.each([0,1] as const)('returns bundle limit only on the actual final generation when isLimit=%s',async isLimit=>{
  await f.maintenanceDb.insert(storeDiscounts).values({id:170,isLimit,limitNum:10});await f.maintenanceDb.update(storeOrder).set({type:5,activityId:170}).where(eq(storeOrder.id,1));const first=await create(1,[{cart_row_id:1,cart_num:1}]),one=await execute(first.id),split=(await f.db.select().from(storeOrderRefundSplit).where(eq(storeOrderRefundSplit.refundId,first.id)))[0];expect(one.result.execution?.completed).toBe(true);expect((await f.db.select().from(storeDiscounts).where(eq(storeDiscounts.id,170)))[0].limitNum).toBe(10);const second=await create(split.remainingOrderId!),two=await execute(second.id);expect(two.result.execution?.completed).toBe(true);expect((await f.db.select().from(storeDiscounts).where(eq(storeDiscounts.id,170)))[0].limitNum).toBe(10+isLimit);const before=await effects();expect((await service.execute('refund_execute',two.context,two.body)).execution?.completed).toBe(true);expect(await effects()).toEqual(before);expect((await service.status(f.actor(),one.context.request_key)).execution?.completed).toBe(true);
 });
 it.each(['missing-main','wrong-sku','missing-stock-return','missing-sku-return'] as const)('rolls actual integral activity funds and all quantities back for %s',async mutant=>{
  const activity=await activityOrder(4),created=await create(1,[{cart_row_id:1,cart_num:1}]);let trigger=false;
  if(mutant==='missing-main')await f.maintenanceDb.delete(storeIntegral).where(eq(storeIntegral.id,activity.activityId));else if(mutant==='wrong-sku'){const cart=(await f.maintenanceDb.select().from(storeOrderCartInfo).where(eq(storeOrderCartInfo.id,1)))[0],raw=JSON.parse(cart.cartInfo!);await f.maintenanceDb.update(storeOrderCartInfo).set({cartInfo:JSON.stringify({...raw,activitySku:{id:1}})}).where(eq(storeOrderCartInfo.id,1));}else{const table=mutant==='missing-sku-return'?'store_product_attr_value':'store_integral',body=mutant==='missing-sku-return'?'IF OLD.type=4 THEN NEW.stock:=OLD.stock; END IF;':'NEW.stock:=OLD.stock;';await f.exec(`CREATE FUNCTION public.owned_financial_hold_integral_stock() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN ${body} RETURN NEW; END $$;CREATE TRIGGER owned_financial_hold_integral_stock BEFORE UPDATE ON public.${table} FOR EACH ROW EXECUTE FUNCTION public.owned_financial_hold_integral_stock()`);trigger=true;}
  try{const before=await effects(),completed=await execute(created.id);expect(completed.result.receipt?.outcome).toBe('rollback-rejected');expect(completed.result.execution).toBeNull();expect(await effects()).toEqual(before);expect((await refund(created.id)).refundType).toBe(0);}finally{if(trigger)await f.exec(`DROP TRIGGER owned_financial_hold_integral_stock ON public.${mutant==='missing-sku-return'?'store_product_attr_value':'store_integral'};DROP FUNCTION public.owned_financial_hold_integral_stock()`);}
 });

 for(const kind of ['wechat','alipay'] as const){
  it(`${kind}: commits the complete original admission before external I/O and completes actual mature business effects`,async()=>{await provider(kind);const created=await create(1,[{cart_row_id:1,cart_num:1}]),body=await decision(created.id,'refund_execute'),context=ctx();const request=vi.spyOn(gateway(kind),'requestRefund').mockImplementation(async(args:RefundProviderRequest)=>{await f.withPeer(async(db,pid)=>{const receipts=await db.execute(sql`SELECT outcome,request_key::text AS key FROM public.customer_financial_operation_request WHERE actor_uid=101 AND request_key=${context.request_key}::uuid`);expect(receipts).toEqual([{outcome:'provider-admitted',key:context.request_key}]);const pending=await db.execute(sql`SELECT provider_status,request_amount,total_amount,out_refund_no FROM public.store_order_refund_payment WHERE refund_id=${created.id}`);expect(pending[0]).toMatchObject({provider_status:'REQUESTING',request_amount:500,total_amount:1000,out_refund_no:'CNSR'+created.id});const states=await db.execute(sql`SELECT state FROM pg_stat_activity WHERE usename=${f.role} AND pid<>${pid}`);expect(states.every(x=>x.state!=='idle in transaction')).toBe(true);});expect(args).toMatchObject({outTradeNo:'customer-financial-1',outRefundNo:'CNSR'+created.id,refundAmount:500,totalAmount:1000});return{status:'SUCCESS',providerRefundId:'owned-'+kind};});const result=await service.execute('refund_execute',context,body);expect(request).toHaveBeenCalledTimes(1);expect(result).toMatchObject({receipt:{outcome:'provider-admitted',evidence:{provider:kind,request_amount:500,total_amount:1000}},execution:{status:'SUCCESS',completed:true,verified:true}});expect((await refund(created.id)).refundType).toBe(6);expect(await f.db.select().from(storeOrderRefundSplit)).toHaveLength(1);});
  it(`${kind}: keeps UNKNOWN under its original UUID, GET does no I/O, and explicit original POST queries before recovery`,async()=>{await provider(kind);const created=await create(1,[{cart_row_id:1,cart_num:1}]),body=await decision(created.id,'refund_execute'),context=ctx(),request=vi.spyOn(gateway(kind),'requestRefund').mockResolvedValue({status:'UNKNOWN',message:'owned uncertain provider boundary'}),query=vi.spyOn(gateway(kind),'queryRefund').mockResolvedValue({status:'SUCCESS',providerRefundId:'owned-recovery-'+kind}),admitted=await service.execute('refund_execute',context,body);expect(admitted).toMatchObject({receipt:{outcome:'provider-admitted'},execution:{status:'UNKNOWN',completed:false,can_resume:true}});expect(query).not.toHaveBeenCalled();expect((await service.status(f.actor(),context.request_key)).receipt).toEqual(admitted.receipt);expect(query).not.toHaveBeenCalled();expect((await service.abandon(f.actor(),context.request_key,{kind:'refund_execute',input:body},context.request_key)).receipt).toEqual(admitted.receipt);const result=await service.execute('refund_execute',context,body);expect(query).toHaveBeenCalledTimes(1);expect(request).toHaveBeenCalledTimes(1);expect(result.receipt).toEqual(admitted.receipt);expect(result.execution).toMatchObject({status:'SUCCESS',completed:true,verified:true});});
  it(`${kind}: requests again only after factual NOT_FOUND, reusing the original out-refund number and amount`,async()=>{await provider(kind);const created=await create(1,[{cart_row_id:1,cart_num:1}]),body=await decision(created.id,'refund_execute'),context=ctx(),request=vi.spyOn(gateway(kind),'requestRefund').mockResolvedValueOnce({status:'UNKNOWN'}).mockResolvedValue({status:'PROCESSING'}),query=vi.spyOn(gateway(kind),'queryRefund').mockResolvedValue({status:'NOT_FOUND'});const first=await service.execute('refund_execute',context,body),next=await service.execute('refund_execute',context,body);expect(query).toHaveBeenCalledTimes(1);expect(request).toHaveBeenCalledTimes(2);expect(request.mock.calls[1][0]).toEqual(request.mock.calls[0][0]);expect(next.receipt).toEqual(first.receipt);expect(next.execution).toMatchObject({status:'PROCESSING',completed:false});});
  it(`${kind}: preserves admitted original intent under a real authority table lock, then explicitly resumes the same UUID once`,async()=>{
   await provider(kind);const created=await create(1,[{cart_row_id:1,cart_num:1}]),body=await decision(created.id,'refund_execute'),context=ctx(),request=vi.spyOn(gateway(kind),'requestRefund').mockResolvedValue({status:'UNKNOWN'}),query=vi.spyOn(gateway(kind),'queryRefund').mockResolvedValue({status:'SUCCESS',providerRefundId:'owned-lock-recovery-'+kind}),accepted=await service.execute('refund_execute',context,body),before=await effects(),originalLedger=await ledger();
   expect(accepted).toMatchObject({receipt:{request_key:context.request_key,outcome:'provider-admitted'},execution:{status:'UNKNOWN',completed:false,can_resume:true}});expect(request).toHaveBeenCalledTimes(1);expect(query).not.toHaveBeenCalled();
   const [runtimeIdentity]=await f.db.execute<{database:string;role:string;session:string;pid:number}>(sql`SELECT current_database() AS database,current_user AS role,session_user AS session,pg_backend_pid() AS pid`);expect(runtimeIdentity.role).toBe(f.role);expect(runtimeIdentity.session).toBe(f.role);
   await f.maintenanceDb.transaction(async maintenance=>{
    const [identity]=await maintenance.execute<{database:string;role:string;session:string;pid:number}>(sql`SELECT current_database() AS database,current_user AS role,session_user AS session,pg_backend_pid() AS pid`);expect(identity.database).toBe(runtimeIdentity.database);expect(identity.role).toBe('finance_test');expect(identity.session).toBe('finance_test');expect(identity.pid).not.toBe(runtimeIdentity.pid);
    await maintenance.execute(sql`LOCK TABLE public.store_service IN ROW EXCLUSIVE MODE`);expect(await f.db.execute(sql`SELECT mode,granted FROM pg_catalog.pg_locks WHERE pid=${identity.pid} AND relation='public.store_service'::regclass AND locktype='relation'`)).toEqual([{mode:'RowExclusiveLock',granted:true}]);
    // This actual caller-owned SQL proves NOWAIT contention. The accepted POST
    // catches its own failed authorization and returns the immutable receipt.
    await expect(tx(db=>db.execute(sql`SELECT public.customer_work_lock_scope_v1(101::integer)`))).rejects.toMatchObject({cause:{code:'55P03'}});
    const blocked=await service.execute('refund_execute',context,body);expect(blocked.receipt).toEqual(accepted.receipt);expect(blocked.execution).toMatchObject({status:'UNKNOWN',completed:false,can_resume:true});expect(await service.ledger.original(f.actor(),context.request_key)).toMatchObject({receipt:accepted.receipt,p:{key:context.request_key,input:body}});expect(await service.status(f.actor(),context.request_key)).toMatchObject({receipt:accepted.receipt,execution:{status:'UNKNOWN',completed:false}});expect(await ledger()).toEqual(originalLedger);expect(await effects()).toEqual(before);expect(request).toHaveBeenCalledTimes(1);expect(query).not.toHaveBeenCalled();
   });
   const recovered=await service.execute('refund_execute',context,body);expect(recovered.receipt).toEqual(accepted.receipt);expect(recovered.execution).toMatchObject({request_key:context.request_key,status:'SUCCESS',completed:true,verified:true});expect(query).toHaveBeenCalledTimes(1);expect(request).toHaveBeenCalledTimes(1);expect(query.mock.calls[0][0]).toEqual(request.mock.calls[0][0]);expect((await refund(created.id)).refundType).toBe(6);expect(await f.db.select().from(storeOrderRefundSplit)).toHaveLength(1);expect(await ledger()).toEqual(originalLedger);
   const completedEffects=await effects();expect((await service.execute('refund_execute',context,body)).execution?.completed).toBe(true);expect(await effects()).toEqual(completedEffects);expect(query).toHaveBeenCalledTimes(1);expect(request).toHaveBeenCalledTimes(1);
  });
 }
 it('preserves original owner admission after role withdrawal, clears PII and prohibits another actor recovery',async()=>{await provider('wechat');const created=await create(1,[{cart_row_id:1,cart_num:1}]),body=await decision(created.id,'refund_execute'),context=ctx(),request=vi.spyOn(WechatPayService.prototype,'requestRefund').mockResolvedValue({status:'UNKNOWN'}),query=vi.spyOn(WechatPayService.prototype,'queryRefund').mockResolvedValue({status:'SUCCESS'}),accepted=await service.execute('refund_execute',context,body);await f.maintenanceDb.update(storeService).set({customer:0}).where(eq(storeService.id,1));const owner=await service.status(f.actor(),context.request_key);expect(owner.receipt).toEqual(accepted.receipt);expect(owner.execution).toMatchObject({completed:false,can_resume:false});expect(JSON.stringify(owner)).not.toMatch(/refundExplain|nickname|address|phone|intent|顾客/);expect(await service.status(f.actor(102),context.request_key)).toEqual({receipt:null,replayed:false,execution:null});expect((await service.execute('refund_execute',context,body)).receipt).toEqual(accepted.receipt);expect(request).toHaveBeenCalledTimes(1);expect(query).not.toHaveBeenCalled();});
 it('does not call a fresh REQUESTING lease or confuse provider SUCCESS with unfinished local business',async()=>{await provider('wechat');const created=await create(1,[{cart_row_id:1,cart_num:1}]),body=await decision(created.id,'refund_execute'),context=ctx(),request=vi.spyOn(WechatPayService.prototype,'requestRefund').mockResolvedValue({status:'UNKNOWN'}),query=vi.spyOn(WechatPayService.prototype,'queryRefund').mockResolvedValue({status:'UNKNOWN'});await service.execute('refund_execute',context,body);await f.maintenanceDb.update(storeOrderRefundPayment).set({providerStatus:'REQUESTING',requestTime:Math.floor(Date.now()/1000)}).where(eq(storeOrderRefundPayment.refundId,created.id));expect((await service.execute('refund_execute',context,body)).execution?.completed).toBe(false);expect(request).toHaveBeenCalledTimes(1);expect(query).not.toHaveBeenCalled();await f.maintenanceDb.update(storeOrderRefundPayment).set({providerStatus:'SUCCESS'}).where(eq(storeOrderRefundPayment.refundId,created.id));expect((await service.status(f.actor(),context.request_key)).execution).toMatchObject({status:'UNKNOWN',completed:false,verified:false});});
 it('enforces the actual int4-cent channel payment-root limit before any funds intent',async()=>{await provider('wechat');const id=await application(1);await f.maintenanceDb.update(storeOrder).set({payPrice:'21474836.48'}).where(eq(storeOrder.id,1));const display=await review(id);expect(display.data.actions.refund_execute).toMatchObject({available:false});expect(display.data.actions.refund_execute.reason).toContain('21474836.47');const result=await service.execute('refund_execute',ctx(),await decision(id,'refund_execute'));expect(result.receipt?.outcome).toBe('rollback-rejected');expect(await f.db.select().from(storeOrderRefundPayment)).toEqual([]);expect((await refund(id)).refundType).toBe(0);});
 it('keeps an admitted legacy row without modern claim unverified instead of fabricating a materializer receipt',async()=>{await provider('wechat');const id=await application(1),body=await decision(id,'refund_execute'),context=ctx(),p=await prepareFinancialOperation('refund_execute',context,body),original=await refund(id);await tx(async db=>{await checkFinancialOperation(db,p);const scope=await authorizeFinancialOperation(db,p);await db.insert(storeOrderRefundPayment).values({refundId:id,storeOrderId:1,provider:'wechat',outRefundNo:'CNSR'+id,requestAmount:500,totalAmount:1000,providerStatus:'SUCCESS'});await appendFinancialOperation(db,p,scope.service_id,'provider-admitted',{refund_id:id,refund_no:original.orderId,payment_order_id:1,uid:11,store_id:0,supplier_id:0,provider:'wechat',out_refund_no:'CNSR'+id,request_amount:500,total_amount:1000,verified:true});});await f.maintenanceDb.update(storeOrderRefund).set({cartInfo:'[]',refundType:6,refundedPrice:'5.00'}).where(eq(storeOrderRefund.id,id));const result=await service.status(f.actor(),context.request_key);expect(result.execution).toMatchObject({status:'UNKNOWN',completed:false,verified:false});expect(await f.db.select().from(storeOrderRefundSplit)).toEqual([]);});
 it('keeps a completed v1 original key verified through a later pending claim and its actual refusal',async()=>{const first=await application(1),completed=await execute(first),second=await application(1);expect((await service.status(f.actor(),completed.context.request_key)).execution).toMatchObject({status:'BALANCE_SUCCESS',completed:true,verified:true});await service.execute('refund_refuse',ctx(),await decision(second,'refund_refuse'));expect((await service.status(f.actor(),completed.context.request_key)).execution).toMatchObject({status:'BALANCE_SUCCESS',completed:true,verified:true});});
 it('pays the actual pure-integral activity, returns its real bills and both inventories exactly once',async()=>{
  const activity=await activityOrder(4,true),paid=await applyStoreOrderPayment(f.container,{orderId:1,payType:PayType.INTEGRAL});expect(paid.outcome).toBe('paid');expect((await f.db.select().from(user).where(eq(user.uid,11)))[0].integral).toBe(80);expect(await f.db.select().from(userBill).where(eq(userBill.type,'storeIntegral_use_integral'))).toMatchObject([{uid:11,linkId:'1',eventKey:'order_pay_integral',number:'20.00',pm:0,status:1}]);
  const created=await create(),completed=await execute(created.id);expect(completed.result.execution).toMatchObject({status:'BALANCE_SUCCESS',completed:true,verified:true});const bills=await f.db.select().from(userBill).where(eq(userBill.type,'order_integral_refund'));expect(bills).toMatchObject([{uid:11,eventKey:'order_integral_refund',number:'20.00',pm:1,status:1}]);expect((await f.db.select().from(user).where(eq(user.uid,11)))[0].integral).toBe(100);
  expect((await f.db.select().from(storeIntegral).where(eq(storeIntegral.id,activity.activityId)))[0]).toMatchObject({stock:12,quota:12,sales:0});expect((await f.db.select().from(storeProductAttrValue).where(eq(storeProductAttrValue.id,activity.skuId)))[0]).toMatchObject({stock:12,quota:12,sales:0});expect((await f.db.select().from(storeProductAttrValue).where(eq(storeProductAttrValue.id,1)))[0]).toMatchObject({stock:12,sales:0});expect((await f.db.select().from(storeProduct).where(eq(storeProduct.id,70)))[0]).toMatchObject({stock:12,sales:0});
  const before=await effects();expect((await service.execute('refund_execute',completed.context,completed.body)).execution?.completed).toBe(true);expect(await effects()).toEqual(before);await corruptOwnedSplit(created.id,{returnedPointBillIds:'[]'});expect((await service.status(f.actor(),completed.context.request_key)).execution).toMatchObject({status:'UNKNOWN',completed:false,verified:false});
 });
 it('rejects first delayed origin-backed presale paid consumption after refund without inventing prior allocation',async()=>{
  const actual=await f.realPurchase(2,true,false);expect(actual.order).toMatchObject({type:6,pid:0,paid:1,supplierAllocationStatus:0});
  expect(actual.paidEvent).toMatchObject({status:'PENDING',attemptCount:0,processedTime:0});
  const created=await create(actual.order.id,[{cart_row_id:actual.line.id,cart_num:1}]),completed=await execute(created.id);
  expect(completed.result.execution).toMatchObject({status:'BALANCE_SUCCESS',completed:true,verified:true});
  const family=await f.db.select().from(storeOrder).where(sql`${storeOrder.id}=${actual.order.id} OR ${storeOrder.pid}=${actual.order.id}`).orderBy(asc(storeOrder.id));
  expect(family).toHaveLength(3);for(const row of family)expect(row).toMatchObject({uid:11,type:6,productType:1,paid:1,payType:'yue',payTime:actual.order.payTime,supplierAllocationStatus:0});
  await expect(tx(db=>preparePresalePaidRecovery(db,actual.order.id,actual.order.orderId))).rejects.toThrow('预售付款恢复的数量或子单凭据不一致');
  const before=await paidReplayEffects(),started=Math.floor(Date.now()/1000);
  expect(before.outbox.find(row=>row.id===actual.paidEvent.id)).toEqual(actual.paidEvent);
  await expect(actual.consumer.processMessage(actual.message)).rejects.toThrow('预售付款恢复的数量或子单凭据不一致');
  const after=await paidReplayEffects(),failed=after.outbox.find(row=>row.id===actual.paidEvent.id)!;
  expect(failed.updateTime).toBeGreaterThanOrEqual(started);expect(failed.updateTime).toBeLessThanOrEqual(Math.floor(Date.now()/1000));
  expect(failed.availableTime).toBe(failed.updateTime+30);
  expect(failed).toEqual({...actual.paidEvent,status:'FAILED',attemptCount:1,leaseUntil:0,leaseToken:'',
   availableTime:failed.updateTime+30,updateTime:failed.updateTime,lastError:'预售付款恢复的数量或子单凭据不一致'});
  expect({...after,outbox:after.outbox.map(row=>row.id===failed.id?actual.paidEvent:row)}).toEqual(before);
  expect(after.outbox.filter(row=>row.eventType===PRESALE_DELIVERY_EVENT)).toEqual([]);
  const cards=(await f.db.select().from(storeProductVirtual)).filter(row=>actual.virtualIds.includes(row.id));
  expect(cards.filter(row=>row.uid===11)).toHaveLength(0);expect(cards.filter(row=>row.uid===0)).toHaveLength(2);
  expect(await quotaRead(db=>readPurchaseQuotaPaymentLedger(db,{paymentOrderId:actual.order.id,buyerId:11})))
   .toMatchObject({products:[{productId:70,purchased:2,refunded:1,pending:0,remaining:1}]});
  expect((await service.status(f.actor(),completed.context.request_key)).execution).toMatchObject({status:'BALANCE_SUCCESS',completed:true,verified:true});
 },60000);
 it('delivers only the actual opaque presale remainder after a completed refund and a late paid-outbox retry',async()=>{
  await presaleOrder();
  const stockBefore=(await f.db.select().from(storeProductAttrValue).where(eq(storeProductAttrValue.id,1)))[0],productBefore=(await f.db.select().from(storeProduct).where(eq(storeProduct.id,70)))[0];const created=await create(1,[{cart_row_id:1,cart_num:1}]),completed=await execute(created.id);expect(completed.result.execution?.completed).toBe(true);expect((await f.db.select().from(storeProductAttrValue).where(eq(storeProductAttrValue.id,1)))[0]).toMatchObject({stock:stockBefore.stock+1,sales:Math.max(0,stockBefore.sales-1)});expect((await f.db.select().from(storeProduct).where(eq(storeProduct.id,70)))[0]).toMatchObject({stock:productBefore.stock+1,sales:Math.max(0,productBefore.sales-1)});const stockAfter=await f.db.select().from(storeProductAttrValue).where(eq(storeProductAttrValue.id,1)),productAfter=await f.db.select().from(storeProduct).where(eq(storeProduct.id,70));const recovered=await tx(db=>preparePresalePaidRecovery(db,1,'customer-financial-1'));expect(recovered?.refundIds.has(created.id)).toBe(true);expect(recovered?.activeOrderIds.size).toBe(1);
  const event=await tx(db=>enqueueOrderPaidEvent(db,{id:1,orderId:'customer-financial-1'})),outbox=new OrderOutboxService(f.container,f.env);expect(await outbox.processMessage({action:'processOrderPaidOutbox',outboxId:event.id,eventKey:event.eventKey})).toBe('completed');expect(await outbox.processMessage({action:'processOrderPaidOutbox',outboxId:event.id,eventKey:event.eventKey})).toBe('already-completed');const pending=(await f.db.select().from(storeOrderOutbox).where(eq(storeOrderOutbox.eventType,PRESALE_DELIVERY_EVENT)))[0];expect(pending).toBeTruthy();expect(await outbox.processMessage({action:'processPresaleDeliveryOutbox',outboxId:pending.id,eventKey:pending.eventKey})).toBe('completed');
  const cards=await f.db.select().from(storeProductVirtual);expect(cards.filter(x=>x.uid===11)).toHaveLength(1);expect(cards.filter(x=>x.uid===0)).toHaveLength(1);await expect(quotaRead(db=>readPurchaseQuotaPaymentLedger(db,{paymentOrderId:1,buyerId:11}))).rejects.toThrow('累计限购购买与退款归属不一致');expect((await service.status(f.actor(),completed.context.request_key)).execution?.completed).toBe(true);expect(await f.db.select().from(storeProductAttrValue).where(eq(storeProductAttrValue.id,1))).toEqual(stockAfter);expect(await f.db.select().from(storeProduct).where(eq(storeProduct.id,70))).toEqual(productAfter);
  // Independently prove current origin-backed presale through actual checkout,
  // balance debit and the COMPLETE original paid consumer before refund. Its
  // original delivery event remains delayed to the immutable database boundary.
  const actual=await f.realPurchase(2,true);
  const originalDelivery=(await f.db.select().from(storeOrderOutbox).where(eq(storeOrderOutbox.eventType,PRESALE_DELIVERY_EVENT)))
   .find(row=>(row.payload as {paymentOrderId?:number}).paymentOrderId===actual.order.id)!;
  expect(originalDelivery).toBeTruthy();expect(originalDelivery.status).toBe('PENDING');
  const next=await create(actual.order.id,[{cart_row_id:actual.line.id,cart_num:1}]),returned=await execute(next.id);
  expect(actual.order).toMatchObject({type:6,paid:1,pid:0,supplierAllocationStatus:2});expect(actual.paidEvent.status).toBe('COMPLETED');
  const family=await f.db.select().from(storeOrder).where(sql`${storeOrder.id}=${actual.order.id} OR ${storeOrder.pid}=${actual.order.id}`).orderBy(asc(storeOrder.id));
  expect(family).toHaveLength(3);for(const row of family)expect(row).toMatchObject({uid:11,type:6,productType:1,paid:1,payType:'yue',payTime:actual.order.payTime,supplierAllocationStatus:2});
  expect((await f.db.select().from(storeOrderOutbox).where(eq(storeOrderOutbox.id,actual.paidEvent.id)))[0]).toEqual(actual.paidEvent);
  const currentRecovery=await tx(db=>preparePresalePaidRecovery(db,actual.order.id,actual.order.orderId));
  expect(currentRecovery?.refundIds.has(next.id)).toBe(true);expect(currentRecovery?.activeOrderIds.size).toBe(1);
  expect(returned.result.execution).toMatchObject({status:'BALANCE_SUCCESS',completed:true,verified:true});
  const lateBefore=await paidReplayEffects();expect(await actual.consumer.processMessage(actual.message)).toBe('already-completed');
  expect(await paidReplayEffects()).toEqual(lateBefore);
  const delivery=(await f.db.select().from(storeOrderOutbox).where(eq(storeOrderOutbox.eventType,PRESALE_DELIVERY_EVENT)))
    .find(row=>(row.payload as {paymentOrderId?:number}).paymentOrderId===actual.order.id)!;expect(delivery).toBeTruthy();expect(delivery).toEqual(originalDelivery);
  const clockDeadline=Date.now()+45000;let due=false;
  while(Date.now()<clockDeadline){const [clock]=await f.db.execute<{due:boolean}>(sql`SELECT floor(extract(epoch FROM clock_timestamp()))>${actual.endsAt} AS due`);
    if(clock.due){due=true;break;}await new Promise(resolve=>setTimeout(resolve,100));}
  expect(due).toBe(true);expect(await actual.consumer.processMessage({action:'processPresaleDeliveryOutbox',outboxId:delivery.id,eventKey:delivery.eventKey})).toBe('completed');
  const actualCards=(await f.db.select().from(storeProductVirtual)).filter(row=>actual.virtualIds.includes(row.id));
  expect(actualCards.filter(row=>row.uid===11)).toHaveLength(1);expect(actualCards.filter(row=>row.uid===0)).toHaveLength(1);
  expect(await quotaRead(db=>readPurchaseQuotaPaymentLedger(db,{paymentOrderId:actual.order.id,buyerId:11})))
    .toMatchObject({products:[{productId:70,purchased:2,refunded:1,pending:0,remaining:1}]});
  expect((await service.status(f.actor(),returned.context.request_key)).execution?.completed).toBe(true);
 },90000);
 it.each(['child-uid','child-pay-type','child-pay-time','remaining-quantity','unfinished-refund'] as const)('fails the real archived presale paid event before upgrade for %s, then repairs and replays that event once',async mutant=>{
  await presaleOrder();const created=await create(1,[{cart_row_id:1,cart_num:1}]),completed=await execute(created.id);expect(completed.result.execution?.completed).toBe(true);const split=(await f.db.select().from(storeOrderRefundSplit).where(eq(storeOrderRefundSplit.refundId,created.id)))[0],child=(await f.maintenanceDb.select().from(storeOrder).where(eq(storeOrder.id,split.remainingOrderId!)))[0],cart=(await f.maintenanceDb.select().from(storeOrderCartInfo).where(eq(storeOrderCartInfo.oid,child.id)))[0],originalRefund=await refund(created.id),event=await tx(db=>enqueueOrderPaidEvent(db,{id:1,orderId:'customer-financial-1'})),consumer=new OrderOutboxService(f.container,f.env),message={action:'processOrderPaidOutbox' as const,outboxId:event.id,eventKey:event.eventKey};
  if(mutant==='child-uid')await f.maintenanceDb.update(storeOrder).set({uid:22}).where(eq(storeOrder.id,child.id));else if(mutant==='child-pay-type')await f.maintenanceDb.update(storeOrder).set({payType:'alipay'}).where(eq(storeOrder.id,child.id));else if(mutant==='child-pay-time')await f.maintenanceDb.update(storeOrder).set({payTime:101}).where(eq(storeOrder.id,child.id));else if(mutant==='remaining-quantity')await f.maintenanceDb.update(storeOrderCartInfo).set({cartNum:2}).where(eq(storeOrderCartInfo.id,cart.id));else await f.maintenanceDb.update(storeOrderRefund).set({refundType:5}).where(eq(storeOrderRefund.id,created.id));
  const before=await effects(),cardsBefore=await f.db.select().from(storeProductVirtual).orderBy(asc(storeProductVirtual.id)),buyerBefore=(await f.db.select().from(user).where(eq(user.uid,11)))[0],eventBefore=before.outbox.find(x=>x.id===event.id)!;await expect(consumer.processMessage(message)).rejects.toThrow();const after=await effects();expect({...after,outbox:[]}).toEqual({...before,outbox:[]});expect(await f.db.select().from(storeProductVirtual).orderBy(asc(storeProductVirtual.id))).toEqual(cardsBefore);expect((await f.db.select().from(user).where(eq(user.uid,11)))[0]).toEqual(buyerBefore);expect(after.outbox).toHaveLength(before.outbox.length);expect(after.outbox.find(x=>x.id===event.id)).toMatchObject({status:'FAILED',aggregateType:eventBefore.aggregateType,aggregateId:eventBefore.aggregateId,eventType:eventBefore.eventType,eventKey:eventBefore.eventKey,payload:eventBefore.payload});
  await f.maintenanceDb.update(storeOrder).set({uid:child.uid,payType:child.payType,payTime:child.payTime}).where(eq(storeOrder.id,child.id));await f.maintenanceDb.update(storeOrderCartInfo).set({cartNum:cart.cartNum}).where(eq(storeOrderCartInfo.id,cart.id));await f.maintenanceDb.update(storeOrderRefund).set({refundType:originalRefund.refundType}).where(eq(storeOrderRefund.id,created.id));await consumer.replay(event.id);expect(await consumer.processMessage(message)).toBe('completed');expect(await consumer.processMessage(message)).toBe('already-completed');const paidEvent=(await f.db.select().from(storeOrderOutbox).where(eq(storeOrderOutbox.id,event.id)))[0];expect(paidEvent).toMatchObject({status:'COMPLETED',replayCount:1,eventKey:eventBefore.eventKey,payload:eventBefore.payload});expect((await f.db.select().from(user).where(eq(user.uid,11)))[0].payCount).toBe(buyerBefore.payCount+1);const delivery=(await f.db.select().from(storeOrderOutbox).where(eq(storeOrderOutbox.eventType,PRESALE_DELIVERY_EVENT)))[0];expect(delivery).toBeTruthy();expect(await consumer.processMessage({action:'processPresaleDeliveryOutbox',outboxId:delivery.id,eventKey:delivery.eventKey})).toBe('completed');expect((await f.db.select().from(storeProductVirtual)).filter(x=>x.uid===11)).toHaveLength(1);expect((await service.status(f.actor(),completed.context.request_key)).execution?.completed).toBe(true);
 });
 it.each(['null','scalar','missing-source','missing-points'] as const)('keeps the original completed key UNKNOWN when durable %s evidence is damaged',async mutant=>{const created=await create(),completed=await execute(created.id),record=(await f.maintenanceDb.select().from(storeOrderRefundSplit))[0],source=JSON.parse(record.sourceSnapshot);if(mutant==='null')source.source=null;else if(mutant==='scalar')source.source=1;else if(mutant==='missing-source')delete source.source;await corruptOwnedSplit(created.id,mutant==='missing-points'?{returnedPointBillIds:'[999999]'}:{sourceSnapshot:JSON.stringify(source)});const result=await service.status(f.actor(),completed.context.request_key);expect(result.receipt).toEqual(completed.result.receipt);expect(result.execution).toMatchObject({status:'UNKNOWN',completed:false,verified:false});});
});
