import {afterAll,beforeAll,beforeEach,describe,expect,it,vi} from 'vitest';
import {eq} from 'drizzle-orm';
import {createContainerFromDb,type DbClient} from '../src/lib/di';
import {createToken} from '../src/utils/jwt';
import {user,userGroup,userLabel,userLabelRelation,userLevel,systemUserLevel,legacyCategory,storeCouponIssue,storeCouponUser,storeCouponIssueUser,userMoney,userBill,otherOrder,otherOrderStatus,storeService,storeOrder,systemLog,adminUserWriteReplay} from '../src/models/schema';
import {customerWorkUserFixture} from './helpers/customerWorkUserFixture';
import {observeIntegralReadDb} from './helpers/integralProductReadFixture';
import {CustomerWorkUserReadService,customerUserIssueRevision,readCustomerUserState,CUSTOMER_USER_KINDS} from '../src/services/customer-work/CustomerWorkUserReadService';
import {CUSTOMER_USER_OPERATION_VERSION,prepareCustomerUserOperation,type CustomerUserOperationBody,type CustomerUserOperationKind} from '../src/services/customer-work/CustomerWorkUserOperationRequest';
import {AdminMobileUserService} from '../src/services/admin/AdminMobileUserService';
import * as Core from '../src/services/user/MobileUserManagementCore';
import * as Frontend from '../../view/uniapp-ts/src/utils/customerWorkUsersContract';
import type {CustomerWorkUserBody,CustomerWorkUserIntent} from '../../view/uniapp-ts/src/types/customerWorkUsers';

describe.skipIf(!process.env.TEST_FINANCE_POSTGRES_URL)('customer users complete mobile contract ordinary LOGIN native PG16',()=>{
 let f:Awaited<ReturnType<typeof customerWorkUserFixture>>;
 beforeAll(async()=>{f=await customerWorkUserFixture();},60000);
 afterAll(async()=>{vi.restoreAllMocks();await f?.close();},60000);
 beforeEach(async()=>{vi.restoreAllMocks();await f.reset();},30000);
 const context=(key=crypto.randomUUID(),uid=101)=>({actor:f.actor(uid),request_key:key});
 const state=async()=>({users:await f.db.select().from(user),groups:await f.db.select().from(userGroup),levelDefinitions:await f.db.select().from(systemUserLevel),levels:await f.db.select().from(userLevel),relations:await f.db.select().from(userLabelRelation),coupons:await f.db.select().from(storeCouponUser),issues:await f.db.select().from(storeCouponIssue),issueUsers:await f.db.select().from(storeCouponIssueUser),money:await f.db.select().from(userMoney),integral:await f.db.select().from(userBill),orders:await f.db.select().from(otherOrder),orderStatuses:await f.db.select().from(otherOrderStatus),logs:await f.db.select().from(systemLog),adminReplay:await f.db.select().from(adminUserWriteReplay)});
 async function body(db:DbClient,payload:unknown,uids=[201]):Promise<CustomerUserOperationBody>{const first=await f.reader(db).detail(f.actor(),uids[0]),targets=[];for(const uid of uids)targets.push({uid,expected_user_revision:uid===uids[0]?first.data.user.user_revision:(await readCustomerUserState(db,uid)).revision});return{version:CUSTOMER_USER_OPERATION_VERSION,scope_key:first.scope_key,targets,expected_catalog_revision:first.data.catalog_revision,payload:payload as CustomerUserOperationBody['payload']};}
 async function payload(db:DbClient,kind:CustomerUserOperationKind){return kind==='replace_level'?{level_id:31}:kind==='replace_group'?{group_id:11}:kind==='replace_labels'?{label_ids:[23]}:kind==='grant_coupons'?{issue_id:40,expected_issue_revision:await customerUserIssueRevision(db,40)}:kind==='adjust_membership'?{direction:'add',days:1}:kind==='adjust_money'?{direction:'add',amount:'0.01'}:{direction:'add',amount:3};}
 async function intent(kind:CustomerUserOperationKind,input:CustomerUserOperationBody,key:string):Promise<CustomerWorkUserIntent>{const wire=JSON.parse(JSON.stringify(input)) as CustomerWorkUserBody;return{version:'customer-work-user-pending-v1',actor_uid:101,service_id:1,scope_key:wire.scope_key,kind,request_key:key,request_hash:await Frontend.customerWorkUserIntentHash(101,kind,wire),body:wire,endpoint:Frontend.customerWorkUserEndpoint(kind,wire.targets.map(t=>t.uid)),method:'POST',created_at:Math.floor(Date.now()/1000)};}
 async function reachedOrFinished(reached:Promise<void>,pending:Promise<unknown>){let timer:ReturnType<typeof setTimeout>|undefined;try{await Promise.race([reached,pending.then(()=>{throw Error('Actual write completed before core-entry pause');}),new Promise<never>((_resolve,reject)=>{timer=setTimeout(()=>reject(Error('Actual core-entry pause was not reached')),7000);})]);}finally{if(timer)clearTimeout(timer);}}
 it('executes exact ordinary LOGIN and all seven read projections through actual frontend guards with complete global scopes',async()=>f.app(async(db,role,peer)=>{
  expect((await peer.exec('SELECT current_user AS role,session_user AS session'))[0]).toEqual({role,session:role});const list=await f.reader(db).list(f.actor());expect(list.data.readiness).toEqual({writes:true,reason:''});expect(list.data.list.map(u=>u.uid)).toContain(202);expect(list.data.list.map(u=>u.uid)).not.toContain(203);const detail=await f.reader(db).detail(f.actor(),201),groups=await f.reader(db).groups(f.actor()),levels=await f.reader(db).levels(f.actor()),labels=await f.reader(db).labels(f.actor(),{uid:'201'}),candidates=await f.reader(db).couponGrants(f.actor()),wallet=await f.reader(db).coupons(f.actor(),201);
  expect(detail.data.user).toMatchObject({uid:201,now_money:'12.34',integral:50,order_total_count:3,order_total_price:'12.91',coupon_num:1,birthday:'2000-01-01',real_name:'真实姓名',card_id:'真实证件',addres:'真实地址'});expect(groups.data.list.map(r=>r.id)).toEqual([11,10]);expect(levels.data.list.map(r=>r.id)).toEqual([30,31]);expect(labels.data.list[0].label.map(l=>l.id)).toEqual([20,23]);expect(candidates.data.list.map(r=>r.id)).toEqual([47,40]);expect(wallet.data.list.map(r=>r.id)).toEqual([2,1]);expect(wallet.data.list.map(r=>r.availability)).toEqual(['expired','future']);
  expect(Frontend.parseCustomerWorkUserEnvelope(list,101,Frontend.isCustomerWorkUserList,undefined,list.consistency_key)).toBe(list);expect(Frontend.parseCustomerWorkUserEnvelope(detail,101,Frontend.isCustomerWorkUserDetailData,undefined,list.consistency_key)).toBe(detail);expect(Frontend.parseCustomerWorkUserEnvelope(groups,101,Frontend.isCustomerWorkUserGroups,undefined,list.consistency_key)).toBe(groups);expect(Frontend.parseCustomerWorkUserEnvelope(levels,101,Frontend.isCustomerWorkUserLevels,undefined,list.consistency_key)).toBe(levels);expect(Frontend.parseCustomerWorkUserEnvelope(labels,101,Frontend.isCustomerWorkUserLabels,undefined,list.consistency_key)).toBe(labels);expect(Frontend.parseCustomerWorkUserEnvelope(candidates,101,Frontend.isCustomerWorkUserCouponCandidates,undefined,list.consistency_key)).toBe(candidates);expect(Frontend.parseCustomerWorkUserEnvelope(wallet,101,Frontend.isCustomerWorkUserCoupons,undefined,list.consistency_key)).toBe(wallet);expect(JSON.stringify(detail)).not.toMatch(/pwd|auth_version|rand_code|extendInfo|PRIVATE/);
 }),20000);
 it.each(['UTC','Asia/Shanghai'] as const)('compares genuine naive-UTC coupon windows consistently in ordinary LOGIN timezone %s through real frontend guards',async timezone=>{
  const now=Date.now();await f.db.insert(storeCouponIssue).values(f.issue(48,{startTime:new Date(now-100000),endTime:new Date(now+100000)}));
  await f.app(async(db,role,peer)=>{await peer.exec(`SELECT set_config('TimeZone','${timezone}',false)`);const[session]=await peer.exec('SELECT current_user AS role,session_user AS session,current_setting(\'TimeZone\') AS timezone');expect(session).toEqual({role,session:role,timezone});console.info('CUSTOMER_USER_TIMEZONE_LOGIN',JSON.stringify({...session,pid:peer.pid}));const detail=await f.reader(db).detail(f.actor(),201),candidates=await f.reader(db).couponGrants(f.actor()),wallet=await f.reader(db).coupons(f.actor(),201);expect(detail.data.user.coupon_num).toBe(1);expect(candidates.data.list.map(c=>c.id)).toEqual([48,47,40]);expect(candidates.data.list[0].action).toEqual({available:true,reason:''});expect(wallet.data.list.map(c=>c.availability)).toEqual(['expired','future']);expect(Frontend.isCustomerWorkUserDetailData(detail.data)).toBe(true);expect(Frontend.isCustomerWorkUserCouponCandidates(candidates.data)).toBe(true);expect(Frontend.isCustomerWorkUserCoupons(wallet.data)).toBe(true);});
 },20000);
 it('keeps literal wildcard/UID/phone search and six legacy filters with strict aliases, paging and query bounds',async()=>f.app(async db=>{expect((await f.reader(db).list(f.actor(),{nickname:'%_\\'})).data.list.map(u=>u.uid)).toEqual([201]);expect((await f.reader(db).list(f.actor(),{keyword:'201'})).data.list.map(u=>u.uid)).toEqual([201]);expect((await f.reader(db).list(f.actor(),{nickname:'456789',group_id:'0',level:'0'})).data.list.map(u=>u.uid)).toEqual([201]);expect((await f.reader(db).list(f.actor(),{label_id:'20'})).data.list.map(u=>u.uid)).toEqual([201]);expect((await f.reader(db).list(f.actor(),{isMember:'1'})).data.list.map(u=>u.uid)).toEqual([207,206,205]);const p=await f.reader(db).list(f.actor(),{limit:'2',page:'2'});expect(p.data.list.map(u=>u.uid)).toEqual([205,202]);await expect(f.reader(db).list(f.actor(),{nickname:'x',keyword:'x'})).rejects.toThrow('别名');await expect(f.reader(db).list(f.actor(),{label_id:'20',label_ids:'20'})).rejects.toThrow('别名');await expect(f.reader(db).list(f.actor(),{store_id:'77'})).rejects.toThrow('不支持');await expect(f.reader(db).list(f.actor(),{nickname:'😀'.repeat(101)})).rejects.toThrow();}),20000);
 it('keeps both deletion kinds readable with actions false and allows disabled targets to be managed without treating them as actors',async()=>f.app(async db=>{for(const uid of[203,204]){const detail=await f.reader(db).detail(f.actor(),uid);expect(detail.data.user.deleted).toBe(true);expect(Object.values(detail.data.user.actions).every(a=>!a.available)).toBe(true);expect(Frontend.isCustomerWorkUserDetailData(detail.data)).toBe(true);const before=await state(),result=await f.writer(db).execute('replace_group',context(),await body(db,{group_id:11},[uid]));expect(result.receipt.outcome).toBe('rollback-rejected');expect(await state()).toEqual(before);}const result=await f.writer(db).execute('replace_group',context(),await body(db,{group_id:11},[202]));expect(result.receipt.outcome).toBe('users-updated');expect((await state()).users.find(u=>u.uid===202)).toMatchObject({status:0,groupId:11});}),20000);
 it.each(CUSTOMER_USER_KINDS)('executes %s in the original ordinary LOGIN transaction and binds actual result to actual frontend receipt parser',async kind=>f.app(async db=>{const input=await body(db,await payload(db,kind)),ctx=context(),p=await prepareCustomerUserOperation(kind,ctx,input),front=await intent(kind,input,ctx.request_key);expect(p.hash).toBe(front.request_hash);const result=await f.writer(db).execute(kind,ctx,input);expect(result.receipt.service_id).toBe(1);expect(Frontend.parseCustomerWorkUserReceipt(result.receipt,front)).toEqual(result.receipt);expect(result.receipt.evidence.verified).toBe(true);expect((await state()).logs).toEqual([]);expect((await state()).adminReplay).toEqual([]);if(kind==='adjust_integral')expect((await state()).integral[0].eventKey).toBe('customer_work_add_integral');if(kind==='adjust_membership'){const s=await state();expect(s.orders[0]).toMatchObject({uid:201,type:4,payType:'admin',isFree:1,paid:1});expect(s.orderStatuses[0].changeType).toBe('customer_work_adjust');}}),20000);
 it.each(['replace_level','replace_group','replace_labels','adjust_money','adjust_integral'] as const)('returns valid zero-change %s receipt without fabricated positive financial records',async kind=>f.app(async db=>{const data=kind==='replace_level'?{level_id:30}:kind==='replace_group'?{group_id:10}:kind==='replace_labels'?{label_ids:[20]}:kind==='adjust_money'?{direction:'subtract',amount:'1.00'}:{direction:'subtract',amount:1};if(kind==='adjust_money')await f.db.update(user).set({nowMoney:'0.00'}).where(eq(user.uid,201));if(kind==='adjust_integral')await f.db.update(user).set({integral:0}).where(eq(user.uid,201));const input=await body(db,data),ctx=context(),result=await f.writer(db).execute(kind,ctx,input);expect(result.receipt.evidence.changed).toBe(0);expect(Frontend.parseCustomerWorkUserReceipt(result.receipt,await intent(kind,input,ctx.request_key))).toEqual(result.receipt);expect((await state()).money).toHaveLength(0);expect((await state()).integral).toHaveLength(0);}));
 it('clamps money and integral subtraction to actual balances, with exact cents and actual journals',async()=>f.app(async db=>{const money=await f.writer(db).execute('adjust_money',context(),await body(db,{direction:'subtract',amount:'9999999999.99'}));expect(money.receipt.evidence.changed).toBe(1);expect((await state()).money[0]).toMatchObject({number:'12.34',balance:'0.00',pm:0});const points=await f.writer(db).execute('adjust_integral',context(),await body(db,{direction:'subtract',amount:2147483647}));expect(points.receipt.evidence.changed).toBe(1);expect((await state()).integral[0]).toMatchObject({number:'50.00',balance:'0.00',pm:0});expect(JSON.stringify([money,points])).not.toMatch(/balance|amount|12.34|50.00/);}));
 it('rejects negative or overflowing finance deterministically and leaves all domain tables unchanged',async()=>f.app(async db=>{await f.db.update(user).set({nowMoney:'9999999999.99',integral:2147483647}).where(eq(user.uid,201));for(const kind of['adjust_money','adjust_integral'] as const){const input=await body(db,kind==='adjust_money'?{direction:'add',amount:'0.01'}:{direction:'add',amount:1}),before=await state(),result=await f.writer(db).execute(kind,context(),input);expect(result.receipt.outcome).toBe('rollback-rejected');expect(await state()).toEqual(before);}await f.db.update(user).set({nowMoney:'-0.01',integral:-1}).where(eq(user.uid,201));const detail=await f.reader(db).detail(f.actor(),201);expect(detail.data.user).toMatchObject({now_money:null,integral:null,financial_diagnostics:['money_invalid','integral_invalid']});expect(Frontend.isCustomerWorkUserDetailData(detail.data)).toBe(true);expect(detail.data.user.actions.adjust_money.available).toBe(false);expect(detail.data.user.actions.replace_group.available).toBe(true);}),20000);
 it('preserves permanent/expired membership rules and original paid-system trace in the same caller transaction',async()=>f.app(async db=>{expect((await f.reader(db).detail(f.actor(),205)).data.user).toMatchObject({membership_active:true,svip_over_day:null,actions:{adjust_membership:{available:false,reason:'permanent_membership'}}});const before=await state(),permanent=await f.writer(db).execute('adjust_membership',context(),await body(db,{direction:'add',days:1},[205]));expect(permanent.receipt.outcome).toBe('rollback-rejected');expect(await state()).toEqual(before);const now=Math.floor(Date.now()/1000),expired=await f.writer(db).execute('adjust_membership',context(),await body(db,{direction:'add',days:1},[206]));expect(expired.receipt.evidence.other_order_id).toBeGreaterThan(0);const row=(await state()).users.find(u=>u.uid===206)!;expect(row.overdueTime).toBeGreaterThanOrEqual(now+86400);expect(row.isMoneyLevel).toBe(2);expect((await f.writer(db).execute('adjust_membership',context(),await body(db,{direction:'add',days:999999},[207]))).receipt.outcome).toBe('rollback-rejected');}),20000);
 it('atomically grants exact target wallets, issue evidence and stock, ignoring manual-send receive limit and previous grants',async()=>f.app(async db=>{await f.db.update(storeCouponIssue).set({receiveLimit:1,remainCount:2}).where(eq(storeCouponIssue.id,40));const input=await body(db,{issue_id:40,expected_issue_revision:await customerUserIssueRevision(db,40)},[201,202]),ctx=context(),result=await f.writer(db).execute('grant_coupons',ctx,input);expect(result.receipt.evidence).toEqual({changed:2,issued_count:2,issue_id:40,verified:true});expect((await f.writer(db).execute('grant_coupons',ctx,input))).toEqual({...result,replayed:true});const s=await state();expect(s.coupons.filter(c=>c.receiveSource==='send'&&c.id>4).map(c=>c.uid)).toEqual([201,202]);expect(s.issueUsers.map(c=>c.uid)).toEqual([201,202]);expect(s.issues.find(i=>i.id===40)?.remainCount).toBe(0);}),20000);
 it('rejects insufficient-stock, wrong grant type, closed, deleted and expiry issues as a whole batch',async()=>f.app(async db=>{await f.db.update(storeCouponIssue).set({remainCount:1}).where(eq(storeCouponIssue.id,40));for(const id of[40,41,42,43,44,45,46]){const input=await body(db,{issue_id:id,expected_issue_revision:await customerUserIssueRevision(db,id)},[201,202]),before=await state(),result=await f.writer(db).execute('grant_coupons',context(),input);expect(result.receipt.outcome).toBe('rollback-rejected');expect(await state()).toEqual(before);}}),30000);
 it('binds coupon definition, stock and xmin ABA revisions and current time again at admission',async()=>f.app(async db=>{const issueRevision=await customerUserIssueRevision(db,40),input=await body(db,{issue_id:40,expected_issue_revision:issueRevision});await f.db.update(storeCouponIssue).set({remainCount:19}).where(eq(storeCouponIssue.id,40));await f.db.update(storeCouponIssue).set({remainCount:20}).where(eq(storeCouponIssue.id,40));expect(await customerUserIssueRevision(db,40)).not.toBe(issueRevision);const before=await state(),result=await f.writer(db).execute('grant_coupons',context(),input);expect(result.receipt).toMatchObject({outcome:'rollback-rejected',evidence:{code:'412'}});expect(await state()).toEqual(before);}));
 it('holds actual coupon inventory through caller commit against another ordinary LOGIN and rejects the old issue revision afterwards',async()=>f.app(async(db,role,caller)=>f.app(async(_other,peerRole,peer)=>{
  const input=await body(db,{issue_id:40,expected_issue_revision:await customerUserIssueRevision(db,40)}),original=Core.applyMobileUserCoupons;
  let signal!:()=>void,release!:()=>void,pending:Promise<unknown>|undefined,open=false;const reached=new Promise<void>(resolve=>{signal=resolve;}),barrier=new Promise<void>(resolve=>{release=resolve;});
  const spy=vi.spyOn(Core,'applyMobileUserCoupons').mockImplementation(async(...args)=>{signal();await barrier;return original(...args);});
  try{const write=f.writer(db).execute('grant_coupons',context(),input);pending=write;await reachedOrFinished(reached,write);expect(role).not.toBe(peerRole);expect(caller.pid).not.toBe(peer.pid);await peer.exec('BEGIN');open=true;await expect(peer.exec('SELECT id FROM store_coupon_issue WHERE id=40 FOR UPDATE NOWAIT')).rejects.toMatchObject({code:'55P03'});await peer.exec('ROLLBACK');open=false;release();expect((await write).receipt.evidence).toEqual({changed:1,issued_count:1,issue_id:40,verified:true});expect((await state()).issues.find(row=>row.id===40)?.remainCount).toBe(19);spy.mockRestore();const before=await state();expect((await f.writer(db).execute('grant_coupons',context(),input)).receipt).toMatchObject({outcome:'rollback-rejected',evidence:{code:'412'}});expect(await state()).toEqual(before);}finally{release();try{if(open)await peer.exec('ROLLBACK');}finally{await pending?.catch(()=>undefined);spy.mockRestore();}}
 })),30000);
 it('keeps malformed coupon monetary/window definitions diagnostic-only and excludes invalid axes without guessed fields',async()=>{const now=new Date();await f.db.insert(storeCouponIssue).values([f.issue(60,{couponPrice:'-0.01'}),f.issue(61,{startTime:new Date(now.getTime()-1000),endTime:null}),f.issue(62,{type:9}),f.issue(63,{couponType:9}),f.issue(64,{remainCount:-1,isPermanent:1})]);await f.db.insert(storeCouponUser).values([{uid:201,issueCouponId:60,couponTitle:'坏金额',type:1,couponPrice:'-0.01',status:0},{uid:201,issueCouponId:62,couponTitle:'坏轴',type:9,status:0}]);await f.app(async db=>{const candidates=await f.reader(db).couponGrants(f.actor()),wallet=await f.reader(db).coupons(f.actor(),201);expect(Frontend.isCustomerWorkUserCouponCandidates(candidates.data)).toBe(true);expect(candidates.data.list.find(i=>i.id===60)).toMatchObject({coupon_price:'-0.01',action:{available:false}});expect(candidates.data.list.find(i=>i.id===61)?.action.available).toBe(false);expect(candidates.data.list.some(i=>[62,63,64].includes(i.id))).toBe(false);expect(Frontend.isCustomerWorkUserCoupons(wallet.data)).toBe(true);expect(wallet.data.list.find(i=>i.coupon_price==='-0.01')?.availability).toBe('invalid');expect(wallet.data.list.some(i=>Number(i.type)===9)).toBe(false);});});
 it('replaces only platform labels, supports empty clear and rejects hidden/foreign/stopped catalog definitions',async()=>f.app(async db=>{const result=await f.writer(db).execute('replace_labels',context(),await body(db,{label_ids:[]}));expect(result.receipt.outcome).toBe('users-updated');expect((await state()).relations).toEqual([expect.objectContaining({uid:201,type:1,relationId:77,labelId:21})]);for(const id of[21,22,24]){const before=await state();expect((await f.writer(db).execute('replace_labels',context(),await body(db,{label_ids:[id]}))).receipt.outcome).toBe('rollback-rejected');expect(await state()).toEqual(before);}}),20000);
 it('preserves genuine pre-1970 birthday epochs and exact aggregate money beyond single-row decimal bounds',async()=>{await f.db.update(user).set({birthday:-315648000}).where(eq(user.uid,201));await f.db.insert(storeOrder).values([{id:100,uid:201,orderId:'REAL-LARGE-100',pid:0,paid:1,payPrice:'9999999999.99'},{id:101,uid:201,orderId:'REAL-LARGE-101',pid:0,paid:1,payPrice:'9999999999.99'}]);await f.app(async db=>{const detail=await f.reader(db).detail(f.actor(),201);expect(detail.data.user).toMatchObject({birthday:'1960-01-01',birthday_epoch:-315648000,order_total_price:'20000000012.89'});expect(Frontend.isCustomerWorkUserDetailData(detail.data)).toBe(true);});});
 it.each(CUSTOMER_USER_KINDS)('rejects a controlled actual %s result corruption after the original core executes and rolls everything back',async kind=>f.app(async db=>{
  const input=await body(db,await payload(db,kind)),before=await state();let spy:{mockRestore():void}|undefined,executed=false;
  const corrupt=async(tx:DbClient)=>{executed=true;if(kind==='replace_level')await tx.update(user).set({exp:'999.00'}).where(eq(user.uid,201));else if(kind==='replace_group')await tx.update(user).set({groupId:10}).where(eq(user.uid,201));else if(kind==='replace_labels')await tx.delete(userLabelRelation).where(eq(userLabelRelation.uid,201));else if(kind==='grant_coupons')await tx.update(storeCouponIssue).set({remainCount:999}).where(eq(storeCouponIssue.id,40));else if(kind==='adjust_membership')await tx.update(user).set({overdueTime:1}).where(eq(user.uid,201));else if(kind==='adjust_money')await tx.update(user).set({nowMoney:'99.00'}).where(eq(user.uid,201));else await tx.update(userBill).set({number:'99.00'});};
  if(kind.startsWith('replace_')){const original=Core.applyMobileUserState;spy=vi.spyOn(Core,'applyMobileUserState').mockImplementation(async(...args)=>{const result=await original(...args);await corrupt(args[0]);return result;});}else if(kind==='grant_coupons'){const original=Core.applyMobileUserCoupons;spy=vi.spyOn(Core,'applyMobileUserCoupons').mockImplementation(async(...args)=>{const result=await original(...args);await corrupt(args[0]);return result;});}else if(kind==='adjust_membership'){const original=Core.applyMobileUserMembership;spy=vi.spyOn(Core,'applyMobileUserMembership').mockImplementation(async(...args)=>{const result=await original(...args);await corrupt(args[0]);return result;});}else{const original=Core.applyMobileUserFinance;spy=vi.spyOn(Core,'applyMobileUserFinance').mockImplementation(async(...args)=>{const result=await original(...args);await corrupt(args[0]);return result;});}
  try{expect((await f.writer(db).execute(kind,context(),input)).receipt.outcome).toBe('rollback-rejected');expect(executed).toBe(true);expect(await state()).toEqual(before);if(kind==='replace_level'){expect((await f.writer(db).execute(kind,context(),await body(db,{level_id:30}))).receipt.outcome).toBe('rollback-rejected');expect(await state()).toEqual(before);}}finally{spy?.mockRestore();}
 }),20000);
 it('bounds writers at exactly 100 immutable targets while full catalog and stored label reads remain complete',async()=>{const uids=Array.from({length:101},(_,i)=>1000+i);await f.db.insert(user).values(uids.map(uid=>({uid,nickname:`完整名单${uid}`})));await f.db.insert(userLabel).values(Array.from({length:101},(_,i)=>({id:1000+i,labelCate:1,name:i===100?'😀'.repeat(255):`完整标签${i}`,color:i===100?'😀'.repeat(32):'',type:0,relationId:0,status:1})));await f.db.insert(userLabelRelation).values(Array.from({length:101},(_,i)=>({uid:201,labelId:1000+i,type:0,relationId:0})));await f.app(async db=>{const labels=await f.reader(db).labels(f.actor(),{uid:'201'}),detail=await f.reader(db).detail(f.actor(),201);expect(labels.data.list[0].label.length).toBe(103);expect(detail.data.user.labels.length).toBe(102);expect(Frontend.isCustomerWorkUserLabels(labels.data)).toBe(true);expect(Frontend.isCustomerWorkUserDetailData(detail.data)).toBe(true);const input=await body(db,{group_id:11},uids.slice(0,100));expect((await f.writer(db).execute('replace_group',context(),input)).receipt.user_ids).toHaveLength(100);const before=await state();await expect(f.writer(db).execute('replace_group',context(),await body(db,{group_id:11},uids))).rejects.toThrow();expect(await state()).toEqual(before);});},30000);
 it.each([102,103,104,105,106,107,110])('denies kefu/manager/verifier/courier/disabled/deleted/ordinary uid %s global user management',async uid=>f.app(async db=>{const input=await body(db,{group_id:11}),before=await state();await expect(f.reader(db).list(f.actor(uid))).rejects.toThrow();expect((await f.writer(db).execute('replace_group',context(undefined,uid),input)).receipt).toMatchObject({service_id:0,outcome:'rollback-rejected'});expect(await state()).toEqual(before);}));
 it('rejects duplicated actual customer identity rather than broadening global users',async()=>{await f.db.insert(storeService).values({id:100,uid:101,account:'duplicate-customer',customer:1,accountStatus:1});await f.app(async db=>{await expect(f.reader(db).list(f.actor())).rejects.toThrow('重复');});});
 it.each(['status','deleted','soft_deleted','password','expiry','missing'] as const)('rejects actual invalidated actor %s for read, write, outcome and abandonment',async reason=>f.app(async db=>{const input=await body(db,{group_id:11}),ctx=context(),saved=await f.writer(db).execute('replace_group',ctx,input),owner=reason==='expiry'?{...f.actor(),expires_at:1}:f.actor();if(reason==='status')await f.db.update(user).set({status:0}).where(eq(user.uid,101));if(reason==='deleted')await f.db.update(user).set({deleteTime:new Date()}).where(eq(user.uid,101));if(reason==='soft_deleted')await f.db.update(user).set({isDel:1}).where(eq(user.uid,101));if(reason==='password')await f.db.update(user).set({pwd:'changed'}).where(eq(user.uid,101));if(reason==='missing')await f.db.delete(user).where(eq(user.uid,101));const before=await state();await expect(f.reader(db).list(owner)).rejects.toThrow();await expect(f.writer(db).execute('replace_group',{...context(),actor:owner},input)).rejects.toThrow();await expect(f.writer(db).outcome(owner,saved.receipt.request_key)).rejects.toThrow();await expect(f.writer(db).abandon(owner,crypto.randomUUID(),{kind:'replace_group',input})).rejects.toThrow();expect(await state()).toEqual(before);}));
 it('keeps minimal same-owner receipts and abandonment after role revocation but rejects new admissions',async()=>f.app(async db=>{const input=await body(db,{group_id:11}),ctx=context(),saved=await f.writer(db).execute('replace_group',ctx,input);await f.db.update(storeService).set({customer:0}).where(eq(storeService.id,1));expect((await f.writer(db).outcome(f.actor(),ctx.request_key)).receipt).toEqual(saved.receipt);expect((await f.writer(db).outcome(f.actor(102),ctx.request_key)).receipt).toBeNull();expect((await f.writer(db).execute('replace_group',context(),input)).receipt.outcome).toBe('rollback-rejected');const key=crypto.randomUUID();expect((await f.writer(db).abandon(f.actor(),key,{kind:'replace_group',input})).receipt.outcome).toBe('abandoned');expect((await f.writer(db).execute('replace_group',context(key),input)).receipt.outcome).toBe('abandoned');expect(JSON.stringify(saved.receipt)).not.toMatch(/nickname|phone|now_money|pwd|address/);}));
 it('replays identical immutable intent once and refuses same UUID with changed kind or target',async()=>f.app(async db=>{const input=await body(db,{direction:'add',amount:'0.01'}),ctx=context(),first=await f.writer(db).execute('adjust_money',ctx,input);expect((await f.writer(db).execute('adjust_money',ctx,input))).toEqual({...first,replayed:true});expect((await state()).money).toHaveLength(1);await expect(f.writer(db).execute('adjust_money',ctx,{...input,payload:{direction:'add',amount:'0.02'}})).rejects.toThrow('不同');}));
 it('uses readonly RR snapshots and fresh actor authority to reject in-flight permission revocation without SELECT-only row locks',async()=>f.app(async db=>{let changed=false;const observed=observeIntegralReadDb(db,async(_tx,command)=>{if(!changed&&command.includes('from "user_group"')){changed=true;await f.db.update(storeService).set({customer:0}).where(eq(storeService.id,1));}}),reader=new CustomerWorkUserReadService(createContainerFromDb(observed),f.env);await expect(reader.groups(f.actor())).rejects.toThrow('权限');expect(changed).toBe(true);}));
 it('fences target and catalog ABA changes while excluding unrelated user revisions',async()=>f.app(async db=>{const input=await body(db,{group_id:11});await f.db.update(user).set({nowMoney:'12.35'}).where(eq(user.uid,201));await f.db.update(user).set({nowMoney:'12.34'}).where(eq(user.uid,201));const before=await state();expect((await f.writer(db).execute('replace_group',context(),input)).receipt).toMatchObject({outcome:'rollback-rejected',evidence:{code:'412'}});expect(await state()).toEqual(before);const fresh=await body(db,{group_id:11});await f.db.update(user).set({nickname:'无关用户变更'}).where(eq(user.uid,202));expect((await f.writer(db).execute('replace_group',context(),fresh)).receipt.outcome).toBe('users-updated');}));
 it.each(CUSTOMER_USER_KINDS)('rejects changed full hidden taxonomy fingerprint before %s mutation',async kind=>f.app(async db=>{const input=await body(db,await payload(db,kind));await f.db.update(legacyCategory).set({name:'隐藏组ABA'}).where(eq(legacyCategory.id,3));const before=await state(),result=await f.writer(db).execute(kind,context(),input);expect(result.receipt).toMatchObject({outcome:'rollback-rejected',evidence:{code:'412'}});expect(await state()).toEqual(before);}),20000);
 it.each(['replace_group','adjust_money'] as const)('holds actual actor account and target user locks through %s commit against a different ordinary LOGIN',async kind=>f.app(async(db,role,caller)=>f.app(async(_peerDb,peerRole,peer)=>{const input=await body(db,await payload(db,kind)),original=kind==='replace_group'?Core.applyMobileUserState:Core.applyMobileUserFinance;let signal!:()=>void,release!:()=>void,open=false,pending:Promise<unknown>|undefined;const reached=new Promise<void>(r=>{signal=r;}),wait=new Promise<void>(r=>{release=r;});const spy=kind==='replace_group'?vi.spyOn(Core,'applyMobileUserState').mockImplementation(async(...args)=>{signal();await wait;return (original as typeof Core.applyMobileUserState)(...args);}):vi.spyOn(Core,'applyMobileUserFinance').mockImplementation(async(...args)=>{signal();await wait;return (original as typeof Core.applyMobileUserFinance)(...args);});try{const write=f.writer(db).execute(kind,context(),input);pending=write;await reachedOrFinished(reached,write);expect(role).not.toBe(peerRole);expect(caller.pid).not.toBe(peer.pid);await peer.exec('BEGIN');open=true;await expect(peer.exec('SELECT uid FROM "user" WHERE uid=101 FOR UPDATE NOWAIT')).rejects.toMatchObject({code:'55P03'});await peer.exec('ROLLBACK');open=false;await peer.exec('BEGIN');open=true;await expect(peer.exec('SELECT uid FROM "user" WHERE uid=201 FOR UPDATE NOWAIT')).rejects.toMatchObject({code:'55P03'});await peer.exec('ROLLBACK');open=false;release();await write;await peer.exec('UPDATE "user" SET status=0 WHERE uid=101');await expect(f.reader(db).list(f.actor())).rejects.toThrow();}finally{release();try{if(open)await peer.exec('ROLLBACK');}finally{await pending?.catch(()=>undefined);spy.mockRestore();}}})),20000);
 it('rejects already-observed noncooperating label insertion before first core mutation and rolls back all writes',async()=>f.app(async db=>f.app(async(_other,_role,peer)=>{const input=await body(db,{direction:'add',amount:'0.01'}),original=Core.applyMobileUserFinance;let inserted=false;const spy=vi.spyOn(Core,'applyMobileUserFinance').mockImplementation(async(...args)=>{await peer.exec('INSERT INTO user_label_relation(uid,type,relation_id,label_id) VALUES(201,1,77,999)');inserted=true;return original(...args);});try{const result=await f.writer(db).execute('adjust_money',context(),input);expect(result.receipt).toMatchObject({outcome:'rollback-rejected',evidence:{code:'412'}});expect(inserted).toBe(true);const s=await state();expect(s.money).toEqual([]);expect(s.users.find(u=>u.uid===201)?.nowMoney).toBe('12.34');expect(s.relations.some(r=>r.labelId===999)).toBe(true);}finally{spy.mockRestore();}})),20000);
 it('executes only real UserJWT controllers for all eight legacy functions and rejects anonymous/AdminJWT/duplicate queries',async()=>f.app(async db=>{const h=f.http(db),token=await createToken(101,'api',f.actor().auth_version,f.env.APP_KEY),admin=await createToken(101,'admin',f.actor().auth_version,f.env.APP_KEY),authorization={'Authori-zation':`Bearer ${token.token}`};for(const path of['/users','/users/groups','/users/levels','/users/labels?uid=201','/users/coupon-grants','/users/201','/users/201/coupons']){const response=await h.request(path,{headers:authorization},f.env);expect(response.status,await response.clone().text()).toBe(200);expect(response.headers.get('Cache-Control')).toBe('private, no-store');}expect((await h.request('/users',{},f.env)).status).toBe(400);expect((await h.request('/users',{headers:{'Authori-zation':`Bearer ${admin.token}`}},f.env)).status).toBe(400);expect((await h.request('/users?page=1&page=2',{headers:authorization},f.env)).status).toBe(400);for(const kind of CUSTOMER_USER_KINDS){const input=await body(db,await payload(db,kind)),response=await h.request('/users/'+kind.replaceAll('_','-'),{method:'POST',headers:{...authorization,'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify(input)},f.env);expect(response.status,await response.clone().text()).toBe(200);} }),30000);
});

describe.skipIf(!process.env.TEST_FINANCE_POSTGRES_URL)('mature Admin user caller-transaction regression',()=>{
 let f:Awaited<ReturnType<typeof customerWorkUserFixture>>;
 beforeAll(async()=>{f=await customerWorkUserFixture();},60000);afterAll(async()=>{await f?.close();},60000);beforeEach(async()=>{await f.reset();},30000);
 const actor={id:900,name:'真实管理员',ip:'127.0.0.1'};
 it.each([1,2,3,4,5] as const)('keeps mature Admin public type %s audit and original behavior through shared actual core',async type=>{const service=new AdminMobileUserService(createContainerFromDb(f.db)),value=type===1?{type,uid:201,level:31}:type===2?{type,uid:201,days_status:1,days:1}:type===3?{type,uid:[201,202],coupon_id:40}:type===4?{type,uid:[201,202],group_id:11}:{type,uid:[201,202],label_id:[]};await service.update(actor,value,crypto.randomUUID());expect((await f.db.select().from(systemLog))[0].adminId).toBe(900);expect((await f.exec('SELECT * FROM customer_user_operation_request'))).toHaveLength(0);if(type===2){expect((await f.db.select().from(otherOrderStatus))[0].changeType).toBe('admin_adjust');expect((await f.db.select().from(adminUserWriteReplay))[0].adminId).toBe(900);}if(type===3)expect((await f.db.select().from(storeCouponIssueUser))).toHaveLength(2);});
 it.each([1,2] as const)('keeps mature Admin finance type %s original journals, actor replay and exact same-key atomicity',async type=>{const service=new AdminMobileUserService(createContainerFromDb(f.db)),key=crypto.randomUUID(),input={type,status:2,number:type===1?'999999.99':9999};await service.adjustFinance(actor,201,input,key);await service.adjustFinance(actor,201,input,key);const replay=await f.db.select().from(adminUserWriteReplay);expect(replay).toHaveLength(1);expect(replay[0].adminId).toBe(900);if(type===2)expect((await f.db.select().from(userBill))[0]).toMatchObject({eventKey:'admin_system_sub_integral',number:'50.00',balance:'0.00'});else expect((await f.db.select().from(userMoney))[0]).toMatchObject({number:'12.34',balance:'0.00'});});
});
