import { afterAll,beforeAll,beforeEach,describe,expect,it,vi } from 'vitest';
import { eq } from 'drizzle-orm';
import { Hono } from 'hono';
import { createContainerFromDb } from '../src/lib/di';
import type { AppVariables,Env,OrderWaybillJobMessage } from '../src/env';
import { authMiddleware } from '../src/middleware/auth';
import { createToken } from '../src/utils/jwt';
import { lockOrderSettlement } from '../src/services/order/OrderBrokerageService';
import { SupplierFulfillmentService } from '../src/services/supplier/SupplierFulfillmentService';
import * as Controller from '../src/controllers/api/v1/CustomerWorkFulfillmentController';
import { customerWorkFulfillmentFixture } from './helpers/customerWorkFulfillmentFixture';
import { CustomerWorkOperationRequest,prepareCustomerOperation,type CustomerOperationInput,type CustomerOperationContext } from '../src/services/customer-work/CustomerWorkOperationRequest';
import { CustomerWorkFulfillmentService,parseCustomerDelivery } from '../src/services/customer-work/CustomerWorkFulfillmentService';
import { OrderWaybillJobService } from '../src/services/waybill/OrderWaybillJobService';
import { storeOrder,storeOrderCartInfo,storeOrderStatus,storeOrderOutbox,storeOrderRefund,storeService,expressCompany,systemConfig,user,orderWaybillJob,orderWaybillJobAction,storePink } from '../src/models/schema';
import * as Frontend from '../../view/uniapp-ts/src/utils/customerWorkFulfillmentContract';
import { parseCustomerWorkEnvelope } from '../../view/uniapp-ts/src/utils/customerWork';

const manual={type:1,express_record_type:1,carrier_id:1,delivery_id:'LOCAL-OWNED-001'};
const electronic={type:1,express_record_type:2,carrier_id:1,express_temp_id:'owned-template',to_name:'实际发件人',to_tel:'13900000999',to_addr:'实际发件地址'};
describe.skipIf(!process.env.TEST_FINANCE_POSTGRES_URL)('customer complete fulfillment ordinary LOGIN real SQL contract',()=>{
 let f:Awaited<ReturnType<typeof customerWorkFulfillmentFixture>>;
 const ctx=(key=crypto.randomUUID(),uid=101):CustomerOperationContext=>({actor:f.actor(uid),request_key:key});
 beforeAll(async()=>{f=await customerWorkFulfillmentFixture();},60000);
 afterAll(async()=>{vi.unstubAllGlobals();await f?.close();},60000);
 beforeEach(async()=>{vi.unstubAllGlobals();await f.reset();vi.stubGlobal('fetch',vi.fn().mockRejectedValue(Error('Unexpected external transport')));},30000);
 const current=async(id=1)=>(await f.db.select().from(storeOrder).where(eq(storeOrder.id,id)))[0];
 const business=async(id=1)=>(await current(id)).orderId;
 const state=async()=>({orders:await f.db.select().from(storeOrder).orderBy(storeOrder.id),carts:await f.db.select().from(storeOrderCartInfo).orderBy(storeOrderCartInfo.id),audits:await f.db.select().from(storeOrderStatus),outbox:await f.db.select().from(storeOrderOutbox),jobs:await f.db.select().from(orderWaybillJob),actions:await f.db.select().from(orderWaybillJobAction)});
 async function intent(db:Parameters<typeof createContainerFromDb>[0],payload:unknown,id=1,remark=false):Promise<CustomerOperationInput>{const service=f.service(db);if(remark){const result=await service.remarkTarget(f.actor(),await business(id),{}),t=result.data.remark_target;return{version:'customer-work-operation-v1',scope_key:result.scope_key,order_id:t.id,expected_order_revision:t.order_revision,expected_fulfillment_revision:t.fulfillment_revision,payload:payload as CustomerOperationInput['payload']};}const result=await service.bootstrap(f.actor(),await business(id),{}),o=result.data.order;return{version:'customer-work-operation-v1',scope_key:result.scope_key,order_id:o.id,expected_order_revision:o.order_revision,expected_fulfillment_revision:o.fulfillment_revision,payload:payload as CustomerOperationInput['payload']};}
 const jobService=(db:Parameters<typeof createContainerFromDb>[0])=>new OrderWaybillJobService(createContainerFromDb(db),f.env);
 async function queueProcess(db:Parameters<typeof createContainerFromDb>[0],jobId:number,fetcher:typeof fetch){const row=(await f.db.select().from(orderWaybillJob).where(eq(orderWaybillJob.id,jobId)))[0];return jobService(db).processMessage({action:'processOrderWaybillJob',waybillJobId:row.id,eventKey:row.eventKey} as OrderWaybillJobMessage,fetcher);}
 function provider(onIssue?:()=>Promise<void>,unknown=false){let issues=0;const fetcher=vi.fn(async(input:Parameters<typeof fetch>[0],init?:RequestInit)=>{const url=String(input);if(url.endsWith('/v2/user/login'))return Response.json({status:200,data:{access_token:'owned-token',expires_in:3600}});if(url.endsWith('/v2/expr/dump')){issues++;expect(init?.method).toBe('POST');await onIssue?.();if(unknown)throw Error('owned provider connection lost after invocation');return Response.json({status:200,data:{kuaidinum:'OWNED-WAYBILL-001',label:'https://example.test/owned-label.png',task_id:'owned-provider-ref'}});}throw Error(`Unowned provider endpoint ${url}`);});return{fetcher:fetcher as unknown as typeof fetch,issues:()=>issues};}
 async function admit(db:Parameters<typeof createContainerFromDb>[0],split=false){const input=await intent(db,split?{...electronic,cart_ids:[{cart_id:'cart-1',cart_num:1}]}:electronic),context=ctx(),prepared=await prepareCustomerOperation(split?'electronic_split_waybill':'electronic_waybill',context,input),o=await current(input.order_id),pending={version:'customer-work-pending-v1' as const,request_key:context.request_key,request_hash:prepared.hash,actor_uid:101,service_id:1,scope_key:input.scope_key,order_no:o.orderId,root_order_id:o.pid>0?o.pid:o.id,kind:prepared.kind,body:input,created_at:Date.now()} as Parameters<typeof Frontend.parseCustomerWorkReceipt>[1],result=await f.service(db).delivery(context,input,split);expect(result.receipt.outcome).toBe('provider-admitted');expect(result.receipt.evidence.waybill_job_id).toEqual(expect.any(Number));expect(Frontend.parseCustomerWorkReceipt(result,pending)).toEqual(result.receipt);return{input,context,result,id:Number(result.receipt.evidence.waybill_job_id)};}
 async function decision(db:Parameters<typeof createContainerFromDb>[0],jobId:number,action:string,extra:Record<string,unknown>={}){const detail=await f.service(db).waybillJob(f.actor(),jobId,{}),o=detail.data.operation;const input={version:'customer-work-operation-v1' as const,scope_key:detail.scope_key,order_id:o.order_id,expected_order_revision:o.order_revision,expected_fulfillment_revision:o.fulfillment_revision,payload:{action,job_id:jobId,expected_job_revision:detail.data.job.job_revision,reason:'Owned operator verified provider outcome',...extra}};return{input,context:ctx()};}

 it('uses fixed non-forging ordinary LOGIN and actual bootstrap auxiliary DTOs through the real frontend guards',async()=>{await f.app(async(db,_role,peer)=>{const service=f.service(db),b=await service.bootstrap(f.actor(),'customer-order-1',{});expect(b.data.actions.manual_delivery.available).toBe(true);expect(b.data.actions.electronic_waybill.available).toBe(true);expect(b.data.actions.city_delivery.available).toBe(false);expect(parseCustomerWorkEnvelope(b,101,Frontend.isCustomerWorkFulfillment).data.order.id).toBe(1);expect(Frontend.isCustomerWorkCarriers((await service.carriers(f.actor(),{})).data)).toBe(true);expect(Frontend.isCustomerWorkCouriers((await service.couriers(f.actor(),{})).data)).toBe(true);expect(Frontend.isCustomerWorkDefaults((await service.defaults(f.actor(),{})).data.defaults)).toBe(true);expect(Frontend.isCustomerWorkRemark((await service.remarkTarget(f.actor(),'customer-order-1',{})).data)).toBe(true);await expect(peer.exec('UPDATE store_service SET customer=1')).rejects.toThrow();await expect(peer.exec('UPDATE express_company SET status=1')).rejects.toThrow();await expect(peer.exec('UPDATE delivery_service SET status=1')).rejects.toThrow();await expect(peer.exec('UPDATE customer_work_operation_request SET service_id=9')).rejects.toThrow();});});
 it('matches actual portable frontend canonical hash while freezing both actor and original intent',async()=>{await f.app(async db=>{const input=await intent(db,manual),context=ctx(),prepared=await prepareCustomerOperation('manual_delivery',context,input);expect(prepared.hash).toBe(Frontend.customerWorkIntentHash(101,'manual_delivery',input as unknown as Record<string,unknown>));(input as {payload:unknown}).payload={remark:'mutated'};context.actor.uid=109;expect(prepared.actor.uid).toBe(101);expect(prepared.input.payload).toEqual(manual);});});
 it('serializes same UUID concurrent requests into one actual remark and append-only owned receipt',async()=>{await f.app(async db=>{const input=await intent(db,{remark:'实际备注'},1,true),context=ctx();const [first,other]=await f.app(async peer=>Promise.all([f.service(db).saveRemark(context,input),f.service(peer).saveRemark(context,input)]));expect([first.replayed,other.replayed].sort()).toEqual([false,true]);expect(first.receipt).toEqual(other.receipt);expect((await state()).audits).toHaveLength(1);expect(JSON.stringify(first.receipt)).not.toMatch(/实际备注|实际收件人|13900000201|实际收件地址|owned-customer-password/);await expect(f.service(db).saveRemark(context,{...input,payload:{remark:'另一备注'}})).rejects.toThrow('不同');});});
 it('keeps original payment header remark with no pending children and without pretending it is shippable',async()=>{await f.db.update(storeOrder).set({pid:-1,paid:0,status:-2}).where(eq(storeOrder.id,1));await f.db.delete(storeOrderCartInfo);await f.app(async db=>{await expect(f.service(db).bootstrap(f.actor(),'customer-order-1',{})).rejects.toThrow('没有待履约');const input=await intent(db,{remark:'父单原实体备注'},1,true),result=await f.service(db).saveRemark(ctx(),input);expect(result.receipt).toMatchObject({order_id:1,outcome:'remark-saved'});expect(await current()).toMatchObject({remark:'父单原实体备注',pid:-1,paid:0,status:-2});expect((await state()).audits[0].oid).toBe(1);expect((await state()).outbox).toHaveLength(0);});});
 it('keeps original header remark when several real pending store and supplier children prevent ambiguous shipping',async()=>{await f.db.update(storeOrder).set({pid:-1,supplierAllocationStatus:2}).where(eq(storeOrder.id,1));await f.db.insert(storeOrder).values([f.order(2,{pid:1,storeId:77}),f.order(3,{pid:1,supplierId:88})]);await f.app(async db=>{await expect(f.service(db).bootstrap(f.actor(),'customer-order-1',{})).rejects.toThrow('多个');expect((await f.service(db).saveRemark(ctx(),await intent(db,{remark:'只更新原根单'},1,true))).receipt.outcome).toBe('remark-saved');expect((await current(2)).remark).toBe('');expect((await current(3)).remark).toBe('');});});
 it.each([{storeId:0,supplierId:0},{storeId:77,supplierId:0},{storeId:0,supplierId:88}])('ships whole physical actual scope $storeId/$supplierId without fake admin or manager authority',async values=>{await f.db.update(storeOrder).set(values).where(eq(storeOrder.id,1));await f.app(async db=>{const result=await f.service(db).delivery(ctx(),await intent(db,manual));expect(result.receipt).toMatchObject({actor_uid:101,service_id:1,outcome:'delivery-recorded'});expect(await current()).toMatchObject({...values,status:1,deliveryType:'express',deliveryName:'实际快递',deliveryCode:'LOCAL',deliveryId:'LOCAL-OWNED-001'});expect((await state()).outbox).toHaveLength(1);expect((await state()).audits.some(a=>a.changeType==='customer_work_delivery')).toBe(true);});});
 it('derives and revalidates a unique pending allocated physical child with its real nonzero store and supplier',async()=>{await f.db.update(storeOrder).set({pid:-1,supplierAllocationStatus:2}).where(eq(storeOrder.id,1));await f.db.insert(storeOrder).values(f.order(2,{pid:1,storeId:77,supplierId:88}));await f.db.update(storeOrderCartInfo).set({oid:2}).where(eq(storeOrderCartInfo.id,1));await f.app(async db=>{const input=await intent(db,manual);expect(input.order_id).toBe(2);const result=await f.service(db).delivery(ctx(),input);expect(result.receipt.outcome).toBe('delivery-recorded');expect(await current(2)).toMatchObject({status:1,storeId:77,supplierId:88});expect((await current(1)).pid).toBe(-1);});});
 it('uses real Supplier split financial allocation with conserved money and cart fulfillment surplus',async()=>{await f.app(async db=>{const result=await f.service(db).delivery(ctx(),await intent(db,{...manual,cart_ids:[{cart_id:'cart-1',cart_num:1}]}),true);expect(result.receipt.outcome).toBe('delivery-recorded');const s=await state(),physical=s.orders.filter(o=>o.pid===1);expect(physical).toHaveLength(2);expect(physical.map(o=>o.payPrice).sort()).toEqual(['10.00','20.00']);expect(physical.filter(o=>o.status===1)).toHaveLength(1);expect(s.orders.find(o=>o.id===1)?.pid).toBe(-1);expect(s.carts.filter(c=>physical.some(o=>o.id===c.oid)).reduce((n,c)=>n+c.cartNum,0)).toBe(3);expect(s.outbox).toHaveLength(1);});});
 it('uses platform courier actual registered name and phone and rejects forged fields',async()=>{await f.app(async db=>{const result=await f.service(db).delivery(ctx(),await intent(db,{type:2,delivery_type:1,delivery_uid:105}));expect(result.receipt.outcome).toBe('delivery-recorded');expect(await current()).toMatchObject({deliveryType:'send',deliveryUid:105,deliveryName:'实际平台配送员',deliveryId:'13900000105'});expect(()=>parseCustomerDelivery({type:2,delivery_type:1,delivery_uid:105,delivery_name:'伪造配送员'},false)).toThrow();});});
 it('records actual manual virtual delivery only for whole virtual goods and never issues a provider label',async()=>{await f.db.update(storeOrder).set({productType:3}).where(eq(storeOrder.id,1));await f.app(async db=>{expect((await f.service(db).delivery(ctx(),await intent(db,{type:3,fictitious_content:'真实虚拟交付内容'}))).receipt.outcome).toBe('delivery-recorded');expect(await current()).toMatchObject({status:1,deliveryType:'fictitious',fictitiousContent:'真实虚拟交付内容'});expect(f.messages).toHaveLength(0);});});
 it('rejects manager chat verifier courier ordinary users as global customer write authorities',async()=>{await f.app(async db=>{const input=await intent(db,manual);for(const uid of[102,103,104,105,108])expect((await f.service(db).delivery(ctx(undefined,uid),input)).receipt.outcome).toBe('rollback-rejected');expect((await current()).status).toBe(0);expect((await state()).outbox).toHaveLength(0);});});
 it('preserves owner minimal receipts after role revoke but denies new writes and all account invalidations',async()=>{await f.app(async db=>{const input=await intent(db,{remark:'真实备注'},1,true),context=ctx(),first=await f.service(db).saveRemark(context,input);await f.db.update(storeService).set({customer:0}).where(eq(storeService.id,1));expect(await f.ledger(db).getOutcome(f.actor(),context.request_key)).toEqual(first.receipt);expect((await f.service(db).saveRemark(ctx(),input)).receipt.outcome).toBe('rollback-rejected');expect(await f.ledger(db).getOutcome(f.actor(102),context.request_key)).toBeNull();for(const patch of[{pwd:'changed-password'},{status:0},{isDel:1},{deleteTime:new Date()}]){await f.db.update(user).set({pwd:'owned-customer-password',status:1,isDel:0,deleteTime:null,...patch}).where(eq(user.uid,101));await expect(f.ledger(db).getOutcome(f.actor(),context.request_key)).rejects.toThrow('会话');}});});
 it('holds the real actor account through manual commit before a concurrent account revocation can commit',async()=>{
  await f.app(async(db,writerRole,writerPeer)=>f.app(async(_revokerDb,revokerRole,revokerPeer)=>{
   const input=await intent(db,manual),context=ctx(),original=SupplierFulfillmentService.prototype.deliver;
   let reachedResolve!:()=>void,releaseResolve!:()=>void,peerOpen=false;
   const reached=new Promise<void>(resolve=>{reachedResolve=resolve;}),release=new Promise<void>(resolve=>{releaseResolve=resolve;});
   let pending:Promise<{result:Awaited<ReturnType<CustomerWorkFulfillmentService['delivery']>>|null;error:unknown}>|undefined;
   let deadline:ReturnType<typeof setTimeout>|undefined;
   const spy=vi.spyOn(SupplierFulfillmentService.prototype,'deliver').mockImplementation(async function(this:SupplierFulfillmentService,...args:Parameters<typeof original>){reachedResolve();await release;return original.apply(this,args);});
   try{
    const writerIdentity=(await writerPeer.exec('SELECT current_user AS role,session_user AS session,pg_backend_pid() AS pid'))[0],revokerIdentity=(await revokerPeer.exec('SELECT current_user AS role,session_user AS session,pg_backend_pid() AS pid'))[0];
    expect(writerIdentity).toMatchObject({role:writerRole,session:writerRole});expect(revokerIdentity).toMatchObject({role:revokerRole,session:revokerRole});expect(writerIdentity.pid).not.toBe(revokerIdentity.pid);
    pending=f.service(db).delivery(context,input).then(result=>({result,error:null}),error=>({result:null,error}));
    await Promise.race([reached,pending.then(()=>{throw Error('Actual manual write completed before the core-entry pause');}),new Promise<never>((_resolve,reject)=>{deadline=setTimeout(()=>reject(Error('Actual manual core-entry pause was not reached')),7000);})]);
    if(deadline)clearTimeout(deadline);
    let revokedBeforeWriteCommit=false,lockError:unknown=null;
    try{
     await revokerPeer.exec('BEGIN');peerOpen=true;
     await revokerPeer.exec('SELECT uid FROM public."user" WHERE uid=101 FOR UPDATE NOWAIT');
     await revokerPeer.exec('UPDATE public."user" SET status=0 WHERE uid=101');
     await revokerPeer.exec('COMMIT');peerOpen=false;revokedBeforeWriteCommit=true;
    }catch(error){lockError=error;if(peerOpen){await revokerPeer.exec('ROLLBACK');peerOpen=false;}}
    releaseResolve();const completed=await pending,order=await current(),actor=(await f.db.select().from(user).where(eq(user.uid,101)))[0];
    console.info('CUSTOMER_ACCOUNT_REVOCATION_RACE '+JSON.stringify({writer:writerIdentity,revoker:revokerIdentity,revokedBeforeWriteCommit,lockCode:(lockError as {code?:string}|null)?.code??null,writeOutcome:completed.result?.receipt.outcome??null,writeError:completed.error instanceof Error?completed.error.message:null,orderStatus:order.status,actorStatus:actor.status}));
    expect(completed.error).toBeNull();expect(completed.result?.receipt.outcome).toBe('delivery-recorded');expect(order.status).toBe(1);
    expect(revokedBeforeWriteCommit).toBe(false);expect(lockError).toMatchObject({code:'55P03'});expect(actor.status).toBe(1);
    await revokerPeer.exec('BEGIN');peerOpen=true;
    await revokerPeer.exec('SELECT uid FROM public."user" WHERE uid=101 FOR UPDATE NOWAIT');
    await revokerPeer.exec('UPDATE public."user" SET status=0 WHERE uid=101');
    await revokerPeer.exec('COMMIT');peerOpen=false;
    expect((await f.db.select().from(user).where(eq(user.uid,101)))[0].status).toBe(0);
    await expect(f.service(db).delivery(ctx(),input)).rejects.toThrow('会话');
    expect((await current()).status).toBe(1);expect((await state()).outbox).toHaveLength(1);
   }finally{
    if(deadline)clearTimeout(deadline);releaseResolve();
    try{if(peerOpen)await revokerPeer.exec('ROLLBACK');}
    finally{try{if(pending)await pending;}finally{try{spy.mockRestore();}finally{await f.db.update(user).set({status:1}).where(eq(user.uid,101));}}}
   }
  }));
 },30000);
 it('uses the same real account lock for remark and releases it only after the original entity commit',async()=>{
  await f.app(async(db,_writerRole,writerPeer)=>f.app(async(_revokerDb,_revokerRole,revokerPeer)=>{
   const input=await intent(db,{remark:'账户锁真实原实体备注'},1,true),original=CustomerWorkOperationRequest.prototype.execute;
   let reachedResolve!:()=>void,releaseResolve!:()=>void,peerOpen=false;
   const reached=new Promise<void>(resolve=>{reachedResolve=resolve;}),release=new Promise<void>(resolve=>{releaseResolve=resolve;});
   let pending:Promise<{result:Awaited<ReturnType<CustomerWorkFulfillmentService['saveRemark']>>|null;error:unknown}>|undefined,deadline:ReturnType<typeof setTimeout>|undefined;
   const spy=vi.spyOn(CustomerWorkOperationRequest.prototype,'execute').mockImplementation(function(this:CustomerWorkOperationRequest,kind,context,value,callback,fence){return original.call(this,kind,context,value,async(...args)=>{if(kind==='remark'){reachedResolve();await release;}return callback(...args);},fence);});
   try{
    pending=f.service(db).saveRemark(ctx(),input).then(result=>({result,error:null}),error=>({result:null,error}));
    await Promise.race([reached,pending.then(()=>{throw Error('Actual remark completed before the authorized callback pause');}),new Promise<never>((_resolve,reject)=>{deadline=setTimeout(()=>reject(Error('Actual authorized remark callback pause was not reached')),7000);})]);
    if(deadline)clearTimeout(deadline);
    let revokedBeforeWriteCommit=false,lockError:unknown=null;
    try{await revokerPeer.exec('BEGIN');peerOpen=true;await revokerPeer.exec('SELECT uid FROM public."user" WHERE uid=101 FOR UPDATE NOWAIT');await revokerPeer.exec('UPDATE public."user" SET status=0 WHERE uid=101');await revokerPeer.exec('COMMIT');peerOpen=false;revokedBeforeWriteCommit=true;}catch(error){lockError=error;if(peerOpen){await revokerPeer.exec('ROLLBACK');peerOpen=false;}}
    releaseResolve();const completed=await pending;
    console.info('CUSTOMER_REMARK_ACCOUNT_LOCK '+JSON.stringify({writerPid:writerPeer.pid,revokerPid:revokerPeer.pid,revokedBeforeWriteCommit,lockCode:(lockError as {code?:string}|null)?.code??null,outcome:completed.result?.receipt.outcome??null}));
    expect(completed.error).toBeNull();expect(completed.result?.receipt.outcome).toBe('remark-saved');expect((await current()).remark).toBe('账户锁真实原实体备注');expect(revokedBeforeWriteCommit).toBe(false);expect(lockError).toMatchObject({code:'55P03'});
    await revokerPeer.exec('BEGIN');peerOpen=true;await revokerPeer.exec('SELECT uid FROM public."user" WHERE uid=101 FOR UPDATE NOWAIT');await revokerPeer.exec('UPDATE public."user" SET status=0 WHERE uid=101');await revokerPeer.exec('COMMIT');peerOpen=false;
    await expect(f.service(db).saveRemark(ctx(),input)).rejects.toThrow('会话');expect((await state()).audits).toHaveLength(1);expect((await state()).outbox).toHaveLength(0);
   }finally{if(deadline)clearTimeout(deadline);releaseResolve();try{if(peerOpen)await revokerPeer.exec('ROLLBACK');}finally{try{if(pending)await pending;}finally{try{spy.mockRestore();}finally{await f.db.update(user).set({status:1}).where(eq(user.uid,101));}}}}
  }));
 },30000);
 it('rejects real disabled missing deleted password-changed and expired actor accounts for both fresh manual and remark writes',async()=>{
  await f.app(async db=>{
   const shipping=await intent(db,manual),remark=await intent(db,{remark:'失效账户不得更新'},1,true),baseline=await state(),originalActor=(await f.db.select().from(user).where(eq(user.uid,101)))[0];
   for(const invalid of['disabled','password','softdeleted','deleted-time','missing','expired']){
    const context=ctx();
    try{
     if(invalid==='missing')await f.db.delete(user).where(eq(user.uid,101));
     else if(invalid==='expired')context.actor.expires_at=Math.floor(Date.now()/1000)-1;
     else await f.db.update(user).set(invalid==='disabled'?{status:0}:invalid==='password'?{pwd:'actually-changed-password'}:invalid==='softdeleted'?{isDel:1}:{deleteTime:new Date()}).where(eq(user.uid,101));
     await expect(f.service(db).delivery(context,shipping)).rejects.toThrow('会话');
     await expect(f.service(db).saveRemark({...context,request_key:crypto.randomUUID()},remark)).rejects.toThrow('会话');
     expect(await state()).toEqual(baseline);expect(Number((await f.exec('SELECT count(*) AS count FROM customer_work_operation_request'))[0].count)).toBe(0);
    }finally{if(invalid==='missing')await f.db.insert(user).values(originalActor);else await f.db.update(user).set({pwd:originalActor.pwd,status:originalActor.status,isDel:originalActor.isDel,deleteTime:originalActor.deleteTime}).where(eq(user.uid,101));}
   }
  });
 },30000);
 it('leaves absence unknown until explicit same UUID abandon and then cannot perform the abandoned operation',async()=>{await f.app(async db=>{const input=await intent(db,manual),context=ctx(),before=await state();expect(await f.ledger(db).getOutcome(f.actor(),context.request_key)).toBeNull();const receipt=await f.ledger(db).abandon('manual_delivery',context,input);expect(receipt).toMatchObject({outcome:'abandoned',service_id:0});expect(await f.service(db).delivery(context,input)).toMatchObject({replayed:true,receipt});expect(await state()).toEqual(before);});});
  it('joins the actual financial root settlement lock and keeps SQL timeout outcome unknown rather than appending false rollback',async()=>{await f.app(async db=>{const input=await intent(db,manual),context=ctx();await f.withPeer!(async peer=>{await peer.exec('BEGIN');try{await lockOrderSettlement(peer.db,1);await expect(f.service(db).delivery(context,input)).rejects.toMatchObject({cause:{code:'55P03'}});expect(await f.ledger(db).getOutcome(f.actor(),context.request_key)).toBeNull();expect((await current()).status).toBe(0);}finally{await peer.exec('ROLLBACK');}});expect((await f.service(db).delivery(context,input)).receipt.outcome).toBe('delivery-recorded');});},15000);
 it.each(['cart','carrier','defaults','deleted'])('rejects stale reviewed $0 resource and persists only rollback after no mutation',async key=>{await f.app(async db=>{const input=await intent(db,manual);if(key==='cart')await f.db.update(storeOrderCartInfo).set({splitSurplusNum:2}).where(eq(storeOrderCartInfo.id,1));if(key==='carrier')await f.db.update(expressCompany).set({status:0}).where(eq(expressCompany.id,1));if(key==='defaults')await f.db.update(systemConfig).set({value:'new sender'}).where(eq(systemConfig.id,4));if(key==='deleted')await f.db.update(storeOrder).set({isDel:1}).where(eq(storeOrder.id,1));const result=await f.service(db).delivery(ctx(),input);expect(result.receipt.outcome).toBe('rollback-rejected');expect((await current()).status).toBe(0);expect((await state()).outbox).toHaveLength(0);});});
 it('denies fresh shipping while an active actual generation refund exists',async()=>{await f.db.insert(storeOrderRefund).values({id:1,storeOrderId:1,orderId:'actual-refund-1',uid:201,refundType:0,refundNum:1,refundPrice:'10.00',cartInfo:JSON.stringify([{cart_id:'cart-1',cart_num:1}])});await f.app(async db=>{const b=await f.service(db).bootstrap(f.actor(),'customer-order-1',{});expect(b.data.actions.manual_delivery.available).toBe(false);expect((await f.service(db).delivery(ctx(),await intent(db,manual))).receipt.outcome).toBe('rollback-rejected');expect((await current()).status).toBe(0);});});
 it('denies uncompleted pink domain and future presale snapshots through the real SQL gate',async()=>{await f.db.update(storeOrder).set({type:3,pinkId:1}).where(eq(storeOrder.id,1));await f.db.insert(storePink).values({id:1,uid:201,status:1});await f.app(async db=>{expect((await f.service(db).delivery(ctx(),await intent(db,manual))).receipt.outcome).toBe('rollback-rejected');});});
  it('uses persisted presale purchase snapshot and actual database clock before any fulfillment',async()=>{await f.db.update(storeOrder).set({type:6}).where(eq(storeOrder.id,1));const snapshot=JSON.parse(f.cart(1).cartInfo!);snapshot.productInfo.presale_end_time=Math.floor(Date.now()/1000)+3600;snapshot.productInfo.presale_start_time=1;snapshot.productInfo.is_presale_product=1;await f.db.update(storeOrderCartInfo).set({cartInfo:JSON.stringify(snapshot)}).where(eq(storeOrderCartInfo.id,1));await f.app(async db=>{expect((await f.service(db).delivery(ctx(),await intent(db,manual))).receipt.outcome).toBe('rollback-rejected');expect((await current()).status).toBe(0);expect((await state()).outbox).toHaveLength(0);});});
 it('admits a real customer waybill and applies queue/provider result once with exact receipt and actual physical fulfillment',async()=>{await f.app(async db=>{const a=await admit(db),p=provider();expect(f.messages).toHaveLength(1);expect(JSON.stringify(f.messages)).not.toMatch(/实际收件人|实际发件人|13900000/);expect(await queueProcess(db,a.id,p.fetcher)).toBe('sent');expect(p.issues()).toBe(1);expect(await current()).toMatchObject({status:1,deliveryId:'OWNED-WAYBILL-001'});expect(await queueProcess(db,a.id,p.fetcher)).toBe('already-sent');expect(p.issues()).toBe(1);const detail=await f.service(db).waybillJob(f.actor(),a.id,{});expect(Frontend.isCustomerWorkWaybillJob(detail.data.job)).toBe(true);expect(detail.data.job).toMatchObject({actor_type:'customer',actor_id:101,service_id:1,status:'SENT'});expect((await f.service(db).waybillJobs(f.actor(),{order_id:'1'})).data.list).toHaveLength(1);expect((await f.service(db).delivery(a.context,a.input)).receipt).toEqual(a.result.receipt);});});
 it('revokes a not yet invoked queued customer waybill without calling provider or granting admin fallback',async()=>{await f.app(async db=>{const a=await admit(db),p=provider();await f.db.update(storeService).set({customer:0}).where(eq(storeService.id,1));expect(await queueProcess(db,a.id,p.fetcher)).toBe('closed');expect(p.issues()).toBe(0);expect((await current()).status).toBe(0);expect(await f.ledger(db).getOutcome(f.actor(),a.context.request_key)).toEqual(a.result.receipt);});});
 it('preserves provider admitted fact and local immutable authority when customer role is revoked after invocation',async()=>{await f.app(async db=>{const a=await admit(db),p=provider(async()=>{await f.db.update(storeService).set({customer:0}).where(eq(storeService.id,1));});expect(await queueProcess(db,a.id,p.fetcher)).toBe('sent');expect(p.issues()).toBe(1);expect((await current()).status).toBe(1);expect((await state()).jobs[0]).toMatchObject({status:'SENT',actorType:'customer',actorId:101,actorServiceId:1});});});
 it('does not invoke provider again after UNKNOWN and accepts only fresh original customer job decision plus immutable action replay',async()=>{await f.app(async db=>{const a=await admit(db),p=provider(undefined,true);expect(await queueProcess(db,a.id,p.fetcher)).toBe('unknown');expect(p.issues()).toBe(1);await jobService(db).dispatchPending(20);await queueProcess(db,a.id,p.fetcher);expect(p.issues()).toBe(1);const d=await decision(db,a.id,'CONFIRM_ISSUED',{tracking_number:'VERIFIED-EXISTING-001',label_url:'https://example.test/confirmed.png',provider_reference:'verified-ref'});const first=await f.service(db).waybillDecision(d.context,a.id,d.input);expect(first.receipt).toMatchObject({kind:'waybill_confirm_issued',outcome:'job-updated',evidence:{status:'SENT'}});expect((await current()).deliveryId).toBe('VERIFIED-EXISTING-001');expect((await f.service(db).waybillDecision(d.context,a.id,d.input)).receipt).toEqual(first.receipt);expect((await f.service(db).waybillActions(f.actor(),a.id,{})).data.list).toHaveLength(1);});});
 it('keeps split job original root operation after provider fulfillment turns its source into pid minus one',async()=>{await f.app(async db=>{const a=await admit(db,true),p=provider();expect(await queueProcess(db,a.id,p.fetcher)).toBe('sent');expect((await current()).pid).toBe(-1);const detail=await f.service(db).waybillJob(f.actor(),a.id,{});expect(detail.data.operation.order_id).toBe(1);expect(detail.data.job.fulfilled_order_id).not.toBe(1);expect(detail.data.job.remaining_order_id).toEqual(expect.any(Number));expect(Frontend.isCustomerWorkWaybillJob(detail.data.job)).toBe(true);expect((await f.service(db).waybillJobs(f.actor(),{order_id:String(detail.data.job.remaining_order_id)})).data.list.map(j=>j.id)).toContain(a.id);expect((await f.service(db).delivery(a.context,a.input,true)).replayed).toBe(true);});});
 it('rejects queued frozen physical identity changes before the provider invocation',async()=>{await f.app(async db=>{const a=await admit(db),p=provider();await f.db.update(storeOrder).set({storeId:77}).where(eq(storeOrder.id,1));await queueProcess(db,a.id,p.fetcher);expect(p.issues()).toBe(0);expect((await current()).status).toBe(0);expect((await state()).jobs[0].status).not.toBe('SENT');});});
  it.each(['disabled','config'])('rejects queued actual carrier $0 changes without invoking provider',async key=>{await f.app(async db=>{const a=await admit(db),p=provider();await f.db.update(expressCompany).set(key==='disabled'?{status:0}:{account:'changed provider signing account'}).where(eq(expressCompany.id,1));await queueProcess(db,a.id,p.fetcher);expect(p.issues()).toBe(0);expect((await current()).status).toBe(0);expect((await state()).jobs[0].status).not.toBe('SENT');});});
  it('publishes real provider template catalog through frontend guard and refuses defaults drift during external catalog query',async()=>{await f.app(async db=>{let change=false;vi.stubGlobal('fetch',vi.fn(async(input:Parameters<typeof fetch>[0])=>{const url=String(input);if(url.includes('/v2/user/login'))return Response.json({status:200,data:{access_token:'owned-token',expires_in:3600}});if(url.includes('/v2/expr_dump/temp')){if(change)await f.db.update(systemConfig).set({value:'Changed actual sender'}).where(eq(systemConfig.id,4));return Response.json({status:200,data:[{title:'实际模板',temp_id:'owned-template',pic:'https://example.test/template.png'}]});}throw Error('Unowned template transport');}));expect(Frontend.isCustomerWorkTemplates((await f.service(db).templates(f.actor(),{carrier_id:'1'})).data)).toBe(true);change=true;await expect(f.service(db).templates(f.actor(),{carrier_id:'1'})).rejects.toThrow('变化');expect((await state()).jobs).toHaveLength(0);});});
  it.each(['snapshot','uid','quantity'])('rejects mutable queued cart $0 drift before invoking the provider',async key=>{await f.app(async db=>{const a=await admit(db),p=provider();const change=key==='snapshot'?{cartInfo:JSON.stringify({productInfo:{id:1,store_name:'changed provider cargo'},truePrice:'10.00'})}:key==='uid'?{uid:109}:{splitSurplusNum:2};await f.db.update(storeOrderCartInfo).set(change).where(eq(storeOrderCartInfo.id,1));await queueProcess(db,a.id,p.fetcher);expect(p.issues()).toBe(0);expect((await current()).status).toBe(0);expect((await state()).jobs[0].status).not.toBe('SENT');});});
  it.each(['absent','partial','malformed'])('returns explicit unavailable bootstrap under ordinary LOGIN for $0 city catalog instead of a relation missing error',async shape=>{const isolated=await customerWorkFulfillmentFixture();try{await isolated.app(async db=>{if(shape==='malformed')await isolated.exec('ALTER TABLE customer_city_delivery_job DROP CONSTRAINT ccdjob_status_ck');else if(shape==='partial')await isolated.exec('DROP TABLE customer_city_delivery_binding');else await isolated.exec('DROP TABLE customer_city_delivery_binding,customer_city_delivery_attempt,customer_city_delivery_job');const b=await isolated.service(db).bootstrap(isolated.actor(),'customer-order-1',{});expect(b.data.readiness.city.schema_ready).toBe(false);expect(b.data.actions.manual_delivery).toMatchObject({available:false});expect(b.data.actions.split_delivery.available).toBe(false);expect(b.data.actions.electronic_waybill.available).toBe(false);expect(b.data.actions.city_delivery.available).toBe(false);expect(Frontend.isCustomerWorkFulfillment(b.data)).toBe(true);const order=b.data.order,context={actor:isolated.actor(),request_key:crypto.randomUUID()},input:CustomerOperationInput={version:'customer-work-operation-v1',scope_key:b.scope_key,order_id:order.id,expected_order_revision:order.order_revision,expected_fulfillment_revision:order.fulfillment_revision,payload:manual},rejected=await isolated.service(db).delivery(context,input);expect(rejected.receipt).toMatchObject({outcome:'rollback-rejected',service_id:0});expect(await isolated.ledger(db).getOutcome(isolated.actor(),context.request_key)).toEqual(rejected.receipt);expect((await isolated.db.select().from(storeOrder).where(eq(storeOrder.id,1)))[0].status).toBe(0);expect(await isolated.db.select().from(storeOrderOutbox)).toHaveLength(0);});}finally{await isolated.close();}},60000);
  it('preserves real third party city delivery for legacy shipping type three through complete wire and dynamic owned outcome',async()=>{
   await f.db.update(storeOrder).set({shippingType:3}).where(eq(storeOrder.id,1));
   await f.db.insert(systemConfig).values([{id:20,menuName:'city_delivery_status',value:'1'},{id:21,menuName:'dada_delivery_status',value:'1'},{id:22,menuName:'uu_delivery_status',value:'0'},{id:23,menuName:'refund_name',value:'真实平台发件人'},{id:24,menuName:'refund_address',value:'上海市真实平台地址'},{id:25,menuName:'refund_phone',value:'13900000999'}]);
   let issues=0;vi.stubGlobal('fetch',vi.fn(async(input:Parameters<typeof fetch>[0])=>{const url=String(input),response=(result:unknown)=>Response.json({code:0,status:'success',result});if(url.endsWith('/api/cityCode/list'))return response([{cityName:'上海',cityCode:'021'}]);if(url.endsWith('/api/order/queryDeliverFee'))return response({deliveryNo:'ACTUAL-SHIPPING3-CITY',distance:1200,fee:8.5});if(url.endsWith('/api/order/addAfterQuery')){issues++;return response('');}throw Error('Unexpected city provider endpoint');}));
   await f.app(async db=>{
    const cityEnv={...f.env,DADA_APP_KEY:'owned-dada-key',DADA_APP_SECRET:'owned-dada-secret',DADA_SOURCE_ID:'owned-dada-source',DADA_CLIENT_ID:'owned-dada-client',DADA_CALLBACK_TOKEN:'owned_callback_dada_token_0123456789',CUSTOMER_CITY_CALLBACK_ORIGIN:'https://city-fixture.example.com'} as unknown as Env;
    const service=new CustomerWorkFulfillmentService(createContainerFromDb(db),cityEnv),bootstrap=await service.bootstrap(f.actor(),'customer-order-1',{});expect(Frontend.isCustomerWorkFulfillment(bootstrap.data)).toBe(true);expect(bootstrap.data.actions.city_delivery.available).toBe(true);expect(bootstrap.data.actions.electronic_waybill.available).toBe(false);
    const o=bootstrap.data.order,input:CustomerOperationInput={version:'customer-work-operation-v1',scope_key:bootstrap.scope_key,order_id:o.id,expected_order_revision:o.order_revision,expected_fulfillment_revision:o.fulfillment_revision,payload:{type:2,delivery_type:2,station_type:1,cargo_weight:'2.50',delivery_remark:'实际配送备注'}},context=ctx(),prepared=await prepareCustomerOperation('city_delivery',context,input),result=await service.delivery(context,input);
    const pending={version:'customer-work-pending-v1',request_key:context.request_key,request_hash:prepared.hash,actor_uid:101,service_id:1,scope_key:input.scope_key,order_no:o.order_id,root_order_id:o.root_order_id,kind:'city_delivery',body:input,created_at:Date.now()} as Parameters<typeof Frontend.parseCustomerWorkReceipt>[1];expect(Frontend.parseCustomerWorkReceipt(result,pending)).toEqual(result.receipt);expect(result.receipt.outcome).toBe('provider-admitted');expect(issues).toBe(1);expect(await current()).toMatchObject({shippingType:3,status:1,deliveryType:'city_delivery',deliveryId:'ACTUAL-SHIPPING3-CITY'});
    const outcome=await service.operationOutcome(f.actor(),context.request_key);expect(outcome.receipt).toEqual(result.receipt);expect(outcome.city_job).toMatchObject({status:'ADMITTED'});expect(Frontend.isCustomerWorkCityJob(outcome.city_job)).toBe(true);await f.db.update(storeService).set({customer:0}).where(eq(storeService.id,1));expect((await service.operationOutcome(f.actor(),context.request_key)).city_job?.status).toBe('ADMITTED');expect((await service.delivery(context,input)).replayed).toBe(true);expect(issues).toBe(1);
   });
  });
 it('uses ordinary UserJWT HTTP writer with required UUID exact body and refuses admin-like tokens and path substitution',async()=>{
  await f.app(async db=>{
   const h=new Hono<{Bindings:Env;Variables:AppVariables}>();h.use('*',async(c,next)=>{c.set('container',createContainerFromDb(db));await next();});h.use('*',authMiddleware({force:true}));h.onError((e,c)=>c.json({status:400,msg:e.message},400));h.post('/orders/:id/fulfillment',Controller.deliver);
   const token=await createToken(101,'api',f.actor().auth_version,f.env.APP_KEY),input=await intent(db,manual),headers={'Content-Type':'application/json','Authori-zation':`Bearer ${token.token}`,'Idempotency-Key':crypto.randomUUID()};
   expect((await h.request('/orders/2/fulfillment',{method:'POST',headers,body:JSON.stringify(input)},f.env)).status).toBe(400);
   const admin=await createToken(101,'admin',f.actor().auth_version,f.env.APP_KEY);expect((await h.request('/orders/1/fulfillment',{method:'POST',headers:{...headers,'Authori-zation':`Bearer ${admin.token}`},body:JSON.stringify(input)},f.env)).status).toBe(400);
   const response=await h.request('/orders/1/fulfillment',{method:'POST',headers,body:JSON.stringify(input)},f.env);expect(response.status).toBe(200);expect(response.headers.get('cache-control')).toContain('no-store');expect((await response.json() as {data:{receipt:{outcome:string}}}).data.receipt.outcome).toBe('delivery-recorded');
  });
 });
});
