import { PGlite } from "@electric-sql/pglite";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { catalogKinds, compareCatalogs, readCatalog, type Catalog, type CatalogRow } from "../scripts/data-migration/postgres-catalog-audit";
import { validateTestTarget } from "../scripts/orm-ddl-audit";

const base = `
CREATE TABLE parent (tenant text NOT NULL, id integer NOT NULL, PRIMARY KEY(tenant,id));
CREATE TABLE probe (
 id serial PRIMARY KEY, tenant text NOT NULL, parent_id integer,
 counter bigint GENERATED ALWAYS AS IDENTITY, payload jsonb DEFAULT '{}'::jsonb,
 amount numeric(12,2) DEFAULT 0.00 NOT NULL, title text COLLATE "C",
 measure integer GENERATED ALWAYS AS (parent_id+1) STORED,
 CONSTRAINT probe_parent_fk FOREIGN KEY(tenant,parent_id) REFERENCES parent(tenant,id) ON DELETE CASCADE,
 CONSTRAINT probe_amount_ck CHECK(amount>=0), CONSTRAINT probe_upper_ck CHECK(amount<100)
);
CREATE INDEX probe_partial ON probe(parent_id DESC NULLS LAST) INCLUDE(tenant) WHERE amount>0;
CREATE UNIQUE INDEX probe_tenant_uid ON probe(tenant,id);
CREATE TABLE old_only(id integer);
CREATE SEQUENCE visitor_uid AS integer START 100 MINVALUE 1 MAXVALUE 200 CACHE 1 OWNED BY probe.parent_id;
`;
const left = new PGlite();
const right = new PGlite();
const read = (db: PGlite) => readCatalog(async (query) => (await db.query<CatalogRow>(query)).rows);
let original: Catalog;
let identical: Catalog;
let changed: Catalog;

beforeAll(async () => {
  await left.exec(base);
  await right.exec(base);
  original = await read(left);
  identical = await read(right);
  await right.exec(`
    DROP TABLE old_only; CREATE TABLE new_only(id integer);
    ALTER TABLE probe DROP COLUMN title, ADD COLUMN extra varchar(4) NOT NULL DEFAULT 'x';
    ALTER TABLE probe ALTER COLUMN amount TYPE numeric(20,4), ALTER COLUMN amount DROP NOT NULL,
      ALTER COLUMN payload DROP DEFAULT, ALTER COLUMN counter SET GENERATED BY DEFAULT;
    ALTER TABLE probe DROP COLUMN measure;
    ALTER TABLE probe ADD COLUMN measure integer GENERATED ALWAYS AS (parent_id+2) STORED;
    ALTER TABLE probe DROP CONSTRAINT probe_parent_fk;
    ALTER TABLE probe ADD CONSTRAINT probe_parent_fk FOREIGN KEY(tenant,parent_id) REFERENCES parent(tenant,id) ON DELETE RESTRICT DEFERRABLE;
    ALTER TABLE probe RENAME CONSTRAINT probe_upper_ck TO renamed_upper_ck;
    DROP INDEX probe_partial;
    CREATE INDEX probe_partial ON probe(parent_id DESC NULLS FIRST) INCLUDE(tenant) WHERE amount>=0;
    ALTER INDEX probe_tenant_uid RENAME TO renamed_tenant_uid;
    ALTER SEQUENCE visitor_uid AS bigint MAXVALUE 300 INCREMENT 2 CACHE 5 CYCLE OWNED BY NONE;
  `);
  changed = await read(right);
}, 30_000);
afterAll(async () => { await left.close(); await right.close(); });

describe("DB-009 real PostgreSQL catalog comparison", () => {
  it("rejects production, connection overrides and malformed targets before any connection", () => {
    expect(validateTestTarget("postgresql://finance_test:fixture@127.0.0.1:5432/cinashop_finance_test").hostname).toBe("127.0.0.1");
    for (const value of [undefined, "not a URL", "https://finance_test:fixture@localhost/cinashop_finance_test",
      "postgres://finance_test:fixture@db.example.invalid/cinashop_finance_test", "postgres://other:fixture@localhost/cinashop_finance_test",
      "postgres://finance_test:fixture@localhost/production", "postgres://finance_test:fixture@localhost/cinashop_finance_test?options=unsafe",
      "postgres://finance_test:fixture@localhost/cinashop_finance_test#fragment"]) {
      expect(() => validateTestTarget(value)).toThrow();
    }
  });

  it("ignores database OIDs but proves identical definitions across independent databases", () => {
    for (const kind of catalogKinds) expect(compareCatalogs(original, identical)[kind]).toEqual({ referenceOnly: [], candidateOnly: [], changed: [], possibleRenames: [] });
  });

  it("detects table/column presence, type, nullability, default, identity and generated expression changes", () => {
    const diff = compareCatalogs(original, changed);
    expect(diff.tables.referenceOnly.map((row) => row.key)).toEqual(["old_only"]);
    expect(diff.tables.candidateOnly.map((row) => row.key)).toEqual(["new_only"]);
    expect(diff.columns.referenceOnly.map((row) => row.key)).toContain("probe.title");
    expect(diff.columns.candidateOnly.map((row) => row.key)).toContain("probe.extra");
    const fields = Object.fromEntries(diff.columns.changed.map((row) => [row.key, row.fields]));
    expect(fields["probe.amount"]).toEqual(["notNull", "type"]);
    expect(fields["probe.payload"]).toEqual(["default"]);
    expect(fields["probe.counter"]).toEqual(["identity"]);
    expect(fields["probe.measure"]).toEqual(["default"]);
    expect(original.columns.find((row) => row.key === "probe.title")?.collation).toBe("pg_catalog.C");
  });

  it("retains tenant FK actions/deferrability and reports name-only evidence without waiving missing constraints", () => {
    const diff = compareCatalogs(original, changed).constraints;
    expect(diff.changed.find((row) => row.key === "probe.probe_parent_fk")?.fields).toEqual(["deferrable", "definition"]);
    expect(diff.possibleRenames).toEqual([{ reference: "probe.probe_upper_ck", candidate: "probe.renamed_upper_ck" }]);
    expect(diff.referenceOnly.map((row) => row.key)).toContain("probe.probe_upper_ck");
  });

  it("compares partial/expression/include/order definitions independently of names", () => {
    const diff = compareCatalogs(original, changed).indexes;
    expect(diff.changed.find((row) => row.key === "probe.probe_partial")?.fields).toEqual(["definition"]);
    expect(diff.possibleRenames).toEqual([{ reference: "probe.probe_tenant_uid", candidate: "probe.renamed_tenant_uid" }]);
    expect(original.indexes.find((row) => row.key === "probe.probe_partial")?.definition).toContain("INCLUDE (tenant)");
  });

  it("detects sequence type/bounds/cache/cycle and ownership instead of checking only the next value", () => {
    expect(compareCatalogs(original, changed).sequences.changed.find((row) => row.key === "visitor_uid")?.fields)
      .toEqual(["cache", "cycle", "increment", "max", "ownedBy", "type"]);
    expect(original.sequences.find((row) => row.key === "visitor_uid")?.ownedBy).toBe("public.probe.parent_id");
  });

  it("distinguishes standalone unique indexes from constraint-owned indexes", async () => {
    await right.exec("ALTER TABLE probe ADD CONSTRAINT renamed_tenant_uid UNIQUE USING INDEX renamed_tenant_uid");
    const after = await read(right);
    const diff = compareCatalogs(changed, after);
    expect(diff.indexes.changed.find((row) => row.key === "probe.renamed_tenant_uid")?.fields).toEqual(["constraintOwned"]);
    expect(diff.constraints.candidateOnly.map((row) => row.key)).toEqual(["probe.renamed_tenant_uid"]);
  });

  it("fails closed on duplicate catalog identities", () => {
    expect(() => compareCatalogs({ ...original, tables: [...original.tables, original.tables[0]] }, identical)).toThrow("Duplicate tables");
  });
});
