import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {eq} from 'drizzle-orm';
import {createContainerFromDb} from '../src/lib/di';
import {systemDise,storeProduct,storeProductDescription,community} from '../src/models/schema';
import {StoreProductService} from '../src/services/product/StoreProductService';
import {PublicCatalogService} from '../src/services/product/PublicCatalogService';
import {V2PublicCompatibilityService} from '../src/services/content/V2PublicCompatibilityService';
import {readActivityDetailDesign,readProductCommunity} from '../src/services/product/ProductDetailDesignData';
import {IntegralProductReadService} from '../src/services/activity/IntegralProductReadService';
import {ActivityService} from '../src/services/activity/ActivityService';
import {StoreNewcomerService} from '../src/services/activity/StoreNewcomerService';
import {productDetailDesignFixture} from './helpers/productDetailDesignFixture';
import {observeCategoryDb} from './helpers/productCategoryStyleFixture';
import {cloneProductDetailDesign} from '../../view/common/productDetailDesign';
import {Hono} from 'hono';
import type {AppVariables,Env} from '../src/env';
import {SeckillSkuCatalogService} from '../src/services/activity/SeckillSkuCatalogService';
import {CombinationSkuCatalogService} from '../src/services/activity/CombinationSkuCatalogService';
import {PresaleSkuCatalogService} from '../src/services/activity/PresaleSkuCatalogService';
import {seckillDetail,combinationDetail} from '../src/controllers/api/v1/UserActivityController';
import {detail as productDetail} from '../src/controllers/api/v1/ProductController';
describe.runIf(Boolean(process.env.TEST_FINANCE_POSTGRES_URL))('native full product detail design consumers',()=>{
  let f:Awaited<ReturnType<typeof productDetailDesignFixture>>,guard:ReturnType<typeof vi.spyOn>;
  beforeEach(async()=>{f=await productDetailDesignFixture();guard=vi.spyOn(globalThis,'fetch').mockRejectedValue(Error('No public detail network'));},30000);
  afterEach(async()=>{try{expect(guard).not.toHaveBeenCalled();}finally{guard?.mockRestore();await f?.close();}},30000);
  const read=(db:any=f.db)=>new StoreProductService(createContainerFromDb(db),f.env);
  const design=async(change:Record<string,unknown>)=>f.db.update(systemDise).set({value:JSON.stringify({...cloneProductDetailDesign(),...change,opaque:{private:'PRIVATE EXTENSION'}})}).where(eq(systemDise.id,5));
  const app=(run:(peer:any)=>Promise<void>)=>f.withRuntimeRole(async peer=>{await f.installSelectSlice(peer,'app');await run(peer);});
  it('returns real bounded reply/community counts, safe body/assets/ensures/specs and rank with no private SKU/extension leakage',async()=>{await app(async peer=>{const before=await f.snapshot(),result=await read(peer.db).getProductDetail(70,11);expect(result.product_detail_design).toMatchObject({configured:true,value:{isOpen:[3,4,5,1,2,0]}});expect(result.reply).toHaveLength(2);expect(result).toMatchObject({replyCount:2,replyChance:50,elegant_count:2});expect(result.elegant_list).toHaveLength(2);expect(result.ensure).toHaveLength(1);expect(result.specs).toEqual([{name:'材质',value:'棉',sort:1}]);expect(result.rank).toBeGreaterThan(0);expect(result.description).toMatch(/\/api\/assets\/41\?/);expect(String(result.description)).not.toMatch(/assets\/43|onerror|<script/);expect(JSON.stringify(result)).not.toMatch(/PRIVATE|SECRET|"cost"|settle_price|disk_info|bar_code|brokerage/);expect(await f.snapshot()).toEqual(before);
    for(const [reference,allowed] of[['/api/assets/111?expires=1&signature=old',true],['/api/assets/112',false],['/api/assets/113',false],['/a/../api/assets/111',false]] as const){await f.db.update(storeProduct).set({videoLink:reference}).where(eq(storeProduct.id,70));const detail=await read(peer.db).getProductDetail(70,11);if(allowed)expect(detail.videoLink).toMatch(/^\/api\/assets\/111\?expires=\d+&signature=/);else expect(detail.videoLink).toBe('');}
  });});
  it('applies every read switch and exact count while leaving safe publication and cart qualification unchanged',async()=>{await app(async peer=>{await design({showReply:1,replyNum:1,showCommunity:1,communityNum:1,showMatch:1,matchNum:1,showRecommend:1,recommendNum:1});let result=await read(peer.db).getProductDetail(70,11);expect(result.reply).toHaveLength(1);expect(result.elegant_list).toHaveLength(1);expect(result.discounts_products).toHaveLength(1);expect(result.recommend).toHaveLength(1);expect(result.cart_button).toBe(1);await design({showReply:0,showCommunity:0,showMatch:0,showRecommend:0,showRank:0,showService:[],showCart:0});result=await read(peer.db).getProductDetail(70,11);expect(result).toMatchObject({reply:[],replyCount:0,replyChance:0,elegant_list:[],elegant_count:0,ensure:[],specs:[],rank:0,recommend:[],discounts_products:[],cart_button:1});});});
  it('changes each selected SKU display offer without changing actual member price or authoritative purchase qualification',async()=>{await app(async peer=>{for(const [showPrice,expected] of [[[],'20.00'],[[0],'17.60'],[[1],'18.00'],[[0,1],'17.60']] as const){await design({showPrice:[...showPrice]});const result=await read(peer.db).getProductDetail(70,11),skus=result.attr_value as any[];expect(skus[0].display_price.price).toBe(expected);expect(skus[0]).toMatchObject({price:'20.00',member_price:'17.60',price_type:'level',stock:8,purchasable:true});expect(skus[1]).toMatchObject({price:'30.00',member_price:'26.40',stock:3});}});});
  it('uses one real RR snapshot across config, body and counts despite a committed peer edit, then exposes the new request',async()=>{await app(async peer=>{await f.withPeer(async writer=>{let switched=false;const db=observeCategoryDb(peer.db,async(_tx,command)=>{if(!switched&&command.includes('system_dise')){switched=true;await writer.db.update(systemDise).set({value:JSON.stringify({...cloneProductDetailDesign(),showReply:0,showCommunity:0})}).where(eq(systemDise.id,5));await writer.db.update(storeProductDescription).set({description:'NEW PEER BODY'}).where(eq(storeProductDescription.productId,70));}});const old=await read(db).getProductDetail(70,11);expect(switched).toBe(true);expect(old.replyCount).toBe(2);expect(old.elegant_count).toBe(2);expect(String(old.description)).toContain('公开正文');const fresh=await read(peer.db).getProductDetail(70,11);expect(fresh.replyCount).toBe(0);expect(fresh.elegant_count).toBe(0);expect(fresh.description).toBe('NEW PEER BODY');});});});
  it('shares the named nineteen-key public authority, protects opaque values, and keeps site origin out of SQL/API fallbacks',async()=>{await app(async peer=>{const publicService=new V2PublicCompatibilityService(createContainerFromDb(peer.db),f.env),raw=await publicService.diy(' product_detail '),page=await publicService.productDetail();expect(Object.keys(raw as object)).toHaveLength(19);expect(JSON.stringify(raw)).not.toContain('opaque');expect(page.product_detail).toEqual(raw);expect(page.product_detail_design_state).toMatchObject({configured:true,issues:[]});const detail=await read(peer.db).getProductDetail(70,0);expect(detail.site_url).toBe('https://shop.example.com');expect(JSON.stringify(detail)).not.toContain('wrong-api');});});
  it('keeps activity inverse specs and its actual reply/ensure subset, including real combination and integral entries',async()=>{await app(async peer=>{await design({showService:[2,3],showReply:0});const ordinary=await read(peer.db).getProductDetail(70,0),activity=await readActivityDetailDesign(peer.db,{id:9,productId:70,specs:'[{"name":"活动参数","value":"活动"}]'},1,0),integral=await new IntegralProductReadService(createContainerFromDb(peer.db),f.env).read(9),combination=await new ActivityService(createContainerFromDb(peer.db),f.env).combinationDetail(401);expect(ordinary.specs).toHaveLength(1);expect(activity.specs).toEqual([]);expect(activity.reply).toEqual([]);expect(combination.specs).toEqual([]);expect(combination.product_detail_design.value.showService).toEqual([2,3]);expect(integral.storeInfo.specs).toEqual([]);await design({showService:[2],showReply:1,replyNum:1});const projected=await new ActivityService(createContainerFromDb(peer.db),f.env).combinationDetail(401);expect(projected.specs).toHaveLength(1);expect(projected.reply).toHaveLength(1);expect(projected.ensure).toHaveLength(1);expect(projected.image).toMatch(/^\/api\/assets\/41\?/);
    const newcomer=await new StoreNewcomerService(createContainerFromDb(peer.db),f.env).detail(0,701);expect(newcomer.product_detail_design).toMatchObject({value:{showService:[2]}});expect((newcomer.storeInfo as any).specs).toHaveLength(1);expect((newcomer.storeInfo as any).attr_value[0]).toMatchObject({image:'',price:'9.00'});expect(JSON.stringify(newcomer)).not.toMatch(/PRIVATE|"cost"|disk_info|bar_code|brokerage/);
  });});
  it('pages only exact published product relations, deduplicates links, and rejects hidden parents or malformed pagination',async()=>{await app(async peer=>{expect(await readProductCommunity(peer.db,70,1,1)).toMatchObject({list:[{id:201}],count:2});expect(await readProductCommunity(peer.db,70,2,1)).toMatchObject({list:[{id:202}],count:2});for(const args of[[0,10],[1,101],[10002,1]])await expect(readProductCommunity(peer.db,70,args[0],args[1])).rejects.toThrow();await f.db.update(community).set({isDel:1}).where(eq(community.id,201));expect((await readProductCommunity(peer.db,70)).count).toBe(1);await f.db.update(storeProduct).set({isShow:0}).where(eq(storeProduct.id,70));await expect(readProductCommunity(peer.db,70)).rejects.toThrow();});});
  it('uses the same design counts for existing recommendation/body/marketing public entry points and never exports unsafe raw extensions',async()=>{await app(async peer=>{await design({showRecommend:0,showMatch:0,showService:[]});const service=new PublicCatalogService(createContainerFromDb(peer.db),f.env);expect(await service.detailRecommend(11,70)).toEqual([]);expect((await service.detailContent(70)).description).toContain('/api/assets/41?');expect((await service.productActivity(70)).discounts_products).toEqual([]);await design({showMatch:1,matchNum:1});expect((await service.productActivity(70)).discounts_products).toHaveLength(1);});});
  it('serves the actual three selection HTTP readers through SELECT-only LOGIN with signed media, exact display switches and unchanged financial SKU identity',async()=>{await app(async peer=>{
    const now=Math.floor(Date.now()/1000);await f.db.update(storeProduct).set({isPresaleProduct:1,presaleStartTime:now-60,presaleEndTime:now+3600,presaleDay:7}).where(eq(storeProduct.id,70));
    await design({showService:[2,3],showReply:1,replyNum:1});
    const http=new Hono<{Bindings:Env;Variables:AppVariables}>();http.use('*',async(c,next)=>{c.set('container',createContainerFromDb(peer.db));c.set('uid',11);await next();});
    http.get('/api/seckill/detail/:id',seckillDetail);http.get('/api/combination/detail/:id',combinationDetail);http.get('/api/product/detail/:id',productDetail);
    const before=await f.snapshot();
    for(const [url,type,price,unique] of[['/api/seckill/detail/601?view=skus',1,'8.25','seck0601'],['/api/combination/detail/401?view=skus',3,'15.00','comb0401'],['/api/product/detail/70?view=presale',6,'20.00','base0070']] as const){
      const response=await http.request(url,undefined,f.env),body=await response.json() as {status:number;data:any};expect(body.status).toBe(200);expect(response.headers.get('cache-control')).toBe('private, no-store');const value=body.data;
      expect(value).toMatchObject({type,product_id:70,product_detail_design:{value:{showService:[2,3]}},replyCount:2,replyChance:50});
      expect(value.reply).toHaveLength(1);expect(value.ensure).toHaveLength(1);expect(value.specs).toHaveLength(type===6?1:0);expect(value.image).toMatch(/^\/api\/assets\/41\?expires=\d+&signature=/);
      expect(value.skus[0]).toMatchObject({unique,catalog_price:price,base_unique:'base0070'});expect(value.skus[0].image).toMatch(/^\/api\/assets\/41\?/);
      expect(JSON.stringify(value)).not.toMatch(/PRIVATE|"cost"|brokerage|diskInfo|opaque|assets\/43/);expect(value.description).toContain('/api/assets/41?');
    }
    expect(await f.snapshot()).toEqual(before);
    await design({showService:[2],showReply:0});const selected=await new CombinationSkuCatalogService(createContainerFromDb(peer.db),f.env).read(11,'401');expect(selected.specs).toHaveLength(1);expect(selected).toMatchObject({reply:[],replyCount:0,replyChance:0});
    const presale=await new PresaleSkuCatalogService(createContainerFromDb(peer.db),f.env).read(11,'70');expect(presale.specs).toEqual([]);expect(presale.skus[0].catalog_price).toBe('20.00');
  });});
  it('keeps the selection design and activity body in the same RR snapshot across a committed peer edit without financial mutation',async()=>{await app(async peer=>{await f.withPeer(async writer=>{
    await design({showService:[2],showReply:1,replyNum:1});const before=await f.snapshot();let switched=false;
    const observed=observeCategoryDb(peer.db,async(_tx,command)=>{if(!switched&&command.includes('store_seckill')){switched=true;await writer.db.update(systemDise).set({value:JSON.stringify({...cloneProductDetailDesign(),showReply:0,showService:[3]})}).where(eq(systemDise.id,5));await writer.db.update(storeProductDescription).set({description:'NEW SECKILL PEER BODY'}).where(eq(storeProductDescription.productId,601));}});
    const old=await new SeckillSkuCatalogService(createContainerFromDb(observed),f.env).read(11,'601');expect(switched).toBe(true);expect(old.replyCount).toBe(2);expect(old.specs).toHaveLength(1);expect(old.description).toContain('秒杀公开正文');
    const fresh=await new SeckillSkuCatalogService(createContainerFromDb(peer.db),f.env).read(11,'601');expect(fresh).toMatchObject({replyCount:0,reply:[],specs:[],description:'NEW SECKILL PEER BODY'});expect(fresh.skus).toEqual(old.skus);
    const after=await f.snapshot();for(const key of Object.keys(before))if(!['system_dise','store_product_description'].includes(key))expect(after[key as keyof typeof after]).toEqual(before[key as keyof typeof before]);
  });});});
});
