import { describe,it,expect } from 'vitest';
import { parseManagerListQuery,parseManagerDailyQuery,parseManagerPeriodQuery,managerOrderNumber } from '../src/services/store/StoreManagerOrderInput';
describe('merchant manager strict query contracts',()=>{
 it('requires explicit positive store and rejects foreign query capabilities',()=>{const cases:Record<string,string>[]=[{},{store_id:'0'},{store_id:'1',uid:'202'},{store_id:'1',supplier_id:'8'},{store_id:'true'},{store_id:'2147483648'}];for(const query of cases)expect(()=>parseManagerListQuery(query)).toThrow();});
 it('keeps empty all and all fourteen status selectors distinct',()=>{expect(parseManagerListQuery({store_id:'77',status:''}).selector).toBeNull();for(let selector=-4;selector<=9;selector++)expect(parseManagerListQuery({store_id:'77',status:String(selector),...(selector===-4?{is_del:'1'}:{})}).selector).toBe(selector);for(const status of ['10','-5','NaN','1.5'])expect(()=>parseManagerListQuery({store_id:'77',status})).toThrow();});
 it('requires an explicit compatible deletion selection',()=>{expect(()=>parseManagerListQuery({store_id:'77',status:'-4'})).toThrow();expect(()=>parseManagerListQuery({store_id:'77',status:'1',is_del:'1'})).toThrow();expect(parseManagerListQuery({store_id:'77',status:'',is_del:'1'}).isDel).toBe(1);});
 it('accepts real order types shipping types payment types and bounded pagination',()=>{for(const type of [0,1,2,3,4,5,6,7,8,105,106,107])expect(parseManagerListQuery({store_id:'77',type:String(type)}).type).toBe(type);for(const type of ['9','104','108'])expect(()=>parseManagerListQuery({store_id:'77',type})).toThrow();for(const page of ['0','10001','1e2'])expect(()=>parseManagerListQuery({store_id:'77',page})).toThrow();for(const limit of ['0','101'])expect(()=>parseManagerListQuery({store_id:'77',limit})).toThrow();expect(parseManagerListQuery({store_id:'77',pay_type:'3'}).payType).toBe('offline');});
 it('validates business order identifiers without coercing them into numeric IDs',()=>{expect(managerOrderNumber('branch-A_1')).toBe('branch-A_1');for(const id of [' ../x','a/b','x'.repeat(33),0,null])expect(()=>managerOrderNumber(id)).toThrow();});
 it('validates real dates periods and strict daily fields',()=>{expect(parseManagerListQuery({store_id:'77',data:'2026/10/01-2026/10/03'}).start).toBeGreaterThan(0);for(const data of ['2026/02/30-2026/03/01','2026/10/03-2026/10/01','garbage'])expect(()=>parseManagerListQuery({store_id:'77',data})).toThrow();for(const type of ['2','31','0'])expect(()=>parseManagerPeriodQuery({store_id:'77',type})).toThrow();expect(()=>parseManagerDailyQuery({store_id:'77',offset:'0'})).toThrow();});
});
