import { afterAll,afterEach,beforeAll,beforeEach,describe,it,expect,vi } from 'vitest';
import { Hono } from 'hono';
import type { AppVariables,Env } from '../src/env';
import { authMiddleware } from '../src/middleware/auth';
import { createToken,md5 } from '../src/utils/jwt';
import * as StoreManagerOrderController from '../src/controllers/api/v1/StoreManagerOrderController';
import { eq,sql } from 'drizzle-orm';
import { createContainerFromDb,withTx } from '../src/lib/di';
import { systemStoreStaff,user,storeOrder,storeOrderRefund,storeOrderCartInfo,storeProductLog,storeConfig,expressCompany,systemDise } from '../src/models/schema';
import { storeManagerOrderFixture,managerReadNow,managerReadEnv,observeManagerReadDb } from './helpers/storeManagerOrderFixture';
import { StoreManagerOrderReadService } from '../src/services/store/StoreManagerOrderReadService';
import { StoreManagerOrderStatisticsService } from '../src/services/store/StoreManagerOrderStatisticsService';
import { requireStoreManagerScope,merchantOrderRevision } from '../src/services/store/StoreManagerScope';
import { inspectManagerScopeLock,managerScopeLockReadiness,acquireManagerCarrierLock } from '../src/migrations/runManagerScopeLock';
import { userCenterDesignFixture } from './helpers/userCenterDesignFixture';
import { REGISTERED_PAGE_ROUTES,LEGACY_ROUTE_RULES } from '../src/services/content/FabRouteRegistry';
const query={store_id:'77'};
describe.runIf(Boolean(process.env.TEST_FINANCE_POSTGRES_URL))('native merchant manager complete scoped readers',()=>{
 let f:Awaited<ReturnType<typeof storeManagerOrderFixture>>,fetchGuard:ReturnType<typeof vi.spyOn>;
 beforeAll(async()=>{f=await storeManagerOrderFixture();},60000);
 beforeEach(async()=>{await f.reset();fetchGuard=vi.spyOn(globalThis,'fetch').mockRejectedValue(Error('No unapproved manager provider I/O'));},30000);
 afterEach(()=>{try{expect(fetchGuard).not.toHaveBeenCalled();}finally{fetchGuard.mockRestore();}});
 afterAll(async()=>{await f?.close();},30000);
 const app=(run:(peer:Parameters<Parameters<typeof f.withRuntimeRole>[0]>[0])=>Promise<void>)=>f.withRuntimeRole(async peer=>{await f.installReadSlice(peer);await run(peer);});
 it('lists every unique current managed store and requires explicit context for multiple stores',async()=>{await f.db.insert(systemStoreStaff).values({id:202,uid:201,storeId:78,status:1,isDel:0,isAdmin:1,orderStatus:1});await app(async peer=>{const service=f.statisticsFor(peer.db),unselected=await service.context(201,{});expect(unselected.data).toMatchObject({stores:[{store_id:77},{store_id:78}],selected_store_id:null});expect(unselected.data.capabilities.remark).toBe(false);expect((await service.context(201,query)).data.selected_store_id).toBe(77);await expect(service.statistics(201,{})).rejects.toThrow();await expect(service.context(201,{store_id:'999'})).rejects.toThrow();});});
 it('rejects disabled deleted soft deleted manager and writeoff-only or order-disabled staff',async()=>{await app(async peer=>{for(const patch of [{status:0},{isDel:1},{deleteTime:new Date()}]){await f.db.update(user).set({status:1,isDel:0,deleteTime:null,...patch}).where(eq(user.uid,201));await expect(f.statisticsFor(peer.db).statistics(201,query)).rejects.toThrow();}await f.db.update(user).set({status:1,isDel:0,deleteTime:null}).where(eq(user.uid,201));for(const patch of [{isManager:0,isAdmin:0,verifyStatus:1},{orderStatus:0},{status:0},{isDel:1}]){await f.db.update(systemStoreStaff).set({isManager:1,isAdmin:0,orderStatus:1,status:1,isDel:0,...patch}).where(eq(systemStoreStaff.id,201));await expect(f.readFor(peer.db).detail(201,'managed-1',query)).rejects.toThrow();}});});
 it('excludes duplicate active manager identity without losing another uniquely authorized store',async()=>{await f.db.insert(systemStoreStaff).values([{id:202,uid:201,storeId:77,status:1,isDel:0,isAdmin:1,orderStatus:1},{id:203,uid:201,storeId:78,status:1,isDel:0,isAdmin:1,orderStatus:1}]);await app(async peer=>{const context=await f.statisticsFor(peer.db).context(201,{});expect(context.data.stores.map(row=>row.store_id)).toEqual([78]);expect(context.issues).toContain('merchant_store_77_duplicate_identity');await expect(f.readFor(peer.db).list(201,query)).rejects.toThrow('重复');});});
 it('counts fulfillment pid zero and positive children exactly once while excluding payment heads other stores and system deleted orders',async()=>{await f.db.insert(storeOrder).values([f.order(2,{pid:1,payPrice:'20.50'}),f.order(3,{pid:-1,payPrice:'32.84'}),f.order(4,{storeId:78,payPrice:'999.00'}),f.order(5,{isSystemDel:1,payPrice:'999.00'}),f.order(6,{paid:0,payPrice:'90.00'})]);await app(async peer=>{const read=await f.statisticsFor(peer.db).statistics(201,query,managerReadNow);expect(read.data).toMatchObject({order_count:3,sum_price:'32.84',unpaid_count:1,unshipped_count:2,todayPrice:'32.84',todayCount:2,metric_scope:'current_store_fulfillments_pid_gte_0'});});});
 const selectorRows=[
  {id:10,paid:0,status:0,refundStatus:0,shippingType:1},
  {id:11,paid:1,status:0,refundStatus:0,shippingType:1},
  {id:12,paid:1,status:4,refundStatus:3,shippingType:3},
  {id:13,paid:1,status:4,refundStatus:0,shippingType:4},
  {id:14,paid:1,status:1,refundStatus:0,shippingType:1},
  {id:15,paid:1,status:5,refundStatus:3,shippingType:1},
  {id:16,paid:1,status:0,refundStatus:0,shippingType:2},
  {id:17,paid:1,status:5,refundStatus:0,shippingType:2},
  {id:18,paid:1,status:2,refundStatus:0,shippingType:1},
  {id:19,paid:1,status:2,refundStatus:3,shippingType:2},
  {id:20,paid:1,status:3,refundStatus:0,shippingType:1},
  {id:21,paid:1,status:1,refundStatus:0,shippingType:2},
  {id:22,paid:1,status:1,refundStatus:1,shippingType:1,pid:-1},
  {id:23,paid:1,status:1,refundStatus:4,shippingType:1,pid:1},
  {id:24,paid:1,status:1,refundStatus:2,shippingType:1,pid:0},
  {id:25,paid:1,status:1,refundStatus:0,shippingType:1,isDel:1},
 ];
 const cases:Array<[string,number[]]>=[['',[10,11,12,13,14,15,16,17,18,19,20,21,23,24]],['0',[10]],['1',[11,12]],['2',[14,15,16,17]],['3',[18,19]],['4',[20]],['5',[16,17,21]],['6',[19]],['7',[12,13]],['8',[16,17,19,21]],['9',[18,19,20]],['-1',[22,23]],['-2',[24]],['-3',[22,23,24]],['-4',[25]]];
 it.each(cases)('executes legacy selector %s with real shipping refund paid deletion and parent predicates',async(status,expected)=>{await f.db.delete(storeOrderCartInfo);await f.db.delete(storeOrder);await f.db.insert(storeOrder).values(selectorRows.map(row=>f.order(row.id,row)));await f.db.insert(storeOrder).values(f.order(90,{uid:203,storeId:78,status:0,payPrice:'999.00'}));await app(async peer=>{const data=(await f.readFor(peer.db).list(201,{...query,status,limit:'100',...(status==='-4'?{is_del:'1'}:{})})).data;expect(data.list.map(row=>row.id).sort((a,b)=>a-b)).toEqual(expected);expect(data.count).toBe(expected.length);expect(JSON.stringify(data)).not.toContain('999.00');});});
 it('filters all actual order types payment selectors and shipping type shortcuts without implicit regular order restriction',async()=>{await f.db.delete(storeOrderCartInfo);await f.db.delete(storeOrder);await f.db.insert(storeOrder).values([f.order(10,{type:6,payType:'offline',shippingType:1}),f.order(11,{type:1,payType:'weixin',shippingType:2}),f.order(12,{type:7,payType:'integral',shippingType:4}),f.order(13,{type:3,payType:'alipay',shippingType:3})]);await app(async peer=>{const r=f.readFor(peer.db);expect((await r.list(201,{...query,type:'6',pay_type:'3'})).data.list.map(row=>row.id)).toEqual([10]);expect((await r.list(201,{...query,type:'105'})).data.list.map(row=>row.id)).toEqual([11]);expect((await r.list(201,{...query,type:'106'})).data.list.map(row=>row.id)).toEqual([12]);expect((await r.list(201,{...query,type:'107'})).data.list.map(row=>row.id).sort()).toEqual([10,13]);});});
 it('keeps deterministic page boundaries counts keyword escaping and owner scoped product and customer search',async()=>{await f.db.insert(storeOrder).values([f.order(2),f.order(3,{storeId:78,userPhone:'13900000202',payPrice:'999.00'}),f.order(4,{realName:'literal%name'})]);await f.db.insert(storeOrderCartInfo).values(f.cart(2));await app(async peer=>{const r=f.readFor(peer.db),first=await r.list(201,{...query,page:'1',limit:'1'}),second=await r.list(201,{...query,page:'2',limit:'1'});expect(first.data).toMatchObject({count:3,has_more:true});expect(first.data.list[0].id).toBe(4);expect(second.data.list[0].id).toBe(2);expect((await r.list(201,{...query,keyword:'搜索商品',field_key:'title'})).data.list.map(row=>row.id)).toEqual([2,1]);expect((await r.list(201,{...query,keyword:'%'})).data.list.map(row=>row.id)).toEqual([4]);expect((await r.list(201,{...query,keyword:'实际客户'})).data.count).toBe(3);await expect(r.list(201,{...query,field_key:'uid',keyword:'2147483648'})).rejects.toThrow();});});
 it('projects exact detail amounts customer membership gifts reasons owned signed media and no wallet password or foreign images',async()=>{await f.db.update(storeOrder).set({refundReasonWap:'损坏',refundReasonWapExplain:'真实原因',refundReasonTime:managerReadNow,refundReasonWapImg:JSON.stringify(['/api/assets/51','/api/assets/52']),customForm:'{"收件要求":"轻放"}',giveIntegral:3}).where(eq(storeOrder.id,1));await f.db.insert(storeOrderRefund).values({id:1,storeOrderId:1,storeId:77,uid:202,supplierId:0,orderId:'refund-1',refundGoodsImg:'["/api/assets/51"]',refundPrice:'1.00'});await app(async peer=>{const detail=(await f.readFor(peer.db).detail(201,'managed-1',query)).data;expect(detail).toMatchObject({id:1,store_id:77,pay_price:'12.34',customer:{uid:202,level_name:'真实等级',vip_discount:'88.00'},refund_reason_wap:'损坏',refund_reason_wap_explain:'真实原因',custom_form:{收件要求:'轻放'},give_integral:3});expect(detail.customer.avatar).toMatch(/^\/api\/assets\/51\?/);expect(detail.cartInfo[0].productInfo.image).toMatch(/^\/api\/assets\/41\?/);expect(detail.refund_img[0]).toMatch(/^\/api\/assets\/51\?/);expect(detail.refund_img[1]).toBe('');expect(detail.refund_goods_img[0]).toMatch(/^\/api\/assets\/51\?/);expect(detail.revision).toMatch(/^[a-f0-9]{64}$/);expect(JSON.stringify(detail)).not.toMatch(/pwd|now_money|PRIVATE|202\.00/);});});
 it('rejects duplicate business numbers foreign orders corrupt cart owner and excessive historical JSON without revealing them',async()=>{await app(async peer=>{const r=f.readFor(peer.db);await f.db.insert(storeOrder).values(f.order(2,{storeId:78,uid:203,orderId:'foreign-2'}));await expect(r.detail(201,'foreign-2',query)).rejects.toThrow();await expect(f.db.insert(storeOrder).values(f.order(3,{orderId:'managed-1'}))).rejects.toThrow();await f.db.update(storeOrderCartInfo).set({uid:203}).where(eq(storeOrderCartInfo.id,1));await expect(r.detail(201,'managed-1',query)).rejects.toThrow('关联');await f.db.update(storeOrderCartInfo).set({uid:202,cartInfo:'x'.repeat(65537)}).where(eq(storeOrderCartInfo.id,1));await expect(r.detail(201,'managed-1',query)).rejects.toThrow('容量');});});
 it('returns true day period chart zero filling daily pagination and visits from actual owned store product relationships',async()=>{await f.db.insert(storeOrder).values([f.order(2,{addTime:managerReadNow-86400,payPrice:'6.17'}),f.order(3,{storeId:78,payPrice:'999.00'}),f.order(4,{pid:-1,payPrice:'999.00'})]);await f.db.insert(storeProductLog).values([{productId:201,type:'visit',addTime:managerReadNow},{productId:202,type:'visit',addTime:managerReadNow},{productId:201,type:'visit',addTime:managerReadNow-86400},{productId:201,type:'cart',addTime:managerReadNow},{productId:201,type:'visit',addTime:managerReadNow,deleteTime:new Date()}]);await app(async peer=>{const s=f.statisticsFor(peer.db),time=await s.time(201,{...query,type:'1'},managerReadNow),chart=await s.chart(201,{...query,type:'1'},managerReadNow),daily=await s.daily(201,{...query,start:String(managerReadNow-2*86400-4*3600),stop:String(managerReadNow),page:'1',limit:'1'},managerReadNow);expect(time.data).toMatchObject({after_price:'12.34',after_number:1,after_pay_number:1,today_visits:1,increase_time:'6.17',growth_rate:100});expect(chart.data).toEqual([{date:'2026-10-02',time:'10-02',num:1,price:'6.17'},{date:'2026-10-03',time:'10-03',num:1,price:'12.34'}]);expect(daily.data).toMatchObject({count:2,page:1,limit:1,has_more:true,list:[{date:'2026-10-03',price:'12.34',count:1,visit:1}]});for(const type of ['7','30'])expect((await s.chart(201,{...query,type},managerReadNow)).data.length).toBe(Number(type));});});
 it('keeps every reader read only in one repeatable snapshot and leaves all business and financial rows unchanged',async()=>{await app(async peer=>{const before=await f.snapshot(),commands:string[]=[],db=observeManagerReadDb(peer.db,async(tx,command)=>{commands.push(command);if(command.includes('SET TRANSACTION'))expect((await tx.execute<{ro:string;iso:string}>(sql`SELECT current_setting('transaction_read_only') AS ro,current_setting('transaction_isolation') AS iso`))[0]).toMatchObject({ro:'on',iso:'repeatable read'});}),r=new StoreManagerOrderReadService(createContainerFromDb(db),managerReadEnv),s=new StoreManagerOrderStatisticsService(createContainerFromDb(db));await s.context(201,query);await s.statistics(201,query,managerReadNow);await s.time(201,{...query,type:'1'},managerReadNow);await s.chart(201,{...query,type:'1'},managerReadNow);await s.daily(201,query,managerReadNow);await r.list(201,query);await r.detail(201,'managed-1',query);expect(commands.filter(c=>/SET TRANSACTION/.test(c))).toHaveLength(7);expect(commands.filter(c=>/^(INSERT|UPDATE|DELETE|MERGE)/i.test(c.trim()))).toEqual([]);expect(await f.snapshot()).toEqual(before);});});
 it('fences common reader authority across middleware bookkeeping signed URLs and real role order or media changes',async()=>{await app(async peer=>{const s=f.statisticsFor(peer.db),r=f.readFor(peer.db),context=await s.context(201,query),list=await r.list(201,query),detail=await r.detail(201,'managed-1',query);expect(context.consistency_key).toBe(list.consistency_key);expect(detail.consistency_key).toBe(list.consistency_key);await f.db.update(user).set({lastTime:managerReadNow+1}).where(eq(user.uid,201));expect((await r.list(201,query)).consistency_key).toBe(list.consistency_key);await f.db.update(storeOrder).set({remark:'真实变化'}).where(eq(storeOrder.id,1));const changed=await r.list(201,query);expect(changed.scope_key).toBe(list.scope_key);expect(changed.consistency_key).not.toBe(list.consistency_key);expect(changed.data.list[0].revision).not.toBe(detail.data.revision);await f.db.update(systemStoreStaff).set({isAdmin:1}).where(eq(systemStoreStaff.id,201));expect((await s.context(201,query)).scope_key).not.toBe(list.scope_key);});});
 it('uses the original snapshot while a peer changes order amount and manager status midway through real SQL',async()=>{await app(async peer=>{let changed=false;const db=observeManagerReadDb(peer.db,async(_tx,command)=>{if(!changed&&command.includes('from "user"')){changed=true;await f.db.update(storeOrder).set({payPrice:'99.00'}).where(eq(storeOrder.id,1));await f.db.update(systemStoreStaff).set({status:0}).where(eq(systemStoreStaff.id,201));}}),s=new StoreManagerOrderStatisticsService(createContainerFromDb(db));expect((await s.statistics(201,query,managerReadNow)).data.sum_price).toBe('12.34');expect(changed).toBe(true);await expect(f.statisticsFor(peer.db).statistics(201,query,managerReadNow)).rejects.toThrow();});});
 it('reads actual shipment gain carriers delivery agents defaults and remaining split carts within the same scope',async()=>{await f.db.insert(storeConfig).values({type:1,relationId:77,keyName:'store_config_export_to_name',value:'"真实寄件人"'});await app(async peer=>{const r=f.readFor(peer.db);expect((await r.deliveryGain(201,'managed-1',query)).data).toMatchObject({id:1,order_id:'managed-1',user_address:'真实地址'});expect((await r.carriers(201,query)).data).toEqual([{id:51,name:'真实快递',code:'actual'}]);expect((await r.deliveryAgents(201,query)).data).toEqual([{uid:204,nickname:'真实配送员',phone:'13800000204'}]);expect((await r.deliveryDefaults(201,query)).data.to_name).toBe('真实寄件人');expect((await r.splitCartInfo(201,1,query)).data.map(row=>row.cart_id)).toEqual(['cart-1']);});});
 it('queries real scoped shipment tracking without fabricating carrier events and denies foreign or revoked roles before provider I/O',async()=>{await f.db.update(storeOrder).set({status:1,deliveryType:'express',deliveryName:'真实快递',deliveryCode:'actual',deliveryId:'TRACK-123'}).where(eq(storeOrder.id,1));await app(async peer=>{const r=f.readFor(peer.db),result=await r.express(201,'managed-1',query);expect(result.data).toMatchObject({trackingState:'not_configured',trackingSource:'merchant',express:[],order:{order_id:'managed-1',delivery_id:'TRACK-123'}});await f.db.update(systemStoreStaff).set({status:0}).where(eq(systemStoreStaff.id,201));await expect(r.express(201,'managed-1',query)).rejects.toThrow();});});
 it('subtracts the real cart SVIP discount from detail product total with exact cents and rejects an impossible historic discount',async()=>{const cart=JSON.parse(f.cart(1).cartInfo!);cart.vip_truePrice='2.34';await f.db.update(storeOrderCartInfo).set({cartInfo:JSON.stringify(cart)}).where(eq(storeOrderCartInfo.oid,1));await app(async peer=>{expect((await f.readFor(peer.db).detail(201,'managed-1',query)).data).toMatchObject({total_price:'10.00',vip_true_price:'2.34',pay_price:'12.34'});cart.vip_truePrice='13.00';await f.db.update(storeOrderCartInfo).set({cartInfo:JSON.stringify(cart)}).where(eq(storeOrderCartInfo.oid,1));await expect(f.readFor(peer.db).detail(201,'managed-1',query)).rejects.toThrow('会员优惠');});});
 it('rejects selected or remaining refund generation markers without real durable evidence and never falls back to a manufactured refund history',async()=>{const snapshot=JSON.parse(f.cart(1).cartInfo!);await app(async peer=>{for(const role of ['selected','remaining']){snapshot.financial_version='refund-order-line-finance-v1';snapshot.refund_order_generation={refundId:501,role};await f.db.update(storeOrderCartInfo).set({cartInfo:JSON.stringify(snapshot)}).where(eq(storeOrderCartInfo.oid,1));await expect(f.readFor(peer.db).detail(201,'managed-1',query)).rejects.toThrow('证据');await expect(f.readFor(peer.db).list(201,query)).rejects.toThrow('证据');}expect(await f.db.select().from(storeOrderRefund)).toEqual([]);});});
 it('keeps six merchant pages scoped separately from customer work aliases and revokes direct manager menu targets',async()=>{const own=await userCenterDesignFixture();try{for(const page of ['statistics','orders','orderDetail','delivery','refund','logistics'])expect(REGISTERED_PAGE_ROUTES.has('/pages/merchant/'+page)).toBe(true);expect(LEGACY_ROUTE_RULES['/pages/admin/orderList/index']).toMatchObject({target:'/pages/customer-work/orders',queryAliases:{types:'status'},coverage:'partial_replacement'});const[row]=await own.db.select().from(systemDise).where(eq(systemDise.id,88)),value=JSON.parse(row.value!);for(const module of ['poster','menu','merMenu'])value[module].list=[{name:'真实经营入口',pic:'/api/assets/41',url:'/pages/admin/order/index',...(module==='poster'?{}:{type:module==='menu'?1:2})}];await own.db.update(systemDise).set({value:JSON.stringify(value)}).where(eq(systemDise.id,88));await own.withRuntimeRole(async peer=>{await own.installSelectSlice(peer,'app');const svc=own.publicFor(peer.db),phone=await svc.menu(11);expect(phone.capabilities).toMatchObject({merchant:true,work:false});for(const module of ['poster','menu','merMenu'] as const)expect(phone.diy_data[module].list).toHaveLength(0);for(const module of ['poster','menu','merMenu'])value[module].list[0].url='/pages/merchant/statistics';await own.db.update(systemDise).set({value:JSON.stringify(value)}).where(eq(systemDise.id,88));const read=await svc.menu(11);expect(read.capabilities.merchant).toBe(true);for(const module of ['poster','menu','merMenu'] as const)expect(read.diy_data[module].list).toHaveLength(1);expect((await svc.data(11)).order).toMatchObject({user_order:true,price:'21.00',num:1});await own.db.update(systemStoreStaff).set({orderStatus:0}).where(eq(systemStoreStaff.uid,11));const revoked=await svc.menu(11);expect(revoked.capabilities.merchant).toBe(false);for(const module of ['poster','menu','merMenu'] as const)expect(revoked.diy_data[module].list).toHaveLength(0);expect((await svc.data(11)).order).toEqual({user_order:false});});}finally{await own.close();}},60000);
 it('serves signed user JWT read handlers with private HTTP envelopes and one consistency key while rejecting guest Admin or forged scope queries',async()=>{await app(async peer=>{const http=new Hono<{Bindings:Env;Variables:AppVariables}>();http.use('*',async(c,next)=>{c.set('container',createContainerFromDb(peer.db));await next();});http.use('*',authMiddleware({force:true}));http.onError((error,c)=>c.json({error:error.message},400));http.get('/context',StoreManagerOrderController.context);http.get('/statistics',StoreManagerOrderController.statistics);http.get('/time',StoreManagerOrderController.time);http.get('/chart',StoreManagerOrderController.chart);http.get('/data',StoreManagerOrderController.daily);http.get('/list',StoreManagerOrderController.list);http.get('/detail/:id',StoreManagerOrderController.detail);const userToken=(await createToken(201,'api',md5('owned-manager-password'),managerReadEnv.APP_KEY)).token,adminToken=(await createToken(201,'admin',md5('owned-manager-password'),managerReadEnv.APP_KEY)).token,keys:string[]=[];for(const route of ['/context','/statistics','/time','/chart','/data','/list','/detail/managed-1']){const response=await http.request(route+'?store_id=77',{headers:{Authorization:`Bearer ${userToken}`}},managerReadEnv),body=await response.json() as {status:number;data:{actor_uid:number;store_id:number;consistency_key:string}};expect(response.headers.get('Cache-Control')).toBe('private, no-store');expect(body).toMatchObject({status:200,data:{actor_uid:201,store_id:77}});keys.push(body.data.consistency_key);}expect(new Set(keys).size).toBe(1);expect((await http.request('/context',{},managerReadEnv)).status).toBe(400);expect((await http.request('/context',{headers:{Authorization:`Bearer ${adminToken}`}},managerReadEnv)).status).toBe(400);expect((await http.request('/list?store_id=77&uid=203',{headers:{Authorization:`Bearer ${userToken}`}},managerReadEnv)).status).toBe(400);await f.db.update(user).set({status:0}).where(eq(user.uid,201));expect((await http.request('/context?store_id=77',{headers:{Authorization:`Bearer ${userToken}`}},managerReadEnv)).status).toBe(400);});});
 it('verifies exact lock-only catalog and refuses owner or missing function grants without changing any grants',async()=>{expect(await inspectManagerScopeLock(f.db)).toMatchObject({tablesSafe:true,absent:false,definitionSafe:true,ownerSafe:true,aclSafe:true});expect((await managerScopeLockReadiness(f.db)).ready).toBe(false);await app(async peer=>{expect((await managerScopeLockReadiness(peer.db)).ready).toBe(true);await f.exec(`REVOKE EXECUTE ON FUNCTION public.manager_lock_carrier_v1(text) FROM "${peer.role}"`);expect((await managerScopeLockReadiness(peer.db)).ready).toBe(false);});});
 it('rejects repeatable read role checks and prevents duplicate manager inserts and carrier edits with NOWAIT locks',async()=>{await f.withRuntimeRole(async peer=>{await f.installLockSlice(peer);await expect(withTx(createContainerFromDb(peer.db),async tx=>{await tx.execute(sql`SET TRANSACTION ISOLATION LEVEL REPEATABLE READ`);await requireStoreManagerScope(tx,201,77,{lock:true});})).rejects.toThrow('READ COMMITTED');await withTx(createContainerFromDb(peer.db),async tx=>{await requireStoreManagerScope(tx,201,77,{lock:true});await f.withPeer!(async other=>{await expect(other.db.transaction(async t=>{await t.execute(sql`SET LOCAL lock_timeout='100ms'`);await t.insert(systemStoreStaff).values({uid:201,storeId:77,status:1,isManager:1,orderStatus:1});})).rejects.toThrow();});await acquireManagerCarrierLock(tx,'actual');await f.withPeer!(async other=>{await expect(other.db.transaction(async t=>{await t.execute(sql`SET LOCAL lock_timeout='100ms'`);await t.update(expressCompany).set({status:0}).where(eq(expressCompany.id,51));})).rejects.toThrow();});});const[order]=await f.db.select().from(storeOrder).where(eq(storeOrder.id,1));expect(await merchantOrderRevision(order)).toMatch(/^[a-f0-9]{64}$/);});});
});
