import{afterEach,beforeEach,describe,it,expect,vi}from'vitest';
import{eq}from'drizzle-orm';
import{user}from'../src/models/schema';
import{userCenterDesignFixture}from'./helpers/userCenterDesignFixture';
import type{PaymentCodeStore}from'../src/services/user/UserProfileService';
describe.runIf(Boolean(process.env.TEST_FINANCE_POSTGRES_URL))('native membership-code actor and expiry boundary',()=>{
 let f:Awaited<ReturnType<typeof userCenterDesignFixture>>;
 beforeEach(async()=>{f=await userCenterDesignFixture();},30000);afterEach(async()=>{vi.useRealTimers();await f?.close();},30000);
 const read=(run:(app:any)=>Promise<void>)=>f.withRuntimeRole(async app=>{await f.installSelectSlice(app,'app');await run(app);});
 it('reports actual remaining provider TTL for an existing six-digit code and never extends it on repeated reads',async()=>{await read(async app=>{const createdAt=Date.now(),values=new Map<string,{code:string;expires:number}>(),store:PaymentCodeStore={get:async key=>{const value=values.get(key);return value&&value.expires>Date.now()?value.code:null;},putIfAbsent:async(key,code,seconds)=>{if(values.has(key))return false;values.set(key,{code,expires:createdAt+seconds*1000});return true;},ttl:async key=>Math.floor((values.get(key)!.expires-Date.now())/1000)},service=f.codeFor(store,app.db);vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(createdAt);const first=await service.paymentCodeSnapshot(11);expect(first).toMatchObject({actor_uid:11,expires_at:Math.floor(createdAt/1000)+600,code:expect.stringMatching(/^\d{6}$/)});vi.setSystemTime(createdAt+240000);const second=await service.paymentCodeSnapshot(11);expect(second).toEqual(first);vi.setSystemTime(createdAt+601000);await expect(service.paymentCodeSnapshot(11)).rejects.toThrow();});});
 it('refuses unknown stale or nonexpiring provider evidence without fabricated expiry',async()=>{await read(async app=>{for(const ttl of[-1,0,601,NaN]){const service=f.codeFor({get:async()=> '123456',putIfAbsent:async()=>false,ttl:async()=>ttl},app.db);await expect(service.paymentCodeSnapshot(11)).rejects.toThrow('已失效');}await expect(f.codeFor({get:async()=> '123456',putIfAbsent:async()=>false},app.db).paymentCodeSnapshot(11)).rejects.toThrow('不可核验');});});
 it('rejects anonymous disabled deleted and account revocation during provider I/O',async()=>{await read(async app=>{let reads=0;const store:PaymentCodeStore={get:async()=>{reads++;if(reads===1)await f.db.update(user).set({status:0}).where(eq(user.uid,11));return'123456';},putIfAbsent:async()=>false,ttl:async()=>180};await expect(f.codeFor(store,app.db).paymentCodeSnapshot(11)).rejects.toThrow('请重新登录');for(const patch of[{status:0},{isDel:1},{deleteTime:new Date()}]){await f.db.update(user).set({status:1,isDel:0,deleteTime:null,...patch}).where(eq(user.uid,11));await expect(f.codeFor(store,app.db).paymentCodeSnapshot(11)).rejects.toThrow('请重新登录');}await expect(f.codeFor(store,app.db).paymentCodeSnapshot(0)).rejects.toThrow();});});
});
