import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const workerSource = readFileSync(
  "test/integration/UserCenterCompatibilityAuditWorker.ts",
  "utf8",
);
const scenarioSource = readFileSync(
  "test/integration/UserCenterCompatibilityScenario.ts",
  "utf8",
);

describe("USER-CENTER-COMPAT isolated PostgreSQL scenario", () => {
  it("exposes only a token-protected audit endpoint and keeps client errors generic", () => {
    expect(workerSource).toContain('"/isolated-user-center"');
    expect(workerSource).toContain("await authorize(request, env.AUDIT_TOKEN_SHA256)");
    expect(workerSource).toContain("runUserCenterCompatibilityScenario(");
    expect(workerSource).toContain('Response.json({ error: "audit failed" }, { status: 500 })');
    expect(workerSource).not.toContain("Response.json({ error: message");
  });

  it("clones only the minimum public tables and replaces copied serial defaults", () => {
    const requiredTables = [
      "city_area",
      "store_product",
      "store_product_log",
      "store_product_relation",
      "store_promotions",
      "system_config",
      "system_sign_reward",
      "user",
      "user_address",
      "user_bill",
      "user_relation",
      "user_sign",
      "video",
    ];
    for (const table of requiredTables) {
      expect(scenarioSource).toContain(`name: "${table}"`);
    }
    expect(scenarioSource).toContain("LIKE public.${table} INCLUDING ALL");
    expect(scenarioSource).toContain("DROP IDENTITY IF EXISTS");
    expect(scenarioSource).toContain("ALTER COLUMN ${identityColumn} DROP DEFAULT");
    expect(scenarioSource).toContain("ADD GENERATED BY DEFAULT AS IDENTITY");
    expect(scenarioSource).toContain("USER_CENTER_COMPATIBILITY_INDEX_SQL");
  });

  it("pins every top-level transaction without relying on Hyperdrive startup options", () => {
    expect(scenarioSource).toContain("crypto.randomUUID()");
    expect(scenarioSource).toContain("createDbFromConnectionString(connectionString, 5");
    expect(scenarioSource).not.toContain("searchPath: schemaName");
    expect(scenarioSource).toContain("async function withIsolatedTransaction<T>(");
    expect(scenarioSource).toContain("SET LOCAL search_path TO ${schema}");
    expect(scenarioSource).toContain("current_schema() AS schema_name");
    expect(scenarioSource).toContain("transaction search_path was not pinned");
    expect(scenarioSource).not.toMatch(/\bdb\.(?:select|insert|update|delete|execute)\b/);
    expect(scenarioSource).not.toContain("createContainerFromDb(db)");
    expect(scenarioSource).toContain("await dropIsolatedSchema(admin, schemaName)");
    expect(scenarioSource).toContain("DROP SCHEMA IF EXISTS ${schema} CASCADE");
  });

  it("calls actual address, collection, and sign services with concurrency checks", () => {
    for (const service of [
      "new UserCenterService(",
      "new UserCollectCompatibilityService(",
      "new UserSignCompatibilityService(",
    ]) {
      expect(scenarioSource).toContain(service);
    }
    expect(scenarioSource).toContain("service.addressDetail(910_002, first)");
    expect(scenarioSource).toContain("service.addressSetDefault(910_002, first)");
    expect(scenarioSource).toContain("cityId: 920_002");
    expect(scenarioSource).toContain("useService((service) => service.addressSetDefault");
    expect(scenarioSource).toContain("useCenter((service) => service.collectAdd(910_001, [930_001, 930_002]");
    expect(scenarioSource).toContain("useCenter((service) => service.collectAdd(910_001, [940_001], \"video\")");
    expect(scenarioSource).toContain("useCenter((service) => service.sign(910_001))");
    expect(scenarioSource).toContain("database Shanghai-day sign uniqueness");
    expect(scenarioSource).toContain("alternateSameDayTime");
    expect(scenarioSource).toContain("Each branch owns a distinct top-level transaction/connection");
  });

  it("verifies public all-row fingerprints and temporary-schema counts after cleanup", () => {
    expect(scenarioSource).toContain("md5(to_jsonb(source_row)::text)");
    expect(scenarioSource).toContain("COUNT(*)::text AS row_count");
    expect(scenarioSource).toContain("starts_with(nspname, ${SCHEMA_PREFIX})");
    expect(scenarioSource).toContain("sameFingerprints(before.publicTables, after.publicTables)");
    expect(scenarioSource).toContain("before.temporarySchemas === after.temporarySchemas");
    expect(scenarioSource).toContain("publicRowsUnchanged: true");
    expect(scenarioSource).toContain("isolatedSchemaDropped: true");
  });
});
