import{afterEach,beforeEach,describe,it,expect,vi}from'vitest';
import{eq,sql}from'drizzle-orm';
import{createContainerFromDb}from'../src/lib/di';
import{systemDise,user,systemStoreStaff,systemStore,systemConfig,userRelation,video,deliveryService,storeProduct,storeOrder}from'../src/models/schema';
import{userCenterDesignFixture,observeUserCenterDb,userCenterEnv}from'./helpers/userCenterDesignFixture';
import{UserCenterPublicReadService}from'../src/services/content/UserCenterPublicReadService';
import{UserCollectCompatibilityService}from'../src/services/user/UserCollectCompatibilityService';
import{UserCenterService}from'../src/services/user/UserCenterService';
import{productDetailDesignFixture}from'./helpers/productDetailDesignFixture';
describe.runIf(Boolean(process.env.TEST_FINANCE_POSTGRES_URL))('native actor-safe user-center real consumption',()=>{
 let f:Awaited<ReturnType<typeof userCenterDesignFixture>>,guard:ReturnType<typeof vi.spyOn>;
 beforeEach(async()=>{f=await userCenterDesignFixture();guard=vi.spyOn(globalThis,'fetch').mockRejectedValue(Error('No user-center external HTTP'));},30000);
 afterEach(async()=>{try{expect(guard).not.toHaveBeenCalled();}finally{guard?.mockRestore();await f?.close();}},30000);
 const profile=(run:(app:any)=>Promise<void>)=>f.withRuntimeRole(async app=>{await f.installSelectSlice(app,'app');await run(app);});
 it('projects current own profile counts signed media and scoped manager statistics with no financial DML or private extensions',async()=>{await profile(async app=>{const before=await f.snapshot(),service=f.publicFor(app.db),menu=await service.menu(11),data=await service.data(11);expect(menu).toMatchObject({actor_uid:11,profile:{uid:11,nickname:'实际用户',now_money:'91.23',integral:27,couponCount:1,collectProductCount:1,collectVideoCount:1,visit_num:1,spread_user_count:1,spread_order_count:1,commissionCount:'50.00',service_num:1,level_name:'实际会员',vip_discount:'88.50'},capabilities:{merchant:true,writeoff:true,promotion:true},orderStatusNum:{order_count:2,unpaid_count:1,received_count:1}});expect(data).toMatchObject({actor_uid:11,design_revision:menu.user_center_design_state.revision,commission:{number:1,order_num:1},order:{user_order:true,price:'21.00',num:1,consignment:0},not_pay_order:{order_id:'owned-unpaid',pay_price:'10.00'}});expect(menu.diy_data.merMenu.list.map(item=>item.name)).toEqual(['核销']);expect(menu.capabilities.work).toBe(false);expect(menu.user_center_design_state.issues).not.toContain('user_center_merMenu_historical_target_partial');expect(JSON.stringify(menu)).not.toMatch(/PRIVATE|pwd|avatar_url|sourceId|foreign-paid/);expect(JSON.stringify(data)).not.toContain('999.00');expect(await f.snapshot()).toEqual(before);});});
 it('keeps anonymous explicit with no user profile or role statistics and rejects disabled deleted or soft-deleted identities',async()=>{await profile(async app=>{const menu=await f.publicFor(app.db).menu(0),data=await f.publicFor(app.db).data(0);expect(menu.profile).toBeNull();expect(menu).toMatchObject({actor_uid:0,capabilities:{merchant:false,promotion:false,writeoff:false},orderStatusNum:{order_count:0}});expect(data).toMatchObject({actor_uid:0,commission:[],order:{user_order:false},not_pay_order:null});for(const patch of[{status:0},{isDel:1},{deleteTime:new Date()}]){await f.db.update(user).set({status:1,isDel:0,deleteTime:null,...patch}).where(eq(user.uid,11));await expect(f.publicFor(app.db).menu(11)).rejects.toThrow('请重新登录');await expect(f.publicFor(app.db).data(11)).rejects.toThrow('请重新登录');}});});
 it('does not turn writeoff-only staff into manager or global customer-service statistics and applies actual business flags',async()=>{await profile(async app=>{await f.db.update(systemStoreStaff).set({isManager:0,isAdmin:0,orderStatus:0}).where(eq(systemStoreStaff.id,1));expect((await f.publicFor(app.db).menu(11)).capabilities).toMatchObject({writeoff:true,merchant:false});expect((await f.publicFor(app.db).data(11)).order).toEqual({user_order:false});await f.db.update(systemConfig).set({value:'0'}).where(eq(systemConfig.menuName,'balance_func_status'));await f.db.update(systemConfig).set({value:'0'}).where(eq(systemConfig.menuName,'brokerage_func_status'));await f.db.update(systemConfig).set({value:'0'}).where(eq(systemConfig.menuName,'video_func_status'));const menu=await f.publicFor(app.db).menu(11);expect(menu.capabilities).toMatchObject({balance:false,promotion:false,video:false});expect(menu.profile).toMatchObject({now_money:'0.00',commissionCount:'0.00',collectVideoCount:0,spread_user_count:0});expect(menu.diy_data.member.property).toEqual([1,2,3]);expect(menu.diy_data.menu.list).toEqual([]);});});
 it('uses one repeatable read for actor flags media designs and all counters while a real peer changes their live authority',async()=>{await profile(async app=>{let observed=false;const commands:string[]=[],database=observeUserCenterDb(app.db,async(tx,command)=>{commands.push(command);if(!observed&&command.includes('from "user"')){observed=true;expect((await tx.execute<{read_only:string;isolation:string}>(await import('drizzle-orm').then(({sql})=>sql`SELECT current_setting('transaction_read_only') AS read_only,current_setting('transaction_isolation') AS isolation`)))[0]).toMatchObject({read_only:'on',isolation:'repeatable read'});await f.db.update(user).set({isPromoter:0,nowMoney:'1.00'}).where(eq(user.uid,11));await f.db.update(systemConfig).set({value:'0'}).where(eq(systemConfig.menuName,'balance_func_status'));}}),service=new UserCenterPublicReadService(createContainerFromDb(database),userCenterEnv),menu=await service.menu(11);expect(observed).toBe(true);expect(menu.profile).toMatchObject({now_money:'91.23',commissionCount:'50.00'});expect(menu.capabilities.balance).toBe(true);expect(commands.filter(command=>command.includes('SET TRANSACTION'))).toHaveLength(1);expect((await f.publicFor(app.db).menu(11)).profile).toMatchObject({now_money:'0.00',commissionCount:'0.00'});});});
 it('diagnoses configured duplicate templates without publishing newest opaque settings or treating corruption as missing',async()=>{await profile(async app=>{await f.db.insert(systemDise).values({templateName:' MEMBER ',type:1,value:'{"PRIVATE":"newest"}'});const before=await f.snapshot(),menu=await f.publicFor(app.db).menu(11);expect(menu.user_center_design_state).toMatchObject({configured:true,issues:['user_center_member_duplicate']});expect(menu.diy_data.member.property).toEqual([]);expect(menu.diy_data.menu.is_show).toBe(0);expect(JSON.stringify(menu)).not.toContain('PRIVATE');expect(await f.snapshot()).toEqual(before);});});
 it('returns only own video collection with genuine available media and removable unavailable relation IDs',async()=>{await profile(async app=>{await f.db.insert(userRelation).values([{uid:11,type:'collect',category:'video',relationId:101},{uid:11,type:'collect',category:'video',relationId:999}]);const service=new UserCollectCompatibilityService(createContainerFromDb(app.db),userCenterEnv),result=await service.list(11,1,20,'video');expect(result).toMatchObject({actor_uid:11,count:3});const list=result.list;expect(list.find(item=>item.id===100)).toMatchObject({available:true,is_fail:0,video_url:'https://media.example.com/video.mp4'});expect(list.find(item=>item.id===101)).toMatchObject({available:false,is_fail:1,video_url:'',image:'',desc:'视频已不可用'});expect(list.find(item=>item.id===999)).toMatchObject({available:false,is_fail:1,video_url:''});expect(JSON.stringify(result)).not.toContain('PRIVATE');await f.db.update(video).set({isShow:0}).where(eq(video.id,100));expect((await service.list(11,1,20,'video')).list.find(item=>item.id===100)).toMatchObject({available:false,video_url:''});await f.db.update(user).set({status:0}).where(eq(user.uid,11));await expect(service.list(11,1,20,'video')).rejects.toThrow();});});
 it('filters role targets across personal menus and posters and rejects conflicting delivery identities without granting manager statistics',async()=>{await profile(async app=>{const[row]=await f.db.select().from(systemDise).where(eq(systemDise.id,88)),value=JSON.parse(row.value!);value.poster.list[0].url='/pages/admin/order_cancellation/index';value.menu.list[0].url='/pages/admin/order_cancellation/index';await f.db.update(systemDise).set({value:JSON.stringify(value)}).where(eq(systemDise.id,88));await f.db.update(systemStoreStaff).set({status:0}).where(eq(systemStoreStaff.id,1));let menu=await f.publicFor(app.db).menu(11);expect(menu.capabilities.writeoff).toBe(false);expect(menu.diy_data.poster.list).toEqual([]);expect(menu.diy_data.menu.list).toEqual([]);await f.db.insert(deliveryService).values([{uid:11,type:0,relationId:0,status:1,isDel:0,nickname:'真实配送员'}]);menu=await f.publicFor(app.db).menu(11);expect(menu.capabilities).toMatchObject({writeoff:true,merchant:false});expect(menu.diy_data.poster.list).toHaveLength(1);expect(menu.diy_data.menu.list).toHaveLength(1);await f.db.insert(deliveryService).values({uid:11,type:0,relationId:0,status:1,isDel:0,nickname:'冲突配送员'});menu=await f.publicFor(app.db).menu(11);expect(menu.operator_profile.delivery_identity_conflict).toBe(true);expect(menu.capabilities.writeoff).toBe(false);expect(menu.diy_data.poster.list).toEqual([]);expect(menu.diy_data.menu.list).toEqual([]);expect((await f.publicFor(app.db).data(11)).order).toEqual({user_order:false});});});
 it('preserves genuine concurrent video collection add and cancellation semantics without mutating another actor or financial authority',async()=>{await f.withRuntimeRole(app=>f.withRuntimeRole(admin=>f.withRuntimeRole(async peer=>{await f.installSlice(app,admin);await f.installSlice(app,peer);await f.exec("CREATE UNIQUE INDEX owned_user_relation_collect_identity ON user_relation(uid,relation_id,type,category) WHERE type <> 'play'");const left=new UserCenterService(createContainerFromDb(admin.db)),right=new UserCenterService(createContainerFromDb(peer.db)),before=await f.snapshot();await Promise.all([left.collectDel(11,[100,101,999],'video'),right.collectDel(11,[100,101,999],'video')]);expect(await left.collectList(11,'video')).toEqual([]);expect(await left.collectList(22,'video')).toEqual([101]);const adds=await Promise.all([left.collectAdd(11,[100],'video'),right.collectAdd(11,[100],'video')]);expect(adds.reduce((sum,value)=>sum+value,0)).toBe(1);expect((await new UserCollectCompatibilityService(createContainerFromDb(app.db),userCenterEnv).list(11,1,20,'video')).list[0]).toMatchObject({id:100,available:true,site_name:'积分商城'});expect((await f.db.select().from(video).where(eq(video.id,100)))[0].collectNum).toBe(1);const after=await f.snapshot();for(const name of['user','user_brokerage','user_extract','store_order','store_order_refund','store_order_cart_info'])expect(after[name]).toEqual(before[name]);})));});
 it('preserves controlled rich product collection images and leaves unavailable products removable without publishing raw media',async()=>{const products=await productDetailDesignFixture();try{await products.db.insert(userRelation).values([{uid:11,type:'collect',category:'product',relationId:70},{uid:11,type:'collect',category:'product',relationId:71}]);await products.db.update(storeProduct).set({isShow:0,image:'/api/assets/43'}).where(eq(storeProduct.id,71));await products.withRuntimeRole(async peer=>{await products.installSelectSlice(peer,'app');const before=await products.snapshot(),result=await new UserCollectCompatibilityService(createContainerFromDb(peer.db),products.env).list(11,1,20,'product');expect(result.count).toBe(2);expect(result.list.find(item=>item.id===70)).toMatchObject({image:expect.stringMatching(/^\/api\/assets\/41\?expires=/),is_fail:0});expect(result.list.find(item=>item.id===71)).toMatchObject({image:'',is_fail:1});expect(JSON.stringify(result)).not.toContain('assets/43');expect(await products.snapshot()).toEqual(before);});}finally{await products.close();}});
 it('expands the genuine pending-fulfillment selector across states refund shipping parent families and all order types without changing paid aggregates',async()=>{
  await profile(async app=>{
   const accepted:Array<typeof storeOrder.$inferInsert>=[],types=[0,1,3,4,6];let index=0;
   for(const status of[0,4])for(const refundStatus of[0,3])for(const shippingType of[1,3])for(const pid of[0,-1]){
    const id=100+index;accepted.push({id,orderId:`accepted-${id}`,unique:`accepted-${id}`,uid:11,storeId:77,paid:1,status,refundStatus,shippingType,pid,payPrice:'10.00',type:types[index++%types.length]});
   }
   const rejected:Array<{name:string;patch:Partial<typeof storeOrder.$inferInsert>}>=[
    {name:'unpaid',patch:{paid:0}},{name:'already-shipped',patch:{status:1}},{name:'received',patch:{status:2}},{name:'completed',patch:{status:3}},{name:'partially-written-off',patch:{status:5}},
    {name:'pickup',patch:{shippingType:2}},{name:'other-shipping',patch:{shippingType:4}},{name:'refund-pending',patch:{refundStatus:1}},{name:'refunded',patch:{refundStatus:2}},{name:'partial-refund',patch:{refundStatus:4}},
    {name:'user-deleted',patch:{isDel:1}},{name:'system-deleted',patch:{isSystemDel:1}},{name:'child-order',patch:{pid:17}},{name:'foreign-store',patch:{storeId:999}},
   ];
   await f.db.insert(storeOrder).values([...accepted,...rejected.map(({name,patch},offset)=>({id:200+offset,orderId:`rejected-${name}`,unique:`rejected-${name}`,uid:22,storeId:77,paid:1,status:0,refundStatus:0,shippingType:1,pid:0,payPrice:'1.00',...patch}))]);
   const before=await f.snapshot(),commands:string[]=[],db=observeUserCenterDb(app.db,async(_tx,command)=>{commands.push(command);}),service=new UserCenterPublicReadService(createContainerFromDb(db),userCenterEnv),menu=await service.menu(11),data=await service.data(11);
   // Six excluded fulfillment states still belong to the unchanged paid totals.
   expect(data.order).toEqual({user_order:true,price:'187.00',num:23,consignment:16});
   // Personal counts own current roots only; merchant statistics also count -1 roots.
   expect(menu.orderStatusNum.unshipped_count).toBe(8);
   expect(menu.consistency_key).toBe(data.consistency_key);
   expect(commands.filter(command=>/^\s*(?:insert|update|delete|merge|alter|create|drop|truncate|grant|revoke)\b/iu.test(command))).toEqual([]);
   expect(await f.snapshot()).toEqual(before);
  });
 });
 it('keeps pending-fulfillment statistics bound to unique current manager roles and visible stores rather than writeoff roles or requested ownership',async()=>{
  await profile(async app=>{
   await f.db.insert(storeOrder).values([{id:100,orderId:'manager-pending',unique:'manager-pending',uid:22,storeId:77,paid:1,status:4,shippingType:3,payPrice:'10.00'},{id:101,orderId:'foreign-pending',unique:'foreign-pending',uid:11,storeId:999,paid:1,status:0,shippingType:1,payPrice:'999.00'}]);
   const service=f.publicFor(app.db);expect((await service.data(11)).order).toEqual({user_order:true,price:'31.00',num:2,consignment:1});
   const noScope=async()=>{const before=await f.snapshot();expect((await service.data(11)).order).toEqual({user_order:false});expect((await service.menu(11)).capabilities.merchant).toBe(false);expect(await f.snapshot()).toEqual(before);};
   await f.db.update(systemStoreStaff).set({orderStatus:0}).where(eq(systemStoreStaff.id,1));await noScope();
   await f.db.update(systemStoreStaff).set({orderStatus:1,isManager:0,isAdmin:0}).where(eq(systemStoreStaff.id,1));await noScope();expect((await service.menu(11)).capabilities.writeoff).toBe(true);
   await f.db.update(systemStoreStaff).set({isManager:1}).where(eq(systemStoreStaff.id,1));
   await f.db.insert(systemStoreStaff).values({id:2,uid:11,storeId:77,status:1,isDel:0,verifyStatus:1,isManager:1,orderStatus:1});await noScope();
   await f.db.update(systemStoreStaff).set({status:0}).where(eq(systemStoreStaff.id,2));
   for(const patch of[{isShow:0},{isDel:1}]){await f.db.update(systemStore).set({isShow:1,isDel:0,...patch}).where(eq(systemStore.id,77));await noScope();}
   await f.db.update(systemStore).set({isShow:1,isDel:0}).where(eq(systemStore.id,77));
   for(const patch of[{status:0},{isDel:1},{deleteTime:new Date()}]){await f.db.update(user).set({status:1,isDel:0,deleteTime:null,...patch}).where(eq(user.uid,11));const before=await f.snapshot();await expect(service.data(11)).rejects.toThrow('请重新登录');expect(await f.snapshot()).toEqual(before);}
  });
 });
 it('keeps the fulfillment count in the actor snapshot during a real concurrent shipment and fences a later read without changing paid money or number',async()=>{
  await profile(async app=>{
   await f.db.insert(storeOrder).values({id:100,orderId:'concurrent-pending',unique:'concurrent-pending',uid:22,storeId:77,paid:1,status:4,shippingType:1,payPrice:'10.00'});
   let observed=false;const commands:string[]=[],db=observeUserCenterDb(app.db,async(tx,command)=>{commands.push(command);if(!observed&&command.includes('from "user"')){observed=true;expect((await tx.execute<{read_only:string;isolation:string}>(sql`SELECT current_setting('transaction_read_only') AS read_only,current_setting('transaction_isolation') AS isolation`))[0]).toMatchObject({read_only:'on',isolation:'repeatable read'});await f.db.update(storeOrder).set({status:1}).where(eq(storeOrder.id,100));}}),service=new UserCenterPublicReadService(createContainerFromDb(db),userCenterEnv),first=await service.data(11),later=await f.publicFor(app.db).data(11);
   expect(observed).toBe(true);expect(first.order).toEqual({user_order:true,price:'31.00',num:2,consignment:1});expect(later.order).toEqual({user_order:true,price:'31.00',num:2,consignment:0});expect(first.consistency_key).not.toBe(later.consistency_key);
   expect(commands.filter(command=>/^\s*(?:insert|update|delete|merge|alter|create|drop|truncate|grant|revoke)\b/iu.test(command))).toEqual([]);
  });
 });
});
