/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WorkerBindings` (hash: 3f58dbfce2bd9a8e64ed43e3e0cd065c)
interface __BaseEnv_WorkerBindings {
	CONFIG_KV: KVNamespace;
	ASSETS_BUCKET: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	ORDER_QUEUE: Queue;
	IMAGES: ImagesBinding;
	NODE_ENV: "production";
	INTERNAL_API_URL: "https://cinashop-api.cinagroup.workers.dev";
	ORDER_DLQ_NAME: "cinashop-order-dlq";
	OUT_API_LOGIN_LIMIT_PER_MINUTE: "10";
	OUT_API_REFRESH_LIMIT_PER_MINUTE: "30";
	OUT_API_READ_LIMIT_PER_MINUTE: "120";
	OUT_API_WRITE_LIMIT_PER_MINUTE: "30";
	ALLOWED_ORIGINS: "https://cinashop-pc.pages.dev,https://cinashop-h5.pages.dev";
	PC_AUTH_ALLOWED_ORIGINS: "https://cinashop-pc.pages.dev";
	TOKEN_BUCKET: DurableObjectNamespace<import("./src/index").TokenBucketDO>;
	ORDER_LOCK: DurableObjectNamespace<import("./src/index").OrderLockDO>;
	SEQUENCE: DurableObjectNamespace<import("./src/index").SequenceDO>;
	CHAT_ROOM: DurableObjectNamespace<import("./src/index").ChatRoomDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "TokenBucketDO" | "OrderLockDO" | "SequenceDO" | "ChatRoomDO";
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NODE_ENV" | "INTERNAL_API_URL" | "ORDER_DLQ_NAME" | "OUT_API_LOGIN_LIMIT_PER_MINUTE" | "OUT_API_REFRESH_LIMIT_PER_MINUTE" | "OUT_API_READ_LIMIT_PER_MINUTE" | "OUT_API_WRITE_LIMIT_PER_MINUTE" | "ALLOWED_ORIGINS" | "PC_AUTH_ALLOWED_ORIGINS">> {}
}
