/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=test/integration/orphan-cleanup.wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=OrphanCleanupEnv test/integration/orphan-cleanup-bindings.d.ts` (hash: d254c24a783cd4f56e602a36e0ccfed2)
interface __BaseEnv_OrphanCleanupEnv {
	HYPERDRIVE: Hyperdrive;
	AUDIT_TOKEN_SHA256: string;
	AUDIT_EXPIRES_AT: string;
	ORPHAN_BACKUP_SHA256: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./OrphanTestCleanupWorker");
	}
	interface Env extends __BaseEnv_OrphanCleanupEnv {}
}
interface OrphanCleanupEnv extends __BaseEnv_OrphanCleanupEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUDIT_TOKEN_SHA256" | "AUDIT_EXPIRES_AT" | "ORPHAN_BACKUP_SHA256">> {}
}

// Module-scoped temporary maintenance bindings.
export type { OrphanCleanupEnv };
