/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=test/integration/paid-runtime-audit.wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=PaidRuntimeAuditEnv test/integration/paid-runtime-audit-bindings.d.ts` (hash: 0f203d75a4e4a9444454cc9e6f2bf411)
interface __BaseEnv_PaidRuntimeAuditEnv {
	HYPERDRIVE: Hyperdrive;
	AUDIT_TOKEN_SHA256: string;
	AUDIT_EXPIRES_AT: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./PaidRuntimeAuditWorker");
	}
	interface Env extends __BaseEnv_PaidRuntimeAuditEnv {}
}
interface PaidRuntimeAuditEnv extends __BaseEnv_PaidRuntimeAuditEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUDIT_TOKEN_SHA256" | "AUDIT_EXPIRES_AT">> {}
}

// Module-scoped by scripts/generate-paid-runtime-audit-types.mjs.
export type { PaidRuntimeAuditEnv };
