/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=test/integration/release-protocol-schema.wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=ReleaseProtocolSchemaEnv test/integration/release-protocol-schema-bindings.d.ts` (hash: 68ff45129f1d7fab3e71d212d6a4985e)
interface __BaseEnv_ReleaseProtocolSchemaEnv {
	HYPERDRIVE: Hyperdrive;
	AUDIT_TOKEN_SHA256: string;
	AUDIT_EXPIRES_AT: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./ReleaseProtocolSchemaWorker");
	}
	interface Env extends __BaseEnv_ReleaseProtocolSchemaEnv {}
}
interface ReleaseProtocolSchemaEnv extends __BaseEnv_ReleaseProtocolSchemaEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUDIT_TOKEN_SHA256" | "AUDIT_EXPIRES_AT">> {}
}

// Module-scoped temporary maintenance bindings.
export type { ReleaseProtocolSchemaEnv };
