/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=test/integration/runtime-role-provision.wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=RuntimeRoleProvisionEnv test/integration/runtime-role-provision-bindings.d.ts` (hash: b51241ea24f71521bb61d7e68ff0dfd1)
interface __BaseEnv_RuntimeRoleProvisionEnv {
	HYPERDRIVE: Hyperdrive;
	AUDIT_TOKEN_SHA256: string;
	AUDIT_EXPIRES_AT: string;
	CREDENTIALS_BODY_SHA256: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./RuntimeRoleProvisionWorker");
	}
	interface Env extends __BaseEnv_RuntimeRoleProvisionEnv {}
}
interface RuntimeRoleProvisionEnv extends __BaseEnv_RuntimeRoleProvisionEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUDIT_TOKEN_SHA256" | "AUDIT_EXPIRES_AT" | "CREDENTIALS_BODY_SHA256">> {}
}

// Module-scoped temporary maintenance bindings.
export type { RuntimeRoleProvisionEnv };
