/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=test/integration/runtime-business-commission.wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=RuntimeBusinessCommissionBindings test/integration/runtime-business-commission-bindings.d.ts` (hash: 7b82aa4dbada71d7c685d7c46cf2f87a)
interface __BaseEnv_RuntimeBusinessCommissionBindings {
	HYPERDRIVE_MAINTENANCE: Hyperdrive;
	HYPERDRIVE: Hyperdrive;
	HYPERDRIVE_ADMIN: Hyperdrive;
	AUDIT_TOKEN_SHA256: string;
	AUDIT_EXPIRES_AT: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./RuntimeBusinessCommissionWorker");
	}
	interface Env extends __BaseEnv_RuntimeBusinessCommissionBindings {}
}
interface RuntimeBusinessCommissionBindings extends __BaseEnv_RuntimeBusinessCommissionBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUDIT_TOKEN_SHA256" | "AUDIT_EXPIRES_AT">> {}
}

// Module-scoped temporary maintenance bindings.
export type { RuntimeBusinessCommissionBindings };
