/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=test/integration/test-product-image-maintenance.wrangler.jsonc --include-runtime=false --env-interface=TestImageMaintenanceEnv test/integration/test-product-image-maintenance.env.d.ts` (hash: 8381b65b5a20b5495a04ef83a1dac8de)
interface __BaseEnv_TestImageMaintenanceEnv {
	HYPERDRIVE: Hyperdrive;
	AUDIT_TOKEN_SHA256: "disabled";
	EXPIRES_AT: "0";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./TestProductImageMaintenanceWorker");
	}
	interface Env extends __BaseEnv_TestImageMaintenanceEnv {}
}
// Module-scoped export keeps this one-off tool's ProcessEnv/Cloudflare declarations
// from augmenting the production application's globals. Reapply after regeneration.
export interface TestImageMaintenanceEnv extends __BaseEnv_TestImageMaintenanceEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUDIT_TOKEN_SHA256" | "EXPIRES_AT">> {}
}
