/** Independent ordinary-user financial wire. No Vue, storage or browser dependencies. */
import { customerWorkCanonicalJson,customerWorkSha256 } from './customerWorkIntent';
import { isUserCenterPublicImage } from './userCenterDesign';
export { customerWorkCanonicalJson } from './customerWorkIntent';
export const CUSTOMER_FINANCIAL_VERSION='customer-work-financial-operation-v1' as const;
export const CUSTOMER_FINANCIAL_KINDS=['change_price','confirm_offline','refund_create','refund_return','refund_refuse','refund_execute','refund_remark'] as const;
export type CustomerFinancialKind=typeof CUSTOMER_FINANCIAL_KINDS[number];
export const CUSTOMER_FINANCIAL_NAMES:Record<CustomerFinancialKind,string>={change_price:'修改订单价格',confirm_offline:'确认线下收款',refund_create:'创建退款申请',refund_return:'同意退货',refund_refuse:'拒绝退款申请',refund_execute:'执行资金退款',refund_remark:'修改退款备注'};
export type CustomerFinancialJson=null|boolean|number|string|CustomerFinancialJson[]|{[key:string]:CustomerFinancialJson};
export interface CustomerFinancialEnvelope<T>{version:'customer-work-read-v1';actor_uid:number;principal:{kind:'customer-order-manager';service_id:number;scope:'global'};scope_key:string;consistency_key:string;data:T}
export interface CustomerFinancialReadiness{writes:boolean;quote:boolean;reason:string;provider_max_amount:'21474836.47'}
export interface CustomerFinancialAction{available:boolean;reason:string}
export type CustomerFinancialActions=Record<CustomerFinancialKind,CustomerFinancialAction>;
export interface CustomerFinancialOrder{
 version:'customer-work-financial-order-v1';requested_order_no:string;order_id:number;order_no:string;payment_order_id:number;payment_order_no:string;
 uid:number;store_id:number;supplier_id:number;order_revision:string;financial_revision:string;paid:number;status:number;pay_type:string;pay_price:string;refunded_price:string;change_price:string;total_num:number;
 readiness:CustomerFinancialReadiness;actions:CustomerFinancialActions;
}
export interface CustomerFinancialQuoteItem{cart_row_id:number;cart_id:string;cart_num:number;max_num:number;title:string;sku:string;image:string;line_price:string}
export interface CustomerFinancialQuoteInput{version:'customer-work-financial-refund-quote-v1';scope_key:string;order_id:number;expected_order_revision:string;expected_financial_revision:string;mode:'remaining'|'items';items:Array<{cart_row_id:number;cart_num:number}>}
export interface CustomerFinancialRefundQuote{
 version:'customer-work-financial-refund-quote-v1';order_id:number;order_no:string;payment_order_id:number;order_revision:string;financial_revision:string;mode:'remaining'|'items';items:CustomerFinancialQuoteItem[];quoted_price:string;quote_fingerprint:string;refund_time_days:number;received_at:number|null;
}
export interface CustomerFinancialRefundReview{
 version:'customer-work-financial-refund-review-v1';requested_refund_no:string;refund_id:number;refund_no:string;order_id:number;order_no:string;payment_order_id:number;payment_order_no:string;uid:number;store_id:number;supplier_id:number;
 order_revision:string;financial_revision:string;refund_revision:string;review_fingerprint:string;apply_type:number;refund_type:number;refund_price:string;refunded_price:string;remark:string;requires_received_confirmation:boolean;
 return_evidence:{reason:string;explain:string;images:string[];goods_images:string[];express_name:string;express_no:string;phone:string};readiness:CustomerFinancialReadiness;actions:CustomerFinancialActions;
}
export interface CustomerFinancialInput{version:typeof CUSTOMER_FINANCIAL_VERSION;scope_key:string;order_id:number;expected_order_revision:string;expected_financial_revision:string;payload:{[key:string]:CustomerFinancialJson}}
export type CustomerFinancialOutcome='price-changed'|'offline-paid'|'refund-created'|'return-approved'|'refused'|'balance-settled'|'provider-admitted'|'refund-remark-saved'|'abandoned'|'rollback-rejected';
export interface CustomerFinancialReceipt{version:typeof CUSTOMER_FINANCIAL_VERSION;request_key:string;request_hash:string;actor_uid:number;service_id:number;order_id:number;kind:CustomerFinancialKind;outcome:CustomerFinancialOutcome;evidence:{[key:string]:CustomerFinancialJson};created_at:number}
export interface CustomerFinancialExecution{version:'customer-work-financial-execution-v1';request_key:string;request_hash:string;refund_id:number;status:'NONE'|'CREATED'|'REQUESTING'|'PROCESSING'|'SUCCESS'|'BALANCE_SUCCESS'|'CLOSED'|'ABNORMAL'|'FAILED'|'UNKNOWN';completed:boolean;verified:boolean;can_resume:boolean}
export interface CustomerFinancialResult{receipt:CustomerFinancialReceipt|null;replayed:boolean;execution:CustomerFinancialExecution|null}
export interface CustomerFinancialIntent{version:'customer-work-financial-pending-v1';actor_uid:number;service_id:number;scope_key:string;kind:CustomerFinancialKind;request_key:string;request_hash:string;order_no:string;payment_order_id:number;payment_order_no:string;body:CustomerFinancialInput;endpoint:string;method:'POST';created_at:number}

export const financialRecord=(value:unknown):value is Record<string,unknown>=>!!value&&typeof value==='object'&&!Array.isArray(value)&&[Object.prototype,null].includes(Object.getPrototypeOf(value));
export const financialKeys=(value:Record<string,unknown>,keys:readonly string[])=>Object.keys(value).sort().join(',')===[...keys].sort().join(',');
export const financialId=(value:unknown,min=1):value is number=>typeof value==='number'&&Number.isSafeInteger(value)&&value>=min&&value<=2147483647;
export const financialEpoch=(value:unknown):value is number=>typeof value==='number'&&Number.isSafeInteger(value)&&value>=0;
export const financialHash=(value:unknown):value is string=>typeof value==='string'&&/^[a-f0-9]{64}$/u.test(value);
export const financialUuid=(value:unknown):value is string=>typeof value==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/u.test(value);
export const financialNumber=(value:unknown,max=32):value is string=>typeof value==='string'&&new RegExp(`^[A-Za-z0-9_-]{1,${max}}$`,'u').test(value);
export const financialMoney=(value:unknown):value is string=>typeof value==='string'&&/^(0|[1-9]\d{0,9})\.\d{2}$/u.test(value);
export const financialSignedMoney=(value:unknown):value is string=>typeof value==='string'&&/^-?(0|[1-9]\d{0,9})\.\d{2}$/u.test(value)&&value!=='-0.00';
export const financialText=(value:unknown,max=4000,required=false):value is string=>typeof value==='string'&&Array.from(value).length<=max&&!/[\u0000-\u001f\u007f\uD800-\uDFFF]/u.test(value)&&(!required||!!value.trim());
// Historical human text may contain tabs and line breaks; write/identifier text stays strict.
export const financialDisplayText=(value:unknown,max:number):value is string=>typeof value==='string'&&Array.from(value).length<=max&&!/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f\uD800-\uDFFF]/u.test(value);
function assert(value:unknown,message:string):asserts value{if(!value)throw Error(message);}
export function financialAmount(value:string):string{const text=value.trim();assert(/^\d{1,10}(?:\.\d{1,2})?$/u.test(text),'请输入不超过十位整数、最多两位小数的金额');const [whole,fraction='']=text.split('.'),result=whole!.replace(/^0+(?=\d)/u,'')+'.'+fraction.padEnd(2,'0');assert(financialMoney(result),'金额超出支持范围');return result;}
export function financialCents(value:string):bigint{assert(financialMoney(value),'金额格式无效');return BigInt(value.replace('.',''));}
export function financialReason(value:string):string{const result=value.trim();assert(financialText(result,255,true),'请填写 1 至 255 字，内容不能含控制字符');return result;}
export const financialEndpoint=(kind:CustomerFinancialKind)=>{assert(CUSTOMER_FINANCIAL_KINDS.includes(kind),'财务操作类型无效');return'/mobile/work/financial/'+kind.replaceAll('_','-');};
export const financialIntentHash=(actor_uid:number,kind:CustomerFinancialKind,input:CustomerFinancialInput)=>customerWorkSha256(customerWorkCanonicalJson({version:CUSTOMER_FINANCIAL_VERSION,actor_uid,kind,input}));
function readiness(value:unknown):value is CustomerFinancialReadiness{return financialRecord(value)&&financialKeys(value,['writes','quote','reason','provider_max_amount'])&&typeof value.writes==='boolean'&&typeof value.quote==='boolean'&&financialText(value.reason,1000)&&value.provider_max_amount==='21474836.47';}
function actions(value:unknown,ready:CustomerFinancialReadiness):value is CustomerFinancialActions{return financialRecord(value)&&financialKeys(value,CUSTOMER_FINANCIAL_KINDS)&&CUSTOMER_FINANCIAL_KINDS.every(kind=>{const action=value[kind];return financialRecord(action)&&financialKeys(action,['available','reason'])&&typeof action.available==='boolean'&&financialText(action.reason,1000)&&(!action.available||ready.writes);});}
function identity(value:Record<string,unknown>){return ['order_id','payment_order_id','uid'].every(key=>financialId(value[key]))&&['store_id','supplier_id'].every(key=>financialId(value[key],0))&&financialNumber(value.order_no)&&financialNumber(value.payment_order_no)&&['order_revision','financial_revision'].every(key=>financialHash(value[key]));}
export function isCustomerFinancialOrder(value:unknown):value is CustomerFinancialOrder{
 if(!financialRecord(value)||!financialKeys(value,['version','requested_order_no','order_id','order_no','payment_order_id','payment_order_no','uid','store_id','supplier_id','order_revision','financial_revision','paid','status','pay_type','pay_price','refunded_price','change_price','total_num','readiness','actions'])||value.version!=='customer-work-financial-order-v1'||!identity(value)||value.requested_order_no!==value.order_no||![0,1].includes(value.paid as number)||!financialId(value.status,-2)||Number(value.status)>5||!financialText(value.pay_type,32)||!financialId(value.total_num,0)||!financialMoney(value.pay_price)||!financialMoney(value.refunded_price)||!financialSignedMoney(value.change_price)||!readiness(value.readiness))return false;return actions(value.actions,value.readiness);
}
export function isCustomerFinancialRefundQuote(value:unknown):value is CustomerFinancialRefundQuote{
 if(!financialRecord(value)||!financialKeys(value,['version','order_id','order_no','payment_order_id','order_revision','financial_revision','mode','items','quoted_price','quote_fingerprint','refund_time_days','received_at'])||value.version!=='customer-work-financial-refund-quote-v1'||!financialId(value.order_id)||!financialId(value.payment_order_id)||!financialNumber(value.order_no)||!financialHash(value.order_revision)||!financialHash(value.financial_revision)||!['remaining','items'].includes(value.mode as string)||!financialMoney(value.quoted_price)||!financialHash(value.quote_fingerprint)||!financialId(value.refund_time_days,0)||(value.received_at!==null&&!financialEpoch(value.received_at))||!Array.isArray(value.items)||!value.items.length||value.items.length>100)return false;
 return value.items.every(item=>financialRecord(item)&&financialKeys(item,['cart_row_id','cart_id','cart_num','max_num','title','sku','image','line_price'])&&financialId(item.cart_row_id)&&financialText(item.cart_id,128,true)&&financialId(item.cart_num)&&financialId(item.max_num)&&item.cart_num<=item.max_num&&financialText(item.title,500)&&financialText(item.sku,500)&&(item.image===''||isUserCenterPublicImage(item.image))&&financialMoney(item.line_price))&&new Set(value.items.map(item=>item.cart_row_id)).size===value.items.length;
}
export function isCustomerFinancialRefundReview(value:unknown):value is CustomerFinancialRefundReview{
 if(!financialRecord(value)||!financialKeys(value,['version','requested_refund_no','refund_id','refund_no','order_id','order_no','payment_order_id','payment_order_no','uid','store_id','supplier_id','order_revision','financial_revision','refund_revision','review_fingerprint','apply_type','refund_type','refund_price','refunded_price','remark','requires_received_confirmation','return_evidence','readiness','actions'])||value.version!=='customer-work-financial-refund-review-v1'||!identity(value)||!financialId(value.refund_id)||!financialNumber(value.refund_no,50)||value.requested_refund_no!==value.refund_no||!financialHash(value.refund_revision)||!financialHash(value.review_fingerprint)||![0,1,2,3,4].includes(value.apply_type as number)||![0,1,2,3,4,5,6].includes(value.refund_type as number)||!financialMoney(value.refund_price)||!financialMoney(value.refunded_price)||!financialDisplayText(value.remark,255)||typeof value.requires_received_confirmation!=='boolean'||!readiness(value.readiness)||!actions(value.actions,value.readiness))return false;
 const evidence=value.return_evidence;return financialRecord(evidence)&&financialKeys(evidence,['reason','explain','images','goods_images','express_name','express_no','phone'])&&['reason','explain'].every(key=>financialDisplayText(evidence[key],10000))&&['express_name','express_no','phone'].every(key=>financialText(evidence[key],10000))&&['images','goods_images'].every(key=>Array.isArray(evidence[key])&&(evidence[key] as unknown[]).length<=3&&(evidence[key] as unknown[]).every(isUserCenterPublicImage));
}
export function parseCustomerFinancialEnvelope<T>(value:unknown,actorUid:number,guard:(data:unknown)=>data is T,authority:{scope_key:string;consistency_key:string;principal:{service_id:number}}):CustomerFinancialEnvelope<T>{
 assert(financialRecord(value)&&financialKeys(value,['version','actor_uid','principal','scope_key','consistency_key','data'])&&value.version==='customer-work-read-v1'&&value.actor_uid===actorUid&&financialRecord(value.principal)&&financialKeys(value.principal,['kind','service_id','scope'])&&value.principal.kind==='customer-order-manager'&&financialId(value.principal.service_id)&&value.principal.scope==='global'&&financialHash(value.scope_key)&&financialHash(value.consistency_key)&&guard(value.data),'财务响应与当前经营身份不匹配，请重新读取');
 assert(value.scope_key===authority.scope_key&&value.principal.service_id===authority.principal.service_id&&value.consistency_key===authority.consistency_key,'经营身份或财务读取依据已变化，请重新读取');return value as unknown as CustomerFinancialEnvelope<T>;
}
function selection(mode:unknown,value:unknown){return ['remaining','items'].includes(mode as string)&&Array.isArray(value)&&value.length<=100&&(mode==='remaining'?value.length===0:value.length>0)&&value.every(item=>financialRecord(item)&&financialKeys(item,['cart_row_id','cart_num'])&&financialId(item.cart_row_id)&&financialId(item.cart_num))&&new Set(value.map(item=>item.cart_row_id)).size===value.length&&value.every((item,index)=>index===0||value[index-1].cart_row_id<item.cart_row_id);}
export function isCustomerFinancialInput(value:unknown,kind:CustomerFinancialKind):value is CustomerFinancialInput{
 if(!financialRecord(value)||!financialKeys(value,['version','scope_key','order_id','expected_order_revision','expected_financial_revision','payload'])||value.version!==CUSTOMER_FINANCIAL_VERSION||!financialId(value.order_id)||!financialHash(value.scope_key)||!financialHash(value.expected_order_revision)||!financialHash(value.expected_financial_revision)||!financialRecord(value.payload))return false;
 const payload=value.payload;
 if(kind==='change_price')return financialKeys(payload,['price'])&&financialMoney(payload.price);
 if(kind==='confirm_offline')return financialKeys(payload,[]);
 if(kind==='refund_create')return financialKeys(payload,['mode','items','quoted_price','refund_price','quote_fingerprint','reason'])&&selection(payload.mode,payload.items)&&financialMoney(payload.quoted_price)&&financialMoney(payload.refund_price)&&financialCents(payload.refund_price)<=financialCents(payload.quoted_price)&&financialHash(payload.quote_fingerprint)&&financialText(payload.reason,255,true)&&payload.reason===payload.reason.trim();
 const keys=['refund_id','refund_no','expected_refund_revision','review_fingerprint'];
 if(kind==='refund_remark')return financialKeys(payload,[...keys,'remark'])&&financialId(payload.refund_id)&&financialNumber(payload.refund_no,50)&&financialHash(payload.expected_refund_revision)&&financialHash(payload.review_fingerprint)&&financialText(payload.remark,255,true)&&payload.remark===payload.remark.trim();
 if(!['refund_return','refund_refuse','refund_execute'].includes(kind)||!financialKeys(payload,[...keys,'decision',...(kind==='refund_refuse'?['reason']:kind==='refund_execute'?['refund_price']:[])])||!financialId(payload.refund_id)||!financialNumber(payload.refund_no,50)||!financialHash(payload.expected_refund_revision)||!financialHash(payload.review_fingerprint)||!financialRecord(payload.decision)||!financialKeys(payload.decision,['apply_type','refund_type','received'])||!(kind==='refund_refuse'?[0,1,2,3,4]:[1,2,3,4]).includes(payload.decision.apply_type as number)||![0,1,2,4,5].includes(payload.decision.refund_type as number)||typeof payload.decision.received!=='boolean')return false;
 const decision=payload.decision;
 if(kind==='refund_return'&&(![2,3].includes(decision.apply_type as number)||![0,1,2].includes(decision.refund_type as number)))return false;
 if(kind==='refund_execute'&&[2,3].includes(decision.apply_type as number)&&(!decision.received||(decision.apply_type===2?decision.refund_type!==5:![4,5].includes(decision.refund_type as number))))return false;
 return kind==='refund_refuse'?financialText(payload.reason,255,true)&&payload.reason===payload.reason.trim():kind==='refund_execute'?financialMoney(payload.refund_price):true;
}
export function isCustomerFinancialIntent(value:unknown):value is CustomerFinancialIntent{
 if(!financialRecord(value)||!financialKeys(value,['version','actor_uid','service_id','scope_key','kind','request_key','request_hash','order_no','payment_order_id','payment_order_no','body','endpoint','method','created_at'])||value.version!=='customer-work-financial-pending-v1'||!financialId(value.actor_uid)||!financialId(value.service_id)||!financialHash(value.scope_key)||!CUSTOMER_FINANCIAL_KINDS.includes(value.kind as CustomerFinancialKind)||!financialUuid(value.request_key)||!financialHash(value.request_hash)||!financialNumber(value.order_no)||!financialId(value.payment_order_id)||!financialNumber(value.payment_order_no)||value.method!=='POST'||!financialEpoch(value.created_at)||!isCustomerFinancialInput(value.body,value.kind as CustomerFinancialKind)||value.scope_key!==value.body.scope_key)return false;
 return value.endpoint===financialEndpoint(value.kind as CustomerFinancialKind)&&value.request_hash===financialIntentHash(value.actor_uid,value.kind as CustomerFinancialKind,value.body);
}
const outcomes:Record<CustomerFinancialKind,CustomerFinancialOutcome[]>={change_price:['price-changed'],confirm_offline:['offline-paid'],refund_create:['refund-created'],refund_return:['return-approved'],refund_refuse:['refused'],refund_execute:['balance-settled','provider-admitted'],refund_remark:['refund-remark-saved']};
export function parseCustomerFinancialReceipt(value:unknown,intent:CustomerFinancialIntent):CustomerFinancialReceipt{
 assert(financialRecord(value)&&financialKeys(value,['version','request_key','request_hash','actor_uid','service_id','order_id','kind','outcome','evidence','created_at'])&&value.version===CUSTOMER_FINANCIAL_VERSION&&value.request_key===intent.request_key&&value.request_hash===intent.request_hash&&value.actor_uid===intent.actor_uid&&value.order_id===intent.body.order_id&&value.kind===intent.kind&&financialId(value.service_id,0)&&financialEpoch(value.created_at)&&financialRecord(value.evidence)&&['abandoned','rollback-rejected',...outcomes[intent.kind]].includes(value.outcome as CustomerFinancialOutcome),'原财务操作回执不匹配，请继续查询原编号');
 const terminal=['abandoned','rollback-rejected'].includes(value.outcome as string),e=value.evidence;
 assert(terminal?value.service_id===0:value.service_id===intent.service_id,'原财务回执的授权服务不匹配');
 if(value.outcome==='abandoned')assert(financialKeys(e,[]),'原放弃回执内容无效');
 else if(value.outcome==='rollback-rejected')assert(financialKeys(e,['code'])&&financialText(e.code,128,true),'原拒绝回执内容无效');
 else {
  assert(e.verified===true,'实际财务效果尚未核验');
  if(['return-approved','refused','balance-settled','refund-remark-saved','provider-admitted'].includes(value.outcome as string))assert(e.refund_id===intent.body.payload.refund_id,'回执的退款申请不匹配');
  if(['price-changed','return-approved','refund-remark-saved'].includes(value.outcome as string))assert(financialKeys(e,value.outcome==='price-changed'?['changed','verified']:['refund_id','changed','verified'])&&[0,1].includes(e.changed as number),'实际修改效果回执无效');
  else if(value.outcome==='offline-paid')assert(financialKeys(e,['outbox_id','verified'])&&financialId(e.outbox_id),'线下收款回执无效');
  else if(value.outcome==='refund-created')assert(financialKeys(e,['refund_id','refund_no','verified'])&&financialId(e.refund_id)&&financialNumber(e.refund_no),'新退款申请回执无效');
  else if(['refused','balance-settled'].includes(value.outcome as string))assert(financialKeys(e,['refund_id','verified'])&&financialId(e.refund_id),'实际退款处理回执无效');
  else if(value.outcome==='provider-admitted')assert(financialKeys(e,['refund_id','refund_no','payment_order_id','uid','store_id','supplier_id','provider','out_refund_no','request_amount','total_amount','verified'])&&e.refund_no===intent.body.payload.refund_no&&e.payment_order_id===intent.payment_order_id&&financialId(e.uid)&&financialId(e.store_id,0)&&financialId(e.supplier_id,0)&&['wechat','alipay'].includes(e.provider as string)&&e.out_refund_no==='CNSR'+e.refund_id&&financialId(e.request_amount)&&financialId(e.total_amount)&&e.request_amount<=e.total_amount&&financialCents(intent.body.payload.refund_price as string)===BigInt(e.request_amount),'渠道受理事实与原意图不匹配');
 }
 return value as unknown as CustomerFinancialReceipt;
}
export function parseCustomerFinancialResult(value:unknown,intent:CustomerFinancialIntent):CustomerFinancialResult{
 assert(financialRecord(value)&&financialKeys(value,['receipt','replayed','execution'])&&typeof value.replayed==='boolean','原财务结果响应无效');const receipt=value.receipt===null?null:parseCustomerFinancialReceipt(value.receipt,intent);let execution:CustomerFinancialExecution|null=null;
 if(value.execution!==null){const e=value.execution;assert(receipt&&['provider-admitted','balance-settled'].includes(receipt.outcome)&&intent.kind==='refund_execute'&&financialRecord(e)&&financialKeys(e,['version','request_key','request_hash','refund_id','status','completed','verified','can_resume'])&&e.version==='customer-work-financial-execution-v1'&&e.request_key===intent.request_key&&e.request_hash===intent.request_hash&&e.refund_id===intent.body.payload.refund_id&&['NONE','CREATED','REQUESTING','PROCESSING','SUCCESS','BALANCE_SUCCESS','CLOSED','ABNORMAL','FAILED','UNKNOWN'].includes(e.status as string)&&typeof e.completed==='boolean'&&typeof e.verified==='boolean'&&typeof e.can_resume==='boolean'&&(!e.completed||e.verified&&(receipt.outcome==='provider-admitted'?e.status==='SUCCESS':e.status==='BALANCE_SUCCESS'))&&(!e.completed||!e.can_resume)&&(receipt.outcome!=='balance-settled'||['UNKNOWN','BALANCE_SUCCESS'].includes(e.status as string))&&(e.status!=='SUCCESS'||receipt.outcome==='provider-admitted'&&e.completed&&e.verified)&&(e.status!=='BALANCE_SUCCESS'||receipt.outcome==='balance-settled'&&e.completed&&e.verified),'原渠道资金结果证据无效');execution=e as unknown as CustomerFinancialExecution;}
 assert(receipt||execution===null,'无回执不能声明资金执行事实');return{receipt,replayed:value.replayed,execution};
}
export function customerFinancialTerminal(result:CustomerFinancialResult):boolean{
 if(!result.receipt)return false;if(!['provider-admitted','balance-settled'].includes(result.receipt.outcome))return true;const e=result.execution;return !!e&&e.completed&&e.verified&&e.status===(result.receipt.outcome==='provider-admitted'?'SUCCESS':'BALANCE_SUCCESS');
}
