/** Ordinary customer writeoff wire. Portable: no Vue, Uni, storage, or actor inference. */
import {customerWorkCanonicalJson,customerWorkSha256} from './customerWorkIntent';
import {isUserCenterPublicImage} from './userCenterDesign';
export {customerWorkCanonicalJson} from './customerWorkIntent';
export const CUSTOMER_WRITEOFF_VERSION='customer-work-writeoff-operation-v1' as const;
export type CustomerWorkWriteoffKind='writeoff';
export type CustomerWorkWriteoffNamespace='auto'|'order-code'|'member-barcode'|'legacy-order-id';
export interface CustomerWorkWriteoffEnvelope<T>{version:'customer-work-read-v1';actor_uid:number;principal:{kind:'customer-order-manager';service_id:number;scope:'global'};scope_key:string;consistency_key:string;data:T}
export interface CustomerWorkWriteoffReadiness{writes:boolean;reason:string}
export interface CustomerWorkWriteoffSalePrice{source:'legacy-root-true-price'|'modern-line-finance'|'unproven';version:'customer-writeoff-sale-price-v1';snapshot_hash:string|null;price_hash:string|null;next_price:string|null;all_remaining_price:string|null;reason:string}
export interface CustomerWorkWriteoffCart{cart_row_id:number;cart_id:string;cart_num:number;product_id:number;product_type:number;product_name:string;image:string;sku:string;write_times:number;write_surplus_times:number;is_writeoff:number;write_start:number;write_end:number;sale_price:CustomerWorkWriteoffSalePrice}
export interface CustomerWorkWriteoffTarget{version:'customer-work-writeoff-target-v1';requested_order_no:string;id:number;order_no:string;root_order_id:number;root_order_no:string;uid:number;store_id:number;supplier_id:number;type:number;product_type:number;paid:number;status:number;shipping_type:number;delivery_type:string;code:string;order_revision:string;writeoff_revision:string;target_fingerprint:string;readiness:CustomerWorkWriteoffReadiness;actions:{writeoff:{available:boolean;reason:string}};cashier_origin:{eligible:boolean;version:string;proof_hash:string|null;reason:string};carts:CustomerWorkWriteoffCart[]}
export interface CustomerWorkWriteoffLookupInput{version:'customer-work-writeoff-read-v1';scope_key:string;namespace:CustomerWorkWriteoffNamespace;value:string}
export interface CustomerWorkWriteoffLookup{version:'customer-work-writeoff-lookup-v1';namespace:CustomerWorkWriteoffNamespace;lookup_kind:'order-code'|'member-barcode'|'legacy-order-id';lookup_fingerprint:string;orders:CustomerWorkWriteoffTarget[]}
export interface CustomerWorkWriteoffOperator{kind:'customer'|'admin'|'staff'|'delivery'|'unknown';actor_uid:number|null;service_id:number|null;admin_id:number|null;staff_id:number|null;delivery_id:number|null;request_key:string|null;request_hash:string|null}
export interface CustomerWorkWriteoffRecord{record_id:number;cart_row_id:number;cart_id:string;writeoff_num:number;writeoff_price:string;created_at:number;operator:CustomerWorkWriteoffOperator}
export interface CustomerWorkWriteoffRecords{version:'customer-work-writeoff-records-v1';order_id:number;order_no:string;root_order_id:number;root_order_no:string;list:CustomerWorkWriteoffRecord[];count:number;page:number;limit:number;has_more:boolean}
export interface CustomerWorkWriteoffItem{cart_row_id:number;writeoff_num:number}
export interface CustomerWorkWriteoffInput{version:typeof CUSTOMER_WRITEOFF_VERSION;scope_key:string;order_id:number;expected_order_revision:string;expected_writeoff_revision:string;payload:{order_no:string;root_order_id:number;root_order_no:string;code:string;target_fingerprint:string;items:CustomerWorkWriteoffItem[]}}
export interface CustomerWorkWriteoffRowEvidence{writeoff_id:number;cart_row_id:number;opaque_cart_id:string;quantity:number;before_remaining:number;after_remaining:number;writeoff_price:string;snapshot_hash:string;sale_price_hash:string}
export interface CustomerWorkWriteoffSettlement{version:'customer-writeoff-settlement-v1';take_delivery_status_id:number;supplier_rows:Array<{row_id:number;before_status:number;after_status:1;amount:string;pm:number;type:number}>;reward_rows:Array<{row_id:number;uid:number;link_id:string;category:'integral'|'exp';event_key:string;type:string;pm:number;amount:string;balance:string}>;brokerage_rows:Array<{row_id:number;uid:number;link_id:string;type:string;source_type:string;pm:number;amount:string;balance:string}>;account_deltas:Array<{uid:number;integral_before:number;integral_after:number;exp_before:string;exp_after:string;brokerage_before:string;brokerage_after:string}>;paid_root:{order_id:number;order_no:string;uid:number;pay_type:string;pay_price:string;paid:1;identity_hash:string};paid_outbox_rows:Array<{row_id:number;event_key:string;event_type:'order.paid';payload_hash:string}>;new_paid_outbox_count:0}
export type CustomerWorkWriteoffJson=null|boolean|number|string|CustomerWorkWriteoffJson[]|{[key:string]:CustomerWorkWriteoffJson};
export interface CustomerWorkWriteoffReceipt{version:typeof CUSTOMER_WRITEOFF_VERSION;request_key:string;request_hash:string;actor_uid:number;service_id:number;order_id:number;kind:CustomerWorkWriteoffKind;outcome:'partial-writtenoff'|'written-off'|'abandoned'|'rollback-rejected';evidence:{[key:string]:CustomerWorkWriteoffJson};created_at:number}
export interface CustomerWorkWriteoffExecution{version:'customer-work-writeoff-execution-v1';request_key:string;request_hash:string;order_id:number;state:'SQL_COMMITTED'|'UNKNOWN';committed:boolean;verified:boolean;order_completed:boolean;reason:string}
export interface CustomerWorkWriteoffResult{receipt:CustomerWorkWriteoffReceipt|null;replayed:boolean;execution:CustomerWorkWriteoffExecution|null}
export interface CustomerWorkWriteoffIntent{version:'customer-work-writeoff-pending-v1';actor_uid:number;service_id:number;scope_key:string;kind:CustomerWorkWriteoffKind;request_key:string;request_hash:string;order_no:string;root_order_id:number;root_order_no:string;body:CustomerWorkWriteoffInput;endpoint:'/mobile/work/writeoff/execute';method:'POST';created_at:number}
export const writeoffRecord=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v)&&[Object.prototype,null].includes(Object.getPrototypeOf(v));
export const writeoffKeys=(v:Record<string,unknown>,keys:readonly string[])=>Object.keys(v).sort().join(',')===[...keys].sort().join(',');
export const writeoffId=(v:unknown,min=1):v is number=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=min&&v<=2147483647;
export const writeoffEpoch=(v:unknown):v is number=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=0;
export const writeoffHash=(v:unknown):v is string=>typeof v==='string'&&/^[a-f0-9]{64}$/u.test(v);
export const writeoffUuid=(v:unknown):v is string=>typeof v==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/u.test(v);
export const writeoffNumber=(v:unknown):v is string=>typeof v==='string'&&/^[A-Za-z0-9_-]{1,32}$/u.test(v);
export const writeoffCode=(v:unknown):v is string=>typeof v==='string'&&/^\d{12}$/u.test(v);
export const writeoffMoney=(v:unknown):v is string=>typeof v==='string'&&/^(0|[1-9]\d{0,9})\.\d{2}$/u.test(v);
export const writeoffText=(v:unknown,max=1000):v is string=>typeof v==='string'&&Array.from(v).length<=max&&!/[\u0000-\u001f\u007f\uD800-\uDFFF]/u.test(v);
const opaque=(v:unknown):v is string=>writeoffText(v,128)&&v.length>0&&v===v.trim();
function assert(v:unknown,message:string):asserts v{if(!v)throw Error(message);}
const hashOrNull=(v:unknown)=>v===null||writeoffHash(v);
function salePrice(v:unknown):v is CustomerWorkWriteoffSalePrice{if(!writeoffRecord(v)||!writeoffKeys(v,['source','version','snapshot_hash','price_hash','next_price','all_remaining_price','reason'])||!['legacy-root-true-price','modern-line-finance','unproven'].includes(v.source as string)||v.version!=='customer-writeoff-sale-price-v1'||!writeoffText(v.reason)||!hashOrNull(v.snapshot_hash)||!hashOrNull(v.price_hash))return false;return v.source==='unproven'?v.next_price===null&&v.all_remaining_price===null:writeoffHash(v.snapshot_hash)&&writeoffHash(v.price_hash)&&writeoffMoney(v.next_price)&&writeoffMoney(v.all_remaining_price);}
export function isCustomerWorkWriteoffTarget(v:unknown):v is CustomerWorkWriteoffTarget{
 if(!writeoffRecord(v)||!writeoffKeys(v,['version','requested_order_no','id','order_no','root_order_id','root_order_no','uid','store_id','supplier_id','type','product_type','paid','status','shipping_type','delivery_type','code','order_revision','writeoff_revision','target_fingerprint','readiness','actions','cashier_origin','carts'])||v.version!=='customer-work-writeoff-target-v1'||!writeoffId(v.id)||!writeoffNumber(v.order_no)||v.requested_order_no!==v.order_no||!writeoffId(v.root_order_id)||!writeoffNumber(v.root_order_no)||!['uid','store_id','supplier_id','type','product_type','shipping_type'].every(k=>writeoffId(v[k],0))||![0,1].includes(v.paid as number)||!writeoffId(v.status,-2)||Number(v.status)>5||!writeoffText(v.delivery_type,32)||!(v.code===''||writeoffCode(v.code))||!['order_revision','writeoff_revision','target_fingerprint'].every(k=>writeoffHash(v[k])))return false;
 const ready=v.readiness,acts=v.actions,origin=v.cashier_origin;
 if(!writeoffRecord(ready)||!writeoffKeys(ready,['writes','reason'])||typeof ready.writes!=='boolean'||!writeoffText(ready.reason)||!writeoffRecord(acts)||!writeoffKeys(acts,['writeoff'])||!writeoffRecord(acts.writeoff)||!writeoffKeys(acts.writeoff,['available','reason'])||typeof acts.writeoff.available!=='boolean'||!writeoffText(acts.writeoff.reason)||!writeoffRecord(origin)||!writeoffKeys(origin,['eligible','version','proof_hash','reason'])||typeof origin.eligible!=='boolean'||!writeoffText(origin.version,128)||!hashOrNull(origin.proof_hash)||!writeoffText(origin.reason)||origin.eligible&&!writeoffHash(origin.proof_hash)||!Array.isArray(v.carts)||v.carts.length>500)return false;
 if(origin.eligible?origin.version!=='cashier-second-card-origin-v1'||!writeoffHash(origin.proof_hash):origin.version!==''||origin.proof_hash!==null)return false;
 if(acts.writeoff.available&&(!ready.writes||!writeoffCode(v.code)||v.paid!==1||v.uid===0&&(v.store_id!==0||!origin.eligible)))return false;
 return v.carts.every(row=>writeoffRecord(row)&&writeoffKeys(row,['cart_row_id','cart_id','cart_num','product_id','product_type','product_name','image','sku','write_times','write_surplus_times','is_writeoff','write_start','write_end','sale_price'])&&writeoffId(row.cart_row_id)&&opaque(row.cart_id)&&writeoffId(row.cart_num)&&writeoffId(row.product_id)&&writeoffId(row.product_type,0)&&writeoffText(row.product_name,500)&&writeoffText(row.sku,500)&&(row.image===''||isUserCenterPublicImage(row.image))&&writeoffId(row.write_times,0)&&writeoffId(row.write_surplus_times,0)&&row.write_surplus_times<=row.write_times&&[0,1].includes(row.is_writeoff as number)&&writeoffId(row.write_start,0)&&writeoffId(row.write_end,0)&&(!row.write_end||!row.write_start||row.write_end>=row.write_start)&&salePrice(row.sale_price))&&new Set(v.carts.map(row=>row.cart_row_id)).size===v.carts.length;
}
export function writeoffLookupValue(namespace:CustomerWorkWriteoffNamespace,value:unknown):value is string{if(!writeoffText(value,32)||value!==value.trim()||!value)return false;if(namespace==='legacy-order-id')return /^[1-9]\d{0,9}$/u.test(value)&&writeoffId(Number(value));if(namespace==='order-code')return writeoffCode(value);return ['auto','member-barcode'].includes(namespace)&&/^[A-Za-z0-9_-]{1,32}$/u.test(value);}
export function isCustomerWorkWriteoffLookup(v:unknown):v is CustomerWorkWriteoffLookup{return writeoffRecord(v)&&writeoffKeys(v,['version','namespace','lookup_kind','lookup_fingerprint','orders'])&&v.version==='customer-work-writeoff-lookup-v1'&&['auto','order-code','member-barcode','legacy-order-id'].includes(v.namespace as string)&&['order-code','member-barcode','legacy-order-id'].includes(v.lookup_kind as string)&&(v.namespace==='auto'?v.lookup_kind!=='legacy-order-id':v.namespace===v.lookup_kind)&&writeoffHash(v.lookup_fingerprint)&&Array.isArray(v.orders)&&v.orders.length<=100&&v.orders.every(isCustomerWorkWriteoffTarget)&&new Set(v.orders.map(row=>row.id)).size===v.orders.length&&(v.lookup_kind==='member-barcode'||v.orders.length<=1);}
function operator(v:unknown):v is CustomerWorkWriteoffOperator{
 if(!writeoffRecord(v)||!writeoffKeys(v,['kind','actor_uid','service_id','admin_id','staff_id','delivery_id','request_key','request_hash'])||!['customer','admin','staff','delivery','unknown'].includes(v.kind as string)||!['actor_uid','service_id','admin_id','staff_id','delivery_id'].every(k=>v[k]===null||writeoffId(v[k]))||!(v.request_key===null||writeoffUuid(v.request_key))||!hashOrNull(v.request_hash))return false;
 if(v.kind==='customer')return writeoffId(v.actor_uid)&&writeoffId(v.service_id)&&writeoffUuid(v.request_key)&&writeoffHash(v.request_hash)&&['admin_id','staff_id','delivery_id'].every(k=>v[k]===null);
 if(!['actor_uid','service_id','request_key','request_hash'].every(k=>v[k]===null))return false;
 return ['admin_id','staff_id','delivery_id'].every(k=>v.kind===k.replace('_id','')?writeoffId(v[k]):v[k]===null);
}
export function isCustomerWorkWriteoffRecords(v:unknown):v is CustomerWorkWriteoffRecords{return writeoffRecord(v)&&writeoffKeys(v,['version','order_id','order_no','root_order_id','root_order_no','list','count','page','limit','has_more'])&&v.version==='customer-work-writeoff-records-v1'&&writeoffId(v.order_id)&&writeoffNumber(v.order_no)&&writeoffId(v.root_order_id)&&writeoffNumber(v.root_order_no)&&writeoffId(v.count,0)&&writeoffId(v.page)&&writeoffId(v.limit)&&v.limit<=100&&typeof v.has_more==='boolean'&&Array.isArray(v.list)&&v.list.length<=v.limit&&v.list.length===Math.min(v.limit,Math.max(0,v.count-(v.page-1)*v.limit))&&v.has_more===(v.page*v.limit<v.count)&&v.list.every(row=>writeoffRecord(row)&&writeoffKeys(row,['record_id','cart_row_id','cart_id','writeoff_num','writeoff_price','created_at','operator'])&&writeoffId(row.record_id)&&writeoffId(row.cart_row_id)&&opaque(row.cart_id)&&writeoffId(row.writeoff_num)&&writeoffMoney(row.writeoff_price)&&writeoffEpoch(row.created_at)&&operator(row.operator))&&new Set(v.list.map(row=>row.record_id)).size===v.list.length;}
export function isCustomerWorkWriteoffInput(v:unknown):v is CustomerWorkWriteoffInput{
 if(!writeoffRecord(v)||!writeoffKeys(v,['version','scope_key','order_id','expected_order_revision','expected_writeoff_revision','payload'])||v.version!==CUSTOMER_WRITEOFF_VERSION||!writeoffHash(v.scope_key)||!writeoffId(v.order_id)||!writeoffHash(v.expected_order_revision)||!writeoffHash(v.expected_writeoff_revision)||!writeoffRecord(v.payload))return false;
 const p=v.payload;return writeoffKeys(p,['order_no','root_order_id','root_order_no','code','target_fingerprint','items'])&&writeoffNumber(p.order_no)&&writeoffId(p.root_order_id)&&writeoffNumber(p.root_order_no)&&writeoffCode(p.code)&&writeoffHash(p.target_fingerprint)&&Array.isArray(p.items)&&p.items.length>0&&p.items.length<=200&&p.items.every((row,i)=>writeoffRecord(row)&&writeoffKeys(row,['cart_row_id','writeoff_num'])&&writeoffId(row.cart_row_id)&&writeoffId(row.writeoff_num)&&(i===0||p.items instanceof Array&&p.items[i-1].cart_row_id<row.cart_row_id));
}
export const writeoffIntentHash=(actor_uid:number,input:CustomerWorkWriteoffInput)=>customerWorkSha256(customerWorkCanonicalJson({version:CUSTOMER_WRITEOFF_VERSION,actor_uid,kind:'writeoff',input}));
export const writeoffLookupFingerprint=(namespace:CustomerWorkWriteoffNamespace,value:string)=>customerWorkSha256(customerWorkCanonicalJson({namespace,value}));
export function isCustomerWorkWriteoffIntent(v:unknown):v is CustomerWorkWriteoffIntent{return writeoffRecord(v)&&writeoffKeys(v,['version','actor_uid','service_id','scope_key','kind','request_key','request_hash','order_no','root_order_id','root_order_no','body','endpoint','method','created_at'])&&v.version==='customer-work-writeoff-pending-v1'&&writeoffId(v.actor_uid)&&writeoffId(v.service_id)&&writeoffHash(v.scope_key)&&v.kind==='writeoff'&&writeoffUuid(v.request_key)&&writeoffHash(v.request_hash)&&writeoffNumber(v.order_no)&&writeoffId(v.root_order_id)&&writeoffNumber(v.root_order_no)&&v.endpoint==='/mobile/work/writeoff/execute'&&v.method==='POST'&&writeoffEpoch(v.created_at)&&isCustomerWorkWriteoffInput(v.body)&&v.scope_key===v.body.scope_key&&v.order_no===v.body.payload.order_no&&v.root_order_id===v.body.payload.root_order_id&&v.root_order_no===v.body.payload.root_order_no&&v.request_hash===writeoffIntentHash(v.actor_uid,v.body);}
export function parseCustomerWorkWriteoffEnvelope<T>(v:unknown,actorUid:number,guard:(data:unknown)=>data is T,authority:{scope_key:string;consistency_key:string;principal:{service_id:number}}):CustomerWorkWriteoffEnvelope<T>{assert(writeoffRecord(v)&&writeoffKeys(v,['version','actor_uid','principal','scope_key','consistency_key','data'])&&v.version==='customer-work-read-v1'&&v.actor_uid===actorUid&&writeoffRecord(v.principal)&&writeoffKeys(v.principal,['kind','service_id','scope'])&&v.principal.kind==='customer-order-manager'&&writeoffId(v.principal.service_id)&&v.principal.scope==='global'&&writeoffHash(v.scope_key)&&writeoffHash(v.consistency_key)&&guard(v.data),'核销响应与当前经营身份不匹配，请重新读取');assert(v.scope_key===authority.scope_key&&v.consistency_key===authority.consistency_key&&v.principal.service_id===authority.principal.service_id,'核销经营资格已变化，请重新读取');return v as unknown as CustomerWorkWriteoffEnvelope<T>;}
function ascii(v:unknown,max:number,empty=false):v is string{return typeof v==='string'&&new RegExp(`^[A-Za-z0-9_.:-]{${empty?0:1},${max}}$`,'u').test(v);}
function sortedRows(v:unknown,max:number,guard:(row:Record<string,unknown>)=>boolean,key='row_id'):v is Record<string,unknown>[] {return Array.isArray(v)&&v.length<=max&&v.every((row,i)=>writeoffRecord(row)&&writeoffId(row[key])&&guard(row)&&(i===0||Number(v[i-1][key])<Number(row[key])));}
export function isCustomerWorkWriteoffSettlement(v:unknown,rootId:number,rootNo:string):v is CustomerWorkWriteoffSettlement{
 if(!writeoffRecord(v)||!writeoffKeys(v,['version','take_delivery_status_id','supplier_rows','reward_rows','brokerage_rows','account_deltas','paid_root','paid_outbox_rows','new_paid_outbox_count'])||v.version!=='customer-writeoff-settlement-v1'||!writeoffId(v.take_delivery_status_id)||v.new_paid_outbox_count!==0)return false;
 const supplier=sortedRows(v.supplier_rows,200,r=>writeoffKeys(r,['row_id','before_status','after_status','amount','pm','type'])&&[0,1].includes(r.before_status as number)&&r.after_status===1&&writeoffMoney(r.amount)&&[0,1].includes(r.pm as number)&&[1,2].includes(r.type as number));
 const reward=sortedRows(v.reward_rows,200,r=>writeoffKeys(r,['row_id','uid','link_id','category','event_key','type','pm','amount','balance'])&&writeoffId(r.uid)&&writeoffLookupValue('legacy-order-id',r.link_id)&&['integral','exp'].includes(r.category as string)&&ascii(r.event_key,64)&&ascii(r.type,64)&&[0,1].includes(r.pm as number)&&writeoffMoney(r.amount)&&writeoffMoney(r.balance));
 const brokerage=sortedRows(v.brokerage_rows,200,r=>writeoffKeys(r,['row_id','uid','link_id','type','source_type','pm','amount','balance'])&&writeoffId(r.uid)&&writeoffLookupValue('legacy-order-id',r.link_id)&&ascii(r.type,64)&&ascii(r.source_type,64,true)&&[0,1].includes(r.pm as number)&&writeoffMoney(r.amount)&&writeoffMoney(r.balance));
 const accounts=sortedRows(v.account_deltas,70,r=>writeoffKeys(r,['uid','integral_before','integral_after','exp_before','exp_after','brokerage_before','brokerage_after'])&&writeoffId(r.integral_before,0)&&writeoffId(r.integral_after,0)&&['exp_before','exp_after','brokerage_before','brokerage_after'].every(k=>writeoffMoney(r[k])),'uid');
 const root=v.paid_root,outbox=sortedRows(v.paid_outbox_rows,200,r=>writeoffKeys(r,['row_id','event_key','event_type','payload_hash'])&&ascii(r.event_key,128)&&r.event_type==='order.paid'&&writeoffHash(r.payload_hash));
 if(!supplier||!reward||!brokerage||!accounts||!outbox||!writeoffRecord(root)||!writeoffKeys(root,['order_id','order_no','uid','pay_type','pay_price','paid','identity_hash'])||root.order_id!==rootId||root.order_no!==rootNo||!writeoffId(root.uid,0)||!ascii(root.pay_type,32)||!writeoffMoney(root.pay_price)||root.paid!==1||!writeoffHash(root.identity_hash))return false;
 return [...v.reward_rows as Record<string,unknown>[],...v.brokerage_rows as Record<string,unknown>[]].every(r=>(v.account_deltas as Record<string,unknown>[]).some(a=>a.uid===r.uid));
}
function byteLength(text:string){let bytes=0;for(const c of text){const n=c.codePointAt(0)!;bytes+=n<128?1:n<2048?2:n<65536?3:4;}return bytes;}
export function parseCustomerWorkWriteoffResult(v:unknown,intent:CustomerWorkWriteoffIntent):CustomerWorkWriteoffResult{
 assert(isCustomerWorkWriteoffIntent(intent)&&writeoffRecord(v)&&writeoffKeys(v,['receipt','replayed','execution'])&&typeof v.replayed==='boolean'&&byteLength(customerWorkCanonicalJson(v))<=262144,'原核销结果格式无效，请保留原编号核对');
 if(v.receipt===null){assert(v.execution===null,'没有原回执的核销结果无效');return v as unknown as CustomerWorkWriteoffResult;}
 const r=v.receipt;assert(writeoffRecord(r)&&writeoffKeys(r,['version','request_key','request_hash','actor_uid','service_id','order_id','kind','outcome','evidence','created_at'])&&r.version===CUSTOMER_WRITEOFF_VERSION&&r.request_key===intent.request_key&&r.request_hash===intent.request_hash&&r.actor_uid===intent.actor_uid&&r.order_id===intent.body.order_id&&r.kind==='writeoff'&&writeoffEpoch(r.created_at)&&writeoffRecord(r.evidence),'原核销回执身份或完整意图不匹配');
 const e=r.evidence,terminal=r.outcome==='abandoned'||r.outcome==='rollback-rejected';
 if(terminal){assert(r.service_id===0&&v.execution===null&&(r.outcome==='abandoned'?writeoffKeys(e,[]):writeoffKeys(e,['code'])&&writeoffText(e.code,128)&&String(e.code).length>0),'原核销终态回执无效');return v as unknown as CustomerWorkWriteoffResult;}
 assert(['partial-writtenoff','written-off'].includes(r.outcome as string)&&r.service_id===intent.service_id&&writeoffKeys(e,['verified','order_completed','status','physical_order_id','root_order_id','writeoff_rows','before_code_hash','after_code_hash','post_order_revision','post_writeoff_revision','settlement'])&&e.verified===true&&e.order_completed===(r.outcome==='written-off')&&e.status===(e.order_completed?2:5)&&e.physical_order_id===intent.body.order_id&&e.root_order_id===intent.root_order_id&&e.before_code_hash===customerWorkSha256(customerWorkCanonicalJson(intent.body.payload.code))&&writeoffHash(e.after_code_hash)&&['post_order_revision','post_writeoff_revision'].every(k=>writeoffHash(e[k]))&&Array.isArray(e.writeoff_rows)&&e.writeoff_rows.length===intent.body.payload.items.length,'原核销业务证据不匹配');
 assert(e.order_completed?e.after_code_hash===customerWorkSha256(customerWorkCanonicalJson(''))&&isCustomerWorkWriteoffSettlement(e.settlement,intent.root_order_id,intent.root_order_no):e.settlement===null&&e.after_code_hash!==e.before_code_hash&&e.after_code_hash!==customerWorkSha256(customerWorkCanonicalJson('')),'原核销码或结算证据不匹配');
 assert(e.writeoff_rows.every((row,i)=>{const item=intent.body.payload.items[i]!;return writeoffRecord(row)&&writeoffKeys(row,['writeoff_id','cart_row_id','opaque_cart_id','quantity','before_remaining','after_remaining','writeoff_price','snapshot_hash','sale_price_hash'])&&writeoffId(row.writeoff_id)&&row.cart_row_id===item.cart_row_id&&opaque(row.opaque_cart_id)&&row.quantity===item.writeoff_num&&writeoffId(row.before_remaining)&&writeoffId(row.after_remaining,0)&&row.before_remaining-row.after_remaining===item.writeoff_num&&writeoffMoney(row.writeoff_price)&&writeoffHash(row.snapshot_hash)&&writeoffHash(row.sale_price_hash);})&&new Set(e.writeoff_rows.map(row=>row.writeoff_id)).size===e.writeoff_rows.length,'原核销商品、次数或成交金额证据不匹配');
 const x=v.execution;assert(writeoffRecord(x)&&writeoffKeys(x,['version','request_key','request_hash','order_id','state','committed','verified','order_completed','reason'])&&x.version==='customer-work-writeoff-execution-v1'&&x.request_key===intent.request_key&&x.request_hash===intent.request_hash&&x.order_id===intent.body.order_id&&['SQL_COMMITTED','UNKNOWN'].includes(x.state as string)&&typeof x.committed==='boolean'&&typeof x.verified==='boolean'&&typeof x.order_completed==='boolean'&&writeoffText(x.reason)&&(x.state==='SQL_COMMITTED'?x.committed&&x.verified&&x.order_completed===e.order_completed:!x.committed&&!x.verified&&!x.order_completed),'原核销实际状态尚不能核验');return v as unknown as CustomerWorkWriteoffResult;
}
export function customerWriteoffTerminal(v:CustomerWorkWriteoffResult|null){return !!v?.receipt&&(v.receipt.outcome==='abandoned'||v.receipt.outcome==='rollback-rejected'||v.execution?.state==='SQL_COMMITTED'&&v.execution.committed&&v.execution.verified);}

/** Identifiers in scan URLs are navigation hints. Authorization happens only in scoped reads. */
export function parseCustomerWriteoffLegacyChoice(input:string|Record<string,unknown>):Record<string,string>{const fields:Record<string,string>={},entries=typeof input==='string'?input.split('&').filter(Boolean).map(part=>{const at=part.indexOf('=');assert(at>0,'历史身份选择入口无效');return[decodeURIComponent(part.slice(0,at)),decodeURIComponent(part.slice(at+1))];}):Object.entries(input).filter(([,v])=>v!==undefined);assert(typeof input!=='string'||input.length<=4096,'历史身份选择入口过长');for(const [k,v]of entries){assert(['entry','next','legacyOrderId','code'].includes(k as string)&&!Object.hasOwn(fields,k as string)&&writeoffText(v,128),'历史身份选择参数无效');fields[k as string]=v as string;}assert(fields.entry==='legacy-auto'&&['scanning','writeoff','writeoffRecords','writeoffResult'].includes(fields.next??'scanning'),'历史身份选择范围无效');fields.next??='scanning';if(fields.code!==undefined)assert(writeoffLookupValue('auto',fields.code),'历史扫码提示无效');if(fields.next==='scanning')assert(fields.legacyOrderId===undefined,'历史扫描不能指定订单物理编号');else assert(writeoffLookupValue('legacy-order-id',fields.legacyOrderId),'缺少历史订单物理编号');return fields;}
export function parseCustomerWriteoffQuery(page:'scanning'|'writeoff'|'writeoffRecords'|'writeoffResult',input:string|Record<string,unknown>):Record<string,string>{
 const fields:Record<string,string>={},allowed=page==='scanning'?['namespace','value','scene','code']:page==='writeoffResult'?['requestKey','legacyOrderId']:['orderId','orderNo','legacyOrderId'];
 const entries=typeof input==='string'?input.split('&').filter(Boolean).map(part=>{const at=part.indexOf('=');assert(at>0,'核销入口参数无效');return[decodeURIComponent(part.slice(0,at)),decodeURIComponent(part.slice(at+1))];}):Object.entries(input).filter(([,v])=>v!==undefined);
 assert(typeof input!=='string'||input.length<=4096,'核销入口参数过长');for(const [k,v]of entries){assert(allowed.includes(k as string)&&!Object.hasOwn(fields,k as string)&&writeoffText(v,1024),'核销入口参数重复或无效');fields[k as string]=v as string;}
 if(page==='scanning'){
  if(fields.scene!==undefined){assert(Object.keys(fields).length===1,'扫码场景与入口标识冲突');const decoded=decodeCustomerWriteoffScan(fields.scene,'scene');return{namespace:decoded.namespace,value:decoded.value};}
  if(fields.code!==undefined){assert(Object.keys(fields).length===1&&writeoffCode(fields.code),'核销码无效');return{namespace:'order-code',value:fields.code};}
  assert((fields.namespace===undefined)===(fields.value===undefined),'缺少扫码命名空间或内容');if(fields.value!==undefined)assert(fields.namespace!=='legacy-order-id'&&writeoffLookupValue(fields.namespace as CustomerWorkWriteoffNamespace,fields.value),'扫码命名空间或内容无效');return fields;
 }
 if(fields.legacyOrderId!==undefined){assert(Object.keys(fields).length===1&&writeoffLookupValue('legacy-order-id',fields.legacyOrderId),'历史订单物理编号无效');return fields;}
 if(page==='writeoffResult'){assert(Object.keys(fields).length===1&&writeoffUuid(fields.requestKey),'缺少原核销编号');return fields;}
 assert(Object.keys(fields).length===2&&writeoffLookupValue('legacy-order-id',fields.orderId)&&writeoffNumber(fields.orderNo),'缺少实际订单物理编号或业务单号');return fields;
}
export function decodeCustomerWriteoffScan(raw:unknown,source:'raw'|'wechat'|'scene'|'native'='raw',scanType?:string):{namespace:'auto'|'order-code'|'member-barcode';value:string}{
 assert(writeoffText(raw,2048)&&raw.length>0,'扫描结果无效');let value=raw;
 if(source==='scene'){assert(!/%25/iu.test(value),'扫码场景重复编码无效');try{value=decodeURIComponent(value);}catch{throw Error('扫码场景编码无效');}}
 if(source==='wechat'&&value.includes(',')){const at=value.indexOf(','),prefix=value.slice(0,at);assert(['CODE_128','CODE_39','EAN_13','EAN_8','UPC_A','UPC_E','ITF','QR_CODE'].includes(prefix),'扫码类型无效');value=value.slice(at+1);assert(!value.includes(','),'扫码内容无效');}
 if(source==='native'&&scanType!==undefined)assert(['QR_CODE','CODE_128','CODE_39','EAN_13','EAN_8','UPC_A','UPC_E','ITF','qrCode','barCode'].includes(scanType),'扫码类型无效');
 if(value.includes('?')||value.startsWith('/pages/')){
  assert(!value.includes('#')&&!value.includes('\\')&&!/^[a-z][a-z0-9+.-]*:/iu.test(value),'扫码地址无效');const at=value.indexOf('?'),path=value.slice(0,at);assert(['/pages/admin/order_cancellation/index','/pages/admin/distribution/scanning/index','/pages/customer-work/scanning'].includes(path),'扫码目标无效');const entries=value.slice(at+1).split('&');assert(entries.length>0,'扫码缺少核销码');let code='';for(const part of entries){const i=part.indexOf('=');assert(i>0,'扫码参数无效');let k:string,v:string;try{k=decodeURIComponent(part.slice(0,i));v=decodeURIComponent(part.slice(i+1));}catch{throw Error('扫码参数编码无效');}assert(k==='code'&&!code&&writeoffCode(v),'扫码参数重复或无效');code=v;}return{namespace:'order-code',value:code};
 }
 assert(writeoffLookupValue('auto',value),'扫码内容无效');return{namespace:'auto',value};
}
