import { customerWorkCanonicalJson,customerWorkIntentHash,CUSTOMER_WORK_OPERATION_VERSION } from '../../../common/customerWorkIntent';
import { customerWorkBusinessId } from '../../../common/customerWorkRoute';
import { customerWorkRecord,customerWorkMoney,customerWorkImage,isCustomerWorkScopes } from './customerWork';
import type { CustomerWorkFulfillment,CustomerWorkFulfillmentDefaults,CustomerWorkRemarkTarget,CustomerWorkCarrier,CustomerWorkCourier,CustomerWorkWaybillTemplate,CustomerWorkWaybillJob,CustomerWorkCityJob,CustomerWorkCityReadiness,CustomerWorkOperationBody,CustomerWorkOperationKind,CustomerWorkOperationReceipt,CustomerWorkPendingIntent } from '../types/customerWorkFulfillment';
export { customerWorkCanonicalJson,customerWorkIntentHash,CUSTOMER_WORK_OPERATION_VERSION } from '../../../common/customerWorkIntent';
export const customerWorkInteger=(value:unknown,min=0):value is number=>typeof value==='number'&&Number.isSafeInteger(value)&&value>=min&&value<=2147483647;
export const customerWorkText=(value:unknown,max=4000):value is string=>typeof value==='string'&&value.length<=max&&!/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/u.test(value);
export const customerWorkHash=(value:unknown):value is string=>typeof value==='string'&&/^[a-f0-9]{64}$/u.test(value);
export const customerWorkUuid=(value:unknown):value is string=>typeof value==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/u.test(value);
export const CUSTOMER_WORK_KINDS:CustomerWorkOperationKind[]=['remark','manual_delivery','split_delivery','electronic_waybill','electronic_split_waybill','city_delivery','city_split_delivery','waybill_apply_existing','waybill_confirm_issued','waybill_confirm_retry','waybill_close'];
function assert(value:unknown,message:string):asserts value{if(!value)throw Error(message);}
const textFields=(value:Record<string,unknown>,fields:string[],max=4000)=>fields.every(key=>customerWorkText(value[key],max));
const integerFields=(value:Record<string,unknown>,fields:string[],min=0)=>fields.every(key=>customerWorkInteger(value[key],min));
export function isCustomerWorkDefaults(value:unknown):value is CustomerWorkFulfillmentDefaults{return customerWorkRecord(value)&&[0,1].includes(value.config_export_open as number)&&textFields(value,['config_export_id','express_temp_id','to_name','to_tel','to_add'],1000)&&typeof value.has_cloud_printer==='boolean';}
export function isCustomerWorkRemarkTarget(value:unknown):value is CustomerWorkRemarkTarget{return customerWorkRecord(value)&&customerWorkInteger(value.id,1)&&customerWorkBusinessId(value.order_id)&&customerWorkText(value.remark,4000)&&customerWorkHash(value.order_revision)&&customerWorkHash(value.fulfillment_revision)&&typeof value.available==='boolean'&&customerWorkText(value.reason,1000);}
export function isCustomerWorkRemark(value:unknown):value is {remark_target:CustomerWorkRemarkTarget}{return customerWorkRecord(value)&&isCustomerWorkRemarkTarget(value.remark_target);}
export function isCustomerWorkCarriers(value:unknown):value is {list:CustomerWorkCarrier[]}{return customerWorkRecord(value)&&Array.isArray(value.list)&&value.list.length<=1000&&value.list.every(row=>customerWorkRecord(row)&&customerWorkInteger(row.id,1)&&textFields(row,['name','code'],200)&&!!row.name&&!!row.code)&&new Set(value.list.map(row=>row.id)).size===value.list.length&&new Set(value.list.map(row=>row.code)).size===value.list.length;}
export function isCustomerWorkCouriers(value:unknown):value is {list:CustomerWorkCourier[]}{return customerWorkRecord(value)&&Array.isArray(value.list)&&value.list.length<=500&&value.list.every(row=>customerWorkRecord(row)&&customerWorkInteger(row.uid,1)&&textFields(row,['nickname','phone'],200))&&new Set(value.list.map(row=>row.uid)).size===value.list.length;}
export function isCustomerWorkTemplates(value:unknown):value is {carrier_id:number;list:CustomerWorkWaybillTemplate[]}{return customerWorkRecord(value)&&customerWorkInteger(value.carrier_id,1)&&Array.isArray(value.list)&&value.list.length<=200&&value.list.every(row=>customerWorkRecord(row)&&textFields(row,['title','temp_id'],255)&&!!row.temp_id&&customerWorkImage(row.pic))&&new Set(value.list.map(row=>row.temp_id)).size===value.list.length;}
const cityStatuses=['PENDING','PROCESSING','ADMITTED','UNKNOWN','REJECTED','REVOKED','CANCELLED','DELIVERED'];
export function isCustomerWorkCityJob(value:unknown):value is CustomerWorkCityJob{return customerWorkRecord(value)&&customerWorkInteger(value.job_id,1)&&customerWorkUuid(value.request_key)&&cityStatuses.includes(String(value.status))&&['dada','uu'].includes(String(value.provider))&&textFields(value,['provider_order_id','last_error_code'],500)&&(value.delivery_status===null||customerWorkInteger(value.delivery_status))&&customerWorkInteger(value.updated_at)&&value.may_retry===false;}
export function isCustomerWorkCityReadiness(value:unknown):value is CustomerWorkCityReadiness{
  if(!customerWorkRecord(value)||typeof value.schema_ready!=='boolean'||!Array.isArray(value.providers)||value.providers.length>2||!value.providers.every(row=>customerWorkRecord(row)&&[1,2].includes(row.station_type as number)&&row.provider===(row.station_type===1?'dada':'uu')&&typeof row.available==='boolean'&&Array.isArray(row.reasons)&&row.reasons.length<=30&&row.reasons.every(reason=>customerWorkText(reason,500)))||new Set(value.providers.map(row=>row.station_type)).size!==value.providers.length)return false;
  const station=value.station;return (station===null||customerWorkRecord(station)&&[0,1,2].includes(station.type as number)&&customerWorkInteger(station.relation_id)&&textFields(station,['name','address','phone','city_name'],1000))&&(value.job===null||isCustomerWorkCityJob(value.job));
}
const waybillStatuses=['PENDING','ENQUEUING','ENQUEUED','PROCESSING','RETRYABLE','SENT','UNKNOWN','DEAD','CLOSED'];
export function isCustomerWorkWaybillJob(value:unknown):value is CustomerWorkWaybillJob{
  if(!customerWorkRecord(value)||!customerWorkHash(value.job_revision))return false;
  if(!customerWorkRecord(value)||!customerWorkInteger(value.id,1)||!customerWorkUuid(value.request_key)||!customerWorkHash(value.request_hash)||value.event_key!==`order.waybill:${value.request_key}`||value.actor_type!=='customer'||!customerWorkInteger(value.actor_id,1)||!customerWorkInteger(value.service_id,1)||!customerWorkBusinessId(value.order_no)||!integerFields(value,['order_id','root_order_id','carrier_id'],1)||!integerFields(value,['supplier_id','dispatch_count','attempt_count','replay_count','available_time','lease_until','fulfilled_order_id','sent_time','add_time','update_time'])||!['whole','split'].includes(String(value.fulfillment_mode))||!waybillStatuses.includes(String(value.status))||!textFields(value,['carrier_code','carrier_name','template_id','provider_reference','response_code','tracking_number','last_error'],2000)||typeof value.has_cloud_printer!=='boolean'||!customerWorkImage(value.label_url)||(value.payload_hash!==''&&!customerWorkHash(value.payload_hash))||(value.remaining_order_id!==null&&!customerWorkInteger(value.remaining_order_id,1)))return false;
  return value.status!=='SENT'||(value.fulfilled_order_id as number)>0&&!!value.tracking_number&&(value.sent_time as number)>0;
}
export function isCustomerWorkFulfillment(value:unknown):value is CustomerWorkFulfillment{
  if(!customerWorkRecord(value)||!isCustomerWorkScopes(value.metric_scopes)||!customerWorkBusinessId(value.requested_order_no)||!customerWorkRecord(value.order)||!customerWorkRecord(value.actions)||!customerWorkRecord(value.readiness)||!isCustomerWorkRemarkTarget(value.remark_target)||value.remark_target.order_id!==value.requested_order_no)return false;
  const order=value.order;
  if(!integerFields(order,['id','requested_order_id','root_order_id','customer_uid'],1)||!integerFields(order,['store_id','supplier_id','paid','shipping_type','product_type','total_num'])||!customerWorkInteger(order.status,-2)||!customerWorkBusinessId(order.order_id)||!customerWorkHash(order.order_revision)||!customerWorkHash(order.fulfillment_revision)||!customerWorkMoney(order.pay_price)||!textFields(order,['remark','real_name','user_phone','user_address']))return false;
  const actions=value.actions;if(!['remark','manual_delivery','split_delivery','electronic_waybill','city_delivery'].every(key=>customerWorkRecord(actions[key])&&typeof actions[key].available==='boolean'&&customerWorkText(actions[key].reason,1000)))return false;
  if(!Array.isArray(value.carts)||value.carts.length>500||!value.carts.every(row=>customerWorkRecord(row)&&customerWorkText(row.cart_id,50)&&!!row.cart_id&&!/[\r\n\t]/u.test(row.cart_id)&&integerFields(row,['product_id','cart_num','surplus_num'],1)&&(row.surplus_num as number)<=(row.cart_num as number)&&textFields(row,['store_name','sku'],1000)&&customerWorkMoney(row.price))||new Set(value.carts.map(row=>row.cart_id)).size!==value.carts.length||!isCustomerWorkDefaults(value.defaults))return false;
  for(const key of ['operations','electronic']){const readiness=value.readiness[key];if(!customerWorkRecord(readiness)||typeof readiness.ready!=='boolean'||!customerWorkText(readiness.reason,1000))return false;}
  return isCustomerWorkCityReadiness(value.readiness.city)&&(value.jobs===undefined||Array.isArray(value.jobs)&&value.jobs.length<=100&&value.jobs.every(isCustomerWorkWaybillJob)&&new Set(value.jobs.map(row=>row.id)).size===value.jobs.length);
}
function finiteJson(value:unknown,depth=0):boolean{if(depth>12)return false;if(value===null||typeof value==='boolean')return true;if(typeof value==='string')return customerWorkText(value,4000);if(typeof value==='number')return Number.isSafeInteger(value);if(Array.isArray(value))return value.length<=500&&value.every(row=>finiteJson(row,depth+1));return customerWorkRecord(value)&&Object.getPrototypeOf(value)===Object.prototype&&Object.keys(value).length<=100&&Object.entries(value).every(([key,row])=>!['__proto__','constructor','prototype'].includes(key)&&customerWorkText(key,100)&&finiteJson(row,depth+1));}
export function isCustomerWorkOperationBody(value:unknown):value is CustomerWorkOperationBody{return customerWorkRecord(value)&&Object.keys(value).sort().join(',')==='expected_fulfillment_revision,expected_order_revision,order_id,payload,scope_key,version'&&value.version===CUSTOMER_WORK_OPERATION_VERSION&&customerWorkInteger(value.order_id,1)&&customerWorkHash(value.scope_key)&&customerWorkHash(value.expected_order_revision)&&customerWorkHash(value.expected_fulfillment_revision)&&customerWorkRecord(value.payload)&&finiteJson(value.payload)&&customerWorkCanonicalJson(value).length<=60000;}
export function customerWorkWriteEndpoint(kind:CustomerWorkOperationKind,orderId:number,jobId?:number):{endpoint:string;method:'POST'|'PUT'}{
  assert(customerWorkInteger(orderId,1),'订单物理目标无效');
  if(kind.startsWith('waybill_')){assert(customerWorkInteger(jobId,1),'电子面单任务标识无效');return {endpoint:`/mobile/work/fulfillment/waybills/${jobId}/decisions`,method:'POST'};}
  const split=['split_delivery','electronic_split_waybill','city_split_delivery'].includes(kind);return {endpoint:`/mobile/work/orders/${orderId}/${kind==='remark'?'remark':split?'split-fulfillment':'fulfillment'}`,method:split?'PUT':'POST'};
}
export function isCustomerWorkPendingIntent(value:unknown):value is CustomerWorkPendingIntent{
  if(!customerWorkRecord(value)||Object.keys(value).sort().join(',')!=='actor_uid,body,created_at,endpoint,kind,method,order_no,request_hash,request_key,root_order_id,scope_key,service_id,version'||value.version!=='customer-work-pending-v1'||!customerWorkUuid(value.request_key)||!customerWorkHash(value.request_hash)||!customerWorkInteger(value.actor_uid,1)||!customerWorkInteger(value.service_id,1)||!customerWorkHash(value.scope_key)||!customerWorkBusinessId(value.order_no)||!customerWorkInteger(value.root_order_id,1)||!CUSTOMER_WORK_KINDS.includes(value.kind as CustomerWorkOperationKind)||!isCustomerWorkOperationBody(value.body)||value.body.scope_key!==value.scope_key||!customerWorkInteger(value.created_at))return false;
  try{const expected=customerWorkWriteEndpoint(value.kind as CustomerWorkOperationKind,value.body.order_id,value.body.payload.job_id as number|undefined);return expected.endpoint===value.endpoint&&expected.method===value.method&&customerWorkIntentHash(value.actor_uid,value.kind as string,value.body)===value.request_hash;}catch{return false;}
}
export function parseCustomerWorkReceipt(value:unknown,intent:CustomerWorkPendingIntent):CustomerWorkOperationReceipt|null{
  assert(customerWorkRecord(value)&&Object.hasOwn(value,'receipt'),'原操作凭据响应无效');if(value.receipt===null)return null;const row=value.receipt;
  assert(customerWorkRecord(row)&&row.version===CUSTOMER_WORK_OPERATION_VERSION&&row.request_key===intent.request_key&&row.request_hash===intent.request_hash&&row.actor_uid===intent.actor_uid&&row.order_id===intent.body.order_id&&row.kind===intent.kind&&customerWorkInteger(row.service_id)&&customerWorkRecord(row.evidence)&&finiteJson(row.evidence),'原操作凭据不匹配，不能重新提交');
  const expected=intent.kind==='remark'?'remark-saved':['manual_delivery','split_delivery'].includes(intent.kind)?'delivery-recorded':intent.kind.startsWith('waybill_')?'job-updated':'provider-admitted';
  assert(['abandoned','rollback-rejected',expected].includes(String(row.outcome))&&(row.service_id===intent.service_id||row.service_id===0&&['abandoned','rollback-rejected'].includes(String(row.outcome))),'原操作身份或结果不匹配');
  const evidence=row.evidence,only=(keys:string[])=>Object.keys(evidence).every(key=>keys.includes(key))&&keys.every(key=>Object.hasOwn(evidence,key));
  if(row.outcome==='remark-saved')assert(only(['changed'])&&typeof evidence.changed==='boolean','原备注保存证据不完整');
  if(row.outcome==='delivery-recorded')assert(only(['split','order_id','remaining_order_id'])&&typeof evidence.split==='boolean'&&customerWorkInteger(evidence.order_id,1)&&(evidence.remaining_order_id===null||customerWorkInteger(evidence.remaining_order_id,1)),'原发货证据不完整');
  if(row.outcome==='job-updated')assert(only(['waybill_job_id','status','order_id','fulfilled_order_id','remaining_order_id'])&&evidence.waybill_job_id===intent.body.payload.job_id&&evidence.order_id===intent.body.order_id&&waybillStatuses.includes(String(evidence.status))&&customerWorkInteger(evidence.fulfilled_order_id)&&(evidence.remaining_order_id===null||customerWorkInteger(evidence.remaining_order_id,1)),'原面单恢复证据不完整');
  if(row.outcome==='provider-admitted'&&intent.kind.startsWith('electronic'))assert(only(['waybill_job_id','waybill_request_hash','waybill_cart_snapshot_hash','root_order_id','root_store_id','root_supplier_id','order_id','store_id','supplier_id','customer_uid'])&&customerWorkInteger(evidence.waybill_job_id,1)&&customerWorkHash(evidence.waybill_request_hash)&&customerWorkHash(evidence.waybill_cart_snapshot_hash)&&integerFields(evidence,['root_store_id','root_supplier_id','store_id','supplier_id'])&&customerWorkInteger(evidence.customer_uid,1)&&evidence.root_order_id===intent.root_order_id&&evidence.order_id===intent.body.order_id,'电子面单受理证据不完整，原操作仍待核对');
  if(row.outcome==='provider-admitted'&&intent.kind.startsWith('city'))assert(only(['city_job_id','status','provider','root_order_id','order_id','store_id','supplier_id','customer_uid'])&&customerWorkInteger(evidence.city_job_id,1)&&evidence.provider===(intent.body.payload.station_type===1?'dada':'uu')&&cityStatuses.includes(String(evidence.status))&&integerFields(evidence,['store_id','supplier_id'])&&customerWorkInteger(evidence.customer_uid,1)&&evidence.root_order_id===intent.root_order_id&&evidence.order_id===intent.body.order_id,'同城任务受理证据不完整，原操作仍待核对');
  if(row.outcome==='abandoned')assert(only([]),'放弃原操作证据不匹配');
  if(row.outcome==='rollback-rejected')assert(only(['code'])&&customerWorkText(evidence.code,50),'原操作未执行证据不匹配');
  return row as unknown as CustomerWorkOperationReceipt;
}
export function customerWorkOperationLabel(kind:CustomerWorkOperationKind):string{return ({remark:'订单备注',manual_delivery:'整单发货',split_delivery:'拆单发货',electronic_waybill:'电子面单',electronic_split_waybill:'拆单电子面单',city_delivery:'同城配送',city_split_delivery:'拆单同城配送',waybill_apply_existing:'应用已签发面单',waybill_confirm_issued:'确认已签发面单',waybill_confirm_retry:'确认面单重试',waybill_close:'关闭面单任务'})[kind];}
