import {parseCustomerWorkQuery,resolveCustomerWorkPageRoute} from '../../../common/customerWorkRoute';
import {CUSTOMER_FINANCIAL_VERSION,CUSTOMER_FINANCIAL_KINDS,financialAmount,financialCents,financialReason,financialMoney,financialSignedMoney,financialEpoch,financialId,financialIntentHash,financialEndpoint,isCustomerFinancialInput,isCustomerFinancialIntent,isCustomerFinancialOrder,isCustomerFinancialRefundQuote,isCustomerFinancialRefundReview,parseCustomerFinancialEnvelope,parseCustomerFinancialResult,customerFinancialTerminal,financialDisplayText,financialText} from './customerWorkFinancial';
import type {CustomerFinancialKind,CustomerFinancialInput,CustomerFinancialIntent,CustomerFinancialJson} from '../types/customerWorkFinancial';
export const financialPayloads:Record<CustomerFinancialKind,Record<string,CustomerFinancialJson>>={change_price:{price:'0.10'},confirm_offline:{},refund_create:{mode:'items',items:[{cart_row_id:41,cart_num:1}],quoted_price:'10.00',refund_price:'0.10',quote_fingerprint:'f'.repeat(64),reason:'独立低额申请'},refund_return:{refund_id:1,refund_no:'REFUND_1',expected_refund_revision:'e'.repeat(64),review_fingerprint:'f'.repeat(64),decision:{apply_type:2,refund_type:0,received:false}},refund_refuse:{refund_id:1,refund_no:'REFUND_1',expected_refund_revision:'e'.repeat(64),review_fingerprint:'f'.repeat(64),decision:{apply_type:1,refund_type:0,received:false},reason:'核对后拒绝'},refund_execute:{refund_id:1,refund_no:'REFUND_1',expected_refund_revision:'e'.repeat(64),review_fingerprint:'f'.repeat(64),decision:{apply_type:1,refund_type:0,received:false},refund_price:'1.00'},refund_remark:{refund_id:1,refund_no:'REFUND_1',expected_refund_revision:'e'.repeat(64),review_fingerprint:'f'.repeat(64),remark:'核对记录'}};
export function financialIntent(kind:CustomerFinancialKind='refund_execute',payload=financialPayloads[kind]):CustomerFinancialIntent{const body:CustomerFinancialInput={version:CUSTOMER_FINANCIAL_VERSION,scope_key:'a'.repeat(64),order_id:1,expected_order_revision:'c'.repeat(64),expected_financial_revision:'d'.repeat(64),payload};return{version:'customer-work-financial-pending-v1',actor_uid:11,service_id:1,scope_key:body.scope_key,kind,request_key:'12345678-1234-4123-8123-123456789abc',request_hash:financialIntentHash(11,kind,body),order_no:'ORDER_1',payment_order_id:1,payment_order_no:'ORDER_1',body,endpoint:financialEndpoint(kind),method:'POST',created_at:2208988800};}
export function financialReceipt(intent:CustomerFinancialIntent,outcome?:string){const kind=intent.kind,evidence:Record<string,CustomerFinancialJson>=kind==='change_price'?{changed:1,verified:true}:kind==='confirm_offline'?{outbox_id:1,verified:true}:kind==='refund_create'?{refund_id:1,refund_no:'REFUND_1',verified:true}:kind==='refund_return'||kind==='refund_remark'?{refund_id:1,changed:1,verified:true}:{refund_id:1,verified:true};return{version:CUSTOMER_FINANCIAL_VERSION,request_key:intent.request_key,request_hash:intent.request_hash,actor_uid:intent.actor_uid,service_id:intent.service_id,order_id:intent.body.order_id,kind,outcome:outcome??({change_price:'price-changed',confirm_offline:'offline-paid',refund_create:'refund-created',refund_return:'return-approved',refund_refuse:'refused',refund_execute:'balance-settled',refund_remark:'refund-remark-saved'}[kind]),evidence,created_at:2208988800};}
export function financialExecution(intent:CustomerFinancialIntent,status='BALANCE_SUCCESS'){return{version:'customer-work-financial-execution-v1',request_key:intent.request_key,request_hash:intent.request_hash,refund_id:1,status,completed:['SUCCESS','BALANCE_SUCCESS'].includes(status),verified:['SUCCESS','BALANCE_SUCCESS'].includes(status),can_resume:false};}
export function runCustomerFinancialPureTests(assert:{equal:(a:unknown,b:unknown)=>void;deepEqual:(a:unknown,b:unknown)=>void;throws:(fn:()=>unknown,pattern?:RegExp)=>void},order:unknown,review:unknown){
 const legacy=review as Record<string,unknown>,evidence=legacy.return_evidence as Record<string,unknown>;
 for(const value of ['', ' 第一行\n第二行 ', '第一行\r\n第二行', '第一行\r第二行', '第一行\t😀第二行']){
  assert.equal(financialDisplayText(value,255),true);
  assert.equal(isCustomerFinancialRefundReview({...legacy,remark:value,return_evidence:{...evidence,reason:value,explain:value}}),true);
 }
 for(const [key,max]of [['remark',255],['reason',10000],['explain',10000]] as const){
  const update=(value:string)=>key==='remark'?{...legacy,remark:value}:{...legacy,return_evidence:{...evidence,[key]:value}};
  assert.equal(isCustomerFinancialRefundReview(update('😀'.repeat(max))),true);
  assert.equal(isCustomerFinancialRefundReview(update('😀'.repeat(max+1))),false);
  for(const value of ['\u0000','\u0001','\u0008','\u000b','\u000c','\u000e','\u001f','\u007f','\ud800','\udfff'])assert.equal(isCustomerFinancialRefundReview(update(value)),false);
 }
 for(const key of ['phone','express_name','express_no'])for(const value of ['bad\ntext','bad\rtext','bad\ttext'])assert.equal(isCustomerFinancialRefundReview({...legacy,return_evidence:{...evidence,[key]:value}}),false);
 for(const value of ['第一行\n第二行','第一行\r\n第二行','第一行\t第二行']){
  assert.equal(financialText(value,255,true),false);assert.throws(()=>financialReason(value));
  for(const kind of ['refund_create','refund_refuse','refund_remark'] as const){const input=financialIntent(kind).body,key=kind==='refund_remark'?'remark':'reason';assert.equal(isCustomerFinancialInput({...input,payload:{...input.payload,[key]:value}},kind),false);}
 }
 assert.deepEqual(parseCustomerWorkQuery('refund','id=ORDER_1&listId=1'),{orderId:'ORDER_1'});assert.equal(resolveCustomerWorkPageRoute('/pages/admin/refund/index','id=ORDER_1&listId=1'),'/pages/customer-work/refund?orderId=ORDER_1');
 for(const query of ['id=ORDER_1&orderId=ORDER_1','orderId=ORDER_1&listId=01','orderId=ORDER_1&listId=2147483648','orderId=ORDER_1&cart_id=41','orderId=ORDER_1&orderId=ORDER_1','listId=1'])assert.throws(()=>parseCustomerWorkQuery('refund',query));
 assert.equal(financialAmount('000.1'),'0.10');assert.equal(financialAmount('0'),'0.00');assert.equal(financialAmount('9999999999.99'),'9999999999.99');assert.equal(financialCents('21474836.47'),2147483647n);for(const amount of ['1e2','-0.10','1.001','Infinity','10000000000',''])assert.throws(()=>financialAmount(amount));for(const amount of ['00.10','1.0','-0.00'])assert.equal(financialMoney(amount),false);
 assert.equal(financialSignedMoney('-0.10'),true);assert.equal(financialSignedMoney('-0.00'),false);assert.equal(financialEpoch(2208988800),true);assert.equal(financialId(2208988800),false);assert.equal(financialReason(' 😀 '),'😀');assert.equal(financialReason('😀'.repeat(255)).length,510);for(const text of ['😀'.repeat(256),'\u0000','\ud800','   '])assert.throws(()=>financialReason(text));
 assert.equal(isCustomerFinancialOrder(order),true);assert.equal(isCustomerFinancialRefundReview(review),true);const o=order as Record<string,unknown>,r=review as Record<string,unknown>;assert.equal(isCustomerFinancialOrder({...o,change_price:'-0.10'}),true);assert.equal(isCustomerFinancialOrder({...o,change_price:'-0.00'}),false);assert.equal(isCustomerFinancialOrder({...o,order_id:'1'}),false);assert.equal(isCustomerFinancialOrder({...o,payment_order_id:2147483648}),false);assert.equal(isCustomerFinancialOrder({...o,requested_order_no:'ORDER_2'}),false);assert.equal(isCustomerFinancialRefundReview({...r,refund_no:'REFUND_2'}),false);assert.equal(isCustomerFinancialRefundReview({...r,return_evidence:{...(r.return_evidence as object),phone:'bad\ntext'}}),false);
 const envelope={version:'customer-work-read-v1',actor_uid:11,principal:{kind:'customer-order-manager',service_id:1,scope:'global'},scope_key:'a'.repeat(64),consistency_key:'b'.repeat(64),data:order},authority={scope_key:'a'.repeat(64),consistency_key:'b'.repeat(64),principal:{service_id:1}};assert.equal(parseCustomerFinancialEnvelope(envelope,11,isCustomerFinancialOrder,authority).data,order);for(const update of [{actor_uid:12},{scope_key:'c'.repeat(64)},{consistency_key:'e'.repeat(64)},{principal:{...envelope.principal,service_id:2}},{data:{...o,metric_scopes:{}}}])assert.throws(()=>parseCustomerFinancialEnvelope({...envelope,...update},11,isCustomerFinancialOrder,authority));
 const q={version:'customer-work-financial-refund-quote-v1',order_id:1,order_no:'ORDER_1',payment_order_id:1,order_revision:'c'.repeat(64),financial_revision:'d'.repeat(64),mode:'items',items:[{cart_row_id:41,cart_id:'opaque-901',cart_num:1,max_num:3,title:'商品',sku:'款式',image:'/static/logo.png',line_price:'10.00'}],quoted_price:'10.00',quote_fingerprint:'f'.repeat(64),refund_time_days:7,received_at:2208988800};assert.equal(isCustomerFinancialRefundQuote(q),true);for(const items of [[{...q.items[0],cart_row_id:'opaque-901'}],[{...q.items[0],cart_num:4}],[q.items[0],q.items[0]],Array.from({length:101},(_,i)=>({...q.items[0],cart_row_id:i+1})),[{...q.items[0],image:'javascript:unsafe()'}]])assert.equal(isCustomerFinancialRefundQuote({...q,items}),false);
 for(const kind of CUSTOMER_FINANCIAL_KINDS){const intent=financialIntent(kind);assert.equal(isCustomerFinancialInput(intent.body,kind),true);assert.equal(isCustomerFinancialIntent(intent),true);assert.equal(isCustomerFinancialIntent({...intent,admin_id:1}),false);assert.equal(isCustomerFinancialIntent({...intent,request_hash:'0'.repeat(64)}),false);assert.equal(isCustomerFinancialInput({...intent.body,kind},kind),false);const receipt=financialReceipt(intent),result={receipt,replayed:false,execution:kind==='refund_execute'?financialExecution(intent):null};assert.equal(customerFinancialTerminal(parseCustomerFinancialResult(result,intent)),true);for(const changed of [{actor_uid:12},{order_id:2},{service_id:2},{request_hash:'0'.repeat(64)},{evidence:{...receipt.evidence,pii:'private'}}])assert.throws(()=>parseCustomerFinancialResult({...result,receipt:{...receipt,...changed}},intent));assert.equal(customerFinancialTerminal(parseCustomerFinancialResult({receipt:{...receipt,service_id:0,outcome:'abandoned',evidence:{}},replayed:false,execution:null},intent)),true);}
 const execute=financialIntent(),body=execute.body,p=body.payload;assert.equal(isCustomerFinancialRefundReview({...r,apply_type:0}),true);assert.equal(isCustomerFinancialInput({...financialIntent('refund_refuse').body,payload:{...financialPayloads.refund_refuse,decision:{apply_type:0,refund_type:0,received:false}}},'refund_refuse'),true);assert.equal(isCustomerFinancialInput({...body,payload:{...p,decision:{apply_type:0,refund_type:0,received:false}}},'refund_execute'),false);for(const state of [3,6])assert.equal(isCustomerFinancialInput({...body,payload:{...p,decision:{apply_type:1,refund_type:state,received:false}}},'refund_execute'),false);for(const [apply_type,refund_type,received,expected]of [[2,4,true,false],[2,5,false,false],[2,5,true,true],[3,4,true,true],[3,5,true,true],[3,2,true,false]] as const)assert.equal(isCustomerFinancialInput({...body,payload:{...p,decision:{apply_type,refund_type,received}}},'refund_execute'),expected);
 for(const apply_type of [1,4])assert.equal(isCustomerFinancialInput({...financialIntent('refund_return').body,payload:{...financialPayloads.refund_return,decision:{apply_type,refund_type:0,received:false}}},'refund_return'),false);for(const kind of ['refund_create','refund_refuse','refund_remark'] as const){const input=financialIntent(kind).body,key=kind==='refund_remark'?'remark':'reason';assert.equal(isCustomerFinancialInput({...input,payload:{...input.payload,[key]:' 😀 '}},kind),false);assert.equal(isCustomerFinancialInput({...input,payload:{...input.payload,[key]:'😀'.repeat(255)}},kind),true);assert.equal(isCustomerFinancialInput({...input,payload:{...input.payload,[key]:'😀'.repeat(256)}},kind),false);}
 const balanced=financialReceipt(execute),unknown={receipt:balanced,replayed:true,execution:financialExecution(execute,'UNKNOWN')};assert.equal(customerFinancialTerminal(parseCustomerFinancialResult(unknown,execute)),false);assert.equal(customerFinancialTerminal(parseCustomerFinancialResult({...unknown,execution:null},execute)),false);assert.throws(()=>parseCustomerFinancialResult({...unknown,execution:financialExecution(execute,'SUCCESS')},execute));
 const provider={...balanced,outcome:'provider-admitted',evidence:{refund_id:1,refund_no:'REFUND_1',payment_order_id:1,uid:21,store_id:0,supplier_id:0,provider:'wechat',out_refund_no:'CNSR1',request_amount:100,total_amount:1000,verified:true}};for(const status of ['REQUESTING','PROCESSING','UNKNOWN','CLOSED','ABNORMAL','FAILED'])assert.equal(customerFinancialTerminal(parseCustomerFinancialResult({receipt:provider,replayed:true,execution:financialExecution(execute,status)},execute)),false);assert.equal(customerFinancialTerminal(parseCustomerFinancialResult({receipt:provider,replayed:true,execution:financialExecution(execute,'SUCCESS')},execute)),true);assert.throws(()=>parseCustomerFinancialResult({receipt:provider,replayed:true,execution:financialExecution(execute)},execute));for(const changed of [{out_refund_no:'CNSR2'},{payment_order_id:2},{request_amount:99},{total_amount:1}])assert.throws(()=>parseCustomerFinancialResult({receipt:{...provider,evidence:{...provider.evidence,...changed}},replayed:false,execution:null},execute));
}
