import {customerWorkSha256} from '../../../common/customerWorkIntent';
import {parseCustomerWorkQuery,resolveCustomerWorkPageRoute} from '../../../common/customerWorkRoute';
import {CUSTOMER_WRITEOFF_VERSION,customerWorkCanonicalJson,writeoffIntentHash,writeoffLookupFingerprint,writeoffLookupValue,decodeCustomerWriteoffScan,isCustomerWorkWriteoffTarget,isCustomerWorkWriteoffInput,isCustomerWorkWriteoffIntent,isCustomerWorkWriteoffRecords,isCustomerWorkWriteoffLookup,parseCustomerWorkWriteoffResult,customerWriteoffTerminal} from './customerWorkWriteoff';
import type {CustomerWorkWriteoffTarget,CustomerWorkWriteoffIntent,CustomerWorkWriteoffInput} from '../types/customerWorkWriteoff';
const h=(letter:string)=>letter.repeat(64),digest=(v:unknown)=>customerWorkSha256(customerWorkCanonicalJson(v));
export function writeoffTarget(overrides:Partial<CustomerWorkWriteoffTarget>={}):CustomerWorkWriteoffTarget{return{version:'customer-work-writeoff-target-v1',requested_order_no:'PUBLIC_ORDER_42',id:42,order_no:'PUBLIC_ORDER_42',root_order_id:42,root_order_no:'PUBLIC_ORDER_42',uid:21,store_id:1,supplier_id:0,type:0,product_type:4,paid:1,status:0,shipping_type:2,delivery_type:'',code:'012345678901',order_revision:h('c'),writeoff_revision:h('d'),target_fingerprint:h('e'),readiness:{writes:true,reason:''},actions:{writeoff:{available:true,reason:''}},cashier_origin:{eligible:false,version:'',proof_hash:null,reason:'当前不是无门店收银来源'},carts:[{cart_row_id:41,cart_id:'opaque-901',cart_num:1,product_id:7,product_type:4,product_name:'真实次卡<script>unsafe()</script>',image:'/static/logo.png',sku:'原规格',write_times:3,write_surplus_times:3,is_writeoff:0,write_start:0,write_end:0,sale_price:{source:'legacy-root-true-price',version:'customer-writeoff-sale-price-v1',snapshot_hash:h('f'),price_hash:h('a'),next_price:'7.00',all_remaining_price:'21.00',reason:''}}],...overrides};}
export function writeoffIntent(target=writeoffTarget(),quantity=1):CustomerWorkWriteoffIntent{const body:CustomerWorkWriteoffInput={version:CUSTOMER_WRITEOFF_VERSION,scope_key:h('a'),order_id:target.id,expected_order_revision:target.order_revision,expected_writeoff_revision:target.writeoff_revision,payload:{order_no:target.order_no,root_order_id:target.root_order_id,root_order_no:target.root_order_no,code:target.code,target_fingerprint:target.target_fingerprint,items:[{cart_row_id:41,writeoff_num:quantity}]}};return{version:'customer-work-writeoff-pending-v1',actor_uid:11,service_id:1,scope_key:body.scope_key,kind:'writeoff',request_key:'12345678-1234-4123-8123-123456789abc',request_hash:writeoffIntentHash(11,body),order_no:target.order_no,root_order_id:target.root_order_id,root_order_no:target.root_order_no,body,endpoint:'/mobile/work/writeoff/execute',method:'POST',created_at:2208988800};}
export function writeoffSettlement(target=writeoffTarget()){return{version:'customer-writeoff-settlement-v1',take_delivery_status_id:81,supplier_rows:[],reward_rows:[],brokerage_rows:[],account_deltas:[],paid_root:{order_id:target.root_order_id,order_no:target.root_order_no,uid:target.uid,pay_type:'cash',pay_price:'21.00',paid:1,identity_hash:h('b')},paid_outbox_rows:[],new_paid_outbox_count:0};}
export function writeoffProof(intent=writeoffIntent(),complete=false){const items=intent.body.payload.items;return{receipt:{version:CUSTOMER_WRITEOFF_VERSION,request_key:intent.request_key,request_hash:intent.request_hash,actor_uid:intent.actor_uid,service_id:intent.service_id,order_id:intent.body.order_id,kind:'writeoff',outcome:complete?'written-off':'partial-writtenoff',evidence:{verified:true,order_completed:complete,status:complete?2:5,physical_order_id:intent.body.order_id,root_order_id:intent.root_order_id,writeoff_rows:items.map((item,i)=>({writeoff_id:91+i,cart_row_id:item.cart_row_id,opaque_cart_id:'opaque-901',quantity:item.writeoff_num,before_remaining:complete?item.writeoff_num:3,after_remaining:complete?0:3-item.writeoff_num,writeoff_price:(item.writeoff_num*7).toFixed(2),snapshot_hash:h('f'),sale_price_hash:h('a')})),before_code_hash:digest(intent.body.payload.code),after_code_hash:digest(complete?'':'012345678902'),post_order_revision:h('f'),post_writeoff_revision:h('b'),settlement:complete?writeoffSettlement(writeoffTarget({id:intent.body.order_id,root_order_id:intent.root_order_id,root_order_no:intent.root_order_no})):null},created_at:2208988800},replayed:false,execution:{version:'customer-work-writeoff-execution-v1',request_key:intent.request_key,request_hash:intent.request_hash,order_id:intent.body.order_id,state:'SQL_COMMITTED',committed:true,verified:true,order_completed:complete,reason:''}};}
export function runCustomerWriteoffPureTests(assert:{equal:(a:unknown,b:unknown)=>void;deepEqual:(a:unknown,b:unknown)=>void;throws:(fn:()=>unknown,pattern?:RegExp)=>void}){
 const target=writeoffTarget(),intent=writeoffIntent(),proof=writeoffProof();assert.equal(isCustomerWorkWriteoffTarget(target),true);assert.equal(isCustomerWorkWriteoffInput(intent.body),true);assert.equal(isCustomerWorkWriteoffIntent(intent),true);assert.equal(customerWriteoffTerminal(parseCustomerWorkWriteoffResult(proof,intent)),true);
 const guest=writeoffTarget({uid:0,store_id:0,cashier_origin:{eligible:true,version:'cashier-second-card-origin-v1',proof_hash:h('a'),reason:'真实收银创建与付款已证明'}});guest.carts[0]!.sale_price.next_price=guest.carts[0]!.sale_price.all_remaining_price='0.00';assert.equal(isCustomerWorkWriteoffTarget(guest),true);assert.equal(isCustomerWorkWriteoffTarget({...guest,cashier_origin:{...guest.cashier_origin,eligible:false}}),false);
 for(const change of [{id:'42'},{requested_order_no:'42'},{order_no:' 42'},{root_order_id:0},{unknown:true},{carts:[{...target.carts[0],cart_row_id:'opaque-901'}]},{carts:[{...target.carts[0],write_surplus_times:4}]},{carts:[{...target.carts[0],sale_price:{...target.carts[0]!.sale_price,next_price:'07.00'}}]},{carts:[target.carts[0],target.carts[0]]},{carts:[{...target.carts[0],image:'javascript:unsafe()'}]}])assert.equal(isCustomerWorkWriteoffTarget({...target,...change}),false);
 for(const items of [[],[{cart_row_id:41,writeoff_num:0}],[{cart_row_id:'opaque-901',writeoff_num:1}],[{cart_row_id:41,writeoff_num:'1'}],[{cart_row_id:41,writeoff_num:1},{cart_row_id:41,writeoff_num:1}],[{cart_row_id:42,writeoff_num:1},{cart_row_id:41,writeoff_num:1}],[{cart_row_id:41,writeoff_num:1,price:'7.00'}]])assert.equal(isCustomerWorkWriteoffInput({...intent.body,payload:{...intent.body.payload,items}}),false);
 assert.equal(isCustomerWorkWriteoffIntent({...intent,body:{...intent.body,payload:{...intent.body.payload,code:'012345678902'}}}),false);assert.equal(isCustomerWorkWriteoffInput({...intent.body,admin_id:1}),false);
 assert.deepEqual(parseCustomerWorkQuery('writeoff','orderId=42&orderNo=PUBLIC_ORDER_42'),{orderId:'42',orderNo:'PUBLIC_ORDER_42'});assert.deepEqual(parseCustomerWorkQuery('writeoffRecords',{legacyOrderId:'42'}),{legacyOrderId:'42'});assert.equal(resolveCustomerWorkPageRoute('/pages/admin/writeOffCard/index','id=42&auth=1'),'/pages/customer-work/writeoff?legacyOrderId=42');assert.equal(resolveCustomerWorkPageRoute('/pages/admin/offOrderResult/index','id=42'),'/pages/customer-work/writeoffResult?legacyOrderId=42');assert.equal(resolveCustomerWorkPageRoute('/pages/admin/order_cancellation/index','auth=3'),'/pages/operator/writeoff?entry=legacy-auto&next=scanning');
 for(const query of ['orderId=42','orderId=042&orderNo=PUBLIC_ORDER_42','id=42&orderNo=PUBLIC_ORDER_42','orderId=42&orderNo=PUBLIC_ORDER_42&orderId=42','legacyOrderId=42&orderNo=PUBLIC_ORDER_42','orderId=42&orderNo=PUBLIC_ORDER_42&cart_id=41'])assert.throws(()=>parseCustomerWorkQuery('writeoff',query));assert.throws(()=>parseCustomerWorkQuery('writeoffResult','orderId=42'));
 assert.equal(resolveCustomerWorkPageRoute('/pages/admin/order_cancellation/index',''),'/pages/operator/writeoff');assert.equal(resolveCustomerWorkPageRoute('/pages/admin/order_cancellation/index','auth=1'),'/pages/customer-work/scanning');
 assert.deepEqual(decodeCustomerWriteoffScan('012345678901'),{namespace:'auto',value:'012345678901'});assert.deepEqual(decodeCustomerWriteoffScan('CODE_128,012345678901','wechat'),{namespace:'auto',value:'012345678901'});assert.deepEqual(decodeCustomerWriteoffScan('%2Fpages%2Fadmin%2Forder_cancellation%2Findex%3Fcode%3D012345678901','scene'),{namespace:'order-code',value:'012345678901'});
 for(const value of ['https://bad.test/pages/admin/order_cancellation/index?code=012345678901','/pages/admin/order_cancellation/index?code=012345678901&code=012345678901','/pages/admin/order_cancellation/index?code=012345678901&uid=1','%252Fpages%252Fadmin%252Forder_cancellation%252Findex','prefix 012345678901 suffix','CODE_BAD,012345678901','012345678901\n'])assert.throws(()=>decodeCustomerWriteoffScan(value,value.startsWith('%')?'scene':value.includes(',')?'wechat':'raw'));
 assert.equal(writeoffLookupValue('member-barcode','a'.repeat(32)),true);assert.equal(writeoffLookupValue('member-barcode','a'.repeat(33)),false);assert.equal(writeoffLookupValue('legacy-order-id','00042'),false);
 const lookup={version:'customer-work-writeoff-lookup-v1',namespace:'auto',lookup_kind:'order-code',lookup_fingerprint:writeoffLookupFingerprint('auto',target.code),orders:[target]};assert.equal(isCustomerWorkWriteoffLookup(lookup),true);assert.equal(isCustomerWorkWriteoffLookup({...lookup,orders:[target,target]}),false);
 const operator={kind:'customer',actor_uid:11,service_id:1,admin_id:null,staff_id:null,delivery_id:null,request_key:intent.request_key,request_hash:intent.request_hash},row={record_id:91,cart_row_id:41,cart_id:'opaque-901',writeoff_num:1,writeoff_price:'7.00',created_at:2208988800,operator},records={version:'customer-work-writeoff-records-v1',order_id:42,order_no:target.order_no,root_order_id:42,root_order_no:target.order_no,list:[row],count:1,page:1,limit:20,has_more:false};assert.equal(isCustomerWorkWriteoffRecords(records),true);assert.equal(isCustomerWorkWriteoffRecords({...records,list:[{...row,operator:{...operator,actor_uid:null}}]}),false);assert.equal(isCustomerWorkWriteoffRecords({...records,has_more:true}),false);assert.equal(isCustomerWorkWriteoffRecords({...records,list:[{...row,operator:{...operator,kind:'unknown'}}]}),false);
 for(const failure of ['hash','actor','order','counter','price','extra','settlement','execution']){const value=JSON.parse(customerWorkCanonicalJson(proof));if(failure==='hash')value.receipt.request_hash=h('0');if(failure==='actor')value.receipt.actor_uid=21;if(failure==='order')value.receipt.evidence.physical_order_id=1;if(failure==='counter')value.receipt.evidence.writeoff_rows[0].after_remaining=1;if(failure==='price')value.receipt.evidence.writeoff_rows[0].writeoff_price='7';if(failure==='extra')value.receipt.evidence.admin_id=1;if(failure==='settlement')value.receipt.evidence.settlement={};if(failure==='execution')value.execution.verified=false;assert.throws(()=>parseCustomerWorkWriteoffResult(value,intent));}
 const unknown={...proof,execution:{...proof.execution,state:'UNKNOWN',committed:false,verified:false,order_completed:false,reason:'原业务证据待核对'}};assert.equal(customerWriteoffTerminal(parseCustomerWorkWriteoffResult(unknown,intent)),false);assert.equal(customerWriteoffTerminal(parseCustomerWorkWriteoffResult({receipt:null,replayed:true,execution:null},intent)),false);
 const full=writeoffProof(writeoffIntent(target,3),true);assert.equal(customerWriteoffTerminal(parseCustomerWorkWriteoffResult(full,writeoffIntent(target,3))),true);const malformed=JSON.parse(customerWorkCanonicalJson(full));malformed.receipt.evidence.settlement.paid_root.order_no='WRONG';assert.throws(()=>parseCustomerWorkWriteoffResult(malformed,writeoffIntent(target,3)));
}
