import { customerWorkCanonicalJson,customerWorkSha256 } from '../../../common/customerWorkIntent';
import { customerWorkRecord,customerWorkImage } from './customerWork';
import { customerWorkInteger,customerWorkHash,customerWorkText,customerWorkUuid } from './customerWorkFulfillmentContract';
import type { CustomerWorkUser,CustomerWorkUserDetail,CustomerWorkUserMeta,CustomerWorkUserEnvelope,CustomerWorkUserList,CustomerWorkUserDetailData,CustomerWorkUserGroups,CustomerWorkUserLevels,CustomerWorkUserLabels,CustomerWorkUserCouponCandidates,CustomerWorkUserCoupons,CustomerWorkUserKind,CustomerWorkUserBody,CustomerWorkUserIntent,CustomerWorkUserReceipt,CustomerWorkUserAction,CustomerWorkUserLabel,CustomerWorkUserActions } from '../types/customerWorkUsers';
export { customerWorkCanonicalJson,customerWorkUuid };
export const CUSTOMER_WORK_USER_VERSION='customer-work-user-operation-v1' as const;
export const CUSTOMER_WORK_USER_KINDS:CustomerWorkUserKind[]=['replace_level','replace_group','replace_labels','grant_coupons','adjust_membership','adjust_money','adjust_integral'];
export const CUSTOMER_WORK_USER_NAMES:Record<CustomerWorkUserKind,string>={replace_level:'修改等级',replace_group:'修改分组',replace_labels:'替换平台标签',grant_coupons:'赠送优惠券',adjust_membership:'调整会员时长',adjust_money:'调整余额',adjust_integral:'调整积分'};
const keys=(v:Record<string,unknown>,names:string[])=>Object.keys(v).sort().join(',')===[...names].sort().join(',');
const id=(v:unknown):v is number=>customerWorkInteger(v,1),flag=(v:unknown)=>v===0||v===1;
const text=(v:unknown,max=Number.POSITIVE_INFINITY):v is string=>customerWorkText(v,Number.POSITIVE_INFINITY)&&Array.from(v).length<=max;
const distinct=(v:unknown,max=Number.POSITIVE_INFINITY,min=0):v is number[]=>Array.isArray(v)&&v.length>=min&&v.length<=max&&v.every(id)&&new Set(v).size===v.length;
const sorted=(v:unknown,max=Number.POSITIVE_INFINITY,min=0):v is number[]=>distinct(v,max,min)&&v.every((row,i)=>!i||row>v[i-1]!);
const strings=(v:unknown):v is string[]=>Array.isArray(v)&&v.every(row=>text(row));
const iso=(v:unknown)=>v===null||typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/u.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString()===v;
function assert(v:unknown,message:string):asserts v{if(!v)throw Error(message);}
export const customerWorkUserMoney=(v:unknown):v is string=>typeof v==='string'&&/^(0|[1-9]\d{0,9})\.\d{2}$/u.test(v);
const aggregateMoney=(v:unknown):v is string=>typeof v==='string'&&/^(0|[1-9]\d*)\.\d{2}$/u.test(v);
const signedMoney=(v:unknown)=>customerWorkUserMoney(v)||typeof v==='string'&&/^-[1-9]\d{0,9}\.\d{2}$/u.test(v)||typeof v==='string'&&/^-0\.\d{2}$/u.test(v);
export function customerWorkUserAmount(value:string):string{const input=value.trim();assert(/^\d{1,10}(?:\.\d{1,2})?$/u.test(input),'余额数量需为正数，最多两位小数');const [whole,fraction='']=input.split('.'),amount=whole!.replace(/^0+(?=\d)/u,'')+'.'+fraction.padEnd(2,'0');assert(customerWorkUserMoney(amount)&&amount!=='0.00','余额数量超出范围或为零');return amount;}
export function customerWorkUserPositive(value:string,max=2147483647):number{assert(/^[1-9]\d{0,9}$/u.test(value),'请填写正整数');const result=Number(value);assert(customerWorkInteger(result,1)&&result<=max,'数量超出支持范围');return result;}
export function isCustomerWorkUserMeta(v:unknown):v is CustomerWorkUserMeta{
 if(!customerWorkRecord(v)||!customerWorkRecord(v.scopes)||!keys(v.scopes,['users','groups','levels','labels','coupon_issues','wallet','paid_order_count','paid_order_value']))return false;
 const scopes=v.scopes;
 const expected={users:'global',groups:'global',levels:'global',labels:'platform',coupon_issues:'global_send',wallet:'exact_target_user',paid_order_count:'original_roots',paid_order_value:'physical_fulfillments'};
 return Object.entries(expected).every(([key,value])=>scopes[key]===value)&&customerWorkHash(v.catalog_revision)&&customerWorkInteger(v.at_time)&&customerWorkRecord(v.readiness)&&keys(v.readiness,['writes','reason'])&&typeof v.readiness.writes==='boolean'&&text(v.readiness.reason);
}
function action(v:unknown):v is CustomerWorkUserAction{return customerWorkRecord(v)&&keys(v,['available','reason'])&&typeof v.available==='boolean'&&text(v.reason);}
function userActions(v:unknown):v is CustomerWorkUserActions{return customerWorkRecord(v)&&keys(v,CUSTOMER_WORK_USER_KINDS)&&Object.values(v).every(action);}
function label(v:unknown):v is CustomerWorkUserLabel{return customerWorkRecord(v)&&id(v.id)&&text(v.label_name,255)&&text(v.color,32);}
const userFields=['uid','nickname','avatar','phone','status','deleted','group_id','group_name','level','level_name','level_status','level_grade','labels','now_money','integral','financial_diagnostics','isMember','is_money_level','is_ever_level','overdue_time','membership_active','svip_over_day','svip_overdue_time','user_revision','actions'];
export function isCustomerWorkUser(v:unknown):v is CustomerWorkUser{
 if(!customerWorkRecord(v)||!id(v.uid)||!text(v.nickname,60)||!customerWorkImage(v.avatar)||!text(v.phone,15)||!flag(v.status)||typeof v.deleted!=='boolean'||!customerWorkInteger(v.group_id)||!text(v.group_name)||!customerWorkInteger(v.level)||!text(v.level_name)||!flag(v.level_status)||(v.level_grade!==null&&!customerWorkInteger(v.level_grade))||!Array.isArray(v.labels)||!v.labels.every(row=>label(row)&&customerWorkRecord(row)&&keys(row,['id','label_name','color']))||new Set(v.labels.map(row=>row.id)).size!==v.labels.length||!(v.now_money===null||customerWorkUserMoney(v.now_money))||!(v.integral===null||customerWorkInteger(v.integral))||!strings(v.financial_diagnostics)||!flag(v.isMember)||![0,1,2,3].includes(v.is_money_level as number)||!flag(v.is_ever_level)||!customerWorkInteger(v.overdue_time)||typeof v.membership_active!=='boolean'||!(v.svip_over_day===null||customerWorkInteger(v.svip_over_day))||!text(v.svip_overdue_time)||!customerWorkHash(v.user_revision)||!userActions(v.actions))return false;
 if(v.deleted&&Object.values(v.actions).some(a=>a.available)||v.is_ever_level===1&&(v.actions.adjust_membership.available||v.svip_over_day!==null)||v.now_money===null&&(v.actions.adjust_money.available||!v.financial_diagnostics.length)||v.integral===null&&(v.actions.adjust_integral.available||!v.financial_diagnostics.length))return false;
 return v.isMember===((v.is_money_level as 0|1|2|3)>0?1:0);
}
export function isCustomerWorkUserDetail(v:unknown):v is CustomerWorkUserDetail{
 if(!isCustomerWorkUser(v)||!customerWorkRecord(v)||!keys(v,[...userFields,'real_name','birthday','birthday_epoch','card_id','addres','add_time','_add_time','order_total_count','order_total_price','coupon_num'])||!text(v.real_name,25)||!text(v.card_id,20)||!text(v.addres,255)||!customerWorkInteger(v.birthday_epoch,-2147483648)||!customerWorkInteger(v.add_time)||!text(v._add_time)||!customerWorkInteger(v.order_total_count)||!aggregateMoney(v.order_total_price)||!customerWorkInteger(v.coupon_num))return false;
 return v.birthday===''||typeof v.birthday==='string'&&/^\d{4}-\d{2}-\d{2}$/u.test(v.birthday)&&Number.isFinite(Date.parse(v.birthday+'T00:00:00Z'))&&new Date(v.birthday+'T00:00:00Z').toISOString().slice(0,10)===v.birthday;
}
function paged(v:Record<string,unknown>){return Array.isArray(v.list)&&customerWorkInteger(v.count)&&id(v.page)&&v.page<=1000000&&id(v.limit)&&v.limit<=100&&v.list.length<=v.limit&&typeof v.has_more==='boolean'&&v.has_more===((v.page-1)*v.limit+v.list.length<v.count);}
export function isCustomerWorkUserList(v:unknown):v is CustomerWorkUserList{return isCustomerWorkUserMeta(v)&&customerWorkRecord(v)&&paged(v)&&Array.isArray(v.list)&&v.list.every(row=>isCustomerWorkUser(row)&&customerWorkRecord(row)&&keys(row,userFields)&&(!v.readiness.writes?!Object.values(row.actions).some(a=>a.available):true))&&new Set(v.list.map(row=>row.uid)).size===v.list.length;}
export function isCustomerWorkUserDetailData(v:unknown):v is CustomerWorkUserDetailData{return isCustomerWorkUserMeta(v)&&customerWorkRecord(v)&&isCustomerWorkUserDetail(v.user)&&(!v.readiness.writes?!Object.values(v.user.actions).some(a=>a.available):true);}
export function isCustomerWorkUserGroups(v:unknown):v is CustomerWorkUserGroups{return isCustomerWorkUserMeta(v)&&customerWorkRecord(v)&&Array.isArray(v.list)&&v.list.every(row=>customerWorkRecord(row)&&keys(row,['id','group_name'])&&id(row.id)&&text(row.group_name,64))&&new Set(v.list.map(row=>row.id)).size===v.list.length&&customerWorkInteger(v.count)&&v.count===v.list.length;}
export function isCustomerWorkUserLevels(v:unknown):v is CustomerWorkUserLevels{return isCustomerWorkUserMeta(v)&&customerWorkRecord(v)&&Array.isArray(v.list)&&v.list.every(row=>customerWorkRecord(row)&&keys(row,['id','name','grade','image','icon'])&&id(row.id)&&text(row.name,255)&&customerWorkInteger(row.grade)&&customerWorkImage(row.image)&&customerWorkImage(row.icon))&&new Set(v.list.map(row=>row.id)).size===v.list.length&&customerWorkInteger(v.count)&&v.count===v.list.length;}
export function isCustomerWorkUserLabels(v:unknown):v is CustomerWorkUserLabels{
 if(!isCustomerWorkUserMeta(v)||!customerWorkRecord(v)||!customerWorkInteger(v.uid)||!Array.isArray(v.list)||!customerWorkInteger(v.count)||v.count!==v.list.length)return false;
 const groups=new Set<number>(),ids=new Set<number>();return v.list.every(row=>{if(!customerWorkRecord(row)||!keys(row,['id','name','sort','label'])||!id(row.id)||groups.has(row.id)||!text(row.name,255)||!customerWorkInteger(row.sort,-2147483648)||!Array.isArray(row.label))return false;groups.add(row.id);return row.label.every(l=>{if(!customerWorkRecord(l)||!keys(l,['id','label_name','color','label_cate','selected'])||!label(l)||ids.has(l.id as number)||l.label_cate!==row.id||typeof l.selected!=='boolean')return false;ids.add(l.id as number);return true;});});
}
export function isCustomerWorkUserCouponCandidates(v:unknown):v is CustomerWorkUserCouponCandidates{
 if(!isCustomerWorkUserMeta(v)||!customerWorkRecord(v)||!paged(v)||!Array.isArray(v.list))return false;
 return v.list.every(row=>customerWorkRecord(row)&&keys(row,['id','cid','coupon_title','type','coupon_type','coupon_price','use_min_price','total_count','remain_count','is_permanent','receive_limit','receive_type','day','start_time','end_time','use_start_time','use_end_time','coupon_time','issue_revision','action'])&&id(row.id)&&customerWorkInteger(row.cid)&&text(row.coupon_title,255)&&[1,2].includes(row.type as number)&&[0,1,2,3].includes(row.coupon_type as number)&&signedMoney(row.coupon_price)&&signedMoney(row.use_min_price)&&['total_count','remain_count','receive_limit','day'].every(key=>customerWorkInteger(row[key]))&&flag(row.is_permanent)&&row.receive_type===3&&['start_time','end_time','use_start_time','use_end_time'].every(key=>iso(row[key]))&&text(row.coupon_time)&&customerWorkHash(row.issue_revision)&&action(row.action)&&(!row.action.available||v.readiness.writes&&customerWorkUserMoney(row.coupon_price)&&customerWorkUserMoney(row.use_min_price)&&Array.from(row.coupon_title as string).length<=64))&&new Set(v.list.map(row=>row.id)).size===v.list.length;
}
export function isCustomerWorkUserCoupons(v:unknown):v is CustomerWorkUserCoupons{
 if(!isCustomerWorkUserMeta(v)||!customerWorkRecord(v)||!id(v.uid)||!paged(v)||!Array.isArray(v.list))return false;
 return v.list.every(row=>customerWorkRecord(row)&&keys(row,['id','uid','issue_coupon_id','template_id','coupon_title','coupon_price','use_min_price','status','is_fail','type','coupon_type','receive_source','receive_time','start_time','end_time','use_time','availability','availability_message'])&&id(row.id)&&row.uid===v.uid&&customerWorkInteger(row.issue_coupon_id)&&(row.template_id===null||customerWorkInteger(row.template_id))&&text(row.coupon_title,64)&&signedMoney(row.coupon_price)&&signedMoney(row.use_min_price)&&row.status===0&&flag(row.is_fail)&&[1,2].includes(row.type as number)&&(row.coupon_type===null||[0,1,2,3].includes(row.coupon_type as number))&&text(row.receive_source,32)&&customerWorkInteger(row.receive_time)&&['start_time','end_time','use_time'].every(key=>iso(row[key]))&&['available','future','expired','invalid'].includes(row.availability as string)&&text(row.availability_message)&&(row.availability==='invalid'||customerWorkUserMoney(row.coupon_price)&&customerWorkUserMoney(row.use_min_price)))&&new Set(v.list.map(row=>row.id)).size===v.list.length;
}
export function parseCustomerWorkUserEnvelope<T>(v:unknown,actorUid:number,guard:(data:unknown)=>data is T,authority?:{scope_key:string;principal:{service_id:number}},consistencyKey?:string):CustomerWorkUserEnvelope<T>{assert(customerWorkRecord(v)&&v.version==='customer-work-user-read-v1'&&v.actor_uid===actorUid&&customerWorkRecord(v.principal)&&keys(v.principal,['kind','service_id','scope'])&&v.principal.kind==='customer-order-manager'&&id(v.principal.service_id)&&v.principal.scope==='global'&&customerWorkHash(v.scope_key)&&customerWorkHash(v.consistency_key)&&guard(v.data),'用户响应与当前客服身份不匹配，请重新读取');if(authority)assert(v.scope_key===authority.scope_key&&v.principal.service_id===authority.principal.service_id,'用户管理权限已变化，请重新读取');if(consistencyKey)assert(v.consistency_key===consistencyKey,'用户、目录或优惠券已变化，请重新读取');return v as unknown as CustomerWorkUserEnvelope<T>;}
export function customerWorkUserEndpoint(kind:CustomerWorkUserKind,uids:number[]):string{assert(CUSTOMER_WORK_USER_KINDS.includes(kind)&&sorted(uids,100,1),'请选择1至100个有效用户');if(['replace_level','adjust_membership','adjust_money','adjust_integral'].includes(kind))assert(uids.length===1,'此操作必须对应一个用户');return '/mobile/work/users/'+kind.replaceAll('_','-');}
export function customerWorkUserIntentHash(actor_uid:number,kind:string,input:CustomerWorkUserBody){return customerWorkSha256(customerWorkCanonicalJson({version:CUSTOMER_WORK_USER_VERSION,actor_uid,kind,input}));}
export function isCustomerWorkUserBody(v:unknown,kind:CustomerWorkUserKind):v is CustomerWorkUserBody{
 if(!customerWorkRecord(v)||!keys(v,['version','scope_key','targets','expected_catalog_revision','payload'])||v.version!==CUSTOMER_WORK_USER_VERSION||!customerWorkHash(v.scope_key)||!customerWorkHash(v.expected_catalog_revision)||!Array.isArray(v.targets)||!v.targets.length||v.targets.length>100||!customerWorkRecord(v.payload)||!CUSTOMER_WORK_USER_KINDS.includes(kind))return false;
 let prior=0;for(const target of v.targets){if(!customerWorkRecord(target)||!keys(target,['uid','expected_user_revision'])||!id(target.uid)||target.uid<=prior||!customerWorkHash(target.expected_user_revision))return false;prior=target.uid;}
 const p=v.payload;if(kind==='replace_group')return keys(p,['group_id'])&&id(p.group_id);if(kind==='replace_labels')return keys(p,['label_ids'])&&sorted(p.label_ids,100);if(kind==='grant_coupons')return keys(p,['issue_id','expected_issue_revision'])&&id(p.issue_id)&&customerWorkHash(p.expected_issue_revision);if(v.targets.length!==1)return false;if(kind==='replace_level')return keys(p,['level_id'])&&id(p.level_id);if(p.direction!=='add'&&p.direction!=='subtract')return false;if(kind==='adjust_membership')return keys(p,['direction','days'])&&id(p.days)&&p.days<=999999;return keys(p,['direction','amount'])&&(kind==='adjust_money'?customerWorkUserMoney(p.amount)&&p.amount!=='0.00':id(p.amount));
}
export function isCustomerWorkUserIntent(v:unknown):v is CustomerWorkUserIntent{if(!customerWorkRecord(v)||!keys(v,['version','actor_uid','service_id','scope_key','kind','request_key','request_hash','body','endpoint','method','created_at'])||v.version!=='customer-work-user-pending-v1'||!id(v.actor_uid)||!id(v.service_id)||!customerWorkHash(v.scope_key)||!CUSTOMER_WORK_USER_KINDS.includes(v.kind as CustomerWorkUserKind)||!customerWorkUuid(v.request_key)||!customerWorkHash(v.request_hash)||!isCustomerWorkUserBody(v.body,v.kind as CustomerWorkUserKind)||v.body.scope_key!==v.scope_key||v.method!=='POST'||!customerWorkInteger(v.created_at))return false;return v.endpoint===customerWorkUserEndpoint(v.kind as CustomerWorkUserKind,v.body.targets.map(row=>row.uid))&&v.request_hash===customerWorkUserIntentHash(v.actor_uid,v.kind as string,v.body);}
export function parseCustomerWorkUserReceipt(v:unknown,intent:CustomerWorkUserIntent):CustomerWorkUserReceipt{
 assert(isCustomerWorkUserIntent(intent)&&customerWorkRecord(v)&&keys(v,['version','actor_uid','service_id','request_key','request_hash','kind','user_ids','outcome','evidence'])&&v.version===CUSTOMER_WORK_USER_VERSION&&v.actor_uid===intent.actor_uid&&v.request_key===intent.request_key&&v.request_hash===intent.request_hash&&v.kind===intent.kind&&sorted(v.user_ids,100,1)&&customerWorkCanonicalJson(v.user_ids)===customerWorkCanonicalJson(intent.body.targets.map(row=>row.uid))&&customerWorkInteger(v.service_id)&&customerWorkRecord(v.evidence),'原用户回执与不可变意图不匹配');
 const e=v.evidence;if(v.outcome==='rollback-rejected'){assert(v.service_id===0&&keys(e,['code'])&&text(e.code)&&!!e.code,'拒绝回执格式无效');return v as unknown as CustomerWorkUserReceipt;}if(v.outcome==='abandoned'){assert(v.service_id===0&&keys(e,[]),'放弃回执格式无效');return v as unknown as CustomerWorkUserReceipt;}assert(v.service_id===intent.service_id&&v.service_id>0&&e.verified===true,'用户回执身份无效');
 if(intent.kind.startsWith('replace_'))assert(v.outcome==='users-updated'&&keys(e,['changed','verified'])&&customerWorkInteger(e.changed)&&e.changed<=intent.body.targets.length,'用户修改回执无效');
 else if(intent.kind==='grant_coupons')assert(v.outcome==='coupons-granted'&&keys(e,['changed','issued_count','issue_id','verified'])&&e.changed===intent.body.targets.length&&e.issued_count===intent.body.targets.length&&e.issue_id===(intent.body.payload as {issue_id:number}).issue_id,'赠券回执未核实全部目标');
 else if(intent.kind==='adjust_membership')assert(v.outcome==='membership-adjusted'&&keys(e,['changed','other_order_id','verified'])&&flag(e.changed)&&id(e.other_order_id),'会员时长回执缺少真实调整记录');
 else{const field=intent.kind==='adjust_money'?'money_ledger_id':'integral_ledger_id';assert(v.outcome==='finance-adjusted'&&keys(e,['changed',field,'verified'])&&flag(e.changed)&&(e.changed===0?e[field]===0:id(e[field])),'资产回执缺少真实账目或无变化依据');}
 return v as unknown as CustomerWorkUserReceipt;
}
