import { parseCustomerWorkQuery,resolveCustomerWorkPageRoute } from '../../../common/customerWorkRoute';
import { customerWorkIntentHash } from '../../../common/customerWorkIntent';
import { CUSTOMER_WORK_USER_KINDS,customerWorkUserIntentHash,customerWorkUserEndpoint,customerWorkUserAmount,customerWorkUserPositive,isCustomerWorkUser,isCustomerWorkUserDetailData,isCustomerWorkUserList,isCustomerWorkUserGroups,isCustomerWorkUserLevels,isCustomerWorkUserLabels,isCustomerWorkUserCouponCandidates,isCustomerWorkUserCoupons,isCustomerWorkUserBody,isCustomerWorkUserIntent,parseCustomerWorkUserEnvelope,parseCustomerWorkUserReceipt } from './customerWorkUsersContract';
import type { CustomerWorkUser,CustomerWorkUserDetail,CustomerWorkUserMeta,CustomerWorkUserKind,CustomerWorkUserIntent,CustomerWorkUserPayload } from '../types/customerWorkUsers';
export const userMeta=():CustomerWorkUserMeta=>({scopes:{users:'global',groups:'global',levels:'global',labels:'platform',coupon_issues:'global_send',wallet:'exact_target_user',paid_order_count:'original_roots',paid_order_value:'physical_fulfillments'},catalog_revision:'c'.repeat(64),readiness:{writes:true,reason:''},at_time:1791075600});
export function userFixture(uid=1):CustomerWorkUser{return{uid,nickname:'实际用户'+uid,avatar:'',phone:'13800000000',status:1,deleted:false,group_id:1,group_name:'真实分组',level:1,level_name:'真实等级',level_status:1,level_grade:1,labels:[{id:1,label_name:'平台标签',color:''}],now_money:'10.00',integral:20,financial_diagnostics:[],isMember:1,is_money_level:1,is_ever_level:0,overdue_time:1791248400,membership_active:true,svip_over_day:2,svip_overdue_time:'2026-10-06',user_revision:'d'.repeat(64),actions:Object.fromEntries(CUSTOMER_WORK_USER_KINDS.map(kind=>[kind,{available:true,reason:''}])) as CustomerWorkUser['actions']};}
export function userDetail(uid=1):CustomerWorkUserDetail{return{...userFixture(uid),real_name:'真实姓名',birthday:'2000-01-01',birthday_epoch:946684800,card_id:'',addres:'实际地址',add_time:1791075600,_add_time:'2026-10-04',order_total_count:3,order_total_price:'23.00',coupon_num:1};}
export function userIntent(kind:CustomerWorkUserKind='replace_group',payload:CustomerWorkUserPayload={group_id:1},uids=[1]):CustomerWorkUserIntent{const body={version:'customer-work-user-operation-v1' as const,scope_key:'a'.repeat(64),targets:uids.map(uid=>({uid,expected_user_revision:'d'.repeat(64)})),expected_catalog_revision:'c'.repeat(64),payload};return{version:'customer-work-user-pending-v1',actor_uid:11,service_id:1,scope_key:body.scope_key,kind,request_key:'12345678-1234-4123-8123-123456789abc',request_hash:customerWorkUserIntentHash(11,kind,body),body,endpoint:customerWorkUserEndpoint(kind,uids),method:'POST',created_at:1791075600};}
export const userPayloads:Record<CustomerWorkUserKind,CustomerWorkUserPayload>={replace_level:{level_id:1},replace_group:{group_id:1},replace_labels:{label_ids:[]},grant_coupons:{issue_id:1,expected_issue_revision:'f'.repeat(64)},adjust_membership:{direction:'subtract',days:2},adjust_money:{direction:'subtract',amount:'20.00'},adjust_integral:{direction:'subtract',amount:30}};
export function userReceipt(intent:CustomerWorkUserIntent,changed=1){const kind=intent.kind,evidence=kind==='grant_coupons'?{changed:intent.body.targets.length,issued_count:intent.body.targets.length,issue_id:(intent.body.payload as {issue_id:number}).issue_id,verified:true}:kind==='adjust_membership'?{changed,other_order_id:2,verified:true}:kind==='adjust_money'?{changed,money_ledger_id:changed?2:0,verified:true}:kind==='adjust_integral'?{changed,integral_ledger_id:changed?2:0,verified:true}:{changed,verified:true};return{version:intent.body.version,actor_uid:intent.actor_uid,service_id:intent.service_id,request_key:intent.request_key,request_hash:intent.request_hash,kind,user_ids:intent.body.targets.map(row=>row.uid),outcome:kind==='grant_coupons'?'coupons-granted':kind==='adjust_membership'?'membership-adjusted':kind==='adjust_money'||kind==='adjust_integral'?'finance-adjusted':'users-updated',evidence};}
export function runCustomerWorkUserPureTests(assert:{equal:(a:unknown,b:unknown)=>void;deepEqual:(a:unknown,b:unknown)=>void;throws:(fn:()=>unknown,pattern?:RegExp)=>void}){
 assert.deepEqual(parseCustomerWorkQuery('users','keyword=138&group_id=0&level=0&label_id=0&isMember=0'),{nickname:'138',group_id:'0',level:'0',label_ids:'',isMember:'0'});assert.equal(resolveCustomerWorkPageRoute('/pages/admin/user/index','uid=1'),'/pages/customer-work/userDetail?uid=1');
 for(const query of ['uid=01','uid=1&uid=1','id=1','uid=1&order_id=1'])assert.throws(()=>parseCustomerWorkQuery('userDetail',query));for(const query of ['nickname=x&keyword=x','label_ids=1&label_id=1','label_ids=1,1','isMember=2','page=1','nickname=%00'])assert.throws(()=>parseCustomerWorkQuery('users',query));
 assert.equal(parseCustomerWorkQuery('users','label_ids=2,1').label_ids,'1,2');
 const labels=Array.from({length:100},(_,i)=>2147483548+i).join(',');assert.equal(parseCustomerWorkQuery('users',{label_ids:labels}).label_ids,labels);assert.throws(()=>parseCustomerWorkQuery('users',{label_ids:Array.from({length:101},(_,i)=>i+1).join(',')}));
 assert.equal(customerWorkUserAmount('000.1'),'0.10');assert.equal(customerWorkUserAmount('1'),'1.00');for(const value of ['0','-1','1e2','1.001','Infinity','10000000000',''])assert.throws(()=>customerWorkUserAmount(value));for(const value of ['0','01','-1','1.5','2147483648',''])assert.throws(()=>customerWorkUserPositive(value));assert.throws(()=>customerWorkUserPositive('1000000',999999));
 const meta=userMeta(),user=userFixture(),wire={version:'customer-work-user-read-v1',actor_uid:11,principal:{kind:'customer-order-manager',service_id:1,scope:'global'},scope_key:'a'.repeat(64),consistency_key:'e'.repeat(64),data:{...meta,user:userDetail()}};assert.equal(isCustomerWorkUserDetailData(wire.data),true);assert.equal(isCustomerWorkUserDetailData({...wire.data,user:{...userDetail(),order_total_price:'10000000000.00'}}),true);assert.equal(parseCustomerWorkUserEnvelope(wire,11,isCustomerWorkUserDetailData).data.user.uid,1);
 for(const changed of [{actor_uid:12},{version:'customer-work-read-v1'},{principal:{...wire.principal,kind:'manager'}},{scope_key:'x'}])assert.throws(()=>parseCustomerWorkUserEnvelope({...wire,...changed},11,isCustomerWorkUserDetailData));assert.throws(()=>parseCustomerWorkUserEnvelope(wire,11,isCustomerWorkUserDetailData,{scope_key:'a'.repeat(64),principal:{service_id:2}}));assert.throws(()=>parseCustomerWorkUserEnvelope(wire,11,isCustomerWorkUserDetailData,undefined,'b'.repeat(64)));
 assert.equal(isCustomerWorkUser({...user,status:0}),true);const disabled=Object.fromEntries(CUSTOMER_WORK_USER_KINDS.map(kind=>[kind,{available:false,reason:'readonly'}]));assert.equal(isCustomerWorkUser({...user,deleted:true,actions:disabled}),true);assert.equal(isCustomerWorkUser({...user,deleted:true}),false);assert.equal(isCustomerWorkUser({...user,is_ever_level:1,svip_over_day:null,actions:disabled}),true);assert.equal(isCustomerWorkUser({...user,is_ever_level:1}),false);assert.equal(isCustomerWorkUser({...user,now_money:null,integral:null,financial_diagnostics:['历史资产记录异常'],actions:disabled}),true);assert.equal(isCustomerWorkUser({...user,now_money:null}),false);assert.equal(isCustomerWorkUser({...user,isMember:0}),false);
 assert.equal(isCustomerWorkUserList({...meta,list:[user,user],count:2,page:1,limit:20,has_more:false}),false);assert.equal(isCustomerWorkUserDetailData({...meta,user:{...userDetail(),birthday:'2026-02-30'}}),false);assert.equal(isCustomerWorkUserDetailData({...meta,user:{...userDetail(),pwd:'private'}}),false);
 const groupList=Array.from({length:1001},(_,i)=>({id:i+1,group_name:'分组'+i}));assert.equal(isCustomerWorkUserGroups({...meta,list:groupList,count:1001}),true);assert.equal(isCustomerWorkUserGroups({...meta,list:[groupList[0],groupList[0]],count:2}),false);assert.equal(isCustomerWorkUserLevels({...meta,list:[{id:1,name:'😀'.repeat(255),grade:0,image:'',icon:''}],count:1}),true);
 const catalog={...meta,uid:0,list:[{id:1,name:'😀'.repeat(255),sort:0,label:Array.from({length:1001},(_,i)=>({id:i+1,label_name:'😀'.repeat(255),color:'',label_cate:1,selected:false}))}],count:1};assert.equal(isCustomerWorkUserLabels(catalog),true);assert.equal(isCustomerWorkUser({...user,labels:catalog.list[0]!.label.map(({id,label_name,color})=>({id,label_name,color}))}),true);assert.equal(isCustomerWorkUserLabels({...catalog,list:[{...catalog.list[0]!,label:[{...catalog.list[0]!.label[0]!,label_cate:2}]}]}),false);
 for(const kind of CUSTOMER_WORK_USER_KINDS){const intent=userIntent(kind,userPayloads[kind]);assert.equal(isCustomerWorkUserIntent(intent),true);assert.equal(intent.request_hash===customerWorkIntentHash(11,kind,intent.body as unknown as Record<string,unknown>),false);assert.equal(isCustomerWorkUserBody({...intent.body,admin_id:1},kind),false);assert.equal(isCustomerWorkUserIntent({...intent,token:'private'}),false);const receipt=userReceipt(intent);assert.deepEqual(parseCustomerWorkUserReceipt(receipt,intent),receipt);for(const changed of [{actor_uid:12},{service_id:0},{user_ids:[2]},{request_hash:'a'.repeat(64)},{evidence:{...receipt.evidence,now_money:'private'}}])assert.throws(()=>parseCustomerWorkUserReceipt({...receipt,...changed},intent));if(kind!=='grant_coupons')assert.equal(parseCustomerWorkUserReceipt(userReceipt(intent,0),intent).outcome,receipt.outcome);assert.equal(parseCustomerWorkUserReceipt({...receipt,service_id:0,outcome:'rollback-rejected',evidence:{code:'410000'}},intent).service_id,0);assert.equal(parseCustomerWorkUserReceipt({...receipt,service_id:0,outcome:'abandoned',evidence:{}},intent).outcome,'abandoned');}
 const batch=userIntent('replace_group',{group_id:1},Array.from({length:100},(_,i)=>i+1));assert.equal(isCustomerWorkUserBody(batch.body,batch.kind),true);assert.equal(isCustomerWorkUserBody({...batch.body,targets:[...batch.body.targets,{uid:101,expected_user_revision:'d'.repeat(64)}]},batch.kind),false);assert.equal(isCustomerWorkUserBody({...batch.body,targets:[batch.body.targets[1],batch.body.targets[0]]},batch.kind),false);assert.equal(isCustomerWorkUserBody({...batch.body,targets:batch.body.targets.slice(0,2)},'replace_level'),false);
 for(const ids of [[1,1],[2,1],Array.from({length:101},(_,i)=>i+1)])assert.equal(isCustomerWorkUserBody({...userIntent('replace_labels',{label_ids:[]}).body,payload:{label_ids:ids}},'replace_labels'),false);assert.equal(isCustomerWorkUserBody(userIntent('replace_labels',{label_ids:[]}).body,'replace_labels'),true);
 for(const kind of ['adjust_money','adjust_integral'] as const){const intent=userIntent(kind,userPayloads[kind]),receipt=userReceipt(intent,0),field=kind==='adjust_money'?'money_ledger_id':'integral_ledger_id';assert.throws(()=>parseCustomerWorkUserReceipt({...receipt,evidence:{changed:0,[field]:1,verified:true}},intent));assert.throws(()=>parseCustomerWorkUserReceipt({...receipt,evidence:{changed:1,[field]:0,verified:true}},intent));}const member=userIntent('adjust_membership',userPayloads.adjust_membership);assert.throws(()=>parseCustomerWorkUserReceipt({...userReceipt(member),evidence:{changed:0,other_order_id:0,verified:true}},member));
 const candidate={id:1,cid:2,coupon_title:'😀'.repeat(64),type:1,coupon_type:0,coupon_price:'1.00',use_min_price:'0.00',total_count:10,remain_count:10,is_permanent:0,receive_limit:1,receive_type:3,day:2,start_time:null,end_time:null,use_start_time:null,use_end_time:null,coupon_time:'有效2天',issue_revision:'f'.repeat(64),action:{available:true,reason:''}},page={...meta,count:1,page:1,limit:20,has_more:false};assert.equal(isCustomerWorkUserCouponCandidates({...page,list:[candidate]}),true);assert.equal(isCustomerWorkUserCouponCandidates({...page,list:[{...candidate,coupon_price:'-1.00',action:{available:false,reason:'invalid'}}]}),true);assert.equal(isCustomerWorkUserCouponCandidates({...page,list:[{...candidate,coupon_price:'-1.00'}]}),false);assert.equal(isCustomerWorkUserCouponCandidates({...page,list:[{...candidate,type:3}]}),false);
 const wallet={id:1,uid:1,issue_coupon_id:1,template_id:2,coupon_title:'😀'.repeat(64),coupon_price:'1.00',use_min_price:'0.00',status:0,is_fail:0,type:1,coupon_type:0,receive_source:'send',receive_time:1791075600,start_time:null,end_time:null,use_time:null,availability:'available',availability_message:''};assert.equal(isCustomerWorkUserCoupons({...page,uid:1,list:[wallet]}),true);assert.equal(isCustomerWorkUserCoupons({...page,uid:2,list:[wallet]}),false);assert.equal(isCustomerWorkUserCoupons({...page,uid:1,list:[{...wallet,coupon_price:'-1.00',availability:'invalid'}]}),true);assert.equal(isCustomerWorkUserCoupons({...page,uid:1,list:[{...wallet,coupon_price:'-1.00'}]}),false);
}
