import {customerWorkRequestKey} from './customerWorkFulfillment';
import {customerWorkCanonicalJson,isCustomerWorkWriteoffIntent,writeoffUuid,writeoffText,customerWriteoffTerminal,type CustomerWorkWriteoffIntent,type CustomerWorkWriteoffResult} from '../../../common/customerWorkWriteoff';
export * from '../../../common/customerWorkWriteoff';
export {customerWorkRequestKey};
export const CUSTOMER_WRITEOFF_STORAGE='customer_work_writeoff_pending_v1';
function assert(v:unknown,message:string):asserts v{if(!v)throw Error(message);}
export function customerWriteoffPending():CustomerWorkWriteoffIntent[]{const v=uni.getStorageSync(CUSTOMER_WRITEOFF_STORAGE);if(v===undefined||v===null||v==='')return[];assert(Array.isArray(v)&&v.length<=100&&v.every(isCustomerWorkWriteoffIntent)&&new Set(v.map(r=>r.request_key)).size===v.length,'原核销记录损坏，请保留本机记录核对');return JSON.parse(customerWorkCanonicalJson(v));}
export function retainCustomerWriteoffIntent(intent:CustomerWorkWriteoffIntent){assert(isCustomerWorkWriteoffIntent(intent),'原核销意图无效，尚未提交');const prior=customerWriteoffPending(),known=prior.find(r=>r.request_key===intent.request_key);if(known){assert(customerWorkCanonicalJson(known)===customerWorkCanonicalJson(intent),'同一核销编号不能替换内容');return;}assert(prior.length<100,'待核对核销记录过多，请先查询原结果');const next=JSON.parse(customerWorkCanonicalJson([...prior,intent]));uni.setStorageSync(CUSTOMER_WRITEOFF_STORAGE,next);assert(customerWorkCanonicalJson(customerWriteoffPending())===customerWorkCanonicalJson(next),'原核销意图保存未确认，尚未提交');}
export function releaseCustomerWriteoffIntent(key:string){assert(writeoffUuid(key),'原核销编号无效');const next=customerWriteoffPending().filter(r=>r.request_key!==key);uni.setStorageSync(CUSTOMER_WRITEOFF_STORAGE,next);assert(customerWorkCanonicalJson(customerWriteoffPending())===customerWorkCanonicalJson(next),'关闭原核销记录失败，请继续核对');}
export function customerWriteoffNotice(code:string):string{if(!code)return'';const messages:Record<string,string>={customer_writeoff_not_ready:'核销依据暂不可用，请重新读取。',customer_writeoff_operation_not_ready:'核销台账暂不可用，请核对后再处理。',writeoff_namespace_ambiguous:'核销码与会员条码存在歧义，请明确选择命名空间后重新查询。',writeoff_origin_unproven:'当前收银订单来源无法证明，请核对真实创建与付款记录。',writeoff_sale_price_unproven:'原成交价无法核验，请人工核对后再处理。'};if(Object.hasOwn(messages,code))return messages[code]!;if(writeoffText(code,500)&&/[\u3400-\u9fff]/u.test(code))return code;return'当前无法核销，请重新读取订单、实际次数和原操作结果。';}
export function customerWriteoffResultMessage(result:CustomerWorkWriteoffResult|null):string{if(!result?.receipt)return'原核销结果尚未确认，请继续查询原编号。';if(result.receipt.outcome==='abandoned')return'尚未执行的原核销意图已放弃。';if(result.receipt.outcome==='rollback-rejected')return'原核销未执行，请重新核对当前订单与资格。';if(!customerWriteoffTerminal(result))return'原核销业务证据尚未确认，请保留原编号继续查询。';return result.execution?.order_completed?'全部剩余次数已核验核销，订单已完成。':'本次分次核销已核验完成，请重新读取剩余次数和新核销码。';}
export function customerWriteoffTime(seconds:number):string{if(seconds===0)return'无边界';return new Date(seconds*1000).toLocaleString('zh-CN',{hour12:false});}
