import { isDeliveryWorkbenchEnvelope } from '../../../common/deliveryWorkbench';
import { isUserCenterPublicImage } from '../../../common/userCenterDesign';
import { merchantCanonicalJson,merchantSha256 } from '@/utils/merchantIntentHash';
import { isMerchantCart,merchantMoney } from '@/utils/merchantOrders';
import type {DeliveryWorkbenchEnvelope,DeliveryWorkbenchContext,DeliveryContextSelection,DeliveryWorkbenchStatistics,DeliveryDailyRow,DeliveryPaged,DeliveryOrderItem,DeliveryOrderDetail,DeliveryOrdersPage,DeliveryPendingIntent,DeliveryOperationInput,DeliveryOperationReceipt,DeliveryWriteoffCart,DeliveryWriteoffPreview,DeliveryWriteoffPreviews,DeliveryWriteoffRecord} from '@/types/deliveryWorkbench';

export const deliveryRecord=(value:unknown):value is Record<string,unknown>=>!!value&&typeof value==='object'&&!Array.isArray(value);
export const deliveryInt=(value:unknown,min=0):value is number=>typeof value==='number'&&Number.isSafeInteger(value)&&value>=min&&value<=2147483647;
export const deliveryText=(value:unknown,max=1024):value is string=>typeof value==='string'&&value.length<=max&&!/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/u.test(value);
export const deliveryHash=(value:unknown):value is string=>typeof value==='string'&&/^[a-f0-9]{64}$/u.test(value);
export const deliveryUUID=(value:unknown):value is string=>typeof value==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/u.test(value);
const image=(value:unknown)=>value===''||isUserCenterPublicImage(value);
function assert(value:unknown,message='配送数据格式无效，请重新读取'):asserts value{if(!value)throw Error(message);}
export function isDeliverySelection(value:unknown):value is DeliveryContextSelection{return deliveryRecord(value)&&(value.kind==='platform'||value.kind==='store')&&deliveryInt(value.delivery_id,1)&&deliveryInt(value.store_id)&&(value.kind==='platform'?value.store_id===0:value.store_id>0);}
export function deliverySameScope(a:DeliveryContextSelection|null|undefined,b:DeliveryContextSelection|null|undefined){return a===null&&b===null||!!a&&!!b&&a.kind===b.kind&&a.store_id===b.store_id&&a.delivery_id===b.delivery_id;}
export function deliverySelectionQuery(scope:DeliveryContextSelection){return {scope_kind:scope.kind,delivery_id:scope.delivery_id,store_id:scope.store_id};}
export function parseDeliveryEnvelope<T>(value:unknown,actor:number,guard:(value:unknown)=>value is T,scope?:DeliveryContextSelection|null,scopeKey?:string):DeliveryWorkbenchEnvelope<T>{assert(isDeliveryWorkbenchEnvelope(value)&&value.actor_uid===actor&&(scope===undefined||deliverySameScope(value.scope,scope))&&(!scopeKey||value.scope_key===scopeKey),'配送身份或账号信息已变化，请重新读取');assert(guard(value.data));return value as DeliveryWorkbenchEnvelope<T>;}
export function isDeliveryContext(value:unknown):value is DeliveryWorkbenchContext{
  if(!deliveryRecord(value)||!Array.isArray(value.contexts)||value.contexts.length>100||!Array.isArray(value.conflicts)||value.conflicts.length>100||!(value.selected===null||isDeliverySelection(value.selected)))return false;
  const contexts=value.contexts;return contexts.every(row=>isDeliverySelection(row)&&deliveryRecord(row)&&['name','nickname','phone'].every(k=>deliveryText(row[k],200))&&image(row.avatar))&&new Set(contexts.map(row=>`${row.kind}:${row.store_id}:${row.delivery_id}`)).size===contexts.length&&value.conflicts.every(row=>deliveryRecord(row)&&(row.kind==='platform'||row.kind==='store')&&deliveryInt(row.store_id)&&(row.kind==='platform'?row.store_id===0:row.store_id>0)&&Array.isArray(row.delivery_ids)&&row.delivery_ids.length>1&&row.delivery_ids.every(id=>deliveryInt(id,1)))&&(value.selected===null||contexts.some(row=>deliverySameScope(row,value.selected as DeliveryContextSelection)));
}
export function isDeliveryStatistics(value:unknown):value is DeliveryWorkbenchStatistics{return deliveryRecord(value)&&deliveryInt(value.unsend)&&deliveryInt(value.send)&&merchantMoney(value.send_price);}
export function isDeliveryPaged<T>(guard:(value:unknown)=>value is T){return (value:unknown):value is DeliveryPaged<T>=>deliveryRecord(value)&&Array.isArray(value.list)&&value.list.length<=100&&value.list.every(guard)&&deliveryInt(value.count)&&deliveryInt(value.page,1)&&deliveryInt(value.limit,1)&&value.limit<=100&&typeof value.has_more==='boolean';}
const coord=(value:unknown,max:number)=>value===null||typeof value==='number'&&Number.isFinite(value)&&Math.abs(value)<=max;
export function isDeliveryOrder(value:unknown):value is DeliveryOrderItem{
  if(!deliveryRecord(value)||!deliveryInt(value.id,1)||!deliveryInt(value.pid,-1)||!deliveryHash(value.revision)||!['store_id','supplier_id','delivery_uid','total_num','pay_integral','paid','status','refund_status','shipping_type','product_type','add_time','pay_time'].every(k=>deliveryInt(value[k]))||!['order_id','real_name','nickname','user_phone','user_address','delivery_type','delivery_name','delivery_id','mark'].every(k=>deliveryText(value[k]))||!['total_price','total_postage','pay_price','promotions_price','first_order_price'].every(k=>merchantMoney(value[k]))||!Array.isArray(value.cartInfo)||value.cartInfo.length>1000||!value.cartInfo.every(isMerchantCart)||!deliveryRecord(value._status)||!deliveryInt(value._status._type,-10)||!['_title','_msg','_class','_payType','_deliveryType'].every(k=>deliveryText((value._status as Record<string,unknown>)[k]))||!deliveryRecord(value.actions)||!deliveryRecord(value.actions.writeoff)||typeof value.actions.writeoff.available!=='boolean'||!deliveryText(value.actions.writeoff.reason,500))return false;
  return value.store===null||deliveryRecord(value.store)&&deliveryInt(value.store.id,1)&&['name','phone','address','detailed_address'].every(k=>deliveryText((value.store as Record<string,unknown>)[k]))&&coord(value.store.latitude,90)&&coord(value.store.longitude,180);
}
export function isDeliveryDetail(value:unknown):value is DeliveryOrderDetail{return isDeliveryOrder(value)&&deliveryRecord(value)&&['pay_type','_pay_time','_add_time','verify_code'].every(k=>deliveryText(value[k]))&&['pay_postage','coupon_price','deduction_price','vip_true_price'].every(k=>merchantMoney(value[k]))&&deliveryInt(value.give_integral)&&Array.isArray(value.give_coupon)&&value.give_coupon.every(row=>deliveryRecord(row)&&deliveryInt(row.id)&&deliveryText(row.coupon_title,500))&&Array.isArray(value.promotions_detail)&&value.promotions_detail.every(row=>deliveryRecord(row)&&deliveryInt(row.promotions_id)&&deliveryInt(row.product_id)&&merchantMoney(row.promotions_price)&&deliveryText(row.title,500))&&(value.custom_form===null||Array.isArray(value.custom_form)||deliveryRecord(value.custom_form))&&coord(value.latitude,90)&&coord(value.longitude,180)&&(value.verify_code===''||/^\d{12}$/u.test(String(value.verify_code)));}
export function isDeliveryOrders(value:unknown):value is DeliveryOrdersPage{return isDeliveryPaged(isDeliveryOrder)(value)&&deliveryRecord(value)&&deliveryInt(value.unsend)&&deliveryInt(value.send)&&new Set(value.list.map(row=>row.id)).size===value.list.length;}
export function isDeliveryDaily(value:unknown):value is DeliveryPaged<DeliveryDailyRow>{return isDeliveryPaged((row:unknown):row is DeliveryDailyRow=>deliveryRecord(row)&&/^\d{4}-\d{2}-\d{2}$/u.test(String(row.date))&&row.time===row.date&&merchantMoney(row.price)&&deliveryInt(row.count))(value);}
export function isDeliverySnapshot(value:unknown):value is DeliveryWriteoffCart['cart_info']{if(!deliveryRecord(value)||!deliveryRecord(value.productInfo))return false;const p=value.productInfo,a=p.attrInfo;return deliveryInt(p.id)&&deliveryText(p.store_name,500)&&image(p.image)&&deliveryRecord(a)&&deliveryText(a.suk,500)&&image(a.image)&&merchantMoney(a.price);}
export function isDeliveryWriteoffCart(value:unknown):value is DeliveryWriteoffCart{return deliveryRecord(value)&&deliveryInt(value.id,1)&&deliveryText(value.cart_id,128)&&['cart_num','product_id','product_type','is_gift','write_times','write_surplus_times','write_start','write_end'].every(k=>deliveryInt(value[k]))&&Number(value.write_surplus_times)<=Number(value.write_times)&&isDeliverySnapshot(value.cart_info);}
export function isDeliveryPreview(value:unknown):value is DeliveryWriteoffPreview{return deliveryRecord(value)&&deliveryInt(value.id,1)&&deliveryText(value.order_id,128)&&deliveryInt(value.store_id)&&deliveryHash(value.revision)&&typeof value.verify_code==='string'&&/^\d{12}$/u.test(value.verify_code)&&['status','total_num','product_type','writeoff_count'].every(k=>deliveryInt(value[k]))&&Array.isArray(value.cart_info)&&value.cart_info.length<=1000&&value.cart_info.every(isDeliveryWriteoffCart)&&new Set(value.cart_info.map(cart=>cart.id)).size===value.cart_info.length&&deliveryRecord(value.actions)&&deliveryRecord(value.actions.writeoff)&&typeof value.actions.writeoff.available==='boolean'&&deliveryText(value.actions.writeoff.reason,500);}
export function isDeliveryPreviews(value:unknown):value is DeliveryWriteoffPreviews{return deliveryRecord(value)&&['order-code','member-barcode','order-id'].includes(String(value.lookup_kind))&&Array.isArray(value.list)&&value.list.length<=100&&value.list.every(isDeliveryPreview)&&new Set(value.list.map(row=>row.id)).size===value.list.length;}
export function isDeliveryWriteoffRecord(value:unknown):value is DeliveryWriteoffRecord{return deliveryRecord(value)&&deliveryInt(value.id,1)&&deliveryInt(value.order_cart_id,1)&&deliveryInt(value.writeoff_num,1)&&merchantMoney(value.writeoff_price)&&deliveryInt(value.add_time)&&deliveryText(value.time,50)&&isDeliverySnapshot(value.cart_info)&&deliveryRecord(value.operator)&&['delivery','staff','admin','kefu','unknown'].includes(String(value.operator.kind))&&(value.operator.delivery_id===null||deliveryInt(value.operator.delivery_id,1))&&(value.operator.kind==='delivery'||value.operator.delivery_id===null);}
export const isDeliveryRecords=isDeliveryPaged(isDeliveryWriteoffRecord);
export function deliveryCode(value:unknown):value is string{return typeof value==='string'&&value.length>=1&&value.length<=32&&value===value.trim()&&!/[\u0000-\u0020\u007f\\]/u.test(value);}
export function deliveryCartReason(cart:DeliveryWriteoffCart,now=Math.floor(Date.now()/1000)){if(!cart.write_surplus_times)return '该商品已全部送达';if(cart.write_start&&now<cart.write_start)return '尚未到可核销时间';if(cart.write_end&&now>cart.write_end)return '已超过可核销时间';return '';}
export function deliveryDiagnostic(issues:string[]){return [...new Set(issues.map(issue=>issue.includes('coordinate')||issue.includes('location')?'部分地址缺少有效坐标，请使用电话联系':issue.includes('conflict')?'配送身份存在重复，请联系管理员核对':issue.includes('media')||issue.includes('image')?'部分商品图片暂不可用':'部分配送内容暂不可用，请重新读取或联系管理员'))].join('；');}
export function deliveryDate(epoch:number){return epoch?new Date(epoch*1000).toLocaleString():'';}
export function isDeliveryInput(value:unknown):value is DeliveryOperationInput{
  if(!deliveryRecord(value)||Object.keys(value).sort().join(',')!=='delivery_id,expected_order_revision,order_id,payload,scope_key,scope_kind,store_id,version'||value.version!=='delivery-writeoff-operation-v1'||!isDeliverySelection({kind:value.scope_kind,store_id:value.store_id,delivery_id:value.delivery_id})||!deliveryInt(value.order_id,1)||!deliveryHash(value.scope_key)||!deliveryHash(value.expected_order_revision)||!deliveryRecord(value.payload)||Object.keys(value.payload).sort().join(',')!=='code,items'||typeof value.payload.code!=='string'||!/^\d{12}$/u.test(value.payload.code)||!Array.isArray(value.payload.items)||!value.payload.items.length||value.payload.items.length>1000)return false;
  const ids=new Set<number>();return value.payload.items.every(item=>{if(!deliveryRecord(item)||Object.keys(item).sort().join(',')!=='order_cart_id,quantity'||!deliveryInt(item.order_cart_id,1)||!deliveryInt(item.quantity,1)||ids.has(item.order_cart_id))return false;ids.add(item.order_cart_id);return true;});
}
/** Canonical hashing preserves the complete immutable wire input. */
export function deliveryIntentHash(actor:number,input:DeliveryOperationInput){return merchantSha256(merchantCanonicalJson({version:'delivery-writeoff-operation-v1',actor_uid:actor,kind:'delivery_writeoff',input}));}
const storageKey='delivery_pending_intents_v1';
export function deliveryPendingIntents():DeliveryPendingIntent[]{const value=uni.getStorageSync(storageKey);if(value===undefined||value===null||value==='')return [];assert(Array.isArray(value)&&value.length<=100,'原配送操作记录无法读取，请勿重复提交');assert(value.every(row=>deliveryRecord(row)&&deliveryUUID(row.request_key)&&deliveryHash(row.request_hash)&&deliveryInt(row.actor_uid,1)&&deliveryInt(row.created_at)&&isDeliveryInput(row.body)&&JSON.stringify(row.body).length<=100000),'原配送操作记录损坏，请保留记录并联系管理员');return value as DeliveryPendingIntent[];}
export function retainDeliveryIntent(intent:DeliveryPendingIntent){const saved=deliveryPendingIntents().filter(row=>row.request_key!==intent.request_key);assert(saved.length<100,'待确认配送操作过多，请先核对原结果');const next=JSON.parse(merchantCanonicalJson([...saved,intent]));uni.setStorageSync(storageKey,next);assert(merchantCanonicalJson(uni.getStorageSync(storageKey))===merchantCanonicalJson(next),'无法保存原配送操作，尚未提交');}
export function releaseDeliveryIntent(key:string){uni.setStorageSync(storageKey,deliveryPendingIntents().filter(row=>row.request_key!==key));}
export function parseDeliveryReceipt(value:unknown,intent:DeliveryPendingIntent):DeliveryOperationReceipt|null{assert(deliveryRecord(value),'配送凭据响应无效，原操作仍待核对');if(value.receipt===null)return null;const row=value.receipt;assert(deliveryRecord(row)&&row.version==='delivery-writeoff-operation-v1'&&row.request_key===intent.request_key&&row.request_hash===intent.request_hash&&row.actor_uid===intent.actor_uid&&row.scope_kind===intent.body.scope_kind&&(row.delivery_id===intent.body.delivery_id||['abandoned','rollback-rejected'].includes(String(row.outcome))&&row.delivery_id===0)&&row.store_id===intent.body.store_id&&row.order_id===intent.body.order_id&&['partial-delivered','delivered','abandoned','rollback-rejected'].includes(String(row.outcome))&&deliveryRecord(row.evidence),'配送凭据与原操作不匹配，不能重新提交');return row as unknown as DeliveryOperationReceipt;}
