import { isMerchantEnvelope } from '../../../common/merchantManagement';
import { isUserCenterPublicImage } from '../../../common/userCenterDesign';
import type { MerchantManagementEnvelope,MerchantManagementContext,MerchantOrderActions,MerchantOrderCart,MerchantOrderListItem,MerchantOrderDetail,MerchantOrderStatistics,MerchantOrderPeriod,MerchantOrderChartPoint,MerchantOrderDailyRow,MerchantPaged,MerchantDeliveryDefaults,MerchantDeliveryAgent,MerchantCarrier,MerchantDeliveryGain,MerchantExpressResult,MerchantTrackingPackage,MerchantPendingIntent } from '@/types/merchantOrders';

const record=(value:unknown):value is Record<string,unknown>=>!!value&&typeof value==='object'&&!Array.isArray(value);
const int=(value:unknown,min=0)=>typeof value==='number'&&Number.isSafeInteger(value)&&value>=min&&value<=2147483647;
const text=(value:unknown,max=1024)=>typeof value==='string'&&value.length<=max&&!/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/u.test(value);
export const merchantMoney=(value:unknown):value is string=>typeof value==='string'&&/^\d{1,12}(?:\.\d{1,2})?$/u.test(value);
export const merchantOrderId=(value:unknown):value is string=>typeof value==='string'&&/^[A-Za-z0-9_-]{1,128}$/u.test(value);
const hash=(value:unknown)=>typeof value==='string'&&/^[a-f0-9]{64}$/u.test(value);
const image=(value:unknown)=>value===''||isUserCenterPublicImage(value);
const keys=['remark','change_price','confirm_offline','manual_delivery','split_delivery','electronic_waybill','refund_create','refund_decide','tracking','writeoff'] as const;
function assert(value:unknown,message='商家数据格式无效，请重新读取'):asserts value{if(!value)throw Error(message);}
function strings(row:Record<string,unknown>,fields:readonly string[],max=1024){return fields.every(key=>text(row[key],max));}
function integers(row:Record<string,unknown>,fields:readonly string[]){return fields.every(key=>int(row[key]));}
function monies(row:Record<string,unknown>,fields:readonly string[]){return fields.every(key=>merchantMoney(row[key]));}
export function parseMerchantEnvelope<T>(value:unknown,actor:number,store:number|null,guard:(data:unknown)=>data is T,scopeKey?:string):MerchantManagementEnvelope<T>{
  assert(isMerchantEnvelope(value)&&value.actor_uid===actor&&(store===null||value.store_id===store)&&(!scopeKey||value.scope_key===scopeKey),'门店或账号信息已变化，请重新读取');
  assert(guard(value.data));return value as MerchantManagementEnvelope<T>;
}
export function isMerchantContext(value:unknown):value is MerchantManagementContext{
  if(!record(value)||!Array.isArray(value.stores)||value.stores.length>100||!record(value.capabilities)||!keys.every(key=>typeof (value.capabilities as Record<string,unknown>)[key]==='boolean'))return false;
  const stores=value.stores;return stores.every(store=>record(store)&&int(store.store_id,1)&&int(store.staff_id,1)&&text(store.name,200))&&new Set(stores.map(store=>store.store_id)).size===stores.length&&(value.selected_store_id===null||int(value.selected_store_id,1)&&stores.some(store=>store.store_id===value.selected_store_id));
}
export function isMerchantActions(value:unknown):value is MerchantOrderActions{return record(value)&&keys.every(key=>{const action=value[key];return record(action)&&typeof action.available==='boolean'&&text(action.reason,500);});}
export function isMerchantCart(value:unknown):value is MerchantOrderCart{
  if(!record(value)||!integers(value,['id','product_id','product_type','cart_num','refund_num','surplus_num','split_surplus_num','is_gift','is_support_refund','is_writeoff','write_times','write_surplus_times','write_start','write_end'])||!strings(value,['unique','cart_id'],128)||!monies(value,['truePrice','vip_truePrice','vip_sum_truePrice','sum_true_price','postage_price','coupon_price','integral_price','promotions_true_price'])||!record(value.productInfo))return false;
  const product=value.productInfo,sku=product.attrInfo;return int(value.id,1)&&record(sku)&&int(product.id)&&text(product.store_name,500)&&image(product.image)&&merchantMoney(product.price)&&text(sku.suk,500)&&image(sku.image)&&merchantMoney(sku.price);
}
export function isMerchantOrder(value:unknown):value is MerchantOrderListItem{
  if(!record(value)||!int(value.id,1)||!int(value.pid,-1)||!merchantOrderId(value.order_id)||!integers(value,['uid','store_id','supplier_id','total_num','pay_integral','paid','status','shipping_type','add_time','pay_time','refund_status','refund_type','type','pink_id','product_type'])||!strings(value,['real_name','user_phone','user_address','nickname','pay_type','_add_time','_pay_time','delivery_type','delivery_name','delivery_code','delivery_id','type_name','mark','remark'])||!monies(value,['total_price','total_postage','pay_price','pay_postage','coupon_price','deduction_price','promotions_price','first_order_price','refund_price'])||!record(value._status)||!Array.isArray(value.cartInfo)||value.cartInfo.length>500||!value.cartInfo.every(isMerchantCart)||!Array.isArray(value.refund)||value.refund.length>200||!isMerchantActions(value.actions)||!hash(value.revision)||typeof value.is_all_refund!=='boolean')return false;
  return int(value._status._type,-4)&&strings(value._status,['_title','_msg','_class','_payType','_deliveryType'])&&value.refund.every(item=>record(item)&&int(item.id,1)&&merchantOrderId(item.order_id)&&int(item.refund_type)&&int(item.refund_num)&&merchantMoney(item.refund_price));
}
function safeForm(value:unknown,depth=0):boolean{if(depth>6)return false;if(value===null||typeof value==='boolean')return true;if(typeof value==='number')return Number.isFinite(value);if(typeof value==='string')return text(value,4000);if(Array.isArray(value))return value.length<=100&&value.every(item=>safeForm(item,depth+1));return record(value)&&Object.keys(value).length<=100&&Object.entries(value).every(([key,item])=>text(key,100)&&safeForm(item,depth+1));}
export function isMerchantDetail(value:unknown):value is MerchantOrderDetail{
  if(!isMerchantOrder(value)||!record(value))return false;const review=value.review,customer=value.customer,store=value.store;
  return record(review)&&integers(review,['uid','storeOrderId','storeId','supplierId','paid','rawStatus','refundStatus'])&&review.orderId===value.order_id&&review.storeOrderId===value.id&&review.storeId===value.store_id&&merchantMoney(review.payPrice)&&text(review.payType,100)&&record(customer)&&customer.uid===value.uid&&strings(customer,['nickname','level_name'],500)&&image(customer.avatar)&&(customer.vip_discount===''||merchantMoney(customer.vip_discount))&&typeof customer.pay_vip_status==='boolean'&&merchantMoney(value.vip_true_price)&&Array.isArray(value.promotions_detail)&&value.promotions_detail.length<=500&&value.promotions_detail.every(item=>record(item)&&integers(item,['promotions_id','product_id'])&&merchantMoney(item.promotions_price)&&text(item.title,500))&&Array.isArray(value.give_coupon)&&value.give_coupon.length<=100&&value.give_coupon.every(item=>record(item)&&int(item.id)&&text(item.coupon_title,500))&&int(value.give_integral)&&safeForm(value.custom_form)&&strings(value,['virtual_info','fictitious_content'],65536)&&strings(value,['refund_reason_wap_explain','refund_reason_wap','refund_reason'],4000)&&integers(value,['refund_reason_time','stop_time'])&&Array.isArray(value.refund_img)&&value.refund_img.length<=20&&value.refund_img.every(image)&&Array.isArray(value.refund_goods_img)&&value.refund_goods_img.length<=20&&value.refund_goods_img.every(image)&&(value.pinkStatus===null||int(value.pinkStatus))&&(value.invoice===null||record(value.invoice)&&integers(value.invoice,['id','status','is_refund']))&&Array.isArray(value.split)&&value.split.length<=500&&value.split.every(item=>record(item)&&integers(item,['id','pid','paid','status','total_num'])&&merchantOrderId(item.order_id)&&merchantMoney(item.pay_price)&&strings(item,['delivery_type','delivery_name','delivery_code','delivery_id']))&&record(store)&&store.id===value.store_id&&strings(store,['name','phone','address','detailed_address']);
}
export function isMerchantStatistics(value:unknown):value is MerchantOrderStatistics{return record(value)&&integers(value,['order_count','unpaid_count','unshipped_count','received_count','evaluated_count','unwritoff_count','complete_count','refunding_count','refunded_count','refund_count','todayCount','proCount','monthCount'])&&monies(value,['sum_price','todayPrice','proPrice','monthPrice'])&&[1,2].includes(Number(value.yue_pay_status))&&[0,1].includes(Number(value.pay_weixin_open))&&typeof value.ali_pay_status==='boolean'&&value.metric_scope==='current_store_fulfillments_pid_gte_0';}
export function isMerchantPeriod(value:unknown):value is MerchantOrderPeriod{return record(value)&&[1,7,30].includes(Number(value.type))&&integers(value,['start','end_exclusive','previous_start','after_number','after_pay_number','today_visits'])&&Number(value.start)<Number(value.end_exclusive)&&merchantMoney(value.after_price)&&typeof value.growth_rate==='number'&&Number.isFinite(value.growth_rate)&&text(value.increase_time,100)&&[1,2].includes(Number(value.increase_time_status))&&value.visit_scope==='current_store_product_visit_events';}
export function isMerchantChart(value:unknown):value is MerchantOrderChartPoint[]{return Array.isArray(value)&&value.length<=31&&value.every(item=>record(item)&&/^\d{4}-\d{2}-\d{2}$/u.test(String(item.date))&&text(item.time,100)&&int(item.num)&&merchantMoney(item.price))&&new Set(value.map(item=>item.date)).size===value.length;}
export function isMerchantDaily(value:unknown):value is MerchantOrderDailyRow{return record(value)&&/^\d{4}-\d{2}-\d{2}$/u.test(String(value.date))&&text(value.time,100)&&merchantMoney(value.price)&&integers(value,['count','visit','add_time']);}
export function isMerchantPaged<T>(guard:(row:unknown)=>row is T){return (value:unknown):value is MerchantPaged<T>=>record(value)&&Array.isArray(value.list)&&value.list.length<=100&&value.list.every(guard)&&int(value.count)&&int(value.page,1)&&int(value.limit,1)&&Number(value.limit)<=100&&value.list.length<=Number(value.limit)&&typeof value.has_more==='boolean';}
export function isMerchantDelivery(value:unknown):value is MerchantDeliveryDefaults{return record(value)&&strings(value,['express_temp_id','to_name','config_export_id','to_tel','to_add'])&&[0,1].includes(Number(value.config_export_open))&&['city_delivery_status','self_delivery_status','dada_delivery_status','uu_delivery_status'].every(key=>typeof value[key]==='boolean');}
export function isMerchantAgents(value:unknown):value is MerchantDeliveryAgent[]{return Array.isArray(value)&&value.length<=1000&&value.every(item=>record(item)&&int(item.uid,1)&&strings(item,['nickname','phone'],200))&&new Set(value.map(item=>item.uid)).size===value.length;}
export function isMerchantCarriers(value:unknown):value is MerchantCarrier[]{return Array.isArray(value)&&value.length<=1000&&value.every(item=>record(item)&&int(item.id,1)&&strings(item,['name','code'],200))&&new Set(value.map(item=>item.id)).size===value.length;}
export function isMerchantDeliveryGain(value:unknown):value is MerchantDeliveryGain{return record(value)&&int(value.id,1)&&merchantOrderId(value.order_id)&&strings(value,['real_name','user_phone','user_address'])&&hash(value.revision);}
function isTrackingPackage(value:unknown):value is MerchantTrackingPackage{return record(value)&&merchantOrderId(value.orderId)&&strings(value,['deliveryStatus','expressName','expressCode','expressNo','message'])&&['pending','in_transit','delivered','exception','not_configured','temporarily_unavailable'].includes(String(value.trackingState))&&['merchant','carrier','cache'].includes(String(value.trackingSource))&&int(value.lastUpdatedAt)&&Array.isArray(value.traces)&&value.traces.length<=1000&&value.traces.every(trace=>record(trace)&&strings(trace,['time','content','status'],2000));}
export function isMerchantExpress(value:unknown):value is MerchantExpressResult{return isTrackingPackage(value)&&record(value)&&Array.isArray(value.packages)&&value.packages.length<=500&&value.packages.every(isTrackingPackage)&&Array.isArray(value.express)&&value.express.length<=1000&&value.express.every(trace=>record(trace)&&strings(trace,['time','status'],2000))&&record(value.order)&&merchantOrderId(value.order.order_id)&&strings(value.order,['delivery_id','delivery_name','delivery_code','delivery_type']);}
export function merchantDiagnostic(issues:string[]){const messages=issues.filter(issue=>issue!=='merchant_metrics_use_current_store_fulfillments_pid_gte_0').map(issue=>issue==='merchant_electronic_waybill_store_actor_unavailable'?'电子面单当前暂不可用，可使用手工物流发货。':issue==='merchant_refund_images_require_reviewed_financial_detail'?'历史退款凭证需打开对应退款申请核对。':'部分历史数据或操作暂不可用，请刷新后查看。');return [...new Set(messages)].join(' ');}
export function merchantFormRows(value:unknown){if(!value)return [];const entries=Array.isArray(value)?value.map((item,index)=>[String(index+1),item] as const):record(value)?Object.entries(value):[];return entries.map(([name,item])=>({name,value:typeof item==='string'?item:JSON.stringify(item)}));}
export function merchantDate(epoch:number){return epoch?new Date(epoch*1000).toLocaleString():'';}
export function merchantMoneyInput(value:string){const clean=value.trim();assert(merchantMoney(clean)&&clean.length<=15,'金额最多保留两位小数');const [whole,fraction='']=clean.split('.');return `${String(Number(whole))}.${fraction.padEnd(2,'0')}`;}
export function merchantMoneySum(values:string[]){let cents=0;for(const value of values){assert(merchantMoney(value),'订单金额格式无效');const [whole,fraction='']=value.split('.');cents+=Number(whole)*100+Number(fraction.padEnd(2,'0'));assert(Number.isSafeInteger(cents),'订单金额超出范围');}return `${Math.floor(cents/100)}.${String(cents%100).padStart(2,'0')}`;}
export function merchantDateRange(index:number,now=Date.now()){if(!index)return '';assert(Number.isInteger(index)&&index>=1&&index<=4,'日期筛选无效');const end=new Date(now+8*3600000),start=new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth(),end.getUTCDate()));if(index===1)start.setUTCDate(start.getUTCDate()-2);else{start.setUTCDate(1);if(index>=3)start.setUTCMonth(start.getUTCMonth()-(index===3?2:5));}const format=(date:Date)=>`${date.getUTCFullYear()}/${String(date.getUTCMonth()+1).padStart(2,'0')}/${String(date.getUTCDate()).padStart(2,'0')}`;return `${format(start)}-${format(end)}`;}
export async function merchantRequestKey():Promise<string>{
  const format=(bytes:Uint8Array)=>{assert(bytes.length===16,'安全请求标识生成失败');bytes[6]=(bytes[6]!&15)|64;bytes[8]=(bytes[8]!&63)|128;const hex=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`;};
  // #ifdef H5
  if(typeof globalThis.crypto?.getRandomValues==='function')return format(globalThis.crypto.getRandomValues(new Uint8Array(16)));
  // #endif
  if(typeof uni.getRandomValues==='function')return new Promise((resolve,reject)=>uni.getRandomValues({length:16,success:result=>{try{resolve(format(new Uint8Array(result.randomValues)));}catch(error){reject(error);}},fail:()=>reject(Error('安全请求标识生成失败，尚未提交'))}));
  throw Error('当前环境缺少安全随机数，尚未提交操作');
}
const storageKey='merchant_pending_intents_v1';
export function merchantPendingIntents():MerchantPendingIntent[]{const saved=uni.getStorageSync(storageKey);return Array.isArray(saved)?saved.filter(item=>record(item)&&typeof item.request_key==='string'&&/^[0-9a-f-]{36}$/u.test(item.request_key)&&int(item.actor_uid,1)&&int(item.store_id,1)&&hash(item.scope_key)&&text(item.action,64)&&merchantOrderId(item.order_id)&&typeof item.receipt_path==='string'&&/^\/store\/manager\/order\/[A-Za-z0-9_./%-]+$/u.test(item.receipt_path)&&['GET','POST'].includes(String(item.receipt_method))&&int(item.created_at)&&(item.funds_pending===undefined||typeof item.funds_pending==='boolean')&&(item.body===undefined||safeForm(item.body)&&JSON.stringify(item.body).length<=30000)&&(item.request_hash===undefined||hash(item.request_hash))).slice(0,100) as MerchantPendingIntent[]:[];}
export function retainMerchantIntent(intent:MerchantPendingIntent){const saved=merchantPendingIntents().filter(item=>item.request_key!==intent.request_key);assert(saved.length<100,'待确认操作过多，请先查询原操作结果');uni.setStorageSync(storageKey,[...saved,intent]);}
export function releaseMerchantIntent(key:string){uni.setStorageSync(storageKey,merchantPendingIntents().filter(item=>item.request_key!==key));}
