<template><DeliveryShell title="配送扫码核对" :controller="controller"><view class="delivery-card"><text class="delivery-label">订单核销码 / 会员付款码</text><text class="delivery-muted">扫描或输入当前会员码可查询本配送范围内的订单。查询后仍需选择订单和实际送达数量。</text><input v-model="code" type="text" maxlength="32" placeholder="输入订单码或会员码，保留开头的0" :disabled="reading||controller.busy.value" /><view class="delivery-controls"><button :disabled="reading||!code||controller.busy.value" @tap="lookup">查询当前范围订单</button><button v-if="nativeScanAvailable" :disabled="reading||controller.busy.value" @tap="scan">扫码</button></view><text v-if="!nativeScanAvailable" class="delivery-muted">当前网页可手动输入码；原生扫码需在 App 或微信小程序中使用。</text></view><view v-if="pageError" class="delivery-warning">{{ pageError }}</view><view v-if="reading" class="delivery-empty">正在核对当前配送范围…</view><view v-if="queried&&!reading&&!previews.length" class="delivery-empty">未找到本配送范围内可查看的订单</view><view v-for="preview in previews" :key="preview.id" class="delivery-card"><view class="delivery-row"><text class="delivery-label">{{ preview.order_id }}</text><text class="delivery-status">{{ preview.status===2?'已配送':preview.status===5?'部分送达':'待核对' }}</text></view><text>商品 {{ preview.total_num }} 件 · 已核销 {{ preview.writeoff_count }} 件 / 次</text><view v-for="cart in preview.cart_info" :key="cart.id" class="delivery-cart"><image v-if="cart.cart_info.productInfo.image" :src="userCenterMedia(cart.cart_info.productInfo.image)" class="delivery-cart-image" mode="aspectFill" /><view class="delivery-cart-copy"><text>{{ cart.cart_info.productInfo.store_name }}</text><text class="delivery-muted">{{ cart.cart_info.productInfo.attrInfo.suk }}</text><text>剩余可核销 {{ cart.write_surplus_times }}</text></view></view><text v-if="!preview.actions.writeoff.available" class="delivery-reason">{{ preview.actions.writeoff.reason }}</text><view class="delivery-controls"><button :disabled="!preview.actions.writeoff.available" @tap="controller.go('scanDetail',{orderId:preview.id})">核对数量并送达</button><button @tap="controller.go('scanDetail',{orderId:preview.id,tab:'records'})">核销记录</button><button @tap="controller.go('orderDetail',{orderId:preview.id})">完整订单详情</button></view></view></DeliveryShell></template>
<script setup lang="ts">
import {ref} from 'vue';import DeliveryShell from '@/components/deliveryWorkbench/DeliveryShell.vue';import {useDeliveryWorkbench} from '@/composables/useDeliveryWorkbench';import {deliveryCode,isDeliveryPreviews} from '@/utils/deliveryWorkbench';import {userCenterMedia} from '@/utils/userCenter';import type {DeliveryWriteoffPreview} from '@/types/deliveryWorkbench';
const code=ref(''),previews=ref<DeliveryWriteoffPreview[]>([]),reading=ref(false),queried=ref(false),pageError=ref('');let lookupEpoch=0;
const nativeScanAvailable=ref(false);
// #ifndef H5
nativeScanAvailable.value=typeof uni.scanCode==='function';
// #endif
const controller=useDeliveryWorkbench({clear(){lookupEpoch++;code.value='';previews.value=[];reading.value=false;queried.value=false;pageError.value='';}});
async function lookup(){if(reading.value||!controller.context.value||!controller.selected.value)return;if(!deliveryCode(code.value)){pageError.value='请输入有效的订单码或会员码';return;}reading.value=true;previews.value=[];pageError.value='';const valid=controller.fence(),generation=++lookupEpoch,original=code.value;
  try{const response=await controller.read('writeoff/info',isDeliveryPreviews,{version:'delivery-workbench-v1',code:original},'POST');if(!valid()||generation!==lookupEpoch||code.value!==original)return;if(/^\d{12}$/u.test(original)&&(response.data.lookup_kind!=='order-code'||response.data.list.length>1))throw Error('订单码查询响应不匹配');previews.value=response.data.list;queried.value=true;}
  catch(failure){if(valid()&&generation===lookupEpoch)pageError.value=failure instanceof Error?failure.message:'当前范围暂无法核对';}finally{if(valid()&&generation===lookupEpoch)reading.value=false;}
}
function scan(){if(!nativeScanAvailable.value||reading.value||controller.busy.value)return;const valid=controller.fence(),generation=lookupEpoch;
  // #ifndef H5
  uni.scanCode({onlyFromCamera:true,success:result=>{if(!valid()||generation!==lookupEpoch)return;if(!deliveryCode(result.result)){pageError.value='扫描内容不是有效的订单码或会员码';return;}code.value=result.result;previews.value=[];queried.value=false;pageError.value='';},fail:failure=>{if(valid()&&generation===lookupEpoch&&!/cancel/iu.test(failure.errMsg||''))pageError.value='扫码未完成，可手动输入当前码';}});
  // #endif
}
</script>
