<template><DeliveryShell title="确认配送送达" :controller="controller"><view class="delivery-tabs"><button :class="{active:tab==='goods'}" @tap="tab='goods'">商品与数量</button><button :class="{active:tab==='records'}" @tap="tab='records'">核销记录</button><button v-if="preview" @tap="controller.go('orderDetail',{orderId:preview.id})">完整订单详情</button></view><template v-if="preview"><DeliveryOperationPanel v-show="tab==='goods'" :key="preview.revision" :controller="controller" :preview="preview" :fresh-required="freshRequired" @confirmed="confirmed" @expired="windowChanged" /><view v-if="freshRequired" class="delivery-card"><text>本次已确认 {{ lastOutcome==='delivered'?'全部送达':'部分送达' }}。继续操作前需重新读取当前订单。</text><view class="delivery-controls"><button @tap="controller.load">重新读取剩余商品</button><button @tap="controller.go('index')">返回配送订单</button></view></view></template><view v-show="tab==='records'" class="delivery-card" data-delivery="records"><text class="delivery-label">实际核销记录</text><text class="delivery-muted">记录按真实操作时间读取；历史记录未能证明配送身份时显示“历史操作人员”。</text><view v-for="record in records" :key="record.id" class="delivery-cart"><image v-if="record.cart_info.productInfo.attrInfo.image||record.cart_info.productInfo.image" :src="userCenterMedia(record.cart_info.productInfo.attrInfo.image||record.cart_info.productInfo.image)" class="delivery-cart-image" mode="aspectFill" /><view class="delivery-cart-copy"><text>{{ record.cart_info.productInfo.store_name }}</text><text class="delivery-muted">{{ record.cart_info.productInfo.attrInfo.suk }}</text><view class="delivery-row"><text>核销 {{ record.writeoff_num }} 件 / 次</text><text>¥{{ record.writeoff_price }}</text></view><text>{{ record.time||deliveryDate(record.add_time) }}</text><text class="delivery-muted">{{ operatorLabel(record) }}</text></view></view><text v-if="!records.length">当前订单暂无可读取的核销记录</text><button v-if="recordsMore" :disabled="recordsBusy" class="delivery-full-button" @tap="loadMoreRecords">加载更多记录</button></view><view v-if="pageError" class="delivery-warning">{{ pageError }}</view></DeliveryShell></template>
<script setup lang="ts">
import {ref} from 'vue';import {onReachBottom} from '@dcloudio/uni-app';import DeliveryShell from '@/components/deliveryWorkbench/DeliveryShell.vue';import DeliveryOperationPanel from '@/components/deliveryWorkbench/DeliveryOperationPanel.vue';import {useDeliveryWorkbench} from '@/composables/useDeliveryWorkbench';import {deliveryInt,isDeliveryPreviews,isDeliveryRecords,deliveryDate} from '@/utils/deliveryWorkbench';import {userCenterMedia} from '@/utils/userCenter';import type {DeliveryWriteoffPreview,DeliveryWriteoffRecord} from '@/types/deliveryWorkbench';
const preview=ref<DeliveryWriteoffPreview|null>(null),records=ref<DeliveryWriteoffRecord[]>([]),tab=ref<'goods'|'records'>('goods'),recordsMore=ref(false),recordsBusy=ref(false),pageError=ref(''),freshRequired=ref(false),lastOutcome=ref('');let orderId=0,recordPage=1,pageEpoch=0;
const controller=useDeliveryWorkbench({query(query){orderId=Number(query.orderId||query.id);if(query.tab==='records')tab.value='records';},clear(){pageEpoch++;preview.value=null;records.value=[];recordsMore.value=false;recordsBusy.value=false;pageError.value='';freshRequired.value=false;lastOutcome.value='';recordPage=1;},async load(c){if(!deliveryInt(orderId,1))throw Error('订单编号无效');const valid=c.fence(),generation=pageEpoch;const [response,logs]=await Promise.all([c.read('writeoff/info',isDeliveryPreviews,{version:'delivery-workbench-v1',order_id:orderId},'POST'),c.read('writeoff/records',isDeliveryRecords,{order_id:orderId,page:1,limit:15})]);if(!valid()||generation!==pageEpoch)return;if(response.data.lookup_kind!=='order-id'||response.data.list.length!==1||response.data.list[0]?.id!==orderId)throw Error('当前订单核对响应不匹配');preview.value=response.data.list[0];records.value=logs.data.list;recordsMore.value=logs.data.has_more;}});
function windowChanged(){if(!controller.current()||freshRequired.value||controller.pending.value.some(intent=>intent.body.order_id===orderId))return;void controller.load();}
function confirmed(outcome:string){lastOutcome.value=outcome;freshRequired.value=true;records.value=[];recordsMore.value=false;pageError.value='核销记录已变化，请重新读取实际记录。';}
function operatorLabel(record:DeliveryWriteoffRecord){const operator=record.operator;if(operator.kind==='delivery'&&operator.delivery_id!==null)return `配送身份 ${operator.delivery_id}`;return ({staff:'门店核销人员',admin:'平台管理人员',kefu:'客服操作人员',unknown:'历史操作人员'} as Record<string,string>)[operator.kind]||'历史操作人员';}
async function loadMoreRecords(){if(recordsBusy.value||!recordsMore.value||freshRequired.value)return;recordsBusy.value=true;pageError.value='';const valid=controller.fence(),generation=pageEpoch;try{const result=await controller.read('writeoff/records',isDeliveryRecords,{order_id:orderId,page:recordPage+1,limit:15});if(!valid()||generation!==pageEpoch)return;if(result.data.page!==recordPage+1||result.data.list.some(row=>records.value.some(previous=>row.id===previous.id)))throw Error('核销记录分页发生变化，请刷新');recordPage++;records.value.push(...result.data.list);recordsMore.value=result.data.has_more;}catch(failure){if(valid()&&generation===pageEpoch)pageError.value=failure instanceof Error?failure.message:'记录暂不可读';}finally{if(valid()&&generation===pageEpoch)recordsBusy.value=false;}}
onReachBottom(()=>{if(tab.value==='records')void loadMoreRecords();});
</script>
