import {and,asc,eq,inArray} from 'drizzle-orm';
import type {Container,DbClient} from '@/lib/di';
import {user,userLevel,userMoney,userBill,otherOrder,otherOrderStatus,storeCouponUser,storeCouponIssueUser,legacyCategory,userLabel,storeCouponIssue,systemUserLevel} from '@/models/schema';
import {outRequestHash} from '@/services/out/OutIdempotency';
import {applyMobileUserState,applyMobileUserFinance,applyMobileUserMembership,applyMobileUserCoupons,type MobileUserCoreOptions,type MobileUserCoreExpectation} from '@/services/user/MobileUserManagementCore';
import {ValidateException} from '@/utils/errors';
import type {CustomerWorkActor} from './CustomerWorkScope';
import {customerUserIssueReason} from './CustomerWorkUserReadService';
import type {CustomerJson} from './CustomerWorkOperationRequest';
import {CustomerWorkUserOperationRequest,customerUserExactKeys,customerUserPayload,assertCustomerUserSnapshots,type CustomerUserOperationContext,type CustomerUserOperationKind} from './CustomerWorkUserOperationRequest';

/** These expected effects come only from the shared caller-transaction core.
 * Neither HTTP input nor a customer actor can supply an attestation callback. */
async function verifyExpected(tx:DbClient,facts:MobileUserCoreExpectation){
 const equal=async(actual:unknown,expected:unknown)=>{if(await outRequestHash(JSON.parse(JSON.stringify(actual)))!==await outRequestHash(JSON.parse(JSON.stringify(expected))))throw new ValidateException('用户实际写入结果未完成回读核验');};
 for(const expected of facts.accounts){const[row]=await tx.select().from(user).where(eq(user.uid,expected.uid)).limit(1);if(!row)throw new ValidateException('用户实际写入结果不存在');await equal(Object.fromEntries(Object.keys(expected.values).map(key=>[key,Reflect.get(row,key)])),expected.values);}
 for(const expected of facts.levels??[])await equal(await tx.select().from(userLevel).where(eq(userLevel.uid,expected.uid)).orderBy(asc(userLevel.id)),expected.rows.sort((a,b)=>a.id-b.id));
 for(const expected of facts.records??[]){let row:Record<string,unknown>|undefined;if(expected.kind==='membership_status'){const rows=await tx.select().from(otherOrderStatus).where(eq(otherOrderStatus.oid,expected.oid));if(rows.length!==1)throw new ValidateException('用户会员状态记录回读不唯一');row=rows[0];}else if(expected.kind==='money')row=(await tx.select().from(userMoney).where(eq(userMoney.id,expected.id)).limit(1))[0];else if(expected.kind==='integral')row=(await tx.select().from(userBill).where(eq(userBill.id,expected.id)).limit(1))[0];else if(expected.kind==='membership')row=(await tx.select().from(otherOrder).where(eq(otherOrder.id,expected.id)).limit(1))[0];else row=(await tx.select().from(storeCouponUser).where(eq(storeCouponUser.id,expected.id)).limit(1))[0];if(!row)throw new ValidateException('用户实际账单或券记录不存在');await equal(Object.fromEntries(Object.keys(expected.values).map(key=>[key,row![key]])),expected.values);}
 if(facts.issue){const[row]=await tx.select().from(storeCouponIssue).where(eq(storeCouponIssue.id,facts.issue.id)).limit(1);if(row?.remainCount!==facts.issue.remainCount)throw new ValidateException('用户赠券库存回读不一致');}
 if(facts.issueUsers){const f=facts.issueUsers,rows=await tx.select().from(storeCouponIssueUser).where(and(eq(storeCouponIssueUser.issueCouponId,f.issueId),inArray(storeCouponIssueUser.uid,f.uids),eq(storeCouponIssueUser.addTime,f.now)));for(let i=0;i<f.uids.length;i++)if(rows.filter(r=>r.uid===f.uids[i]).length!==f.before[i]+1)throw new ValidateException('用户赠券发行记录回读不一致');}
}

export class CustomerWorkUserOperationService {
 readonly requests:CustomerWorkUserOperationRequest;
 constructor(readonly container:Container){this.requests=new CustomerWorkUserOperationRequest(container);}
 async execute(kind:CustomerUserOperationKind,context:CustomerUserOperationContext,value:unknown){customerUserPayload(kind,value);return this.requests.execute(kind,context,value,async(tx,_scope,states,p)=>{const payload=p.input.payload as Record<string,unknown>,uids=states.map(s=>s.account.uid);let expected:MobileUserCoreExpectation|undefined;const options:MobileUserCoreOptions={catalogLocked:true,semanticNoop:true,authorityLabel:'客服工作台调整用户',authorityRealm:'customer',assertBeforeMutation:db=>assertCustomerUserSnapshots(db,states),expected:facts=>{expected=facts;}};const finish=async(evidence:Record<string,CustomerJson>)=>{if(!expected)throw new ValidateException('用户写链未提供真实回读依据');await verifyExpected(tx,expected);return evidence;};
  if(kind==='replace_level'){const id=Number(payload.level_id),[level]=await tx.select().from(systemUserLevel).where(eq(systemUserLevel.id,id)).limit(1);if(!level||level.expNum<0||level.grade<0||!/^\d{1,10}\.\d{2}$/.test(level.discount)||Number(level.discount)>100||![0,1].includes(level.isForever))throw new ValidateException('会员等级定义无效');const result=await applyMobileUserState(tx,{type:1,uids,levelId:id},async()=>undefined,options);return finish({changed:result.changed,verified:true});}
  if(kind==='replace_group'){const result=await applyMobileUserState(tx,{type:4,uids,groupId:Number(payload.group_id)},async()=>undefined,options);return finish({changed:result.changed,verified:true});}
  if(kind==='replace_labels'){const labelIds=payload.label_ids as number[];if(labelIds.length){const rows=await tx.select({id:userLabel.id}).from(userLabel).innerJoin(legacyCategory,eq(legacyCategory.id,userLabel.labelCate)).where(and(inArray(userLabel.id,labelIds),eq(legacyCategory.ownerId,0),eq(legacyCategory.type,0),eq(legacyCategory.relationId,0),eq(legacyCategory.group,0),eq(legacyCategory.isShow,1)));if(rows.length!==labelIds.length)throw new ValidateException('用户标签分组不存在或不可用');}const result=await applyMobileUserState(tx,{type:5,uids,labelIds},async()=>undefined,options);return finish({changed:result.changed,verified:true});}
  if(kind==='grant_coupons'){const issueId=Number(payload.issue_id),[issue]=await tx.select().from(storeCouponIssue).where(eq(storeCouponIssue.id,issueId)).limit(1);if(!issue)throw new ValidateException('赠送优惠券不存在');const reason=customerUserIssueReason(issue,new Date());if(reason)throw new ValidateException(`赠送优惠券不可用：${reason}`);const result=await applyMobileUserCoupons(tx,{type:3,uids,couponId:issueId},async()=>undefined,options);return finish({changed:result.changed,issued_count:result.changed,issue_id:result.coupon_id,verified:true});}
  if(kind==='adjust_membership'){const account=states[0].account;if(![0,1,2,3].includes(account.isMoneyLevel)||![0,1].includes(account.isEverLevel)||account.overdueTime<0)throw new ValidateException('用户会员状态无效');const orderId=`cu${(await outRequestHash({version:'customer-user-membership-v1',actor_uid:p.actor.uid,request_key:p.key})).slice(0,30)}`,result=await applyMobileUserMembership(tx,{type:2,uids,daysStatus:payload.direction==='add'?1:2,days:Number(payload.days)},orderId,async()=>undefined,options);return finish({changed:result.changed,other_order_id:result.other_order_id,verified:true});}
  const moneyKind=kind==='adjust_money',amount=payload.amount,linkId=(await outRequestHash({version:'customer-user-finance-v1',actor_uid:p.actor.uid,request_key:p.key})).slice(0,32),result=await applyMobileUserFinance(tx,{uid:uids[0],status:payload.direction==='add'?1:2,kind:moneyKind?'money':'integral',moneyCents:moneyKind?Number(BigInt(String(amount).replace('.',''))):0,integral:moneyKind?0:Number(amount)},linkId,async()=>undefined,options);return finish(moneyKind?{changed:result.ledger_id?1:0,money_ledger_id:result.ledger_id,verified:true}:{changed:result.ledger_id?1:0,integral_ledger_id:result.ledger_id,verified:true});
 });}
 async outcome(actor:CustomerWorkActor,key:unknown){return{receipt:await this.requests.outcome(actor,key)};}
 async abandon(actor:CustomerWorkActor,key:string,value:unknown){customerUserExactKeys(value,['kind','input']);return{receipt:await this.requests.abandon(value.kind as CustomerUserOperationKind,{actor,request_key:key},value.input)};}
}
