import {and,asc,eq,inArray,sql} from 'drizzle-orm';
import type {DbClient} from '@/lib/di';
import {storeOrder,storeOrderCartInfo,storeOrderRefund,storeOrderInvoice,storeOrderStatus,storeProduct,storeProductAttrValue,storeSeckill,storeBargain,storeBargainUser,storeCombination,storeIntegral,storeDiscounts,user,userBill} from '@/models/schema';
import {storeOrderRefundSplit} from '@/models/schema/order_refund_split';
import {ValidateException} from '@/utils/errors';
import {amountToCents} from '@/services/payment/RefundGateway';
import {readRefundQuantityReservation,refundClaimCartKey,isMaterializedRefundClaim} from '@/services/order/RefundQuantityReservation';
import {refundOrderSplitFingerprint} from '@/services/order/RefundOrderSplitIdentity';
import {planOrderFinancialSplit,planCompletedRefundLineCompensation} from '@/services/order/OrderSplitFinance';
import {loadRefundOrderGeneration,currentGenerationRefunds} from '@/services/order/RefundOrderGeneration';
import {readRefundEarnedIncomeScope,captureRefundEarnedIncomeScope} from '@/services/order/RefundEarnedIncome';
import {readBargainOrderParticipation} from '@/services/activity/BargainOrderSnapshot';
import {outRequestHash} from '@/services/out/OutIdempotency';
import type {FinancialOrder,FinancialRefund} from './CustomerWorkFinancialReadService';

const fail=()=>new ValidateException('实际退款结算及实体归属证据不完整，请继续核对原请求');
const requireFact=(ok:boolean)=>{if(!ok)throw fail();};
function json(value:string,max:number){if(typeof value!=='string'||new TextEncoder().encode(value).length>max)throw fail();try{const parsed=JSON.parse(value);if(max===65536)requireFact(!!parsed&&typeof parsed==='object'&&!Array.isArray(parsed));return parsed;}catch{throw fail();}}
function object(value:unknown):Record<string,unknown>{requireFact(!!value&&typeof value==='object'&&!Array.isArray(value));return value as Record<string,unknown>;}
function snapshot(value:string){const result=object(json(value,16777216)),source=object(result.source),refund=object(result.refund);requireFact(result.version==='refund-order-materialization-v1'&&Array.isArray(result.carts)&&result.carts.length>0&&result.carts.length<=100&&result.carts.every((x:unknown)=>{const row=object(x);return Number.isSafeInteger(row.id)&&Number.isSafeInteger(row.oid)&&Number.isSafeInteger(row.uid)&&Number.isSafeInteger(row.cartNum)&&typeof row.cartId==='string'&&typeof row.cartInfo==='string';}));return{...result,source,refund,carts:result.carts} as unknown as {version:string;source:FinancialOrder;refund:FinancialRefund;carts:Array<typeof storeOrderCartInfo.$inferSelect>;payment:FinancialOrder};}
function pointIds(value:string):number[]{const ids=json(value,16384);requireFact(Array.isArray(ids)&&ids.length<=1024&&ids.every((x:unknown)=>typeof x==='number'&&Number.isSafeInteger(x)&&x>0)&&new Set(ids).size===ids.length);return ids;}
interface InventorySource {id:number;stock:number;quota:number;sales:number;}
async function activityInventory(tx:DbClient,type:number,id:number):Promise<InventorySource[]>{
 requireFact([1,2,3,4].includes(type)&&Number.isSafeInteger(id)&&id>0);
 const table=type===1?storeSeckill:type===2?storeBargain:type===3?storeCombination:storeIntegral;
 return tx.select({id:table.id,stock:table.stock,quota:table.quota,sales:table.sales}).from(table).where(eq(table.id,id)).limit(2);
}
/** Match the mature inventory namespaces, including its bounded legacy bargain
 * fallback. These are observations, not late locks after the settlement actor. */
async function activitySource(tx:DbClient,order:FinancialOrder,carts:Array<typeof storeOrderCartInfo.$inferSelect>){
 if(order.status!==0||![1,2,3,4].includes(order.type))return null;
 let id=order.activityId,rows:InventorySource[];
 if(order.type===2){
  let identity:ReturnType<typeof readBargainOrderParticipation>;
  try{identity=readBargainOrderParticipation(carts,order.uid,order.activityId);}catch{throw fail();}
  if(identity){id=identity.activityId;rows=await activityInventory(tx,2,id);}
  else{rows=Number.isSafeInteger(id)&&id>0?await activityInventory(tx,2,id):[];if(!rows.length){const owners=await tx.select({bargainId:storeBargainUser.bargainId}).from(storeBargainUser).where(and(eq(storeBargainUser.uid,order.uid),eq(storeBargainUser.id,order.activityId))).limit(2);requireFact(owners.length===1);id=owners[0].bargainId;rows=await activityInventory(tx,2,id);}}
 }else rows=await activityInventory(tx,order.type,id);
 requireFact(rows.length<=1&&(order.type!==4||rows.length===1));
 const skuIds=[...new Set(carts.map(cart=>{const data=object(json(cart.cartInfo??'{}',65536)),sku=data.activitySku;return sku&&typeof sku==='object'&&!Array.isArray(sku)?Number((sku as Record<string,unknown>).id??0):0;}).filter(id=>Number.isSafeInteger(id)&&id>0))];
 const skus=skuIds.length?await tx.select().from(storeProductAttrValue).where(inArray(storeProductAttrValue.id,skuIds)).orderBy(asc(storeProductAttrValue.id)):[];
 return{type:order.type,id,main:rows[0]??null,skus};
}
/** Source rows are captured inside the core's actual authorization phase.
 * They are not fixtures or calculated receipts. A stock race fails closed. */
export async function captureFinancialEffects(tx:DbClient,order:FinancialOrder,refund:FinancialRefund){
 const carts=await tx.select().from(storeOrderCartInfo).where(eq(storeOrderCartInfo.oid,order.id)).orderBy(asc(storeOrderCartInfo.id)).limit(101);requireFact(carts.length<=100);
 const ids=[...new Set(carts.map(x=>x.productId))],products=ids.length?await tx.select().from(storeProduct).where(inArray(storeProduct.id,ids)).orderBy(asc(storeProduct.id)):[],skus=ids.length?await tx.select().from(storeProductAttrValue).where(inArray(storeProductAttrValue.productId,ids)).orderBy(asc(storeProductAttrValue.id)):[],accounts=await tx.select().from(user).where(eq(user.uid,order.uid)).limit(2),bills=await tx.select().from(userBill).where(and(eq(userBill.uid,order.uid),inArray(userBill.linkId,[String(order.id),refund.orderId]))).limit(1025);
 const activity=await activitySource(tx,order,carts),packages=order.status===0&&order.type===5&&order.activityId>0?await tx.select().from(storeDiscounts).where(eq(storeDiscounts.id,order.activityId)).limit(2):[];requireFact(packages.length<=1);
 let completedCents=0;
 if(order.status===0&&order.type===5){const history=await tx.select().from(storeOrderRefund).where(and(eq(storeOrderRefund.storeOrderId,order.id),eq(storeOrderRefund.refundType,6),eq(storeOrderRefund.isCancel,0),eq(storeOrderRefund.isDel,0))).limit(202);requireFact(history.length<=201);const current=await currentGenerationRefunds(history,await loadRefundOrderGeneration(tx,order,carts));for(const previous of current){const amount=amountToCents(previous.refundedPrice);requireFact(amount!==null&&amount>=0);completedCents+=amount!;}requireFact(Number.isSafeInteger(completedCents));}
 requireFact(accounts.length===1&&bills.length<=1024);return{order:{...order},refund:{...refund},carts,products,skus,account:accounts[0],bills,activity,package:packages[0]??null,completedCents};
}
async function verifyInventoryEffects(tx:DbClient,before:Awaited<ReturnType<typeof captureFinancialEffects>>,refund:FinancialRefund){
 if(before.order.status!==0)return;
 const claim=readRefundQuantityReservation(refund);requireFact(!!claim);
 const skuQuantities=new Map<number,number>(),productQuantities=new Map<number,{all:number;stock:number}>(),activityQuantities=new Map<number,number>();let activityCount=0;
 for(const item of claim!.items){
  const cart=before.carts.find(x=>x.id===item.rowId&&x.cartId===refundClaimCartKey(item));requireFact(!!cart);
  const data=object(json(cart!.cartInfo??'{}',65536)),snapshotSku=data.sku&&typeof data.sku==='object'&&!Array.isArray(data.sku)?data.sku as Record<string,unknown>:null,explicit=Number(snapshotSku?.id??0),matches=before.skus.filter(x=>x.productId===cart!.productId&&x.type===0&&(Number.isSafeInteger(explicit)&&explicit>0?x.id===explicit:x.unique===cart!.skuUnique));requireFact(matches.length===1);
  const sku=matches[0],product=productQuantities.get(cart!.productId)??{all:0,stock:0};skuQuantities.set(sku.id,(skuQuantities.get(sku.id)??0)+item.cartNum);product.all+=item.cartNum;if(sku.isRetired!==1)product.stock+=item.cartNum;productQuantities.set(cart!.productId,product);
  if(before.activity){
   const activity=before.activity,snapshotActivity=data.activitySku&&typeof data.activitySku==='object'&&!Array.isArray(data.activitySku)?data.activitySku as Record<string,unknown>:null,activityId=Number(snapshotActivity?.id??0),legacy=!activity.main&&!Object.hasOwn(data,'activitySku')&&Number.isSafeInteger(explicit)&&explicit>0;
   const matches=Number.isSafeInteger(activityId)&&activityId>0?activity.skus.filter(x=>x.id===activityId&&x.productId===activity.id&&x.type===activity.type):[];
   requireFact(matches.length===1||legacy);if(matches.length)activityQuantities.set(matches[0].id,(activityQuantities.get(matches[0].id)??0)+item.cartNum);activityCount+=item.cartNum;
  }
 }
 for(const[id,count]of skuQuantities){const previous=before.skus.find(x=>x.id===id)!;const actual=(await tx.select().from(storeProductAttrValue).where(eq(storeProductAttrValue.id,id)).limit(1))[0];requireFact(!!actual&&actual.productId===previous.productId&&actual.type===0&&actual.stock===previous.stock+count&&actual.sales===Math.max(0,previous.sales-count)&&actual.isRetired===previous.isRetired);}
 for(const[id,count]of productQuantities){const previous=before.products.find(x=>x.id===id),actual=(await tx.select().from(storeProduct).where(eq(storeProduct.id,id)).limit(1))[0];requireFact(!!previous&&!!actual&&actual.stock===previous.stock+count.stock&&actual.sales===Math.max(0,previous.sales-count.all));}
 if(before.activity){
  const source=before.activity,rows=await activityInventory(tx,source.type,source.id);requireFact(rows.length===(source.main?1:0));if(source.main){const actual=rows[0];requireFact(actual.stock===source.main.stock+activityCount&&actual.quota===source.main.quota+activityCount&&actual.sales===Math.max(0,source.main.sales-activityCount));}
  for(const[id,count]of activityQuantities){const previous=source.skus.find(x=>x.id===id)!,actual=(await tx.select().from(storeProductAttrValue).where(eq(storeProductAttrValue.id,id)).limit(1))[0];requireFact(!!actual&&actual.productId===source.id&&actual.type===source.type&&actual.stock===previous.stock+count&&actual.quota===previous.quota+count&&actual.sales===Math.max(0,previous.sales-count));}
 }
 if(before.order.type===5&&before.order.activityId>0){
  const amount=amountToCents(refund.refundPrice),paid=amountToCents(before.order.payPrice);requireFact(amount!==null&&paid!==null);const fully=before.completedCents+amount!>=paid!,rows=await tx.select().from(storeDiscounts).where(eq(storeDiscounts.id,before.order.activityId)).limit(2);requireFact(rows.length===(before.package?1:0));if(fully)requireFact(!!before.package);if(before.package){const actual=rows[0],increment=fully&&before.package.isLimit===1?1:0;requireFact(actual.isLimit===before.package.isLimit&&actual.limitNum===before.package.limitNum+increment);}
 }
}
export async function verifyFinancialLocalRefund(tx:DbClient,before:Awaited<ReturnType<typeof captureFinancialEffects>>){
 const refund=(await tx.select().from(storeOrderRefund).where(eq(storeOrderRefund.id,before.refund.id)).limit(1))[0];if(!refund)throw fail();requireFact(refund.refundType===6&&!refund.isDel&&!refund.isCancel&&refund.refundedPrice===refund.refundPrice&&refund.refundPrice===before.refund.refundPrice&&refund.storeOrderId===before.order.id&&refund.uid===before.order.uid);
 const claim=readRefundQuantityReservation(refund);requireFact(!!claim);const account=(await tx.select().from(user).where(eq(user.uid,refund.uid)).limit(1))[0];if(!account)throw fail();
 const refundCents=amountToCents(refund.refundPrice);requireFact(refundCents!==null);if(before.order.payType==='yue'&&refundCents!>0){const initial=amountToCents(before.account.nowMoney),current=amountToCents(account.nowMoney);requireFact(initial!==null&&current===initial+refundCents!);const bills=await tx.select().from(userBill).where(and(eq(userBill.uid,refund.uid),eq(userBill.linkId,refund.orderId),eq(userBill.type,'pay_product_refund'))).limit(2);requireFact(bills.length===1&&bills[0].pm===1&&bills[0].number===refund.refundPrice&&bills[0].balance===account.nowMoney&&!before.bills.some(x=>x.id===bills[0].id));}
 await verifyInventoryEffects(tx,before,refund);
 await verifyFinancialCompletedRefund(tx,refund);
 const actualBills=await tx.select().from(userBill).where(and(eq(userBill.uid,refund.uid),inArray(userBill.linkId,[String(before.order.id),refund.orderId]))).limit(1025);requireFact(actualBills.length<=1024);const originalIds=new Set(before.bills.map(x=>x.id)),pointDelta=actualBills.filter(x=>!originalIds.has(x.id)&&x.category==='integral');requireFact(pointDelta.every(x=>x.status===1&&/^\d{1,10}(?:\.0{1,2})?$/.test(x.number)&&[0,1].includes(x.pm)));requireFact(account.integral===before.account.integral+pointDelta.reduce((sum,x)=>sum+(x.pm===1?1:-1)*Number(x.number),0));
 const logs=await tx.select().from(storeOrderStatus).where(and(eq(storeOrderStatus.oid,before.order.id),eq(storeOrderStatus.changeType,'refund_price'))).limit(403);requireFact(logs.length<=402&&logs.some(x=>x.changeTime===refund.refundedTime&&x.changeMessage.includes(refund.refundPrice)));
}
/** Read-only proof from the immutable materializer record, current physical
 * partitions, invoice allocation and actual refund bill. No repair/finalizer. */
export async function verifyFinancialMaterializedRefund(tx:DbClient,refund:FinancialRefund,visited=new Set<number>()){
 requireFact(!visited.has(refund.id)&&visited.size<200);visited=new Set(visited).add(refund.id);
 const claim=readRefundQuantityReservation(refund);requireFact(isMaterializedRefundClaim(claim)&&refund.refundType===6&&refund.refundedPrice===refund.refundPrice&&!refund.isCancel&&!refund.isDel);
 const records=await tx.select().from(storeOrderRefundSplit).where(eq(storeOrderRefundSplit.refundId,refund.id)).limit(2);requireFact(records.length===1);const record=records[0];requireFact(record.fingerprint===await refundOrderSplitFingerprint(refund)&&record.sourceOrderId===refund.storeOrderId&&record.uid===refund.uid&&record.storeId===refund.storeId&&record.supplierId===refund.supplierId);
 const source=snapshot(record.sourceSnapshot);requireFact(source.source.id===record.sourceOrderId&&source.source.uid===refund.uid&&source.source.storeId===refund.storeId&&source.source.supplierId===refund.supplierId&&source.refund.id===refund.id);
 const selections=new Map(claim!.items.map(x=>[refundClaimCartKey(x),x.cartNum])),planning={...source.source,refundPrice:'0.00',backIntegral:'0.00'},planningCarts=source.carts.map(x=>({...x,refundNum:0,splitStatus:0,splitSurplusNum:x.cartNum})),plan=planOrderFinancialSplit(planning,planningCarts,selections);requireFact(!!plan);const orders=await tx.select().from(storeOrder).where(inArray(storeOrder.id,[record.paymentOrderId,record.sourceOrderId,record.selectedOrderId,...(record.remainingOrderId?[record.remainingOrderId]:[])])).limit(4),selected=orders.find(x=>x.id===record.selectedOrderId),remaining=orders.find(x=>x.id===record.remainingOrderId),payment=orders.find(x=>x.id===record.paymentOrderId);requireFact(!!selected&&!!payment&&selected!.uid===refund.uid&&selected!.storeId===refund.storeId&&selected!.supplierId===refund.supplierId&&selected!.paid===1&&selected!.refundType===6&&selected!.refundStatus===2&&selected!.refundPrice===refund.refundPrice&&selected!.payPrice===plan!.selected.payPrice&&(!record.remainingOrderId||!!remaining&&remaining.uid===refund.uid&&remaining.storeId===refund.storeId&&remaining.supplierId===refund.supplierId));
 const partitions=json(record.partitions,131072) as Array<{sourceRowId:number;sourceCartId:string;selectedRowId:number|null;remainingRowId:number|null;selectedNum:number;remainingNum:number}>;requireFact(Array.isArray(partitions)&&partitions.length===source.carts.length&&partitions.length<=100&&partitions.every(x=>!!x&&typeof x==='object'&&Object.keys(x).sort().join(',')==='remainingNum,remainingRowId,selectedNum,selectedRowId,sourceCartId,sourceRowId')&&new Set(partitions.map(x=>x.sourceRowId)).size===partitions.length);let actual=await tx.select().from(storeOrderCartInfo).where(inArray(storeOrderCartInfo.oid,[record.selectedOrderId,...(record.remainingOrderId?[record.remainingOrderId]:[])])).orderBy(asc(storeOrderCartInfo.id)).limit(201);let successor:typeof storeOrderRefundSplit.$inferSelect|undefined,successorRefund:FinancialRefund|undefined;
 if(record.remainingOrderId){const next=await tx.select().from(storeOrderRefundSplit).where(and(eq(storeOrderRefundSplit.previousRefundId,refund.id),eq(storeOrderRefundSplit.sourceOrderId,record.remainingOrderId))).limit(2);requireFact(next.length<=1);if(next.length){successor=next[0];requireFact(successor.refundId>refund.id&&successor.paymentOrderId===record.paymentOrderId&&successor.uid===refund.uid&&successor.storeId===refund.storeId&&successor.supplierId===refund.supplierId);successorRefund=(await tx.select().from(storeOrderRefund).where(eq(storeOrderRefund.id,successor.refundId)).limit(1))[0];requireFact(!!successorRefund);await verifyFinancialMaterializedRefund(tx,successorRefund!,visited);const archive=snapshot(successor.sourceSnapshot);requireFact(archive.source.id===record.remainingOrderId&&archive.source.payPrice===plan!.remaining.payPrice&&archive.source.totalNum===plan!.remaining.totalNum);actual=[...actual.filter(x=>x.oid===record.selectedOrderId),...archive.carts];}}
 const expectedHeld=new Map<number,number>();if(record.remainingOrderId){let holds=successorRefund?[successorRefund]:await tx.select().from(storeOrderRefund).where(and(eq(storeOrderRefund.storeOrderId,record.remainingOrderId),eq(storeOrderRefund.isCancel,0),eq(storeOrderRefund.isDel,0),inArray(storeOrderRefund.refundType,[0,1,2,4,5,6]))).orderBy(asc(storeOrderRefund.id)).limit(202);requireFact(holds.length<=201);if(!successorRefund)holds=await currentGenerationRefunds(holds,await loadRefundOrderGeneration(tx,remaining!,actual.filter(x=>x.oid===record.remainingOrderId)));for(const heldRefund of holds){const held=readRefundQuantityReservation(heldRefund);requireFact(!!held);for(const item of held!.items){const row=actual.find(x=>x.id===item.rowId&&x.oid===record.remainingOrderId),previous=expectedHeld.get(item.rowId)??0;requireFact(!!row&&row.cartId===refundClaimCartKey(item)&&item.totalNum===row.cartNum&&item.beforeRefundNum===previous);expectedHeld.set(item.rowId,previous+item.cartNum);}}}
 requireFact(actual.length<=200&&actual.every(x=>x.uid===refund.uid)&&actual.length===partitions.reduce((sum,x)=>sum+Number(x.selectedRowId!==null)+Number(x.remainingRowId!==null),0));
 for(const part of partitions){
  const original=source.carts.find(x=>x.id===part.sourceRowId);requireFact(!!original&&part.sourceCartId===original.cartId);
  const count=selections.get(original!.cartId)??0,selectedCart=actual.find(x=>x.id===part.selectedRowId),remainingCart=actual.find(x=>x.id===part.remainingRowId),planned=plan!.carts.get(original!.cartId);requireFact(!!planned&&part.selectedNum===count&&part.remainingNum===original!.cartNum-count);
  if(count){
   requireFact(!!selectedCart&&selectedCart.oid===record.selectedOrderId&&selectedCart.productId===original!.productId&&selectedCart.skuUnique===original!.skuUnique&&selectedCart.cartNum===count&&selectedCart.refundNum===(record.disposition==='whole'?0:count)&&selectedCart.splitStatus===2&&selectedCart.splitSurplusNum===0);
   if(record.disposition==='whole')requireFact(selectedCart!.id===original!.id&&selectedCart!.cartInfo===original!.cartInfo&&selectedCart!.writeTimes===original!.writeTimes&&selectedCart!.writeSurplusTimes===original!.writeSurplusTimes);
   else{const expected={...object(json(planned!.selected!,65536)),id:selectedCart!.cartId,financial_version:'refund-order-line-finance-v1',refund_order_generation:{refundId:refund.id,role:'selected'}};requireFact(await outRequestHash(object(json(selectedCart!.cartInfo!,65536)))===await outRequestHash(expected)&&selectedCart!.writeTimes===planned!.selectedWriteoff!.writeTimes&&selectedCart!.writeSurplusTimes===planned!.selectedWriteoff!.writeSurplusTimes);}
  }else requireFact(part.selectedRowId===null);
  if(original!.cartNum>count){
   requireFact(!!remainingCart&&remainingCart.oid===record.remainingOrderId&&remainingCart.productId===original!.productId&&remainingCart.skuUnique===original!.skuUnique&&remainingCart.cartNum===original!.cartNum-count&&remainingCart.refundNum===(expectedHeld.get(remainingCart.id)??0));
   const expected={...object(json(planned!.remaining!,65536)),id:remainingCart!.cartId,financial_version:'refund-order-line-finance-v1',refund_order_generation:{refundId:refund.id,role:'remaining'}};requireFact(await outRequestHash(object(json(remainingCart!.cartInfo!,65536)))===await outRequestHash(expected)&&remainingCart!.writeTimes===planned!.remainingWriteoff!.writeTimes&&remainingCart!.writeSurplusTimes===planned!.remainingWriteoff!.writeSurplusTimes);
  }else requireFact(part.remainingRowId===null);
 }
 const allocationRaw=json(record.invoiceAllocation,16384);if(allocationRaw!==null){const allocation=object(allocationRaw),original=object(allocation.original),chosen=object(allocation.selected),retained=allocation.remaining===null?null:object(allocation.remaining);requireFact(allocation.version==='refund-invoice-allocation-v1'&&allocation.sourceOrderId===record.sourceOrderId&&allocation.paymentOrderId===record.paymentOrderId&&chosen.orderId===record.selectedOrderId&&chosen.amount===plan!.selected.payPrice&&original.uid===refund.uid&&original.invoiceAmount===source.source.payPrice);const invoices=await tx.select().from(storeOrderInvoice).where(inArray(storeOrderInvoice.id,[Number(original.id),Number(chosen.invoiceId),...(retained?[Number(retained.invoiceId)]:[])])).limit(3);const invoice=invoices.find(x=>x.id===chosen.invoiceId);requireFact(!!invoice&&invoice.orderId===record.selectedOrderId&&invoice.uid===refund.uid&&invoice.isRefund===1&&invoice.isPay===1&&invoice.isDel===0&&invoice.invoiceAmount===chosen.amount);if(retained){requireFact(retained.orderId===record.remainingOrderId&&retained.amount===plan!.remaining.payPrice);if(successor){const nextAllocation=object(json(successor.invoiceAllocation,16384)),nextOriginal=object(nextAllocation.original);requireFact(nextAllocation.version==='refund-invoice-allocation-v1'&&nextAllocation.sourceOrderId===record.remainingOrderId&&nextAllocation.paymentOrderId===record.paymentOrderId&&nextOriginal.id===retained.invoiceId&&nextOriginal.orderId===retained.orderId&&nextOriginal.uid===refund.uid&&nextOriginal.invoiceAmount===retained.amount&&nextOriginal.isRefund===0&&nextOriginal.isPay===1&&nextOriginal.isDel===0);}else{const actualInvoice=invoices.find(x=>x.id===retained.invoiceId);requireFact(!!actualInvoice&&actualInvoice.orderId===record.remainingOrderId&&actualInvoice.uid===refund.uid&&actualInvoice.isRefund===0&&actualInvoice.isPay===1&&actualInvoice.isDel===0&&actualInvoice.invoiceAmount===retained.amount);}}}
 const frozenPayment=object(source.payment);requireFact(Object.keys(frozenPayment).sort().join(',')==='id,orderId,payPrice,payType,tradeNo'&&payment!.id===frozenPayment.id&&payment!.uid===refund.uid&&payment!.paid===1&&payment!.payType===source.source.payType&&selected!.payType===payment!.payType&&['orderId','tradeNo','payPrice','payType'].every(key=>(payment! as unknown as Record<string,unknown>)[key]===frozenPayment[key]));
 const points=planCompletedRefundLineCompensation(source.source,source.carts,[refund]);requireFact(!!points&&amountToCents(source.source.backIntegral)===points!.usedIntegral*100);
 let previousScope=readRefundEarnedIncomeScope(null),priorIds:number[]=[];
 if(record.previousRefundId){const prior=await tx.select().from(storeOrderRefundSplit).where(eq(storeOrderRefundSplit.refundId,record.previousRefundId)).limit(2);requireFact(prior.length===1&&prior[0].remainingOrderId===record.sourceOrderId&&prior[0].paymentOrderId===record.paymentOrderId&&prior[0].uid===refund.uid&&prior[0].storeId===refund.storeId&&prior[0].supplierId===refund.supplierId);const previousRefund=(await tx.select().from(storeOrderRefund).where(eq(storeOrderRefund.id,record.previousRefundId)).limit(1))[0];requireFact(!!previousRefund&&previousRefund.refundType===6&&await refundOrderSplitFingerprint(previousRefund)===prior[0].fingerprint);priorIds=pointIds(prior[0].returnedPointBillIds);previousScope=readRefundEarnedIncomeScope(json(prior[0].earnedIncomeScope,2048));}
 requireFact(await outRequestHash(readRefundEarnedIncomeScope(json(record.earnedIncomeScope,2048)))===await outRequestHash(captureRefundEarnedIncomeScope(source.source,refund.id,previousScope)));
 const billIds=pointIds(record.returnedPointBillIds),priorSet=new Set(priorIds);requireFact(priorIds.every(id=>billIds.includes(id)));const bills=billIds.length?await tx.select().from(userBill).where(inArray(userBill.id,billIds)).limit(1025):[];requireFact(bills.length===billIds.length&&bills.every(x=>x.uid===refund.uid&&x.category==='integral'&&x.pm===1&&x.status===1&&['pay_product_integral_back','order_integral_refund'].includes(x.type)&&x.eventKey===x.type));
 const currentBills=bills.filter(x=>!priorSet.has(x.id));requireFact(currentBills.every(x=>[String(record.sourceOrderId),refund.orderId].includes(x.linkId)));const returned=(type:string)=>currentBills.filter(x=>x.type===type).reduce((sum,x)=>{requireFact(/^\d{1,10}(?:\.0{1,2})?$/.test(x.number));return sum+Number(x.number);},0);requireFact(returned('pay_product_integral_back')===points!.usedIntegral&&returned('order_integral_refund')===points!.payIntegral);
 if(payment!.payType==='yue'&&amountToCents(refund.refundPrice)!>0){const bills=await tx.select().from(userBill).where(and(eq(userBill.uid,refund.uid),eq(userBill.linkId,refund.orderId),eq(userBill.type,'pay_product_refund'))).limit(2);requireFact(bills.length===1&&bills[0].pm===1&&bills[0].number===refund.refundPrice);}
}

/** Modern reservation-v1 keeps the current physical generation. Legacy rows
 * without an exact modern plan remain unverified; no guessed v2 or repair. */
export async function verifyFinancialCompletedRefund(tx:DbClient,refund:FinancialRefund){
 const claim=readRefundQuantityReservation(refund);requireFact(!!claim&&refund.refundType===6&&refund.refundedPrice===refund.refundPrice&&!refund.isDel&&!refund.isCancel);
 const logs=await tx.select().from(storeOrderStatus).where(and(eq(storeOrderStatus.oid,refund.storeOrderId),eq(storeOrderStatus.changeType,'refund_price'))).limit(403);requireFact(logs.length<=402&&logs.some(x=>x.changeTime===refund.refundedTime&&x.changeMessage===`退款给用户：${refund.refundPrice}元`));
 if(isMaterializedRefundClaim(claim)){await verifyFinancialMaterializedRefund(tx,refund);return;}
 const order=(await tx.select().from(storeOrder).where(eq(storeOrder.id,refund.storeOrderId)).limit(1))[0];requireFact(!!order&&order.uid===refund.uid&&order.storeId===refund.storeId&&order.supplierId===refund.supplierId&&order.paid===1&&!order.isDel&&!order.isSystemDel&&order.pid>=0);
 const carts=await tx.select().from(storeOrderCartInfo).where(eq(storeOrderCartInfo.oid,refund.storeOrderId)).orderBy(asc(storeOrderCartInfo.id)).limit(101);requireFact(carts.length>0&&carts.length<=100);const generation=await loadRefundOrderGeneration(tx,order!,carts),history=await tx.select().from(storeOrderRefund).where(and(eq(storeOrderRefund.storeOrderId,refund.storeOrderId),eq(storeOrderRefund.isCancel,0),eq(storeOrderRefund.isDel,0))).orderBy(asc(storeOrderRefund.id)).limit(403);requireFact(history.length<=402);const allCurrent=await currentGenerationRefunds(history,generation),current=allCurrent.filter(x=>x.refundType===6),active=allCurrent.filter(x=>[0,1,2,4,5].includes(x.refundType)),plan=planCompletedRefundLineCompensation(order!,carts,current);requireFact(!!plan&&current.some(x=>x.id===refund.id)&&amountToCents(order!.backIntegral)===plan!.usedIntegral*100&&active.length<=1);
 const quantities=new Map<number,number>();for(const completed of current){const held=readRefundQuantityReservation(completed);requireFact(!!held);for(const item of held!.items)quantities.set(item.rowId,(quantities.get(item.rowId)??0)+item.cartNum);}for(const pending of active){requireFact(pending.uid===refund.uid&&pending.storeId===refund.storeId&&pending.supplierId===refund.supplierId);const held=readRefundQuantityReservation(pending);requireFact(!!held);for(const item of held!.items){const row=carts.find(x=>x.id===item.rowId);requireFact(!!row&&row.cartId===refundClaimCartKey(item)&&row.cartNum===item.totalNum&&item.beforeRefundNum===(quantities.get(item.rowId)??0));quantities.set(item.rowId,item.beforeRefundNum+item.cartNum);}}requireFact(carts.every(x=>x.refundNum===(quantities.get(x.id)??0)));
 let metadata=order!.refundType===6&&[2,3].includes(order!.refundStatus)||active.length===1&&order!.refundStatus===1&&order!.refundType===active[0].refundType;
 if(!metadata&&order!.refundType===3&&order!.refundStatus===0){const refused=allCurrent.filter(x=>x.refundType===3).at(-1);if(refused){const events=await tx.execute<{aggregate_id:number;payload:Record<string,unknown>}>(sql`SELECT aggregate_id,payload FROM public.store_order_outbox WHERE event_key=${'order.refund.refused.notice:'+refused.id} AND event_type='order.refund.refused.notice' LIMIT 2`);metadata=events.length===1&&events[0].aggregate_id===order!.id&&events[0].payload.orderId===order!.id&&events[0].payload.refundId===refused.id&&events[0].payload.userId===refund.uid;}}requireFact(metadata);
 const invoices=await tx.select().from(storeOrderInvoice).where(eq(storeOrderInvoice.orderId,order!.id)).limit(4);requireFact(invoices.length<=3&&invoices.every(x=>x.uid===refund.uid&&x.isRefund===1));
 const prior=new Set(generation?.returnedPointBillIds??[]),links=[String(order!.id),...current.map(x=>x.orderId)],bills=await tx.select().from(userBill).where(and(eq(userBill.uid,refund.uid),inArray(userBill.linkId,links))).limit(1025);requireFact(bills.length<=1024);const returned=(type:string)=>bills.filter(x=>!prior.has(x.id)&&x.type===type&&x.category==='integral'&&x.pm===1&&x.status===1).reduce((sum,x)=>{requireFact(/^\d+(?:\.0{1,2})?$/.test(x.number));return sum+Number(x.number);},0);requireFact(returned('pay_product_integral_back')===plan!.usedIntegral&&returned('order_integral_refund')===plan!.payIntegral);
 if(order!.payType==='yue'&&amountToCents(refund.refundPrice)!>0){const balance=bills.filter(x=>x.linkId===refund.orderId&&x.type==='pay_product_refund');requireFact(balance.length===1&&balance[0].number===refund.refundPrice&&balance[0].pm===1&&balance[0].category==='now_money'&&balance[0].status===1);}
 // SKU identity remains available for the mature stock path. Historical stock
 // deltas are verified only by the local before/after proof, never inferred.
 for(const item of claim!.items){const cart=carts.find(x=>x.id===item.rowId&&x.cartId===refundClaimCartKey(item));requireFact(!!cart);const snapshot=json(cart!.cartInfo??'{}',65536),id=Number(snapshot.sku?.id??0),skus=await tx.select().from(storeProductAttrValue).where(and(eq(storeProductAttrValue.productId,cart!.productId),eq(storeProductAttrValue.type,0),Number.isSafeInteger(id)&&id>0?eq(storeProductAttrValue.id,id):eq(storeProductAttrValue.unique,cart!.skuUnique))).limit(2);requireFact(skus.length===1);}
}
