import {and,asc,desc,eq,inArray,isNull,sql,type SQL} from 'drizzle-orm';
import {withTx,type Container,type DbClient} from '@/lib/di';
import type {Env} from '@/env';
import {user,userGroup,userLabel,userLabelRelation,userLevel,systemUserLevel,legacyCategory,storeCouponIssue,storeCouponUser,systemAttachment} from '@/models/schema';
import {outRequestHash} from '@/services/out/OutIdempotency';
import {customerUserOperationReadiness} from '@/migrations/runCustomerUserOperation';
import {publicProductPictures,renderProductPictures} from '@/services/activity/ProductAssetPolicy';
import {fabImage} from '@/services/admin/AdminFabSettingsInput';
import {parseCanonicalAttachmentId} from '@/services/system/AttachmentService';
import {AuthException,NotFoundException,ValidateException} from '@/utils/errors';
import {authorizeCustomerWorkActor,customerWorkId,type CustomerWorkActor} from './CustomerWorkScope';
import {freezeCustomerActor} from './CustomerWorkOperationRequest';

export const CUSTOMER_USER_READ_VERSION='customer-work-user-read-v1' as const;
export const CUSTOMER_USER_SCOPES={users:'global',groups:'global',levels:'global',labels:'platform',coupon_issues:'global_send',wallet:'exact_target_user',paid_order_count:'original_roots',paid_order_value:'physical_fulfillments'} as const;
export const CUSTOMER_USER_KINDS=['replace_level','replace_group','replace_labels','grant_coupons','adjust_membership','adjust_money','adjust_integral'] as const;
type User=typeof user.$inferSelect;type Issue=typeof storeCouponIssue.$inferSelect;
export interface CustomerUserState {account:User;levels:(typeof userLevel.$inferSelect)[];relations:(typeof userLabelRelation.$inferSelect)[];revision:string}
const hash64=/^[a-f0-9]{64}$/;
export function customerUserQuery(query:Record<string,string>,keys:readonly string[]){for(const key of Object.keys(query))if(key!=='scope_key'&&!keys.includes(key))throw new ValidateException(`用户工作台不支持查询参数：${key}`);if(query.scope_key!==undefined&&!hash64.test(query.scope_key))throw new ValidateException('用户管理身份指纹无效');}
function integer(value:string|undefined,fallback:number,min:number,max:number){if(value===undefined||value==='')return fallback;if(!/^(?:0|[1-9]\d*)$/.test(value)||!Number.isSafeInteger(Number(value))||Number(value)<min||Number(value)>max)throw new ValidateException('用户查询编号或分页无效');return Number(value);}
function text(value:string|undefined){const result=(value??'').trim();if(Array.from(result).length>100||/[\u0000-\u001f\u007f]/.test(result))throw new ValidateException('用户查询文本无效');return result;}
function labelsQuery(value:string|undefined){if(!value)return[];const parts=value.split(',');if(parts.length>100)throw new ValidateException('用户标签筛选超过100项');let previous=0;return parts.map(v=>{const id=integer(v,0,1,2147483647);if(id<=previous)throw new ValidateException('用户标签筛选须唯一排序');previous=id;return id;});}
function money(value:string){if(!/^-?(?:0|[1-9]\d{0,9})\.\d{2}$/.test(value))throw new ValidateException('历史金额格式无效');return value;}
function safeMoney(value:string){try{const result=money(value);return result.startsWith('-')?null:result;}catch{return null;}}
function aggregateMoney(value:string){if(!/^\d+(?:\.\d{1,2})?$/.test(value))throw new ValidateException('用户订单汇总金额无效');const [whole,fraction='']=value.split('.');return whole+'.'+fraction.padEnd(2,'0');}
function epoch(value:number){if(!Number.isSafeInteger(value)||value<0||value>2147483647)throw new ValidateException('用户历史时间无效');return value;}
function birthdayEpoch(value:number){if(!Number.isSafeInteger(value)||value< -2147483648||value>2147483647)throw new ValidateException('用户生日无效');return value;}
function birthday(value:number){return value?new Date((birthdayEpoch(value)+28800)*1000).toISOString().slice(0,10):'';}
function date(value:number,time=false){return value?new Date((epoch(value)+28800)*1000).toISOString().slice(0,time?19:10).replace('T',' '):'';}
function iso(value:Date|null){return value?.toISOString()??null;}
async function fingerprint(db:DbClient,tables:readonly string[]){const parts=tables.map(table=>sql.raw(`SELECT '${table}' AS kind,md5((to_jsonb(t)||jsonb_build_object('_xmin',t.xmin::text))::text) AS h FROM public."${table}" t`));const[row]=await db.execute<{value:unknown}>(sql`WITH facts AS(${sql.join(parts,sql` UNION ALL `)}),digests AS(SELECT kind,count(*)::text AS n,COALESCE(sum(('x'||substr(h,1,15))::bit(60)::bigint),0)::text AS a,COALESCE(sum(('x'||substr(h,17,15))::bit(60)::bigint),0)::text AS b,COALESCE(bit_xor(('x'||substr(h,1,16))::bit(64)::bigint),0)::text AS x FROM facts GROUP BY kind)SELECT COALESCE(jsonb_agg(jsonb_build_array(kind,n,a,b,x) ORDER BY kind),'[]'::jsonb) AS value FROM digests`);return outRequestHash({version:'customer-user-facts-v1',facts:row?.value});}
export function customerUserCatalogRevision(db:DbClient){return fingerprint(db,['user_group','user_label','system_user_level','category']);}
export async function readCustomerUserState(db:DbClient,uid:number):Promise<CustomerUserState>{const[account]=await db.select().from(user).where(eq(user.uid,uid)).limit(1);if(!account)throw new NotFoundException('用户不存在');const[levels,relations]=await Promise.all([db.select().from(userLevel).where(eq(userLevel.uid,uid)).orderBy(asc(userLevel.id)),db.select().from(userLabelRelation).where(eq(userLabelRelation.uid,uid)).orderBy(asc(userLabelRelation.id))]);const[versions]=await db.execute<{value:unknown}>(sql`SELECT jsonb_build_object('account',(SELECT xmin::text FROM "user" WHERE uid=${uid}),'levels',(SELECT COALESCE(jsonb_agg(jsonb_build_array(id,xmin::text) ORDER BY id),'[]'::jsonb) FROM user_level WHERE uid=${uid}),'relations',(SELECT COALESCE(jsonb_agg(jsonb_build_array(id,xmin::text) ORDER BY id),'[]'::jsonb) FROM user_label_relation WHERE uid=${uid})) AS value`);return{account,levels,relations,revision:await outRequestHash({version:'customer-user-revision-v1',account:JSON.parse(JSON.stringify(account)),levels,relations,versions:versions?.value})};}
export async function customerUserIssueRevision(db:DbClient,id:number){const[row]=await db.execute<{value:unknown}>(sql`SELECT to_jsonb(t)||jsonb_build_object('_xmin',t.xmin::text) AS value FROM store_coupon_issue t WHERE id=${id}`);if(!row)throw new NotFoundException('赠送优惠券不存在');return outRequestHash({version:'customer-user-issue-v1',value:row.value});}
export function customerUserIssueReason(issue:Issue,now:Date){if(issue.isDel||issue.status!==1||issue.receiveType!==3)return'coupon_issue_unavailable';if(![1,2].includes(issue.type)||![0,1,2,3].includes(issue.couponType)||![0,1].includes(issue.isPermanent)||issue.totalCount<0||issue.remainCount<0||issue.receiveLimit<0||issue.day<0||!safeMoney(issue.couponPrice)||!safeMoney(issue.useMinPrice))return'coupon_issue_invalid';if(issue.type===2&&(Number(issue.couponPrice)<=0||Number(issue.couponPrice)>100))return'coupon_discount_invalid';if(Boolean(issue.startTime)!==Boolean(issue.endTime)||issue.startTime&&issue.endTime&&issue.startTime>issue.endTime)return'coupon_issue_window_invalid';if(issue.startTime&&issue.startTime>now)return'coupon_issue_not_started';if(issue.endTime&&issue.endTime<now)return'coupon_issue_ended';if(!issue.isPermanent&&issue.remainCount===0)return'coupon_issue_empty';const title=issue.couponTitle||issue.title;if(!title||Array.from(title).length>64||/[\u0000-\u001f\u007f]/.test(title))return'coupon_title_invalid';if(issue.day===0&&(!issue.useEndTime||issue.useEndTime<now||issue.useStartTime&&issue.useStartTime>issue.useEndTime))return'coupon_use_window_invalid';if(issue.day>0&&!Number.isFinite(new Date(now.getTime()+issue.day*86400000).getTime()))return'coupon_use_window_invalid';return'';}
async function avatar(db:DbClient,uid:number,value:string){let ref='';try{ref=value?fabImage(value):'';}catch{}const id=parseCanonicalAttachmentId(ref);if(id!==null){const[a]=await db.select().from(systemAttachment).where(eq(systemAttachment.attId,id)).limit(1);if(a?.type===3&&a.relationId===uid&&a.moduleType===3&&a.fileType===1&&a.imageType===8&&a.attDir===ref&&a.name.startsWith(`attachments/user/${uid}/`)&&!/[\\\u0000-\u001f\u007f]/.test(a.name)&&!a.name.split('/').some(v=>v==='.'||v==='..')&&/\.(?:jpe?g|png|gif|webp)$/i.test(a.name)&&/^image\/(?:jpeg|jpg|png|gif|webp)$/i.test(a.attType.trim()))return ref;}
 return(await publicProductPictures(db,[{image:ref,type:0,relationId:0}]))[0];}

export class CustomerWorkUserReadService {
 constructor(readonly container:Container,readonly env:Env){}
 private async snapshot<T extends object>(value:CustomerWorkActor,query:Record<string,string>,read:(db:DbClient,ready:boolean,now:number)=>Promise<T>){const actor=freezeCustomerActor(value),result=await withTx(this.container,async db=>{await db.execute(sql`SET TRANSACTION ISOLATION LEVEL REPEATABLE READ, READ ONLY`);await db.execute(sql`SELECT set_config('statement_timeout',LEAST(NULLIF((SELECT setting::bigint FROM pg_settings WHERE name='statement_timeout'),0),8000)::text||'ms',true)`);const scope=await authorizeCustomerWorkActor(db,actor);if(query.scope_key!==undefined&&query.scope_key!==scope.scope_key)throw new AuthException('用户管理身份已变化，请重新读取');const readiness=await customerUserOperationReadiness(db),at_time=Math.floor(Date.now()/1000),data=await read(db,readiness.ready,at_time),catalog_revision=await customerUserCatalogRevision(db),digest=await fingerprint(db,['user','user_group','user_label','user_label_relation','user_level','system_user_level','category','store_coupon_issue','store_coupon_user','store_coupon_issue_user','store_order','system_attachment']);return{version:CUSTOMER_USER_READ_VERSION,actor_uid:actor.uid,principal:{kind:'customer-order-manager' as const,service_id:scope.service_id,scope:'global' as const},scope_key:scope.scope_key,consistency_key:await outRequestHash({version:CUSTOMER_USER_READ_VERSION,scope_key:scope.scope_key,digest,readiness:readiness.ready}),data:{...data,scopes:CUSTOMER_USER_SCOPES,catalog_revision,readiness:{writes:readiness.ready,reason:readiness.reason},at_time}};});const fresh=await authorizeCustomerWorkActor(this.container.db,actor);if(fresh.scope_key!==result.scope_key)throw new AuthException('用户管理身份已变化，请重新读取');return result;}
 private async projection(db:DbClient,state:CustomerUserState,ready:boolean,now:number){const p=state.account;if(![0,1].includes(p.status)||![0,1].includes(p.isDel)||![0,1].includes(p.levelStatus)||![0,1].includes(p.isEverLevel)||![0,1,2,3].includes(p.isMoneyLevel)||[p.groupId,p.level].some(n=>!Number.isSafeInteger(n)||n<0))throw new ValidateException('用户历史身份字段无效');const[group]=await db.select().from(userGroup).where(eq(userGroup.id,p.groupId)).limit(1),[level]=await db.select().from(systemUserLevel).where(eq(systemUserLevel.id,p.level)).limit(1),relationIds=[...new Set(state.relations.filter(r=>r.type===0&&r.relationId===0).map(r=>r.labelId))].sort((a,b)=>a-b),labels: (typeof userLabel.$inferSelect)[]=[];for(let offset=0;offset<relationIds.length;offset+=10000)labels.push(...await db.select().from(userLabel).where(and(inArray(userLabel.id,relationIds.slice(offset,offset+10000)),eq(userLabel.type,0),eq(userLabel.relationId,0))).orderBy(asc(userLabel.id)));labels.sort((a,b)=>a.id-b.id);
  const now_money=safeMoney(p.nowMoney),integral=Number.isSafeInteger(p.integral)&&p.integral>=0?p.integral:null,financial_diagnostics=[...(now_money===null?['money_invalid']:[]),...(integral===null?['integral_invalid']:[])],deleted=Boolean(p.isDel||p.deleteTime),overdue_time=epoch(p.overdueTime),permanent=p.isEverLevel===1,membership_active=p.isMoneyLevel>0&&(permanent||overdue_time>now),validLevel=state.levels.find(l=>l.levelId===p.level&&l.status===1&&l.isDel===0&&(l.isForever===1||l.validTime>now));
  const baseReason=deleted?'user_deleted':!ready?'user_management_not_ready':'',actions=Object.fromEntries(CUSTOMER_USER_KINDS.map(kind=>{const reason=baseReason||(kind==='adjust_membership'&&permanent?'permanent_membership':kind==='adjust_money'&&now_money===null?'money_invalid':kind==='adjust_integral'&&integral===null?'integral_invalid':'');return[kind,{available:!reason,reason}];}));
  return{uid:p.uid,nickname:p.nickname,avatar:(await renderProductPictures(this.env.APP_KEY,[await avatar(db,p.uid,p.avatar)]))[0],phone:p.phone,status:p.status as 0|1,deleted,group_id:p.groupId,group_name:group?.groupName??'',level:p.level,level_name:level?.name??'',level_status:p.levelStatus as 0|1,level_grade:validLevel?.grade??null,labels:labels.map(l=>({id:l.id,label_name:l.name,color:l.color})),now_money,integral,financial_diagnostics,isMember:(p.isMoneyLevel>0?1:0) as 0|1,is_money_level:p.isMoneyLevel as 0|1|2|3,is_ever_level:p.isEverLevel as 0|1,overdue_time,membership_active,svip_over_day:permanent?null:membership_active?Math.ceil((overdue_time-now)/86400):0,svip_overdue_time:permanent?'':date(overdue_time),user_revision:state.revision,actions};
 }
 async list(actor:CustomerWorkActor,query:Record<string,string>={}){customerUserQuery(query,['page','limit','nickname','keyword','uid','phone','status','group_id','level','label_ids','label_id','isMember']);if(query.nickname!==undefined&&query.keyword!==undefined||query.label_ids!==undefined&&query.label_id!==undefined)throw new ValidateException('用户查询别名不能同时出现');const page=integer(query.page,1,1,1000000),limit=integer(query.limit,20,1,100),nickname=text(query.nickname??query.keyword),phone=text(query.phone),uid=text(query.uid),group=integer(query.group_id,0,0,2147483647),level=integer(query.level,0,0,2147483647),labels=labelsQuery(query.label_ids??query.label_id);if(!['',undefined,'0','1'].includes(query.status)||!['',undefined,'0','1'].includes(query.isMember))throw new ValidateException('用户状态筛选无效');return this.snapshot(actor,query,async(db,ready,now)=>{const filters:SQL[]=[eq(user.isDel,0),isNull(user.deleteTime)];const pattern=(s:string)=>`%${s.replace(/[\\%_]/g,'\\$&')}%`;if(nickname)filters.push(sql`(${user.nickname} LIKE ${pattern(nickname)} ESCAPE '\\' OR ${user.uid}::text LIKE ${pattern(nickname)} ESCAPE '\\' OR ${user.phone} LIKE ${pattern(nickname)} ESCAPE '\\')`);if(phone)filters.push(sql`${user.phone} LIKE ${pattern(phone)} ESCAPE '\\'`);if(uid)filters.push(sql`${user.uid}::text LIKE ${pattern(uid)} ESCAPE '\\'`);if(group)filters.push(eq(user.groupId,group));if(level)filters.push(eq(user.level,level));if(query.status)filters.push(eq(user.status,Number(query.status)));if(query.isMember==='1')filters.push(sql`${user.isMoneyLevel}>0`);if(query.isMember==='0')filters.push(eq(user.isMoneyLevel,0));if(labels.length)filters.push(sql`EXISTS(SELECT 1 FROM user_label_relation r WHERE r.uid=${user.uid} AND r.type=0 AND r.relation_id=0 AND r.label_id IN(${sql.join(labels.map(id=>sql`${id}`),sql`, `)}))`);const where=and(...filters),[rows,[count]]=await Promise.all([db.select({uid:user.uid}).from(user).where(where).orderBy(desc(user.uid)).limit(limit).offset((page-1)*limit),db.select({count:sql<number>`count(*)::int`}).from(user).where(where)]),list=[];for(const row of rows)list.push(await this.projection(db,await readCustomerUserState(db,row.uid),ready,now));return{list,count:count.count,page,limit,has_more:(page-1)*limit+list.length<count.count};});}
 async detail(actor:CustomerWorkActor,uidValue:unknown,query:Record<string,string>={}){customerUserQuery(query,[]);const uid=customerWorkId(uidValue,'用户');return this.snapshot(actor,query,async(db,ready,now)=>{const state=await readCustomerUserState(db,uid),p=state.account,base=await this.projection(db,state,ready,now),[facts]=await db.execute<{count:number;price:string;coupons:number}>(sql`SELECT (SELECT count(*)::int FROM store_order WHERE uid=${uid} AND paid=1 AND pid IN(0,-1) AND is_del=0 AND is_system_del=0) AS count,(SELECT COALESCE(sum(pay_price),0)::text FROM store_order WHERE uid=${uid} AND paid=1 AND pid>=0 AND refund_status IN(0,3) AND is_del=0 AND is_system_del=0) AS price,(SELECT count(*)::int FROM store_coupon_user WHERE uid=${uid} AND status=0 AND is_fail=0 AND (end_time IS NULL OR end_time>=(to_timestamp(${now}) AT TIME ZONE 'UTC'))) AS coupons`);return{user:{...base,real_name:p.realName,birthday:birthday(p.birthday),birthday_epoch:birthdayEpoch(p.birthday),card_id:p.cardId,addres:p.addres,add_time:epoch(p.addTime),_add_time:date(p.addTime,true),order_total_count:facts.count,order_total_price:aggregateMoney(facts.price),coupon_num:facts.coupons}};});}
 async groups(actor:CustomerWorkActor,query:Record<string,string>={}){customerUserQuery(query,[]);return this.snapshot(actor,query,async db=>{const rows=await db.select().from(userGroup).orderBy(desc(userGroup.id));return{list:rows.map(r=>({id:r.id,group_name:r.groupName})),count:rows.length};});}
 async levels(actor:CustomerWorkActor,query:Record<string,string>={}){customerUserQuery(query,[]);return this.snapshot(actor,query,async db=>{const rows=await db.select().from(systemUserLevel).where(and(eq(systemUserLevel.isShow,1),eq(systemUserLevel.isDel,0))).orderBy(asc(systemUserLevel.grade),asc(systemUserLevel.id)),refs:string[]=[];for(let offset=0;offset<rows.length;offset+=5000)refs.push(...await publicProductPictures(db,rows.slice(offset,offset+5000).flatMap(r=>[{image:r.image,type:0,relationId:0},{image:r.icon,type:0,relationId:0}])));const rendered=await renderProductPictures(this.env.APP_KEY,refs);return{list:rows.map((r,i)=>({id:r.id,name:r.name,grade:r.grade,image:rendered[i*2],icon:rendered[i*2+1]})),count:rows.length};});}
 async labels(actor:CustomerWorkActor,query:Record<string,string>={}){customerUserQuery(query,['uid']);const uid=integer(query.uid,0,0,2147483647);return this.snapshot(actor,query,async db=>{if(uid)await readCustomerUserState(db,uid);const[groups,labels,relations]=await Promise.all([db.select().from(legacyCategory).where(and(eq(legacyCategory.ownerId,0),eq(legacyCategory.type,0),eq(legacyCategory.relationId,0),eq(legacyCategory.group,0),eq(legacyCategory.isShow,1))).orderBy(desc(legacyCategory.sort),asc(legacyCategory.id)),db.select().from(userLabel).where(and(eq(userLabel.type,0),eq(userLabel.relationId,0),eq(userLabel.status,1))).orderBy(desc(userLabel.sort),asc(userLabel.id)),uid?db.select().from(userLabelRelation).where(and(eq(userLabelRelation.uid,uid),eq(userLabelRelation.type,0),eq(userLabelRelation.relationId,0))):Promise.resolve([])]),selected=new Set(relations.map(r=>r.labelId)),list=groups.map(g=>({id:g.id,name:g.name,sort:g.sort,label:labels.filter(l=>l.labelCate===g.id).map(l=>({id:l.id,label_name:l.name,color:l.color,label_cate:l.labelCate,selected:selected.has(l.id)}))})).filter(g=>g.label.length);return{uid,list,count:list.length};});}
 async couponGrants(actor:CustomerWorkActor,query:Record<string,string>={}){customerUserQuery(query,['page','limit','coupon_title']);const page=integer(query.page,1,1,1000000),limit=integer(query.limit,20,1,100),title=text(query.coupon_title);return this.snapshot(actor,query,async(db,ready,now)=>{const filters:SQL[]=[eq(storeCouponIssue.receiveType,3),eq(storeCouponIssue.status,1),eq(storeCouponIssue.isDel,0),inArray(storeCouponIssue.isPermanent,[0,1]),sql`${storeCouponIssue.day}>=0 AND ${storeCouponIssue.totalCount}>=0 AND ${storeCouponIssue.remainCount}>=0 AND ${storeCouponIssue.receiveLimit}>=0`,inArray(storeCouponIssue.type,[1,2]),inArray(storeCouponIssue.couponType,[0,1,2,3]),sql`(${storeCouponIssue.isPermanent}=1 OR ${storeCouponIssue.remainCount}>0)`,sql`(${storeCouponIssue.startTime} IS NULL OR ${storeCouponIssue.startTime}<=(to_timestamp(${now}) AT TIME ZONE 'UTC'))`,sql`(${storeCouponIssue.endTime} IS NULL OR ${storeCouponIssue.endTime}>=(to_timestamp(${now}) AT TIME ZONE 'UTC'))`,sql`(${storeCouponIssue.day}>0 OR ${storeCouponIssue.useEndTime}>=(to_timestamp(${now}) AT TIME ZONE 'UTC'))`];if(title)filters.push(sql`${storeCouponIssue.couponTitle} LIKE ${`%${title.replace(/[\\%_]/g,'\\$&')}%`} ESCAPE '\\'`);const where=and(...filters),[rows,[count]]=await Promise.all([db.select().from(storeCouponIssue).where(where).orderBy(desc(storeCouponIssue.id)).limit(limit).offset((page-1)*limit),db.select({count:sql<number>`count(*)::int`}).from(storeCouponIssue).where(where)]),list=[];for(const r of rows){const reason=customerUserIssueReason(r,new Date(now*1000))||(!ready?'user_management_not_ready':'');list.push({id:r.id,cid:r.cid,coupon_title:r.couponTitle||r.title,type:r.type as 1|2,coupon_type:r.couponType as 0|1|2|3,coupon_price:money(r.couponPrice),use_min_price:money(r.useMinPrice),total_count:r.totalCount,remain_count:r.remainCount,is_permanent:r.isPermanent as 0|1,receive_limit:r.receiveLimit,receive_type:3 as const,day:r.day,start_time:iso(r.startTime),end_time:iso(r.endTime),use_start_time:iso(r.useStartTime),use_end_time:iso(r.useEndTime),coupon_time:r.day>0?`${r.day}天`:r.useEndTime?.toISOString()??'',issue_revision:await customerUserIssueRevision(db,r.id),action:{available:!reason,reason}});}return{list,count:count.count,page,limit,has_more:(page-1)*limit+list.length<count.count};});}
 async coupons(actor:CustomerWorkActor,uidValue:unknown,query:Record<string,string>={}){customerUserQuery(query,['page','limit']);const uid=customerWorkId(uidValue,'用户'),page=integer(query.page,1,1,1000000),limit=integer(query.limit,20,1,100);return this.snapshot(actor,query,async(db,_ready,now)=>{await readCustomerUserState(db,uid);const where=and(eq(storeCouponUser.uid,uid),eq(storeCouponUser.status,0),inArray(storeCouponUser.isFail,[0,1]),inArray(storeCouponUser.type,[1,2])),[rows,[count]]=await Promise.all([db.select({coupon:storeCouponUser,issue:storeCouponIssue}).from(storeCouponUser).leftJoin(storeCouponIssue,eq(storeCouponIssue.id,storeCouponUser.issueCouponId)).where(where).orderBy(desc(storeCouponUser.id)).limit(limit).offset((page-1)*limit),db.select({count:sql<number>`count(*)::int`}).from(storeCouponUser).where(where)]);return{uid,list:rows.map(({coupon:r,issue})=>{const availability=r.isFail||!safeMoney(r.couponPrice)||!safeMoney(r.useMinPrice)||Boolean(r.startTime)!==Boolean(r.endTime)||r.startTime&&r.endTime&&r.startTime>r.endTime?'invalid':r.endTime&&r.endTime.getTime()<now*1000?'expired':r.startTime&&r.startTime.getTime()>now*1000?'future':'available';return{id:r.id,uid:r.uid,issue_coupon_id:r.issueCouponId,template_id:issue?.cid??null,coupon_title:r.couponTitle,coupon_price:money(r.couponPrice),use_min_price:money(r.useMinPrice),status:0 as const,is_fail:r.isFail as 0|1,type:r.type as 1|2,coupon_type:issue&&[0,1,2,3].includes(issue.couponType)?issue.couponType as 0|1|2|3:null,receive_source:r.receiveSource,receive_time:epoch(r.receiveTime),start_time:iso(r.startTime),end_time:iso(r.endTime),use_time:iso(r.useTime),availability,availability_message:availability==='available'?'':'coupon_'+availability};}),count:count.count,page,limit,has_more:(page-1)*limit+rows.length<count.count};});}
}
