import {and,asc,eq,inArray,isNull,sql} from 'drizzle-orm';
import {withTx,type Container,type DbClient} from '@/lib/di';
import {user,userLevel,storeCouponIssue} from '@/models/schema';
import {normalizeOutRequestKey,outRequestHash} from '@/services/out/OutIdempotency';
import {assertCustomerUserOperationCatalog,customerUserOperationReadiness} from '@/migrations/runCustomerUserOperation';
import {acquireCustomerUserCatalogLock} from '@/migrations/runCustomerUserCatalogLock';
import {acquireCustomerWorkScopeLock} from '@/migrations/runCustomerWorkScopeLock';
import {AuthException,HttpApiException,NotFoundException,ValidateException} from '@/utils/errors';
import {authorizeCustomerWorkActor,customerWorkId,type CustomerWorkActor,type CustomerWorkScope} from './CustomerWorkScope';
import {authorizeCustomerOperationOwner,freezeCustomerActor,freezeCustomerJson,type CustomerJson} from './CustomerWorkOperationRequest';
import {CUSTOMER_USER_KINDS,customerUserCatalogRevision,customerUserIssueRevision,readCustomerUserState,type CustomerUserState} from './CustomerWorkUserReadService';

export const CUSTOMER_USER_OPERATION_VERSION='customer-work-user-operation-v1' as const;
export type CustomerUserOperationKind=typeof CUSTOMER_USER_KINDS[number];
export type CustomerUserOperationOutcome='users-updated'|'coupons-granted'|'membership-adjusted'|'finance-adjusted'|'rollback-rejected'|'abandoned';
export interface CustomerUserOperationBody {readonly version:typeof CUSTOMER_USER_OPERATION_VERSION;readonly scope_key:string;readonly targets:readonly{readonly uid:number;readonly expected_user_revision:string}[];readonly expected_catalog_revision:string;readonly payload:CustomerJson}
export interface CustomerUserOperationContext {actor:CustomerWorkActor;request_key:string}
export interface PreparedCustomerUserOperation {readonly actor:CustomerWorkActor;readonly key:string;readonly hash:string;readonly kind:CustomerUserOperationKind;readonly input:CustomerUserOperationBody}
export interface CustomerUserOperationReceipt {version:typeof CUSTOMER_USER_OPERATION_VERSION;actor_uid:number;service_id:number;request_key:string;request_hash:string;kind:CustomerUserOperationKind;user_ids:number[];outcome:CustomerUserOperationOutcome;evidence:Record<string,CustomerJson>}
export interface CustomerUserOperationResult {receipt:CustomerUserOperationReceipt;replayed:boolean}
export function customerUserExactKeys(value:unknown,keys:readonly string[]):asserts value is Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).sort().join(',')!==[...keys].sort().join(','))throw new ValidateException('用户操作字段不符合合同');}
export function customerUserPayload(kind:CustomerUserOperationKind,value:unknown){const raw=value as Record<string,unknown>;if(!raw||typeof raw!=='object')throw new ValidateException('用户操作内容无效');const p=raw.payload;const keys=kind==='replace_level'?['level_id']:kind==='replace_group'?['group_id']:kind==='replace_labels'?['label_ids']:kind==='grant_coupons'?['issue_id','expected_issue_revision']:kind==='adjust_membership'?['direction','days']:['direction','amount'];customerUserExactKeys(p,keys);const positive=(n:unknown)=>{if(typeof n!=='number')throw new ValidateException('用户操作编号须为整数');return customerWorkId(n,'用户操作');};
 if(kind==='replace_level')positive(p.level_id);else if(kind==='replace_group')positive(p.group_id);else if(kind==='replace_labels'){if(!Array.isArray(p.label_ids)||p.label_ids.length>100)throw new ValidateException('用户标签超过100项');let previous=0;for(const n of p.label_ids){const id=positive(n);if(id<=previous)throw new ValidateException('用户标签须唯一排序');previous=id;}}
 else if(kind==='grant_coupons'){positive(p.issue_id);if(typeof p.expected_issue_revision!=='string'||!/^[a-f0-9]{64}$/.test(p.expected_issue_revision))throw new ValidateException('赠券版本无效');}
 else{if(p.direction!=='add'&&p.direction!=='subtract')throw new ValidateException('用户调整方向无效');if(kind==='adjust_membership'){if(typeof p.days!=='number'||!Number.isSafeInteger(p.days)||p.days<1||p.days>999999)throw new ValidateException('会员天数无效');}else if(kind==='adjust_money'){if(typeof p.amount!=='string'||!/^(?:0|[1-9]\d{0,9})\.\d{2}$/.test(p.amount)||BigInt(p.amount.replace('.',''))<=0n)throw new ValidateException('余额数量须为正两位小数字符串');}else positive(p.amount);}
 return p;
}
export async function prepareCustomerUserOperation(kind:CustomerUserOperationKind,context:CustomerUserOperationContext,value:unknown):Promise<PreparedCustomerUserOperation>{if(!(CUSTOMER_USER_KINDS as readonly string[]).includes(kind))throw new ValidateException('用户操作种类无效');const actor=freezeCustomerActor(context.actor),key=normalizeOutRequestKey(context.request_key),body=freezeCustomerJson(value);customerUserExactKeys(body,['version','scope_key','targets','expected_catalog_revision','payload']);if(body.version!==CUSTOMER_USER_OPERATION_VERSION||typeof body.scope_key!=='string'||!/^[a-f0-9]{64}$/.test(body.scope_key)||typeof body.expected_catalog_revision!=='string'||!/^[a-f0-9]{64}$/.test(body.expected_catalog_revision)||!Array.isArray(body.targets)||!body.targets.length||body.targets.length>100)throw new ValidateException('用户操作身份或版本无效');let previous=0;const targets=body.targets.map(value=>{customerUserExactKeys(value,['uid','expected_user_revision']);if(typeof value.uid!=='number'||value.uid<=previous||typeof value.expected_user_revision!=='string'||!/^[a-f0-9]{64}$/.test(value.expected_user_revision))throw new ValidateException('用户目标须按编号唯一排序');const uid=customerWorkId(value.uid,'用户');previous=uid;return Object.freeze({uid,expected_user_revision:value.expected_user_revision});});if(['replace_level','adjust_membership','adjust_money','adjust_integral'].includes(kind)&&targets.length!==1)throw new ValidateException('此用户操作仅接受一个目标');customerUserPayload(kind,body);const input=Object.freeze({version:CUSTOMER_USER_OPERATION_VERSION,scope_key:body.scope_key,targets:Object.freeze(targets),expected_catalog_revision:body.expected_catalog_revision,payload:body.payload as CustomerJson});return Object.freeze({actor,key,kind,input,hash:await outRequestHash({version:CUSTOMER_USER_OPERATION_VERSION,actor_uid:actor.uid,kind,input})});}
async function lockRequest(tx:DbClient,uid:number,key:string,write=true){if(Object.hasOwn(tx,'$client'))throw Error('User operation requires caller-owned transaction');await assertCustomerUserOperationCatalog(tx);await tx.execute(sql`LOCK TABLE public.customer_user_operation_request IN ROW SHARE MODE NOWAIT`);if(write&&!(await customerUserOperationReadiness(tx)).ready)throw new HttpApiException('用户操作台账或运行权限尚未验收',503,503);await tx.execute(sql`SET LOCAL row_security=off`);await tx.execute(sql`SELECT set_config('statement_timeout',LEAST(NULLIF((SELECT setting::bigint FROM pg_settings WHERE name='statement_timeout'),0),8000)::text||'ms',true),set_config('lock_timeout',LEAST(NULLIF((SELECT setting::bigint FROM pg_settings WHERE name='lock_timeout'),0),1500)::text||'ms',true)`);const digest=await outRequestHash([uid,key]);await tx.execute(sql`SELECT pg_advisory_xact_lock(731656::int,${parseInt(digest.slice(0,8),16)|0}::int)`);}
async function readReceipt(tx:DbClient,uid:number,key:string):Promise<CustomerUserOperationReceipt|null>{const rows=await tx.execute<{actor_uid:number;service_id:number;request_hash:string;kind:CustomerUserOperationKind;targets:{uid:number}[];outcome:CustomerUserOperationOutcome;evidence:Record<string,CustomerJson>}>(sql`SELECT actor_uid,service_id,request_hash,kind,targets,outcome,evidence FROM public.customer_user_operation_request WHERE actor_uid=${uid} AND request_key=${key}::uuid LIMIT 2`);if(rows.length>1)throw Error('User receipt identity ambiguous');if(!rows[0])return null;const{targets,...row}=rows[0];return{version:CUSTOMER_USER_OPERATION_VERSION,request_key:key,...row,user_ids:targets.map(t=>t.uid)};}
function same(receipt:CustomerUserOperationReceipt,p:PreparedCustomerUserOperation){if(receipt.request_hash!==p.hash||receipt.kind!==p.kind||receipt.user_ids.join(',')!==p.input.targets.map(t=>t.uid).join(','))throw new HttpApiException('原请求键已用于不同用户操作',409,409);}
async function prior(tx:DbClient,p:PreparedCustomerUserOperation,write=true){await lockRequest(tx,p.actor.uid,p.key,write);const result=await readReceipt(tx,p.actor.uid,p.key);if(result)same(result,p);return result;}
function success(kind:CustomerUserOperationKind):CustomerUserOperationOutcome{return kind==='grant_coupons'?'coupons-granted':kind==='adjust_membership'?'membership-adjusted':kind==='adjust_money'||kind==='adjust_integral'?'finance-adjusted':'users-updated';}
async function append(tx:DbClient,p:PreparedCustomerUserOperation,serviceId:number,outcome:CustomerUserOperationOutcome,evidence:Record<string,CustomerJson>={}):Promise<CustomerUserOperationReceipt>{if(!Number.isSafeInteger(serviceId)||serviceId<0||![success(p.kind),'abandoned','rollback-rejected'].includes(outcome)||serviceId===0&&outcome===success(p.kind))throw new ValidateException('用户回执无效');const safe=freezeCustomerJson(evidence,16384),existing=await prior(tx,p);if(existing){if(existing.outcome!==outcome)throw new HttpApiException('原用户操作已有确定回执',409,409);return existing;}await tx.execute(sql`INSERT INTO public.customer_user_operation_request(actor_uid,request_key,request_hash,service_id,kind,scope_key,targets,expected_catalog_revision,intent,evidence,outcome) VALUES(${p.actor.uid},${p.key}::uuid,${p.hash},${serviceId},${p.kind},${p.input.scope_key},${JSON.stringify(p.input.targets)}::jsonb,${p.input.expected_catalog_revision},${JSON.stringify(p.input)}::jsonb,${JSON.stringify(safe)}::jsonb,${outcome})`);const result=await readReceipt(tx,p.actor.uid,p.key);if(!result)throw Error('User receipt did not persist');same(result,p);return result;}
export async function authorizeCustomerUserWrite(tx:DbClient,p:PreparedCustomerUserOperation){await authorizeCustomerOperationOwner(tx,p.actor);await acquireCustomerWorkScopeLock(tx,p.actor.uid);const scope=await authorizeCustomerWorkActor(tx,p.actor);if(scope.scope_key!==p.input.scope_key)throw new HttpApiException('用户管理身份已变化，请重新读取',403,403);return scope;}
export async function lockCustomerUsers(tx:DbClient,uids:number[]){const rows=await tx.select().from(user).where(and(inArray(user.uid,uids),eq(user.isDel,0),isNull(user.deleteTime))).orderBy(asc(user.uid)).for('update',{noWait:true});if(rows.length!==uids.length)throw new NotFoundException('部分用户不存在或已删除');await tx.select({id:userLevel.id}).from(userLevel).where(inArray(userLevel.uid,uids)).orderBy(asc(userLevel.uid),asc(userLevel.id)).for('update',{noWait:true});// Relations are INSERT/DELETE-only under the fixed runtime. The locked target
// account coordinates normal writers; full relation/xmin CAS and pre/post
// topology checks reject observed drift without claiming a raw-writer fence.
}
export async function assertCustomerUserSnapshots(tx:DbClient,states:CustomerUserState[]){for(const before of states)if((await readCustomerUserState(tx,before.account.uid)).revision!==before.revision)throw new HttpApiException('用户完整状态在写入前变化，请重新读取',412,412);}
async function verifyTopology(tx:DbClient,states:CustomerUserState[],p:PreparedCustomerUserOperation){const payload=p.input.payload as Record<string,CustomerJson>;for(const before of states){const after=await readCustomerUserState(tx,before.account.uid),allowed=p.kind==='replace_level'?['level','exp','levelStatus']:p.kind==='replace_group'?['groupId']:p.kind==='adjust_membership'?['isMoneyLevel','isEverLevel','overdueTime']:p.kind==='adjust_money'?['nowMoney']:p.kind==='adjust_integral'?['integral']:[],untouched=(state:CustomerUserState)=>Object.fromEntries(Object.entries(state.account).filter(([key])=>!allowed.includes(key)));if(await outRequestHash(JSON.parse(JSON.stringify(untouched(after))))!==await outRequestHash(JSON.parse(JSON.stringify(untouched(before)))))throw new HttpApiException('用户其它账户字段在写入期间变化',412,412);if(p.kind==='replace_labels'){const platform=after.relations.filter(r=>r.type===0&&r.relationId===0),expected=payload.label_ids as number[];if(platform.length!==expected.length||platform.map(r=>r.labelId).sort((a,b)=>a-b).join(',')!==expected.join(','))throw new HttpApiException('用户标签完整集合在写入期间变化',412,412);const rest=(s:CustomerUserState)=>s.relations.filter(r=>r.type!==0||r.relationId!==0);if(await outRequestHash(rest(after))!==await outRequestHash(rest(before)))throw new HttpApiException('用户其它标签归属在写入期间变化',412,412);}else if(await outRequestHash(after.relations)!==await outRequestHash(before.relations))throw new HttpApiException('用户标签完整集合在写入期间变化',412,412);
 if(p.kind==='replace_level'&&before.account.level!==Number(payload.level_id)){const previous=new Set(before.levels.map(r=>r.id)),newRows=after.levels.filter(r=>!previous.has(r.id));if(after.levels.length<before.levels.length||newRows.length>1||newRows.some(r=>r.levelId!==payload.level_id)||before.levels.some(r=>!after.levels.some(a=>a.id===r.id)))throw new HttpApiException('用户等级完整历史在写入期间变化',412,412);}else if(await outRequestHash(after.levels)!==await outRequestHash(before.levels))throw new HttpApiException('用户等级完整历史在写入期间变化',412,412);
 }}
export class CustomerWorkUserOperationRequest {
 constructor(readonly container:Container){}
 async outcome(value:CustomerWorkActor,keyValue:unknown){const actor=freezeCustomerActor(value),key=normalizeOutRequestKey(keyValue);return withTx(this.container,async tx=>{await lockRequest(tx,actor.uid,key,false);await authorizeCustomerOperationOwner(tx,actor);return readReceipt(tx,actor.uid,key);});}
 async abandon(kind:CustomerUserOperationKind,context:CustomerUserOperationContext,value:unknown){const p=await prepareCustomerUserOperation(kind,context,value);return withTx(this.container,async tx=>{const existing=await prior(tx,p,false);await authorizeCustomerOperationOwner(tx,p.actor);return existing??append(tx,p,0,'abandoned');});}
 private async rejection(p:PreparedCustomerUserOperation,error:unknown){if(!(error instanceof ValidateException||error instanceof NotFoundException||error instanceof AuthException||error instanceof HttpApiException&&[403,412].includes(error.httpStatus)))return null;return withTx(this.container,async tx=>{const existing=await prior(tx,p,false);await authorizeCustomerOperationOwner(tx,p.actor);return{receipt:existing??await append(tx,p,0,'rollback-rejected',{code:error instanceof HttpApiException?String(error.httpStatus):String(error.code)}),replayed:Boolean(existing)};});}
 async execute(kind:CustomerUserOperationKind,context:CustomerUserOperationContext,value:unknown,callback:(tx:DbClient,scope:CustomerWorkScope,states:CustomerUserState[],p:PreparedCustomerUserOperation)=>Promise<Record<string,CustomerJson>>):Promise<CustomerUserOperationResult>{const p=await prepareCustomerUserOperation(kind,context,value);try{return await withTx(this.container,async tx=>{const existing=await prior(tx,p);if(existing){await authorizeCustomerOperationOwner(tx,p.actor);return{receipt:existing,replayed:true};}await lockCustomerUsers(tx,p.input.targets.map(t=>t.uid));const scope=await authorizeCustomerUserWrite(tx,p);await acquireCustomerUserCatalogLock(tx,kind==='replace_level'?'level':kind==='replace_group'?'group':'label',[]);if(await customerUserCatalogRevision(tx)!==p.input.expected_catalog_revision)throw new HttpApiException('用户分组等级标签目录已变化，请重新读取',412,412);const states=[];for(const target of p.input.targets){const state=await readCustomerUserState(tx,target.uid);if(state.revision!==target.expected_user_revision)throw new HttpApiException('用户已变化，请重新读取',412,412);states.push(state);}if(kind==='grant_coupons'){const payload=p.input.payload as Record<string,CustomerJson>,id=Number(payload.issue_id);const[issue]=await tx.select().from(storeCouponIssue).where(eq(storeCouponIssue.id,id)).limit(1).for('update',{noWait:true});if(!issue)throw new NotFoundException('赠送优惠券不存在');if(await customerUserIssueRevision(tx,id)!==payload.expected_issue_revision)throw new HttpApiException('赠券定义或库存已变化，请重新读取',412,412);}const evidence=await callback(tx,scope,states,p);await verifyTopology(tx,states,p);await authorizeCustomerOperationOwner(tx,p.actor);return{receipt:await append(tx,p,scope.service_id,success(kind),evidence),replayed:false};});}catch(error){let failure=error,cause:unknown=error;for(let depth=0;depth<8&&cause&&typeof cause==='object';depth++){if('code'in cause&&cause.code==='55P03'){failure=new ValidateException('用户或权限正在变化，请重新读取后重试');break;}cause='cause'in cause?cause.cause:undefined;}const rejected=await this.rejection(p,failure);if(rejected)return rejected;throw failure;}}
}
