import {and,asc,desc,eq,inArray,sql} from 'drizzle-orm';
import {withTx,createContainerFromDb,type Container,type DbClient} from '@/lib/di';
import type {Env} from '@/env';
import {storeOrder,storeOrderCartInfo,storeOrderRefund,storeOrderRefundPayment,storeOrderStatus,storeOrderInvoice,storeProduct,systemConfig} from '@/models/schema';
import {ValidateException,NotFoundException,HttpApiException} from '@/utils/errors';
import {outRequestHash} from '@/services/out/OutIdempotency';
import {amountToCents} from '@/services/payment/RefundGateway';
import {evaluatePaymentReadiness} from '@/services/payment/PaymentReadinessService';
import {normalizeConfigScalar} from '@/utils/config';
import {merchantOrderRevision} from '@/services/store/StoreManagerScope';
import {managerRefundMaterializationReadiness} from '@/services/store/StoreManagerFinancialService';
import {customerFinancialOperationReadiness} from '@/migrations/runCustomerFinancialOperation';
import {customerWorkScopeLockReadiness,acquireCustomerWorkScopeLock} from '@/migrations/runCustomerWorkScopeLock';
import {acquireCheckoutPricingLock,auditCheckoutPricingLockRuntime} from '@/migrations/checkoutPricingLock';
import {quoteOrderRefundWithMaterialization,type OrderRefundApplicationQuote} from '@/services/order/StoreOrderRefundService';
import {previewReturnImages,returnImageReferences} from '@/services/order/RefundReturnPayload';
import {publicProductPictures,renderProductPictures} from '@/services/activity/ProductAssetPolicy';
import {quoteOrderRefundLineFinance} from '@/services/order/OrderSplitFinance';
import {loadRefundOrderGeneration,currentGenerationRefunds} from '@/services/order/RefundOrderGeneration';
import {parseCanonicalAttachmentId} from '@/services/system/AttachmentService';
import {authorizeCustomerOperationOwner,freezeCustomerActor,lockCustomerWorkOrder} from './CustomerWorkOperationRequest';
import {authorizeCustomerWorkActor,CUSTOMER_WORK_VERSION,customerWorkId,customerWorkConsistency,type CustomerWorkActor,type CustomerWorkEnvelope,type CustomerWorkScope} from './CustomerWorkScope';
import {CUSTOMER_FINANCIAL_KINDS,CUSTOMER_FINANCIAL_QUOTE_VERSION,financialMoney,financialText,financialBusinessNumber,parseFinancialQuote,type FinancialInput} from './CustomerWorkFinancialProtocol';
import type {CustomerFinancialOrder,CustomerFinancialRefundQuote,CustomerFinancialRefundReview,CustomerFinancialActions,CustomerFinancialReadiness} from '../../../../view/common/customerWorkFinancial';

export type FinancialOrder=typeof storeOrder.$inferSelect;
export type FinancialRefund=typeof storeOrderRefund.$inferSelect;
const CONFIG_KEYS=['refund_time_available','ali_pay_status','balance_func_status','offline_pay_status','pay_weixin_mchid','pay_weixin_open','pay_weixin_serial_no','routine_appId','site_url','wechat_app_appid','wechat_appid','yue_pay_status'];
const safe=(condition:boolean,message:string)=>{if(!condition)throw new ValidateException(message);};
export async function financialRoot(db:DbClient,order:FinancialOrder):Promise<FinancialOrder>{financialBusinessNumber(order.orderId,32);const rootId=order.pid>0?order.pid:order.id,rows=await db.select().from(storeOrder).where(eq(storeOrder.id,rootId)).limit(2);safe(rows.length===1,'原支付主单不存在或身份不唯一');const root=rows[0],allocated=root.pid===-1&&root.supplierId===0&&root.supplierAllocationStatus===2;financialBusinessNumber(root.orderId,32);safe(order.uid===root.uid&&order.payType===root.payType&&(order.pid<=0||root.pid===-1)&&(order.storeId===root.storeId||allocated)&&(order.supplierId===root.supplierId||allocated),'履约订单和原支付订单归属不一致');return root;}
export async function financialFacts(db:DbClient,order:FinancialOrder){
 const root=await financialRoot(db,order),carts=await db.select().from(storeOrderCartInfo).where(eq(storeOrderCartInfo.oid,order.id)).orderBy(asc(storeOrderCartInfo.id)).limit(101),refunds=await db.select().from(storeOrderRefund).where(eq(storeOrderRefund.storeOrderId,order.id)).orderBy(asc(storeOrderRefund.id)).limit(201),statuses=await db.select().from(storeOrderStatus).where(eq(storeOrderStatus.oid,order.id)).orderBy(asc(storeOrderStatus.id)).limit(403),invoices=await db.select().from(storeOrderInvoice).where(inArray(storeOrderInvoice.orderId,[root.id,order.id])).orderBy(asc(storeOrderInvoice.id)).limit(4),config=await db.select({id:systemConfig.id,name:systemConfig.menuName,value:systemConfig.value,sort:systemConfig.sort}).from(systemConfig).where(and(eq(systemConfig.isStore,0),inArray(systemConfig.menuName,CONFIG_KEYS))).orderBy(desc(systemConfig.sort),desc(systemConfig.id)).limit(101);
 safe(carts.length<=100&&refunds.length<=200&&statuses.length<=402&&invoices.length<=3&&config.length<=100,'财务关联数据超过完整核对容量');safe(carts.every(x=>x.uid===order.uid&&x.oid===order.id)&&new Set(carts.map(x=>x.cartId)).size===carts.length&&refunds.every(x=>x.uid===order.uid&&x.storeId===order.storeId&&x.supplierId===order.supplierId),'财务商品或退款关联不一致');safe(carts.reduce((sum,x)=>sum+new TextEncoder().encode(x.cartInfo??'').length,0)<=1048576&&carts.every(x=>new TextEncoder().encode(x.cartInfo??'').length<=65536),'财务商品快照过大');
 const payments=refunds.length?await db.select().from(storeOrderRefundPayment).where(inArray(storeOrderRefundPayment.refundId,refunds.map(x=>x.id))).orderBy(asc(storeOrderRefundPayment.id)).limit(201):[];safe(payments.length<=200&&new Set(payments.map(x=>x.refundId)).size===payments.length,'退款资金凭据重复或过多');
 return{root,carts,refunds,payments,statuses,invoices,config};
}
export async function financialRevisions(db:DbClient,order:FinancialOrder){const facts=await financialFacts(db,order);return{facts,order_revision:await merchantOrderRevision(order),financial_revision:await outRequestHash({version:'customer-financial-source-v1',order,...facts})};}
export async function assertFinancialReview(db:DbClient,order:FinancialOrder,input:FinancialInput){const state=await financialRevisions(db,order);if(state.order_revision!==input.expected_order_revision||state.financial_revision!==input.expected_financial_revision)throw new ValidateException('订单财务依据已变化，请重新读取并确认');return state;}
export async function financialWindow(tx:DbClient){await acquireCheckoutPricingLock(tx);const rows=await tx.select({value:systemConfig.value}).from(systemConfig).where(and(eq(systemConfig.isStore,0),eq(systemConfig.menuName,'refund_time_available'))).orderBy(desc(systemConfig.sort),desc(systemConfig.id)).limit(1);const value=normalizeConfigScalar(rows[0]?.value)||'0';if(!/^\d+$/.test(value)||!Number.isSafeInteger(Number(value))||Number(value)>36500)throw new HttpApiException('全局售后期限配置无效',503,503);return Number(value);}
export async function financialRefundRevision(refund:FinancialRefund){financialBusinessNumber(refund.orderId,50);return outRequestHash({version:'customer-financial-refund-source-v1',refund});}
export async function financialRefundReviewHash(db:DbClient,refund:FinancialRefund,order:FinancialOrder){const state=await financialRevisions(db,order);return outRequestHash({version:'customer-financial-refund-review-source-v1',refund,order,...state.facts});}
export async function financialQuoteFingerprint(quote:OrderRefundApplicationQuote){return outRequestHash({version:'customer-financial-refund-quote-source-v1',order:quote.order,carts:quote.carts,refunds:quote.previousRefunds,refundTimeDays:quote.refundTimeDays,receivedAt:quote.receivedAt});}
async function methodReadiness(db:DbClient,env:Env){const rows=await db.select({name:systemConfig.menuName,value:systemConfig.value}).from(systemConfig).where(and(eq(systemConfig.isStore,0),inArray(systemConfig.menuName,CONFIG_KEYS))).orderBy(desc(systemConfig.sort),desc(systemConfig.id)).limit(101);safe(rows.length<=100,'财务配置超过核对容量');const values:Record<string,string>={};for(const row of rows)if(!Object.hasOwn(values,row.name))values[row.name]=normalizeConfigScalar(row.value);return evaluatePaymentReadiness(values,env).methods;}
export async function financialAvailability(db:DbClient,order:FinancialOrder,env:Env,refund?:FinancialRefund):Promise<{readiness:CustomerFinancialReadiness;actions:CustomerFinancialActions}>{
 const ledger=await customerFinancialOperationReadiness(db),scope=await customerWorkScopeLockReadiness(db),pricing=await auditCheckoutPricingLockRuntime(db,'public','customer-work'),material=await managerRefundMaterializationReadiness(db),methods=await methodReadiness(db,env),visible=order.pid>=0&&!order.isDel&&!order.isSystemDel&&order.supplierAllocationStatus!==1;
 const ready=ledger.ready&&scope.ready&&pricing.ready,reason=!ledger.ready?'手机订单财务台账及实际权限尚未验收':!scope.ready?'手机订单管理身份锁尚未验收':!pricing.ready?'财务配置锁及实际权限尚未验收':'',action=(available:boolean,denied:string)=>({available:ready&&available,reason:ready?(available?'':denied):reason}),root=await financialRoot(db,order),amount=amountToCents(root.payPrice),channel=['weixin','alipay'].includes(order.payType),providerReady=!channel||methods[order.payType as 'weixin'|'alipay'].enabled,cap=!channel||amount!==null&&amount<=2147483647;
 const actions=Object.fromEntries(CUSTOMER_FINANCIAL_KINDS.map(kind=>[kind,action(false,'请先读取当前财务操作对象')])) as CustomerFinancialActions;
 actions.change_price=action(visible&&order.paid===0&&order.status===0,'仅未支付且可操作的订单允许改价');actions.confirm_offline=action(visible&&order.pid===0&&order.paid===0&&order.status===0&&order.type===0&&methods.offline.enabled,order.type!==0?'营销订单不支持手机线下收款':!methods.offline.enabled?methods.offline.reason:'仅未支付且未拆分订单允许确认实际线下收款');
 actions.refund_create=action(visible&&order.paid===1&&[0,1,2,3].includes(order.status)&&['yue','weixin','alipay','integral'].includes(order.payType)&&order.type!==3&&material.ready&&providerReady&&cap,!material.ready?'退款实体拆单与发票台账尚未验收':!cap?'当前渠道原支付金额超过21474836.47元，需人工核对':!providerReady?methods[order.payType as 'weixin'|'alipay'].reason:'当前状态或支付方式不支持安全主动退款');
 if(refund){const active=!refund.isCancel&&!refund.isDel&&[0,1,2,4,5].includes(refund.refundType),payment=(await db.select().from(storeOrderRefundPayment).where(eq(storeOrderRefundPayment.refundId,refund.id)).limit(2))[0],free=!payment||['CREATED','FAILED','CLOSED'].includes(payment.providerStatus),refundCents=amountToCents(refund.refundPrice),exactChannel=order.payType==='yue'||refundCents===0||channel&&providerReady&&cap&&refundCents!==null&&refundCents<=2147483647;
  actions.refund_return=action(visible&&order.paid===1&&active&&[2,3].includes(refund.applyType)&&[0,1,2].includes(refund.refundType)&&free,'当前申请不允许审批退货，或渠道已受理');actions.refund_refuse=action(visible&&order.paid===1&&active&&free,'当前申请不能拒绝，或渠道资金结果尚未确认');actions.refund_execute=action(visible&&order.paid===1&&active&&exactChannel&&([1,4].includes(refund.applyType)||refund.applyType===2&&refund.refundType===5||refund.applyType===3&&[4,5].includes(refund.refundType)),!cap?'当前渠道原支付金额超过21474836.47元，需人工核对':!providerReady&&channel?methods[order.payType as 'weixin'|'alipay'].reason:'当前申请状态或支付方式不允许资金退款');actions.refund_remark=action(!order.isSystemDel&&!refund.isDel,'退款申请已删除，不能修改管理备注');
 }
 if(refund&&(order.isDel||order.isSystemDel||root.isDel||root.isSystemDel))actions.refund_remark=action(false,'订单或退款申请已删除，不能修改管理备注');
 return{readiness:{writes:ready,quote:ready&&material.ready,reason,provider_max_amount:'21474836.47'},actions};
}
async function images(db:DbClient,uid:number,value:unknown,env:Env){const values=returnImageReferences(value);if(values.some(v=>parseCanonicalAttachmentId(v)===null))throw new ValidateException('历史退款图片缺少受控上传归属依据');return(await previewReturnImages(createContainerFromDb(db),uid,values,env.APP_KEY)).map(x=>x.src);}
export class CustomerWorkFinancialReadService {
 constructor(readonly container:Container,readonly env:Env){}
 private async snapshot<T>(actorValue:CustomerWorkActor,scopeKey:string|undefined,read:(tx:DbClient,scope:CustomerWorkScope)=>Promise<T>):Promise<CustomerWorkEnvelope<T>>{const actor=freezeCustomerActor(actorValue),result=await withTx(this.container,async tx=>{await tx.execute(sql`SET TRANSACTION ISOLATION LEVEL REPEATABLE READ, READ ONLY`);await tx.execute(sql`SELECT set_config('statement_timeout','5000ms',true)`);const scope=await authorizeCustomerWorkActor(tx,actor);if(scopeKey!==undefined&&scope.scope_key!==scopeKey)throw new HttpApiException('手机订单管理身份已变化',403,403);const data=await read(tx,scope);return{version:CUSTOMER_WORK_VERSION,actor_uid:actor.uid,principal:{kind:'customer-order-manager' as const,service_id:scope.service_id,scope:'global' as const},scope_key:scope.scope_key,consistency_key:await customerWorkConsistency(tx,scope),data};});const current=await authorizeCustomerWorkActor(this.container.db,actor);if(current.scope_key!==result.scope_key)throw new HttpApiException('手机订单管理身份已变化',403,403);return result;}
 async order(actor:CustomerWorkActor,idValue:unknown,query:Record<string,string>){if(Object.keys(query).some(k=>!['order_no','scope_key'].includes(k))||!query.order_no)throw new ValidateException('订单财务查询必须指定实际订单号');const id=customerWorkId(idValue,'订单'),number=financialText(query.order_no,32);return this.snapshot(actor,query.scope_key,async db=>{const rows=await db.select().from(storeOrder).where(eq(storeOrder.orderId,number)).limit(2);if(rows.length!==1||rows[0].id!==id||rows[0].isSystemDel)throw new NotFoundException('订单业务编号与真实订单身份不匹配');const order=rows[0],state=await financialRevisions(db,order),policy=await financialAvailability(db,order,this.env);return{version:'customer-work-financial-order-v1',requested_order_no:number,order_id:order.id,order_no:order.orderId,payment_order_id:state.facts.root.id,payment_order_no:state.facts.root.orderId,uid:order.uid,store_id:order.storeId,supplier_id:order.supplierId,order_revision:state.order_revision,financial_revision:state.financial_revision,paid:order.paid,status:order.status,pay_type:order.payType,pay_price:financialMoney(order.payPrice),refunded_price:financialMoney(order.refundPrice),change_price:order.changePrice,total_num:order.totalNum,...policy} satisfies CustomerFinancialOrder;});}
 async review(actor:CustomerWorkActor,idValue:unknown,query:Record<string,string>){if(Object.keys(query).some(k=>!['refund_no','scope_key'].includes(k))||!query.refund_no)throw new ValidateException('退款审查必须指定实际退款单号');const id=customerWorkId(idValue,'退款'),number=financialText(query.refund_no,50);return this.snapshot(actor,query.scope_key,async db=>{const rows=await db.select().from(storeOrderRefund).where(eq(storeOrderRefund.orderId,number)).limit(2);if(rows.length!==1||rows[0].id!==id||rows[0].isDel)throw new NotFoundException('退款业务编号与真实申请身份不匹配');const refund=rows[0],order=(await db.select().from(storeOrder).where(eq(storeOrder.id,refund.storeOrderId)).limit(1))[0];if(!order||order.isSystemDel||refund.uid!==order.uid||refund.storeId!==order.storeId||refund.supplierId!==order.supplierId)throw new NotFoundException('退款申请不属于当前实际订单');const state=await financialRevisions(db,order),policy=await financialAvailability(db,order,this.env,refund);return{version:'customer-work-financial-refund-review-v1',requested_refund_no:number,refund_id:refund.id,refund_no:refund.orderId,order_id:order.id,order_no:order.orderId,payment_order_id:state.facts.root.id,payment_order_no:state.facts.root.orderId,uid:refund.uid,store_id:refund.storeId,supplier_id:refund.supplierId,order_revision:state.order_revision,financial_revision:state.financial_revision,refund_revision:await financialRefundRevision(refund),review_fingerprint:await financialRefundReviewHash(db,refund,order),apply_type:refund.applyType,refund_type:refund.refundType,refund_price:financialMoney(refund.refundPrice),refunded_price:financialMoney(refund.refundedPrice),remark:refund.remark,requires_received_confirmation:[2,3].includes(refund.applyType),return_evidence:{reason:refund.refundReason,explain:refund.refundExplain,images:await images(db,refund.uid,refund.refundImg,this.env),goods_images:await images(db,refund.uid,refund.refundGoodsImg,this.env),express_name:refund.refundExpressName,express_no:refund.refundExpress,phone:refund.refundPhone},...policy} satisfies CustomerFinancialRefundReview;});}
 async quote(actorValue:CustomerWorkActor,value:unknown){const actor=freezeCustomerActor(actorValue),input=parseFinancialQuote(value);const result=await withTx(this.container,async tx=>{const order=await lockCustomerWorkOrder(tx,input.order_id);await authorizeCustomerOperationOwner(tx,actor);await acquireCustomerWorkScopeLock(tx,actor.uid);const scope=await authorizeCustomerWorkActor(tx,actor);if(scope.scope_key!==input.scope_key)throw new HttpApiException('手机订单管理身份已变化',403,403);await acquireCheckoutPricingLock(tx);const state=await assertFinancialReview(tx,order,{...input,version:'customer-work-financial-operation-v1',payload:{}}),policy=await financialAvailability(tx,order,this.env);if(!policy.actions.refund_create.available)throw new ValidateException(policy.actions.refund_create.reason);const quote=await quoteOrderRefundWithMaterialization(createContainerFromDb(tx),{uid:order.uid,orderId:order.orderId,applyType:4,privilegedActor:'customer-work',selectorNamespace:'row',...(input.mode==='items'?{cartSelections:input.items.map(x=>({cartId:x.cart_row_id,cartNum:x.cart_num}))}:{}),resolveRefundTimeDays:financialWindow,authorizeApplication:async(db,current)=>{await authorizeCustomerOperationOwner(db,actor);if(current.id!==order.id||current.orderId!==order.orderId)throw new ValidateException('退款报价原订单已变化');}},0);
 const remaining=input.mode==='remaining'?quote:await quoteOrderRefundWithMaterialization(createContainerFromDb(tx),{uid:order.uid,orderId:order.orderId,applyType:4,privilegedActor:'customer-work',selectorNamespace:'row',resolveRefundTimeDays:financialWindow,authorizeApplication:async(db,current)=>{await authorizeCustomerOperationOwner(db,actor);if(current.id!==order.id||current.orderId!==order.orderId)throw new ValidateException('退款报价原订单已变化');}},0);
 const products=await tx.select().from(storeProduct).where(inArray(storeProduct.id,[...new Set(quote.carts.map(x=>x.productId))])).limit(101);safe(products.length<=100,'退款商品超过完整预览容量');const currentCompleted=await currentGenerationRefunds(quote.previousRefunds.filter(x=>x.refundType===6),await loadRefundOrderGeneration(tx,order,quote.carts));
 const items=await Promise.all(quote.items.map(async item=>{const matching=quote.carts.filter(cart=>cart.id===item.cartId);if(matching.length!==1)throw new ValidateException('退款报价商品标识无法精确定位');const cart=matching[0],maximum=remaining.items.find(x=>x.cartId===item.cartId);safe(!!maximum&&maximum.cartNum>=item.cartNum,'退款报价可退件数已变化');let raw:Record<string,unknown>;try{raw=JSON.parse(cart.cartInfo??'{}');if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('shape');}catch{throw new ValidateException('退款商品快照无效');}const product=(raw.productInfo??raw.product??{}) as Record<string,unknown>,sku=(raw.sku??{}) as Record<string,unknown>,owner=products.find(x=>x.id===cart.productId),title=product.store_name??product.storeName??'',skuName=(product.attrInfo as Record<string,unknown>|undefined)?.suk??sku.suk??'';safe(typeof title==='string'&&typeof skuName==='string','退款商品名称快照无效');const refs=owner?await publicProductPictures(tx,[{image:product.image??owner.image,type:owner.type,relationId:owner.relationId}]):[''],previews=await renderProductPictures(this.env.APP_KEY,refs),line=quoteOrderRefundLineFinance(order,quote.carts,currentCompleted,new Map([[cart.cartId,item.cartNum]]));safe(line!==null,'退款商品缺少完整实际报价');return{cart_row_id:cart.id,cart_id:cart.cartId,cart_num:item.cartNum,max_num:maximum!.cartNum,title:financialText(title,500,false),sku:financialText(skuName,500,false),image:previews[0]??'',line_price:financialMoney(line!)};}));
 const data={version:CUSTOMER_FINANCIAL_QUOTE_VERSION,order_id:order.id,order_no:order.orderId,payment_order_id:state.facts.root.id,order_revision:state.order_revision,financial_revision:state.financial_revision,mode:input.mode,items,quoted_price:quote.quotedPrice,quote_fingerprint:await financialQuoteFingerprint(quote),refund_time_days:quote.refundTimeDays,received_at:quote.receivedAt} satisfies CustomerFinancialRefundQuote;return{version:CUSTOMER_WORK_VERSION,actor_uid:actor.uid,principal:{kind:'customer-order-manager' as const,service_id:scope.service_id,scope:'global' as const},scope_key:scope.scope_key,consistency_key:await customerWorkConsistency(tx,scope),data};});const current=await authorizeCustomerWorkActor(this.container.db,actor);if(current.scope_key!==result.scope_key)throw new HttpApiException('手机订单管理身份已变化',403,403);return result;}
}
