import {and,eq,sql} from 'drizzle-orm';
import {withTx,createContainerFromDb,type Container,type DbClient} from '@/lib/di';
import type {Env} from '@/env';
import {storeOrder,storeOrderRefund,storeOrderRefundPayment,storeOrderStatus,storeOrderOutbox} from '@/models/schema';
import {ValidateException,NotFoundException,HttpApiException,AuthException} from '@/utils/errors';
import {amountToCents} from '@/services/payment/RefundGateway';
import {computeAdminOrderPrice} from '@/services/admin/AdminMobileOrderOperationService';
import {PayType,applyStoreOrderPayment} from '@/services/order/StoreOrderPayService';
import {hasInitiatedAssistedProviderPayment} from '@/services/payment/AssistedProviderPaymentClaim';
import {assertPinkOrderPayable} from '@/services/activity/PinkLifecycleService';
import {assertMarketingOfflinePaymentAllowed} from '@/services/payment/OrderPaymentPolicy';
import {acquireCheckoutPricingLock} from '@/migrations/checkoutPricingLock';
import {approveStoreOrderReturn,applyOrderRefundWithMaterialization,quoteOrderRefundWithMaterialization,StoreOrderRefundService,type RefundExecutionScope} from '@/services/order/StoreOrderRefundService';
import {readRefundQuantityReservation,assertRefundQuantitiesHeld} from '@/services/order/RefundQuantityReservation';
import {normalizeOutRequestKey,outRequestHash} from '@/services/out/OutIdempotency';
import {CustomerWorkFinancialOperationRequest,checkFinancialOperation,appendFinancialOperation,authorizeFinancialOperation,sameFinancialReceipt,lockFinancialRequest} from './CustomerWorkFinancialOperationRequest';
import {CustomerWorkFinancialReadService,assertFinancialReview,financialAvailability,financialRoot,financialWindow,financialQuoteFingerprint,financialRefundRevision,financialRefundReviewHash,type FinancialOrder,type FinancialRefund} from './CustomerWorkFinancialReadService';
import {prepareFinancialOperation,validateFinancialPayload,financialCreation,financialDecision,financialRecord,financialRefundTarget,financialText,customerFinancialRefundNumber,CUSTOMER_FINANCIAL_KINDS,type FinancialKind,type FinancialContext,type FinancialReceipt,type FinancialRefundTarget,type PreparedFinancialOperation} from './CustomerWorkFinancialProtocol';
import {authorizeCustomerOperationOwner,freezeCustomerActor,type CustomerJson} from './CustomerWorkOperationRequest';
import {authorizeCustomerWorkActor,type CustomerWorkActor} from './CustomerWorkScope';
import {captureFinancialEffects,verifyFinancialLocalRefund,verifyFinancialCompletedRefund} from './CustomerWorkFinancialVerification';
import type {CustomerFinancialResult,CustomerFinancialExecution} from '../../../../view/common/customerWorkFinancial';

const now=()=>Math.floor(Date.now()/1000);
const fact=(ok:boolean,message='实际财务效果无法核对')=>{if(!ok)throw new ValidateException(message);};
class Replay extends Error {constructor(readonly receipt:FinancialReceipt){super('customer financial replay');}}
export class CustomerWorkFinancialService {
 readonly ledger:CustomerWorkFinancialOperationRequest;
 readonly reader:CustomerWorkFinancialReadService;
 constructor(readonly container:Container,readonly env:Env){this.ledger=new CustomerWorkFinancialOperationRequest(container);this.reader=new CustomerWorkFinancialReadService(container,env);}
 private async action(tx:DbClient,p:PreparedFinancialOperation,order:FinancialOrder,refund?:FinancialRefund){await acquireCheckoutPricingLock(tx);await assertFinancialReview(tx,order,p.input);const policy=await financialAvailability(tx,order,this.env,refund);if(!policy.actions[p.kind].available)throw new ValidateException(policy.actions[p.kind].reason);}
 private audit(p:PreparedFinancialOperation){return{changeType:'cw_financial_'+p.kind,changeMessage:`用户 ${p.actor.uid} / 原请求 ${p.key} 确认 ${p.kind}`};}
 private async auditOnce(tx:DbClient,p:PreparedFinancialOperation){const audit=this.audit(p),rows=await tx.select({id:storeOrderStatus.id}).from(storeOrderStatus).where(and(eq(storeOrderStatus.oid,p.input.order_id),eq(storeOrderStatus.changeType,audit.changeType),eq(storeOrderStatus.changeMessage,audit.changeMessage))).limit(2);fact(rows.length<=1);if(!rows.length)await tx.insert(storeOrderStatus).values({oid:p.input.order_id,...audit,changeTime:now()});}
 private async outbox(tx:DbClient,key:string,orderId:number,eventType:string,payload:unknown,id?:number){const rows=await tx.select().from(storeOrderOutbox).where(eq(storeOrderOutbox.eventKey,key)).limit(2);fact(rows.length===1&&(!id||rows[0].id===id)&&rows[0].aggregateType==='order'&&rows[0].aggregateId===orderId&&rows[0].eventType===eventType&&await outRequestHash(rows[0].payload)===await outRequestHash(payload),'实际支付或拒绝通知事件未完整持久化');}
 async price(ctx:FinancialContext,value:unknown){return this.ledger.local('change_price',ctx,value,async(tx,_scope,p,order)=>{await this.action(tx,p,order);const payload=validateFinancialPayload('change_price',p.input.payload) as {price:string};if(await hasInitiatedAssistedProviderPayment(tx,order.orderId))throw new ValidateException('扫码支付已发起，不能改价；请先核对原交易');const changed=computeAdminOrderPrice(order.payPrice,order.changePrice,amountToCents(payload.price)!);await tx.update(storeOrder).set({payPrice:changed.payPrice,changePrice:changed.changePrice}).where(and(eq(storeOrder.id,order.id),eq(storeOrder.paid,0)));const actual=(await tx.select().from(storeOrder).where(eq(storeOrder.id,order.id)).limit(1))[0];fact(!!actual&&actual.paid===0&&actual.payPrice===changed.payPrice&&actual.changePrice===changed.changePrice);const count=Number(changed.payPrice!==order.payPrice||changed.changePrice!==order.changePrice) as 0|1;if(count)await this.auditOnce(tx,p);return{outcome:'price-changed',evidence:{changed:count,verified:true}};});}
 async offline(ctx:FinancialContext,value:unknown){return this.ledger.local('confirm_offline',ctx,value,async(tx,_scope,p,order)=>{await this.action(tx,p,order);if(await hasInitiatedAssistedProviderPayment(tx,order.orderId))throw new ValidateException('扫码支付已发起，请先核对原交易');assertMarketingOfflinePaymentAllowed(order.type,'customer-work');await assertPinkOrderPayable(tx,order);const result=await applyStoreOrderPayment(createContainerFromDb(tx),{orderId:order.id,payType:PayType.OFFLINE,authorizeBeforePayment:async(db,current)=>{await authorizeFinancialOperation(db,p);fact(current.id===order.id&&current.uid===order.uid&&current.storeId===order.storeId&&current.supplierId===order.supplierId&&current.pid===0&&!current.isDel&&!current.isSystemDel,'线下收款订单归属已变化');},audit:this.audit(p)});const actual=(await tx.select().from(storeOrder).where(eq(storeOrder.id,order.id)).limit(1))[0];fact(result.outcome==='paid'&&!!result.outbox&&!!actual&&actual.paid===1&&actual.payType===PayType.OFFLINE);await this.outbox(tx,'order.paid:'+order.id,order.id,'order.paid',{orderId:order.id,orderNo:order.orderId},result.outbox!.id);return{outcome:'offline-paid',evidence:{outbox_id:result.outbox!.id,verified:true}};});}
 async create(ctx:FinancialContext,value:unknown){return this.ledger.local('refund_create',ctx,value,async(tx,_scope,p,order)=>{await this.action(tx,p,order);const payload=financialCreation(p.input.payload),number=customerFinancialRefundNumber(p.actor.uid,p.key),authorize=async(db:DbClient,current:FinancialOrder)=>{await authorizeFinancialOperation(db,p);fact(current.id===order.id&&current.orderId===order.orderId&&current.uid===order.uid&&current.storeId===order.storeId&&current.supplierId===order.supplierId,'主动退款订单归属已变化');};const quote=await quoteOrderRefundWithMaterialization(createContainerFromDb(tx),{uid:order.uid,orderId:order.orderId,applyType:4,privilegedActor:'customer-work',selectorNamespace:'row',...(payload.mode==='items'?{cartSelections:payload.items.map(x=>({cartId:x.cart_row_id,cartNum:x.cart_num}))}:{}),resolveRefundTimeDays:financialWindow,authorizeApplication:authorize},0);fact(quote.quotedPrice===payload.quoted_price&&await financialQuoteFingerprint(quote)===payload.quote_fingerprint,'主动退款报价依据已变化，请重新读取并确认');const result=await applyOrderRefundWithMaterialization(createContainerFromDb(tx),{uid:order.uid,orderId:order.orderId,applyType:4,privilegedActor:'customer-work',selectorNamespace:'row',refundReason:payload.reason,refundExplain:payload.reason,applicationOrderId:number,requireNewApplication:true,cartSelections:payload.mode==='items'?payload.items.map(x=>({cartId:x.cart_row_id,cartNum:x.cart_num})):quote.items,expectedRefundAmountCents:amountToCents(payload.quoted_price)!,requestedRefundAmountCents:amountToCents(payload.refund_price)!,resolveRefundTimeDays:financialWindow,authorizeApplication:authorize,authorizePreparedApplication:async(_db,actual)=>{fact(actual.quotedPrice===payload.quoted_price&&await financialQuoteFingerprint(actual)===payload.quote_fingerprint,'主动退款报价依据已变化，请重新读取并确认');},audit:this.audit(p)});const actual=(await tx.select().from(storeOrderRefund).where(eq(storeOrderRefund.id,result.refundId)).limit(1))[0];fact(!!actual&&actual.orderId===number&&actual.storeOrderId===order.id&&actual.uid===order.uid&&actual.refundPrice===payload.refund_price&&actual.refundedPrice==='0.00'&&actual.applyType===4&&actual.refundType===0&&!!readRefundQuantityReservation(actual));fact(await assertRefundQuantitiesHeld(tx,actual));return{outcome:'refund-created',evidence:{refund_id:actual.id,refund_no:actual.orderId,verified:true}};});}
 private async target(tx:DbClient,order:FinancialOrder,target:FinancialRefundTarget){const rows=await tx.select().from(storeOrderRefund).where(eq(storeOrderRefund.id,target.refund_id)).limit(2);if(rows.length!==1)throw new NotFoundException('退款申请不存在');const refund=rows[0];fact(refund.orderId===target.refund_no&&refund.storeOrderId===order.id&&refund.uid===order.uid&&refund.storeId===order.storeId&&refund.supplierId===order.supplierId&&!refund.isDel,'退款单号与实际申请归属不一致');fact(await financialRefundRevision(refund)===target.expected_refund_revision&&await financialRefundReviewHash(tx,refund,order)===target.review_fingerprint,'退款审查依据已变化，请重新读取并确认');return refund;}
 async remark(ctx:FinancialContext,value:unknown){return this.ledger.local('refund_remark',ctx,value,async(tx,_scope,p,order)=>{const raw=financialRecord(p.input.payload,['refund_id','refund_no','expected_refund_revision','review_fingerprint','remark']),payload={...financialRefundTarget(raw),remark:financialText(raw.remark)},refund=await this.target(tx,order,payload);await this.action(tx,p,order,refund);const changed=Number(refund.remark!==payload.remark) as 0|1;if(changed){const updated=await tx.update(storeOrderRefund).set({remark:payload.remark}).where(and(eq(storeOrderRefund.id,refund.id),eq(storeOrderRefund.remark,refund.remark))).returning({id:storeOrderRefund.id});fact(updated.length===1);await this.auditOnce(tx,p);}const actual=(await tx.select().from(storeOrderRefund).where(eq(storeOrderRefund.id,refund.id)).limit(1))[0];fact(!!actual&&actual.remark===payload.remark);return{outcome:'refund-remark-saved',evidence:{refund_id:refund.id,changed,verified:true}};});}
 async execute(kind:'refund_return'|'refund_refuse'|'refund_execute',ctx:FinancialContext,value:unknown):Promise<CustomerFinancialResult>{
  if(!Object.hasOwn(this.container.db,'$client'))throw Error('Customer refund execution requires a root database client; provider I/O must follow committed admission');
  const p=await prepareFinancialOperation(kind,ctx,value),body=financialDecision(kind,p.input.payload),original=await this.ledger.original(p.actor,p.key);if(original){sameFinancialReceipt(original.receipt,p);if(original.receipt.outcome!=='provider-admitted')return this.status(p.actor,p.key,true);const current=await this.status(p.actor,p.key,true);if(current.execution?.completed||!current.execution?.can_resume)return current;}
  let admitted:FinancialReceipt|null=original?.receipt??null,serviceId=0,before:Awaited<ReturnType<typeof captureFinancialEffects>>|null=null;
  const scope:RefundExecutionScope={expectedStoreOrderId:p.input.order_id,expectedRefundOrderId:body.refund_no,expectedRefundAmountCents:kind==='refund_execute'?amountToCents(body.refund_price!)!:undefined,requireSystemVisible:true,requirePaid:true,reasonCodePoints:true,
   authorizeBeforeRefundLock:async(tx,refund)=>{admitted=await checkFinancialOperation(tx,p);if(admitted&&admitted.outcome!=='provider-admitted')throw new Replay(admitted);fact(refund.id===body.refund_id&&refund.orderId===body.refund_no&&refund.storeOrderId===p.input.order_id,'原退款业务单号与真实申请不匹配');},
   authorizeLockedDecision:async(tx,refund,order)=>{const authority=await authorizeFinancialOperation(tx,p);serviceId=authority.service_id;fact(refund.id===body.refund_id&&refund.orderId===body.refund_no&&refund.storeOrderId===order.id&&order.id===p.input.order_id&&refund.uid===order.uid&&refund.storeId===order.storeId&&refund.supplierId===order.supplierId,'退款申请与当前履约订单归属不符');if(admitted){fact(admitted.service_id===serviceId&&await this.providerBinding(tx,admitted,refund,order),'原渠道受理身份或资金凭据已变化');return;}await this.action(tx,p,order,refund);fact(await financialRefundRevision(refund)===body.expected_refund_revision&&await financialRefundReviewHash(tx,refund,order)===body.review_fingerprint&&refund.applyType===body.decision.apply_type&&refund.refundType===body.decision.refund_type,'退款审查依据已变化，请核对原请求');if(kind==='refund_execute'){fact(refund.refundPrice===body.refund_price,'执行金额必须等于本申请已审查金额；减少金额请创建新申请');before=await captureFinancialEffects(tx,order,refund);}},
   recordLockedDecision:async(tx,outcome)=>{const refund=(await tx.select().from(storeOrderRefund).where(eq(storeOrderRefund.id,body.refund_id)).limit(1))[0],order=(await tx.select().from(storeOrder).where(eq(storeOrder.id,p.input.order_id)).limit(1))[0];fact(!!refund&&!!order);let evidence:Record<string,CustomerJson>={refund_id:body.refund_id,verified:true};if(outcome==='provider-admitted'){const rows=await tx.select().from(storeOrderRefundPayment).where(eq(storeOrderRefundPayment.refundId,refund.id)).limit(2),root=await financialRoot(tx,order);fact(rows.length===1);const pay=rows[0];fact(pay.storeOrderId===order.id&&pay.outRefundNo==='CNSR'+refund.id&&pay.requestAmount===amountToCents(body.refund_price!)&&pay.totalAmount===amountToCents(root.payPrice)&&pay.requestAmount>0&&pay.totalAmount<=2147483647&&pay.provider===(order.payType==='weixin'?'wechat':'alipay'));evidence={...evidence,refund_no:refund.orderId,payment_order_id:root.id,uid:refund.uid,store_id:refund.storeId,supplier_id:refund.supplierId,provider:pay.provider,out_refund_no:pay.outRefundNo,request_amount:pay.requestAmount,total_amount:pay.totalAmount};}
    else if(outcome==='balance-settled'){fact(!!before);await verifyFinancialLocalRefund(tx,before!);}
    else if(outcome==='return-approved'){fact(refund.refundType===4&&order.refundType===4&&order.refundStatus===1);evidence.changed=1;}
    else {fact(refund.refundType===3&&refund.refuseReason===body.reason);await this.outbox(tx,'order.refund.refused.notice:'+refund.id,order.id,'order.refund.refused.notice',{orderId:order.id,orderNo:order.orderId,refundId:refund.id,userId:refund.uid,payPrice:order.payPrice});const claim=readRefundQuantityReservation(refund);if(claim){const held=await tx.execute<{id:number;refund_num:number}>(sql`SELECT id,refund_num FROM public.store_order_cart_info WHERE id IN (${sql.join(claim.items.map(x=>sql`${x.rowId}`),sql`,`)})`);fact(held.length===claim.items.length&&claim.items.every(x=>held.find(y=>y.id===x.rowId)?.refund_num===x.beforeRefundNum));}}
    await this.auditOnce(tx,p);admitted=await appendFinancialOperation(tx,p,serviceId,outcome,evidence);
   }};
  try{if(kind==='refund_return')await approveStoreOrderReturn(this.container,body.refund_id,scope,this.audit(p));else if(kind==='refund_refuse')await new StoreOrderRefundService(this.container,this.env).refuseRefund(body.refund_id,body.reason!,scope,this.audit(p));else await new StoreOrderRefundService(this.container,this.env).agreeRefund(body.refund_id,scope);}
  catch(error){if(error instanceof Replay)return this.status(p.actor,p.key,true);const receipt=await this.ledger.outcome(p.actor,p.key);if(receipt){sameFinancialReceipt(receipt,p);return this.status(p.actor,p.key,!!original);}const rejected=await this.ledger.reject(p,error);if(rejected)return rejected;throw error;}
  const result=await this.status(p.actor,p.key,!!original);if(!result.receipt)throw new HttpApiException('原财务操作回执暂无法核对，请查询原请求',503,503);sameFinancialReceipt(result.receipt,p);return result;
 }
 private async providerBinding(tx:DbClient,receipt:FinancialReceipt,refund:FinancialRefund,order:FinancialOrder){const evidence=receipt.evidence,rows=await tx.select().from(storeOrderRefundPayment).where(eq(storeOrderRefundPayment.refundId,refund.id)).limit(2),rootId=evidence.payment_order_id;if(rows.length!==1||typeof rootId!=='number')return false;const roots=await tx.select().from(storeOrder).where(eq(storeOrder.id,rootId)).limit(2);if(roots.length!==1)return false;const pay=rows[0],root=roots[0];return refund.id===evidence.refund_id&&refund.orderId===evidence.refund_no&&refund.storeOrderId===receipt.order_id&&refund.uid===evidence.uid&&refund.storeId===evidence.store_id&&refund.supplierId===evidence.supplier_id&&order.uid===refund.uid&&order.storeId===refund.storeId&&order.supplierId===refund.supplierId&&order.paid===1&&root.uid===refund.uid&&root.paid===1&&root.payType===order.payType&&(order.pid===root.id||order.id===root.id)&&pay.storeOrderId===order.id&&pay.outRefundNo===evidence.out_refund_no&&pay.outRefundNo==='CNSR'+refund.id&&pay.provider===evidence.provider&&pay.provider===(order.payType==='weixin'?'wechat':order.payType==='alipay'?'alipay':null)&&pay.requestAmount===evidence.request_amount&&pay.requestAmount===amountToCents(refund.refundPrice)&&pay.totalAmount===evidence.total_amount&&pay.totalAmount===amountToCents(root.payPrice);}
 /** Owner-only SQL read. Never queries the external provider or finalizes. */
 async status(actorValue:CustomerWorkActor,keyValue:unknown,replayed=false):Promise<CustomerFinancialResult>{const actor=freezeCustomerActor(actorValue),key=normalizeOutRequestKey(keyValue),original=await this.ledger.original(actor,key);if(!original)return{receipt:null,replayed,execution:null};const {receipt,p}=original;if(receipt.kind!=='refund_execute'||!['provider-admitted','balance-settled'].includes(receipt.outcome))return{receipt,replayed,execution:null};const body=financialDecision('refund_execute',p.input.payload),execution:CustomerFinancialExecution={version:'customer-work-financial-execution-v1',request_key:key,request_hash:receipt.request_hash,refund_id:body.refund_id,status:'UNKNOWN',completed:false,verified:false,can_resume:false};return withTx(this.container,async tx=>{await tx.execute(sql`SET TRANSACTION ISOLATION LEVEL REPEATABLE READ`);await lockFinancialRequest(tx,actor.uid,key,false);await authorizeCustomerOperationOwner(tx,actor);const refunds=await tx.select().from(storeOrderRefund).where(eq(storeOrderRefund.id,body.refund_id)).limit(2),orders=await tx.select().from(storeOrder).where(eq(storeOrder.id,receipt.order_id)).limit(2);if(refunds.length!==1||orders.length!==1)return{receipt,replayed,execution};const refund=refunds[0],order=orders[0];if(refund.orderId!==body.refund_no||refund.storeOrderId!==order.id||refund.refundPrice!==body.refund_price||refund.uid!==order.uid||refund.storeId!==order.storeId||refund.supplierId!==order.supplierId)return{receipt,replayed,execution};
   if(receipt.outcome==='balance-settled'){try{await verifyFinancialCompletedRefund(tx,refund);execution.status='BALANCE_SUCCESS';execution.completed=true;execution.verified=true;}catch(error){if(!(error instanceof ValidateException))throw error;}return{receipt,replayed,execution};}
   if(!await this.providerBinding(tx,receipt,refund,order))return{receipt,replayed,execution};const payment=(await tx.select().from(storeOrderRefundPayment).where(eq(storeOrderRefundPayment.refundId,refund.id)).limit(1))[0];if(!['CREATED','REQUESTING','PROCESSING','SUCCESS','CLOSED','ABNORMAL','FAILED','UNKNOWN'].includes(payment.providerStatus))return{receipt,replayed,execution};execution.status=payment.providerStatus as CustomerFinancialExecution['status'];execution.verified=true;if(payment.providerStatus==='SUCCESS'){try{await verifyFinancialCompletedRefund(tx,refund);execution.completed=true;}catch(error){if(!(error instanceof ValidateException))throw error;execution.status='UNKNOWN';execution.verified=false;}}
   if(!execution.completed&&![ 'CLOSED','ABNORMAL'].includes(payment.providerStatus)&&!refund.isDel&&!refund.isCancel&&refund.refundType!==6){try{const scope=await authorizeCustomerWorkActor(tx,actor);execution.can_resume=scope.scope_key===p.input.scope_key&&scope.service_id===receipt.service_id;}catch(error){if(!(error instanceof HttpApiException)&&!(error instanceof ValidateException)&&!(error instanceof AuthException))throw error;}}
   return{receipt,replayed,execution};});}
 async abandon(actor:CustomerWorkActor,keyValue:unknown,value:unknown,headerKey?:string):Promise<CustomerFinancialResult>{const key=normalizeOutRequestKey(keyValue);if(headerKey!==undefined&&normalizeOutRequestKey(headerKey)!==key)throw new ValidateException('路径与原请求键不匹配');const r=financialRecord(value,['kind','input']);if(typeof r.kind!=='string'||!CUSTOMER_FINANCIAL_KINDS.includes(r.kind as FinancialKind))throw new ValidateException('原财务操作种类无效');const result=await this.ledger.abandon(r.kind as FinancialKind,{actor,request_key:key},r.input);return result.receipt&&['provider-admitted','balance-settled'].includes(result.receipt.outcome)?this.status(actor,key,true):result;}
}
