import { and,eq,sql } from 'drizzle-orm';
import { createContainerFromDb,type Container,type DbClient } from '@/lib/di';
import type { Env } from '@/env';
import { deliveryService,expressCompany,storeOrder,storeOrderStatus,user,orderWaybillJob } from '@/models/schema';
import { acquireCustomerWorkCarrierLock,acquireCustomerWorkCourierLock } from '@/migrations/runCustomerWorkScopeLock';
import { SupplierFulfillmentService,type SupplierSplitCartInput } from '@/services/supplier/SupplierFulfillmentService';
import { OrderWaybillJobService } from '@/services/waybill/OrderWaybillJobService';
import { customerWaybillBindingFromReceipt,customerWaybillCartSnapshotHash } from '@/services/waybill/CustomerWaybillAuthority';
import { merchantOrderRevision } from '@/services/store/StoreManagerScope';
import { themeHash } from '@/services/content/ThemeReadService';
import { listCrmebOnePassWaybillTemplates,WaybillConfigurationError } from '@/services/waybill/CrmebOnePassWaybillProvider';
import { projectAdminWaybillTemplateCatalog } from '@/services/admin/AdminMobileFulfillmentService';
import { assertManualOrderDeliveryType } from '@/services/order/ManualVirtualDeliveryPolicy';
import { customerWorkQueryKeys,CUSTOMER_WORK_METRIC_SCOPES } from './CustomerWorkReadService';
import { customerWorkFulfillmentState,customerWorkCarriers,customerWorkCouriers,customerWorkDefaults,customerWorkRemarkTarget } from './CustomerWorkFulfillmentRead';
import { CustomerCityDeliveryService,acquireCustomerCityAdmissionFence } from './CustomerCityDeliveryService';
import { assertCustomerFulfillmentReady } from './customerFulfillmentAuthority';
import { CustomerWorkOperationRequest,freezeCustomerJson,type CustomerOperationContext,type CustomerOperationInput,type CustomerOperationKind,type CustomerOperationOutcome,type CustomerJson } from './CustomerWorkOperationRequest';
import { withCustomerWorkRead,customerWorkId,type CustomerWorkActor } from './CustomerWorkScope';
import { ApiException,HttpApiException,ValidateException } from '@/utils/errors';

function record(value:unknown):Record<string,unknown>{if(!value||Array.isArray(value)||typeof value!=='object'||Object.getPrototypeOf(value)!==Object.prototype)throw new ValidateException('履约操作格式无效');return value as Record<string,unknown>;}
function keys(body:Record<string,unknown>,required:string[],optional:string[]=[]){if(required.some(k=>!Object.hasOwn(body,k))||Object.keys(body).some(k=>!required.includes(k)&&!optional.includes(k)))throw new ValidateException('履约操作字段缺失或不受支持');}
function text(value:unknown,label:string,max:number,empty=false,multiline=false){if(typeof value!=='string'||!empty&&!value.trim()||[...value.trim()].length>max||(multiline?/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/:/[\u0000-\u001f\u007f]/).test(value))throw new ValidateException(`${label}格式无效`);return value.trim();}
function id(value:unknown,label:string){if(typeof value!=='number')throw new ValidateException(`${label}须为数字标识`);return customerWorkId(value,label);}
export function customerDeliveryKind(value:unknown,split:boolean):CustomerOperationKind{const body=record(value);if(body.type===1){if(body.express_record_type===1)return split?'split_delivery':'manual_delivery';if(body.express_record_type===2)return split?'electronic_split_waybill':'electronic_waybill';}if(body.type===2&&body.delivery_type===2)return split?'city_split_delivery':'city_delivery';if(body.type===2&&body.delivery_type===1||body.type===3)return split?'split_delivery':'manual_delivery';throw new ValidateException('履约类型无效');}
export function parseCustomerDelivery(value:unknown,split:boolean){
  const body=record(value),cartKeys=split?['cart_ids']:[];let parsed:Record<string,CustomerJson>;
  if(body.type===1&&body.express_record_type===1){keys(body,['type','express_record_type','carrier_id','delivery_id',...cartKeys]);parsed={type:1,express_record_type:1,carrier_id:id(body.carrier_id,'快递公司'),delivery_id:text(body.delivery_id,'快递单号',64)};}
  else if(body.type===1&&body.express_record_type===2){keys(body,['type','express_record_type','carrier_id','express_temp_id','to_name','to_tel','to_addr',...cartKeys]);parsed={type:1,express_record_type:2,carrier_id:id(body.carrier_id,'快递公司'),express_temp_id:text(body.express_temp_id,'面单模板',255),to_name:text(body.to_name,'发件人',128),to_tel:text(body.to_tel,'发件电话',32),to_addr:text(body.to_addr,'发件地址',255)};}
  else if(body.type===2&&body.delivery_type===1){keys(body,['type','delivery_type','delivery_uid',...cartKeys]);parsed={type:2,delivery_type:1,delivery_uid:id(body.delivery_uid,'配送员')};}
  else if(body.type===2&&body.delivery_type===2){keys(body,['type','delivery_type','station_type','cargo_weight','delivery_remark',...cartKeys]);if(body.station_type!==1&&body.station_type!==2)throw new ValidateException('同城平台无效');const weight=text(body.cargo_weight,'货物重量',12);if(!/^(?:[1-9]\d{0,2}|0)(?:\.\d{1,2})?$/.test(weight)||Number(weight)<=0||Number(weight)>100)throw new ValidateException('货物重量须为正数且不超过100千克');parsed={type:2,delivery_type:2,station_type:body.station_type,cargo_weight:weight,delivery_remark:text(body.delivery_remark,'配送备注',255,true)};}
  else if(body.type===3){keys(body,['type','fictitious_content',...cartKeys]);if(split)throw new ValidateException('手工虚拟商品须整单交付');parsed={type:3,fictitious_content:text(body.fictitious_content,'虚拟交付内容',500,false,true)};}
  else throw new ValidateException('履约渠道无效');
  const carts:SupplierSplitCartInput[]=[];
  if(split){if(!Array.isArray(body.cart_ids)||body.cart_ids.length<1||body.cart_ids.length>200)throw new ValidateException('请选择1至200项发货商品');const seen=new Set<string>();for(const item of body.cart_ids){const cart=record(item);keys(cart,['cart_id','cart_num']);const cartId=text(cart.cart_id,'商品快照ID',50),cartNum=id(cart.cart_num,'发货数量');if(seen.has(cartId))throw new ValidateException('同一商品不能重复选择');seen.add(cartId);carts.push({cartId,cartNum});}}
  return{payload:parsed,carts};
}
export class CustomerWorkFulfillmentService {
  constructor(readonly container:Container,readonly env:Env){}
  async operationOutcome(actor:CustomerWorkActor,key:unknown){const receipt=await new CustomerWorkOperationRequest(this.container).getOutcome(actor,key),jobId=receipt?.evidence.city_job_id;return{receipt,...(typeof jobId==='number'?{city_job:await new CustomerCityDeliveryService(this.container,this.env).outcome(actor,jobId)}:{})};}
  async cityJobOutcome(actor:CustomerWorkActor,idValue:unknown){return{city_job:await new CustomerCityDeliveryService(this.container,this.env).outcome(actor,customerWorkId(idValue,'同城配送任务'))};}
  async cityJobRecover(actor:CustomerWorkActor,idValue:unknown,value:unknown){const body=record(freezeCustomerJson(value)),jobId=customerWorkId(idValue,'同城配送任务');keys(body,['request_key']);const receipt=await new CustomerWorkOperationRequest(this.container).getOutcome(actor,body.request_key);if(!receipt||receipt.outcome!=='provider-admitted'||!['city_delivery','city_split_delivery'].includes(receipt.kind)||receipt.evidence.city_job_id!==jobId)throw new ValidateException('同城恢复须绑定原操作回执');return{receipt,city_job:await new CustomerCityDeliveryService(this.container,this.env).recover(actor,jobId)};}
  async remarkTarget(actor:CustomerWorkActor,reference:unknown,query:Record<string,string>){customerWorkQueryKeys(query,[]);return withCustomerWorkRead(this.container,actor,query.scope_key,async db=>({metric_scopes:CUSTOMER_WORK_METRIC_SCOPES,remark_target:await customerWorkRemarkTarget(db,reference,'number')}));}
  async bootstrap(actor:CustomerWorkActor,reference:unknown,query:Record<string,string>){customerWorkQueryKeys(query,[]);return withCustomerWorkRead(this.container,actor,query.scope_key,async db=>{const state=await customerWorkFulfillmentState(db,this.env,reference,'number'),o=state.order;return{metric_scopes:CUSTOMER_WORK_METRIC_SCOPES,requested_order_no:state.requested.orderId,remark_target:await customerWorkRemarkTarget(db,reference,'number'),order:{id:o.id,order_id:o.orderId,requested_order_id:state.requested.id,root_order_id:state.root.id,store_id:o.storeId,supplier_id:o.supplierId,customer_uid:o.uid,order_revision:state.order_revision,fulfillment_revision:state.fulfillment_revision,remark:o.remark,real_name:o.realName,user_phone:o.userPhone,user_address:o.userAddress,paid:o.paid,status:o.status,shipping_type:o.shippingType,product_type:o.productType,total_num:o.totalNum,pay_price:o.payPrice},actions:state.actions,carts:state.carts,defaults:state.defaults,readiness:state.readiness};});}
  async carriers(actor:CustomerWorkActor,query:Record<string,string>){customerWorkQueryKeys(query,[]);return withCustomerWorkRead(this.container,actor,query.scope_key,async db=>({metric_scopes:CUSTOMER_WORK_METRIC_SCOPES,list:await customerWorkCarriers(db)}));}
  async couriers(actor:CustomerWorkActor,query:Record<string,string>){customerWorkQueryKeys(query,[]);return withCustomerWorkRead(this.container,actor,query.scope_key,async db=>({metric_scopes:CUSTOMER_WORK_METRIC_SCOPES,list:await customerWorkCouriers(db)}));}
  async defaults(actor:CustomerWorkActor,query:Record<string,string>){customerWorkQueryKeys(query,[]);return withCustomerWorkRead(this.container,actor,query.scope_key,async db=>({metric_scopes:CUSTOMER_WORK_METRIC_SCOPES,defaults:await customerWorkDefaults(db)}));}
  async waybillJobs(actor:CustomerWorkActor,query:Record<string,string>){customerWorkQueryKeys(query,['order_id','status','after_id','limit']);return withCustomerWorkRead(this.container,actor,query.scope_key,async(db,scope)=>{const result=await new OrderWaybillJobService(createContainerFromDb(db),this.env).readCustomerJobs(db,{actorType:'customer',actorId:scope.actor_uid,serviceId:scope.service_id},{orderId:query.order_id?customerWorkId(query.order_id,'订单'):undefined,status:query.status,afterId:query.after_id?customerWorkId(query.after_id,'游标'):undefined,limit:query.limit?customerWorkId(query.limit,'每页数量'):undefined});return{metric_scopes:CUSTOMER_WORK_METRIC_SCOPES,...result};});}
  private async jobOperation(db:DbClient,idValue:unknown,uid:number,serviceId:number){
    const service=new OrderWaybillJobService(createContainerFromDb(db),this.env),job=await service.readCustomerJob(db,idValue,{actorType:'customer',actorId:uid,serviceId}),[root]=await db.select().from(storeOrder).where(eq(storeOrder.id,job.root_order_id)).limit(1),[order]=await db.select().from(storeOrder).where(eq(storeOrder.id,job.order_id)).limit(1);
    if(!root||!order||root.isSystemDel||order.isSystemDel)throw new ValidateException('原面单订单不存在');
    const order_revision=await merchantOrderRevision(order),fulfillment_revision=await themeHash({version:'customer-work-job-operation-revision-v1',job_revision:job.job_revision,order_revision,root_revision:await merchantOrderRevision(root)});
    return{job,order,root,operation:{order_id:order.id,order_revision,fulfillment_revision,root_order_id:root.id}};
  }
  async waybillJob(actor:CustomerWorkActor,idValue:unknown,query:Record<string,string>){customerWorkQueryKeys(query,[]);return withCustomerWorkRead(this.container,actor,query.scope_key,async(db,scope)=>{const state=await this.jobOperation(db,idValue,scope.actor_uid,scope.service_id);return{metric_scopes:CUSTOMER_WORK_METRIC_SCOPES,job:state.job,operation:state.operation};});}
  async waybillActions(actor:CustomerWorkActor,idValue:unknown,query:Record<string,string>){customerWorkQueryKeys(query,[]);return withCustomerWorkRead(this.container,actor,query.scope_key,async(db,scope)=>({metric_scopes:CUSTOMER_WORK_METRIC_SCOPES,list:await new OrderWaybillJobService(createContainerFromDb(db),this.env).readCustomerActions(db,idValue,{actorType:'customer',actorId:scope.actor_uid,serviceId:scope.service_id})}));}
  async waybillDecision(ctx:CustomerOperationContext,idValue:unknown,value:unknown){
    const immutable=freezeCustomerJson(value) as unknown as CustomerOperationInput,body=record(immutable.payload),jobId=customerWorkId(idValue,'面单任务');
    keys(body,['action','job_id','expected_job_revision','reason'],['tracking_number','label_url','provider_reference']);
    const action=body.action;if(!['APPLY_EXISTING','CONFIRM_ISSUED','CONFIRM_RETRY','CLOSE_NO_RETRY'].includes(String(action))||typeof body.expected_job_revision!=='string'||!/^[a-f0-9]{64}$/.test(body.expected_job_revision)||body.job_id!==jobId)throw new ValidateException('面单处置合同无效');
    const kind=({APPLY_EXISTING:'waybill_apply_existing',CONFIRM_ISSUED:'waybill_confirm_issued',CONFIRM_RETRY:'waybill_confirm_retry',CLOSE_NO_RETRY:'waybill_close'} as const)[action as 'APPLY_EXISTING'|'CONFIRM_ISSUED'|'CONFIRM_RETRY'|'CLOSE_NO_RETRY'];
    const result=await new CustomerWorkOperationRequest(this.container).execute(kind,ctx,immutable,async(tx,scope,order,p)=>{const state=await this.jobOperation(tx,jobId,scope.actor_uid,scope.service_id);if(state.order.id!==order.id||state.operation.order_revision!==immutable.expected_order_revision||state.operation.fulfillment_revision!==immutable.expected_fulfillment_revision)throw new HttpApiException('原面单或订单依据已变化，请重新核对',412,412);
      const [rawJob]=await tx.select().from(orderWaybillJob).where(eq(orderWaybillJob.id,jobId)).limit(1);if(!rawJob)throw new ValidateException('原面单任务不存在');const binding=await customerWaybillBindingFromReceipt(tx,rawJob),updated=await new OrderWaybillJobService(createContainerFromDb(tx),this.env).applyCustomerDecisionInTransaction(tx,jobId,{actorType:'customer',actorId:scope.actor_uid,serviceId:scope.service_id},action as 'APPLY_EXISTING'|'CONFIRM_ISSUED'|'CONFIRM_RETRY'|'CLOSE_NO_RETRY',{requestKey:p.key,reason:body.reason,trackingNumber:body.tracking_number,labelUrl:body.label_url,providerReference:body.provider_reference},binding,String(body.expected_job_revision));
      return{outcome:'job-updated',evidence:{waybill_job_id:jobId,status:updated.job.status,order_id:updated.job.order_id,fulfilled_order_id:updated.job.fulfilled_order_id,remaining_order_id:updated.job.remaining_order_id}};
    });
    if(!result.replayed&&result.receipt.outcome==='job-updated'&&result.receipt.evidence.status==='RETRYABLE')try{await new OrderWaybillJobService(this.container,this.env).dispatchPending(1,undefined,[jobId]);}catch{}
    return result;
  }
  async templates(actor:CustomerWorkActor,query:Record<string,string>){
    customerWorkQueryKeys(query,['carrier_id']);const carrierId=customerWorkId(query.carrier_id,'快递公司'),before=await withCustomerWorkRead(this.container,actor,query.scope_key,async db=>{const carrier=(await customerWorkCarriers(db)).find(c=>c.id===carrierId);if(!carrier)throw new ValidateException('快递公司已停用或不存在');return{carrier,defaults:await customerWorkDefaults(db)};});
    let catalog:ReturnType<typeof projectAdminWaybillTemplateCatalog>;
    try{catalog=projectAdminWaybillTemplateCatalog(await listCrmebOnePassWaybillTemplates({accessKey:this.env.CRMEB_ONEPASS_ACCESS_KEY,secretKey:this.env.CRMEB_ONEPASS_SECRET_KEY},{carrierCode:before.data.carrier.code,cloudPrinterConfigured:before.data.defaults.has_cloud_printer}));}catch(error){if(error instanceof WaybillConfigurationError)throw new ValidateException(error.message);if(error instanceof ApiException)throw error;throw new ApiException('电子面单模板服务暂不可用',502);}
    const fresh=await withCustomerWorkRead(this.container,actor,before.scope_key,async db=>({carrier:(await customerWorkCarriers(db)).find(c=>c.id===carrierId),defaults:await customerWorkDefaults(db)}));if(fresh.consistency_key!==before.consistency_key||JSON.stringify(fresh.data)!==JSON.stringify(before.data))throw new HttpApiException('发货配置或订单依据已变化，请重新读取',412,412);return{...fresh,data:{metric_scopes:CUSTOMER_WORK_METRIC_SCOPES,carrier_id:carrierId,list:catalog.data}};
  }
  private async reviewed(tx:DbClient,input:CustomerOperationInput,lock=true){const state=await customerWorkFulfillmentState(tx,this.env,input.order_id,'id',lock);if(state.order.id!==input.order_id||state.order_revision!==input.expected_order_revision||state.fulfillment_revision!==input.expected_fulfillment_revision)throw new HttpApiException('订单或履约依据已变化，请核对原请求',412,412);return state;}
  async saveRemark(ctx:CustomerOperationContext,value:unknown){const immutable=freezeCustomerJson(value) as unknown as CustomerOperationInput;return new CustomerWorkOperationRequest(this.container).execute('remark',ctx,immutable,async(tx,scope,order)=>{const target=await customerWorkRemarkTarget(tx,order.id,'id');if(target.order_revision!==immutable.expected_order_revision||target.fulfillment_revision!==immutable.expected_fulfillment_revision)throw new HttpApiException('原备注订单依据已变化，请重新核对',412,412);const body=record(immutable.payload);keys(body,['remark']);const remark=text(body.remark,'订单备注',512,false,true),changed=order.remark!==remark;if(changed){await tx.update(storeOrder).set({remark}).where(eq(storeOrder.id,order.id));await tx.insert(storeOrderStatus).values({oid:order.id,changeType:'customer_work_remark',changeMessage:`手机订单管理用户 ${scope.actor_uid}，服务 ${scope.service_id} 更新备注`,changeTime:Math.floor(Date.now()/1000)});}return{outcome:'remark-saved',evidence:{changed}};});}
  async delivery(ctx:CustomerOperationContext,value:unknown,split=false){
    const immutable=freezeCustomerJson(value) as unknown as CustomerOperationInput,kind=customerDeliveryKind(immutable.payload,split),cityKind=kind==='city_delivery'||kind==='city_split_delivery';
    const result=await new CustomerWorkOperationRequest(this.container).execute(kind,ctx,immutable,async(tx,scope,order,p):Promise<{outcome:CustomerOperationOutcome;evidence:Record<string,CustomerJson>}>=>{
      const parsed=parseCustomerDelivery(immutable.payload,split),state=await this.reviewed(tx,immutable),identity=state.identity,mode=cityKind?'city':kind.startsWith('electronic')?'electronic':split?'split':'manual';
      if(!state.city.schema_ready)throw new ValidateException('同城配送完整目录或运行权限尚未验收，请保留原操作核对');
      const authorityCarts=await assertCustomerFulfillmentReady(tx,state,mode);
      if(await new CustomerCityDeliveryService(createContainerFromDb(tx),this.env).blocking(tx,identity,true))throw new ValidateException('订单存在未结同城配送任务');
      const actor={actorType:'customer' as const,actorId:scope.actor_uid,serviceId:scope.service_id},binding={rootOrderId:state.root.id,orderId:order.id,storeId:order.storeId,supplierId:order.supplierId,uid:order.uid,rootStoreId:state.root.storeId,rootSupplierId:state.root.supplierId};
      if(kind.startsWith('electronic')){
        const job=await new OrderWaybillJobService(createContainerFromDb(tx),this.env).createCustomerInTransaction(tx,order.id,actor,{request_key:p.key,fulfillment_mode:split?'split':'whole',cart_ids:parsed.carts.map(c=>({cart_id:c.cartId,cart_num:c.cartNum})),carrier_id:parsed.payload.carrier_id,template_id:parsed.payload.express_temp_id,sender_name:parsed.payload.to_name,sender_phone:parsed.payload.to_tel,sender_address:parsed.payload.to_addr},binding);
        return{outcome:'provider-admitted',evidence:{waybill_job_id:job.job.id,waybill_request_hash:job.job.request_hash,waybill_cart_snapshot_hash:await customerWaybillCartSnapshotHash(authorityCarts),root_order_id:state.root.id,root_store_id:state.root.storeId,root_supplier_id:state.root.supplierId,order_id:order.id,store_id:order.storeId,supplier_id:order.supplierId,customer_uid:order.uid}};
      }
      if(cityKind){const admitted=await new CustomerCityDeliveryService(createContainerFromDb(tx),this.env).admitInTx(tx,{actor_uid:scope.actor_uid,service_id:scope.service_id,scope_key:scope.scope_key,actor_auth_version:p.actor.auth_version,actor_expires_at:p.actor.expires_at,request_key:p.key,request_hash:p.hash,identity,payload:{station_type:parsed.payload.station_type as 1|2,cargo_weight:String(parsed.payload.cargo_weight),delivery_remark:String(parsed.payload.delivery_remark)},cart_ids:parsed.carts.map(c=>({cart_id:c.cartId,cart_num:c.cartNum}))});return{outcome:'provider-admitted',evidence:{city_job_id:admitted.job_id,status:admitted.status,provider:admitted.provider,root_order_id:state.root.id,order_id:order.id,store_id:order.storeId,supplier_id:order.supplierId,customer_uid:order.uid}};}
      let delivery={deliveryType:'fictitious' as 'express'|'send'|'fictitious',deliveryName:'',deliveryCode:'',deliveryId:'',deliveryUid:0,fictitiousContent:''};
      if(parsed.payload.type===1){const carrierId=Number(parsed.payload.carrier_id);await acquireCustomerWorkCarrierLock(tx,carrierId);const[carrier]=await tx.select({name:expressCompany.name,code:expressCompany.code}).from(expressCompany).where(and(eq(expressCompany.id,carrierId),eq(expressCompany.isShow,1),eq(expressCompany.status,1))).limit(1);if(!carrier)throw new ValidateException('快递公司不存在或已停用');delivery={...delivery,deliveryType:'express',deliveryName:carrier.name,deliveryCode:carrier.code,deliveryId:String(parsed.payload.delivery_id)};}
      else if(parsed.payload.type===2){const uid=Number(parsed.payload.delivery_uid);await acquireCustomerWorkCourierLock(tx,uid);const agents=await tx.select({nickname:deliveryService.nickname,phone:deliveryService.phone}).from(deliveryService).innerJoin(user,eq(user.uid,deliveryService.uid)).where(and(eq(deliveryService.uid,uid),eq(deliveryService.type,0),eq(deliveryService.relationId,0),eq(deliveryService.status,1),eq(deliveryService.isDel,0),eq(user.status,1),eq(user.isDel,0),sql`${user.deleteTime} IS NULL`)).limit(2);if(agents.length!==1)throw new ValidateException('配送员已停用、身份重复或无效');const agent=agents[0];delivery={...delivery,deliveryType:'send',deliveryUid:uid,deliveryName:agent.nickname,deliveryId:agent.phone};}
      else delivery.fictitiousContent=String(parsed.payload.fictitious_content);
      assertManualOrderDeliveryType(order.productType,delivery.deliveryType);
      const options={expectedStoreId:order.storeId,expectedRootStoreId:state.root.storeId,authorize:async(_db:DbClient,actual:{requestedOrderId:number;rootOrderId:number;customerUid:number;supplierId:number})=>{if(actual.requestedOrderId!==identity.orderId||actual.rootOrderId!==identity.rootOrderId||actual.customerUid!==identity.customerUid||actual.supplierId!==identity.supplierId)throw new ValidateException('履约资源身份已变化');},audit:{changeType:split?'customer_work_split_delivery':'customer_work_delivery',changeMessage:`手机订单管理用户 ${scope.actor_uid}，服务 ${scope.service_id} 提交${split?'拆单':'整单'}履约`}},core=new SupplierFulfillmentService(createContainerFromDb(tx),this.env),deliveryResult=split?await core.splitDelivery(order.supplierId,order.id,delivery,parsed.carts,options):await core.deliver(order.supplierId,order.id,delivery,options);
      return{outcome:'delivery-recorded',evidence:{split:deliveryResult.split,order_id:deliveryResult.order_id,remaining_order_id:deliveryResult.remaining_order_id}};
    },cityKind?acquireCustomerCityAdmissionFence:undefined);
    if(!result.replayed&&result.receipt.outcome==='provider-admitted'){const e=result.receipt.evidence;if(typeof e.waybill_job_id==='number')try{await new OrderWaybillJobService(this.container,this.env).dispatchPending(1,undefined,[e.waybill_job_id]);}catch{}if(typeof e.city_job_id==='number')try{await new CustomerCityDeliveryService(this.container,this.env).postCommitDispatch(e.city_job_id);}catch{}}
    return result;
  }
}
