const test = require('node:test'), assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), crypto = require('node:crypto');
const ts = require('typescript'), vue = require('vue'), sfc = require('@vue/compiler-sfc');
const adminRoot = path.resolve(__dirname, '../src'), commonRoot = path.resolve(__dirname, '../../common');
const revision = 'a'.repeat(64), nextRevision = 'b'.repeat(64), id = n => `12345678-1234-4123-8123-${String(n).padStart(12, '0')}`;
const clone = value => JSON.parse(JSON.stringify(value)), tick = () => new Promise(resolve => setImmediate(resolve));
function deferred() { let resolve; const promise = new Promise(done => { resolve = done; }); return { promise, resolve }; }
function loader(gateway = {}) {
  const cache = new Map();
  function load(file) {
    file = path.resolve(file); if (!path.extname(file)) file += '.ts'; if (cache.has(file)) return cache.get(file);
    const exports = {}; cache.set(file, exports); let source = fs.readFileSync(file, 'utf8').replace(/import\.meta\.env\.DEV/g,'false');
    if (file.endsWith('.vue')) source = sfc.compileScript(sfc.parse(source, { filename:file }).descriptor, { id:'detail-design-runtime' }).content;
    const output = ts.transpileModule(source, { compilerOptions:{ target:ts.ScriptTarget.ES2022, module:ts.ModuleKind.CommonJS, esModuleInterop:true } }).outputText;
    new Function('require', 'exports', output)(name => {
      if (name === 'vue') return vue;
      if (name === '@/utils/request') return { __esModule:true, default:gateway, getData:async result => (await result).data };
      if (name.startsWith('@/')) return load(path.join(adminRoot, name.slice(2)));
      if (name.startsWith('.')) return load(path.resolve(path.dirname(file), name));
      return require(name);
    }, exports); return exports;
  }
  return { load };
}
function harness(overrides = {}, storage = new Map()) {
  const actual = loader(), model = actual.load(path.join(commonRoot, 'userCenterDesignController.ts')), shared = actual.load(path.join(commonRoot, 'userCenterDesign.ts'));
  let actor = { id:11,identity:'11:sessionA:view/manage',stored:'sessionA',view:true,manage:true }, sequence = 1;
  const records = { read:[],write:[],receipt:[],confirm:[] };
  const snapshot = (changes = {}) => ({ revision,value:shared.cloneUserCenterDesign(),configured:true,editable:true,issues:[],imagePreviews:{poster:[],menu:[],merMenu:[]},...changes });
  const receipt = async input => ({ operation:'update',id:9,operationId:input.operationId,payloadHash:await model.userCenterDesignFingerprint(input) });
  const memory = { getItem:key => storage.has(key) ? storage.get(key) : null,setItem:(key,value) => storage.set(key,value),removeItem:key => storage.delete(key) };
  const ports = {
    read:async signal => { records.read.push(signal); return snapshot(); },
    write:async (input,signal) => { records.write.push({ input:clone(input),signal }); return receipt(input); },
    receipt:async (operationId,signal) => { records.receipt.push({ operationId,signal }); throw notFound(); },
    confirm:async message => { records.confirm.push(message); },storage:memory,uuid:() => id(sequence++),...overrides,
  };
  const c = new model.UserCenterDesignController(() => actor,ports,value => vue.reactive(value));
  return { c,model,shared,ports,records,storage,snapshot,receipt,actual,setActor:value => { actor = { ...actor,...value }; } };
}
const notFound = () => ({ isAxiosError:true,response:{ status:404,data:{ status:404,msg:'not found' } } });
function proof(status,pending,changes = {}) { return { isAxiosError:true,response:{ status,data:{ status,msg:'explicit rejection',data:{ code:status === 409 ? 'USER_CENTER_DESIGN_STALE_VERSION' : 'USER_CENTER_DESIGN_REJECTED',operation:'update',operationId:pending.input.operationId,payloadHash:pending.fingerprint,...changes } } } }; }

const row=(number,name='入口')=>({sourceId:String(number).repeat(64),name,pic:'/images/test.png',url:'/pages/user/index'});
test('actual diagnostics explain conflicting shared data and preserve retired entry boundaries',()=>{const actual=loader().load(path.join(adminRoot,'utils/userCenterDesignDiagnostics.ts'));assert(actual.userCenterDesignIssueLabel('user_center_poster_group_disagreement').includes('确认保存会按本页列表同步'));assert(actual.userCenterDesignIssueLabel('user_center_merMenu_historical_target_partial').includes('旧入口'));assert(actual.userCenterDesignIssueLabel('user_center_member_duplicate').includes('多条'));assert.equal(actual.userCenterDesignIssueLabel('unknown_code'),'诊断：unknown_code');});
test('read signed previews reject credentials and protocol-relative or encoded dangerous paths',()=>{const r=harness(),v=r.shared.cloneUserCenterDesign();v.poster.list=[row(1)];for(const pic of ['https://name:secret@cdn.test/a.png','//evil.test/a.png','/%2f/evil','/api/a\\b'])assert.throws(()=>r.model.parseUserCenterDesignSnapshot({...listSnapshot(r,v),imagePreviews:{poster:[pic],menu:[],merMenu:[]}}),pic);r.c.dispose();});
function listSnapshot(r,value){return r.snapshot({value,imagePreviews:Object.fromEntries(['poster','menu','merMenu'].map(key=>[key,value[key].list.map(()=>'/api/assets/test.png')]))});}
test('real default six modules retain video ordinal4 and read without initialization',async()=>{const r=harness({read:async()=>r.snapshot({configured:false,issues:['member_missing']})});await r.c.activate();assert.equal(Object.keys(r.c.state.draft).length,6);assert.deepEqual(clone(r.c.state.draft.member.property),[0,1,2,3,4]);assert.equal(r.c.state.draft.merMenu.title,'商家管理');assert.equal(r.records.write.length,0);r.c.dispose();});
test('strict nested model rejects aliases coercion duplicate selections bad type and exceeded ranges',()=>{const r=harness(),v=r.shared.cloneUserCenterDesign();for(const patch of [{member:{...v.member,style:6}},{member:{...v.member,property:[0,0]}},{member:{...v.member,property:[9]}},{member:{...v.member,style:2,property:[0,1,2,3]}},{order:{style:4}},{orderStatic:{style:2,is_show:true}},{menu:{...v.menu,title:''}},{poster:{...v.poster,list:Array(11).fill({...row(1),sourceId:null})}},{menu:{...v.menu,list:[{...row(1),type:2}]}},{merMenu:{...v.merMenu,list:[{...row(1),type:1}]}},{extra:1}])assert.throws(()=>r.model.normalizeUserCenterDesignWrite({operationId:id(1),revision,value:{...v,...patch}}));assert.throws(()=>r.model.normalizeUserCenterDesignWrite({operationId:'bad',revision,value:v}));r.c.dispose();});
test('read DTO requires ordered matching signed previews and rejects malformed envelopes',()=>{const r=harness(),v=r.shared.cloneUserCenterDesign();v.poster.list=[row(1)];assert.doesNotThrow(()=>r.model.parseUserCenterDesignSnapshot(listSnapshot(r,v)));for(const patch of [{imagePreviews:{poster:[],menu:[],merMenu:[]}},{imagePreviews:{poster:['javascript:evil'],menu:[],merMenu:[]}},{value:null,editable:true},{issues:['bad\nissue']},{extra:1}])assert.throws(()=>r.model.parseUserCenterDesignSnapshot({...listSnapshot(r,v),...patch}));assert.doesNotThrow(()=>r.model.parseUserCenterDesignSnapshot(r.snapshot({value:null,editable:false})));r.c.dispose();});
test('form edits own nested arrays and do not mutate defaults incoming reads or current snapshot',async()=>{const r=harness(),incoming=r.snapshot();r.ports.read=async()=>incoming;await r.c.activate();r.c.toggleProperty(4,false);assert.deepEqual(incoming.value.member.property,[0,1,2,3,4]);assert.deepEqual(clone(r.c.state.snapshot.value.member.property),[0,1,2,3,4]);assert.deepEqual(r.shared.USER_CENTER_DESIGN_DEFAULT.member.property,[0,1,2,3,4]);r.c.dispose();});
test('all six modules accept true fields while out of range editing retains previous draft',async()=>{const r=harness();await r.c.activate();assert.equal(r.c.edit(v=>{v.member={style:5,property:[8,6,4],per_show_type:1};v.order.style=3;v.orderStatic={style:2,is_show:0};v.poster.is_show=0;v.menu={title:'服务',style:2,is_show:0,list:[{...row(1),type:1}]};v.merMenu.style=3;}),true);const wanted=clone(r.c.state.draft);assert.equal(r.c.edit(v=>{v.member.style=8;}),false);assert.deepEqual(clone(r.c.state.draft),wanted);r.c.dispose();});
test('list order deletion and hidden modules retain exact canonical values and source IDs',async()=>{const r=harness(),v=r.shared.cloneUserCenterDesign();v.poster.list=[row(1,'一'),row(2,'二')];v.menu.list=[{...row(3),type:1}];r.ports.read=async()=>listSnapshot(r,v);await r.c.activate();r.c.move('poster',1,-1);r.c.remove('menu',0);r.c.edit(x=>{x.poster.is_show=0;});await r.c.save();assert.deepEqual(r.records.write[0].input.value.poster.list.map(x=>x.name),['二','一']);assert.equal(r.records.write[0].input.value.poster.is_show,0);assert.equal(r.records.write[0].input.value.menu.list.length,0);r.c.dispose();});
test('merchant targets cannot be added removed reassigned or promoted through a tampered draft',async()=>{for(const change of ['add','remove','url','type']){const r=harness(),v=r.shared.cloneUserCenterDesign();v.merMenu.list=[{...row(1),type:2,url:'/pages/admin/order_cancellation/index'}];r.ports.read=async()=>listSnapshot(r,v);await r.c.activate();if(change==='add')r.c.state.draft.merMenu.list.push({...row(2),type:2});if(change==='remove')r.c.state.draft.merMenu.list=[];if(change==='url')r.c.state.draft.merMenu.list[0].url='/pages/admin/work/index';if(change==='type')r.c.state.draft.merMenu.list[0].type=1;await r.c.save();assert.equal(r.records.write.length,0,change);r.c.dispose();}});
test('merchant names pics and reorder can be saved while fixed target set is preserved',async()=>{const r=harness(),v=r.shared.cloneUserCenterDesign();v.merMenu.list=[{...row(1,'核销'),type:2,url:'/pages/admin/order_cancellation/index'},{...row(2,'配送'),type:2,url:'/pages/admin/distribution/index'}];r.ports.read=async()=>listSnapshot(r,v);await r.c.activate();r.c.move('merMenu',1,-1);r.c.edit(x=>{x.merMenu.list[0].name='我的配送';x.merMenu.list[0].pic='/images/delivery.png';});await r.c.save();assert.equal(r.records.write[0].input.value.merMenu.list[0].name,'我的配送');assert.equal(r.records.write[0].input.value.merMenu.list[0].url,'/pages/admin/distribution/index');r.c.dispose();});
test('digest binds all lists and order but intentionally excludes operation UUID',async()=>{const r=harness(),v=r.shared.cloneUserCenterDesign();v.poster.list=[row(1),row(2)];const input={operationId:id(1),revision,value:v},hash=await r.model.userCenterDesignFingerprint(input);assert.equal(hash,crypto.createHash('sha256').update(JSON.stringify(r.shared.userCenterDesignPayload(revision,v))).digest('hex'));assert.equal(hash,await r.model.userCenterDesignFingerprint({...input,operationId:id(2)}));v.poster.list.reverse();assert.notEqual(hash,await r.model.userCenterDesignFingerprint(input));r.c.dispose();});
test('cancelled confirmation submits and persists nothing',async()=>{const r=harness({confirm:async()=>{throw Error('cancel');}});await r.c.activate();r.c.edit(v=>{v.menu.title='取消草稿';});await r.c.save();assert.equal(r.records.write.length,0);assert.equal(r.storage.size,0);assert.equal(r.c.state.draft.menu.title,'取消草稿');r.c.dispose();});
test('actual shared disagreement is included in the final operator confirmation',async()=>{const r=harness();r.ports.read=async()=>r.snapshot({issues:['user_center_menu_group_disagreement']});await r.c.activate();await r.c.save();assert(r.records.confirm[0].includes('按本页列表同步广告和菜单组'));assert(r.records.confirm[0].includes('额外共享项停用并原样保留'));r.c.dispose();});
test('successful matched receipt clears only current operation and rereads authority',async()=>{const r=harness();await r.c.activate();r.c.edit(v=>{v.order.style=3;});await r.c.save();assert.equal(r.records.write.length,1);assert.equal(r.c.state.pending,null);assert.equal(r.storage.size,0);assert.equal(r.records.read.length,2);r.c.dispose();});
test('unknown response keeps deeply frozen full lists and prevents repeated writes',async()=>{const r=harness({write:async()=>{throw Error('lost reply');}}),v=r.shared.cloneUserCenterDesign();v.poster.list=[row(1)];r.ports.read=async()=>listSnapshot(r,v);await r.c.activate();await r.c.save();const pending=r.c.state.pending;assert(Object.isFrozen(pending.input.value.poster.list[0]));const original=clone(pending);r.c.state.draft.poster.list[0].name='later edit';await r.c.save();assert.deepEqual(clone(r.c.state.pending),original);assert.equal(r.records.write.length,0);assert.equal(r.c.editorDisabled,true);r.c.dispose();});
test('refresh restores unknown original request without automatic post or new source mapping',async()=>{const r=harness({write:async()=>{throw Error('lost');}});await r.c.activate();r.c.edit(v=>{v.order.style=3;});await r.c.save();const pending=clone(r.c.state.pending);r.c.dispose();const fresh=harness({},r.storage);await fresh.c.activate();assert.deepEqual(clone(fresh.c.state.pending),pending);assert.equal(fresh.records.write.length,0);assert.equal(fresh.c.editorDisabled,true);fresh.c.dispose();});
test('only actual receipt404 enables explicit unchanged UUID revision list retry',async()=>{const r=harness({write:async()=>{throw Error('lost');}});await r.c.activate();await r.c.save();const pending=clone(r.c.state.pending);await r.c.retryOriginal();assert.equal(r.records.confirm.length,1);await r.c.readReceipt();assert.equal(r.c.state.retryReady,true);let retried;r.ports.write=async input=>{retried=clone(input);return r.receipt(input);};await r.c.retryOriginal();assert.deepEqual(retried,pending.input);assert.equal(r.c.state.pending,null);r.c.dispose();});
test('foreign malformed receipt business404 or failed network never clear an unknown original',async()=>{for(const variant of ['business404','network','uuid','hash','extra']){const r=harness({write:async()=>{throw Error('unknown');}});await r.c.activate();await r.c.save();const pending=clone(r.c.state.pending);r.ports.receipt=async()=>{if(variant==='network')throw Error('timeout');if(variant==='business404')throw{isAxiosError:true,response:{status:200,data:{status:404}}};const receipt=await r.receipt(pending.input);if(variant==='uuid')receipt.operationId=id(90);if(variant==='hash')receipt.payloadHash='e'.repeat(64);if(variant==='extra')receipt.extra=1;return receipt;};await r.c.readReceipt();assert.deepEqual(clone(r.c.state.pending),pending,variant);assert.equal(r.c.state.retryReady,false,variant);r.c.dispose();}});
test('view-only current actor recovers successful receipt without edit permission',async()=>{const r=harness({write:async()=>{throw Error('unknown');}});await r.c.activate();await r.c.save();const pending=clone(r.c.state.pending);r.c.dispose();const fresh=harness({},r.storage);fresh.setActor({manage:false});fresh.ports.receipt=async()=>fresh.receipt(pending.input);await fresh.c.activate();await fresh.c.readReceipt();assert.equal(fresh.storage.size,0);assert.equal(fresh.c.editorDisabled,true);assert.equal(fresh.records.write.length,0);fresh.c.dispose();});
test('matching rollback proofs preserve draft and require new current revision and explicit confirmation',async()=>{for(const status of [400,409]){const r=harness();await r.c.activate();r.c.edit(v=>{v.order.style=3;});r.ports.write=async()=>{throw proof(status,r.c.state.pending);};await r.c.save();const rejected=clone(r.c.state.rejected);assert.equal(r.c.state.pending,null);assert.equal(r.c.state.needsReread,true);r.ports.read=async()=>r.snapshot({revision:nextRevision});await r.c.reread();assert.equal(r.c.state.draft.order.style,3);assert.equal(r.c.state.needsReread,false);let posted;r.ports.write=async input=>{posted=clone(input);return r.receipt(input);};await r.c.save();assert.equal(posted.revision,nextRevision);assert.notEqual(posted.operationId,rejected.input.operationId);assert.equal(posted.value.order.style,3);r.c.dispose();}});
test('bare or mismatched rejection cannot erase unknown request',async()=>{for(const variant of ['bare','status','operation','operationId','payloadHash','code']){const r=harness();await r.c.activate();r.ports.write=async()=>{if(variant==='bare')throw{isAxiosError:true,response:{status:409,data:{status:409}}};const failure=proof(409,r.c.state.pending);if(variant==='status')failure.response.status=200;else failure.response.data.data[variant]='foreign';throw failure;};await r.c.save();assert(r.c.state.pending,variant);assert.equal(r.c.state.rejected,null);r.c.dispose();}});
test('reread remaps unchanged unique source identity without silently choosing changed rows',async()=>{const r=harness(),v=r.shared.cloneUserCenterDesign();v.poster.list=[row(1,'old')];r.ports.read=async()=>listSnapshot(r,v);await r.c.activate();r.c.edit(x=>{x.poster.list[0].name='draft';});const current=clone(v);current.poster.list[0].sourceId='2'.repeat(64);r.ports.read=async()=>({...listSnapshot(r,current),revision:nextRevision});await r.c.reread();assert.equal(r.c.state.draft.poster.list[0].sourceId,'2'.repeat(64));assert.equal(r.c.state.draft.poster.list[0].name,'draft');assert.equal(r.c.state.needsReread,false);current.poster.list[0]={...row(3,'changed')};await r.c.reread();assert.equal(r.c.state.needsReread,true);assert.equal(r.c.state.draft.poster.list[0].name,'draft');await r.c.save();assert.equal(r.records.write.length,0);await r.c.adoptCurrent();assert.equal(r.c.state.draft.poster.list[0].name,'changed');assert.equal(r.c.state.needsReread,false);r.c.dispose();});
test('source correspondence ambiguity keeps original and blocks save until current config is adopted',async()=>{const r=harness(),v=r.shared.cloneUserCenterDesign();v.poster.list=[row(1)];r.ports.read=async()=>listSnapshot(r,v);await r.c.activate();const current=clone(v);current.poster.list=[row(2),row(3)];r.ports.read=async()=>listSnapshot(r,current);await r.c.reread();assert.equal(r.c.state.draft.poster.list[0].sourceId,'1'.repeat(64));assert.equal(r.c.state.needsReread,true);r.c.dispose();});
test('reread failure retains edited lists while disabling save until a successful read',async()=>{const r=harness();await r.c.activate();r.c.edit(v=>{v.menu.title='我的草稿';});r.ports.read=async()=>{throw Error('offline');};await r.c.reread();await r.c.save();assert.equal(r.c.state.draft.menu.title,'我的草稿');assert.equal(r.c.state.ready,false);assert.equal(r.records.write.length,0);r.c.dispose();});
test('storage denial corrupt and tampered journals cannot permit unrecorded posts',async()=>{const r=harness();await r.c.activate();r.ports.storage.setItem=()=>{throw Error('denied');};await r.c.save();assert.equal(r.records.write.length,0);r.c.dispose();const bad=harness({},new Map([['admin_user_center_design_pending:11','corrupt']]));await bad.c.activate();assert(bad.c.state.recoveryError);assert.equal(bad.storage.size,1);bad.c.dispose();});
test('actor session view revocation and disposal abort and fence delayed reads',async()=>{for(const variant of ['actor','stored','view','dispose']){const r=harness(),gate=deferred();let signal;r.ports.read=async value=>{signal=value;return gate.promise;};const task=r.c.activate();await tick();if(variant==='actor')r.setActor({id:22,identity:'new'});if(variant==='stored')r.setActor({stored:'new'});if(variant==='view')r.setActor({view:false});if(variant==='dispose')r.c.dispose();else r.c.invalidate();assert.equal(signal.aborted,true);gate.resolve(r.snapshot());await task;assert.equal(r.c.state.snapshot,null);r.c.dispose();}});
test('late confirmation write receipt never update another actor or remove original actor journal',{timeout:10000},async()=>{for(const channel of ['confirm','write','receipt']){const r=harness(),gate=deferred(),started=deferred();let task,signal,input;await r.c.activate();if(channel==='confirm'){r.ports.confirm=()=>{started.resolve();return gate.promise;};task=r.c.save();}else if(channel==='write'){r.ports.write=(value,requestSignal)=>{input=clone(value);signal=requestSignal;started.resolve();return gate.promise;};task=r.c.save();}else{r.ports.write=async()=>{throw Error('unknown');};await r.c.save();input=clone(r.c.state.pending.input);r.ports.receipt=(_,requestSignal)=>{signal=requestSignal;started.resolve();return gate.promise;};task=r.c.readReceipt();}await started.promise;r.setActor({id:22,identity:'22',stored:'new',view:false,manage:false});r.c.invalidate();if(signal)assert.equal(signal.aborted,true);gate.resolve(channel==='confirm'?undefined:await r.receipt(input));await task;assert.equal(r.c.state.success,false);assert.equal(r.storage.has(r.model.userCenterDesignPendingKey(11)),channel!=='confirm');assert.equal(r.storage.has(r.model.userCenterDesignPendingKey(22)),false);r.c.dispose();}});
test('manage permission revoked during confirmation cannot POST',async()=>{const r=harness(),gate=deferred(),started=deferred();await r.c.activate();r.ports.confirm=()=>{started.resolve();return gate.promise;};const task=r.c.save();await started.promise;r.setActor({manage:false});gate.resolve();await task;assert.equal(r.storage.size,0);assert.equal(r.records.write.length,0);r.c.dispose();});
test('actual API binds exact design selector paths full value receipt and signals',async()=>{const r=harness(),input={operationId:id(1),revision,value:r.shared.cloneUserCenterDesign()},result=await r.receipt(input),calls=[],gateway={get:async(url,options)=>{calls.push({url,options});return{data:url.includes('/receipt/')?result:r.snapshot()};},post:async(url,body,options)=>{calls.push({url,body,options});return{data:result};}};const api=loader(gateway).load(path.join(adminRoot,'api/userCenterDesign.ts')),signal=new AbortController().signal;await api.apiUserCenterDesign(signal);await api.apiSaveUserCenterDesign(input,signal);await api.apiUserCenterDesignReceipt(input.operationId,signal);assert.deepEqual(calls.map(x=>x.url),['/config/user-center-design','/config/user-center-design/save',`/config/user-center-design/receipt/${id(1)}`]);assert(calls.every(x=>x.options.signal===signal));assert.deepEqual(clone(calls[1].body),input);await assert.rejects(api.apiUserCenterDesignReceipt('../other'));r.c.dispose();});
test('actual asset DTO rejects unexpected count identities dangerous previews and credentials',()=>{const api=loader({}).load(path.join(adminRoot,'api/userCenterDesign.ts')),good={list:[{id:1,name:'图片',canonical_url:'/images/a.png',preview_url:'https://cdn.test/image.png?sig=a'}],count:1,page:1,limit:20};assert.doesNotThrow(()=>api.parseUserCenterAssets(good,1,20));for(const patch of [{count:0},{page:2},{list:[{...good.list[0],preview_url:'javascript:alert(1)'}]},{list:[{...good.list[0],preview_url:'https://user:password@cdn.test/img.png'}]},{list:[{...good.list[0],canonical_url:'//evil.test/img.png'}]},{list:[good.list[0],good.list[0]],count:2}])assert.throws(()=>api.parseUserCenterAssets({...good,...patch},1,20));});
test('actual compiled preview renders six modules all five member styles and three list styles',async()=>{const file=path.join(adminRoot,'pages/setting/UserCenterDesignPreview.vue'),actual=loader(),component=actual.load(file).default,shared=actual.load(path.join(commonRoot,'userCenterDesign.ts')),descriptor=sfc.parse(fs.readFileSync(file,'utf8'),{filename:file}).descriptor,script=sfc.compileScript(descriptor,{id:'user-center-preview-ssr'});component.render=new Function('Vue',require('@vue/compiler-dom').compile(descriptor.template.content,{mode:'function',prefixIdentifiers:true,bindingMetadata:script.bindings}).code)(vue);const render=value=>require('@vue/server-renderer').renderToString(vue.createSSRApp(component,{value,active:'member',image:()=>'/images/test.png'}));for(let style=1;style<=5;style++){const value=shared.cloneUserCenterDesign();value.member.style=style;value.member.property=style===1?[0,1,2,3,4]:[0,4,8];value.poster.list=[row(1,'广告')];value.menu.list=[{...row(2,'我的服务项'),type:1}];value.merMenu.list=[{...row(3,'商家项'),type:2}];const html=await render(value);for(const key of shared.USER_CENTER_DESIGN_KEYS)assert(html.includes(`data-testid="user-center-preview-${key}"`));assert(html.includes(`member-style-${style}`));if(style===3)assert(html.includes('SVIP'));if(style===4)assert(html.includes('累计佣金'));}for(let style=1;style<=3;style++){const value=shared.cloneUserCenterDesign();value.menu.style=style;value.menu.list=[{...row(1),type:1}];assert((await render(value)).includes(`menu-style-${style}`));}});
test('all real SFC templates compile with precise permission alias runtime hooks and immutable merchant UI',()=>{for(const name of ['UserCenterDesign.vue','UserCenterDesignPreview.vue','UserCenterDesignPicker.vue']){const file=path.join(adminRoot,'pages/setting',name),parsed=sfc.parse(fs.readFileSync(file,'utf8'),{filename:file});assert.deepEqual(parsed.errors,[]);const script=sfc.compileScript(parsed.descriptor,{id:'user-center-sfc'});assert.deepEqual(sfc.compileTemplate({source:parsed.descriptor.template.content,filename:file,id:'user-center-sfc',compilerOptions:{bindingMetadata:script.bindings}}).errors,[]);}const page=fs.readFileSync(path.join(adminRoot,'pages/setting/UserCenterDesign.vue'),'utf8');for(const word of ['user_center_design.view','user_center_design.manage','admin-session-changed','user-center-rejected-intent','user-center-historical-video','controller.editorDisabled'])assert(page.includes(word));const routes=fs.readFileSync(path.join(adminRoot,'router/index.ts'),'utf8');assert(routes.includes('alias: "/admin/setting/pages/home"'));});

