/** Legacy promotion definitions referenced by order-level promotion allocations. */
import { decimal, index, integer, pgTable, serial, smallint, text, varchar } from "drizzle-orm/pg-core";

export const storePromotions = pgTable(
  "store_promotions",
  {
    id: serial("id").primaryKey(),
    pid: integer("pid").default(0).notNull(),
    type: smallint("type").default(1).notNull(),
    storeId: integer("store_id").default(0).notNull(),
    promotionsType: smallint("promotions_type").default(1).notNull(),
    promotionsCate: smallint("promotions_cate").default(1).notNull(),
    name: varchar("name", { length: 255 }).default("").notNull(),
    title: varchar("title", { length: 255 }).default("").notNull(),
    image: varchar("image", { length: 255 }).default("").notNull(),
    description: text("desc"),
    thresholdType: smallint("threshold_type").default(1).notNull(),
    threshold: decimal("threshold", { precision: 12, scale: 2 }).default("0.00").notNull(),
    discountType: smallint("discount_type").default(1).notNull(),
    nPieceNDiscount: smallint("n_piece_n_discount").default(1).notNull(),
    discount: decimal("discount", { precision: 12, scale: 2 }).default("0.00").notNull(),
    giveIntegral: integer("give_integral").default(0).notNull(),
    giveCouponId: text("give_coupon_id"),
    giveProductId: text("give_product_id"),
    giveProductUnique: text("give_product_unique"),
    overlay: varchar("overlay", { length: 255 }).default("").notNull(),
    labelId: text("label_id"),
    productPartakeType: smallint("product_partake_type").default(0).notNull(),
    productId: text("product_id"),
    isLimit: smallint("is_limit").default(0).notNull(),
    limitNum: integer("limit_num").default(0).notNull(),
    startTime: integer("start_time").default(0).notNull(),
    stopTime: integer("stop_time").default(0).notNull(),
    sort: smallint("sort").default(0).notNull(),
    status: smallint("status").default(1).notNull(),
    isDel: smallint("is_del").default(0).notNull(),
    updateTime: integer("update_time").default(0).notNull(),
    addTime: integer("add_time").default(0).notNull(),
  },
  (t) => [
    index("sp_parent").on(t.pid),
    index("sp_owner").on(t.type, t.storeId),
    index("sp_type").on(t.promotionsType),
    index("sp_update_time").on(t.updateTime),
    index("sp_active_window").on(t.pid, t.status, t.isDel, t.startTime, t.stopTime),
  ],
);

export const storePromotionsAuxiliary = pgTable(
  "store_promotions_auxiliary",
  {
    id: serial("id").primaryKey(),
    type: smallint("type").default(1).notNull(),
    promotionsId: integer("promotions_id").default(0).notNull(),
    productPartakeType: smallint("product_partake_type").default(1).notNull(),
    productId: integer("product_id").default(0).notNull(),
    couponId: integer("coupon_id").default(0).notNull(),
    brandId: integer("brand_id").default(0).notNull(),
    storeLabelId: integer("store_label_id").default(0).notNull(),
    limitNum: integer("limit_num").default(0).notNull(),
    surplusNum: integer("surplus_num").default(0).notNull(),
    isAll: smallint("is_all").default(1).notNull(),
    unique: text("unique"),
  },
  (t) => [
    index("spa_promotion_product").on(t.promotionsId, t.productId),
    index("spa_promotion_type_product").on(t.promotionsId, t.type, t.productId),
    index("spa_promotion_type_brand").on(t.promotionsId, t.type, t.brandId),
    index("spa_promotion_type_label").on(t.promotionsId, t.type, t.storeLabelId),
  ],
);
