import { and,asc,desc,eq,getTableColumns,gte,ilike,inArray,or,sql,type SQL } from 'drizzle-orm';
import { createContainerFromDb,type Container,type DbClient } from '@/lib/di';
import type { Env } from '@/env';
import { storeOrder,storeOrderCartInfo,storeOrderRefund,storeOrderInvoice,storeOrderPromotions,storePromotions,storeCouponIssue,storePink,systemUserLevel,user,systemStore,systemAttachment,expressCompany,deliveryService,storeConfig } from '@/models/schema';
import { orderProjection,cartProjection } from '@/services/kefu/KefuOrderService';
import { publicProductPictures,renderProductPictures } from '@/services/activity/ProductAssetPolicy';
import { parseCanonicalAttachmentId } from '@/services/system/AttachmentService';
import { fabImage } from '@/services/admin/AdminFabSettingsInput';
import { orderCancelHours } from '@/services/payment/OrderPaymentPolicy';
import { ExpressService,type ExpressQueryResult } from '@/services/order/ExpressService';
import { normalizeConfigScalar } from '@/utils/config';
import { CityDeliverySettingsResolver } from '@/services/delivery/CityDeliverySettingsResolver';
import { orderReadStatusPredicate } from '@/services/order/OrderReadStatusPredicate';
import { loadRefundOrderGeneration,currentGenerationRefunds } from '@/services/order/RefundOrderGeneration';
import { readRefundGenerationMarker } from '@/services/order/RefundGenerationMarker';
import { refundOrderSplitFingerprint } from '@/services/order/RefundOrderSplitIdentity';
import { storeOrderRefundSplit } from '@/models/schema/order_refund_split';
import { NotFoundException,ValidateException } from '@/utils/errors';
import { managerId,merchantOrderRevision,type StoreManagerScope } from './StoreManagerScope';
import { parseManagerListQuery,parseManagerStoreQuery,managerOrderNumber,type ManagerListQuery } from './StoreManagerOrderInput';
import { withManagerRead,managerCount,managerMoney } from './StoreManagerOrderStatisticsService';
import type { MerchantOrderActions,MerchantOrderListItem,MerchantOrderDetail,MerchantOrderCart,MerchantManagementEnvelope,MerchantPaged,MerchantDeliveryDefaults,MerchantDeliveryAgent,MerchantCarrier } from '../../../../view/common/merchantManagement';

type Order=typeof storeOrder.$inferSelect;
type Cart=typeof storeOrderCartInfo.$inferSelect;
type Refund=typeof storeOrderRefund.$inferSelect;
export type ManagerOrderActionReader=(db:DbClient,scope:StoreManagerScope,order:Order)=>Promise<Partial<MerchantOrderActions>>;
export function unavailableManagerOrderActions():MerchantOrderActions{return Object.fromEntries(['remark','change_price','confirm_offline','manual_delivery','split_delivery','electronic_waybill','refund_create','refund_decide','tracking','writeoff'].map(key=>[key,{available:false,reason:'该操作尚无当前门店的完整执行合同'}])) as MerchantOrderActions;}
const orderColumns=getTableColumns(storeOrder),orderTextKeys=['cartId','virtualInfo','customForm','promotionsGive','giveCoupon','expressDump','refundReasonWapImg'] as const;
const bytes=sql`(${sql.join(orderTextKeys.map(key=>sql`COALESCE(octet_length(${orderColumns[key]})::bigint,0)`),sql`+`)})`;
const boundedOrder={...orderColumns,...Object.fromEntries(orderTextKeys.map(key=>[key,sql<string|null>`CASE WHEN ${bytes}<=262144 THEN ${orderColumns[key]} ELSE NULL END`])),oversized:sql<boolean>`${bytes}>262144`} as typeof orderColumns&{oversized:SQL<boolean>};
function checkedOrder(row:Order&{oversized:boolean}):Order{if(row.oversized)throw new ValidateException('订单数据过大，请先完成数据核对');const{oversized:_oversized,...order}=row;return order;}
function text(value:unknown,max=512){return typeof value==='string'?value.slice(0,max):'';}
function json(value:string|null,label:string):unknown[]|Record<string,unknown>|null{if(!value)return null;try{const parsed:unknown=JSON.parse(value);if(parsed&&typeof parsed==='object')return parsed as unknown[]|Record<string,unknown>;}catch{}throw new ValidateException(`${label}无法读取，请先核对历史数据`);}
function moneyCart(row:Cart):MerchantOrderCart{const projected=cartProjection(row);return{...projected,split_surplus_num:row.splitSurplusNum,is_writeoff:row.isWriteoff,write_times:row.writeTimes,write_surplus_times:row.writeSurplusTimes,write_start:row.writeStart,write_end:row.writeEnd,
  ...Object.fromEntries(['truePrice','vip_truePrice','vip_sum_truePrice','sum_true_price','postage_price','coupon_price','integral_price','promotions_true_price'].map(key=>[key,managerMoney(projected[key as keyof typeof projected])])),productInfo:{...projected.productInfo,price:managerMoney(projected.productInfo.price),attrInfo:{...projected.productInfo.attrInfo,price:managerMoney(projected.productInfo.attrInfo.price)}}} as MerchantOrderCart;}
async function orderUserPictures(db:DbClient,uid:number,values:unknown[]):Promise<string[]>{
  if(values.length>40)throw new ValidateException('订单图片超过安全读取容量');
  const refs=values.map(value=>{try{return value?fabImage(value):'';}catch{return '';}}),ids=[...new Set(refs.map(parseCanonicalAttachmentId).filter((id):id is number=>id!==null))];
  const assets=ids.length?await db.select().from(systemAttachment).where(inArray(systemAttachment.attId,ids)):[],byId=new Map(assets.map(row=>[row.attId,row]));
  const fallback=await publicProductPictures(db,refs.map(image=>({image,type:0,relationId:0})));
  return refs.map((ref,index)=>{const id=parseCanonicalAttachmentId(ref);if(id===null)return fallback[index];const asset=byId.get(id);return asset?.type===3&&asset.relationId===uid&&asset.moduleType===3&&asset.fileType===1&&asset.imageType===8&&asset.attDir===ref&&asset.name.startsWith(`attachments/user/${uid}/`)&&!/[\\\u0000-\u001f\u007f]/u.test(asset.name)&&!asset.name.split('/').some(piece=>piece==='.'||piece==='..')&&/\.(?:jpe?g|png|gif|webp)$/i.test(asset.name)&&/^image\/(?:jpeg|jpg|png|gif|webp)$/i.test(asset.attType.trim())?ref:fallback[index];});
}
function pictureList(value:string|null,label:string):unknown[]{if(!value)return[];let parsed:unknown;try{parsed=JSON.parse(value);}catch{throw new ValidateException(`${label}历史数据格式无效`);}if(!Array.isArray(parsed)||parsed.length>20||parsed.some(item=>typeof item!=='string'))throw new ValidateException(`${label}历史数据格式无效`);return parsed;}
function couponIds(value:string|null):number[]{if(!value)return[];let input:unknown=value.split(',');if(value.trim().startsWith('[')){try{input=JSON.parse(value);}catch{throw new ValidateException('赠送优惠券历史数据异常');}}if(!Array.isArray(input)||input.length>100)throw new ValidateException('赠送优惠券历史数据异常');const ids=input.filter(value=>value!=='').map(value=>managerId(value,'赠送优惠券'));if(new Set(ids).size!==ids.length)throw new ValidateException('赠送优惠券历史数据异常');return ids;}

export class StoreManagerOrderReadService{
  constructor(private readonly container:Container,private readonly env:Env,private readonly actionReader:ManagerOrderActionReader=async()=>({})){}
  private async orderByNumber(db:DbClient,scope:StoreManagerScope,value:unknown):Promise<Order>{const number=managerOrderNumber(value),rows=await db.select(boundedOrder).from(storeOrder).where(and(eq(storeOrder.orderId,number),eq(storeOrder.storeId,scope.store_id),eq(storeOrder.isSystemDel,0),eq(storeOrder.isDel,0))).orderBy(asc(storeOrder.id)).limit(2);if(rows.length!==1)throw new NotFoundException('订单不存在、编号重复或不属于当前门店');return checkedOrder(rows[0]);}
  private async orderById(db:DbClient,scope:StoreManagerScope,value:unknown):Promise<Order>{const id=managerId(value,'订单'),rows=await db.select(boundedOrder).from(storeOrder).where(and(eq(storeOrder.id,id),eq(storeOrder.storeId,scope.store_id),eq(storeOrder.isSystemDel,0),eq(storeOrder.isDel,0))).limit(1);if(!rows[0])throw new NotFoundException('订单不存在或不属于当前门店');return checkedOrder(rows[0]);}
  private async associations(db:DbClient,orders:Order[]){
    if(!orders.length)return{carts:[] as Cart[],refunds:[] as Refund[],byOrder:new Map<number,Refund[]>()};const ids=orders.map(row=>row.id),byId=new Map(orders.map(row=>[row.id,row]));
    const cartBytes=sql`COALESCE(octet_length(${storeOrderCartInfo.cartInfo})::bigint,0)`,carts=await db.select({...getTableColumns(storeOrderCartInfo),cartInfo:sql<string|null>`CASE WHEN ${cartBytes}<=65536 AND sum(${cartBytes}) OVER()<=1048576 THEN ${storeOrderCartInfo.cartInfo} ELSE NULL END`,oversized:sql<boolean>`${cartBytes}>65536 OR sum(${cartBytes}) OVER()>1048576`}).from(storeOrderCartInfo).where(inArray(storeOrderCartInfo.oid,ids)).orderBy(asc(storeOrderCartInfo.id)).limit(501);
    if(carts.length>500||carts.some(row=>row.oversized||row.uid!==byId.get(row.oid)?.uid))throw new ValidateException('订单商品关联异常或超过安全读取容量');
    const refunds=await db.select({...getTableColumns(storeOrderRefund),cartInfo:sql<string|null>`CASE WHEN octet_length(${storeOrderRefund.cartInfo})<=131072 THEN ${storeOrderRefund.cartInfo} ELSE NULL END`,refundGoodsImg:sql<null>`NULL`,oversized:sql<boolean>`octet_length(${storeOrderRefund.cartInfo})>131072`}).from(storeOrderRefund).where(and(inArray(storeOrderRefund.storeOrderId,ids),eq(storeOrderRefund.isCancel,0),eq(storeOrderRefund.isDel,0))).orderBy(asc(storeOrderRefund.id)).limit(501);
    if(refunds.length>500||refunds.some(row=>{const o=byId.get(row.storeOrderId);return row.oversized||!o||row.uid!==o.uid||row.storeId!==o.storeId||row.supplierId!==o.supplierId;}))throw new ValidateException('订单售后关联异常或超过安全读取容量');
    const checkedCarts=carts.map(({oversized:_oversized,...row})=>row),checkedRefunds=refunds.map(({oversized:_oversized,...row})=>row),byOrder=new Map<number,Refund[]>();
    for(const order of orders)byOrder.set(order.id,await this.generationRefunds(db,order,checkedCarts.filter(row=>row.oid===order.id),checkedRefunds.filter(row=>row.storeOrderId===order.id)));
    return{carts:checkedCarts,refunds:checkedRefunds,byOrder};
  }
  /** Physical refund children keep the original immutable refund/payment owner.
   * Resolve the real generation evidence without repointing its business row. */
  private async generationRefunds(db:DbClient,order:Order,carts:Cart[],direct:Refund[]):Promise<Refund[]>{
    const invalid=()=>new ValidateException('退款实体归属证据不一致，请先核对订单');
    const markers=carts.map(row=>{if(!row.cartInfo?.includes('refund_order_generation')&&!row.cartInfo?.includes('refund-order-line-finance-v1'))return null;const parsed=json(row.cartInfo,'退款拆分商品');if(!parsed||Array.isArray(parsed)||parsed.financial_version!=='refund-order-line-finance-v1')throw invalid();return readRefundGenerationMarker(parsed.refund_order_generation);});
    if(markers.every(value=>value===null))return direct;
    const marker=markers[0];if(!marker||carts.length>200||markers.some(value=>JSON.stringify(value)!==JSON.stringify(marker)))throw invalid();
    if(marker.role==='remaining')return currentGenerationRefunds(direct,await loadRefundOrderGeneration(db,order,carts));
    const records=await db.select({refundId:storeOrderRefundSplit.refundId,fingerprint:storeOrderRefundSplit.fingerprint,uid:storeOrderRefundSplit.uid,storeId:storeOrderRefundSplit.storeId,supplierId:storeOrderRefundSplit.supplierId,sourceOrderId:storeOrderRefundSplit.sourceOrderId,paymentOrderId:storeOrderRefundSplit.paymentOrderId,selectedOrderId:storeOrderRefundSplit.selectedOrderId,disposition:storeOrderRefundSplit.disposition,partitions:sql<unknown>`${storeOrderRefundSplit.partitions}::jsonb`}).from(storeOrderRefundSplit).where(and(eq(storeOrderRefundSplit.refundId,marker.refundId),eq(storeOrderRefundSplit.selectedOrderId,order.id))).limit(2);
    const record=records[0];if(records.length!==1||!record||record.uid!==order.uid||record.storeId!==order.storeId||record.supplierId!==order.supplierId||record.paymentOrderId!==(order.pid||order.id)||record.disposition!=='split'||!Array.isArray(record.partitions)||record.partitions.length>200||order.refundStatus!==2||order.refundType!==6)throw invalid();
    const expected=new Map<number,number>();for(const value of record.partitions){if(!value||typeof value!=='object'||Array.isArray(value))throw invalid();const part=value as Record<string,unknown>;if(part.selectedNum===0){if(part.selectedRowId!==null)throw invalid();continue;}if(!Number.isSafeInteger(part.selectedRowId)||Number(part.selectedRowId)<=0||!Number.isSafeInteger(part.selectedNum)||Number(part.selectedNum)<=0||expected.has(Number(part.selectedRowId)))throw invalid();expected.set(Number(part.selectedRowId),Number(part.selectedNum));}
    if(expected.size!==carts.length||carts.some(row=>expected.get(row.id)!==row.cartNum||row.cartId!==String(row.id)||row.refundNum!==row.cartNum))throw invalid();
    const rows=await db.select({...getTableColumns(storeOrderRefund),cartInfo:sql<string|null>`CASE WHEN octet_length(${storeOrderRefund.cartInfo})<=131072 THEN ${storeOrderRefund.cartInfo} ELSE NULL END`,refundGoodsImg:sql<null>`NULL`}).from(storeOrderRefund).where(eq(storeOrderRefund.id,record.refundId)).limit(1),refund=rows[0];
    if(!refund||refund.storeOrderId!==record.sourceOrderId||refund.uid!==order.uid||refund.storeId!==order.storeId||refund.supplierId!==order.supplierId||refund.refundType!==6||refund.isDel||refund.isCancel||refund.refundedPrice!==refund.refundPrice||await refundOrderSplitFingerprint(refund)!==record.fingerprint)throw invalid();
    return [...direct.filter(row=>row.id!==refund.id),refund];
  }
  private async project(db:DbClient,scope:StoreManagerScope,order:Order,carts:Cart[],refunds:Refund[]):Promise<MerchantOrderListItem>{
    const value=orderProjection(order,carts,refunds),[customer]=await db.select({nickname:user.nickname}).from(user).where(eq(user.uid,order.uid)).limit(1);
    const projectedCarts=carts.map(moneyCart),images=await publicProductPictures(db,projectedCarts.map(row=>({image:row.productInfo.image,type:order.supplierId>0?2:0,relationId:order.supplierId>0?order.supplierId:0})));
    projectedCarts.forEach((row,index)=>{row.productInfo.image=images[index];row.productInfo.attrInfo.image=images[index];});
    const actions={...unavailableManagerOrderActions(),...await this.actionReader(db,scope,order)},status=order.status===4&&order.refundStatus===0?{...value._status,_title:'部分发货',_msg:'尚有商品待发货'}:value._status;
    return{...value,store_id:order.storeId,supplier_id:order.supplierId,nickname:customer?.nickname??'',cartInfo:projectedCarts,_status:status,actions,revision:await merchantOrderRevision(order),is_all_refund:carts.filter(row=>row.isGift===0).reduce((sum,row)=>sum+row.cartNum,0)>0&&carts.filter(row=>row.isGift===0).every(row=>row.refundNum===row.cartNum)};
  }
  private conditions(q:ManagerListQuery):SQL[]{const result:SQL[]=[eq(storeOrder.storeId,q.storeId),eq(storeOrder.isSystemDel,0),eq(storeOrder.isDel,q.isDel),orderReadStatusPredicate(q.selector)];if(q.selector===null||q.selector>=0||q.selector===-4)result.push(gte(storeOrder.pid,0));
    if(q.type!==null)result.push(q.type===105?eq(storeOrder.shippingType,2):q.type===106?eq(storeOrder.shippingType,4):q.type===107?inArray(storeOrder.shippingType,[1,3]):eq(storeOrder.type,q.type));if(q.payType)result.push(eq(storeOrder.payType,q.payType));
    if(q.start!==null)result.push(sql`${storeOrder.addTime}>=${q.start} AND ${storeOrder.addTime}<${q.endExclusive}`);
    if(q.keyword){const keyword=q.keyword,match=`%${keyword.replace(/[\\%_]/g,'\\$&')}%`,title=sql`EXISTS(SELECT 1 FROM store_order_cart_info c JOIN store_product p ON p.id=c.product_id WHERE c.oid=${storeOrder.id} AND c.uid=${storeOrder.uid} AND (p.store_name ILIKE ${match} OR p.keyword ILIKE ${match}))`;
      if(q.fieldKey==='uid'||q.fieldKey==='total_num'){if(!/^\d{1,10}$/.test(keyword)||Number(keyword)>2147483647)throw new ValidateException('数字搜索值无效');result.push(eq(q.fieldKey==='uid'?storeOrder.uid:storeOrder.totalNum,Number(keyword)));}
      else if(q.fieldKey==='title')result.push(title);
      else if(q.fieldKey)result.push(eq(q.fieldKey==='order_id'?storeOrder.orderId:q.fieldKey==='real_name'?storeOrder.realName:storeOrder.userPhone,keyword));
      else result.push(or(ilike(storeOrder.orderId,match),ilike(storeOrder.realName,match),ilike(storeOrder.userPhone,match),title,
        sql`EXISTS(SELECT 1 FROM "user" u WHERE u.uid=${storeOrder.uid} AND (u.nickname ILIKE ${match} OR u.phone ILIKE ${match} OR u.uid::text ILIKE ${match}))`,
        sql`EXISTS(SELECT 1 FROM user_address a WHERE a.uid=${storeOrder.uid} AND (a.real_name ILIKE ${match} OR a.phone ILIKE ${match}))`,
        sql`(${storeOrder.type}=1 AND EXISTS(SELECT 1 FROM store_seckill a WHERE a.id=${storeOrder.activityId} AND (a.store_name ILIKE ${match} OR a.info ILIKE ${match})))`,
        sql`(${storeOrder.type}=2 AND EXISTS(SELECT 1 FROM store_bargain a WHERE a.id=${storeOrder.activityId} AND (a.title ILIKE ${match} OR a.info ILIKE ${match})))`,
        sql`(${storeOrder.type}=3 AND EXISTS(SELECT 1 FROM store_combination a WHERE a.id=${storeOrder.activityId} AND (a.store_name ILIKE ${match} OR a.info ILIKE ${match})))`)!);
    }return result;
  }
  private async render<T extends MerchantOrderListItem>(rows:T[]):Promise<T[]>{const pictures=rows.flatMap(row=>row.cartInfo.map(cart=>cart.productInfo.image)),signed=await renderProductPictures(this.env.APP_KEY,pictures);let index=0;for(const row of rows)for(const cart of row.cartInfo){cart.productInfo.image=signed[index];cart.productInfo.attrInfo.image=signed[index++];}return rows;}
  async list(uid:number,query:Record<string,string>){const q=parseManagerListQuery(query),result=await withManagerRead(this.container,uid,q.storeId,async(db,scope):Promise<MerchantPaged<MerchantOrderListItem>>=>{
    const where=and(...this.conditions(q)),rows=await db.select(boundedOrder).from(storeOrder).where(where).orderBy(desc(storeOrder.addTime),desc(storeOrder.payTime),desc(storeOrder.id)).limit(q.limit).offset((q.page-1)*q.limit),[total]=await db.select({count:sql<number>`count(*)::int`}).from(storeOrder).where(where),orders=rows.map(checkedOrder),associations=await this.associations(db,orders),list=[];
    for(const order of orders)list.push(await this.project(db,scope,order,associations.carts.filter(row=>row.oid===order.id),associations.byOrder.get(order.id)??[]));
    return{list,count:managerCount(total.count),page:q.page,limit:q.limit,has_more:(q.page-1)*q.limit+rows.length<total.count};});await this.render(result.data.list);return result;
  }
  async detail(uid:number,number:unknown,query:Record<string,string>):Promise<MerchantManagementEnvelope<MerchantOrderDetail>>{
    const result=await withManagerRead(this.container,uid,parseManagerStoreQuery(query),async(db,scope):Promise<MerchantOrderDetail>=>{
      const order=await this.orderByNumber(db,scope,number),associations=await this.associations(db,[order]),mappedRefunds=associations.byOrder.get(order.id)??[],value=await this.project(db,scope,order,associations.carts,mappedRefunds);
      const [customer]=await db.select({uid:user.uid,nickname:user.nickname,avatar:user.avatar,level:user.level,isEverLevel:user.isEverLevel,isMoneyLevel:user.isMoneyLevel,overdueTime:user.overdueTime}).from(user).where(eq(user.uid,order.uid)).limit(1);
      const [level]=customer?.level?await db.select({name:systemUserLevel.name,discount:systemUserLevel.discount}).from(systemUserLevel).where(and(eq(systemUserLevel.id,customer.level),eq(systemUserLevel.isDel,0),eq(systemUserLevel.isShow,1))).limit(1):[];
      const [store]=await db.select({id:systemStore.id,name:systemStore.name,phone:systemStore.phone,address:systemStore.address,detailed_address:systemStore.detailedAddress}).from(systemStore).where(eq(systemStore.id,scope.store_id)).limit(1);
      const [invoice]=await db.select({id:storeOrderInvoice.id,status:storeOrderInvoice.isInvoice,is_refund:storeOrderInvoice.isRefund}).from(storeOrderInvoice).where(and(eq(storeOrderInvoice.orderId,order.id),eq(storeOrderInvoice.uid,order.uid),eq(storeOrderInvoice.isDel,0))).orderBy(asc(storeOrderInvoice.id)).limit(2); // Duplicate handled below by dedicated count.
      const invoiceRows=await db.select({id:storeOrderInvoice.id}).from(storeOrderInvoice).where(and(eq(storeOrderInvoice.orderId,order.id),eq(storeOrderInvoice.uid,order.uid),eq(storeOrderInvoice.isDel,0))).limit(2);if(invoiceRows.length>1)throw new ValidateException('订单发票身份存在重复');
      const promotions=await db.select({promotions_id:storeOrderPromotions.promotionsId,product_id:storeOrderPromotions.productId,promotions_price:storeOrderPromotions.promotionsPrice,title:storePromotions.title}).from(storeOrderPromotions).leftJoin(storePromotions,and(eq(storePromotions.id,storeOrderPromotions.promotionsId),or(eq(storePromotions.storeId,0),eq(storePromotions.storeId,scope.store_id)))).where(and(eq(storeOrderPromotions.oid,order.id),eq(storeOrderPromotions.uid,order.uid))).orderBy(asc(storeOrderPromotions.id)).limit(201);if(promotions.length>200)throw new ValidateException('订单优惠活动过多');
      const ids=couponIds(order.giveCoupon),coupons=ids.length?await db.select({id:storeCouponIssue.id,coupon_title:storeCouponIssue.couponTitle}).from(storeCouponIssue).where(inArray(storeCouponIssue.id,ids)).orderBy(asc(storeCouponIssue.id)):[];
      const [pink]=order.type===3&&order.pinkId>0?await db.select({status:storePink.status}).from(storePink).where(and(eq(storePink.id,order.pinkId),eq(storePink.uid,order.uid))).limit(1):[];
      const split=order.pid===-1?await db.select({id:storeOrder.id,pid:storeOrder.pid,order_id:storeOrder.orderId,paid:storeOrder.paid,status:storeOrder.status,total_num:storeOrder.totalNum,pay_price:storeOrder.payPrice,delivery_type:storeOrder.deliveryType,delivery_name:storeOrder.deliveryName,delivery_code:storeOrder.deliveryCode,delivery_id:storeOrder.deliveryId}).from(storeOrder).where(and(eq(storeOrder.pid,order.id),eq(storeOrder.uid,order.uid),eq(storeOrder.storeId,scope.store_id),eq(storeOrder.isDel,0),eq(storeOrder.isSystemDel,0))).orderBy(asc(storeOrder.id)).limit(201):[];if(split.length>200)throw new ValidateException('订单子履约过多，请按具体子单读取');
      const configs=await createContainerFromDb(db).systemConfigDao.getValues(['order_cancel_time','order_activity_time','order_seckill_time','order_bargain_time','order_pink_time']),hours=orderCancelHours(order.type,Object.fromEntries(Object.entries(configs).map(([key,val])=>[key,normalizeConfigScalar(typeof val==='string'?val:undefined)])));
      const vipCents=associations.carts.map(moneyCart).reduce((sum,cart)=>sum+BigInt(cart.vip_sum_truePrice.replace('.','')),0n),vip_true_price=`${vipCents/100n}.${String(vipCents%100n).padStart(2,'0')}`;
      const totalCents=BigInt(value.total_price.replace('.',''))-vipCents;
      if(totalCents<0n)throw new ValidateException('订单会员优惠超过原商品金额，请先核对历史数据');
      value.total_price=`${totalCents/100n}.${String(totalCents%100n).padStart(2,'0')}`;
      const avatar=customer?.avatar?(await orderUserPictures(db,order.uid,[customer.avatar]))[0]:'';
      const goods=mappedRefunds.length?await db.select({value:sql<string|null>`CASE WHEN octet_length(${storeOrderRefund.refundGoodsImg})<=16384 THEN ${storeOrderRefund.refundGoodsImg} ELSE NULL END`,oversized:sql<boolean>`octet_length(${storeOrderRefund.refundGoodsImg})>16384`}).from(storeOrderRefund).where(and(inArray(storeOrderRefund.id,mappedRefunds.map(row=>row.id)),eq(storeOrderRefund.uid,order.uid),eq(storeOrderRefund.storeId,scope.store_id),eq(storeOrderRefund.supplierId,order.supplierId),eq(storeOrderRefund.isCancel,0),eq(storeOrderRefund.isDel,0))).orderBy(asc(storeOrderRefund.id)).limit(501):[];
      if(goods.some(row=>row.oversized))throw new ValidateException('退款凭证超过安全读取容量');
      const refund_img=await orderUserPictures(db,order.uid,pictureList(order.refundReasonWapImg,'申请退款图片')),refund_goods_img=await orderUserPictures(db,order.uid,goods.flatMap(row=>pictureList(row.value,'退货凭证')));
      return{...value,review:{uid:order.uid,storeOrderId:order.id,storeId:order.storeId,supplierId:order.supplierId,orderId:order.orderId,payPrice:order.payPrice,paid:order.paid,rawStatus:order.status,refundStatus:order.refundStatus,payType:order.payType},customer:{uid:order.uid,nickname:customer?.nickname??'',avatar,level_name:level?.name??'',vip_discount:level?.discount??'',pay_vip_status:!!customer&&(customer.isEverLevel===1||customer.isMoneyLevel===1&&customer.overdueTime>Math.floor(Date.now()/1000))},vip_true_price,promotions_detail:promotions.map(row=>({...row,title:row.title??''})),give_coupon:coupons,give_integral:order.giveIntegral,custom_form:json(order.customForm,'订单自定义表单'),virtual_info:order.paid===1?text(order.virtualInfo,65536):'',fictitious_content:order.paid===1?order.fictitiousContent:'',pinkStatus:pink?.status??null,invoice:invoice??null,split,store,refund_reason_wap_explain:order.refundReasonWapExplain,refund_reason_wap:order.refundReasonWap,refund_reason:order.refundReason,refund_reason_time:order.refundReasonTime,refund_img,refund_goods_img,stop_time:order.paid===0&&hours>0?order.addTime+Math.ceil(hours*3600):0};
    });await this.render([result.data]);const signed=await renderProductPictures(this.env.APP_KEY,[result.data.customer.avatar,...result.data.refund_img,...result.data.refund_goods_img]);result.data.customer.avatar=signed[0];result.data.refund_img=signed.slice(1,1+result.data.refund_img.length);result.data.refund_goods_img=signed.slice(1+result.data.refund_img.length);return result;
  }
  async deliveryGain(uid:number,number:unknown,query:Record<string,string>){return withManagerRead(this.container,uid,parseManagerStoreQuery(query),async(db,scope)=>{const order=await this.orderByNumber(db,scope,number);if(order.paid!==1)throw new ValidateException('未支付订单不能发货');return{id:order.id,order_id:order.orderId,real_name:order.realName,user_phone:order.userPhone,user_address:order.userAddress,revision:await merchantOrderRevision(order)};});}
  async express(uid:number,number:unknown,query:Record<string,string>):Promise<MerchantManagementEnvelope<ExpressQueryResult>>{
    const storeId=parseManagerStoreQuery(query),snapshot=()=>withManagerRead(this.container,uid,storeId,async(db,scope)=>{
      const root=await this.orderByNumber(db,scope,number),split=root.pid===-1||root.deliveryType==='split';
      const children=split?await db.select(boundedOrder).from(storeOrder).where(and(eq(storeOrder.pid,root.id),eq(storeOrder.uid,root.uid),eq(storeOrder.storeId,scope.store_id),eq(storeOrder.supplierId,root.supplierId),eq(storeOrder.isDel,0),eq(storeOrder.isSystemDel,0))).orderBy(asc(storeOrder.id)).limit(50):[];
      if(children.length>=50)throw new ValidateException('物流包裹超过安全读取容量');return[root,...children.map(checkedOrder)];
    });
    const initial=await snapshot(),revisions=await Promise.all(initial.data.map(merchantOrderRevision));
    const authorize=async()=>{const fresh=await snapshot();if(fresh.scope_key!==initial.scope_key||fresh.consistency_key!==initial.consistency_key||JSON.stringify(await Promise.all(fresh.data.map(merchantOrderRevision)))!==JSON.stringify(revisions))throw new ValidateException('管理身份或物流订单已变化，请重新读取');};
    const data=await new ExpressService(this.container,this.env).queryScopedOrders(initial.data,authorize);return{...initial,data};
  }
  async splitCartInfo(uid:number,id:unknown,query:Record<string,string>){const result=await withManagerRead(this.container,uid,parseManagerStoreQuery(query),async(db,scope)=>{const order=await this.orderById(db,scope,id),rows=await this.associations(db,[order]),value=await this.project(db,scope,order,rows.carts.filter(row=>[0,1].includes(row.splitStatus)&&row.splitSurplusNum>0),rows.byOrder.get(order.id)??[]);return value.cartInfo;});const rows=result.data,images=await renderProductPictures(this.env.APP_KEY,rows.map(row=>row.productInfo.image));rows.forEach((row,index)=>{row.productInfo.image=images[index];row.productInfo.attrInfo.image=images[index];});return result;}
  async carriers(uid:number,query:Record<string,string>){return withManagerRead(this.container,uid,parseManagerStoreQuery(query),async(db):Promise<MerchantCarrier[]>=>db.select({id:expressCompany.id,name:expressCompany.name,code:expressCompany.code}).from(expressCompany).where(and(eq(expressCompany.isShow,1),eq(expressCompany.status,1))).orderBy(desc(expressCompany.sort),asc(expressCompany.id)).limit(201).then(rows=>{if(rows.length>200)throw new ValidateException('快递公司目录超过安全读取容量');return rows;}));}
  async deliveryAgents(uid:number,query:Record<string,string>){return withManagerRead(this.container,uid,parseManagerStoreQuery(query),async(db,scope):Promise<MerchantDeliveryAgent[]>=>{const rows=await db.select({id:deliveryService.id,uid:deliveryService.uid,nickname:deliveryService.nickname,phone:deliveryService.phone}).from(deliveryService).innerJoin(user,eq(user.uid,deliveryService.uid)).where(and(eq(deliveryService.type,1),eq(deliveryService.relationId,scope.store_id),eq(deliveryService.status,1),eq(deliveryService.isDel,0),eq(user.status,1),eq(user.isDel,0),sql`${user.deleteTime} IS NULL`)).orderBy(asc(deliveryService.id)).limit(201);if(rows.length>200)throw new ValidateException('配送员目录超过安全读取容量');const count=new Map<number,number>();for(const row of rows)count.set(row.uid,(count.get(row.uid)??0)+1);return rows.filter(row=>count.get(row.uid)===1).map(({id:_id,...row})=>row);});}
  async deliveryDefaults(uid:number,query:Record<string,string>){return withManagerRead(this.container,uid,parseManagerStoreQuery(query),async(db,scope):Promise<MerchantDeliveryDefaults>=>{const keys=['store_config_export_temp_id','store_config_export_to_name','store_config_export_id','store_config_export_to_tel','store_config_export_to_address','store_config_export_open'],rows=await db.select({key:storeConfig.keyName,value:storeConfig.value}).from(storeConfig).where(and(eq(storeConfig.type,1),eq(storeConfig.relationId,scope.store_id),inArray(storeConfig.keyName,keys))).orderBy(asc(storeConfig.id)).limit(7),values=new Map<string,string>();for(const row of rows){if(values.has(row.key))throw new ValidateException('门店发货配置重复，请先核对');values.set(row.key,normalizeConfigScalar(row.value));}const flags=await new CityDeliverySettingsResolver(createContainerFromDb(db),this.env).flags(),enabled=(value:unknown)=>normalizeConfigScalar(typeof value==='string'?value:undefined)==='1',city=enabled(flags.city_delivery_status),self=city&&enabled(flags.self_delivery_status),dada=city&&enabled(flags.dada_delivery_status),uu=city&&enabled(flags.uu_delivery_status);return{express_temp_id:values.get(keys[0])??'',to_name:values.get(keys[1])??'',config_export_id:values.get(keys[2])??'',to_tel:values.get(keys[3])??'',to_add:values.get(keys[4])??'',config_export_open:values.get(keys[5])==='1'?1:0,city_delivery_status:city&&(self||dada||uu),self_delivery_status:self,dada_delivery_status:dada,uu_delivery_status:uu};});}
}
