import {ref,watch} from 'vue';
import {onShow,onHide,onUnload} from '@dcloudio/uni-app';
import {RequestError} from '@/utils/request';
import {createCustomerWriteoffRequests,type CustomerWriteoffRequests} from '@/api/customerWorkWriteoff';
import {CUSTOMER_WRITEOFF_VERSION,customerWorkCanonicalJson,writeoffId,writeoffNumber,writeoffLookupValue,writeoffLookupFingerprint,writeoffIntentHash,isCustomerWorkWriteoffInput,isCustomerWorkWriteoffIntent,isCustomerWorkWriteoffTarget,isCustomerWorkWriteoffLookup,isCustomerWorkWriteoffRecords,parseCustomerWorkWriteoffEnvelope,parseCustomerWorkWriteoffResult,customerWriteoffTerminal,customerWriteoffPending,retainCustomerWriteoffIntent,releaseCustomerWriteoffIntent,customerWorkRequestKey,customerWriteoffNotice,customerWriteoffResultMessage} from '@/utils/customerWorkWriteoff';
import type {CustomerWorkController} from './useCustomerWork';
import type {CustomerWorkWriteoffEnvelope,CustomerWorkWriteoffTarget,CustomerWorkWriteoffLookup,CustomerWorkWriteoffRecords,CustomerWorkWriteoffNamespace,CustomerWorkWriteoffItem,CustomerWorkWriteoffInput,CustomerWorkWriteoffIntent,CustomerWorkWriteoffResult,CustomerWorkWriteoffOperationState} from '@/types/customerWorkWriteoff';
const confirm=(title:string,content:string)=>new Promise<boolean>(resolve=>uni.showModal({title,content,success:r=>resolve(!!r.confirm),fail:()=>resolve(false)}));
export type CustomerWorkWriteoffOperations=ReturnType<typeof useCustomerWorkWriteoffOperations>;
export function useCustomerWorkWriteoffOperations(manager:CustomerWorkController){
 const target=ref<CustomerWorkWriteoffEnvelope<CustomerWorkWriteoffTarget>|null>(null),lookupResult=ref<CustomerWorkWriteoffLookup|null>(null),records=ref<CustomerWorkWriteoffRecords|null>(null),busy=ref(false),error=ref(''),pending=ref<CustomerWorkWriteoffIntent[]>([]),states=ref<Record<string,CustomerWorkWriteoffOperationState>>({});
 const requests=new Set<CustomerWriteoffRequests>();let epoch=0,disposed=false;
 const current=()=>!disposed&&manager.current()&&manager.auth.isLoggedIn;
 const sameOwner=(owner:CustomerWriteoffRequests)=>current()&&manager.auth.uid===owner.owner.uid&&manager.auth.token===owner.owner.token&&manager.auth.sessionVersion===owner.owner.version;
 const owns=(intent:CustomerWorkWriteoffIntent)=>current()&&intent.actor_uid===manager.auth.uid;
 const readable=()=>current()&&manager.context.value?.data.capabilities.writeoff_read===true;
 function refreshPending(){if(!current()){pending.value=[];return;}try{pending.value=customerWriteoffPending().filter(r=>r.actor_uid===manager.auth.uid);}catch(failure){pending.value=[];error.value=failure instanceof Error?customerWriteoffNotice(failure.message):'原核销记录需核对';}}
 function clearRequests(){epoch++;for(const owner of requests)owner.abort();requests.clear();target.value=null;lookupResult.value=null;records.value=null;busy.value=false;error.value='';}
 function clear(){clearRequests();pending.value=[];states.value={};}
 function clearDomain(){clearRequests();if(current())refreshPending();else{pending.value=[];states.value={};}}
 function scope(fence?:()=>boolean){const version=epoch,owner=createCustomerWriteoffRequests(()=>current()&&epoch===version&&(!fence||fence()));requests.add(owner);return owner;}
 function close(owner:CustomerWriteoffRequests){owner.abort();requests.delete(owner);}
 function known(intent:CustomerWorkWriteoffIntent){if(!isCustomerWorkWriteoffIntent(intent)||!owns(intent))throw Error('原核销意图不属于当前账号');const saved=customerWriteoffPending().find(r=>r.request_key===intent.request_key);if(!saved||customerWorkCanonicalJson(saved)!==customerWorkCanonicalJson(intent))throw Error('原核销内容已变化，请保留原记录核对');}
 function state(intent:CustomerWorkWriteoffIntent,result:CustomerWorkWriteoffResult|null,checked=false,message=''){states.value={...states.value,[intent.request_key]:{result,checked,unknown:!result?.receipt||!customerWriteoffTerminal(result),error:message}};}
 function matches(authority:CustomerWorkWriteoffEnvelope<CustomerWorkWriteoffTarget>){const context=manager.context.value;return readable()&&context&&authority.actor_uid===manager.auth.uid&&authority.scope_key===context.scope_key&&authority.principal.service_id===context.principal.service_id&&authority.consistency_key===context.consistency_key;}
 function parse<T>(raw:unknown,guard:(v:unknown)=>v is T,owner:CustomerWriteoffRequests){const context=manager.context.value;if(!owner.active()||!context||!readable())throw Error('当前核销经营身份已变化');try{return parseCustomerWorkWriteoffEnvelope(raw,owner.owner.uid,guard,context);}catch(failure){if(owner.active())manager.invalidate(failure);throw failure;}}
 function failed(owner:CustomerWriteoffRequests,intent:CustomerWorkWriteoffIntent|undefined,failure:unknown){if(!owner.active()||!sameOwner(owner))return;const message=failure instanceof Error?customerWriteoffNotice(failure.message):'原核销结果未确认，请查询原编号';if(failure instanceof RequestError&&(failure.httpStatus===403||[410000,410001,410002].includes(Number(failure.status))))manager.invalidate(Error('当前核销权限已变化，请重新读取'));if(!sameOwner(owner))return;refreshPending();if(intent){const prior=states.value[intent.request_key];state(intent,prior?.result??null,prior?.checked??false,message);}error.value=message;}
 function consume(raw:unknown,intent:CustomerWorkWriteoffIntent,owner:CustomerWriteoffRequests,checked=false){let result:CustomerWorkWriteoffResult;try{result=parseCustomerWorkWriteoffResult(raw,intent);}catch(failure){if(owner.active())manager.invalidate(Error('原核销回执不匹配，已清除当前订单资料，请继续核对原编号'));throw failure;}if(result.receipt?.service_id===0)manager.invalidate(Error('原核销意图已终止，请重新读取当前资格与订单'));if(sameOwner(owner)){refreshPending();state(intent,result,checked||!!result.receipt);error.value=customerWriteoffResultMessage(result);}return result;}
 async function lookup(namespace:CustomerWorkWriteoffNamespace,value:string){if(!readable()||!writeoffLookupValue(namespace,value))throw Error('当前查询命名空间、内容或经营资格无效');const context=manager.context.value!,owner=scope(manager.fence());try{const response=parse(await owner.request('/mobile/work/writeoff/lookup','POST',{version:'customer-work-writeoff-read-v1',scope_key:context.scope_key,namespace,value}),isCustomerWorkWriteoffLookup,owner);if(!owner.active())throw Error('核销查询页面已变化');if(response.data.namespace!==namespace||response.data.lookup_fingerprint!==writeoffLookupFingerprint(namespace,value)||namespace==='legacy-order-id'&&response.data.orders.some(r=>r.id!==Number(value))){manager.invalidate(Error('核销查询目标或命名空间不匹配'));throw Error('核销查询目标或命名空间不匹配');}lookupResult.value=response.data;return response.data;}catch(failure){failed(owner,undefined,failure);throw failure;}finally{close(owner);}}
 async function loadTarget(id:number,no:string){refreshPending();if(!readable()||!writeoffId(id)||!writeoffNumber(no))throw Error('核销订单身份或经营资格无效');const owner=scope(manager.fence());try{const response=parse(await owner.request(`/mobile/work/writeoff/orders/${id}`,'GET',{scope_key:manager.context.value!.scope_key,order_no:no}),isCustomerWorkWriteoffTarget,owner);if(!owner.active())throw Error('核销订单页面已变化');if(response.data.id!==id||response.data.order_no!==no||response.data.requested_order_no!==no){manager.invalidate(Error('核销订单物理编号与业务单号不匹配'));throw Error('核销订单物理编号与业务单号不匹配');}target.value=response;records.value=null;return response.data;}catch(failure){failed(owner,undefined,failure);throw failure;}finally{close(owner);}}
 async function resolveLegacy(id:string){const value=await lookup('legacy-order-id',id);if(value.orders.length!==1)throw Error('历史订单暂无法唯一核对');const order=value.orders[0]!;return loadTarget(order.id,order.order_no);}
 async function loadRecords(id:number,no:string,page=1,limit=20){if(!readable()||!writeoffId(id)||!writeoffNumber(no)||!writeoffId(page)||!writeoffId(limit)||limit>100)throw Error('核销记录订单或分页参数无效');const owner=scope(manager.fence());try{const response=parse(await owner.request(`/mobile/work/writeoff/orders/${id}/records`,'GET',{scope_key:manager.context.value!.scope_key,order_no:no,page,limit}),isCustomerWorkWriteoffRecords,owner),value=response.data,basis=target.value?.data;if(!owner.active())throw Error('核销记录页面已变化');if(value.order_id!==id||value.order_no!==no||value.page!==page||value.limit!==limit||basis&&basis.id===id&&(value.root_order_id!==basis.root_order_id||value.root_order_no!==basis.root_order_no)){manager.invalidate(Error('核销记录订单、付款根或分页不匹配'));throw Error('核销记录订单、付款根或分页不匹配');}records.value=value;return value;}catch(failure){failed(owner,undefined,failure);throw failure;}finally{close(owner);}}
 function selection(basis:CustomerWorkWriteoffTarget,items:CustomerWorkWriteoffItem[]){const now=Math.floor(Date.now()/1000);return items.every(item=>basis.carts.some(row=>row.cart_row_id===item.cart_row_id&&row.write_surplus_times>=item.writeoff_num&&row.is_writeoff===0&&row.sale_price.source!=='unproven'&&(!row.write_start||row.write_start<=now)&&(!row.write_end||row.write_end>=now)));}
 async function submit(basis:CustomerWorkWriteoffTarget,items:CustomerWorkWriteoffItem[]):Promise<CustomerWorkWriteoffResult|null>{
  const authority=target.value;if(busy.value||!authority||!matches(authority)||!basis.readiness.writes||!basis.actions.writeoff.available||customerWorkCanonicalJson(authority.data)!==customerWorkCanonicalJson(basis)){error.value='当前核销目标、次数或资格已变化，请重新读取';return null;}
  const snapshot=JSON.parse(customerWorkCanonicalJson(basis)) as CustomerWorkWriteoffTarget,input:CustomerWorkWriteoffInput={version:CUSTOMER_WRITEOFF_VERSION,scope_key:authority.scope_key,order_id:basis.id,expected_order_revision:basis.order_revision,expected_writeoff_revision:basis.writeoff_revision,payload:{order_no:basis.order_no,root_order_id:basis.root_order_id,root_order_no:basis.root_order_no,code:basis.code,target_fingerprint:basis.target_fingerprint,items:JSON.parse(customerWorkCanonicalJson(items))}};
  if(!isCustomerWorkWriteoffInput(input)||!selection(snapshot,input.payload.items)){error.value='请选择有效商品与实际剩余次数，尚未提交';return null;}
  refreshPending();if(pending.value.some(i=>i.root_order_id===snapshot.root_order_id&&!customerWriteoffTerminal(states.value[i.request_key]?.result??null))){error.value='此付款订单存在待确认原核销，请先查询原编号';return null;}
  const owner=scope(manager.fence());busy.value=true;error.value='';let intent:CustomerWorkWriteoffIntent|undefined;
  const valid=()=>owner.active()&&target.value===authority&&matches(authority)&&customerWorkCanonicalJson(authority.data)===customerWorkCanonicalJson(snapshot);
  try{const qty=items.reduce((sum,item)=>sum+item.writeoff_num,0);if(!await confirm('确认本次核销',`订单 ${snapshot.order_no} · 本次 ${qty} 次。本次金额按原成交快照逐项核验。操作不可撤销，分次后原码立即失效。`)||!valid())return null;const key=await customerWorkRequestKey();if(!valid())return null;
   intent=JSON.parse(customerWorkCanonicalJson({version:'customer-work-writeoff-pending-v1',actor_uid:owner.owner.uid,service_id:authority.principal.service_id,scope_key:authority.scope_key,kind:'writeoff',request_key:key,request_hash:writeoffIntentHash(owner.owner.uid,input),order_no:snapshot.order_no,root_order_id:snapshot.root_order_id,root_order_no:snapshot.root_order_no,body:input,endpoint:'/mobile/work/writeoff/execute',method:'POST',created_at:Math.floor(Date.now()/1000)}));retainCustomerWriteoffIntent(intent!);refreshPending();state(intent!,null);const raw=await owner.request(intent!.endpoint,'POST',intent!.body as unknown as Record<string,unknown>,intent!.request_key);if(!owner.active())return null;return consume(raw,intent!,owner);
  }catch(failure){failed(owner,intent,failure);return null;}finally{if(owner.active())busy.value=false;close(owner);}
 }
 async function check(intent:CustomerWorkWriteoffIntent){if(busy.value||!owns(intent))return;const owner=scope();busy.value=true;error.value='';try{known(intent);const raw=await owner.request(`/mobile/work/writeoff/operations/${intent.request_key}`);if(owner.active())return consume(raw,intent,owner,true);}catch(failure){failed(owner,intent,failure);}finally{if(owner.active())busy.value=false;close(owner);}}
 async function checkRelevant(rootId:number){refreshPending();for(const intent of [...pending.value].filter(i=>i.root_order_id===rootId)){if(!current()||!manager.context.value)break;await check(intent);}}
 function sameIntentScope(intent:CustomerWorkWriteoffIntent){const context=manager.context.value;return owns(intent)&&readable()&&!!context&&context.scope_key===intent.scope_key&&context.principal.service_id===intent.service_id;}
 function canRestore(intent:CustomerWorkWriteoffIntent){const state=states.value[intent.request_key],authority=target.value,basis=authority?.data,input=intent.body;return !busy.value&&sameIntentScope(intent)&&!!state?.checked&&!state.result?.receipt&&!!authority&&!!basis&&!!matches(authority)&&basis.readiness.writes&&basis.actions.writeoff.available&&basis.id===input.order_id&&basis.order_no===input.payload.order_no&&basis.root_order_id===intent.root_order_id&&basis.root_order_no===intent.root_order_no&&basis.order_revision===input.expected_order_revision&&basis.writeoff_revision===input.expected_writeoff_revision&&basis.code===input.payload.code&&basis.target_fingerprint===input.payload.target_fingerprint&&selection(basis,input.payload.items);}
 function canAbandon(intent:CustomerWorkWriteoffIntent){const value=states.value[intent.request_key];return owns(intent)&&!busy.value&&!!value?.checked&&!value.result?.receipt;}
 async function retry(intent:CustomerWorkWriteoffIntent,operation:'restore'|'abandon'){
  const allowed=()=>operation==='restore'?canRestore(intent):canAbandon(intent);if(!allowed())return;const owner=scope(operation==='restore'?manager.fence():undefined);busy.value=true;error.value='';try{known(intent);if(!await confirm(operation==='restore'?'恢复原核销意图':'放弃尚未执行的原核销','已查询原结果。使用原编号及完整原内容，只处理这一次意图；已经执行的回执永久保留。')||!owner.active()||!sameOwner(owner))return;busy.value=false;const stillAllowed=allowed();busy.value=true;if(!stillAllowed)return;known(intent);const path=operation==='abandon'?`/mobile/work/writeoff/operations/${intent.request_key}/abandon`:intent.endpoint,body=operation==='abandon'?{kind:'writeoff',input:intent.body}:intent.body;const raw=await owner.request(path,'POST',body as unknown as Record<string,unknown>,intent.request_key);if(owner.active())consume(raw,intent,owner,true);}catch(failure){failed(owner,intent,failure);}finally{if(owner.active())busy.value=false;close(owner);}
 }
 async function acknowledge(intent:CustomerWorkWriteoffIntent){const result=states.value[intent.request_key]?.result;if(busy.value||!owns(intent)||!customerWriteoffTerminal(result??null))return;const owner=scope();busy.value=true;try{known(intent);const original=customerWorkCanonicalJson(result);if(!await confirm('关闭本机原核销记录','已核对真实原回执及业务结果，关闭这条本机待确认记录。')||!owner.active()||customerWorkCanonicalJson(states.value[intent.request_key]?.result)!==original)return;known(intent);releaseCustomerWriteoffIntent(intent.request_key);const next={...states.value};delete next[intent.request_key];states.value=next;refreshPending();}catch(failure){failed(owner,intent,failure);}finally{if(owner.active())busy.value=false;close(owner);}}
 onShow(refreshPending);onHide(clear);onUnload(()=>{disposed=true;clear();});watch(()=>[manager.auth.uid,manager.auth.token,manager.auth.sessionVersion],()=>{clear();refreshPending();},{flush:'sync'});watch(()=>manager.context.value,(value,prior)=>{if(prior&&(!value||value.scope_key!==prior.scope_key||value.principal.service_id!==prior.principal.service_id||value.consistency_key!==prior.consistency_key))clearDomain();},{flush:'sync'});
 return{manager,target,lookupResult,records,busy,error,pending,states,current,readable,clear,clearDomain,refreshPending,lookup,loadTarget,resolveLegacy,loadRecords,submit,check,checkRelevant,canRestore,canAbandon,restore:(intent:CustomerWorkWriteoffIntent)=>retry(intent,'restore'),abandon:(intent:CustomerWorkWriteoffIntent)=>retry(intent,'abandon'),acknowledge};
}
