import {ref,watch,type Ref} from 'vue';
import {onShow,onHide,onUnload} from '@dcloudio/uni-app';
import {RequestError} from '@/utils/request';
import {createCustomerFinancialRequests,type CustomerFinancialRequests} from '@/api/customerWorkFinancial';
import {CUSTOMER_FINANCIAL_VERSION,CUSTOMER_FINANCIAL_NAMES,customerWorkCanonicalJson,financialIntentHash,financialEndpoint,isCustomerFinancialOrder,isCustomerFinancialRefundReview,isCustomerFinancialRefundQuote,isCustomerFinancialInput,isCustomerFinancialIntent,parseCustomerFinancialEnvelope,parseCustomerFinancialResult,customerFinancialTerminal,customerFinancialPending,retainCustomerFinancialIntent,releaseCustomerFinancialIntent,customerWorkRequestKey,customerFinancialNotice,customerFinancialResultMessage} from '@/utils/customerWorkFinancial';
import type {CustomerWorkController} from './useCustomerWork';
import type {CustomerFinancialOrder,CustomerFinancialEnvelope,CustomerFinancialRefundQuote,CustomerFinancialRefundReview,CustomerFinancialQuoteInput,CustomerFinancialKind,CustomerFinancialInput,CustomerFinancialIntent,CustomerFinancialResult,CustomerFinancialOperationState,CustomerFinancialJson} from '@/types/customerWorkFinancial';
type Basis=CustomerFinancialOrder|CustomerFinancialRefundReview;
function confirm(title:string,content:string):Promise<boolean>{return new Promise(resolve=>uni.showModal({title,content,success:value=>resolve(value.confirm),fail:()=>resolve(false)}));}
export interface CustomerFinancialOperations{
 manager:CustomerWorkController;order:Ref<CustomerFinancialEnvelope<CustomerFinancialOrder>|null>;review:Ref<CustomerFinancialEnvelope<CustomerFinancialRefundReview>|null>;busy:Ref<boolean>;error:Ref<string>;pending:Ref<CustomerFinancialIntent[]>;states:Ref<Record<string,CustomerFinancialOperationState>>;
 current:()=>boolean;clear:()=>void;clearDomain:()=>void;loadOrder:(id:number,no:string)=>Promise<CustomerFinancialOrder>;loadRefund:(id:number,no:string)=>Promise<CustomerFinancialRefundReview>;
 quote:(mode:'remaining'|'items',items:Array<{cart_row_id:number;cart_num:number}>)=>Promise<CustomerFinancialRefundQuote>;
 submit:(kind:CustomerFinancialKind,basis:Basis,payload:Record<string,CustomerFinancialJson>)=>Promise<CustomerFinancialResult|null>;
 check:(intent:CustomerFinancialIntent)=>Promise<void>;restore:(intent:CustomerFinancialIntent)=>Promise<void>;resume:(intent:CustomerFinancialIntent)=>Promise<void>;abandon:(intent:CustomerFinancialIntent)=>Promise<void>;acknowledge:(intent:CustomerFinancialIntent)=>Promise<void>;
 checkRelevant:(paymentOrderId:number)=>Promise<void>;
 canRestore:(intent:CustomerFinancialIntent)=>boolean;canResume:(intent:CustomerFinancialIntent)=>boolean;canAbandon:(intent:CustomerFinancialIntent)=>boolean;
}
export function useCustomerWorkFinancialOperations(manager:CustomerWorkController):CustomerFinancialOperations{
 const order=ref<CustomerFinancialEnvelope<CustomerFinancialOrder>|null>(null),review=ref<CustomerFinancialEnvelope<CustomerFinancialRefundReview>|null>(null),busy=ref(false),error=ref(''),pending=ref<CustomerFinancialIntent[]>([]),states=ref<Record<string,CustomerFinancialOperationState>>({});
 const requests=new Set<CustomerFinancialRequests>();let epoch=0,disposed=false;
 const current=()=>!disposed&&manager.current()&&manager.auth.isLoggedIn;
 const sameOwner=(scope:CustomerFinancialRequests)=>current()&&manager.auth.uid===scope.owner.uid&&manager.auth.token===scope.owner.token&&manager.auth.sessionVersion===scope.owner.version;
 const owns=(intent:CustomerFinancialIntent)=>current()&&intent.actor_uid===manager.auth.uid;
 function refreshPending(){if(!current()){pending.value=[];return;}try{pending.value=customerFinancialPending().filter(intent=>intent.actor_uid===manager.auth.uid);}catch(failure){pending.value=[];error.value=failure instanceof Error?failure.message:'原财务记录需核对';}}
 function clearRequests(){epoch++;for(const scope of requests)scope.abort();requests.clear();order.value=null;review.value=null;busy.value=false;error.value='';}
 function clear(){clearRequests();pending.value=[];states.value={};}
 function clearDomain(){clearRequests();if(current())refreshPending();else{pending.value=[];states.value={};}}
 function scope(fence?:()=>boolean){const version=epoch,value=createCustomerFinancialRequests(()=>current()&&epoch===version&&(!fence||fence()));requests.add(value);return value;}
 function close(value:CustomerFinancialRequests){value.abort();requests.delete(value);}
 function known(intent:CustomerFinancialIntent){if(!isCustomerFinancialIntent(intent)||!owns(intent))throw Error('原财务意图不属于当前账号');const saved=customerFinancialPending().find(row=>row.request_key===intent.request_key);if(!saved||customerWorkCanonicalJson(saved)!==customerWorkCanonicalJson(intent))throw Error('原财务内容已变化，请保留原记录核对');}
 function state(intent:CustomerFinancialIntent,result:CustomerFinancialResult|null,checked=false,message=''){states.value={...states.value,[intent.request_key]:{result,checked,unknown:!result?.receipt,error:message}};}
 function matches(authority:CustomerFinancialEnvelope<Basis>){const context=manager.context.value;return current()&&context&&authority.actor_uid===manager.auth.uid&&authority.scope_key===context.scope_key&&authority.principal.service_id===context.principal.service_id&&authority.consistency_key===context.consistency_key;}
 function parse<T>(value:unknown,guard:(data:unknown)=>data is T,owner:CustomerFinancialRequests){const context=manager.context.value;if(!owner.active()||!context)throw Error('当前财务身份已变化');try{return parseCustomerFinancialEnvelope(value,owner.owner.uid,guard,context);}catch(failure){if(owner.active())manager.invalidate(failure);throw failure;}}
 function failed(owner:CustomerFinancialRequests,intent:CustomerFinancialIntent|undefined,failure:unknown){if(!owner.active()||!sameOwner(owner))return;const msg=failure instanceof Error?customerFinancialNotice(failure.message):'原财务结果未确认，请查询原编号';if(failure instanceof RequestError&&(failure.httpStatus===403||[410000,410001,410002].includes(Number(failure.status))))manager.invalidate(Error('当前财务权限已变化，请重新读取'));if(!sameOwner(owner))return;refreshPending();if(intent){const previous=states.value[intent.request_key];state(intent,previous?.result??null,previous?.checked??false,msg);}error.value=msg;}
 function consume(value:unknown,intent:CustomerFinancialIntent,owner:CustomerFinancialRequests,checked=false){let result:CustomerFinancialResult;try{result=parseCustomerFinancialResult(value,intent);}catch(failure){if(owner.active())manager.invalidate(Error('原财务回执不匹配，已清除当前订单资料，请继续核对原编号'));throw failure;}
  if(result.receipt?.service_id===0||result.receipt?.outcome==='rollback-rejected')manager.invalidate(Error('当前财务依据已变化，请重新读取权限与订单'));
  if(sameOwner(owner)){refreshPending();state(intent,result,checked||!!result.receipt);error.value=customerFinancialResultMessage(result);}return result;
 }
 async function loadOrder(id:number,no:string){refreshPending();const owner=scope(manager.fence());try{const response=parse(await owner.request(`/mobile/work/financial/orders/${id}`,'GET',{scope_key:manager.context.value?.scope_key,order_no:no}),isCustomerFinancialOrder,owner);if(!owner.active())throw Error('订单财务页面已变化');if(response.data.order_id!==id||response.data.order_no!==no||response.data.requested_order_no!==no){manager.invalidate(Error('订单财务目标不匹配'));throw Error('订单财务目标不匹配');}order.value=response;review.value=null;return response.data;}catch(failure){if(owner.active()){order.value=null;error.value=failure instanceof Error?customerFinancialNotice(failure.message):'财务依据暂不可用';}throw failure;}finally{close(owner);}}
 async function loadRefund(id:number,no:string){refreshPending();const owner=scope(manager.fence());try{const response=parse(await owner.request(`/mobile/work/financial/refunds/${id}`,'GET',{scope_key:manager.context.value?.scope_key,refund_no:no}),isCustomerFinancialRefundReview,owner);if(!owner.active())throw Error('退款财务页面已变化');if(response.data.refund_id!==id||response.data.refund_no!==no||response.data.requested_refund_no!==no){manager.invalidate(Error('退款财务目标不匹配'));throw Error('退款财务目标不匹配');}review.value=response;order.value=null;return response.data;}catch(failure){if(owner.active()){review.value=null;error.value=failure instanceof Error?customerFinancialNotice(failure.message):'退款依据暂不可用';}throw failure;}finally{close(owner);}}
 async function quote(mode:'remaining'|'items',items:Array<{cart_row_id:number;cart_num:number}>){const authority=order.value;if(!authority||!matches(authority)||!authority.data.readiness.quote)throw Error('当前订单暂不可核对退款报价');const body:CustomerFinancialQuoteInput={version:'customer-work-financial-refund-quote-v1',scope_key:authority.scope_key,order_id:authority.data.order_id,expected_order_revision:authority.data.order_revision,expected_financial_revision:authority.data.financial_revision,mode,items:JSON.parse(customerWorkCanonicalJson(items))},owner=scope(manager.fence());try{const response=parse(await owner.request('/mobile/work/financial/refund-quote','POST',body as unknown as Record<string,unknown>),isCustomerFinancialRefundQuote,owner);const value=response.data;if(!owner.active()||order.value!==authority)throw Error('原退款报价依据已变化');if(value.order_id!==body.order_id||value.order_no!==authority.data.order_no||value.payment_order_id!==authority.data.payment_order_id||value.order_revision!==body.expected_order_revision||value.financial_revision!==body.expected_financial_revision||value.mode!==mode||mode==='items'&&(value.items.length!==items.length||value.items.some(row=>!items.some(item=>item.cart_row_id===row.cart_row_id&&item.cart_num===row.cart_num)))){manager.invalidate(Error('实际退款报价目标或数量不匹配'));throw Error('实际退款报价目标或数量不匹配');}return value;}catch(failure){if(owner.active())failed(owner,undefined,failure);throw failure;}finally{close(owner);}}
 function authorityFor(kind:CustomerFinancialKind){return ['change_price','confirm_offline','refund_create'].includes(kind)?order.value:review.value;}
 async function submit(kind:CustomerFinancialKind,basis:Basis,payload:Record<string,CustomerFinancialJson>):Promise<CustomerFinancialResult|null>{
  if(busy.value||!current())return null;const authority=authorityFor(kind);if(!authority||!matches(authority)||!authority.data.readiness.writes||!authority.data.actions[kind].available||customerWorkCanonicalJson(authority.data)!==customerWorkCanonicalJson(basis)){error.value='当前财务目标或资格已变化，请重新读取';return null;}
  const snapshot=JSON.parse(customerWorkCanonicalJson(basis)) as Basis,input:CustomerFinancialInput={version:CUSTOMER_FINANCIAL_VERSION,scope_key:authority.scope_key,order_id:snapshot.order_id,expected_order_revision:snapshot.order_revision,expected_financial_revision:snapshot.financial_revision,payload:JSON.parse(customerWorkCanonicalJson(payload))};
  if(!isCustomerFinancialInput(input,kind)){error.value='财务编辑内容无效，尚未提交';return null;}
  refreshPending();if(pending.value.some(intent=>intent.payment_order_id===snapshot.payment_order_id&&!customerFinancialTerminal(states.value[intent.request_key]?.result??{receipt:null,replayed:false,execution:null}))){error.value='该支付订单存在待确认原财务操作，请先查询原结果';return null;}
  const owner=scope(manager.fence());busy.value=true;error.value='';let intent:CustomerFinancialIntent|undefined;
  const valid=()=>owner.active()&&authorityFor(kind)===authority&&matches(authority)&&customerWorkCanonicalJson(authority.data)===customerWorkCanonicalJson(snapshot);
  try{
   const amount=payload.price??payload.refund_price,title=CUSTOMER_FINANCIAL_NAMES[kind],note=kind==='confirm_offline'?'请先确认实际已收到本订单的线下款项。':kind==='refund_return'?'这里只同意退货，实际收到并验收后再执行退款。':kind==='refund_execute'?'外部渠道受理不代表资金已退回。':kind==='refund_create'?'本次创建退款申请，资金需要另行确认执行。':'';
   if(!await confirm('确认'+title,`订单 ${snapshot.order_no}${amount!==undefined?' · 金额 ¥'+amount:''}。${note}`)||!valid())return null;
   const key=await customerWorkRequestKey();if(!valid())return null;
   intent=JSON.parse(customerWorkCanonicalJson({version:'customer-work-financial-pending-v1',actor_uid:owner.owner.uid,service_id:authority.principal.service_id,scope_key:authority.scope_key,kind,request_key:key,request_hash:financialIntentHash(owner.owner.uid,kind,input),order_no:snapshot.order_no,payment_order_id:snapshot.payment_order_id,payment_order_no:snapshot.payment_order_no,body:input,endpoint:financialEndpoint(kind),method:'POST',created_at:Math.floor(Date.now()/1000)}));
   retainCustomerFinancialIntent(intent!);refreshPending();state(intent!,null);
   const response=await owner.request(intent!.endpoint,'POST',intent!.body as unknown as Record<string,unknown>,intent!.request_key);if(!owner.active())return null;return consume(response,intent!,owner);
  }catch(failure){failed(owner,intent,failure);return null;}finally{if(owner.active())busy.value=false;close(owner);}
 }
 async function check(intent:CustomerFinancialIntent){if(busy.value||!owns(intent))return;const owner=scope();busy.value=true;error.value='';try{known(intent);const value=await owner.request(`/mobile/work/financial/operations/${intent.request_key}`);if(owner.active())consume(value,intent,owner,true);}catch(failure){failed(owner,intent,failure);}finally{if(owner.active())busy.value=false;close(owner);}}
 async function checkRelevant(paymentOrderId:number){refreshPending();for(const intent of [...pending.value].filter(value=>value.payment_order_id===paymentOrderId)){if(!current()||!manager.context.value)break;await check(intent);}}
 function sameIntentScope(intent:CustomerFinancialIntent){const context=manager.context.value;return owns(intent)&&!!context&&context.scope_key===intent.scope_key&&context.principal.service_id===intent.service_id;}
 function canRestore(intent:CustomerFinancialIntent){const value=states.value[intent.request_key],authority=authorityFor(intent.kind);if(!owns(intent)||busy.value||!value?.checked||value.result?.receipt||!sameIntentScope(intent)||!authority||!matches(authority)||!authority.data.readiness.writes||!authority.data.actions[intent.kind].available||authority.data.order_id!==intent.body.order_id||authority.data.payment_order_id!==intent.payment_order_id||authority.data.order_revision!==intent.body.expected_order_revision||authority.data.financial_revision!==intent.body.expected_financial_revision)return false;return !('refund_id'in authority.data)||authority.data.refund_id===intent.body.payload.refund_id&&authority.data.refund_no===intent.body.payload.refund_no&&authority.data.refund_revision===intent.body.payload.expected_refund_revision&&authority.data.review_fingerprint===intent.body.payload.review_fingerprint;}
 function canResume(intent:CustomerFinancialIntent){const value=states.value[intent.request_key]?.result;return !busy.value&&sameIntentScope(intent)&&intent.kind==='refund_execute'&&value?.receipt?.outcome==='provider-admitted'&&value.execution?.can_resume===true&&!customerFinancialTerminal(value);}
 function canAbandon(intent:CustomerFinancialIntent){const value=states.value[intent.request_key];return owns(intent)&&!busy.value&&!!value?.checked&&!value.result?.receipt;}
 async function retry(intent:CustomerFinancialIntent,operation:'restore'|'resume'|'abandon'){
  const allowed=()=>operation==='restore'?canRestore(intent):operation==='resume'?canResume(intent):canAbandon(intent);if(!allowed())return;
  const owner=scope(operation==='abandon'?undefined:manager.fence());busy.value=true;error.value='';
  try{known(intent);const title=operation==='restore'?'恢复原财务意图':operation==='resume'?'核对原退款渠道':'放弃尚未执行的原意图',note=operation==='resume'?'使用原编号和完整原内容查询原渠道事实，不重新发起退款。':operation==='abandon'?'保留已经受理或执行的真实结果，只阻止尚未执行的原意图。':'已查询原结果，仍按原编号和完整原内容恢复这一次操作。';
   // The busy flag belongs to this call; repeat the non-busy eligibility check after the native modal.
   if(!await confirm(title,note)||!owner.active()||!sameOwner(owner))return;busy.value=false;const stillAllowed=allowed();busy.value=true;if(!stillAllowed)return;
   known(intent);
   const path=operation==='abandon'?`/mobile/work/financial/operations/${intent.request_key}/abandon`:intent.endpoint,body=operation==='abandon'?{kind:intent.kind,input:intent.body}:intent.body;
   const response=await owner.request(path,'POST',body as unknown as Record<string,unknown>,intent.request_key);if(owner.active())consume(response,intent,owner,true);
  }catch(failure){failed(owner,intent,failure);}finally{if(owner.active())busy.value=false;close(owner);}
 }
 async function acknowledge(intent:CustomerFinancialIntent){const value=states.value[intent.request_key]?.result;if(busy.value||!owns(intent)||!value||!customerFinancialTerminal(value))return;const owner=scope();busy.value=true;try{known(intent);const frozen=customerWorkCanonicalJson(value);if(!await confirm('确认原财务结果','已核对此原操作的实际结果，关闭这条本机待确认记录。')||!owner.active()||customerWorkCanonicalJson(states.value[intent.request_key]?.result)!==frozen)return;known(intent);releaseCustomerFinancialIntent(intent.request_key);const next={...states.value};delete next[intent.request_key];states.value=next;refreshPending();}catch(failure){failed(owner,intent,failure);}finally{if(owner.active())busy.value=false;close(owner);}}
 onShow(refreshPending);onHide(clear);onUnload(()=>{disposed=true;clear();});
 watch(()=>[manager.auth.uid,manager.auth.token,manager.auth.sessionVersion],()=>{clear();refreshPending();},{flush:'sync'});
 watch(()=>manager.context.value,(value,previous)=>{if(previous&&(!value||value.scope_key!==previous.scope_key||value.principal.service_id!==previous.principal.service_id||value.consistency_key!==previous.consistency_key))clearDomain();},{flush:'sync'});
 return{manager,order,review,busy,error,pending,states,current,clear,clearDomain,loadOrder,loadRefund,quote,submit,check,checkRelevant,restore:intent=>retry(intent,'restore'),resume:intent=>retry(intent,'resume'),abandon:intent=>retry(intent,'abandon'),acknowledge,canRestore,canResume,canAbandon};
}
