<template><view class="merchant-dialog"><view class="merchant-dialog-panel"><text class="merchant-subtitle">{{ title }}</text><text class="merchant-note">{{ order.order_id }} · 当前金额 ¥{{ order.pay_price }}</text><view class="merchant-divider" /><view v-if="action==='remark'" class="merchant-form-field"><text>商家备注</text><textarea v-model="remark" :maxlength="512" placeholder="填写本订单的处理备注" /></view><view v-else-if="action==='change_price'" class="merchant-form-field"><text>修改后的实付款（元）</text><input v-model="price" type="digit" maxlength="15" placeholder="最多两位小数" /><text class="merchant-note">核对当前订单金额，确认后将修改未支付订单的价格。</text></view><view v-else-if="action==='confirm_offline'" class="merchant-warning">请先确认线下实际收到本订单款项。确认付款会更新真实订单、账务及奖励状态。</view><text v-if="error" class="merchant-money">{{ error }}</text><view class="merchant-dialog-buttons"><button :disabled="manager.busy.value" @tap="emit('close')">取消</button><button :disabled="manager.busy.value || !manager.context.value?.data.capabilities[action] || !order.actions[action].available" @tap="submit">{{ manager.busy.value ? '处理中…' : '核对并提交' }}</button></view></view></view></template>
<script setup lang="ts">
import { computed,ref } from 'vue';import type { MerchantController } from '@/composables/useMerchantOrders';import type { MerchantOrderListItem,MerchantOrderAction } from '@/types/merchantOrders';import { merchantMoneyInput } from '@/utils/merchantOrders';
const props=defineProps<{manager:MerchantController;order:MerchantOrderListItem;action:MerchantOrderAction}>(),emit=defineEmits<{close:[];saved:[]}>(),remark=ref(props.order.remark),price=ref(props.order.pay_price),error=ref('');
const title=computed(()=>props.action==='remark'?'订单备注':props.action==='change_price'?'修改价格':'确认线下收款');
async function submit(){const {manager,order,action}=props;if(manager.busy.value||!manager.current()||!order.actions[action].available||!manager.context.value?.data.capabilities[action]||manager.selectedStore.value!==order.store_id)return;error.value='';
  try{let payload:Record<string,unknown>={};if(action==='remark'){const value=remark.value.trim();if(!value||value.length>512)throw Error('请填写不超过 512 字的备注');payload={remark:value};}else if(action==='change_price')payload={price:merchantMoneyInput(price.value)};else if(action!=='confirm_offline')throw Error('该操作请打开完整订单页面');
    const wire={version:'merchant-order-operation-v1',store_id:order.store_id,scope_key:manager.context.value.scope_key,order_id:order.id,expected_order_revision:order.revision,payload},financial=action!=='remark',path=financial?`/store/manager/order/financial/${action==='change_price'?'price':'offline'}`:'/store/manager/order/remark';
    const result=await manager.execute({action,order_id:order.order_id,endpoint:path,body:wire,receipt_path:'/store/manager/order/operation/{requestKey}',receipt_method:'GET',abandon_path:`/store/manager/order/operation/abandon/${action}`});
    if(!manager.current()||!result)return;const expected=action==='remark'?'remark-saved':action==='change_price'?'price-changed':'offline-paid';if(result.outcome!==expected){error.value='原操作已核对但未执行，请确认待处理记录后重新读取。';return;}uni.showToast({title:'操作已确认',icon:'success'});emit('saved');
  }catch(failure){if(manager.current())error.value=manager.unresolved.value.some(intent=>intent.order_id===order.order_id)?'原操作结果待确认，请关闭此窗口并查询原操作。':failure instanceof Error?failure.message:'尚未提交';}
}
</script>
