const assert=require('node:assert/strict'),test=require('node:test'),path=require('node:path');
const {runtime,tick,deferred,render}=require('./user-center-runtime.cjs');
const root=path.resolve(__dirname,'..');
const scopes={sales:'global_fulfillment_orders',order_totals:'global_fulfillment_orders',order_state_counts:'platform_fulfillment_orders',refund_counts:'global_refunds',inventory:'global_products',visits:'global_product_visits'};
function envelope(data,uid=11){return {version:'customer-work-read-v1',actor_uid:uid,principal:{kind:'customer-order-manager',service_id:1,scope:'global'},scope_key:'a'.repeat(64),consistency_key:'b'.repeat(64),data:{...data,metric_scopes:scopes}};}
function cart(){return {id:1,cart_id:'c1',product_id:1,cart_num:1,refund_num:0,surplus_num:1,is_gift:0,truePrice:'10.00',sum_true_price:'10.00',productInfo:{store_name:'测试商品',image:'/static/logo.png',price:'10.00',attrInfo:{suk:'默认',image:'/static/logo.png',price:'10.00'}}};}
function order(id=1){return {id,pid:0,order_id:'ORDER_'+id,uid:21,store_id:0,supplier_id:0,nickname:'测试买家',real_name:'测试收货人',user_phone:'13800000000',user_address:'测试地址',total_num:1,total_price:'10.00',total_postage:'0.00',pay_price:'10.00',pay_postage:'0.00',paid:1,status:1,shipping_type:1,pay_type:'weixin',type:0,type_name:'普通订单',refund_status:0,refund_type:0,delivery_type:'express',delivery_name:'测试快递',delivery_code:'TEST',delivery_id:'TEST123',mark:'<script>unsafe()</script>',remark:'测试备注',add_time:1791075600,pay_time:1791075600,_add_time:'2026-10-04 09:00:00',_pay_time:'2026-10-04 09:00:00',_status:{_type:2,_title:'待收货',_msg:'已发货'},cartInfo:[cart()],refund:[{id:1,order_id:'REFUND_1',refund_type:0,refund_num:1,refund_price:'1.00'}],revision:'c'.repeat(64),write_available:false};}
function refund(id=1){return {id,order_id:'REFUND_'+id,store_order_id:id,store_order_sn:'ORDER_'+id,uid:21,apply_type:0,refund_type:0,refund_price:'1.00',refunded_price:'0.00',refund_num:1,refund_reason:'测试原因',refund_explain:'测试说明',refuse_reason:'',remark:'',add_time:1791075600,_add_time:'2026-10-04 09:00:00',_status:{status_name:'待审核'},cartInfo:[cart()],write_available:false,refund_express:'',refund_express_name:'',refund_phone:''};}
function fixtureData(call){const route=new URL(call.url,'http://localhost').pathname.replace('/api/mobile/work/',''),q=call.data??{};
  if(route==='context')return {profile:{uid:11,nickname:'测试经营账号',phone:'13900000000',avatar:'/static/logo.png'},capabilities:{statistics:true,orders:true,refunds:true,logistics:true,product_management:false,user_management:false,assisted_order:false,writes:false}};
  const summary={after_price:'10.00',growth_rate:20,increase_time:'2.00',increase_time_status:1,after_number:1,after_pay_number:1,today_visits:2};
  if(route==='overview')return {today:summary,badges:{unshipped_count:1,refunding_count:1,refunded_count:0,refund_count:1,outofstock:0,policeforce:0}};
  if(route==='statistics')return {type:Number(q.type||1),summary,counters:{order_count:2,unpaid_count:0,unshipped_count:1,received_count:1,evaluated_count:0,unwritoff_count:0,complete_count:0,refunding_count:1,refunded_count:0,refund_count:1,sum_price:'20.00',todayPrice:'10.00',todayCount:1,proPrice:'10.00',proCount:1,monthPrice:'20.00',monthCount:2}};
  if(route==='trend'){const type=Number(q.type||1),n=type===1?2:type,today=new Date(Date.now()+28800000).toISOString().slice(0,10),last=Date.parse(today+'T00:00:00Z');return {type,list:Array.from({length:n},(_,i)=>{const date=new Date(last-(n-i-1)*86400000).toISOString().slice(0,10);return {date,time:date.slice(5),num:i===n-1?1:0,price:i===n-1?'10.00':'0.00'};})};}
  if(route==='statistics/orders'){const date=new Date(Date.now()+28800000).toISOString().slice(0,10);return {list:[{date,time:date.slice(5),price:'10.00',count:1,visit:2,add_time:1791075600}],count:1,page:Number(q.page||1),limit:10,has_more:false};}
  if(route==='orders')return {list:[order(Number(q.page||1))],count:2,page:Number(q.page||1),limit:10,has_more:Number(q.page||1)===1};
  if(route==='refunds')return {list:[refund(Number(q.page||1))],count:2,page:Number(q.page||1),limit:10,has_more:Number(q.page||1)===1};
  if(route.startsWith('refunds/'))return {...refund(1),real_name:'测试收货人',user_phone:'13800000000',user_address:'测试地址',refund_img:[],refund_goods_img:[]};
  if(route.endsWith('/logistics')){const orderId=decodeURIComponent(route.split('/')[1]),p={orderId,deliveryStatus:'已发货',expressName:'测试快递',expressCode:'TEST',expressNo:'TEST123',trackingState:'not_configured',trackingSource:'merchant',lastUpdatedAt:0,message:'物流服务尚未配置',traces:[]};return {...p,packages:[p],order:{order_id:orderId,delivery_id:p.expressNo,delivery_name:p.expressName,delivery_code:p.expressCode,delivery_type:'express'}};}
  if(route.endsWith('/fulfillment')||route.endsWith('/remark')||route.startsWith('fulfillment/'))return require('./customer-work-fulfillment-runtime.test.cjs').fulfillmentFixture(call).data.data;
  if(route.startsWith('orders/'))return {...order(1),split:[],customer:{uid:21,nickname:'测试买家',avatar:''},custom_form:{留言:'<script>unsafe()</script>'},refund_img:[],refund_goods_img:[],vip_true_price:'0.00',refund_reason_wap:'',refund_reason_wap_explain:'',refund_reason_time:0};
  throw Error('Unexpected actual request '+route);
}
function financialEnvelope(data){const value=envelope({});value.data=data;return value;}
function financialOrder(id=1,writes=false){return {version:'customer-work-financial-order-v1',requested_order_no:'ORDER_'+id,order_id:id,order_no:'ORDER_'+id,payment_order_id:id,payment_order_no:'ORDER_'+id,uid:21,store_id:0,supplier_id:0,order_revision:'c'.repeat(64),financial_revision:'d'.repeat(64),paid:1,status:1,pay_type:'weixin',pay_price:'10.00',refunded_price:'0.00',change_price:'0.00',total_num:1,readiness:{writes,quote:writes,reason:writes?'':'当前财务功能尚未就绪',provider_max_amount:'21474836.47'},actions:Object.fromEntries(['change_price','confirm_offline','refund_create','refund_return','refund_refuse','refund_execute','refund_remark'].map(kind=>[kind,{available:writes,reason:writes?'':'当前财务功能尚未就绪'}]))};}
function financialReview(id=1,writes=false){const o=financialOrder(id,writes);delete o.requested_order_no;delete o.paid;delete o.status;delete o.pay_type;delete o.pay_price;delete o.change_price;delete o.total_num;return {...o,version:'customer-work-financial-refund-review-v1',requested_refund_no:'REFUND_'+id,refund_id:id,refund_no:'REFUND_'+id,refund_revision:'e'.repeat(64),review_fingerprint:'f'.repeat(64),apply_type:1,refund_type:0,refund_price:'1.00',remark:'',requires_received_confirmation:false,return_evidence:{reason:'测试原因',explain:'测试说明',images:[],goods_images:[],express_name:'',express_no:'',phone:''}};}
function financialFixture(call){const route=new URL(call.url,'http://localhost').pathname.replace('/api/mobile/work/financial/','');if(route.startsWith('orders/'))return {data:financialEnvelope(financialOrder(Number(route.split('/')[1])))};if(route.startsWith('refunds/'))return {data:financialEnvelope(financialReview(Number(route.split('/')[1])))};if(route.startsWith('operations/'))return {data:{receipt:null,replayed:false,execution:null}};throw Error('Unexpected actual financial request '+route);}
const fixture=call=>call.url.includes('/mobile/work/financial/')?financialFixture(call):({data:envelope(fixtureData(call))});
module.exports={envelope,fixtureData,fixture,order,refund,scopes,financialEnvelope,financialOrder,financialReview,financialFixture};
if(require.main===module){
test('shared strict query, identity, image and calendar contracts',()=>{const r=runtime({send:fixture});try{r.load(path.join(root,'src/utils/customerWork.test.ts')).runCustomerWorkPureTests(assert);}finally{r.stop();}});
for(const [name,query,dataKey]of [['index',{},'overview'],['statistics',{},'statistics'],['orders',{types:'0'},'rows'],['orderDetail',{id:'ORDER_1',types:'0',goname:'look'},'order'],['refunds',{refundTypes:'0'},'rows'],['refundDetail',{id:'REFUND_1'},'refund'],['logistics',{orderId:'ORDER_1'},'logistics']])test('actual '+name+' page reads scoped DTO and clears on hide/unload',async()=>{const r=runtime({send:fixture,component:'pages/customer-work/'+name+'.vue'});try{await r.start(query);assert.equal(r.page.manager.error.value,'');assert.ok(r.page[dataKey].value);assert.equal(r.calls[0].url.endsWith('/api/mobile/work/context'),true);for(const call of r.calls){assert.equal(call.method,'GET');assert.match(call.header['Authori-zation'],/^Bearer /);if(!call.url.endsWith('/context'))assert.equal(call.data.scope_key,'a'.repeat(64));}r.hooks.onHide();assert.equal(r.page.manager.context.value,null);assert.ok(Array.isArray(r.page[dataKey].value)?r.page[dataKey].value.length===0:r.page[dataKey].value===null);r.hooks.onShow();await tick();assert.ok(r.page.manager.context.value);r.hooks.onUnload();assert.equal(r.page.manager.context.value,null);}finally{r.stop();}});
test('actual order/refund pagination and old zero selectors',async()=>{for(const name of ['orders','refunds']){const r=runtime({send:fixture,component:'pages/customer-work/'+name+'.vue'});try{await r.start(name==='orders'?{types:'0'}:{refundTypes:'0'});const first=r.calls.find(c=>c.url.endsWith('/'+name));assert.equal(first.data[name==='orders'?'status':'refundTypes'],'0');await r.page.more();assert.equal(r.page.rows.value.length,2);assert.equal(r.page.rows.value[1].id,2);assert.equal(r.page.hasMore.value,false);if(name==='orders'){r.page.chooseStatus({detail:{value:0}});await tick();assert.equal(r.calls.at(-1).data.status,'');}else for(const index of [1,2,3,0]){r.page.chooseRefund(index);await tick();assert.equal(r.calls.at(-1).data.refundTypes,['0','2','5','6'][index]);}}finally{r.stop();}}});
test('actual 1/7/30 statistic methods preserve zero days and scoped headings',async()=>{const r=runtime({send:fixture,component:'pages/customer-work/statistics.vue'});try{await r.start();for(const index of [0,1,2]){if(index){r.page.choosePeriod({detail:{value:index}});await tick();}assert.equal(r.page.trend.value.list.length,index===0?2:[1,7,30][index]);assert.equal(r.page.trend.value.list[0].num,0);assert.equal(r.page.manager.error.value,'');}}finally{r.stop();}});
test('account ABA fences late response even after the same UID returns',async()=>{const delayed=deferred();let first=true;const r=runtime({component:'pages/customer-work/orders.vue',send:call=>{if(call.url.endsWith('/orders')&&first){first=false;return delayed.promise;}return fixture(call);}});try{await r.start();assert.equal(r.page.rows.value.length,0);r.auth.setLogin('second-account',12);r.auth.setLogin('synthetic-local-token',11);await tick();assert.equal(r.page.rows.value[0].order_id,'ORDER_1');delayed.resolve({data:envelope({...fixtureData({url:'/api/mobile/work/orders',data:{}}),list:[order(99)]})});await tick();assert.equal(r.page.rows.value[0].order_id,'ORDER_1');assert.ok(r.aborts.length);}finally{r.stop();}});
test('revocation and inconsistent authority immediately erase every page data',async()=>{for(const failure of ['revoke','actor','scope','consistency','profile']){let broken=false;const r=runtime({send:call=>{if(!broken)return fixture(call);if(failure==='revoke')return {status:403,msg:'role revoked'};const value=envelope(fixtureData(call));if(failure==='actor')value.actor_uid=12;if(failure==='scope')value.scope_key='d'.repeat(64);if(failure==='consistency'&&!call.url.endsWith('/context'))value.consistency_key='d'.repeat(64);if(failure==='profile'&&call.url.endsWith('/context'))value.data.profile.uid=12;return {data:value};},component:'pages/customer-work/orders.vue'});try{await r.start();assert.equal(r.page.rows.value.length,1);broken=true;if(failure==='scope'){await r.page.more();assert.equal(r.page.rows.value.length,0);}else{await r.page.manager.load();assert.equal(r.page.rows.value.length,0);}assert.equal(r.page.manager.context.value,null);assert.ok(r.page.manager.error.value);}finally{r.stop();}}});
test('transport timeout aborts actual request and cannot commit late data',async()=>{const late=deferred(),r=runtime({send:()=>late.promise});try{const request=r.load(path.join(root,'src/api/customerWork.ts')).createCustomerWorkRequests(()=>true,15),promise=request.request('/mobile/work/context');await assert.rejects(promise,/超时/);assert.ok(r.aborts.length);late.resolve(fixture({url:'/api/mobile/work/context'}));await tick();request.abort();}finally{r.stop();}});
test('malformed duplicate route has no authorized request and detail identity fails closed',async()=>{const r=runtime({send:fixture,component:'pages/customer-work/orderDetail.vue'});try{await r.start({id:'ORDER_1',orderId:'ORDER_1'});assert.equal(r.calls.length,0);assert.ok(r.page.manager.error.value);}finally{r.stop();}const bad=runtime({component:'pages/customer-work/orderDetail.vue',send:call=>{const data=fixtureData(call);if(call.url.includes('/orders/'))data.order_id='ORDER_99';return {data:envelope(data)};}});try{await bad.start({orderId:'ORDER_1'});assert.equal(bad.page.order.value,null);assert.equal(bad.page.manager.context.value,null);}finally{bad.stop();}});
test('actual rendered detail escapes customer text and contains only real read destinations',async()=>{const r=runtime({send:fixture,component:'pages/customer-work/orderDetail.vue'});try{await r.start({orderId:'ORDER_1'});await render(r,'components/ThemePage.vue');await render(r,'components/customerWork/CustomerWorkRecoveryPanel.vue');await render(r,'components/customerWork/CustomerWorkShell.vue');const html=await render(r,'pages/customer-work/orderDetail.vue',r.page);assert.ok(html.includes('&lt;script&gt;unsafe()&lt;/script&gt;'));assert.ok(html.includes('订单财务'));assert.ok(html.includes('修改管理备注'));assert.ok(html.includes('核对并发货'));assert.equal(html.includes('<script>unsafe()'),false);}finally{r.stop();}});
}
