const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const vue=require('vue'),{runtime,tick,deferred}=require('./uni-store-runtime.cjs');
const dir=path.resolve(__dirname,'../src');
const baseDesign={navList:[0,1,2,3,4],openShare:1,pictureConfig:0,swiperDot:1,showPrice:[0,1],isOpen:[3,4,5,1,2,0],showSvip:1,showRank:1,showService:[0,1,2,3],showReply:1,replyNum:3,showMatch:1,matchNum:3,showRecommend:1,recommendNum:12,menuList:[0,1,2],showCart:1,showCommunity:1,communityNum:3};
const hint=(price='8.00',type='level',enabled=true)=>({enabled,price,price_type:type,level_name:type==='level'?'银卡':'',vip_price:'9.00',level_price:'8.00'});
const reply=(id=1)=>({id,product_id:70,uid:9,nickname:'真实评价',avatar:'/avatar.png',comment:'实际商品不错',suk:'红',sku:'红',product_score:5,service_score:5,delivery_score:5,star:5,pics:['/review.png'],merchant_reply:'',merchant_reply_content:'',merchant_reply_time:'',add_time:'2026-10-02',praise:0,is_praise:false});
function goods(design={}){return{id:70,storeName:'真实普通商品',storeInfo:'普通规格',price:'10.00',stock:8,image:'/product.png',sliderImage:['/one.png','/two.png'],isVip:1,cart_button:1,productType:0,systemFormId:0,specType:1,userCollect:false,
  productAttr:[{attr_name:'颜色',attr_values:['红','蓝']}],attr_value:[{unique:'red001',suk:'红',price:'10.00',ot_price:'15.00',vip_price:'9.00',stock:8,image:'/red.png',member_price:'8.00',price_type:'level',level_name:'银卡',display_price:hint()},
    {unique:'blue001',suk:'蓝',price:'20.00',ot_price:'25.00',vip_price:'19.00',stock:2,image:'/blue.png',member_price:'18.00',price_type:'level',level_name:'银卡',display_price:{...hint('19.00','member'),vip_price:'19.00',level_price:'18.00'}}],
  product_detail_design:{value:{...structuredClone(baseDesign),...design},revision:'a'.repeat(64),configured:true,issues:[]},display_price:hint(),video_link:'https://media.example/product.mp4',description:'<p>真实商品介绍<img src="/api/assets/41?sig=fresh"></p><script>bad()</script>',
  ensure:[{id:1,name:'退换保障',image:'/ensure.png',desc:'具体保障说明'}],specs:[{name:'材质',value:'棉',sort:1}],rank:2,rank_type:1,rank_name:'热销榜',reply:[reply()],replyCount:12,replyChance:95,
  elegant_list:[{id:61,title:'真实商品晒单',image:'/post.png',content_type:1}],elegant_count:11,recommend:Array.from({length:24},(_,i)=>({id:i+100,store_name:`推荐商品${i}`,image:'/recommend.png',price:'0.10'})),
  site_url:'https://shop.example',site_name:'商城',share_qrcode:1,product_poster_title:'普通好物',routine_contact_type:0};}
const bundle=()=>({id:5,type:0,title:'真实搭配购',products:[1,2].map(id=>({id,product_id:id+70,productValue:[{unique:'red001',stock:8,price:'0.10'}]}))});
function setup({product=goods(),storage=new Map(),override=()=>undefined,component='pages/goods/detail.vue'}={}){
  const r=runtime({storage,component,send:call=>override(call)??(/\/product\/detail\/\d+$/u.test(call.url)?{data:product}:call.url.includes('/store_discounts/list/')?{data:[bundle()]}:call.url.includes('/product/detail/activity/')?{data:{coupons:[{id:8,coupon_title:'优惠券',coupon_price:'0.10',use_min_price:'1.00'}],promotions:[{id:9,name:'满减',desc:'真实活动说明'}]}}:call.url.endsWith('/cart/count')?{data:{count:2}}:call.url.endsWith('/cart/add')?{data:{id:91,cartNum:1}}:call.url.endsWith('/coupon/receive')?{data:{couponUserId:81}}:call.url.endsWith('/collect/add')?{data:{count:1}}:call.url.endsWith('/collect/del')?{data:null}:call.url.endsWith('/user/spread')?{data:null}:call.url.endsWith('/v2/diy/product_detail')?{data:{product_detail:structuredClone(baseDesign),product_detail_design_state:{configured:true,revision:'a'.repeat(64),issues:[]}}}:call.url.includes('/community')?{data:{list:[],count:0}}:{data:[]})});return r;
}
function render(r,file,setup){const sfc=require('@vue/compiler-sfc'),compiler=require('@vue/compiler-dom');const p=path.join(dir,file),descriptor=sfc.parse(fs.readFileSync(p,'utf8'),{filename:p}).descriptor,bindings=sfc.compileScript(descriptor,{id:'actual-detail-contract'}).bindings;
  const fn=new Function('Vue',compiler.compile(descriptor.template.content,{mode:'function',prefixIdentifiers:true,bindingMetadata:bindings,isCustomElement:tag=>['view','text','image','rich-text','swiper','swiper-item','video','scroll-view'].includes(tag)}).code)(vue);
  if(!setup){r.load(p).default.render=fn;return;}
  const app=vue.createSSRApp({render:fn,setup:()=>setup});app.use(require('pinia').getActivePinia());return require('@vue/server-renderer').renderToString(app).then(html=>html.replace(/<!--[\s\S]*?-->/gu,''));
}
const posts=r=>r.calls.filter(c=>c.url.endsWith('/cart/add'));

test('same snapshot nineteen settings preserve legacy ordinals and real modules in their old order',async()=>{const r=setup();try{await r.start({id:'70'});const p=r.checkout;assert.deepEqual(p.design.value.isOpen,[3,4,5,1,2,0]);render(r,'components/ThemePage.vue');const html=await render(r,'pages/goods/detail.vue',p);
  for(const content of ['真实普通商品','热销榜','服务保障','实际商品不错','真实商品晒单','真实搭配购','推荐商品0','真实商品介绍']){if(content==='服务保障')continue;assert.ok(html.includes(content),content);}
  const positions=['商品评价','商品晒单','搭配购','为你推荐'].map(value=>html.indexOf(value));assert.ok(positions.every((value,i)=>i===0||value>positions[i-1]));assert.doesNotMatch(html,/<script>bad/u);assert.equal(posts(r).length,0);
}finally{r.stop();}});

test('disabled modules do not fetch hidden marketing reviews or expose hidden service/menu/add-cart controls',async()=>{const r=setup({product:goods({navList:[],showService:[],showReply:0,showMatch:0,showRecommend:0,showCommunity:0,menuList:[],showCart:0,showSvip:0,showRank:0,isOpen:[],openShare:0})});try{await r.start({id:'70'});const p=r.checkout;render(r,'components/ThemePage.vue');const html=await render(r,'pages/goods/detail.vue',p);for(const text of ['商品评价','商品晒单','搭配购','为你推荐','加入购物车','库存 ','已售 ','购物车</'])assert.ok(!html.includes(text),text);p.openSku('cart');await p.confirmSku();assert.equal(posts(r).length,0);p.openSku('buy');await p.confirmSku();assert.equal(posts(r).length,1);assert.ok(!r.calls.some(c=>c.url.includes('/product/detail/activity/')));}finally{r.stop();}});

test('all four display selections change each SKU visible quote while real trading quote remains unchanged',async()=>{
  for(const [showPrice,visible,type]of [[[], '10.00',''],[[0],'8.00','level'],[[1],'9.00','member'],[[0,1],'8.00','level']]){const data=goods({showPrice});data.attr_value[0].display_price=hint(visible,type,!!showPrice.length);const r=setup({product:data});try{await r.start({id:'70'});const p=r.checkout;assert.equal(p.displayPrice.value,visible);assert.equal(p.selectedSku.value.member_price,'8.00');assert.equal(p.selectedSku.value.price_type,'level');p.openSku('buy');await p.confirmSku();assert.deepEqual(r.calls.find(c=>c.url.endsWith('/cart/add')).data,{productId:70,unique:'red001',cartNum:1,new:1});assert.match(r.navigations[0],/cartId=91/);}finally{r.stop();}}
  const tiny=goods({showPrice:[0]}),zeroDisplay={enabled:true,price:'0.00',price_type:'level',level_name:'银卡',vip_price:'',level_price:'0.00'};
  tiny.price='0.01';tiny.display_price=zeroDisplay;tiny.attr_value=[{...tiny.attr_value[0],price:'0.01',member_price:'0.01',price_type:'',level_name:'',vip_price:'',display_price:zeroDisplay}];
  const r=setup({product:tiny});try{const normalize=r.load(path.join(dir,'api/productDetail.ts')).normalizeMobileGoods,parsed=normalize(tiny);assert.equal(parsed.skus[0].display_price.price,'0.00');assert.equal(parsed.skus[0].member_price,'0.01');
    for(const badDisplay of [{...zeroDisplay,price:'0.02'},{...zeroDisplay,enabled:false}])assert.throws(()=>normalize({...tiny,attr_value:[{...tiny.attr_value[0],display_price:badDisplay}]}));
    await r.start({id:'70'});assert.equal(r.checkout.displayPrice.value,'0.00');assert.equal(r.checkout.selectedSku.value.member_price,'0.01');r.checkout.openSku('buy');await r.checkout.confirmSku();assert.deepEqual(r.calls.find(c=>c.url.endsWith('/cart/add')).data,{productId:70,unique:'red001',cartNum:1,new:1});
  }finally{r.stop();}
});

test('SKU media selection clamps quantity and uses its independent member display rather than product minimum',async()=>{const r=setup();try{await r.start({id:'70'});const p=r.checkout;p.openSku('buy');p.num.value=5;p.pickSku(p.skuList.value[1]);assert.equal(p.num.value,2);assert.equal(p.displayPrice.value,'19.00');assert.equal(p.selectedSku.value.member_price,'18.00');assert.equal(p.mediaImages.value[0],'/blue.png');assert.equal(p.skuMedia.value,true);}finally{r.stop();}});

test('configured bounds make reply and package counts real and recommendation layout changes at six',async()=>{const data=goods({replyNum:1,matchNum:1,recommendNum:6,communityNum:1});data.reply=[reply(1),reply(2)];const r=setup({product:data});try{await r.start({id:'70'});const p=r.checkout;assert.equal(p.replies.value.length,1);assert.equal(p.discountPackages.value.length,1);assert.equal(p.recommendations.value.length,6);render(r,'components/ThemePage.vue');assert.match(await render(r,'pages/goods/detail.vue',p),/recommend-grid/u);p.detail.value.display.design.recommendNum=24;assert.equal(p.recommendations.value.length,24);assert.equal(p.recommendationColumns.value.length,12);assert.match(await render(r,'pages/goods/detail.vue',p),/recommend-columns/u);}finally{r.stop();}});

test('marketing errors are explicit and coupon retry never changes the acknowledged purchase cart',async()=>{let fail=true;const r=setup({override:c=>c.url.includes('/product/detail/activity/')&&fail?{transport:'read failed'}:undefined});r.uni.navigateTo=o=>o.fail();try{await r.start({id:'70'});const p=r.checkout;assert.match(p.marketingError.value,/读取失败/u);fail=false;await p.retryMarketing();assert.equal(p.coupons.value[0].id,8);p.openSku('buy');await p.confirmSku();assert.equal(p.preparedCart.value.ids[0],91);await p.receiveCoupon(8);p.resumeCheckout();assert.equal(posts(r).length,1);assert.equal(p.preparedCart.value.ids[0],91);assert.equal(r.calls.filter(c=>c.url.endsWith('/coupon/receive')).length,1);assert.ok(r.navigations.length===0);}finally{r.stop();}});

test('late marketing and collection responses cannot enter a replacement actor or a hidden page',async()=>{for(const channel of ['marketing','collect']){const gate=deferred(),r=setup({override:c=>channel==='marketing'&&c.url.includes('/product/detail/activity/')||channel==='collect'&&c.url.endsWith('/collect/add')?gate.promise:undefined});try{await r.start({id:'70'});const p=r.checkout;let pending;if(channel==='collect')pending=p.toggleCollection();r.hooks.onHide();r.auth.setLogin('actor-b',22);gate.resolve({data:channel==='marketing'?{coupons:[],promotions:[]}:null});await pending;await tick();assert.equal(p.detail.value,null);assert.equal(p.collected.value,null);assert.equal(p.marketingError.value,'');assert.equal(posts(r).length,0);}finally{gate.resolve({data:{coupons:[],promotions:[]}});r.stop();}}});

test('ordinary collection uses product identity and ambiguous writes require explicit status reread',async()=>{const r=setup({override:c=>c.url.endsWith('/collect/add')?{transport:'uncertain'}:undefined});try{await r.start({id:'70'});const p=r.checkout;await p.toggleCollection();assert.equal(p.collected.value,null);await p.toggleCollection();assert.equal(r.calls.filter(c=>c.url.endsWith('/collect/add')).length,1);assert.deepEqual(r.calls.find(c=>c.url.endsWith('/collect/add')).data,{id:70,category:'product'});assert.match(p.collectionError.value,/重新加载/u);await p.load();assert.equal(p.collected.value,false);}finally{r.stop();}});

test('ordinary unknown new1 survives hide show refresh and another detail with zero second POST',async()=>{const storage=new Map(),r=setup({storage,override:c=>c.url.endsWith('/cart/add')?{transport:'unknown outcome'}:undefined});try{await r.start({id:'70'});const p=r.checkout;p.openSku('buy');await p.confirmSku();assert.equal(posts(r).length,1);r.hooks.onHide();r.hooks.onShow();await tick();await p.load();p.openSku('buy');await p.confirmSku();assert.equal(posts(r).length,1);assert.ok(p.ordinaryRecovery.value);assert.equal(p.ordinaryLocked.value,true);}finally{r.stop();}const next=setup({storage});try{await next.start({id:'70'});next.checkout.openSku('buy');await next.checkout.confirmSku();assert.equal(posts(next).length,0);assert.equal(next.checkout.ordinaryRecovery.value.state,'unknown');}finally{next.stop();}});

test('special product/cart-button gates keep valid buy while forms and presale use their actual entry',async()=>{for(const [type,form,presale,buy]of [[1,0,0,true],[2,0,0,true],[3,0,0,true],[4,0,0,true],[0,9,0,true],[0,0,0,true],[0,0,1,false]]){const data=goods();data.productType=type;data.systemFormId=form;data.cart_button=0;data.is_presale_product=presale;const r=setup({product:data});try{await r.start({id:'70'});const p=r.checkout;p.openSku('cart');await p.confirmSku();assert.equal(posts(r).length,0);p.openSku('buy');await p.confirmSku();assert.equal(posts(r).length,buy?1:0);if(presale)assert.ok(r.navigations.every(url=>url.includes('presaleDetail')));}finally{r.stop();}}});

test('share and timeline routes retain canonical product referrer and APP uses real provider',async()=>{const r=setup();const providers=[],shares=[];r.uni.getProvider=o=>providers.push(o);r.uni.share=o=>{shares.push(o);o.success();};try{await r.start({id:'70',spid:'8'});const p=r.checkout;assert.equal(r.calls.filter(c=>c.url.endsWith('/user/spread')).length,1);assert.deepEqual(r.calls.find(c=>c.url.endsWith('/user/spread')).data,{spread_uid:8});assert.equal(r.hooks.onShareAppMessage().path,'/pages/goods/detail?id=70&spid=11');assert.equal(r.hooks.onShareTimeline().query,'id=70&spid=11');p.appShare('WXSceneTimeline');providers[0].success({provider:['weixin']});assert.equal(shares[0].href,'https://shop.example/#/pages/goods/detail?id=70&spid=11');assert.equal(shares[0].scene,'WXSceneTimeline');assert.equal(shares[0].imageUrl,'/red.png');}finally{r.stop();}});

test('incoming referrer is consumed once and never transfers to a replacement identity',async()=>{const r=setup();try{await r.start({id:'70',spid:'8'});r.auth.setLogin('new',22);await tick();r.hooks.onHide();r.hooks.onShow();await tick();assert.equal(r.calls.filter(c=>c.url.endsWith('/user/spread')).length,1);assert.equal(r.checkout.sharePath.value,'/pages/goods/detail?id=70&spid=22');}finally{r.stop();}});

test('invalid referrer and foreign review cannot silently become a valid product view',async()=>{const r=setup();try{await r.start({id:'70',spid:'0'});assert.equal(r.checkout.detail.value,null);assert.equal(posts(r).length,0);}finally{r.stop();}const data=goods();data.reply[0].product_id=71;const next=setup({product:data});try{await next.start({id:'70'});assert.equal(next.checkout.detail.value,null);assert.match(next.checkout.loadError.value,/归属/u);}finally{next.stop();}});

test('real relation list paginates by product and drops a late actor response instead of leaking old cards',async()=>{const gate=deferred(),r=setup({component:'pages/goods/productCommunity.vue',override:c=>c.url.includes('/community')?gate.promise:undefined});try{r.hooks.onLoad({productId:'70'});r.hooks.onShow();await tick();assert.deepEqual(r.calls.at(-1).data,{page:1,limit:10});assert.match(r.calls.at(-1).url,/\/product\/70\/community$/);r.hooks.onHide();gate.resolve({data:{list:[{id:61,title:'旧晒单',image:'/p.png',content_type:1}],count:1}});await tick();assert.deepEqual(r.checkout.list.value,[]);assert.equal(r.checkout.count.value,0);}finally{gate.resolve({data:{list:[],count:0}});r.stop();}});

test('activity consumer limits applied settings to media/dots/footer and late public reads are fenced',async()=>{const r=runtime({feature:'useActivityDetailDesign',send:()=>({data:{product_detail:structuredClone(baseDesign),product_detail_design_state:{configured:true}}})});try{await r.start();assert.equal(r.checkout.activityDesign.value.pictureConfig,0);assert.equal(r.checkout.activityDesign.value.swiperDot,1);assert.deepEqual(r.checkout.activityDesign.value.menuList,[0,1,2]);r.hooks.onHide();assert.equal(r.checkout.activityVisible.value,false);}finally{r.stop();}});

test('real media geometry callbacks, image errors and cancelled page ownership cannot change newer media',async()=>{
  const props=vue.reactive({images:['/one.png'],video:'https://media.example/one.mp4',pictureConfig:1,dots:1,active:true});
  const r=runtime({component:'components/productDetail/ProductMedia.vue',props,send:()=>({data:null})}),reads=[],pauses=[],previews=[];
  Object.assign(r.uni,{getSystemInfoSync:()=>({windowWidth:390}),getImageInfo:o=>reads.push(o),createVideoContext:()=>({pause:()=>pauses.push(1),play(){}}),previewImage:o=>previews.push(o)});
  try{const p=r.checkout;p.measure();assert.equal(reads.length,1);const oldVideo=p.videoHandlers.value.error,oldImage=p.imageHandlers.value[0].error;
    props.images=['/two.png'];props.video='https://media.example/two.mp4';await tick();const before=p.height.value;reads[0].success({width:1,height:10});assert.equal(p.height.value,before);oldVideo();oldImage();assert.equal(p.videoError.value,'');assert.equal(p.imageError.value,'');
    reads.at(-1).fail();assert.match(p.imageError.value,/读取失败/u);p.retryImage();reads.at(-1).success({width:390,height:780});assert.equal(p.height.value,780);p.preview('/two.png');assert.deepEqual(previews,[{urls:['/two.png'],current:'/two.png'}]);
    const handler=p.videoHandlers.value.error;props.active=false;await tick();handler();reads.at(-1).fail();assert.equal(p.videoError.value,'');assert.equal(p.imageError.value,'');assert.ok(pauses.length>0);p.preview('/two.png');assert.equal(previews.length,1);
  }finally{r.stop();}
});

test('ordinary and integral canvases keep separate IDs and original integral quote while fencing late ordinary images',async()=>{
  const r=setup(),sfc=require('@vue/compiler-sfc'),ts=require('typescript'),file=path.join(dir,'components/IntegralSharePoster.vue'),unmounts=[],exports={},texts=[],ids=[],reads=[],drawnImages=[];
  const context={setFillStyle(){},fillRect(){},setFontSize(){},fillText:value=>texts.push(value),drawImage:(...args)=>drawnImages.push(args),draw(_reserve,done){done();}};
  Object.assign(r.uni,{getImageInfo:o=>reads.push(o),createCanvasContext:id=>{ids.push(id);return context;}});
  const source=sfc.compileScript(sfc.parse(fs.readFileSync(file,'utf8'),{filename:file}).descriptor,{id:'dual-poster-runtime'}).content;
  const code=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;
  new Function('require','exports','uni',code)(id=>id==='vue'?{...vue,onMounted(){},onUnmounted:fn=>unmounts.push(fn)}:id.startsWith('@/')?r.load(path.join(dir,id.slice(2))):id.startsWith('.')?r.load(path.resolve(path.dirname(file),id)):require(id),exports,r.uni);
  const scope=vue.effectScope(),ordinaryProps=vue.reactive({url:'https://shop.example/#/pages/goods/detail?id=70&spid=11',title:'普通商品',image:'/ordinary.png',price:'0.10',integral:0,siteName:'商城',tagline:'',canvasId:'ordinary-share-poster',quoteText:'银卡价 · ¥0.10'});
  const integralProps=vue.reactive({url:'https://shop.example/#/pages/activity/integralDetail?id=70',title:'积分商品',image:'/integral.png',price:'12.34',integral:200,siteName:'商城',tagline:''});
  const ordinary=scope.run(()=>exports.default.setup(ordinaryProps,{expose(){}})),integral=scope.run(()=>exports.default.setup(integralProps,{expose(){}}));
  try{const first=ordinary.draw(),second=integral.draw();await tick();reads[1].success({path:'/integral.png'});await second;assert.ok(texts.includes('200积分 + ¥12.34'));assert.equal(ids.at(-1),'integral-share-poster');
    ordinaryProps.image='/new.png';await tick();const before=texts.length;reads[0].success({path:'/late.png'});await first;assert.equal(texts.length,before);reads.at(-1).success({path:'/new.png'});await tick();assert.ok(texts.includes('银卡价 · ¥0.10'));assert.equal(ids.at(-1),'ordinary-share-poster');
    ordinaryProps.qrImage='https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=owned-code';await tick();reads.at(-1).success({path:'/new.png'});await tick();assert.equal(reads.at(-1).src,ordinaryProps.qrImage);reads.at(-1).success({path:'/official-code.png'});await tick();assert.ok(drawnImages.some(args=>args[0]==='/official-code.png'&&args.slice(1).join(',')==='60,345,200,200'));
    const pending=ordinary.draw();await tick();unmounts.forEach(fn=>fn());reads.at(-1).success({path:'/hidden.png'});const after=texts.length;await pending;assert.equal(texts.length,after);
  }finally{unmounts.forEach(fn=>fn());scope.stop();r.stop();}
});

test('a guest incoming referral waits for the first coherent login and cannot bind a second account',async()=>{const r=setup();try{r.auth.clear();await r.start({id:'70',spid:'8'});assert.equal(r.calls.filter(c=>c.url.endsWith('/user/spread')).length,0);r.hooks.onHide();r.auth.setLogin('guest-first',11);await tick();r.hooks.onShow();await tick();assert.equal(r.calls.filter(c=>c.url.endsWith('/user/spread')).length,1);r.auth.setLogin('guest-second',22);await tick();assert.equal(r.calls.filter(c=>c.url.endsWith('/user/spread')).length,1);}finally{r.stop();}});

test('authenticated official code reads preserve product and platform, reject foreign URLs and drop late actor code',async()=>{
  const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAAB',gate=deferred(),r=setup({override:c=>c.url.endsWith('/product/code/70')?gate.promise:undefined});
  try{await r.start({id:'70'});const p=r.checkout;p.openShare();p.togglePoster();await tick();assert.equal(r.calls.filter(c=>c.url.endsWith('/product/code/70')).length,1);assert.deepEqual(r.calls.at(-1).data,{user_type:'routine'});assert.equal(p.officialCodeLoading.value,true);
    r.hooks.onHide();r.auth.setLogin('new-code-owner',22);gate.resolve({data:{code:png}});await tick();assert.equal(p.officialCode.value,'');assert.equal(p.posterVisible.value,false);assert.equal(p.officialCodeLoading.value,false);
    const api=r.load(path.join(dir,'api/productDetailDesign.ts'));assert.equal(api.productShareCode('https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=owned%2Fticket','wechat'),'https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=owned%2Fticket');assert.equal(api.productShareCode(png,'routine'),png);assert.equal(api.productShareCode('data:image/jpeg;base64,/9j/AA==','routine'),'data:image/jpeg;base64,/9j/AA==');
    for(const source of ['https://evil.test/cgi-bin/showqrcode?ticket=x','https://mp.weixin.qq.com/cgi-bin/showqrcode?ticket=x&ticket=y','javascript:alert(1)','data:image/svg+xml;base64,PHN2Zz4='])assert.throws(()=>api.productShareCode(source,'wechat'));
  }finally{gate.resolve({data:{code:png}});r.stop();}
  const failed=setup({override:c=>c.url.endsWith('/product/code/70')?{status:503,msg:'正式小程序码未配置'}:undefined});try{await failed.start({id:'70'});failed.checkout.openShare();failed.checkout.togglePoster();await tick();assert.equal(failed.checkout.officialCode.value,'');assert.match(failed.checkout.officialCodeError.value,/未配置/u);assert.equal(posts(failed).length,0);}finally{failed.stop();}
});

test('official mini-program scenes reach the same product and actual referral consumer, while ambiguous scenes make no read',async()=>{
  const r=setup();try{await r.start({scene:'id%3D70%26spid%3D8'});assert.equal(r.checkout.detail.value.id,70);assert.deepEqual(r.calls.find(c=>c.url.endsWith('/user/spread')).data,{spread_uid:8});const route=r.load(path.join(dir,'utils/ordinaryShare.ts'));
    for(const scene of ['id=70&id=71','id=70&spid=0','id=70&spid=8&unknown=1','id=70%2526spid=8'])assert.throws(()=>route.ordinaryShareRoute({scene}));assert.throws(()=>route.ordinaryShareRoute({scene:'id=70&spid=8',id:'71'}));
  }finally{r.stop();}
  const invalid=setup();try{await invalid.start({scene:'id=70&id=71'});assert.equal(invalid.checkout.detail.value,null);assert.equal(invalid.calls.filter(c=>/\/product\/detail\/\d+$/u.test(c.url)).length,0);}finally{invalid.stop();}
});

test('H5 WeChat uses the real SDK signature, canonical share metadata and visible-owner callbacks without stale registration',async()=>{
  const originalWindow=global.window,originalDocument=global.document,config={appId:'wx0123456789abcdef',timestamp:1770000000,nonceStr:'owned-nonce',signature:'a'.repeat(40)},r=setup({override:c=>c.url.endsWith('/wechat/config')?{data:config}:undefined}),scripts=[],configured=[],metadata=[],ready=[],failed=[],notices=[];let active=true;
  const sdk={config:o=>configured.push(o),ready:fn=>ready.push(fn),error:fn=>failed.push(fn),updateAppMessageShareData:o=>metadata.push(['friend',o]),updateTimelineShareData:o=>metadata.push(['timeline',o]),onMenuShareAppMessage:o=>metadata.push(['legacy-friend',o]),onMenuShareTimeline:o=>metadata.push(['legacy-timeline',o])};
  try{global.window={location:{href:'https://shop.example/?tenant=1#/pages/goods/detail?id=70',origin:'https://shop.example'},navigator:{userAgent:'MicroMessenger'},addEventListener(){},removeEventListener(){},wx:{}};global.document={createElement:()=>({remove(){}}),head:{appendChild:script=>scripts.push(script)}};
    const api=r.load(path.join(dir,'utils/ordinaryWechatShare.ts')),data={url:'https://shop.example/#/pages/goods/detail?id=70&spid=11',title:'真实商品',image:'/safe.png',summary:'商城'};
    const pending=api.configureOrdinaryWechatShare(data,()=>active,message=>notices.push(message));await tick();assert.equal(r.calls.at(-1).url.endsWith('/wechat/config'),true);assert.deepEqual(r.calls.at(-1).data,{url:'https://shop.example/?tenant=1'});assert.equal(scripts[0].src,'https://res.wx.qq.com/open/js/jweixin-1.6.0.js');global.window.wx=sdk;scripts[0].onload();await tick();assert.equal(configured.length,1);assert.equal(configured[0].signature,config.signature);ready[0]();await pending;assert.equal(metadata.length,4);assert.equal(metadata[0][1].link,data.url);assert.match(notices.at(-1),/微信分享已准备/u);
    const stale=api.configureOrdinaryWechatShare(data,()=>active,message=>notices.push(message));await tick();active=false;ready[1]();await stale;assert.equal(metadata.length,4);
    active=true;const error=api.configureOrdinaryWechatShare(data,()=>active,message=>notices.push(message));await tick();failed[2]({errMsg:'owned config failure'});await error;assert.match(notices.at(-1),/配置失败/u);assert.equal(metadata.length,4);
  }finally{active=false;r.stop();global.window=originalWindow;global.document=originalDocument;}
});

test('malformed officially loaded SDK rejects before config and can retry with a complete SDK',async()=>{
  const originalWindow=global.window,originalDocument=global.document,config={appId:'wx0123456789abcdef',timestamp:1770000000,nonceStr:'owned-nonce',signature:'a'.repeat(40)};
  for(const incomplete of [{},{config(){},ready(){},error(){},updateAppMessageShareData(){}}]){
    const r=setup({override:c=>c.url.endsWith('/wechat/config')?{data:config}:undefined}),scripts=[],calls=[],notices=[],ready=[];let active=true;
    const sdk={config:o=>calls.push(o),ready:fn=>ready.push(fn),error(){},updateAppMessageShareData(){},updateTimelineShareData(){}};
    try{global.window={location:{href:'https://shop.example/#/pages/goods/detail?id=70',origin:'https://shop.example'},navigator:{userAgent:'MicroMessenger'},addEventListener(){},removeEventListener(){},wx:{}};global.document={createElement:()=>({remove(){}}),head:{appendChild:script=>scripts.push(script)}};
      const api=r.load(path.join(dir,'utils/ordinaryWechatShare.ts')),data={url:'https://shop.example/#/pages/goods/detail?id=70&spid=11',title:'真实商品',image:'/safe.png',summary:'商城'};
      const rejected=api.configureOrdinaryWechatShare(data,()=>active,message=>notices.push(message));await tick();assert.equal(scripts.length,1);assert.equal(scripts[0].src,api.ORDINARY_WECHAT_SDK_URL);global.window.wx=incomplete;scripts[0].onload();await rejected;assert.equal(calls.length,0);assert.match(notices.at(-1),/组件不可用/u);
      const retried=api.configureOrdinaryWechatShare(data,()=>active,message=>notices.push(message));await tick();assert.equal(scripts.length,2);global.window.wx=sdk;scripts[1].onload();await tick();assert.equal(calls.length,1);ready[0]();await retried;assert.match(notices.at(-1),/微信分享已准备/u);
    }finally{active=false;r.stop();global.window=originalWindow;global.document=originalDocument;}
  }
});

test('registered product community preserves the real Home entry and every existing subsequent page order',()=>{
  const pages=JSON.parse(fs.readFileSync(path.join(dir,'pages.json'),'utf8')).pages.map(row=>row.path);
  assert.equal(pages[0],'pages/index/index');assert.equal(pages[1],'pages/goods/productCommunity');assert.equal(new Set(pages).size,pages.length);
  // Exact genuine 20261002 before bytes, now tracked so a clean checkout can
  // verify the old page order. Raw SHA: 068c7b3a6b883f13f1eb74b84cf0e4c4cd7036d25a082d4dab799aff0770873e.
  const original=fs.readFileSync(path.join(__dirname,'fixtures/product-detail-design-original-manifest-20261002.json'),'utf8');
  assert.equal(require('node:crypto').createHash('sha256').update(original.replace(/\r\n/g,'\n')).digest('hex'),'0705f1a2f6ed1aae8c0d2b2583a4ee3a61a9b0666782ad60662c6f1ec8ea26f8');
  const incoming=JSON.parse(original).pages.map(row=>row.path);
  assert.equal(incoming.length,96);assert.equal(new Set(incoming).size,incoming.length);
  assert.deepEqual(pages.filter(page=>incoming.includes(page)),incoming);
});

function selectionFixture(kind){const now=Math.floor(Date.now()/1000),common={selection_only:true,product_id:70,title:'活动商品',image:'/activity.png',images:['/gallery-one.png','/gallery-two.png'],skus:[{unique:'act00001',base_unique:'act00001',suk:'活动红',catalog_price:'0.10',ot_price:'1.00',image:'/sku.png',stock:8,max_quantity:3}]};
  if(kind==='seckill')return{...common,type:1,seckill_id:20,once_limit:3,total_limit:8,schedule:{timezone:'Asia/Shanghai',state:'active',message:'活动进行中',starts_at:new Date((now-60)*1000).toISOString(),ends_at:new Date((now+60)*1000).toISOString()}};
  if(kind==='combination')return{...common,type:3,combination_id:20,people:3,once_limit:3,total_limit:8,start_time:new Date((now-60)*1000).toISOString(),stop_time:new Date((now+60)*1000).toISOString(),date_window:'active',groups:[],requested_group:null};
  return{...common,version:1,type:6,payment_mode:'full',subtitle:'全款预售',sales:3,unit_name:'件',product_type:0,system_form_id:0,purchase_limits:{mode:'per_order',quantity:3},schedule:{timezone:'Asia/Shanghai',state:'active',presale_pay_status:2,start_time:now-60,stop_time:now+60,starts_at:new Date((now-60)*1000).toISOString(),ends_at:new Date((now+61)*1000).toISOString(),shipping_days_after_end:7}};
}
async function componentHtml(r,file,props){render(r,file);const app=vue.createSSRApp(r.load(path.join(dir,file)).default,props);app.use(require('pinia').getActivePinia());return (await require('@vue/server-renderer').renderToString(app)).replace(/<!--[\s\S]*?-->/gu,'');}
test('real activity selection adapters consume same-response gallery service specs and related reviews without changing cart identities or decimal prices',async()=>{
  for(const [kind,component,url,type]of [['seckill','pages/activity/seckillDetail.vue','/seckill/detail/20',1],['combination','pages/activity/detail.vue','/combination/detail/20',3],['presale','pages/activity/presaleDetail.vue','/product/detail/70',6]]){
    const extra=goods({showService:kind==='presale'?[2,3]:[2],replyNum:1});extra.reply=[reply(1),reply(2)];const fixture={...selectionFixture(kind),product_detail_design:extra.product_detail_design,ensure:extra.ensure,specs:extra.specs,description:'<p>活动真实正文</p>',reply:extra.reply,replyCount:12,replyChance:95};
    const r=runtime({component,send:c=>c.url.endsWith(url)?{data:fixture}:c.url.endsWith('/cart/add')?{data:{id:91}}:{data:[]}});try{await r.start({id:kind==='presale'?'70':'20'});const p=r.checkout;assert.ok(p.detail.value,p.error.value);p.choose('act00001');assert.equal(p.detail.value.detailDisplay.data.configured,true);assert.deepEqual(p.detail.value.detailDisplay.images,['/gallery-one.png','/gallery-two.png']);assert.deepEqual(p.activityGallery.value,['/sku.png','/gallery-one.png','/gallery-two.png']);assert.equal(p.selectedSku.value.catalog_price,'0.10');
      const html=await componentHtml(r,'components/productDetail/ActivityDetailContent.vue',{data:p.detail.value.detailDisplay.data,productId:70,active:true,specsMode:kind==='presale'?'included':'excluded'});assert.match(html,/服务保障/u);assert.match(html,/商品参数/u);assert.match(html,/棉/u);assert.match(html,/活动真实正文/u);assert.equal((html.match(/实际商品不错/gu)||[]).length,1);assert.match(html,/商品评价 \(12\)/u);
      await p.purchase();assert.deepEqual(r.calls.find(c=>c.url.endsWith('/cart/add')).data,{productId:70,activityId:kind==='presale'?0:20,type,unique:'act00001',cartNum:1,new:1});assert.equal(r.calls.filter(c=>c.url.endsWith('/wechat/config')).length,0);
    }finally{r.stop();}
  }
});
test('activity service drawers and native navigation fence old owners, preserve inverse specs, and integral never invents ordinary reviews',async()=>{
  const apiRuntime=setup(),data=apiRuntime.load(path.join(dir,'api/productDetailDesign.ts')).parseProductDetailDesignData(goods({showService:[2]})),props=vue.reactive({data,productId:70,active:true,reviewModule:true}),r=runtime({component:'components/productDetail/ActivityDetailContent.vue',props,send:()=>({data:null})}),callbacks=[];
  r.uni.navigateTo=o=>callbacks.push(o);try{r.checkout.openService();assert.equal(r.checkout.service.value,true);r.checkout.comments();assert.equal(callbacks[0].url,'/pages/goods/commentList?productId=70');props.active=false;await tick();callbacks[0].fail();assert.equal(r.checkout.service.value,false);assert.equal(r.checkout.error.value,'');props.active=true;r.checkout.comments();callbacks.at(-1).fail();assert.match(r.checkout.error.value,/未打开/u);
    const integral=await componentHtml(r,'components/productDetail/ActivityDetailContent.vue',{data,productId:70,active:true,reviewModule:false});assert.ok(!integral.includes('商品评价'));assert.match(integral,/商品参数/u);data.design.showService=[2,3];const inverse=await componentHtml(r,'components/productDetail/ActivityDetailContent.vue',{data,productId:70,active:true,reviewModule:false});assert.ok(!inverse.includes('商品参数'));const direct=await componentHtml(r,'components/productDetail/ActivityDetailContent.vue',{data,productId:70,active:true,reviewModule:false,specsMode:'included'});assert.match(direct,/商品参数/u);
  }finally{r.stop();apiRuntime.stop();}
});

module.exports={goods,baseDesign};
