const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),ts=require('typescript'),vue=require('vue'),pinia=require('pinia'),sfc=require('@vue/compiler-sfc');
const {runtime,tick,deferred}=require('./uni-store-runtime.cjs');
const root=path.resolve(__dirname,'../..'),uniRoot=path.resolve(__dirname,'../src'),adminRoot=path.resolve(__dirname,'../../admin-ts/src');
const native=['view','text','image','button','scroll-view','swiper','swiper-item','navigator','rich-text'];
function loader({uni={},gateway={}}={}){const cache=new Map();function load(file){file=path.resolve(file);if(!path.extname(file))file+='.ts';if(cache.has(file))return cache.get(file);const exports={};cache.set(file,exports);let source=fs.readFileSync(file,'utf8');if(file.endsWith('.vue'))source=sfc.compileScript(sfc.parse(source,{filename:file}).descriptor,{id:'actual-theme-runtime'}).content;
 const code=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;
 new Function('require','exports','uni',code)(id=>{if(id==='vue')return vue;if(id==='pinia')return pinia;if(id==='axios')return {default:{isAxiosError:e=>e?.isAxiosError===true},isAxiosError:e=>e?.isAxiosError===true};if(id==='@/utils/request'&&file.startsWith(adminRoot))return {default:gateway,getData:async p=>(await p).data};if(id.startsWith('@/'))return load(path.resolve(file.startsWith(adminRoot)?adminRoot:uniRoot,id.slice(2)));if(id.startsWith('.'))return load(path.resolve(path.dirname(file),id));return require(id);},exports,uni);return exports; }return {load};}
function publicHarness(send,storage=new Map()){const r=runtime({send,feature:'useCheckout',storage});const selected=[];r.uni.setTabBarStyle=o=>selected.push(o.selectedColor);const store=r.load(path.join(uniRoot,'stores/theme.ts')).useThemeStore();return {...r,store,selected};}
const pub=(status,issues=[])=>({data:{status,navigation:1,product_category_level:2,theme_issues:issues}});
const revision='a'.repeat(64),next='b'.repeat(64),uuid='12345678-1234-4123-8123-123456789abc',uuid2='12345678-1234-4123-8123-123456789abd';
const snapshot=(status=2,revisionValue=revision,editable=true)=>({revision:revisionValue,status,configured:status!==null,editable,issues:status===null?['theme_missing']:[]});
function adminHarness(overrides={},storage=new Map()){let actor={id:11,identity:'11:session-a:view/manage',stored:'session-a',view:true,manage:true},writes=[],signals=[];const actual=loader(),api=actual.load(path.join(adminRoot,'api/themeSettings.ts')),Controller=actual.load(path.join(adminRoot,'pages/setting/themeSettingsController.ts')).ThemeSettingsController;const memory={getItem:k=>storage.has(k)?storage.get(k):null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)};
 const ports={read:async signal=>{signals.push(signal);return snapshot();},write:async input=>{writes.push(structuredClone(vue.toRaw(input)));return {operation:'update',id:9,request_id:input.request_id,payload_hash:await api.themeFingerprint(input)};},receipt:async()=>{throw Error('not found');},confirm:async()=>{},storage:memory,uuid:()=>uuid,...overrides};const c=new Controller(()=>actor,ports);return {c,api,writes,storage,signals,ports,setActor:value=>{actor={...actor,...value};}};}
const fault=(status,code,pending,changes={})=>({isAxiosError:true,response:{status,data:{status,msg:'确定拒绝',data:{code,operation:'update',request_id:pending.input.request_id,payload_hash:pending.fingerprint,...changes}}}});
function renderComponent(file,load,props,piniaInstance){const component=load(file).default,descriptor=sfc.parse(fs.readFileSync(file,'utf8')).descriptor,bindings=sfc.compileScript(descriptor,{id:'theme-render'}).bindings;component.render=new Function('Vue',require('@vue/compiler-dom').compile(descriptor.template.content,{mode:'function',prefixIdentifiers:true,bindingMetadata:bindings,isCustomElement:tag=>native.includes(tag)}).code)(vue);const app=vue.createSSRApp(component,props);if(piniaInstance)app.use(piniaInstance);return require('@vue/server-renderer').renderToString(app);}

test('six exact legacy presets expose all six distinct semantic roles',()=>{const p=loader().load(path.join(root,'common/theme.ts'));assert.equal(p.THEME_PRESETS.length,6);assert.deepEqual(p.THEME_PRESETS.map(x=>x.name),['天空蓝','生鲜绿','热情红','魅力粉','活力橙','高端金']);const expected=[['#1DB0FC','#FD502F','#22CAFD','#5ACBFF'],['#42CA4D','#FF7600','#FE960F','#4DEA4D'],['#e93323','#e93323','#FE960F','#FF7931'],['#FF448F','#FF448F','#282828','#FF67AD'],['#FE5C2D','#FE5C2D','#FDB000','#FF9451'],['#E0A558','#DA8C18','#1A1A1A','#FFCD8C']];for(const [i,row]of p.THEME_PRESETS.entries()){assert.deepEqual([row.theme,row.priceColor,row.bntColor,row.gradient],expected[i]);assert.equal(Object.keys(p.themeVariables(row.status)).length,6);assert.match(row.minorColor,/0\.5/);assert.match(row.minorColorT,/0\.1/);}assert.equal(p.themePreset(0).status,3);});
test('actual six Admin preview templates render the six shopping scenes and token styles',async()=>{const r=loader();for(let status=1;status<=6;status++){const html=await renderComponent(path.join(adminRoot,'pages/setting/ThemePreview.vue'),r.load,{status});for(const label of ['商城首页','品质生活商品','加入购物车','立即购买','订单结算','会员中心'])assert.ok(html.includes(label));assert.ok(html.includes('--view-priceColor:'));assert.ok(html.includes('--view-bntColor:'));} });
test('actual public API uses the unauthenticated theme endpoint and rejects malformed preset values',async()=>{const r=publicHarness(()=>pub(2));try{await r.store.refresh();assert.equal(r.calls.at(-1).url,'/api/v2/diy/color_change/color_change');const parse=r.load(path.join(uniRoot,'api/theme.ts')).parsePublicTheme;for(const status of [-1,7,'2',null])assert.throws(()=>parse({status,theme_issues:[]}));assert.equal(parse({status:0,theme_issues:['theme_missing']}).status,0);}finally{r.stop();}});
test('real Pinia refresh applies every preset to host styles native tabbar and confirmed cache',async()=>{let status=1;const r=publicHarness(()=>pub(status));try{for(status=1;status<=6;status++){await r.store.refresh(true);assert.equal(r.store.status,status);assert.equal(r.store.configured,true);assert.equal(r.store.stale,false);assert.ok(r.store.style.includes('--view-priceColor:'));assert.equal(r.selected.at(-1),r.store.preset.theme);assert.deepEqual(r.storage.get('cinashop_theme_v1'),{version:1,status});}}finally{r.stop();}});
test('missing and corrupt public theme show red fallback without claiming a saved configuration',async()=>{const r=publicHarness(()=>pub(0,['theme_duplicate']));try{await r.store.refresh();assert.equal(r.store.status,null);assert.equal(r.store.displayStatus,3);assert.equal(r.store.configured,false);assert.deepEqual(r.store.issues,['theme_duplicate']);assert.equal(r.storage.has('cinashop_theme_v1'),false);}finally{r.stop();}});
test('failed refresh preserves last confirmed palette and marks it stale',async()=>{let fail=false;const r=publicHarness(()=>fail?{transport:'offline'}:pub(6));try{await r.store.refresh();fail=true;await r.store.refresh(true);assert.equal(r.store.displayStatus,6);assert.equal(r.store.stale,true);assert.match(r.store.error,/offline/);}finally{r.stop();}});
test('forced refresh and app hide fence late public replies before the next app show',async()=>{const gate=deferred();let requests=0;const r=publicHarness(()=>++requests===1?gate.promise:pub(5));try{const first=r.store.refresh();await tick();await r.store.refresh(true);gate.resolve(pub(1));await first;assert.equal(r.store.status,5);const gate2=deferred();r.uni.request=options=>{gate2.promise.then(result=>options.success({statusCode:200,data:{status:200,data:result.data}}));};const hidden=r.store.refresh(true);r.store.pause();gate2.resolve(pub(2));await hidden;assert.equal(r.store.status,5);assert.equal(r.store.loading,false);}finally{r.stop();}});
test('cached palette is display continuity and never proof of current saved configuration',()=>{const r=publicHarness(()=>pub(1),new Map([['cinashop_theme_v1',{version:1,status:4}]]));try{assert.equal(r.store.displayStatus,4);assert.equal(r.store.configured,false);assert.equal(r.store.stale,true);}finally{r.stop();}});
test('all 97 registered pages use an explicit real crossplatform ThemePage host',async()=>{const pages=JSON.parse(fs.readFileSync(path.join(uniRoot,'pages.json'),'utf8')).pages;assert.equal(pages.length,97);for(const page of pages){const file=path.join(uniRoot,page.path+'.vue'),d=sfc.parse(fs.readFileSync(file,'utf8')).descriptor;assert.ok(d.scriptSetup?.content.includes("import ThemePage from '@/components/ThemePage.vue'"),page.path);const ast=require('@vue/compiler-dom').baseParse(d.template.content),elements=ast.children.filter(node=>node.type===1);assert.equal(elements.length,1,page.path);assert.equal(elements[0].tag,'ThemePage',page.path);}
 const r=publicHarness(()=>pub(1));try{await r.store.refresh();const appPinia=pinia.getActivePinia();const html=await renderComponent(path.join(uniRoot,'components/ThemePage.vue'),r.load,{},appPinia);assert.match(html,/--view-theme:\s*#1DB0FC/);assert.match(html,/--view-priceColor:\s*#FD502F/);}finally{r.stop();}});
test('DIY follow mode ignores authored brand colour but keeps authored content and module backgrounds',()=>{const r=publicHarness(()=>pub(2));try{const f=r.load(path.join(uniRoot,'utils/diyTheme.ts')),p=r.load(path.join(root,'common/theme.ts')).themePreset(2),block={name:'goodList',toneConfig:{tabVal:0},goodsPriceColor:{color:[{item:'#123456'}]},bottomBgColor:{color:[{item:'#abcdef'}]}};assert.equal(f.diyThemeColor(block,'goodsPriceColor',0,'red',p),'#FF7600');assert.equal(f.diyThemeColor(block,'bottomBgColor',0,'white',p),'#abcdef');assert.equal(f.diyThemeVariables(block,p)['--view-priceColor'],'#FF7600');}finally{r.stop();}});
test('DIY custom commerce editorial sign and footer roles remain authored after global palette changes',()=>{const r=publicHarness(()=>pub(2));try{const f=r.load(path.join(uniRoot,'utils/diyTheme.ts')),themes=r.load(path.join(root,'common/theme.ts')),colour=value=>({color:[{item:value},{item:'#778899'}]});for(const status of [1,6]){const p=themes.themePreset(status);for(const [name,key]of [['coupon','couponMoneyColor'],['combination','pinkPriceColor'],['seckill','seckillPriceColor'],['bargain','bargainPriceColor'],['presale','presalePriceColor']]){const block={name,toneConfig:{tabVal:1},[key]:colour('#123456')};assert.equal(f.diyThemeVariables(block,p)['--view-priceColor'],'#123456');}for(const [name,key]of [['signIn','labelBgColor'],['ranking','classColor'],['pageFoot','activeColor']])assert.equal(f.diyThemeVariables({name,toneConfig:{tabVal:1},[key]:colour('#abcdef')},p)['--view-theme'],'#abcdef');assert.equal(f.diyThemeColor({name:'news',toneConfig:{tabVal:1},titleBgColor:colour('#112233')},'titleBgColor',1,'red',p),'#778899');assert.equal(f.diyThemeColor({name:'follow',themeColor:colour('#abcdef')},'themeColor',0,'red',p),'#abcdef');}}finally{r.stop();}});
test('price primary secondary selected and gradient CSS roles change while financial and error colours remain semantic',()=>{const read=p=>fs.readFileSync(path.join(uniRoot,p),'utf8');const goods=read('pages/goods/detail.vue');assert.match(goods,/\.add-btn\s*\{[^}]*var\(--view-bntColor/s);assert.match(goods,/\.buy-btn\s*\{[^}]*var\(--view-theme/s);assert.match(read('components/IntegralSkuSelection.vue'),/selection-total[^}]*var\(--view-priceColor/s);assert.match(read('pages/user/sign.vue'),/linear-gradient\(135deg, var\(--view-theme[^\n]+var\(--view-gradient/);assert.match(read('pages/user/finance.vue'),/\.item-right\.income\s*\{\s*color: #e93323/s);assert.match(read('components/ActivityPurchase.vue'),/\.error \{ color: #b72a1d/);assert.match(read('pages/order/detail.vue'),/#b54708/);});
test('actual poster canvas uses each theme price colour and fences an older image response on theme change',async()=>{let status=1;const r=publicHarness(()=>pub(status)),fills=[],unmounts=[],exports={},file=path.join(uniRoot,'components/IntegralSharePoster.vue');let blocked=null;const context={setFillStyle:value=>fills.push(value),setFontSize(){},fillText(){},fillRect(){},drawImage(){},draw(_reserve,callback){callback();}};
 try{r.uni.createCanvasContext=()=>context;r.uni.getImageInfo=options=>blocked?blocked(options):options.success({path:'/temporary/image.png'});const script=sfc.compileScript(sfc.parse(fs.readFileSync(file,'utf8'),{filename:file}).descriptor,{id:'theme-poster-runtime'}).content;const code=ts.transpileModule(script,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;
  new Function('require','exports','uni',code)(id=>id==='vue'?{...vue,onMounted(){},onUnmounted:fn=>unmounts.push(fn)}:id.startsWith('@/')?r.load(path.join(uniRoot,id.slice(2))):id.startsWith('.')?r.load(path.resolve(path.dirname(file),id)):require(id),exports,r.uni);const scope=vue.effectScope(),props=vue.reactive({url:'https://shop.example/#/pages/activity/integralDetail?id=70',title:'积分商品',image:'/api/assets/42?sig=current',price:'12.34',integral:200,siteName:'商城',tagline:''});const p=scope.run(()=>exports.default.setup(props,{expose(){}}));
  for(status=1;status<=6;status++){await r.store.refresh(true);await p.draw();assert.ok(fills.includes(r.store.preset.priceColor));}
  const late=[];blocked=options=>late.push(options);const old=p.draw();await tick();status=2;await r.store.refresh(true);await tick();assert.ok(late.length>=2);const before=fills.length;late[0].success({path:'/old/image.png'});await old;assert.equal(fills.length,before);blocked=null;late.at(-1).success({path:'/new/image.png'});await tick();assert.equal(p.ready.value,true);assert.ok(fills.includes('#FF7600'));unmounts.forEach(fn=>fn());scope.stop();
 }finally{r.stop();}});
test('Admin canonical and pending records enforce preset bounds actor identity and the cross-end golden hash',async()=>{const r=adminHarness(),input={request_id:uuid,revision,status:2};assert.equal(await r.api.themeFingerprint(input),'32dfcf5630c93a8b6615392e6ab6112e9e12c46c5f445201a2926191e0ae95bc');for(const status of [0,7,'2',null])assert.throws(()=>r.api.normalizeThemeWrite({...input,status}));const p={version:1,actor:11,input,fingerprint:await r.api.themeFingerprint(input)};assert.deepEqual(await r.api.parseThemePending(JSON.stringify(p),11),p);await assert.rejects(r.api.parseThemePending(JSON.stringify(p),22));await assert.rejects(r.api.parseThemePending(JSON.stringify({...p,fingerprint:'f'.repeat(64)}),11));r.c.dispose();});
test('Admin read-only missing and corrupt snapshots never create or permit writes',async()=>{const r=adminHarness({read:async()=>snapshot(null)});await r.c.activate();assert.equal(r.c.state.status,3);assert.equal(r.c.state.snapshot.configured,false);assert.equal(r.writes.length,0);r.setActor({manage:false});r.c.select(1);await r.c.save();assert.equal(r.c.state.status,3);assert.equal(r.writes.length,0);r.setActor({manage:true});r.ports.read=async()=>snapshot(null,revision,false);await r.c.activate();assert.equal(r.c.editorDisabled,true);await r.c.save();assert.equal(r.writes.length,0);r.c.dispose();});
test('Admin successful writes and cancelled confirmation use the actual reactive controller and UUID receipt',async()=>{const r=adminHarness();await r.c.activate();r.c.select(6);await r.c.save();assert.equal(r.writes.length,1);assert.equal(r.writes[0].status,6);assert.equal(r.c.state.pending,null);assert.equal(r.c.state.success,true);r.ports.confirm=async()=>{throw 'cancel';};r.c.select(1);await r.c.save();assert.equal(r.writes.length,1);r.c.dispose();});
test('Admin unknown writes remain frozen across reload and matching receipts are the only success recovery',async()=>{const r=adminHarness({write:async()=>{throw Error('network uncertain');}});await r.c.activate();r.c.select(4);await r.c.save();assert.equal(r.c.editorDisabled,true);const p=r.c.state.pending;assert.ok(p);await r.c.activate();assert.equal(r.c.state.status,4);assert.ok(r.c.state.pending);r.ports.receipt=async()=>({operation:'update',id:9,request_id:p.input.request_id,payload_hash:p.fingerprint});await r.c.readReceipt();assert.equal(r.c.state.pending,null);assert.equal(r.c.state.success,true);r.c.dispose();});
test('Admin actual 404 authorizes only explicit identical retry while wrong receipt stays frozen',async()=>{const r=adminHarness({write:async()=>{throw Error('uncertain');}});await r.c.activate();await r.c.save();const p=JSON.parse(JSON.stringify(r.c.state.pending));r.ports.receipt=async()=>{throw {isAxiosError:true,response:{status:404}};};await r.c.readReceipt();assert.equal(r.c.state.retryReady,true);let submitted;r.ports.write=async input=>{submitted=JSON.parse(JSON.stringify(input));return {operation:'update',id:9,request_id:input.request_id,payload_hash:'f'.repeat(64)};};await r.c.retryOriginal();assert.deepEqual(submitted,p.input);assert.ok(r.c.state.pending);r.c.dispose();});
test('Admin matching rollback 400 and 409 preserve draft then require explicit reread and a new UUID',async()=>{for(const [status,code]of [[400,'THEME_SETTINGS_REJECTED'],[409,'THEME_SETTINGS_STALE_VERSION']]){const r=adminHarness();r.ports.write=async()=>{throw fault(status,code,r.c.state.pending);};await r.c.activate();r.c.select(6);await r.c.save();assert.equal(r.c.state.pending,null);assert.equal(r.c.state.status,6);assert.equal(r.c.state.needsReread,true);assert.equal(r.storage.has(r.api.themeDraftKey(11)),true);await r.c.save();assert.equal(r.writes.length,0);r.ports.read=async()=>snapshot(2,next);await r.c.reread();assert.equal(r.c.state.status,6);assert.equal(r.c.state.needsReread,false);r.ports.uuid=()=>uuid2;r.ports.write=async input=>{r.writes.push(input);return {operation:'update',id:9,request_id:input.request_id,payload_hash:await r.api.themeFingerprint(input)};};await r.c.save();assert.equal(r.writes[0].revision,next);assert.equal(r.writes[0].request_id,uuid2);r.c.dispose();}});
test('Admin bare errors business envelopes and foreign proof cannot release an uncertain intent',async()=>{for(const variant of ['bare','business','nonce','hash']){const r=adminHarness();r.ports.write=async()=>{const p=r.c.state.pending;throw variant==='bare'?{isAxiosError:true,response:{status:400,data:{status:400}}}:variant==='business'?fault(200,'THEME_SETTINGS_STALE_VERSION',p):fault(409,'THEME_SETTINGS_STALE_VERSION',p,variant==='nonce'?{request_id:uuid2}:{payload_hash:'f'.repeat(64)});};await r.c.activate();await r.c.save();assert.ok(r.c.state.pending,variant);assert.equal(r.c.editorDisabled,true);r.c.dispose();}});
test('Admin actor changes permission revocation and disposed requests never publish late private state',async()=>{for(const channel of ['read','write','receipt']){const gate=deferred(),r=adminHarness();if(channel==='read')r.ports.read=()=>gate.promise;else if(channel==='write')r.ports.write=()=>gate.promise;else r.ports.write=async()=>{throw Error('uncertain');};let pending;if(channel==='read')pending=r.c.activate();else{await r.c.activate();pending=r.c.save();await tick();if(channel==='receipt'){await pending;r.ports.receipt=()=>gate.promise;pending=r.c.readReceipt();}}r.setActor({id:22,identity:'22:session-b',stored:'session-b',manage:false,view:false});r.c.invalidate();gate.resolve(channel==='read'?snapshot(6):{operation:'update',id:9,request_id:uuid,payload_hash:'f'.repeat(64)});await pending;assert.equal(r.c.state.snapshot,null);assert.equal(r.c.state.pending,null);assert.equal(r.c.state.success,false);assert.equal(r.c.editorDisabled,true);r.c.dispose();}});
