const test=require('node:test'),assert=require('node:assert/strict'),{runtime,tick,deferred}=require('./user-center-runtime.cjs');
const product=id=>({id,store_name:`收藏商品${id}`,image:'/p.png',price:'10.50',is_show:1,is_fail:0,is_presale_product:0,activity:'0,1,2,3',recommendation_target:{version:1,product_id:id,kind:'product',id,ends_at:null}});
const video=(id,available=true)=>({id,video_id:id,image:available?'/video-cover.png':'',site_name:'店铺视频',wap_login_logo:'/site.png',desc:`收藏视频${id}`,video_url:available?`/video-${id}.mp4`:'',like_num:2,available,is_fail:available?0:1});
const setup=send=>runtime({component:'pages/user/collect.vue',send});

test('legacy active 1 reads video collections, plays the actual video id and cancels that exact category',async()=>{let removed=false;const r=setup(c=>c.url.endsWith('/collect/del')?(removed=true,{data:null}):{data:{actor_uid:11,list:removed?[]:[video(71)],count:removed?0:1}});try{await r.start({active:'1'});assert.equal(r.page.kind.value,'video');assert.deepEqual(r.calls[0].data,{page:1,limit:20,category:'video'});r.page.openVideo(999);assert.equal(r.page.playing.value,null);r.page.openVideo(71);assert.equal(r.page.playing.value.video_id,71);assert.equal(r.page.playing.value.video_url,'/video-71.mp4');await r.page.remove(71);assert.deepEqual(r.calls.find(c=>c.url.endsWith('/collect/del')).data,{id:[71],category:'video'});assert.equal(r.page.playing.value,null);assert.equal(r.page.count.value,0);assert.equal(r.page.videos.value.length,0);assert.equal(r.page.mutationError.value,'');}finally{r.stop();}});
test('default product collection retains actual presale and activity destination authority',async()=>{const rows=[product(31),{...product(32),is_presale_product:1,recommendation_target:{version:1,product_id:32,kind:'presale',id:32,ends_at:null}},{...product(33),activity:'1,2,3,0',recommendation_target:{version:1,product_id:33,kind:'seckill',id:901,ends_at:'2099-09-24T01:00:00.000Z'}}];const r=setup(()=>({data:{list:rows,count:3}}));try{await r.start();r.page.openProduct(31);r.page.openProduct(32);r.page.openProduct(33);assert.deepEqual(r.navigations,['/pages/goods/detail?id=31','/pages/activity/presaleDetail?id=32','/pages/activity/seckillDetail?id=901']);}finally{r.stop();}});
test('unavailable video and physically missing relation can be cancelled but cannot open media',async()=>{let removed=false;const r=setup(c=>c.url.endsWith('/collect/del')?(removed=true,{data:null}):{data:{actor_uid:11,list:removed?[]:[video(71,false)],count:removed?0:1}});try{await r.start({active:'1'});r.page.openVideo(71);assert.equal(r.page.playing.value,null);await r.page.remove(71);assert.equal(r.calls.filter(c=>c.url.endsWith('/collect/del')).length,1);}finally{r.stop();}});
test('collection pagination follows relation count even when objects are missing and cannot repeat a busy page',async()=>{const wait=deferred(),r=setup(c=>c.data.page===2?wait.promise:{data:{actor_uid:11,list:[video(1)],count:25}});try{await r.start({active:'1'});assert.equal(r.page.hasMore.value,true);r.hooks.onReachBottom();r.hooks.onReachBottom();await tick();assert.equal(r.calls.length,2);wait.resolve({data:{actor_uid:11,list:[video(21)],count:25}});await tick();assert.equal(r.page.videos.value.length,2);assert.equal(r.page.hasMore.value,false);r.hooks.onReachBottom();await tick();assert.equal(r.calls.length,2);}finally{r.stop();}});
test('malformed active parameter makes no collection request and remains diagnosed on a reshow',async()=>{const r=setup(()=>{throw Error('must not request');});try{await r.start({active:'yes'});assert.equal(r.calls.length,0);assert.match(r.page.error.value,/分类参数/);r.hooks.onHide();r.hooks.onShow();await tick();assert.equal(r.calls.length,0);assert.match(r.page.error.value,/分类参数/);}finally{r.stop();}});
test('anonymous collection sends no reads, no deletion and offers only the login action',async()=>{const r=runtime({component:'pages/user/collect.vue',anonymous:true,send:()=>{throw Error('must not request');}});try{await r.start({active:'1'});assert.equal(r.calls.length,0);await r.page.remove(1);assert.equal(r.calls.length,0);assert.match(r.page.error.value,/登录/);r.page.login();assert.equal(r.navigations.at(-1),'/pages/auth/login');}finally{r.stop();}});
test('account swap aborts old collection and late old video cannot restore state or playback',async()=>{const first=deferred();let n=0;const r=setup(c=>n++===0?first.promise:{data:{actor_uid:12,list:[video(2)],count:1}});try{r.hooks.onLoad({active:'1'});r.hooks.onShow();await tick();r.auth.setLogin('new-collection-session',12);await tick();first.resolve({data:{actor_uid:11,list:[video(1)],count:1}});await tick();assert.deepEqual(r.page.videos.value.map(x=>x.id),[2]);assert.ok(r.aborts.length);r.page.openVideo(1);assert.equal(r.page.playing.value,null);}finally{r.stop();}});
test('category switch, hide and unload invalidate playback and old pending native collection reads',async()=>{const r=setup(c=>({data:c.data.category==='video'?{actor_uid:11,list:[video(1)],count:1}:{list:[product(3)],count:1}}));try{await r.start({active:'1'});r.page.openVideo(1);assert.ok(r.page.playing.value);r.page.select('product');await tick();assert.equal(r.page.playing.value,null);assert.equal(r.page.videos.value.length,0);assert.equal(r.page.products.value[0].id,3);r.hooks.onHide();assert.equal(r.page.products.value.length,0);r.page.openProduct(3);assert.deepEqual(r.navigations,[]);}finally{r.stop();}});
test('ambiguous deletion never speculatively removes a row or permits replay before refresh',async()=>{const r=setup(c=>c.url.endsWith('/collect/del')?{transport:'timeout'}:{data:{actor_uid:11,list:[video(1)],count:1}});try{await r.start({active:'1'});await r.page.remove(1);assert.equal(r.page.videos.value.length,1);assert.match(r.page.mutationError.value,/未确认/);await r.page.remove(1);assert.equal(r.calls.filter(c=>c.url.endsWith('/collect/del')).length,1);await r.page.load(true);assert.equal(r.page.mutationError.value,'');}finally{r.stop();}});
test('late deletion cannot erase a replacement account collection',async()=>{const wait=deferred(),r=setup(c=>c.url.endsWith('/collect/del')?wait.promise:{data:{actor_uid:c.header['Authori-zation']==='Bearer synthetic-local-token'?11:12,list:[video(c.header['Authori-zation']==='Bearer synthetic-local-token'?1:2)],count:1}});try{await r.start({active:'1'});const action=r.page.remove(1);await tick();r.auth.setLogin('replacement-user',12);await tick();wait.resolve({data:null});await action;assert.deepEqual(r.page.videos.value.map(x=>x.id),[2]);assert.equal(r.page.mutationError.value,'');}finally{r.stop();}});
test('unsafe available video, duplicate ids, wrong actor and ambiguous count reject the whole runtime response',async()=>{for(const data of [{actor_uid:11,list:[{...video(1),video_url:'javascript:alert(1)'}],count:1},{actor_uid:11,list:[video(1),video(1)],count:2},{actor_uid:12,list:[video(1)],count:1},{actor_uid:11,list:[video(1)],count:-1}]){const r=setup(()=>({data}));try{await r.start({active:'1'});assert.equal(r.page.videos.value.length,0);assert.ok(r.page.error.value);assert.equal(r.page.ready.value,false);}finally{r.stop();}}});
test('native playback errors remove the playable element and expose refresh rather than an invented source',async()=>{const r=setup(()=>({data:{actor_uid:11,list:[video(1)],count:1}}));try{await r.start({active:'1'});r.page.openVideo(1);r.page.playbackFailed();assert.equal(r.page.playing.value,null);assert.match(r.page.videoError.value,/暂时无法播放/);assert.equal(r.calls.length,1);}finally{r.stop();}});
test('failed collection refresh clears all stale product records and never prints a network error',async()=>{let fail=false;const r=setup(()=>fail?{transport:'offline'}:{data:{list:[product(1)],count:1}});try{await r.start();assert.equal(r.page.products.value.length,1);fail=true;await r.page.load(true);assert.equal(r.page.products.value.length,0);assert.match(r.page.error.value,/offline/);}finally{r.stop();}});
