const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),{runtime,tick,deferred,render}=require('./user-center-runtime.cjs');
const revision='a'.repeat(64),consistency='c'.repeat(64);
const item=(name='我的优惠券',url='/pages/users/user_coupon/index',type=1)=>({name,pic:'/menu.png',url,type});
const design=(style=1)=>({member:{style,property:style===1?[4,0,1,2,3]:[0,2,4],per_show_type:1},order:{style:2},orderStatic:{style:2,is_show:1},poster:{is_show:1,list:[{name:'领券活动',pic:'/poster.png',url:'/pages/activity/coupon/index'}]},menu:{title:'账户服务',is_show:1,style:3,list:[item()]},merMenu:{title:'门店工作',is_show:1,style:2,list:[]}});
const menu=(uid=11,overrides={})=>({actor_uid:uid,consistency_key:consistency,diy_data:design(),user_center_design_state:{revision,configured:true,issues:[]},profile:uid?{uid,nickname:`会员${uid}`,phone:'13800138000',avatar:'/avatar.png',now_money:'123.45',integral:210,couponCount:4,collectProductCount:8,collectVideoCount:6,visit_num:9,level_name:'黄金会员',vip_discount:'85',is_promoter:1,pay_vip_status:true,service_num:2,commissionCount:'16.20',brokerage_price:'41.70',spread_user_count:3,spread_order_count:2}:null,capabilities:{balance:true,member:true,paid_member:true,promotion:uid>0,video:true,merchant:false,writeoff:false,deliveryWorkBench:false,invoice:true,promoter_application:false,agent_application:uid>0,agent_records:uid>0},orderStatusNum:{order_count:6,unpaid_count:1,unshipped_count:2,received_count:1,evaluated_count:1,refund_count:1},operator_profile:null,routine_contact_type:0,...overrides});
const stats=(uid=11,overrides={})=>({actor_uid:uid,consistency_key:consistency,design_revision:revision,commission:uid?{brokerage_price:'41.70',number:3,order_num:2}:[],order:{user_order:false},not_pay_order:uid?{id:90,order_id:'order90',pay_price:'12.50',img:'/pending.png',store_name:'真实未付款商品',stop_time:Math.floor(Date.now()/1000)+300}:null,...overrides});
const serve=overrides=>call=>({data:call.url.endsWith('/menu/user')?menu(11,overrides?.menu):call.url.endsWith('/menu/date')?stats(11,overrides?.stats):null});

test('customer-only mobile work entry renders and navigates from every actual module without merchant aggregate authority',async()=>{
 const d=design();for(const group of ['poster','menu','merMenu'])d[group].list=[{name:'手机经营',pic:'/menu.png',url:'/pages/admin/work/index',...(group==='poster'?{}:{type:group==='merMenu'?2:1})}];
 const r=runtime({send:serve({menu:{diy_data:d,capabilities:{...menu().capabilities,work:true}}})});
 try{await r.start();assert.ok(r.page.snapshot.value);assert.equal(r.page.merchantStats.value,null);assert.ok(r.page.shortcuts.value.some(x=>x.name==='手机工作台'&&x.url==='/pages/customer-work/index'));
  await render(r,'components/ThemePage.vue');await render(r,'components/userCenter/UserCenterMenus.vue');const html=await render(r,'pages/user/index.vue',r.page);assert.match(html,/data-module="merMenu"/);assert.match(html,/手机经营/);
  for(const group of ['poster','menu','merMenu'])r.page.openMenu(group,0);assert.deepEqual(r.navigations,Array(3).fill('/pages/customer-work/index'));
  r.page.snapshot.value.menu.capabilities.work=false;r.page.go('/pages/admin/work/index');assert.equal(r.navigations.length,3);assert.match(r.page.navigationError.value,/手机经营权限/);
 }finally{r.stop();}
});
test('work target requires its own role across poster personal and merchant placements despite another role',async()=>{
 for(const group of ['poster','menu','merMenu']){const d=design();d[group].list=[{name:'手机经营',pic:'/menu.png',url:'/pages/admin/work/index',...(group==='poster'?{}:{type:group==='merMenu'?2:1})}];const r=runtime({send:serve({menu:{diy_data:d,capabilities:{...menu().capabilities,merchant:true,kefu:true,work:false}}})});try{await r.start();assert.equal(r.page.snapshot.value,null);assert.match(r.page.error.value,/手机经营入口/);assert.deepEqual(r.navigations,[]);}finally{r.stop();}}
});
test('work capability validates strict booleans and cannot authorize merchant amounts',async()=>{
 for(const work of [1,'1','true',null]){const r=runtime({send:serve({menu:{capabilities:{...menu().capabilities,work}}})});try{await r.start();assert.equal(r.page.snapshot.value,null);assert.match(r.page.error.value,/手机经营角色/);}finally{r.stop();}}
 const r=runtime({send:serve({menu:{capabilities:{...menu().capabilities,work:true}},stats:{order:{user_order:true,price:'123.45',num:1,consignment:1}}})});try{await r.start();assert.equal(r.page.snapshot.value,null);assert.match(r.page.error.value,/商家统计/);}finally{r.stop();}
});
test('work entry disappears after revocation hide and account replacement and rejects anonymous privilege replay',async()=>{
 let enabled=true;const r=runtime({send:c=>serve({menu:{capabilities:{...menu().capabilities,work:enabled}}})(c)});try{await r.start();assert.ok(r.page.shortcuts.value.some(x=>x.name==='手机工作台'));enabled=false;await r.page.load();assert.ok(!r.page.shortcuts.value.some(x=>x.name==='手机工作台'));r.hooks.onHide();assert.equal(r.page.snapshot.value,null);r.page.go('/pages/customer-work/index');assert.deepEqual(r.navigations,[]);}finally{r.stop();}
 const m=menu(0,{capabilities:{...menu(0).capabilities,work:true}});m.orderStatusNum=Object.fromEntries(Object.keys(m.orderStatusNum).map(k=>[k,0]));const a=runtime({anonymous:true,send:c=>({data:c.url.endsWith('/menu/user')?m:stats(0)})});try{await a.start();assert.equal(a.page.snapshot.value,null);assert.match(a.page.error.value,/匿名响应/);}finally{a.stop();}
});

test('Kefu-only actor opens the independently configured workbench from personal and merchant menus without exporting a storefront credential',async()=>{
 const url='https://kefu.example.com/mobile_list',d=design();d.merMenu.list=[item('客服工作台',url,2)];d.menu.list=[item('客服工作台',url)];
 const r=runtime({send:serve({menu:{diy_data:d,kefu_workbench_url:url,capabilities:{...menu().capabilities,kefu:true}}})});
 try{await r.start();assert.ok(r.page.snapshot.value);assert.ok(r.page.shortcuts.value.some(x=>x.name==='客服工作台'&&x.url===url));await render(r,'components/ThemePage.vue');await render(r,'components/userCenter/UserCenterMenus.vue');const html=await render(r,'pages/user/index.vue',r.page);assert.match(html,/data-module="merMenu"/);assert.match(html,/客服工作台/);r.page.openMenu('merMenu',0);r.page.openMenu('menu',0);assert.deepEqual(r.navigations,[`/pages/common/fabWebView?url=${encodeURIComponent(url)}`,`/pages/common/fabWebView?url=${encodeURIComponent(url)}`]);assert.ok(!r.navigations.join('').includes('synthetic-local-token'));assert.equal(r.page.snapshot.value.menu.capabilities.merchant,false);}
 finally{r.stop();}
});
test('Kefu qualification alone never invents an unconfigured app destination',async()=>{
 const r=runtime({send:serve({menu:{kefu_workbench_url:'',capabilities:{...menu().capabilities,kefu:true}}})});
 try{await r.start();assert.ok(r.page.snapshot.value);assert.ok(!r.page.shortcuts.value.some(x=>x.name==='客服工作台'));const u=r.load(path.join(__dirname,'../src/utils/userCenter.ts'));assert.match(u.userCenterIssueText('user_center_menu_kefu_entry_unavailable'),/客服工作台入口暂未开通/);}
 finally{r.stop();}
});
test('Kefu entry DTO rejects wrong role, unsafe destinations and credentials before enabling navigation',async()=>{
 for(const override of[{kefu_workbench_url:'https://kefu.example.com/mobile_list'},{kefu_workbench_url:'https://u:p@kefu.example.com/mobile_list',capabilities:{...menu().capabilities,kefu:true}},{kefu_workbench_url:'https://kefu.example.com/mobile_list?token=secret',capabilities:{...menu().capabilities,kefu:true}},{kefu_workbench_url:'http://kefu.example.com/mobile_list',capabilities:{...menu().capabilities,kefu:true}},{capabilities:{...menu().capabilities,kefu:1}}]){
  const r=runtime({send:serve({menu:override})});try{await r.start();assert.equal(r.page.snapshot.value,null);assert.match(r.page.error.value,/客服/);assert.deepEqual(r.navigations,[]);}finally{r.stop();}
 }
});
test('refreshed Kefu revocation and hidden page clear the role shortcut instead of retaining a prior actor entry',async()=>{
 let enabled=true;const r=runtime({send:c=>serve({menu:{kefu_workbench_url:enabled?'https://kefu.example.com/mobile_list':'',capabilities:{...menu().capabilities,kefu:enabled}}})(c)});
 try{await r.start();assert.ok(r.page.shortcuts.value.some(x=>x.name==='客服工作台'));enabled=false;await r.page.load();assert.ok(!r.page.shortcuts.value.some(x=>x.name==='客服工作台'));r.hooks.onHide();assert.equal(r.page.snapshot.value,null);assert.deepEqual(r.page.shortcuts.value,[]);}finally{r.stop();}
});

test('member code registration preserves the existing startup and product community pages',()=>{const manifest=JSON.parse(require('node:fs').readFileSync(path.join(__dirname,'../src/pages.json'),'utf8'));assert.equal(manifest.pages[0].path,'pages/index/index');assert.equal(manifest.pages[1].path,'pages/goods/productCommunity');assert.equal(manifest.pages.filter(p=>p.path==='pages/user/memberCode').length,1);});

test('six-module consumer reads the real member layout, ordered asset values, counts, banner, and menu links',async()=>{const r=runtime({send:serve()});try{await r.start();const p=r.page;assert.equal(p.snapshot.value.menu.profile.nickname,'会员11');assert.deepEqual(p.properties.value.map(x=>[x.id,x.value]),[[0,'123.45'],[1,'4'],[2,'210'],[3,'8'],[4,'6']]);assert.equal(p.pendingOrder.value.order_id,'order90');assert.match(p.countdown.value,/^00:(?:04:\d{2}|05:00)$/);assert.deepEqual(p.orderEntries.value.map(x=>x.count),[1,2,1,1,1]);p.openMenu('menu',0);p.openMenu('poster',0);p.openProperty(4);assert.deepEqual(r.navigations,['/pages/user/coupon','/pages/user/couponCenter','/pages/user/collect?active=1']);assert.equal(p.snapshot.value.menu.diy_data.menu.style,3);assert.equal(p.snapshot.value.menu.diy_data.orderStatic.style,2);}finally{r.stop();}});
for(const style of [1,2,3,4,5])test(`member style ${style} preserves actual semantics and server property selection`,async()=>{const r=runtime({send:serve({menu:{diy_data:design(style)}})});try{await r.start();assert.equal(r.page.snapshot.value.menu.diy_data.member.style,style);assert.equal(r.page.properties.value.length,style===3||style===4?0:style===1?5:3);if(style===4)assert.equal(r.page.commission.value.brokerage_price,'41.70');}finally{r.stop();}});
test('style 2 renders the actual user level percentage as a discount and hides the card without member capability',async()=>{for(const enabled of [true,false]){const r=runtime({send:serve({menu:{diy_data:design(2),profile:{...menu().profile,vip_discount:'77.5'},capabilities:{...menu().capabilities,member:enabled}}})});try{await r.start();await render(r,'components/ThemePage.vue');await render(r,'components/userCenter/UserCenterMenus.vue');const html=await render(r,'pages/user/index.vue',r.page);if(enabled)assert.match(html,/7\.75折/);else assert.doesNotMatch(html,/7\.75折/);}finally{r.stop();}}});
test('invalid actual membership discount rejects the whole personal snapshot before rendering',async()=>{const r=runtime({send:serve({menu:{diy_data:design(2),profile:{...menu().profile,vip_discount:'125'}}})});try{await r.start();assert.equal(r.page.snapshot.value,null);assert.match(r.page.error.value,/会员折扣响应无效/);}finally{r.stop();}});
test('rendered diagnostics explain unavailable and historical items without exposing internal codes',async()=>{const issues=['user_center_avatar_invalid','user_center_menu_picture_unavailable','user_center_menu_historical_target_partial','user_center_unknown_new_diagnostic'];const r=runtime({send:serve({menu:{user_center_design_state:{revision,configured:true,issues}}})});try{await r.start();assert.deepEqual(r.page.snapshot.value.menu.user_center_design_state.issues,issues);await render(r,'components/ThemePage.vue');await render(r,'components/userCenter/UserCenterMenus.vue');const html=await render(r,'pages/user/index.vue',r.page);assert.match(html,/头像暂不可用/);assert.match(html,/部分图片暂不可用/);assert.match(html,/部分历史入口暂不可用/);assert.match(html,/联系管理员确认个人中心设置/);assert.doesNotMatch(html,/user_center_|historical_target_partial|picture_unavailable/);const u=r.load(path.join(__dirname,'../src/utils/userCenter.ts'));assert.match(u.userCenterIssueText('user_center_member_duplicate'),/设置存在重复/);}finally{r.stop();}});
for(const style of [1,2,3])test(`order and menu style ${style} reach actual configured consumers`,async()=>{const d=design();d.order.style=style;d.menu.style=style;d.merMenu.style=style;const r=runtime({send:serve({menu:{diy_data:d}})});try{await r.start();assert.equal(r.page.design.value.order.style,style);assert.equal(r.page.design.value.menu.style,style);r.page.go(r.page.orderEntries.value[2].url);assert.equal(r.navigations.at(-1),'/pages/order/list?status=2');}finally{r.stop();}});
test('anonymous public layout has no actor assets, statistics or merchant access',async()=>{const m=menu(0);m.orderStatusNum=Object.fromEntries(Object.keys(m.orderStatusNum).map(k=>[k,0]));const r=runtime({anonymous:true,send:c=>({data:c.url.endsWith('/menu/user')?m:stats(0)})});try{await r.start();assert.equal(r.page.snapshot.value.menu.actor_uid,0);assert.deepEqual(r.page.properties.value,[]);r.page.openMenu('menu',0);assert.equal(r.navigations.at(-1),'/pages/auth/login');assert.equal(r.calls.filter(c=>c.url.includes('rand_code')).length,0);}finally{r.stop();}});
test('promotion, balance and video assets require current server capabilities',async()=>{const d=design();d.member.property=[0,4,6,7,8];const caps={...menu().capabilities,balance:false,video:false,promotion:false};const r=runtime({send:serve({menu:{diy_data:d,capabilities:caps},stats:{commission:[]}})});try{await r.start();assert.deepEqual(r.page.properties.value,[]);assert.ok(!r.page.shortcuts.value.some(x=>['/pages/user/finance','/pages/user/recharge'].includes(x.url)));}finally{r.stop();}});
test('merchant statistics and menus require actual operator roles, never the design type marker',async()=>{const d=design();d.merMenu.list=[item('订单核销','/pages/admin/writeOffCard/index',2)];const r=runtime({send:serve({menu:{diy_data:d},stats:{order:{user_order:true,price:'999.00',num:4,consignment:2}}})});try{await r.start();assert.equal(r.page.snapshot.value,null);assert.match(r.page.error.value,/商家入口/);assert.deepEqual(r.navigations,[]);}finally{r.stop();}});
test('authorized merchant receives only real scoped statistics and current writeoff profile',async()=>{const d=design();d.merMenu.list=[item('订单核销','/pages/admin/writeOffCard/index',2)];const operator={can_writeoff:true,staff_stores:[{id:1,store_id:7,store_name:'门店7',identity_conflict:false}],delivery:null,delivery_identity_conflict:false};const r=runtime({send:serve({menu:{diy_data:d,operator_profile:operator,capabilities:{...menu().capabilities,merchant:true,writeoff:true}},stats:{order:{user_order:true,price:'98.20',num:3,consignment:1}}})});try{await r.start();assert.equal(r.page.merchantStats.value.price,'98.20');r.page.openOperator();assert.equal(r.navigations.at(-1),'/pages/operator/writeoff?role=staff');r.page.openMenu('merMenu',0);assert.equal(r.navigations.at(-1),'/pages/operator/writeoff');}finally{r.stop();}});
test('malformed configured source is diagnosed without repainting default six modules',async()=>{const r=runtime({send:serve({menu:{user_center_design_state:{revision,configured:true,issues:['user_center_member_duplicate']}}})});try{await r.start();assert.equal(r.page.snapshot.value,null);assert.match(r.page.error.value,/配置异常/);assert.equal(r.calls.length,1);}finally{r.stop();}});
test('invalid runtime DTO and mixed design revision fail with explicit retry instead of old account data',async()=>{for(const override of [{menu:{profile:{...menu().profile,uid:99}}},{stats:{design_revision:'b'.repeat(64)}}]){const r=runtime({send:serve(override)});try{await r.start();assert.equal(r.page.snapshot.value,null);assert.ok(r.page.error.value);assert.deepEqual(r.navigations,[]);}finally{r.stop();}}});
test('old account read cannot replay after a same uid relogin or a different uid switch',async()=>{for(const nextUid of [11,12]){const first=deferred();let n=0;const r=runtime({send:c=>c.url.endsWith('/menu/user')&&n++===0?first.promise:{data:c.url.endsWith('/menu/user')?menu(nextUid):stats(nextUid)}});try{r.hooks.onShow();await tick();r.auth.setLogin('new-synthetic-token',nextUid);await tick();first.resolve({data:menu(11)});await tick();assert.equal(r.page.snapshot.value.menu.actor_uid,nextUid);assert.equal(r.page.snapshot.value.menu.profile.uid,nextUid);assert.ok(r.aborts.length);assert.equal(r.page.loading.value,false);}finally{r.stop();}}});
test('hide and unload abort outstanding reads, clear all personal state and disable navigation',async()=>{for(const end of ['onHide','onUnload']){const wait=deferred(),r=runtime({send:()=>wait.promise});try{r.hooks.onShow();await tick();r.hooks[end]();wait.resolve({data:menu()});await tick();assert.equal(r.page.snapshot.value,null);assert.equal(r.page.loading.value,false);assert.ok(r.aborts.length);r.page.go('/pages/user/profile');assert.deepEqual(r.navigations,[]);}finally{r.stop();}}});
test('transport errors never restore a previous loaded user profile',async()=>{let fail=false;const r=runtime({send:c=>fail?{transport:'network offline'}:serve()(c)});try{await r.start();assert.ok(r.page.snapshot.value);fail=true;await r.page.load();assert.equal(r.page.snapshot.value,null);assert.match(r.page.error.value,/network offline/);}finally{r.stop();}});
test('pending order expiration reloads real counts and removes expired payment data once',async()=>{let reads=0;const r=runtime({send:c=>{if(c.url.endsWith('/menu/user'))return {data:menu(11,{orderStatusNum:{...menu().orderStatusNum,unpaid_count:reads?0:1}})};return {data:stats(11,{not_pay_order:reads++?null:{...stats().not_pay_order,stop_time:Math.floor(Date.now()/1000)+1}})};}});try{await r.start();assert.ok(r.page.pendingOrder.value);await new Promise(resolve=>setTimeout(resolve,1150));await tick();assert.equal(r.page.pendingOrder.value,null);assert.equal(r.page.orderEntries.value[0].count,0);assert.equal(reads,2);}finally{r.stop();}});
test('logout preserves server-revocation uncertainty and does not clear a replacement account',async()=>{const wait=deferred(),r=runtime({send:c=>c.url.endsWith('/logout')?wait.promise:serve()(c)});try{await r.start();const action=r.page.logout();await tick();r.auth.setLogin('replacement-token',12);wait.resolve({data:null});await action;assert.equal(r.auth.uid,12);}finally{r.stop();}const x=runtime({send:c=>c.url.endsWith('/logout')?{transport:'offline'}:serve()(c)});try{await x.start();await x.page.logout();assert.equal(x.auth.isLoggedIn,false);assert.equal(x.modals[0].title,'本机已退出');}finally{x.stop();}});
test('standalone member code uses only the real actor code and actual server expiration',async()=>{const deadline=Math.floor(Date.now()/1000)+22,r=runtime({component:'pages/user/memberCode.vue',send:c=>({data:c.url.endsWith('/user/rand_code')?{actor_uid:11,code:'123456',expires_at:deadline}:serve()(c).data})});try{await r.start();assert.equal(r.page.code.value,'123456');assert.equal(r.page.codeDeadline.value,deadline);const rows=r.page.qrRows.value;assert.equal(rows.length,29);assert.ok(rows.slice(0,4).flat().every(x=>!x));assert.ok(rows.slice(4).some(row=>row.some(Boolean)));assert.equal(r.calls.filter(c=>c.url.includes('activity')||c.url.includes('qrserver')).length,0);r.hooks.onHide();assert.equal(r.page.code.value,'');assert.deepEqual(r.page.qrRows.value,[]);}finally{r.stop();}});
test('member code rejects wrong account, invalid code and invented expiration extensions',async()=>{for(const code of [{actor_uid:12,code:'123456',expires_at:Math.floor(Date.now()/1000)+20},{actor_uid:11,code:'bad',expires_at:Math.floor(Date.now()/1000)+20},{actor_uid:11,code:'123456',expires_at:Math.floor(Date.now()/1000)+700}]){const r=runtime({component:'pages/user/memberCode.vue',send:c=>({data:c.url.endsWith('/user/rand_code')?code:serve()(c).data})});try{await r.start();assert.equal(r.page.code.value,'');assert.deepEqual(r.page.qrRows.value,[]);assert.match(r.page.codeError.value,/响应无效/);}finally{r.stop();}}});
test('member code expired on the current clock has no drawable matrix',async()=>{const r=runtime({component:'pages/user/memberCode.vue',send:c=>({data:c.url.endsWith('/user/rand_code')?{actor_uid:11,code:'123456',expires_at:Math.floor(Date.now()/1000)+10}:serve()(c).data})});try{await r.start();r.page.clock.value=Date.now()+11000;assert.deepEqual(r.page.qrRows.value,[]);r.auth.clear();await tick();assert.equal(r.page.code.value,'');}finally{r.stop();}});
test('late member code response cannot repopulate a hidden or replaced account',async()=>{const wait=deferred(),r=runtime({component:'pages/user/memberCode.vue',send:c=>c.url.endsWith('/user/rand_code')?wait.promise:serve()(c)});try{await r.start();r.hooks.onHide();wait.resolve({data:{actor_uid:11,code:'123456',expires_at:Math.floor(Date.now()/1000)+15}});await tick();assert.equal(r.page.code.value,'');assert.equal(r.page.codeLoading.value,false);}finally{r.stop();}});
test('native media and link validators reject credential, decoding, protocol and path tricks without URL global',async()=>{const r=runtime({send:serve()}),old=global.URL;try{const u=r.load(path.join(__dirname,'../src/utils/userCenter.ts'));global.URL=undefined;for(const value of ['//evil/path','javascript:alert(1)','https://user:pass@shop.example/x','/%25252f%25252fevil/x','/a/../secret','https://shop.example/a\\b'])assert.equal(u.userCenterMedia(value),'');assert.equal(u.userCenterMedia('/api/attachments/7?sig=real'),'/api/attachments/7?sig=real');assert.equal(u.userCenterDestination('/pages/users/user_goods_collection/index?active=1').url,'/pages/user/collect?active=1');assert.equal(u.userCenterDestination('/pages/users/user_member_code/index').url,'/pages/user/memberCode');assert.equal(u.userCenterDestination('/pages/not_registered'),null);}finally{global.URL=old;r.stop();}});
test('request deadline aborts native IO and settled requests never keep a page timer',async()=>{const r=runtime({send:()=>new Promise(()=>{})});try{const api=r.load(path.join(__dirname,'../src/api/userCenter.ts')),scope=api.createUserCenterRequests(()=>true,2);await assert.rejects(scope.request('/menu/user'),/超时/);assert.equal(r.aborts.length,1);scope.abort();}finally{r.stop();}});
test('Admin shortcut checks the independent session permission and expiry at the actual tap',async()=>{const r=runtime({send:serve()});try{await r.start();r.page.goAdmin('/pages/behalf/record/index');assert.deepEqual(r.navigations,[]);r.page.admin.install({token:'synthetic-admin',id:7,label:'管理员',expiresAt:Date.now()+60000,permissions:['order.assisted']});r.page.goAdmin('/pages/behalf/record/index');assert.equal(r.navigations.at(-1),'/pages/behalf/record/index');r.page.admin.expiresAt=Date.now()-1;r.page.goAdmin('/pages/behalf/user_list/index');assert.equal(r.navigations.length,1);}finally{r.stop();}});
test('same design revision with changed permissions or account output cannot join two authority snapshots',async()=>{const r=runtime({send:serve({stats:{consistency_key:'d'.repeat(64)}})});try{await r.start();assert.equal(r.page.snapshot.value,null);assert.match(r.page.error.value,/账号权限已变化/);assert.deepEqual(r.page.properties.value,[]);}finally{r.stop();}});
test('invoice and application shortcuts follow separate current capabilities while own history remains read-only',async()=>{const caps={...menu().capabilities,invoice:false,promoter_application:false,agent_application:false,agent_records:true};const r=runtime({send:serve({menu:{capabilities:caps}})});try{await r.start();const urls=r.page.shortcuts.value.map(x=>x.url);assert.ok(!urls.includes('/pages/user/invoice'));assert.ok(!urls.includes('/pages/users/agent/apply'));assert.ok(!urls.includes('/pages/users/distributor/apply'));assert.ok(urls.includes('/pages/users/agent/record'));}finally{r.stop();}});
test('conflicted delivery or only conflicted staff cannot activate writeoff through a true capability marker',async()=>{for(const operator of [{can_writeoff:true,staff_stores:[{id:1,store_id:2,store_name:'门店',identity_conflict:true}],delivery:null,delivery_identity_conflict:false},{can_writeoff:true,staff_stores:[],delivery:{id:1,nickname:'配送'},delivery_identity_conflict:true}]){const r=runtime({send:serve({menu:{operator_profile:operator,capabilities:{...menu().capabilities,writeoff:true}}})});try{await r.start();assert.equal(r.page.snapshot.value,null);assert.match(r.page.error.value,/核销权限/);}finally{r.stop();}}});
test('promotion property 6 through 8 displays real commission, people and order counts in legacy catalog order',async()=>{const d=design(5);d.member.property=[8,6,7];const r=runtime({send:serve({menu:{diy_data:d}})});try{await r.start();assert.deepEqual(r.page.properties.value.map(x=>[x.id,x.value]),[[6,'41.70'],[7,'3'],[8,'2']]);}finally{r.stop();}});
