<template>
  <div class="combinations">
    <div class="heading"><div><h2>拼团商品</h2><p class="hint">一个拼团活动绑定一个来源商品，可选择多个参与规格。活动时间与每个团的成团时效分别配置。</p></div><div class="actions"><el-button v-if="canExport" type="primary" :disabled="busy || loading" :loading="exporting" @click="exportCsv">导出全部筛选结果</el-button><el-button v-if="exporting" @click="cancelExport(true)">取消导出</el-button><el-button v-if="canManage" type="primary" :disabled="!ready || busy" @click="openForm(0, 'create')">添加拼团商品</el-button></div></div>
    <el-alert v-if="!canView && !canExport" title="当前账号没有拼团查看或导出权限" type="warning" :closable="false" />
    <template v-if="canView || canExport">      <div class="filters"><label>名称或ID<el-input v-model="draftKeyword" aria-label="拼团名称或ID" maxlength="100" clearable @keyup.enter="search" /></label><label>日期阶段<el-select v-model="draftPhase" clearable placeholder="全部阶段" @change="search"><el-option label="未开始" value="future" /><el-option label="进行中" value="active" /><el-option label="已结束" value="ended" /><el-option label="时间损坏" value="invalid" /></el-select></label><label>上架状态<el-select v-model="draftStatus" clearable placeholder="全部状态" @change="search"><el-option label="上架" :value="1" /><el-option label="下架" :value="0" /></el-select></label><el-button :disabled="busy" @click="search">查询</el-button><el-button :disabled="busy" @click="reset">重置</el-button></div>
      <el-alert v-if="actionNotice" :title="actionNotice" type="warning" :closable="false" class="notice"><template #default><el-button link :disabled="busy" @click="load()">重新读取核对</el-button></template></el-alert>
      <el-alert v-if="canView && listError" :title="listError" type="error" :closable="false"><template #default><el-button link @click="load()">重试列表</el-button></template></el-alert>
      <div v-if="canView && !listError" class="table-scroll"><el-table :data="list" row-key="id" border v-loading="loading"><el-table-column prop="id" label="ID" width="75" /><el-table-column label="拼团商品" min-width="220"><template #default="{ row }"><div class="product-name"><el-image v-if="preview(row.image_preview)" :src="preview(row.image_preview)" :preview-src-list="[preview(row.image_preview)]" preview-teleported fit="cover" /><span>{{ row.title || '未命名活动' }}<el-tag v-if="!row.valid" type="danger" size="small">需修复</el-tag></span></div></template></el-table-column><el-table-column label="基础商品当前划线价" width="175"><template #default="{ row }">{{ row.ot_price || '—' }}</template></el-table-column><el-table-column label="活动拼团价" width="130"><template #default="{ row }">{{ row.price ?? '—' }}</template></el-table-column><el-table-column prop="count_people" label="开团数" width="105" /><el-table-column prop="count_people_all" label="参与记录数" width="120" /><el-table-column prop="count_people_pink" label="已成团数" width="115" /><el-table-column prop="people" label="成团人数" width="100" /><el-table-column prop="quota_total" label="配置总额度" width="110" /><el-table-column prop="consumed" label="已消耗" width="90" /><el-table-column prop="remaining" label="剩余额度" width="110" /><el-table-column label="活动时间" min-width="280"><template #default="{ row }">{{ timeLabel(row.start_time) }} — {{ timeLabel(row.end_time) }}</template></el-table-column><el-table-column label="日期阶段" width="115"><template #default="{ row }">{{ phaseLabel(row.phase) }}</template></el-table-column><el-table-column label="上架状态" width="100"><template #default="{ row }"><el-tag :type="row.status ? 'success' : 'info'">{{ row.status ? '上架' : '下架' }}</el-tag></template></el-table-column><el-table-column label="操作" :fixed="compact ? undefined : 'right'" width="310"><template #default="{ row }"><div class="actions"><router-link v-if="has('combination_statistics.view')" :to="'/activity/combination-statistics/' + row.id">统计</router-link><el-button link :disabled="!ready || busy" @click="openForm(row.id, 'view')">详情</el-button><template v-if="canManage"><el-button link type="primary" :disabled="!ready || busy || row.phase === 'ended'" @click="openForm(row.id, 'edit')">编辑</el-button><el-button link type="primary" :disabled="!ready || busy" @click="openForm(row.id, 'copy')">复制</el-button><el-button link :disabled="!ready || busy" @click="toggleStatus(row)">{{ row.status ? '下架' : '上架' }}</el-button><el-button link type="danger" :disabled="!ready || busy" @click="remove(row)">删除</el-button></template></div></template></el-table-column></el-table></div>
      <el-pagination v-if="canView && ready && !listError" :current-page="page" :page-size="15" :total="count" :page-count="Math.min(MAX_PAGE, Math.max(1, Math.ceil(count / 15)))" layout="total, prev, pager, next" :disabled="busy || loading" @current-change="load" class="pager" />
      <el-alert v-if="!canView && canExport" title="此账号仅可导出；不读取商品目录或配置选项。应用筛选后导出全部结果。" type="info" :closable="false" /><p v-if="exporting" class="hint">正在读取 {{ exportRead }} / {{ exportTotal || '—' }} 条；所有页完整且快照一致后才生成文件。</p><el-alert v-if="exportError" :title="exportError" type="warning" :closable="false" /><p class="hint">开团数与已成团数按团长记录计数；参与记录包含虚拟与退款，不是去重人数。划线价取基础商品当前值，缺失时显示—。导出11列、上海时间，最多100000条/16MiB，数据变化或任一页失败均不下载。</p>
    </template>
    <el-dialog v-model="formVisible" :title="mode === 'view' ? '拼团详情' : mode === 'copy' ? '复制拼团商品' : formId ? '编辑拼团商品' : '添加拼团商品'" width="min(1160px, calc(100vw - 24px))" top="4vh" :close-on-click-modal="false" :close-on-press-escape="!submitting" :show-close="!submitting" @closed="onFormClosed">
      <div v-loading="formLoading"><el-alert v-if="formError" :title="formError" type="error" :closable="false" class="notice" /><el-alert v-if="optionsError" :title="optionsError" type="warning" :closable="false"><template #default><el-button link @click="loadOptions">重读配置选项</el-button></template></el-alert>
        <template v-if="form"><el-alert v-if="mode === 'copy'" title="复制创建新活动和新规格身份；总额度预填来源配置总量，不复制销量、已消耗量或订单。请调整已过期活动时间。" type="info" :closable="false" class="notice" /><el-alert v-if="formIssues.length" :title="formIssues.join('；')" type="warning" :closable="false" /><details v-if="raw" class="legacy"><summary>历史原值</summary><pre>{{ JSON.stringify(raw, null, 2) }}</pre></details>
          <el-tabs v-model="formTab" @tab-change="hydrateRich"><el-tab-pane label="1. 来源商品" name="source"><div class="source-summary"><h3>{{ form.title || '尚未选择来源商品' }}</h3><p>来源 #{{ form.product_id || '未选' }} · {{ productTypeLabel(form.product_type) }} · 所属方 {{ form.owner.type }}/{{ form.owner.relation_id }}</p><el-button v-if="editable && !formId && mode !== 'copy'" type="primary" :disabled="submitting || choosingSource" @click="openProducts">{{ form.product_id ? '重新选择来源商品' : '选择来源商品' }}</el-button><p v-if="formId || mode === 'copy'" class="hint">编辑与复制均保留来源商品；需要其他来源请新建活动。</p><p class="hint">更换来源会在完整读取成功后替换草稿的展示、配送与规格配置。</p><details v-if="form.source_metadata"><summary>来源只读业务配置</summary><pre>{{ JSON.stringify(form.source_metadata, null, 2) }}</pre></details></div></el-tab-pane>
          <el-tab-pane label="2. 基础信息与规格" name="base"><el-form label-width="125px" :disabled="!editable || submitting || choosingSource"><el-form-item label="拼团名称" required><el-input v-model="form.title" maxlength="256" /></el-form-item><el-form-item label="拼团简介" required><el-input v-model="form.info" type="textarea" :rows="3" maxlength="255" /></el-form-item><el-form-item label="商品单位" required><el-select v-model="form.unit_name" filterable placeholder="选择商品单位"><el-option v-for="unit in options?.units || []" :key="unit.id" :label="unit.name" :value="unit.name" /><el-option v-if="form.unit_name && !options?.units.some(unit => unit.name === form!.unit_name)" :label="`${form.unit_name}（历史值）`" :value="form.unit_name" /></el-select><a v-if="has('product.manage') && editable" href="/product/metadata" target="_blank" rel="noopener" class="manage-link">新增/管理单位</a><el-button link :disabled="optionsLoading" @click="loadOptions">刷新选项</el-button></el-form-item>
            <el-form-item label="商品轮播图" required><div class="image-editor"><article v-for="(reference, index) in form.images" :key="`${reference}:${index}`" :draggable="editable && !submitting" @dragstart="imageDragging = index" @dragover.prevent @drop.prevent="moveImage(imageDragging, index)"><el-image v-if="preview(form.images_preview[index] || '')" :src="preview(form.images_preview[index] || '')" :preview-src-list="form.images_preview.map(preview).filter(Boolean)" preview-teleported fit="cover" /><span v-else class="hint">无预览</span><span>{{ index ? `图片 ${index + 1}` : '主图' }}</span><div v-if="editable" class="actions"><el-button link :disabled="submitting || index === 0" @click="moveImage(index, index - 1)">前移</el-button><el-button link :disabled="submitting || index === form.images.length - 1" @click="moveImage(index, index + 1)">后移</el-button><el-button link type="danger" :disabled="submitting" @click="removeImage(index)">删除</el-button></div></article><CombinationImagePicker v-if="editable && form.images.length < 10" :disabled="submitting || choosingSource" :editor-key="editorKey" :limit="10 - form.images.length" @choose="addImages" /></div></el-form-item><p class="hint inset">最多10张；可拖动或前后移动，首张为主图。保存稳定引用，预览使用授权地址。</p>
            <div class="dates"><el-form-item label="开始时间" required><input type="datetime-local" :value="combinationLocalTime(form.start_time)" :disabled="!editable || submitting" aria-label="拼团开始时间" @change="setTime('start_time', ($event.target as HTMLInputElement).value)" /></el-form-item><el-form-item label="结束时间" required><input type="datetime-local" :value="combinationLocalTime(form.end_time)" :disabled="!editable || submitting" aria-label="拼团结束时间" @change="setTime('end_time', ($event.target as HTMLInputElement).value)" /></el-form-item></div><p class="hint inset">上海时间，保存为UTC。已结束活动不能原位保存，可读取、启停、删除或复制后调整时间。</p>
            <el-form-item label="拼团时效（小时）" required><el-input-number v-model="form.effective_time" :min="1" :max="2147483647" :precision="0" /><span class="hint">每个团发起后计算，未达到成团阈值则到期失败退款</span></el-form-item><el-form-item label="成团人数" required><el-input-number v-model="form.people" :min="2" :max="500" :precision="0" @change="recomputeVirtual" /></el-form-item><el-form-item label="累计购买上限" required><el-input-number v-model="form.num" :min="1" :max="2147483647" :precision="0" /></el-form-item><el-form-item label="单次购买上限" required><el-input-number v-model="form.once_num" :min="1" :max="2147483647" :precision="0" /></el-form-item>
            <el-form-item label="虚拟成团阈值" required><el-input-number v-model="form.virtual" :min="1" :max="100" :precision="0" @change="thresholdChanged" /><span>%</span></el-form-item><el-form-item label="期望最多补齐"><el-input-number v-model="desiredFill" :min="0" :max="Math.max(0, form.people - 1)" :precision="0" @change="fillChanged" /></el-form-item><p class="hint inset">到期时实际至少 {{ requiredReal }} 人才可补齐至 {{ form.people }} 人；实际最多补齐 {{ Math.max(0, form.people - requiredReal) }} 人。人数输入换算为向下截断整数百分比，再按 ceil(人数 × 阈值 / 100) 判断；100%表示不虚拟补齐。</p>
            <el-form-item label="排序"><el-input-number v-model="form.sort" :min="0" :max="2147483647" :precision="0" /></el-form-item><el-form-item label="上架状态"><el-switch v-model="form.status" :active-value="1" :inactive-value="0" /></el-form-item><el-form-item label="热门推荐"><el-switch v-model="form.is_host" :active-value="1" :inactive-value="0" /><span class="hint">邀请好友页面的推荐模块</span></el-form-item><el-form-item label="支持退款"><el-switch v-model="form.is_support_refund" :active-value="1" :inactive-value="0" :disabled="form.product_type === 0" /><span v-if="form.product_type === 0" class="hint">普通商品支持退款</span></el-form-item>
            <fieldset><legend>配送与运费</legend><p v-if="form.product_type !== 0" class="hint">非普通商品继承来源配送规则。</p><el-form-item label="配送方式"><el-checkbox-group v-model="form.shipping.delivery_type" :disabled="form.product_type !== 0"><el-checkbox :value="1">快递</el-checkbox><el-checkbox :value="2">自提</el-checkbox><el-checkbox v-if="form.shipping.delivery_type.includes(3)" :value="3">历史门店配送</el-checkbox></el-checkbox-group></el-form-item><el-form-item label="运费方式"><el-select v-model="form.shipping.freight" :disabled="form.product_type !== 0"><el-option :value="1" label="包邮" /><el-option :value="2" label="固定邮费" /><el-option :value="3" label="运费模板" /></el-select></el-form-item><el-form-item v-if="form.shipping.freight === 2" label="固定邮费"><el-input v-model="form.shipping.postage" inputmode="decimal" :disabled="form.product_type !== 0" /></el-form-item><el-form-item v-if="form.shipping.freight === 3" label="运费模板"><el-select v-model="form.shipping.temp_id" :disabled="form.product_type !== 0"><el-option v-for="item in availableTemplates" :key="item.id" :value="item.id" :label="item.name" /><el-option v-if="form.shipping.temp_id && !availableTemplates.some(item => item.id === form!.shipping.temp_id)" :value="form.shipping.temp_id" :label="`缺失的历史模板 #${form.shipping.temp_id}`" /></el-select><a v-if="has('shipping.manage') && editable" href="/shipping" target="_blank" rel="noopener" class="manage-link">新增/管理运费模板</a></el-form-item></fieldset>
          </el-form><h3>参与规格（{{ form.skus.length }} / 500）</h3><div v-if="editable" class="toolbar"><el-button :disabled="submitting || choosingSource" @click="selectSkus(true)">选择可用规格</el-button><el-button :disabled="submitting || choosingSource" @click="selectSkus(false)">关闭全部规格</el-button><el-input v-model="batchPrice" aria-label="批量拼团价" placeholder="批量价格，可空" inputmode="decimal" /><el-input v-model="batchQuota" aria-label="批量总额度" placeholder="批量总额度，可空" inputmode="numeric" /><el-button :disabled="submitting || choosingSource" @click="applyBatch">应用到参与规格</el-button></div><p class="hint">总额度减已消耗量得到保存后剩余；不重置历史销量、库存或规格身份。退役规格不可恢复。</p><div class="table-scroll"><el-table :data="form.skus" border :row-key="skuKey"><el-table-column label="参与" width="70"><template #default="{ row }"><el-checkbox v-model="row.enabled" :disabled="!editable || submitting || choosingSource || row.retired || (!row.valid && !row.id)" /></template></el-table-column><el-table-column label="规格 / 图片" min-width="210"><template #default="{ row }"><el-image v-if="preview(row.image_preview)" :src="preview(row.image_preview)" :preview-src-list="[preview(row.image_preview)]" preview-teleported class="sku-image" fit="cover" /><span v-else class="hint">无规格图</span><p>{{ row.suk || '默认规格' }}</p><p class="hint">{{ row.id ? `活动规格 #${row.id}` : `基础规格 ${row.base_unique || '缺失'}` }}</p><el-tag v-if="row.retired" size="small">已退役</el-tag><p class="bad">{{ row.issues.join('；') }}</p><CombinationImagePicker v-if="editable && !row.retired" :disabled="submitting || choosingSource || !row.enabled" :editor-key="`${editorKey}:sku:${skuKey(row)}`" @choose="chooseSkuImage(row, $event)" /></template></el-table-column><el-table-column label="拼团价" width="130"><template #default="{ row }"><el-input v-model="row.price" inputmode="decimal" :disabled="!editable || submitting || !row.enabled || row.retired" /></template></el-table-column><el-table-column prop="cost" label="成本价" width="100" /><el-table-column prop="ot_price" label="日常售价" width="100" /><el-table-column label="配置总额度" width="135"><template #default="{ row }"><el-input v-model.number="row.quota_total" type="number" min="0" max="2147483647" :disabled="!editable || submitting || !row.enabled || row.retired" /></template></el-table-column><el-table-column prop="consumed" label="已消耗" width="95" /><el-table-column prop="remaining" label="当前剩余" width="105" /><el-table-column label="保存后剩余" width="110"><template #default="{ row }">{{ nextRemaining(row) }}</template></el-table-column><el-table-column prop="base_stock" label="基础库存" width="105" /><el-table-column prop="stock" label="活动库存" width="105" /><el-table-column prop="weight" label="重量KG" width="100" /><el-table-column prop="volume" label="体积m³" width="100" /><el-table-column prop="bar_code" label="条形码" min-width="140" /><el-table-column prop="code" label="商品编码" min-width="140" /></el-table></div></el-tab-pane>
          <el-tab-pane label="3. 商品详情" name="content"><div v-if="editable" class="toolbar"><el-radio-group v-model="contentMode" @change="hydrateRich"><el-radio-button value="visual">富文本</el-radio-button><el-radio-button value="html">HTML源码</el-radio-button></el-radio-group><template v-if="contentMode === 'visual'"><el-button :disabled="submitting" @mousedown.prevent @click="formatContent('bold')">粗体</el-button><el-button :disabled="submitting" @mousedown.prevent @click="formatContent('italic')">斜体</el-button><el-button :disabled="submitting" @mousedown.prevent @click="formatContent('insertUnorderedList')">列表</el-button><el-button :disabled="submitting" @mousedown.prevent @click="formatContent('formatBlock', 'h3')">标题</el-button><CombinationImagePicker :disabled="submitting" :editor-key="`${editorKey}:content`" @choose="insertContentImages" /></template></div><el-input v-if="contentMode === 'html' && editable" v-model="form.description" type="textarea" :rows="16" maxlength="200000" :disabled="submitting" aria-label="拼团详情HTML" /><div v-else-if="editable" ref="contentEditor" class="rich-editor" :contenteditable="!submitting && !choosingSource" role="textbox" aria-label="拼团商品详情" @input="readRich" /><div v-else class="rich-preview" v-html="safeDescription(form.description)" /><p class="hint">正文由服务端清理不安全标签和属性；图片保存稳定地址。来源表单/规格成本/所属方为服务端只读配置。</p></el-tab-pane></el-tabs>
        </template>
      </div><template #footer><el-button :disabled="submitting" @click="closeForm">{{ editable ? '取消' : '关闭' }}</el-button><el-button v-if="formTab !== 'source'" :disabled="submitting" @click="previousTab">上一步</el-button><el-button v-if="formTab !== 'content'" :disabled="!form?.product_id || choosingSource || submitting" @click="nextTab">下一步</el-button><el-button v-if="editable" type="primary" :loading="submitting" :disabled="!form || formLoading || choosingSource || optionsLoading || !!optionsError" @click="save">{{ mode === 'copy' ? '创建复制活动' : '保存活动' }}</el-button></template>
    </el-dialog>
    <el-dialog v-model="productsVisible" title="选择一个来源商品" width="min(900px, calc(100vw - 24px))" append-to-body @closed="onProductsClosed"><div class="toolbar"><el-cascader v-model="productCategory" :options="categoryTree" :props="{ checkStrictly: true, emitPath: false }" filterable clearable placeholder="商品分类" :disabled="choosingSource" @change="searchProducts" /><el-select v-model="productLabel" filterable clearable placeholder="商品标签" :disabled="choosingSource" @change="searchProducts"><el-option v-for="label in options?.labels || []" :key="label.id" :value="label.id" :label="label.label_name" /></el-select><el-input v-model="productKeyword" aria-label="来源名称或ID" clearable :disabled="choosingSource" @keyup.enter="searchProducts" /><el-button :disabled="choosingSource" @click="searchProducts">查询</el-button></div><el-alert v-if="productError" :title="productError" type="error" :closable="false" /><div class="table-scroll"><el-table :data="products" v-loading="productsLoading" border><el-table-column prop="product_id" label="商品ID" width="90" /><el-table-column prop="store_name" label="商品名称" min-width="180" /><el-table-column label="类型" width="110"><template #default="{ row }">{{ productTypeLabel(row.product_type) }}</template></el-table-column><el-table-column prop="category_name" label="分类" min-width="150" /><el-table-column prop="stock" label="库存" width="90" /><el-table-column label="操作" width="120"><template #default="{ row }"><el-button type="primary" :disabled="!row.valid || choosingSource || productsLoading" :loading="choosingSource" @click="chooseSource(row)">选择</el-button><p class="bad">{{ row.issues.join('；') }}</p></template></el-table-column></el-table></div><el-pagination :current-page="productPage" :page-size="15" :total="productCount" layout="total, prev, pager, next" :disabled="productsLoading || choosingSource" @current-change="loadProducts" /><template #footer><el-button @click="closeProducts">取消</el-button></template></el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { useAuthStore } from '@/stores/auth';
import { getAdminSession, getToken } from '@/utils/auth';
import { AdminResponseError } from '@/utils/request';
import CombinationImagePicker from './CombinationImagePicker.vue';
import { collectCombinationExport } from '@/api/combinationStatistics';
import { downloadCombinationCsv } from '@/utils/combinationCsv';
import { apiCombinationList, apiCombinationDetail, apiCombinationOptions, apiCombinationProducts, apiCombinationProduct, apiCombinationSave, apiCombinationStatus, apiCombinationDelete, combinationCategoryTree, combinationPreview, combinationPicture, combinationMoney, combinationLocalTime, combinationUtcTime, combinationRequiredReal, normalizeCombinationInput, type CombinationRow, type CombinationPhase, type CombinationSource, type CombinationOptions, type CombinationSku, type CombinationProduct, type CombinationInput, type CombinationSave, type CombinationMutationKey } from '@/api/combination';
type Mode = 'create' | 'edit' | 'copy' | 'view'; type Editor = CombinationSource & { start_time: string; end_time: string; effective_time: number; people: number; num: number; once_num: number; virtual: number; sort: number; status: 0 | 1; is_host: 0 | 1; revision: string };
type Stamp = { identity: string; generation: number; stored: string | null }; type Mutation = { kind: 'save'; id: number; body: CombinationSave } | { kind: 'status'; id: number; body: CombinationMutationKey & { status: 0 | 1 } } | { kind: 'delete'; id: number; body: CombinationMutationKey };
const auth = useAuthStore(), has = (permission: string) => !!auth.userInfo && (auth.userInfo.level === 0 || auth.uniqueAuth.includes(permission));
const canView = computed(() => !!auth.token && auth.token === getToken() && has('combination.view')), canManage = computed(() => canView.value && has('combination.manage'));
const canExport = computed(() => !!auth.token && auth.token === getToken() && has('combination_export.view'));
type CatalogRow = CombinationRow & { price?: string; ot_price?: string; count_people?: number; count_people_all?: number; count_people_pink?: number };
const exporting = ref(false), exportRead = ref(0), exportTotal = ref(0), exportError = ref('');
let exportId = 0, exportAbort: AbortController | null = null;
function catalogRow(row: CombinationRow): CatalogRow {
  const result = row as CatalogRow;
  if (['price','ot_price'].some(key => result[key as 'price'|'ot_price'] !== undefined && typeof result[key as 'price'|'ot_price'] !== 'string') ||
    ['count_people','count_people_all','count_people_pink'].some(key => { const value = result[key as 'count_people']; return value !== undefined && (!Number.isSafeInteger(value) || value < 0); })) throw Error('拼团目录聚合字段无效');
  return result;
}
function cancelExport(notify = false) { exportId++; exportAbort?.abort(); exportAbort = null; exporting.value = false; exportRead.value = exportTotal.value = 0; exportError.value = notify ? '导出已取消，没有生成文件。' : ''; }
async function exportCsv() {
  if (!alive || !canExport.value || busy.value || loading.value || stored !== localStorage.getItem('admin_session')) return;
  cancelExport(); const serial = exportId, value = stamp(), controller = new AbortController(); exportAbort = controller; exporting.value = true;
  const active = () => alive && canExport.value && serial === exportId && !controller.signal.aborted && value.generation === generation && value.identity === identity.value && value.stored === localStorage.getItem('admin_session') && auth.token === getToken();
  try {
    const result = await collectCombinationExport({ keyword:keyword.value,phase:phase.value,status:status.value },controller.signal,(read,total) => { if (active()) { exportRead.value = read; exportTotal.value = total; } });
    if (active()) downloadCombinationCsv(result.csv,result.filename);
  } catch (reason) { if (active()) exportError.value = reason instanceof Error ? reason.message : '导出失败，没有生成文件'; }
  finally { if (exportAbort === controller) { exportAbort = null; exporting.value = false; } }
}
const identity = computed(() => `${auth.token}:${auth.userInfo?.id}:${auth.userInfo?.level}:${auth.uniqueAuth.join(',')}`), compact = ref(window.innerWidth < 650), MAX_PAGE = 667;
const ready = ref(false), loading = ref(false), listError = ref(''), list = ref<CatalogRow[]>([]), count = ref(0), page = ref(1), keyword = ref(''), phase = ref<'' | CombinationPhase>(''), status = ref<'' | 0 | 1>(''), draftKeyword = ref(''), draftPhase = ref<'' | CombinationPhase>(''), draftStatus = ref<'' | 0 | 1>('');
const formVisible = ref(false), formLoading = ref(false), mode = ref<Mode>('create'), formId = ref(0), form = ref<Editor | null>(null), formError = ref(''), formTab = ref('source'), formIssues = ref<string[]>([]), raw = ref<Record<string, unknown> | null>(null), endedSource = ref(false);
const editable = computed(() => canManage.value && mode.value !== 'view' && !(mode.value === 'edit' && endedSource.value));
const submitting = ref(false), confirming = ref(false), actionNotice = ref(''), uncertainOperation = ref<Mutation | null>(null), busy = computed(() => submitting.value || confirming.value || exporting.value);
const options = ref<CombinationOptions | null>(null), optionsLoading = ref(false), optionsError = ref(''), categoryTree = computed(() => options.value ? combinationCategoryTree(options.value.categories) : []);
const availableTemplates = computed(() => form.value?.templates ?? (form.value?.owner.type === 2 ? [] : options.value?.templates ?? []));
const productsVisible = ref(false), productsLoading = ref(false), choosingSource = ref(false), products = ref<CombinationProduct[]>([]), productPage = ref(1), productCount = ref(0), productKeyword = ref(''), productCategory = ref<number | '' | null>(null), productLabel = ref<number | ''>(''), productError = ref('');
const batchPrice = ref(''), batchQuota = ref(''), desiredFill = ref(0), requiredReal = computed(() => form.value ? combinationRequiredReal(form.value.people, form.value.virtual) : 0), imageDragging = ref(-1), contentMode = ref('visual'), contentEditor = ref<HTMLElement | null>(null);
const extraPreviews = new Map<string, string>(); let alive = false, syncing = false, generation = 0, editorGeneration = 0, pickerGeneration = 0, productRequest = 0, mutationId = 0, confirmId = 0;
let stored = localStorage.getItem('admin_session'), formScope: Stamp | null = null; const editorKey = computed(() => `${identity.value}:${generation}:${editorGeneration}`);
let listAbort: AbortController | null = null, formAbort: AbortController | null = null, optionsAbort: AbortController | null = null, productsAbort: AbortController | null = null, sourceAbort: AbortController | null = null, mutationAbort: AbortController | null = null;
function stamp(): Stamp { return { identity: identity.value, generation, stored }; }
function current(value: Stamp) { return alive && canView.value && value.identity === identity.value && value.generation === generation && auth.token === getToken() && value.stored === localStorage.getItem('admin_session'); }
function editorCurrent(value: Stamp, serial: number) { return current(value) && serial === editorGeneration && formVisible.value; }
function draftCurrent() { return !!formScope && current(formScope) && formVisible.value && editable.value && !!form.value && !formLoading.value && !submitting.value && !choosingSource.value; }
function resize() { compact.value = window.innerWidth < 650; }
const preview = combinationPreview; function timeLabel(value: string) { return combinationLocalTime(value).replace('T', ' ') || '时间损坏'; }
function phaseLabel(value: CombinationPhase) { return { future: '未开始', active: '进行中', ended: '已结束', invalid: '时间损坏' }[value]; }
function productTypeLabel(value: number) { return ({ 0: '普通商品', 1: '卡密商品', 2: '优惠券商品', 3: '虚拟商品', 4: '次卡商品' } as Record<number, string>)[value] ?? `未知类型 #${value}`; }
function skuKey(sku: CombinationSku) { return sku.id ? `sku:${sku.id}` : `base:${sku.base_unique}:${sku.suk}`; }
function nextRemaining(sku: CombinationSku) { return Number.isSafeInteger(sku.quota_total) && Number.isSafeInteger(sku.consumed) ? sku.quota_total - sku.consumed : '请输入整数'; }
function closeProducts() { pickerGeneration++; productRequest++; productsAbort?.abort(); sourceAbort?.abort(); productsAbort = sourceAbort = null; productsVisible.value = productsLoading.value = choosingSource.value = false; products.value = []; productCount.value = 0; productError.value = ''; }
function onProductsClosed() { if (!productsVisible.value) closeProducts(); }
function closeForm() { closeProducts(); editorGeneration++; formAbort?.abort(); optionsAbort?.abort(); formAbort = optionsAbort = null; formVisible.value = formLoading.value = optionsLoading.value = false; form.value = null; formScope = null; options.value = null; formError.value = optionsError.value = ''; raw.value = null; formIssues.value = []; extraPreviews.clear(); contentEditor.value = null; }
function onFormClosed() { if (!formVisible.value) closeForm(); }
function clearList() { cancelExport(); generation++; listAbort?.abort(); listAbort = null; list.value = []; count.value = 0; ready.value = loading.value = false; listError.value = ''; closeForm(); }
function invalidate() { clearList(); mutationId++; mutationAbort?.abort(); mutationAbort = null; confirmId++; if (confirming.value) ElMessageBox.close(); submitting.value = confirming.value = false; actionNotice.value = ''; uncertainOperation.value = null; }
async function load(target = page.value) { if (!alive || !canView.value || stored !== localStorage.getItem('admin_session') || !Number.isSafeInteger(target) || target < 1 || target > MAX_PAGE) return; clearList(); page.value = target; const value = stamp(), controller = new AbortController(); listAbort = controller; loading.value = true; try { const result = await apiCombinationList({ page: target, limit: 15, keyword: keyword.value, phase: phase.value, status: status.value }, controller.signal); if (!current(value)) return; if (!result.list.length && target > 1) { await load(Math.max(1, Math.min(target - 1, Math.ceil(result.count / 15)))); return; } list.value = result.list.map(catalogRow); count.value = result.count; ready.value = true; } catch (reason) { if (current(value)) listError.value = reason instanceof Error ? reason.message : '拼团读取失败'; } finally { if (listAbort === controller) { listAbort = null; loading.value = false; } } }
function search() { if (busy.value) return; keyword.value = draftKeyword.value.trim(); phase.value = draftPhase.value || ''; status.value = draftStatus.value ?? ''; void load(1); }
function reset() { if (!busy.value) { draftKeyword.value = ''; draftPhase.value = ''; draftStatus.value = ''; search(); } }
function blankForm(): Editor { return { product_id: 0, product_type: 0, owner: { type: 0, relation_id: 0 }, title: '', info: '', unit_name: '', images: [], images_preview: [], description: '', description_preview: '', start_time: '', end_time: '', effective_time: 24, people: 2, num: 1, once_num: 1, virtual: 100, sort: 0, status: 0, is_host: 0, is_support_refund: 1, shipping: { delivery_type: [], freight: 1, postage: '0.00', temp_id: 0 }, skus: [], revision: '', valid: true, issues: [] }; }
async function openForm(id: number, nextMode: Mode) {
  if (!ready.value || busy.value || !current(stamp()) || (nextMode !== 'view' && !canManage.value) || (id && !list.value.some(item => item.id === id))) return;
  closeForm(); formId.value = nextMode === 'copy' ? 0 : id; mode.value = nextMode; formVisible.value = formLoading.value = true; formTab.value = id ? 'base' : 'source'; contentMode.value = 'visual'; batchPrice.value = batchQuota.value = ''; const value = stamp(), serial = editorGeneration, controller = new AbortController(); formAbort = controller; formScope = value;
  try { const result = id ? await apiCombinationDetail(id, controller.signal) : null; if (!editorCurrent(value, serial)) return; endedSource.value = result?.phase === 'ended'; if (!result) form.value = blankForm(); else { const material = structuredClone(result); if (nextMode === 'copy') { for (const sku of material.skus) { sku.id = null; sku.unique = ''; sku.enabled = sku.enabled && sku.valid && !sku.retired; sku.consumed = 0; sku.remaining = sku.quota_total; } material.revision = ''; } form.value = material; raw.value = material.raw ?? null; formIssues.value = [...material.issues]; }
    seedContentPreviews(form.value!.description_preview); thresholdChanged(); await loadOptions();
  } catch (reason) { if (editorCurrent(value, serial)) formError.value = reason instanceof Error ? reason.message : '详情读取失败'; } finally { if (formAbort === controller) { formAbort = null; formLoading.value = false; } }
}
async function loadOptions() { if (!formScope || !current(formScope) || !formVisible.value) return; optionsAbort?.abort(); const value = stamp(), serial = editorGeneration, controller = new AbortController(); optionsAbort = controller; optionsLoading.value = true; optionsError.value = ''; try { const result = await apiCombinationOptions(controller.signal); if (editorCurrent(value, serial)) options.value = result; } catch (reason) { if (editorCurrent(value, serial)) optionsError.value = reason instanceof Error ? reason.message : '配置读取失败'; } finally { if (optionsAbort === controller) { optionsAbort = null; optionsLoading.value = false; } } }
async function openProducts() { if (!draftCurrent() || formId.value || mode.value === 'copy' || optionsLoading.value || optionsError.value || !options.value) return; closeProducts(); productsVisible.value = true; productKeyword.value = ''; productCategory.value = null; productLabel.value = ''; await loadProducts(1); }
function pickerCurrent(value: Stamp, editor: number, picker: number) { return editorCurrent(value, editor) && editable.value && !formId.value && mode.value !== 'copy' && productsVisible.value && picker === pickerGeneration; }
async function loadProducts(target = productPage.value) { if (!formScope || !current(formScope) || !productsVisible.value || !editable.value || choosingSource.value || !Number.isSafeInteger(target) || target < 1 || target > MAX_PAGE) return; productsAbort?.abort(); const value = stamp(), editor = editorGeneration, picker = pickerGeneration, serial = ++productRequest, controller = new AbortController(); productsAbort = controller; productsLoading.value = true; products.value = []; productError.value = ''; productPage.value = target; try { const result = await apiCombinationProducts({ page: target, limit: 15, keyword: productKeyword.value.trim(), category_id: productCategory.value || '', label_id: productLabel.value || '' }, controller.signal); if (pickerCurrent(value, editor, picker) && serial === productRequest) { products.value = result.list; productCount.value = result.count; } } catch (reason) { if (pickerCurrent(value, editor, picker) && serial === productRequest) productError.value = reason instanceof Error ? reason.message : '选品读取失败'; } finally { if (productsAbort === controller) { productsAbort = null; productsLoading.value = false; } } }
function searchProducts() { if (!choosingSource.value) void loadProducts(1); }
async function chooseSource(product: CombinationProduct) { if (!draftCurrent() || formId.value || mode.value === 'copy' || !productsVisible.value || productsLoading.value || !product.valid || !products.value.some(item => item.product_id === product.product_id && item.valid)) return; const value = stamp(), editor = editorGeneration, picker = pickerGeneration, controller = new AbortController(); sourceAbort = controller; choosingSource.value = true; productError.value = ''; try { const source = await apiCombinationProduct(product.product_id, controller.signal); if (!pickerCurrent(value, editor, picker)) return; if (!source.valid || !source.skus.length || !source.skus.some(sku => sku.valid && !sku.retired)) throw Error('来源没有可参与的完整有效规格'); const replacement: Editor = { ...blankForm(), ...structuredClone(source), skus: source.skus.map(sku => ({ ...sku, id: null, unique: '', enabled: sku.valid && !sku.retired, consumed: 0, quota_total: Math.max(0, sku.base_stock), remaining: Math.max(0, sku.base_stock) })) }; if (replacement.product_type === 0) replacement.is_support_refund = 1; form.value = replacement; formIssues.value = [...source.issues]; raw.value = null; extraPreviews.clear(); seedContentPreviews(source.description_preview); thresholdChanged(); formTab.value = 'base'; closeProducts(); } catch (reason) { if (pickerCurrent(value, editor, picker)) productError.value = reason instanceof Error ? reason.message : '商品材料读取失败'; } finally { if (sourceAbort === controller) { sourceAbort = null; choosingSource.value = false; } } }
function setTime(field: 'start_time' | 'end_time', value: string) { if (!draftCurrent()) return; try { form.value![field] = combinationUtcTime(value); formError.value = ''; } catch (reason) { form.value![field] = ''; formError.value = reason instanceof Error ? reason.message : '时间无效'; } }
function thresholdChanged() { if (form.value) desiredFill.value = Math.max(0, form.value.people - combinationRequiredReal(form.value.people, form.value.virtual)); }
function fillChanged() { if (!draftCurrent()) return; const people = form.value!.people, fill = desiredFill.value; if (!Number.isSafeInteger(people) || people < 2 || !Number.isSafeInteger(fill) || fill < 0 || fill >= people) return; form.value!.virtual = Math.max(1, Math.min(100, Math.floor((people - fill) / people * 100))); }
function recomputeVirtual() { if (!draftCurrent()) return; desiredFill.value = Math.max(0, Math.min(desiredFill.value, form.value!.people - 1)); fillChanged(); }
function addImages(images: { reference: string; preview: string }[]) { if (!draftCurrent()) return; try { const refs = images.map(item => combinationPicture(item.reference)); if (form.value!.images.length + refs.length > 10 || new Set([...form.value!.images, ...refs]).size !== form.value!.images.length + refs.length || [...JSON.stringify([...form.value!.images, ...refs])].length > 2000) throw Error('轮播图重复或超过10张/2000字容量'); form.value!.images.push(...refs); form.value!.images_preview.push(...images.map(item => preview(item.preview))); formError.value = ''; } catch (reason) { formError.value = reason instanceof Error ? reason.message : '图片无效'; } }
function moveImage(from: number, to: number) { if (!draftCurrent() || !Number.isInteger(from) || !Number.isInteger(to) || from < 0 || to < 0 || from >= form.value!.images.length || to >= form.value!.images.length) return; const [reference] = form.value!.images.splice(from, 1), [signed] = form.value!.images_preview.splice(from, 1); form.value!.images.splice(to, 0, reference!); form.value!.images_preview.splice(to, 0, signed!); imageDragging.value = -1; }
function removeImage(index: number) { if (draftCurrent() && Number.isInteger(index) && index >= 0 && index < form.value!.images.length) { form.value!.images.splice(index, 1); form.value!.images_preview.splice(index, 1); } }
function chooseSkuImage(sku: CombinationSku, images: { reference: string; preview: string }[]) { if (!draftCurrent() || !form.value!.skus.includes(sku) || sku.retired || !sku.enabled || images.length !== 1) return; try { sku.image = combinationPicture(images[0]!.reference, 128); sku.image_preview = preview(images[0]!.preview); formError.value = ''; } catch (reason) { formError.value = reason instanceof Error ? reason.message : '规格图片无效'; } }
function selectSkus(enabled: boolean) { if (draftCurrent()) form.value!.skus.forEach(sku => { if (!enabled || (sku.valid && !sku.retired)) sku.enabled = enabled; }); }
function applyBatch() { if (!draftCurrent()) return; try { const price = batchPrice.value.trim(), quota = batchQuota.value.trim(); if (!price && !quota) throw Error('请填写批量价格或总额度'); const nextPrice = price ? combinationMoney(price) : null, nextQuota = quota ? Number(quota) : null; if (quota && (!/^(?:0|[1-9]\d{0,9})$/u.test(quota) || !Number.isSafeInteger(nextQuota) || nextQuota! > 2147483647)) throw Error('批量额度须为非负整数'); const affected = form.value!.skus.filter(sku => sku.enabled && !sku.retired); if (!affected.length) throw Error('没有可修改的参与规格'); if (nextQuota !== null && affected.some(sku => !Number.isSafeInteger(sku.consumed) || sku.consumed < 0 || nextQuota < sku.consumed)) throw Error('总额度不能小于任何规格已消耗量，本批价格与额度均未修改'); affected.forEach(sku => { if (nextPrice !== null) sku.price = nextPrice; if (nextQuota !== null) sku.quota_total = nextQuota; }); formError.value = ''; } catch (reason) { formError.value = reason instanceof Error ? reason.message : '批量配置错误'; } }
async function mutate(operation: Mutation, value: Stamp, editor?: number) { const active = () => current(value) && canManage.value && (editor === undefined || editor === editorGeneration); if (!active() || submitting.value) return; const serial = ++mutationId, controller = new AbortController(); mutationAbort = controller; submitting.value = true; actionNotice.value = ''; try { if (operation.kind === 'save') await apiCombinationSave(operation.id, operation.body, controller.signal); else if (operation.kind === 'status') await apiCombinationStatus(operation.id, operation.body, controller.signal); else await apiCombinationDelete(operation.id, operation.body, controller.signal); if (!active() || serial !== mutationId) return; uncertainOperation.value = null; ElMessage.success('拼团操作已完成'); } catch (reason) { if (!active() || serial !== mutationId) return; const rejected = reason instanceof AdminResponseError && [400, 403, 404, 409, 422].includes(Number(reason.status)); uncertainOperation.value = rejected ? null : operation; actionNotice.value = `${rejected ? '操作未完成' : '操作结果未确认'}：${reason instanceof Error ? reason.message : '请求失败'}。请GET重新读取核对，勿重复提交。`; } finally { if (serial === mutationId) { mutationAbort = null; submitting.value = false; } } if (active()) await load(); }
async function save() { if (!draftCurrent() || !formScope || optionsLoading.value || optionsError.value || !options.value) return; let input: CombinationInput; try { if (!formId.value && !form.value!.skus.some(sku => sku.enabled && !sku.retired)) throw Error('新建或复制须至少一个参与规格'); for (const sku of form.value!.skus) if (sku.enabled && (sku.retired || sku.quota_total < sku.consumed)) throw Error('规格已退役或总额度小于已消耗量'); input = normalizeCombinationInput({ ...form.value!, skus: form.value!.skus.filter(sku => formId.value || !sku.retired && (sku.valid || sku.enabled)).map(sku => ({ id: sku.id, base_unique: sku.base_unique, enabled: sku.enabled, price: sku.price, quota_total: sku.quota_total, image: sku.image })) }); } catch (reason) { formError.value = reason instanceof Error ? reason.message : '配置错误'; return; } formError.value = ''; await mutate({ kind: 'save', id: formId.value, body: { ...input, request_id: crypto.randomUUID(), ...(formId.value ? { revision: form.value!.revision } : {}) } }, formScope, editorGeneration); }
function currentRow(row: CombinationRow) { return list.value.some(item => item.id === row.id && item.revision === row.revision); }
async function confirmAction(row: CombinationRow, kind: 'status' | 'delete') { if (!ready.value || loading.value || busy.value || !canManage.value || !currentRow(row)) return; if (kind === 'status' && row.status === 0 && !row.valid) { actionNotice.value = '请先修复有效配置后再上架。'; return; } row = { ...row }; const value = stamp(), serial = ++confirmId; confirming.value = true; try { await ElMessageBox.confirm(kind === 'delete' ? `确认删除拼团「${row.title || row.id}」？从列表移除，已有订单继续按成团规则处理。` : `确认${row.status ? '下架' : '上架'}拼团「${row.title || row.id}」？${row.status ? '尚未完成的团将提前到期，并按成团规则结算或退款；已有订单继续处理。' : '已有订单继续按成团规则处理。'}`, kind === 'delete' ? '删除拼团' : '修改拼团上架状态', { type: 'warning', confirmButtonText: '确认', cancelButtonText: '取消' }); } catch { return; } finally { if (serial === confirmId) confirming.value = false; } if (!current(value) || !canManage.value || serial !== confirmId || !currentRow(row)) return; const body = { revision: row.revision, request_id: crypto.randomUUID() }; await mutate(kind === 'delete' ? { kind, id: row.id, body } : { kind, id: row.id, body: { ...body, status: row.status ? 0 : 1 } }, value); }
function toggleStatus(row: CombinationRow) { return confirmAction(row, 'status'); } function remove(row: CombinationRow) { return confirmAction(row, 'delete'); }
function nextTab() { formTab.value = formTab.value === 'source' ? 'base' : 'content'; void hydrateRich(); } function previousTab() { formTab.value = formTab.value === 'content' ? 'base' : 'source'; }
function seedContentPreviews(value: string) { if (typeof DOMParser === 'undefined') return; const document = new DOMParser().parseFromString(value, 'text/html'); for (const node of document.body.querySelectorAll('img, a[href]')) { const signed = preview(node.getAttribute(node.tagName === 'A' ? 'href' : 'src') || ''); if (!signed) continue; const reference = /^\/api\/assets\/[1-9]\d*(?:\?|$)/u.test(signed) ? signed.split('?')[0]! : signed; extraPreviews.set(reference, signed); } }
function safeDescription(value: string) { if (typeof DOMParser === 'undefined') return ''; const document = new DOMParser().parseFromString(value, 'text/html'), allowed = new Set(['P','BR','STRONG','B','EM','I','U','S','UL','OL','LI','H1','H2','H3','H4','BLOCKQUOTE','TABLE','THEAD','TBODY','TR','TH','TD','SPAN','DIV','A','IMG']); for (const node of [...document.body.querySelectorAll('*')]) { if (!allowed.has(node.tagName)) { if (['SCRIPT','STYLE','IFRAME','OBJECT','SVG','MATH','FORM'].includes(node.tagName)) node.remove(); else node.replaceWith(...node.childNodes); continue; } const imageReference = node.tagName === 'IMG' ? node.getAttribute('data-reference') || node.getAttribute('src') || '' : ''; const href = node.tagName === 'A' ? node.getAttribute('href') || '' : ''; for (const attribute of [...node.attributes]) node.removeAttribute(attribute.name); if (node.tagName === 'A') { const signed = extraPreviews.get(href) || (/^https:\/\//iu.test(href) ? preview(href) : ''); if (signed) { node.setAttribute('href', signed); node.setAttribute('data-reference', href); node.setAttribute('rel', 'noopener noreferrer'); } } if (node.tagName === 'IMG') { const index = form.value?.images.indexOf(imageReference) ?? -1, signed = extraPreviews.get(imageReference) || (index >= 0 ? form.value!.images_preview[index] : ''); if (!preview(signed || '')) { node.remove(); continue; } node.setAttribute('src', signed!); node.setAttribute('data-reference', imageReference); } } return document.body.innerHTML; }
async function hydrateRich() { await nextTick(); if (contentEditor.value && form.value && formTab.value === 'content' && contentMode.value === 'visual') contentEditor.value.innerHTML = safeDescription(form.value.description); }
function readRich() { if (!draftCurrent() || !contentEditor.value) return; const clone = contentEditor.value.cloneNode(true) as HTMLElement; clone.querySelectorAll('img[data-reference], a[data-reference]').forEach(node => { node.setAttribute(node.tagName === 'A' ? 'href' : 'src', node.getAttribute('data-reference')!); node.removeAttribute('data-reference'); }); form.value!.description = clone.innerHTML; }
function formatContent(command: string, value?: string) { if (!draftCurrent() || !contentEditor.value) return; contentEditor.value.focus(); document.execCommand(command, false, value); readRich(); }
function insertContentImages(images: { reference: string; preview: string }[]) { if (!draftCurrent()) return; try { for (const image of images) { const reference = combinationPicture(image.reference); extraPreviews.set(reference, preview(image.preview)); form.value!.description += `<p><img src="${reference.replace(/&/gu, '&amp;').replace(/"/gu, '&quot;')}" /></p>`; } void hydrateRich(); } catch (reason) { formError.value = reason instanceof Error ? reason.message : '内容图片错误'; } }
function syncSession() { syncing = true; invalidate(); const session = getAdminSession(); auth.$patch({ token: getToken() ?? '', userInfo: session?.userInfo ?? null, menus: (session?.menus as typeof auth.menus) ?? [], uniqueAuth: session?.uniqueAuth ?? [] }); stored = localStorage.getItem('admin_session'); syncing = false; page.value = 1; keyword.value = draftKeyword.value = ''; phase.value = draftPhase.value = ''; status.value = draftStatus.value = ''; void load(1); }
function storage(event: StorageEvent) { if (event.key === null || event.key === 'admin_session' || event.key === 'admin_token') syncSession(); }
watch(identity, () => { if (alive && !syncing) { invalidate(); void load(1); } }, { flush: 'sync' });
onMounted(() => { alive = true; window.addEventListener('resize', resize); window.addEventListener('admin-session-changed', syncSession); window.addEventListener('admin-auth-expired', syncSession); window.addEventListener('storage', storage); syncSession(); });
onBeforeUnmount(() => { alive = false; invalidate(); window.removeEventListener('resize', resize); window.removeEventListener('admin-session-changed', syncSession); window.removeEventListener('admin-auth-expired', syncSession); window.removeEventListener('storage', storage); });
</script>
<style scoped>
.combinations{min-width:0}.heading{display:flex;justify-content:space-between;gap:15px;align-items:center;flex-wrap:wrap;margin-bottom:18px}.heading h2{font-size:20px;margin:0}.hint{color:#747b87;font-size:12px;line-height:1.6}.filters,.toolbar,.actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.filters{align-items:end;margin-bottom:18px}.filters label{display:grid;gap:6px;flex:1 1 170px;font-size:13px}.filters :deep(.el-select){width:100%}.toolbar{margin:12px 0}.toolbar :deep(.el-input){flex:1 1 160px;max-width:260px}.toolbar :deep(.el-select),.toolbar :deep(.el-cascader){flex:1 1 180px;max-width:260px;min-width:0}.actions{gap:6px}.actions :deep(.el-button + .el-button){margin:0}.table-scroll{max-width:100%;overflow-x:auto}.pager{justify-content:flex-end;flex-wrap:wrap;margin:18px 0}.notice{margin-bottom:12px}.product-name{display:flex;gap:10px;align-items:center}.product-name :deep(.el-image){width:42px;height:42px;flex-shrink:0}.legacy pre,.source-summary pre{white-space:pre-wrap;overflow-wrap:anywhere}.dates{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.dates input{min-width:0;width:100%;box-sizing:border-box;padding:7px;border:1px solid #dcdfe6;border-radius:4px;font:inherit}.inset{margin:4px 0 18px 125px}.image-editor{display:flex;gap:12px;flex-wrap:wrap}.image-editor article{display:grid;gap:5px;width:150px}.image-editor :deep(.el-image){width:150px;height:120px}.sku-image{width:50px;height:50px}.bad{font-size:12px;color:#c45656}.manage-link{margin-left:12px;font-size:13px;color:#409eff}fieldset{border:1px solid #dcdfe6;border-radius:5px;padding:15px;min-width:0}.rich-editor,.rich-preview{min-height:300px;border:1px solid #dcdfe6;border-radius:4px;padding:15px;overflow-wrap:anywhere}.rich-editor :deep(img),.rich-preview :deep(img){max-width:100%;height:auto}.rich-editor:focus{outline:2px solid #409eff}.source-summary{padding:15px 0}
@media(max-width:650px){.filters{display:grid;grid-template-columns:minmax(0,1fr)}.dates{grid-template-columns:minmax(0,1fr)}.inset{margin-left:0}.toolbar :deep(.el-select),.toolbar :deep(.el-cascader){max-width:100%}.pager{justify-content:center}.image-editor article{width:120px}.image-editor :deep(.el-image){width:120px;height:100px}}
</style>
