import {asc,eq,sql} from 'drizzle-orm';
import {customerWorkFinancialFixture} from './customerWorkFinancialFixture';
import {runCustomerWriteoffOperation,customerWriteoffOperationReadiness} from '../../src/migrations/runCustomerWriteoffOperation';
import {runCashierSecondCardOrigin,cashierSecondCardOriginReadiness} from '../../src/migrations/runCashierSecondCardOrigin';
import {CUSTOMER_WRITEOFF_FUNCTIONS} from '../../src/migrations/customerWriteoffRuntimePlan';
import {CASHIER_SECOND_CARD_FUNCTIONS,CASHIER_SECOND_CARD_TABLES,CASHIER_SECOND_CARD_PURCHASE_APPEND_TABLES,cashierSecondCardRuntimePrivilegePlan} from '../../src/migrations/cashierSecondCardRuntimePlan';
import {storeOrder,storeOrderCartInfo,storeOrderWriteoff,storeOrderPromotions,storeCart,storeProduct,storeProductAttrValue,systemConfig,user,storeOrderEconomize,paymentReconciliationCase,storeServiceRecord,agentLevelTask,agentLevelTaskRecord,supplierFlowingWater,supplierTransactions,storePromotions,storePromotionsAuxiliary,storeProductRelation} from '../../src/models/schema';
import {customerWriteoffRuntimePrivilegePlan} from '../../src/migrations/customerWriteoffRuntimePlan';
import {CustomerWorkWriteoffService} from '../../src/services/customer-work/CustomerWorkWriteoffService';
import {authorizeCustomerWorkActor} from '../../src/services/customer-work/CustomerWorkScope';
import {StoreOrderCreateService,type StoreOrderCreationRuntime} from '../../src/services/order/StoreOrderCreateService';
import {applyStoreOrderBalancePayment} from '../../src/services/order/StoreOrderPayService';
import {createCustomerCashierSecondCardWithRuntime,applyCustomerCashierCashPayment} from '../../src/services/customer-work/CustomerWorkCashierService';
import {OrderOutboxService} from '../../src/services/order/OrderOutboxService';
import {CUSTOMER_WRITEOFF_VERSION,type WriteoffInput} from '../../src/services/customer-work/CustomerWorkWriteoffProtocol';
import {auditCheckoutPricingLockRuntime} from '../../src/migrations/checkoutPricingLock';
import {installCashierSecondCardPromotionLock,inspectCashierSecondCardPromotionLock,cashierSecondCardPromotionLockGrantSql} from '../../src/migrations/cashierSecondCardPromotionLock';

/** Registered disposable PG16 only. The inherited fixture supplies a genuine
 * independent ordinary LOGIN; maintenance explicitly adds just the new append
 * realms and validators. Nothing repairs an HTTP runtime or a production ACL. */
export async function customerWorkWriteoffFixture(){
 const f=await customerWorkFinancialFixture(),quoteCache=new Map<string,string>();let sequence=0;
 try{
  const kit=await import('drizzle-kit/api');for(const statement of await kit.generateMigration(kit.generateDrizzleJson({}),kit.generateDrizzleJson({storeOrderEconomize,paymentReconciliationCase,supplierFlowingWater,supplierTransactions,storeOrderPromotions,storePromotions,storePromotionsAuxiliary,storeProductRelation})))if(/^CREATE (?:UNIQUE )?INDEX/.test(statement.trim()))await f.exec(statement);
  const[conversation]=await f.maintenanceDb.execute<{present:boolean}>(sql`SELECT to_regclass('public.store_service_record') IS NOT NULL AS present`);if(!conversation.present)for(const statement of await kit.generateMigration(kit.generateDrizzleJson({}),kit.generateDrizzleJson({storeServiceRecord})))await f.exec(statement);
  for(const[name,table]of [['agent_level_task',agentLevelTask],['agent_level_task_record',agentLevelTaskRecord]] as const){const[present]=await f.maintenanceDb.execute<{present:boolean}>(sql`SELECT to_regclass(${`public.${name}`}) IS NOT NULL AS present`);if(!present.present)for(const statement of await kit.generateMigration(kit.generateDrizzleJson({}),kit.generateDrizzleJson({[name]:table})))await f.exec(statement);}
  await runCustomerWriteoffOperation(f.maintenanceDb);await runCashierSecondCardOrigin(f.maintenanceDb);
  const role='"'+f.role.replaceAll('"','""')+'"';
  for(const table of ['customer_writeoff_operation_request',...CASHIER_SECOND_CARD_TABLES])await f.exec(`GRANT SELECT,INSERT ON public.${table} TO ${role}`);
  await f.exec(`GRANT SELECT ON public.store_service_record TO ${role}`);
  const profile=customerWriteoffRuntimePrivilegePlan();for(const name of ['agent_level_task','agent_level_task_record']){const permissions=profile.tables[name];if(!permissions?.length)throw Error('Existing reviewed runtime profile lacks agent task capability');await f.exec(`GRANT ${permissions.join(',')} ON public.${name} TO ${role}`);if(permissions.includes('INSERT'))await f.exec(`GRANT USAGE ON SEQUENCE public.${name}_id_seq TO ${role}`);}
  const cashierProfile=cashierSecondCardRuntimePrivilegePlan(),promotionPrivileges=cashierProfile.tables.store_order_promotions;
  if(JSON.stringify(CASHIER_SECOND_CARD_PURCHASE_APPEND_TABLES)!==JSON.stringify(['store_order_promotions'])||JSON.stringify(promotionPrivileges)!==JSON.stringify(['SELECT','INSERT'])||JSON.stringify(cashierProfile.updateColumns.store_order_promotions)!==JSON.stringify(['id']))throw Error('Reviewed cashier profile lacks exact append/read and guarded-id order-promotion capability');
  await f.exec(`GRANT ${promotionPrivileges.join(',')} ON public.store_order_promotions TO ${role}`);
  const ownedPromotionSequences=await f.maintenanceDb.execute<{name:string}>(sql`SELECT s.relname AS name FROM pg_catalog.pg_class s JOIN pg_catalog.pg_namespace n ON n.oid=s.relnamespace JOIN pg_catalog.pg_depend d ON d.objid=s.oid AND d.deptype IN('a','i') JOIN pg_catalog.pg_class t ON t.oid=d.refobjid JOIN pg_catalog.pg_attribute a ON a.attrelid=t.oid AND a.attnum=d.refobjsubid WHERE s.relkind='S' AND n.nspname='public' AND t.oid='public.store_order_promotions'::regclass AND a.attname='id'`);
  if(ownedPromotionSequences.length!==1||!/^store_order_promotions_id_seq$/.test(ownedPromotionSequences[0].name))throw Error('Actual cashier order-promotion sequence ownership is incomplete');
  await f.exec(`GRANT USAGE ON SEQUENCE public.${ownedPromotionSequences[0].name} TO ${role}`);
  await installCashierSecondCardPromotionLock(f.maintenanceDb,f.role);
  if(!(await inspectCashierSecondCardPromotionLock(f.maintenanceDb,f.role)).ready)throw Error('Actual cashier promotion lock guard was not installed and verified');
  await f.exec(cashierSecondCardPromotionLockGrantSql(f.role));
  for(const signature of [...CUSTOMER_WRITEOFF_FUNCTIONS,...CASHIER_SECOND_CARD_FUNCTIONS])await f.exec(`GRANT EXECUTE ON FUNCTION public.${signature} TO ${role}`);
  for(const status of [await customerWriteoffOperationReadiness(f.db),await cashierSecondCardOriginReadiness(f.db)])if(!status.ready)throw Error('Actual customer writeoff/cashier ordinary runtime was not commissioned: '+JSON.stringify(status));
  const pricing=await auditCheckoutPricingLockRuntime(f.db,'public','customer-work');if(!pricing.ready)throw Error('Actual customer writeoff promotion pricing runtime was not commissioned: '+JSON.stringify(pricing));
  const env={...f.env,CONFIG_KV:{get:async(key:string)=>quoteCache.get(key)??null,put:async(key:string,value:string)=>{quoteCache.set(key,value);},delete:async(key:string)=>{quoteCache.delete(key);}} as KVNamespace};
  const runtime:StoreOrderCreationRuntime={...env,nextOrderId:async()=>`native-writeoff-${++sequence}`};
  const service=()=>new CustomerWorkWriteoffService(f.container,env),scope=async(uid=101)=>authorizeCustomerWorkActor(f.db,f.actor(uid));
  const order=async(id=1)=>(await f.db.select().from(storeOrder).where(eq(storeOrder.id,id)))[0];
  const reset=async()=>{quoteCache.clear();await f.exec('ALTER TABLE public.store_order_purchase_origin DISABLE TRIGGER USER;TRUNCATE public.store_order_purchase_origin;ALTER TABLE public.store_order_purchase_origin ENABLE TRIGGER USER');await f.reset();await f.exec(`TRUNCATE public.customer_writeoff_operation_request,public.${CASHIER_SECOND_CARD_TABLES.join(',public.')} RESTART IDENTITY`);await f.maintenanceDb.delete(storeOrderEconomize);await f.maintenanceDb.delete(paymentReconciliationCase);await f.maintenanceDb.delete(storeOrderWriteoff);await f.maintenanceDb.delete(storeCart);await f.maintenanceDb.insert(storeCart).values({id:1,uid:11,productId:70,productAttrUnique:'qared001',cartNum:2,isNew:1,status:1});await f.exec("SELECT setval(pg_get_serial_sequence('store_cart','id'),1,true)");
   await f.maintenanceDb.update(user).set({exp:'0.00',brokeragePrice:'0.00',pwd:'owned-financial-password'}).where(sql`${user.uid} IN(11,101,102,103,104,105)`);
   for(let id=1;id<=3;id++){await f.maintenanceDb.update(storeOrder).set({orderId:'native-physical-'+id,storeId:1,shippingType:2,productType:4,verifyCode:`12345678900${id}`,totalNum:2,payPrice:'10.00',totalPrice:'10.00'}).where(eq(storeOrder.id,id));await f.maintenanceDb.update(storeOrderCartInfo).set({cartId:'opaque-card-'+id,skuUnique:'qared001',productType:4,writeTimes:6,writeSurplusTimes:6,isWriteoff:0,writeStart:0,writeEnd:0,cartInfo:JSON.stringify({id:'opaque-card-'+id,cart_num:2,truePrice:'5.00',productInfo:{id:70,price:'10.00',store_name:'真实旧次卡',image:'/api/qa/image.svg',attrInfo:{unique:'qared001',price:'10.00',write_times:3,suk:'Red'}}})}).where(eq(storeOrderCartInfo.id,id));}
   await f.maintenanceDb.delete(supplierFlowingWater);await f.maintenanceDb.delete(supplierTransactions);await f.maintenanceDb.delete(storeOrderPromotions);await f.maintenanceDb.delete(storePromotionsAuxiliary);await f.maintenanceDb.delete(storePromotions);await f.maintenanceDb.delete(storeProductRelation);
   await f.maintenanceDb.update(storeProduct).set({type:0,relationId:0,productType:0,isPresaleProduct:0,stock:100,sales:0,freight:2}).where(eq(storeProduct.id,70));await f.maintenanceDb.update(storeProductAttrValue).set({stock:100,sales:0,price:'10.00',vipPrice:'7.00',settlePrice:'0.00',writeTimes:3,writeValid:1,writeDays:0,writeStart:0,writeEnd:0}).where(eq(storeProductAttrValue.id,1));
   for(const key of ['first_order_status','newcomer_status','member_func_status','member_card_status','svip_price_status','order_give_integral','order_give_exp','brokerage_func_status','store_brokerage_statu']){await f.maintenanceDb.delete(systemConfig).where(eq(systemConfig.menuName,key));await f.maintenanceDb.insert(systemConfig).values({menuName:key,value:'0'});}
  };
  const input=async(id=1,items?:Array<{cart_row_id:number;writeoff_num:number}>):Promise<WriteoffInput>=>{const s=await scope(),o=await order(id),target=(await service().reader.order(f.actor(),id,{scope_key:s.scope_key,order_no:o.orderId})).data;return{version:CUSTOMER_WRITEOFF_VERSION,scope_key:s.scope_key,order_id:id,expected_order_revision:target.order_revision,expected_writeoff_revision:target.writeoff_revision,payload:{order_no:target.order_no,root_order_id:target.root_order_id,root_order_no:target.root_order_no,code:target.code,target_fingerprint:target.target_fingerprint,items:items??target.carts.filter(c=>c.write_surplus_times>0).map(c=>({cart_row_id:c.cart_row_id,writeoff_num:c.write_surplus_times}))}};};
  const consume=async(outbox:{id:number;eventKey:string})=>{const consumer=new OrderOutboxService(f.container,env),message={action:'processOrderPaidOutbox' as const,outboxId:outbox.id,eventKey:outbox.eventKey};const result=await consumer.processMessage(message);if(result!=='completed')throw Error('Genuine original paid outbox did not complete: '+result);return{consumer,message};};
  const ordinary=async()=>{await f.maintenanceDb.update(storeProductAttrValue).set({price:'7.00'}).where(eq(storeProductAttrValue.id,1));const params={uid:11,key:crypto.randomUUID().replaceAll('-',''),cartIds:[1],shippingType:2,storeId:1,type:0,realName:'原生购买用户',userPhone:'00000000000',userIp:'',useIntegral:false};const created=await StoreOrderCreateService.createWithRuntime(f.container,{...runtime,requirePurchaseOrigin:true},params),o=await f.container.storeOrderDao.findByOrderId(created.orderId);if(!o)throw Error('Actual checkout did not persist order');const paid=await applyStoreOrderBalancePayment(f.container,{uid:11,orderId:o.orderId});if(!paid.outbox)throw Error('Actual balance payment did not persist paid outbox');await consume(paid.outbox);return await order(o.id);};
  const cashier=async(buyer=11,price='7.00',quantity=2)=>{await f.maintenanceDb.update(storeProduct).set({productType:4}).where(eq(storeProduct.id,70));await f.maintenanceDb.update(storeProductAttrValue).set({price,writeTimes:3}).where(eq(storeProductAttrValue.id,1));const s=await scope(),created=await createCustomerCashierSecondCardWithRuntime(f.container,runtime,f.actor(),{request_key:crypto.randomUUID(),version:'customer-cashier-second-card-v1',scope_key:s.scope_key,buyer_uid:buyer,tourist_key:buyer?'':'native-guest-writeoff',product_id:70,sku_unique:'qared001',quantity,real_name:buyer?'原生现金用户':'原生游客',user_phone:'00000000000',mark:'',custom_form:[],coupon_id:0,use_integral:false}),o=await f.container.storeOrderDao.findByOrderId(created.orderId);if(!o)throw Error('Genuine cashier did not persist order');const payment=await applyCustomerCashierCashPayment(f.container,f.actor(),{request_key:crypto.randomUUID(),version:'customer-cashier-second-card-payment-v1',scope_key:s.scope_key,order_id:o.id,order_no:o.orderId,expected_amount:o.payPrice});if(!payment.outbox)throw Error('Genuine cashier payment did not persist original event');const consumed=await consume(payment.outbox);return{order:await order(o.id),created,payment,...consumed};};
  const effects=async()=>({orders:await f.db.select().from(storeOrder).orderBy(asc(storeOrder.id)),carts:await f.db.select().from(storeOrderCartInfo).orderBy(asc(storeOrderCartInfo.id)),records:await f.db.select().from(storeOrderWriteoff).orderBy(asc(storeOrderWriteoff.id))});
  await reset();return{...f,env,reset,service,scope,input,order,ordinary,cashier,consume,effects,runtime};
 }catch(error){await f.close();throw error;}
}
