import {randomUUID} from 'node:crypto';
import {SQL,sql} from 'drizzle-orm';
import {getTableConfig,PgDialect} from 'drizzle-orm/pg-core';
import {Hono} from 'hono';
import {createContainerFromDb,type DbClient} from '../../src/lib/di';
import type {AppVariables,Env} from '../../src/env';
import {user,storeService,deliveryService,expressCompany,systemStoreStaff,userGroup,userLabel,userLabelRelation,userLevel,systemUserLevel,legacyCategory,storeCouponIssue,storeCouponUser,storeCouponIssueUser,userBill,userMoney,otherOrder,otherOrderStatus,storeOrder,systemAttachment,systemLog,adminUserWriteReplay,userAddress} from '../../src/models/schema';
import {sequenceRunnerDatabase,type SequenceRunnerPeer} from './kefuSequenceRunnerDatabase';
import {installCustomerWorkScopeLock} from '../../src/migrations/runCustomerWorkScopeLock';
import {CUSTOMER_WORK_LOCK_FUNCTIONS} from '../../src/migrations/customerWorkRuntimePrivilegePlan';
import {runCustomerUserOperation} from '../../src/migrations/runCustomerUserOperation';
import {installCustomerUserCatalogLock} from '../../src/migrations/runCustomerUserCatalogLock';
import {customerUserRuntimePrivilegePlan,CUSTOMER_USER_FUNCTIONS} from '../../src/migrations/customerUserRuntimePlan';
import {CustomerWorkUserReadService} from '../../src/services/customer-work/CustomerWorkUserReadService';
import {CustomerWorkUserOperationService} from '../../src/services/customer-work/CustomerWorkUserOperationService';
import type {CustomerWorkActor} from '../../src/services/customer-work/CustomerWorkScope';
import {authMiddleware} from '../../src/middleware/auth';
import * as Controller from '../../src/controllers/api/v1/CustomerWorkUserController';
import {md5} from '../../src/utils/jwt';

const ident=(name:string)=>{if(!/^[a-z_][a-z_0-9]*$/.test(name))throw Error('Invalid user fixture identifier');return`"${name}"`;};
export const customerUserTables=[user,storeService,deliveryService,expressCompany,systemStoreStaff,userGroup,userLabel,userLabelRelation,userLevel,systemUserLevel,legacyCategory,storeCouponIssue,storeCouponUser,storeCouponIssueUser,userBill,userMoney,otherOrder,otherOrderStatus,storeOrder,systemAttachment,systemLog,adminUserWriteReplay,userAddress];
export async function customerWorkUserFixture(){
 const f=await sequenceRunnerDatabase();if(f.format!=='pg16'||!f.withRuntimeRole){await f.close();throw Error('Customer users require native PG16 independent LOGIN');}
 const owners=[`customer_user_scope_${randomUUID().replaceAll('-','')}`,`customer_user_taxonomy_${randomUUID().replaceAll('-','')}`],created:string[]=[];
 try{
  const dialect=new PgDialect();for(const table of customerUserTables){const d=getTableConfig(table),columns=d.columns.map(c=>{const initial=c.default,value=initial===undefined?'':` DEFAULT ${initial instanceof SQL?dialect.sqlToQuery(initial).sql:dialect.sqlToQuery(sql`${initial}`.inlineParams()).sql}`;return`${ident(c.name)} ${c.getSQLType()}${value}${c.notNull?' NOT NULL':''}${c.primary?' PRIMARY KEY':''}${c.isUnique?' UNIQUE':''}`;});await f.exec(`CREATE TABLE public.${ident(d.name)} (${columns.join(',')})`);}
  await runCustomerUserOperation(f.db);
  for(const owner of owners){await f.exec(`CREATE ROLE ${ident(owner)} NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS`);created.push(owner);}
  await installCustomerWorkScopeLock(f.db,owners[0]);await installCustomerUserCatalogLock(f.db,owners[1]);
  const tableNames=[...customerUserTables.map(t=>getTableConfig(t).name),'customer_user_operation_request'];
  const actor=(uid=101):CustomerWorkActor=>({uid,auth_version:md5('owned-customer-password'),expires_at:Math.floor(Date.now()/1000)+3600});
  const env={APP_KEY:'owned-customer-user-key',UPSTASH_REDIS_URL:'',UPSTASH_REDIS_TOKEN:'',CONFIG_KV:{get:async()=>null,put:async()=>{},delete:async()=>{}}} as unknown as Env;
  const issue=(id:number,values:Partial<typeof storeCouponIssue.$inferInsert>={})=>({id,cid:id+1000,title:`真实赠券${id}`,couponTitle:`真实赠券${id}`,type:1,couponType:0,couponPrice:'5.00',useMinPrice:'20.00',receiveType:3,remainCount:20,totalCount:20,status:1,day:3,...values});
  const reset=async()=>{
   await f.exec(`TRUNCATE ${tableNames.map(n=>`public.${ident(n)}`).join(',')} RESTART IDENTITY`);
   const now=Math.floor(Date.now()/1000);await f.db.insert(user).values([...Array.from({length:12},(_,i)=>({uid:101+i,account:`user-actor-${i}`,pwd:'owned-customer-password',nickname:`经营用户${i}`,status:1,isDel:0})),{uid:201,nickname:'百分%_\\ Alice',phone:'12345678901',nowMoney:'12.34',integral:50,groupId:10,level:30,levelStatus:1,addTime:1600000000,birthday:946656000,realName:'真实姓名',cardId:'真实证件',addres:'真实地址'},{uid:202,nickname:'停用目标',status:0,groupId:10},{uid:203,nickname:'已删除目标',isDel:1},{uid:204,nickname:'时间删除目标',deleteTime:new Date(0)},{uid:205,nickname:'永久会员',isMoneyLevel:1,isEverLevel:1},{uid:206,nickname:'过期会员',isMoneyLevel:2,overdueTime:now-100},{uid:207,nickname:'有效会员',isMoneyLevel:3,overdueTime:now+86400*10}]);
   await f.db.insert(storeService).values([{id:1,uid:101,account:'customer-chat-off',customer:1,accountStatus:1,status:0},{id:2,uid:102,account:'kefu-only',customer:0,accountStatus:1,status:1},{id:3,uid:106,account:'disabled-role',customer:1,accountStatus:0},{id:4,uid:107,account:'deleted-role',customer:1,isDel:1}]);
   await f.db.insert(systemStoreStaff).values([{id:1,uid:103,storeId:77,status:1,isManager:1,orderStatus:1},{id:2,uid:104,storeId:77,status:1,verifyStatus:1}]);await f.db.insert(deliveryService).values({id:1,uid:105,type:0,relationId:0,status:1});
   await f.db.insert(userGroup).values([{id:10,groupName:'真实分组'},{id:11,groupName:'新分组'}]);
   await f.db.insert(systemUserLevel).values([{id:30,name:'原等级',grade:1,discount:'90.00',isShow:1,isForever:1,expNum:10},{id:31,name:'新等级',grade:2,discount:'80.00',isShow:1,isForever:1,expNum:20},{id:32,name:'隐藏等级',isShow:0},{id:33,name:'删除等级',isShow:1,isDel:1}]);
   await f.db.insert(legacyCategory).values([{id:1,name:'平台用户标签组',group:0,type:0,relationId:0,isShow:1},{id:2,name:'他店用户标签组',group:0,type:1,relationId:77,isShow:1},{id:3,name:'隐藏组',group:0,type:0,relationId:0,isShow:0}]);
   await f.db.insert(userLabel).values([{id:20,labelCate:1,name:'平台用户标签',type:0,relationId:0,status:1},{id:21,labelCate:1,name:'他店用户标签',type:1,relationId:77,status:1},{id:22,labelCate:3,name:'隐藏组标签',type:0,relationId:0,status:1},{id:23,labelCate:1,name:'另平台标签',type:0,relationId:0,status:1},{id:24,labelCate:1,name:'停用标签',type:0,relationId:0,status:0}]);
   await f.db.insert(userLabelRelation).values([{id:1,uid:201,labelId:20,type:0,relationId:0},{id:2,uid:201,labelId:21,type:1,relationId:77}]);
   await f.db.insert(userLevel).values({id:1,uid:201,levelId:30,grade:1,status:1,isDel:0,isForever:1});
   await f.db.insert(storeCouponIssue).values([issue(40),issue(41,{receiveType:1}),issue(42,{status:0}),issue(43,{isDel:1}),issue(44,{remainCount:0}),issue(45,{startTime:new Date((now+100)*1000),endTime:new Date((now+200)*1000)}),issue(46,{day:0,useEndTime:new Date((now-100)*1000)}),issue(47,{remainCount:0,isPermanent:1})]);
   await f.db.insert(storeCouponUser).values([{id:1,uid:201,issueCouponId:40,couponTitle:'未来券',couponPrice:'5.00',useMinPrice:'20.00',startTime:new Date((now+100)*1000),endTime:new Date((now+200)*1000),type:1,status:0,receiveTime:now},{id:2,uid:201,issueCouponId:40,couponTitle:'过期券',couponPrice:'5.00',useMinPrice:'20.00',startTime:new Date((now-200)*1000),endTime:new Date((now-100)*1000),type:1,status:0},{id:3,uid:201,issueCouponId:40,couponTitle:'已使用券',status:1,type:1},{id:4,uid:202,issueCouponId:40,couponTitle:'他人券',status:0,type:1}]);
   await f.db.insert(storeOrder).values([{id:1,uid:201,orderId:'ROOT-1',paid:1,pid:-1,payPrice:'10.00'},{id:2,uid:201,orderId:'CHILD-2',paid:1,pid:1,payPrice:'0.29'},{id:3,uid:201,orderId:'CHILD-3',paid:1,pid:1,payPrice:'0.28',storeId:77},{id:4,uid:201,orderId:'ROOT-4',paid:1,pid:0,payPrice:'12.34',supplierId:88},{id:5,uid:201,orderId:'REFUND-5',paid:1,pid:0,payPrice:'20.00',refundStatus:2},{id:6,uid:201,orderId:'DELETED-6',paid:1,pid:0,payPrice:'90.00',isSystemDel:1}]);
   const sequences=await f.exec("SELECT c.relname AS table_name,a.attname AS column_name FROM pg_class seq JOIN pg_depend d ON d.objid=seq.oid AND d.deptype IN('a','i') JOIN pg_class c ON c.oid=d.refobjid JOIN pg_attribute a ON a.attrelid=c.oid AND a.attnum=d.refobjsubid WHERE seq.relkind='S'");for(const row of sequences){const table=String(row.table_name),column=String(row.column_name);if(!tableNames.includes(table))throw Error('Unexpected user fixture sequence owner');await f.exec(`SELECT setval(pg_get_serial_sequence('public.${table}','${column}'),COALESCE((SELECT MAX(${ident(column)}) FROM public.${ident(table)}),1),EXISTS(SELECT 1 FROM public.${ident(table)}))`);}
  };
  const app=async<T>(callback:(db:DbClient,role:string,peer:SequenceRunnerPeer)=>Promise<T>)=>f.withRuntimeRole!(async peer=>{
   const plan=customerUserRuntimePrivilegePlan();for(const name of tableNames){const privileges=plan.tables[name];if(!privileges){if(name==='admin_user_write_replay')continue;throw Error(`Missing fixed customer user privileges for ${name}`);}if(privileges.length)await f.exec(`GRANT ${privileges.join(',')} ON public.${ident(name)} TO ${ident(peer.role)}`);const columns=plan.updateColumns[name];if(columns?.length)await f.exec(`GRANT UPDATE(${columns.map(ident).join(',')}) ON public.${ident(name)} TO ${ident(peer.role)}`);}
   const sequences=await f.exec("SELECT seq.relname AS name,t.relname AS table_name FROM pg_class seq JOIN pg_depend d ON d.objid=seq.oid AND d.deptype IN('a','i') JOIN pg_class t ON t.oid=d.refobjid WHERE seq.relkind='S'");for(const s of sequences)if(plan.tables[String(s.table_name)]?.includes('INSERT'))await f.exec(`GRANT USAGE ON SEQUENCE public.${ident(String(s.name))} TO ${ident(peer.role)}`);
   for(const signature of[...CUSTOMER_WORK_LOCK_FUNCTIONS,...CUSTOMER_USER_FUNCTIONS])await f.exec(`GRANT EXECUTE ON FUNCTION public.${signature} TO ${ident(peer.role)}`);
   const[row]=await peer.exec("SELECT current_user AS role,session_user AS session,(SELECT rolsuper OR rolcreatedb OR rolcreaterole OR rolinherit OR rolreplication OR rolbypassrls FROM pg_roles WHERE rolname=current_user) AS elevated,has_table_privilege(current_user,'user_label','INSERT,UPDATE,DELETE') AS taxonomy_dml,has_table_privilege(current_user,'customer_user_operation_request','UPDATE,DELETE,TRUNCATE') AS ledger_dml,has_table_privilege(current_user,'admin_user_write_replay','SELECT,INSERT,UPDATE,DELETE') AS admin_replay,has_table_privilege(current_user,'user_money','UPDATE,DELETE') AS money_mutation,has_column_privilege(current_user,'store_service','customer','UPDATE') AS role_dml");if(row.role!==peer.role||row.session!==peer.role||row.elevated!==false||row.taxonomy_dml!==false||row.ledger_dml!==false||row.admin_replay!==false||row.money_mutation!==false||row.role_dml!==false)throw Error('User fixture must use independent non-forging LOGIN');return callback(peer.db,peer.role,peer);
  });
  const taxonomyWriter=async<T>(callback:(peer:SequenceRunnerPeer&{role:string})=>Promise<T>)=>f.withRuntimeRole!(async peer=>{for(const name of['user_group','user_label','system_user_level','category'])await f.exec(`GRANT SELECT,INSERT,UPDATE,DELETE ON public.${ident(name)} TO ${ident(peer.role)}`);return callback(peer);});
  const reader=(db:DbClient)=>new CustomerWorkUserReadService(createContainerFromDb(db),env),writer=(db:DbClient)=>new CustomerWorkUserOperationService(createContainerFromDb(db));
  const http=(db:DbClient)=>{const h=new Hono<{Bindings:Env;Variables:AppVariables}>();h.use('*',async(c,next)=>{c.set('container',createContainerFromDb(db));await next();});h.use('*',authMiddleware({force:true}));h.onError((error,c)=>c.json({status:400,msg:error.message,data:null},400));h.get('/users',Controller.userList);h.get('/users/groups',Controller.userGroups);h.get('/users/levels',Controller.userLevels);h.get('/users/labels',Controller.userLabels);h.get('/users/coupon-grants',Controller.couponGrants);h.get('/users/operations/:key',Controller.userOperationOutcome);h.post('/users/operations/:key/abandon',Controller.abandonUserOperation);h.get('/users/:uid/coupons',Controller.userCoupons);h.get('/users/:uid',Controller.userDetail);h.post('/users/replace-level',Controller.replaceUserLevel);h.post('/users/replace-group',Controller.replaceUserGroup);h.post('/users/replace-labels',Controller.replaceUserLabels);h.post('/users/grant-coupons',Controller.grantUserCoupons);h.post('/users/adjust-membership',Controller.adjustUserMembership);h.post('/users/adjust-money',Controller.adjustUserMoney);h.post('/users/adjust-integral',Controller.adjustUserIntegral);return h;};
  await reset();return{...f,reset,actor,env,issue,app,taxonomyWriter,reader,writer,http,tableNames,close:async()=>{try{for(const owner of created.reverse())await f.exec(`DROP OWNED BY ${ident(owner)}; DROP ROLE ${ident(owner)}`);}finally{await f.close();}}};
 }catch(error){try{for(const owner of created.reverse())await f.exec(`DROP OWNED BY ${ident(owner)}; DROP ROLE ${ident(owner)}`);}finally{await f.close();}throw error;}
}
