// Shared adversarial definitions exercised through both maintenance runner and raw SQL file.
export const shippingLifecycleCatalogMutations = [
  ['argument default', 'CREATE OR REPLACE FUNCTION public.shipping_lifecycle_ref(temp integer,freight integer DEFAULT 3) RETURNS integer LANGUAGE sql IMMUTABLE STRICT SECURITY INVOKER SET search_path=pg_catalog,pg_temp AS $$ SELECT CASE WHEN temp>0 THEN temp WHEN freight NOT IN (1,2) THEN 1 ELSE 0 END $$'],
  ['argument types', 'DROP FUNCTION public.shipping_lifecycle_ref(integer,integer); CREATE FUNCTION public.shipping_lifecycle_ref(temp smallint,freight smallint) RETURNS integer LANGUAGE sql IMMUTABLE STRICT SECURITY INVOKER SET search_path=pg_catalog,pg_temp AS $$ SELECT CASE WHEN temp>0 THEN temp WHEN freight NOT IN (1,2) THEN 1 ELSE 0 END $$'],
  ['return type', 'DROP FUNCTION public.shipping_lifecycle_ref(integer,integer); CREATE FUNCTION public.shipping_lifecycle_ref(temp integer,freight integer) RETURNS bigint LANGUAGE sql IMMUTABLE STRICT SECURITY INVOKER SET search_path=pg_catalog,pg_temp AS $$ SELECT CASE WHEN temp>0 THEN temp WHEN freight NOT IN (1,2) THEN 1 ELSE 0 END $$'],
  ['implementation language', 'CREATE OR REPLACE FUNCTION public.shipping_lifecycle_ref(temp integer,freight integer) RETURNS integer LANGUAGE plpgsql IMMUTABLE STRICT SECURITY INVOKER SET search_path=pg_catalog,pg_temp AS $$ BEGIN RETURN CASE WHEN temp>0 THEN temp WHEN freight NOT IN (1,2) THEN 1 ELSE 0 END; END $$'],
  ['body', 'CREATE OR REPLACE FUNCTION public.shipping_lifecycle_ref(temp integer,freight integer) RETURNS integer LANGUAGE sql IMMUTABLE STRICT SECURITY INVOKER SET search_path=pg_catalog,pg_temp AS $$ SELECT 0 $$'],
  ['strictness', 'ALTER FUNCTION public.shipping_lifecycle_ref(integer,integer) CALLED ON NULL INPUT'],
  ['volatility', 'ALTER FUNCTION public.shipping_lifecycle_ref(integer,integer) STABLE'],
  ['security definer', 'ALTER FUNCTION public.shipping_lifecycle_child() SECURITY DEFINER'],
  ['search path', "ALTER FUNCTION public.shipping_lifecycle_child() SET search_path=public,pg_temp"],
  ['RLS setting', 'ALTER FUNCTION public.shipping_lifecycle_child() SET row_security=on'],
  ['extra function configuration', "ALTER FUNCTION public.shipping_lifecycle_child() SET work_mem='1MB'"],
  ['parallel safety', 'ALTER FUNCTION public.shipping_lifecycle_ref(integer,integer) PARALLEL SAFE'],
  ['planner cost', 'ALTER FUNCTION public.shipping_lifecycle_ref(integer,integer) COST 1'],
  ['leakproof', 'ALTER FUNCTION public.shipping_lifecycle_ref(integer,integer) LEAKPROOF'],
  ['missing function', 'DROP FUNCTION public.shipping_lifecycle_parent() CASCADE'],
  ['overload', 'CREATE FUNCTION public.shipping_lifecycle_ref(bigint,bigint) RETURNS integer LANGUAGE sql AS $$ SELECT 0 $$'],
  ['extra reserved function', 'CREATE FUNCTION public.shipping_lifecycle_extra() RETURNS integer LANGUAGE sql AS $$ SELECT 0 $$'],
  ['removed execute ACL', 'REVOKE EXECUTE ON FUNCTION public.shipping_lifecycle_ref(integer,integer) FROM PUBLIC'],
  ['disabled trigger', 'ALTER TABLE public.store_bargain DISABLE TRIGGER shipping_lifecycle_child'],
  ['replica-only trigger', 'ALTER TABLE public.store_bargain ENABLE REPLICA TRIGGER shipping_lifecycle_child'],
  ['always trigger', 'ALTER TABLE public.store_bargain ENABLE ALWAYS TRIGGER shipping_lifecycle_child'],
  ['missing trigger', 'DROP TRIGGER shipping_lifecycle_child ON public.store_bargain'],
  ['renamed trigger', 'ALTER TRIGGER shipping_lifecycle_child ON public.store_bargain RENAME TO qa_renamed_guard'],
  ['before trigger', 'CREATE OR REPLACE TRIGGER shipping_lifecycle_child BEFORE INSERT OR UPDATE OR DELETE ON public.store_bargain FOR EACH ROW EXECUTE FUNCTION public.shipping_lifecycle_child()'],
  ['statement-level trigger', 'CREATE OR REPLACE TRIGGER shipping_lifecycle_child AFTER INSERT OR UPDATE OR DELETE ON public.store_bargain FOR EACH STATEMENT EXECUTE FUNCTION public.shipping_lifecycle_child()'],
  ['transition tables', 'CREATE OR REPLACE TRIGGER shipping_lifecycle_child AFTER UPDATE ON public.store_bargain REFERENCING OLD TABLE AS previous_rows NEW TABLE AS incoming_rows FOR EACH ROW EXECUTE FUNCTION public.shipping_lifecycle_child()'],
  ['column-limited trigger', 'CREATE OR REPLACE TRIGGER shipping_lifecycle_child AFTER UPDATE OF temp_id ON public.store_bargain FOR EACH ROW EXECUTE FUNCTION public.shipping_lifecycle_child()'],
  ['trigger condition', 'CREATE OR REPLACE TRIGGER shipping_lifecycle_child AFTER INSERT OR UPDATE OR DELETE ON public.store_bargain FOR EACH ROW WHEN(false) EXECUTE FUNCTION public.shipping_lifecycle_child()'],
  ['trigger arguments', "CREATE OR REPLACE TRIGGER shipping_lifecycle_child AFTER INSERT OR UPDATE OR DELETE ON public.store_bargain FOR EACH ROW EXECUTE FUNCTION public.shipping_lifecycle_child('unexpected')"],
  ['wrong trigger function', 'CREATE OR REPLACE TRIGGER shipping_lifecycle_child AFTER INSERT OR UPDATE OR DELETE ON public.store_bargain FOR EACH ROW EXECUTE FUNCTION public.shipping_lifecycle_parent()'],
  ['deferred constraint trigger', 'DROP TRIGGER shipping_lifecycle_child ON public.store_bargain; CREATE CONSTRAINT TRIGGER shipping_lifecycle_child AFTER INSERT OR UPDATE OR DELETE ON public.store_bargain DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.shipping_lifecycle_child()'],
  ['duplicate attachment', 'CREATE TRIGGER qa_duplicate_guard AFTER INSERT ON public.store_bargain FOR EACH ROW EXECUTE FUNCTION public.shipping_lifecycle_child()'],
  ['extra table attachment', 'CREATE TRIGGER qa_foreign_table_guard AFTER INSERT ON public.store_order FOR EACH ROW EXECUTE FUNCTION public.shipping_lifecycle_child()'],
] as const;
