<template>
  <div class="coupon-templates">
    <div class="heading"><div><h2>优惠券模板</h2><p class="hint">模板定义面额、使用门槛、领券后有效天数和适用范围；每次发布生成独立发行快照。</p></div><el-button v-if="canManage" type="primary" :disabled="busy || !!uncertainOperation" @click="openCreate">添加优惠券模板</el-button></div>
    <el-alert v-if="!canView" title="当前账号没有优惠券模板查看权限" type="warning" :closable="false" />
    <template v-else>
      <div class="filters"><label>模板名称<el-input v-model="draftKeyword" maxlength="100" clearable aria-label="模板名称筛选" @keyup.enter="search" /></label><label>有效状态<el-select v-model="draftStatus" clearable placeholder="全部状态" @change="search"><el-option label="有效" :value="1" /><el-option label="已失效" :value="0" /></el-select></label><el-button :disabled="busy" @click="search">查询</el-button><el-button :disabled="busy" @click="reset">重置</el-button></div>
      <el-alert v-if="notice" :title="notice" type="warning" :closable="false" class="notice" />
      <el-alert v-if="uncertainOperation" title="操作结果未确认，请核对后再继续写入" type="warning" :closable="false" class="notice"><p>操作：{{ operationLabel(uncertainOperation.kind) }} · 请求ID：{{ uncertainOperation.body.request_id }}</p><p class="hint">草稿及此次操作信息已保留。重新读取不会重复提交；列表或记录中的相似内容不能单独确认此次操作结果。</p><details><summary>保留的操作内容</summary><pre>{{ JSON.stringify(uncertainOperation.body, null, 2) }}</pre></details><div class="actions"><el-button :disabled="busy" @click="reconcile()">只重新读取核对</el-button><el-button :disabled="busy" @click="acknowledge">已人工核对，结束此次操作</el-button></div></el-alert>
      <el-alert v-if="listError" :title="listError" type="error" :closable="false"><template #default><el-button link @click="load()">重试列表</el-button></template></el-alert>
      <div v-if="!listError" class="table-scroll"><el-table :data="list" row-key="id" border v-loading="loading"><el-table-column prop="id" label="ID" width="75" /><el-table-column label="模板名称" min-width="190"><template #default="{ row }">{{ row.title || '未命名模板' }}<el-tag v-if="!row.valid" type="danger" size="small">历史数据需核对</el-tag></template></el-table-column><el-table-column label="适用范围" min-width="200"><template #default="{ row }">{{ scopeLabel(row) }}</template></el-table-column><el-table-column prop="coupon_price" label="面额" width="100" /><el-table-column prop="use_min_price" label="使用门槛" width="110" /><el-table-column prop="valid_days" label="有效天数" width="100" /><el-table-column prop="sort" label="排序" width="80" /><el-table-column prop="issue_count" label="发布次数" width="100" /><el-table-column label="状态" width="100"><template #default="{ row }">{{ row.status ? '有效' : '已失效' }}</template></el-table-column><el-table-column label="添加时间" min-width="165"><template #default="{ row }">{{ timeLabel(row.add_time) }}</template></el-table-column><el-table-column label="操作" :fixed="compact ? undefined : 'right'" width="270"><template #default="{ row }"><div class="actions"><el-button link :disabled="busy || loading" @click="openDetail(row, 'view')">详情 / 发布记录</el-button><el-button v-if="canPublish" link type="primary" :disabled="busy || loading || !!uncertainOperation || !row.valid || !row.status || row.deleted" @click="openDetail(row, 'publish')">发布</el-button><el-button v-if="canManage && row.status" link type="warning" :disabled="busy || loading || !!uncertainOperation" @click="confirmAction(row, 'invalidate')">立即失效</el-button><el-button v-if="canManage" link type="danger" :disabled="busy || loading || !!uncertainOperation" @click="confirmAction(row, 'delete')">删除</el-button></div></template></el-table-column></el-table></div>
      <el-pagination v-if="ready && !loading && !listError" :current-page="page" :page-size="15" :total="count" layout="total, prev, pager, next" @current-change="load" class="pager" :disabled="busy" />
      <p class="hint">创建后模板内容不可编辑，失效后不可恢复。失效会停止关联发行，已领取的优惠券继续有效；删除仅移除模板，已有发行与已领券继续处理。</p>
    </template>
    <el-dialog v-model="editorVisible" :title="mode === 'create' ? '添加优惠券模板' : mode === 'publish' ? '发布优惠券模板' : '模板详情与发布记录'" width="min(900px, calc(100vw - 24px))" top="5vh" :close-on-click-modal="false" :close-on-press-escape="!writing" :show-close="!writing" @closed="onEditorClosed">
      <div v-loading="editorLoading"><el-alert v-if="editorError" :title="editorError" type="error" :closable="false" class="notice"><template #default><el-button v-if="mode !== 'create' && !detail" link @click="readDetail">重试详情</el-button></template></el-alert>
        <template v-if="mode === 'create'"><el-alert v-if="optionsError" :title="optionsError" type="error" :closable="false"><template #default><el-button link @click="loadOptions">重读范围选项</el-button></template></el-alert><el-form label-width="125px" :disabled="writing || !!uncertainOperation"><el-form-item label="模板名称" required><el-input v-model="form.title" maxlength="128" placeholder="1–64个字符" /></el-form-item><el-form-item label="适用范围" required><el-radio-group v-model="form.scope_type"><el-radio :value="0">通用券</el-radio><el-radio :value="1">品类券</el-radio><el-radio :value="2">商品券</el-radio></el-radio-group></el-form-item><el-form-item v-if="form.scope_type === 1" label="适用品类" required><el-cascader v-model="form.category_id" :options="categoryTree" :props="{ checkStrictly: true, emitPath: false }" filterable clearable placeholder="选择一个品类" :disabled="optionsLoading || !!optionsError" /></el-form-item><el-form-item v-if="form.scope_type === 2" label="适用商品" required><div><el-button :disabled="optionsLoading || !!optionsError || !options" @click="openProducts">选择商品（{{ form.product_ids.length }}）</el-button><div class="selected"><el-tag v-for="product in selectedProducts" :key="product.id" closable @close="removeSelected(product.id)">#{{ product.id }} {{ product.store_name }}</el-tag></div><p class="hint">跨页选择后一次确认，最多100个商品且ID列表不超过500字符。</p></div></el-form-item><el-form-item label="优惠券面额" required><el-input v-model="form.coupon_price" inputmode="decimal" placeholder="大于0，最多2位小数" /></el-form-item><el-form-item label="最低消费金额" required><el-input v-model="form.use_min_price" inputmode="decimal" placeholder="0表示无门槛" /></el-form-item><el-form-item label="领券后有效天数" required><el-input-number v-model="form.valid_days" :min="1" :max="3650" :precision="0" /></el-form-item><el-form-item label="排序"><el-input-number v-model="form.sort" :min="0" :max="2147483647" :precision="0" /></el-form-item><el-form-item label="有效状态"><el-switch v-model="form.status" :active-value="1" :inactive-value="0" /></el-form-item></el-form></template>
        <template v-else-if="detail"><el-alert v-if="detail.issues.length" :title="detail.issues.join('；')" type="warning" :closable="false" /><dl class="snapshot"><dt>模板</dt><dd>#{{ detail.id }} {{ detail.title }}</dd><dt>面额 / 门槛</dt><dd>{{ detail.coupon_price }} / {{ detail.use_min_price }}</dd><dt>领券后有效天数</dt><dd>{{ detail.valid_days }}</dd><dt>适用范围</dt><dd>{{ scopeLabel(detail) }}<ul v-if="detail.scope_type === 2"><li v-for="product in detail.products" :key="product.id">#{{ product.id }} {{ product.store_name || '商品已缺失' }} {{ product.deleted ? '（已删除）' : '' }}</li></ul></dd><dt>模板状态</dt><dd>{{ detail.deleted ? '已删除' : detail.status ? '有效' : '已失效' }}</dd><dt>排序 / 添加时间</dt><dd>{{ detail.sort }} / {{ timeLabel(detail.add_time) }}</dd></dl>
          <template v-if="mode === 'publish'"><p class="hint">以上模板内容将作为本次发行快照，之后模板失效会停止关联发行。</p><el-form label-width="125px" :disabled="writing || !!uncertainOperation || !detail.valid || !detail.status || detail.deleted"><el-form-item label="发行用途"><el-select v-model="publishForm.receive_type"><el-option :value="1" label="普通领取券" /><el-option :value="2" label="新人券" /><el-option :value="3" label="赠送券" /></el-select></el-form-item><el-alert v-if="publishForm.receive_type === 2" title="新人赠券需要在注册赠券配置中关联本次发行。发布不会自动修改注册赠券配置。" type="info" :closable="false" class="notice" /><el-alert v-if="publishForm.receive_type === 3" title="赠送券需要关联赠券渠道；填写满赠金额不会自动发券。" type="info" :closable="false" class="notice" /><el-form-item label="不限发行数量"><el-switch v-model="publishForm.is_permanent" :active-value="1" :inactive-value="0" /></el-form-item><el-form-item v-if="!publishForm.is_permanent" label="发行数量" required><el-input-number v-model="publishForm.count" :min="1" :max="2147483647" :precision="0" /></el-form-item><div class="dates"><el-form-item label="领取开始时间"><input v-model="publishStart" type="datetime-local" aria-label="领取开始时间" :disabled="writing || !!uncertainOperation || !detail.valid || !detail.status || detail.deleted" /></el-form-item><el-form-item label="领取结束时间"><input v-model="publishEnd" type="datetime-local" aria-label="领取结束时间" :disabled="writing || !!uncertainOperation || !detail.valid || !detail.status || detail.deleted" /></el-form-item></div><p class="hint inset">上海时间。两项同时留空表示不限制领取时间；填写时需完整且结束时间尚未到期。</p><el-form-item v-if="publishForm.receive_type === 3" label="满赠金额"><el-input v-model="publishForm.full_reduction" inputmode="decimal" /></el-form-item><el-form-item label="发行状态"><el-switch v-model="publishForm.status" :active-value="1" :inactive-value="0" /></el-form-item></el-form></template>
          <template v-else><div class="heading"><h3>发布记录</h3><el-button :disabled="historyLoading" @click="loadHistory()">刷新发布记录</el-button></div><el-alert v-if="historyError" :title="historyError" type="error" :closable="false"><template #default><el-button link @click="loadHistory()">重试发布记录</el-button></template></el-alert><div v-else class="table-scroll"><el-table :data="history" border v-loading="historyLoading"><el-table-column prop="issue_id" label="发行ID" width="90" /><el-table-column prop="title" label="发行快照名称" min-width="160" /><el-table-column label="用途" width="100"><template #default="{ row }">{{ receiveLabel(row.receive_type) }}</template></el-table-column><el-table-column label="状态" width="90"><template #default="{ row }">{{ issueStatus(row.status) }}</template></el-table-column><el-table-column label="总量 / 剩余" min-width="135"><template #default="{ row }">{{ issueAmount(row) }}</template></el-table-column><el-table-column label="领取窗口（上海）" min-width="280"><template #default="{ row }">{{ isoLabel(row.start_time) }} — {{ isoLabel(row.end_time) }}</template></el-table-column><el-table-column label="发布时间" min-width="165"><template #default="{ row }">{{ timeLabel(row.issued_at) }}</template></el-table-column><el-table-column prop="source_revision" label="源模板版本" min-width="230" /></el-table></div><el-pagination v-if="!historyLoading && !historyError" :current-page="historyPage" :page-size="15" :total="historyCount" layout="total, prev, pager, next" @current-change="loadHistory" class="pager" /></template>
        </template>
      </div><template #footer><el-button :disabled="writing" @click="closeEditor">{{ mode === 'view' ? '关闭' : '取消' }}</el-button><el-button v-if="mode === 'create' && canManage" type="primary" :disabled="editorLoading || optionsLoading || !!optionsError || !!uncertainOperation" :loading="writing" @click="save">创建模板</el-button><el-button v-if="mode === 'publish' && canPublish" type="primary" :disabled="editorLoading || !detail?.valid || !detail?.status || detail?.deleted || !!uncertainOperation" :loading="writing" @click="publish">确认发布</el-button></template>
    </el-dialog>
    <el-dialog v-model="productsVisible" title="选择适用商品" width="min(780px, calc(100vw - 24px))" append-to-body :close-on-click-modal="false" @closed="onProductsClosed"><div class="filters"><el-input v-model="productKeyword" aria-label="适用商品名称" maxlength="100" clearable @keyup.enter="loadProducts(1)" /><el-button @click="loadProducts(1)">查询</el-button><el-button :disabled="productsLoading" @click="selectPage(true)">选中本页</el-button><el-button :disabled="productsLoading" @click="selectPage(false)">取消本页</el-button></div><el-alert v-if="productError" :title="productError" type="error" :closable="false"><template #default><el-button link @click="loadProducts()">重试选品</el-button></template></el-alert><p>已选 {{ choices.size }} 个 / 100</p><div class="selected"><el-tag v-for="product in [...choices.values()]" :key="product.id" closable @close="unchoose(product.id)">#{{ product.id }} {{ product.store_name }}</el-tag></div><div class="table-scroll"><el-table :data="products" row-key="id" border v-loading="productsLoading"><el-table-column label="选择" width="75"><template #default="{ row }"><el-checkbox :model-value="choices.has(row.id)" :disabled="productsLoading" @change="choose(row, !!$event)" /></template></el-table-column><el-table-column prop="id" label="商品ID" width="100" /><el-table-column prop="store_name" label="商品名称" min-width="230" /></el-table></div><el-pagination v-if="!productsLoading && !productError" :current-page="productPage" :page-size="15" :total="productCount" layout="total, prev, pager, next" @current-change="loadProducts" class="pager" /><template #footer><el-button @click="closeProducts">取消</el-button><el-button type="primary" :disabled="productsLoading || !!productError" @click="applyProducts">确认所选商品</el-button></template></el-dialog>
  </div>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { useAuthStore } from '@/stores/auth';
import { getAdminSession, getToken } from '@/utils/auth';
import { AdminResponseError } from '@/utils/request';
import { apiCouponTemplateList, apiCouponTemplateOptions, apiCouponTemplateProducts, apiCouponTemplateDetail, apiCouponTemplateIssues, apiCouponTemplateCreate, apiCouponTemplateInvalidate, apiCouponTemplateDelete, apiCouponTemplatePublish, normalizeCouponTemplate, normalizeCouponTemplatePublish, couponTemplateUtc, couponCategoryTree, type CouponTemplateRow, type CouponTemplateInput, type CouponTemplateOptions, type CouponTemplateProduct, type CouponTemplateIssue, type CouponTemplatePublish, type CouponTemplateMutationKey } from '@/api/couponTemplate';
type Mode = 'create' | 'view' | 'publish'; type Stamp = { identity: string; generation: number; stored: string | null }; type Job = { stamp: Stamp; controller: AbortController };
type Mutation = { kind: 'create'; body: CouponTemplateInput & { request_id: string } } | { kind: 'publish'; body: CouponTemplatePublish & { request_id: string } } | { kind: 'invalidate' | 'delete'; id: number; body: CouponTemplateMutationKey };
const auth = useAuthStore(), has = (key: string) => !!auth.userInfo && (auth.userInfo.level === 0 || auth.uniqueAuth.includes(key));
const canView = computed(() => !!auth.token && auth.token === getToken() && has('coupon_template.view')), canManage = computed(() => canView.value && has('coupon_template.manage')), canPublish = computed(() => canView.value && has('coupon_template_issue.manage'));
const identity = computed(() => JSON.stringify([auth.token, auth.userInfo?.id, auth.userInfo?.level, auth.uniqueAuth])), compact = ref(window.innerWidth < 650);
const list = ref<CouponTemplateRow[]>([]), ready = ref(false), loading = ref(false), listError = ref(''), page = ref(1), count = ref(0), keyword = ref(''), status = ref<'' | 0 | 1>(1), draftKeyword = ref(''), draftStatus = ref<'' | 0 | 1>(1);
const editorVisible = ref(false), mode = ref<Mode>('create'), editorLoading = ref(false), editorError = ref(''), detail = ref<CouponTemplateRow | null>(null), detailId = ref(0), form = ref<CouponTemplateInput>(blank()), selectedProducts = ref<CouponTemplateProduct[]>([]);
const options = ref<CouponTemplateOptions | null>(null), optionsLoading = ref(false), optionsError = ref(''), categoryTree = computed(() => options.value ? couponCategoryTree(options.value.categories) : []);
const history = ref<CouponTemplateIssue[]>([]), historyLoading = ref(false), historyError = ref(''), historyPage = ref(1), historyCount = ref(0);
const publishForm = ref({ receive_type: 1 as 1 | 2 | 3, status: 1 as 0 | 1, is_permanent: 0 as 0 | 1, count: 1, full_reduction: '0.00' }), publishStart = ref(''), publishEnd = ref('');
const productsVisible = ref(false), products = ref<CouponTemplateProduct[]>([]), productsLoading = ref(false), productError = ref(''), productPage = ref(1), productCount = ref(0), productKeyword = ref(''), choices = ref(new Map<number, CouponTemplateProduct>());
const writing = ref(false), confirming = ref(false), busy = computed(() => writing.value || confirming.value), notice = ref(''), uncertainOperation = ref<Mutation | null>(null);
let alive = false, syncing = false, generation = 0, editorGeneration = 0, pickerGeneration = 0, confirmGeneration = 0, stored = localStorage.getItem('admin_session'); const jobs = new Map<string, Job>();
function blank(): CouponTemplateInput { return { title: '', scope_type: 0, category_id: 0, product_ids: [], coupon_price: '', use_min_price: '0.00', valid_days: 1, sort: 0, status: 1 }; }
function stamp(): Stamp { return { identity: identity.value, generation, stored }; }
function current(value: Stamp) { return alive && canView.value && value.generation === generation && value.identity === identity.value && value.stored === localStorage.getItem('admin_session') && auth.token === getToken(); }
function start(channel: string): Job { jobs.get(channel)?.controller.abort(); const job = { stamp: stamp(), controller: new AbortController() }; jobs.set(channel, job); return job; }
function valid(channel: string, job: Job) { return current(job.stamp) && jobs.get(channel) === job && !job.controller.signal.aborted; }
function finish(channel: string, job: Job) { if (jobs.get(channel) !== job) return false; jobs.delete(channel); return true; }
function cancel(channel: string) { jobs.get(channel)?.controller.abort(); jobs.delete(channel); }
function editable() { return current(stamp()) && canManage.value && editorVisible.value && mode.value === 'create' && !writing.value && !uncertainOperation.value; }
function pickerCurrent(job: Job, editor: number, picker: number) { return valid('products', job) && editable() && productsVisible.value && editor === editorGeneration && picker === pickerGeneration; }
function message(reason: unknown) { return reason instanceof Error ? reason.message : '读取失败，请重试'; }
function scopeLabel(row: CouponTemplateInput & { category_name?: string }) { return row.scope_type === 0 ? '通用券' : row.scope_type === 1 ? `品类券 · ${row.category_name || `#${row.category_id}`}` : `商品券 · ${row.product_ids.length}个商品`; }
function timeLabel(seconds: number) { return seconds ? new Date(seconds * 1000).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai', hour12: false }) : '—'; }
function isoLabel(value: string | null) { return value ? new Date(value).toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai', hour12: false }) : '不限'; }
function receiveLabel(value: number) { return ({ 1: '普通领取', 2: '新人券', 3: '赠送券' } as Record<number, string>)[value] || `未知 #${value}`; }
function issueStatus(value: number) { return ({ 1: '开启', 0: '关闭', '-1': '已失效' } as Record<number, string>)[value] || `历史状态 #${value}`; }
function issueAmount(row: CouponTemplateIssue) { return row.is_permanent === 1 ? '不限量' : `${row.is_permanent === 0 ? '' : `未知标记 #${row.is_permanent} · `}${row.total_count} / ${row.remain_count}`; }
function operationLabel(value: Mutation['kind']) { return { create: '创建模板', publish: '发布发行', invalidate: '模板失效', delete: '删除模板' }[value]; }
async function load(target: number = page.value) { if (!current(stamp()) || !Number.isSafeInteger(target) || target < 1 || target > 667) return; const job = start('list'); page.value = target; loading.value = true; ready.value = false; list.value = []; count.value = 0; listError.value = ''; try { const result = await apiCouponTemplateList({ page: target, limit: 15, keyword: keyword.value, status: status.value }, job.controller.signal); if (!valid('list', job)) return; if (!result.list.length && target > 1) { await load(Math.max(1, Math.min(target - 1, Math.ceil(result.count / 15)))); return; } list.value = result.list; count.value = result.count; ready.value = true; } catch (reason) { if (valid('list', job)) listError.value = message(reason); } finally { if (finish('list', job)) loading.value = false; } }
function search() { if (busy.value) return; keyword.value = draftKeyword.value.trim(); status.value = draftStatus.value === 0 || draftStatus.value === 1 ? draftStatus.value : ''; void load(1); }
function reset() { draftKeyword.value = ''; draftStatus.value = 1; search(); }
function closeProducts() { pickerGeneration++; cancel('products'); productsVisible.value = productsLoading.value = false; products.value = []; choices.value = new Map(); productError.value = ''; }
function onProductsClosed() { if (!productsVisible.value) closeProducts(); }
function closeEditor() { if (writing.value) return; editorGeneration++; closeProducts(); ['detail', 'options', 'history'].forEach(cancel); editorVisible.value = editorLoading.value = optionsLoading.value = historyLoading.value = false; detail.value = null; history.value = []; editorError.value = optionsError.value = historyError.value = ''; }
function onEditorClosed() { if (!editorVisible.value) closeEditor(); }
async function openCreate() { if (!canManage.value || busy.value || uncertainOperation.value || !current(stamp())) return; closeEditor(); mode.value = 'create'; form.value = blank(); selectedProducts.value = []; options.value = null; editorVisible.value = true; await loadOptions(); }
async function loadOptions() { if (!editable()) return; const job = start('options'), editor = editorGeneration; optionsLoading.value = true; optionsError.value = ''; try { const result = await apiCouponTemplateOptions(job.controller.signal); if (valid('options', job) && editor === editorGeneration && editable()) options.value = result; } catch (reason) { if (valid('options', job) && editor === editorGeneration) optionsError.value = message(reason); } finally { if (finish('options', job)) optionsLoading.value = false; } }
async function openDetail(row: CouponTemplateRow, next: 'view' | 'publish') { if (!ready.value || loading.value || busy.value || !current(stamp()) || !list.value.includes(row) || next === 'publish' && (!canPublish.value || uncertainOperation.value || !row.valid || !row.status || row.deleted)) return; closeEditor(); mode.value = next; detailId.value = row.id; editorVisible.value = true; if (next === 'publish') { publishForm.value = { receive_type: 1, status: 1, is_permanent: 0, count: 1, full_reduction: '0.00' }; publishStart.value = publishEnd.value = ''; } await readDetail(); }
async function readDetail() { if (!editorVisible.value || mode.value === 'create' || !current(stamp())) return; const job = start('detail'), editor = editorGeneration; editorLoading.value = true; editorError.value = ''; try { const result = await apiCouponTemplateDetail(detailId.value, job.controller.signal); if (!valid('detail', job) || editor !== editorGeneration || !editorVisible.value) return; detail.value = result; if (mode.value === 'view') await loadHistory(1); } catch (reason) { if (valid('detail', job) && editor === editorGeneration) editorError.value = message(reason); } finally { if (finish('detail', job)) editorLoading.value = false; } }
async function loadHistory(target: number = historyPage.value) { if (!editorVisible.value || !detail.value || !current(stamp()) || !Number.isSafeInteger(target) || target < 1 || target > 667) return; const job = start('history'), editor = editorGeneration; historyLoading.value = true; historyError.value = ''; history.value = []; historyCount.value = 0; historyPage.value = target; try { const result = await apiCouponTemplateIssues(detail.value.id, { page: target, limit: 15 }, job.controller.signal); if (valid('history', job) && editor === editorGeneration && editorVisible.value) { history.value = result.list; historyCount.value = result.count; } } catch (reason) { if (valid('history', job) && editor === editorGeneration) historyError.value = message(reason); } finally { if (finish('history', job)) historyLoading.value = false; } }
async function openProducts() { if (!editable() || !options.value || optionsLoading.value || optionsError.value || form.value.scope_type !== 2) return; closeProducts(); choices.value = new Map(selectedProducts.value.map(row => [row.id, { ...row }])); productsVisible.value = true; productKeyword.value = ''; await loadProducts(1); }
async function loadProducts(target: number = productPage.value) { if (!editable() || !productsVisible.value || !Number.isSafeInteger(target) || target < 1 || target > 667) return; const job = start('products'), editor = editorGeneration, picker = pickerGeneration; productsLoading.value = true; productError.value = ''; products.value = []; productCount.value = 0; productPage.value = target; try { const result = await apiCouponTemplateProducts({ page: target, limit: 15, keyword: productKeyword.value.trim() }, job.controller.signal); if (pickerCurrent(job, editor, picker)) { products.value = result.list; productCount.value = result.count; } } catch (reason) { if (pickerCurrent(job, editor, picker)) productError.value = message(reason); } finally { if (finish('products', job)) productsLoading.value = false; } }
function choose(row: CouponTemplateProduct, selected: boolean) { if (!editable() || !productsVisible.value || productsLoading.value || !products.value.includes(row)) return; const next = new Map(choices.value); if (selected) next.set(row.id, { ...row }); else next.delete(row.id); choices.value = next; if (productError.value.startsWith('所选商品超过')) productError.value = ''; }
function unchoose(id: number) { if (!editable() || !productsVisible.value) return; const next = new Map(choices.value); next.delete(id); choices.value = next; if (productError.value.startsWith('所选商品超过')) productError.value = ''; }
function selectPage(selected: boolean) { if (!editable() || productsLoading.value || !productsVisible.value) return; const next = new Map(choices.value); for (const row of products.value) { if (selected) next.set(row.id, { ...row }); else next.delete(row.id); } choices.value = next; if (productError.value.startsWith('所选商品超过')) productError.value = ''; }
function applyProducts() { if (!editable() || !productsVisible.value || productsLoading.value || productError.value) return; const selected = [...choices.value.values()]; if (selected.length > 100 || selected.map(row => row.id).join(',').length > 500) { productError.value = '所选商品超过100项或ID列表超过500字符，完整选择仍保留，请减少后确认'; return; } form.value.product_ids = selected.map(row => row.id); selectedProducts.value = selected; closeProducts(); }
function removeSelected(id: number) { if (!editable()) return; selectedProducts.value = selectedProducts.value.filter(row => row.id !== id); form.value.product_ids = form.value.product_ids.filter(value => value !== id); }
function authorized(operation: Mutation) { return operation.kind === 'publish' ? canPublish.value : canManage.value; }
async function mutate(operation: Mutation, editor?: number) { if (!current(stamp()) || !authorized(operation) || busy.value || uncertainOperation.value) return; const job = start('write'); writing.value = true; notice.value = ''; const active = () => valid('write', job) && authorized(operation) && (editor === undefined || editor === editorGeneration && editorVisible.value); try { if (operation.kind === 'create') await apiCouponTemplateCreate(operation.body, job.controller.signal); else if (operation.kind === 'publish') await apiCouponTemplatePublish(operation.body, job.controller.signal); else if (operation.kind === 'invalidate') await apiCouponTemplateInvalidate(operation.id, operation.body, job.controller.signal); else await apiCouponTemplateDelete(operation.id, operation.body, job.controller.signal); if (!active()) return; ElMessage.success(`${operationLabel(operation.kind)}已完成`); writing.value = false; if (editor !== undefined) closeEditor(); await load(); } catch (reason) { if (!active()) return; const rejected = reason instanceof AdminResponseError && [400, 403, 404, 409, 422].includes(Number(reason.status)); uncertainOperation.value = rejected ? null : operation; notice.value = `${rejected ? '操作未完成' : '操作结果未确认'}：${message(reason)}`; if (editor !== undefined) editorError.value = notice.value; writing.value = false; await reconcile(operation); } finally { if (finish('write', job)) writing.value = false; } }
async function save() { if (!editable() || optionsLoading.value || optionsError.value || !options.value) return; try { const body = normalizeCouponTemplate(form.value); if (body.scope_type === 1 && !options.value.categories.some(row => row.id === body.category_id)) throw Error('所选品类不在当前可用范围'); await mutate({ kind: 'create', body: { ...body, request_id: crypto.randomUUID() } }, editorGeneration); } catch (reason) { editorError.value = message(reason); } }
async function publish() { if (!canPublish.value || !current(stamp()) || mode.value !== 'publish' || !editorVisible.value || !detail.value?.valid || !detail.value.status || detail.value.deleted || editorLoading.value || busy.value || uncertainOperation.value) return; try { const body = normalizeCouponTemplatePublish({ ...publishForm.value, count: publishForm.value.is_permanent ? 0 : publishForm.value.count, full_reduction: publishForm.value.receive_type === 3 ? publishForm.value.full_reduction : '0.00', template_id: detail.value.id, revision: detail.value.revision, start_time: couponTemplateUtc(publishStart.value), end_time: couponTemplateUtc(publishEnd.value) }); await mutate({ kind: 'publish', body: { ...body, request_id: crypto.randomUUID() } }, editorGeneration); } catch (reason) { editorError.value = message(reason); } }
async function confirmAction(row: CouponTemplateRow, kind: 'invalidate' | 'delete') { if (!current(stamp()) || !canManage.value || !ready.value || loading.value || busy.value || uncertainOperation.value || !list.value.includes(row) || row.deleted || kind === 'invalidate' && !row.status) return; const value = stamp(), serial = ++confirmGeneration, id = row.id, revision = row.revision; confirming.value = true; try { await ElMessageBox.confirm(kind === 'invalidate' ? '模板将永久失效，关联发行将停止；不会取消已领取的优惠券。确认立即失效？' : '仅软删除模板，已有发行和已领取的优惠券不受影响。确认删除？', operationLabel(kind), { type: 'warning', confirmButtonText: '确认', cancelButtonText: '取消' }); } catch { return; } finally { if (serial === confirmGeneration) confirming.value = false; } if (!current(value) || serial !== confirmGeneration || !canManage.value || !list.value.some(value => value.id === id && value.revision === revision)) return; await mutate({ kind, id, body: { revision, request_id: crypto.randomUUID() } }); }
async function reconcile(operation: Mutation | null = uncertainOperation.value) { if (!current(stamp()) || busy.value) return; await load(); if (!operation || operation.kind === 'create' || !current(stamp())) return; const id = operation.kind === 'publish' ? operation.body.template_id : operation.id, job = start('reconcile'); try { await apiCouponTemplateDetail(id, job.controller.signal); if (!valid('reconcile', job)) return; if (operation.kind === 'publish') await apiCouponTemplateIssues(id, { page: 1, limit: 15 }, job.controller.signal); if (valid('reconcile', job)) notice.value += '；已重新读取详情与近期记录，请人工核对此次请求结果。'; } catch (reason) { if (valid('reconcile', job)) notice.value += `；核对读取失败：${message(reason)}`; } finally { finish('reconcile', job); } }
async function acknowledge() { if (!uncertainOperation.value || busy.value || !current(stamp())) return; const value = stamp(), operation = uncertainOperation.value; try { await ElMessageBox.confirm('确认已人工核对该请求结果？此操作仅结束本地待核对状态，不会再次提交。', '结束待核对操作', { confirmButtonText: '已核对', cancelButtonText: '取消', type: 'warning' }); } catch { return; } if (current(value) && uncertainOperation.value === operation) { uncertainOperation.value = null; notice.value = ''; } }
function invalidate() { generation++; confirmGeneration++; for (const job of jobs.values()) job.controller.abort(); jobs.clear(); if (confirming.value) ElMessageBox.close(); writing.value = confirming.value = false; closeEditor(); list.value = []; count.value = 0; ready.value = loading.value = false; listError.value = notice.value = ''; uncertainOperation.value = null; form.value = blank(); selectedProducts.value = []; options.value = null; }
function syncSession() { syncing = true; invalidate(); const session = getAdminSession(); auth.$patch({ token: getToken() ?? '', userInfo: session?.userInfo ?? null, menus: (session?.menus as typeof auth.menus) ?? [], uniqueAuth: session?.uniqueAuth ?? [] }); stored = localStorage.getItem('admin_session'); syncing = false; page.value = 1; keyword.value = draftKeyword.value = ''; status.value = draftStatus.value = 1; void load(1); }
function storage(event: StorageEvent) { if (event.key === null || event.key === 'admin_token' || event.key === 'admin_session') syncSession(); }
function resize() { compact.value = window.innerWidth < 650; }
watch(identity, () => { if (alive && !syncing) { invalidate(); void load(1); } }, { flush: 'sync' });
watch(productsVisible, value => { if (!value) { pickerGeneration++; cancel('products'); productsLoading.value = false; } }, { flush: 'sync' });
watch(editorVisible, value => { if (!value) { editorGeneration++; ['detail', 'options', 'history'].forEach(cancel); closeProducts(); } }, { flush: 'sync' });
onMounted(() => { alive = true; window.addEventListener('resize', resize); window.addEventListener('storage', storage); window.addEventListener('admin-session-changed', syncSession); window.addEventListener('admin-auth-expired', syncSession); syncSession(); });
onBeforeUnmount(() => { alive = false; invalidate(); window.removeEventListener('resize', resize); window.removeEventListener('storage', storage); window.removeEventListener('admin-session-changed', syncSession); window.removeEventListener('admin-auth-expired', syncSession); });
</script>
<style scoped>
.coupon-templates{min-width:0}.heading,.actions,.filters,.selected{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.heading{justify-content:space-between;margin-bottom:16px}.heading h2{margin:0;font-size:20px}.hint{color:#707783;font-size:12px;line-height:1.7;overflow-wrap:anywhere}.filters{margin:14px 0;align-items:end}.filters label{display:grid;gap:6px;flex:1 1 180px;font-size:13px}.filters :deep(.el-input){min-width:0;flex:1 1 170px}.filters :deep(.el-select){width:100%}.table-scroll{max-width:100%;overflow-x:auto}.pager{justify-content:flex-end;margin:18px 0;flex-wrap:wrap}.actions :deep(.el-button + .el-button){margin-left:0}.selected{margin:12px 0}.selected :deep(.el-tag){max-width:100%;white-space:normal;height:auto;min-height:24px;overflow-wrap:anywhere}.notice{margin:12px 0;overflow-wrap:anywhere}.notice pre{white-space:pre-wrap;overflow-wrap:anywhere}.snapshot{display:grid;grid-template-columns:140px minmax(0,1fr);gap:12px;line-height:1.6}.snapshot dd{margin:0;overflow-wrap:anywhere}.snapshot ul{padding-left:20px}.dates{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.dates input{min-width:0;width:100%;box-sizing:border-box;border:1px solid #dcdfe6;border-radius:4px;padding:7px;font:inherit}.inset{margin-left:125px}:deep(.el-form-item__content){min-width:0}:deep(.el-select),:deep(.el-cascader){max-width:100%}
@media(max-width:650px){.filters{display:grid;grid-template-columns:minmax(0,1fr)}.dates{grid-template-columns:minmax(0,1fr)}.snapshot{grid-template-columns:100px minmax(0,1fr)}.inset{margin-left:0}.pager{justify-content:center}:deep(.el-form-item__label){width:110px!important}}
</style>
