<template>
  <CustomerWorkShell title="订单发货" :manager="manager" :operations="operations" active="orders">
    <view v-show="!!operations.bootstrap.value">
      <view class="cw-card"><text class="cw-subtitle">{{ operations.bootstrap.value?.data.order.order_id }}</text><text class="cw-scope">订单管理身份 · {{ operations.bootstrap.value?.data.order.store_id?'门店履约':operations.bootstrap.value?.data.order.supplier_id?'供应商履约':'平台履约' }}</text><text>{{ operations.bootstrap.value?.data.order.real_name }} · {{ operations.bootstrap.value?.data.order.user_phone }}</text><text class="cw-scope">{{ operations.bootstrap.value?.data.order.user_address }}</text><text v-if="operations.bootstrap.value?.data.order.order_id!==orderNo" class="cw-scope">原订单 {{ orderNo }} 的待发货子单</text></view>
      <view class="cw-card"><text class="cw-subtitle">发货方式</text><view class="cw-tabs"><button v-for="option in modes" :key="option.key" :class="{active:mode===option.key}" :disabled="operations.busy.value || !option.available" @tap="chooseMode(option.key)">{{ option.title }}</button></view><text v-for="option in modes.filter(item=>!item.available)" :key="option.key" class="cw-scope">{{ option.title }}：{{ option.reason }}</text>
        <view v-show="mode==='express'" class="cw-catalog-controls">
          <view class="cw-tabs"><button :class="{active:expressType===1}" :disabled="operations.busy.value" @tap="chooseExpress(1)">手工快递</button><button :class="{active:expressType===2}" :disabled="operations.busy.value || !operations.bootstrap.value?.data.actions.electronic_waybill.available" @tap="chooseExpress(2)">电子面单</button></view>
          <view class="cw-form-field"><text>快递公司</text><picker :disabled="operations.busy.value || !carriers.length" :range="carriers" range-key="name" :value="Math.max(0,carrierIndex)" @change="chooseCarrier"><view>{{ carriers[carrierIndex]?.name || '请选择可用快递公司' }} ⌄</view></picker><text v-if="!carriers.length" class="cw-scope">当前没有可用快递公司</text></view>
          <view v-show="expressType===1"><view class="cw-form-field"><text>真实快递单号</text><input v-model="tracking" maxlength="64" :disabled="operations.busy.value" placeholder="填写本次实际物流单号" @confirm="submit" /></view><text class="cw-scope">顺丰可填写单号与收件人或寄件人手机号后四位，例如 SF000000000000:3941。</text><button v-if="scannerAvailable" :disabled="operations.busy.value || scanning" @tap="scan">{{ scanning?'扫描中…':'扫描快递条码' }}</button></view>
          <view v-show="expressType===2"><view class="cw-form-field"><text>寄件人姓名</text><input v-model="senderName" maxlength="128" :disabled="operations.busy.value" placeholder="实际寄件人姓名" /></view><view class="cw-form-field"><text>寄件人电话</text><input v-model="senderPhone" maxlength="32" :disabled="operations.busy.value" placeholder="实际寄件人电话" /></view><view class="cw-form-field"><text>寄件人地址</text><textarea v-model="senderAddress" :maxlength="255" :disabled="operations.busy.value" :adjust-position="true" placeholder="实际寄件人地址" /></view><view class="cw-form-field"><text>电子面单模板</text><picker :disabled="operations.busy.value || templateLoading || !templates.length" :range="templates" range-key="title" :value="Math.max(0,templateIndex)" @change="chooseTemplate"><view>{{ templateLoading?'读取当前快递模板…':templates[templateIndex]?.title || '请选择当前快递的模板' }} ⌄</view></picker><button v-if="templates[templateIndex]?.pic" :disabled="operations.busy.value" @tap="previewTemplate">预览面单模板</button><text v-if="!templateLoading && !templates.length" class="cw-scope">当前快递尚无可用电子面单模板</text></view><text class="cw-scope">提交后先创建渠道任务，只有查询到实际面单与发货凭据后才确认发货。</text></view>
        </view>
        <view v-show="mode==='courier'"><view class="cw-form-field"><text>平台配送员</text><picker :disabled="operations.busy.value || !couriers.length" :range="couriers" range-key="nickname" :value="Math.max(0,courierIndex)" @change="chooseCourier"><view>{{ couriers[courierIndex]?.nickname || '请选择平台配送员' }} ⌄</view></picker><text v-if="couriers[courierIndex]" class="cw-scope">{{ couriers[courierIndex]?.phone }}</text><text v-if="!couriers.length" class="cw-scope">当前没有可用平台配送员</text></view></view>
        <view v-show="mode==='city'"><view class="cw-form-field"><text>同城渠道</text><picker :disabled="operations.busy.value || !cityProviders.length" :range="cityProviderLabels" :value="Math.max(0,cityIndex)" @change="chooseCity"><view>{{ cityProviderLabels[cityIndex] || '请选择真实可用同城渠道' }} ⌄</view></picker></view><text v-for="provider in operations.bootstrap.value?.data.readiness.city.providers.filter(item=>!item.available) || []" :key="provider.station_type" class="cw-scope">{{ provider.provider==='dada'?'达达':'UU' }}：{{ provider.reasons.join('；') }}</text><text class="cw-scope">发货站点：{{ operations.bootstrap.value?.data.readiness.city.station?.name || '尚无可用发货站点' }}</text><view class="cw-form-field"><text>商品重量（千克）</text><input v-model="cargoWeight" type="digit" maxlength="12" :disabled="operations.busy.value" placeholder="填写本次商品实际重量" /></view><view class="cw-form-field"><text>配送备注</text><textarea v-model="cityRemark" :maxlength="255" :disabled="operations.busy.value" :adjust-position="true" placeholder="本次配送说明" /></view><text class="cw-scope">渠道受理后继续查询原任务。受理和发货记录均不代表已经送达。</text></view>
        <view v-show="mode==='virtual'" class="cw-form-field"><text>实际虚拟交付内容</text><textarea v-model="virtualContent" :maxlength="500" :disabled="operations.busy.value" :adjust-position="true" placeholder="填写实际交付给客户的内容" /></view>
      </view>
      <view class="cw-card"><text class="cw-subtitle">本次发货商品</text><view class="cw-tabs"><button :class="{active:!split}" :disabled="operations.busy.value" @tap="split=false">整单发货</button><button :class="{active:split}" :disabled="operations.busy.value || mode==='virtual' || !operations.bootstrap.value?.data.actions.split_delivery.available" @tap="split=true">选择商品拆单发货</button></view>
        <view v-for="cart in operations.bootstrap.value?.data.carts || []" :key="cart.cart_id" class="cw-cart"><view class="cw-stack cw-grow"><text>{{ cart.store_name }}</text><text class="cw-muted">{{ cart.sku }} · 剩余可发 {{ cart.surplus_num }} 件 · ¥{{ cart.price }}</text><view v-if="split" class="cw-quantity"><button :disabled="operations.busy.value" @tap="toggle(cart)">{{ quantities[cart.cart_id]?'已选':'选择' }}</button><button :disabled="operations.busy.value || !quantities[cart.cart_id] || (quantities[cart.cart_id] || 0)<=1" @tap="quantity(cart,-1)">−</button><text>{{ quantities[cart.cart_id] || 0 }}</text><button :disabled="operations.busy.value || !quantities[cart.cart_id] || (quantities[cart.cart_id] || 0)>=cart.surplus_num" @tap="quantity(cart,1)">＋</button></view></view></view>
        <text v-if="error" class="cw-error">{{ error }}</text><text v-if="hasPending" class="cw-scope">此订单仍有原操作待核对，请先使用上方原请求查询。</text><button class="cw-full" :disabled="operations.busy.value || hasPending || !canSubmit" @tap="submit">{{ operations.busy.value?'核对原请求中…':'核对并提交本次发货' }}</button>
      </view>
      <view v-for="job in operations.bootstrap.value?.data.jobs || []" :key="job.id" class="cw-card" data-customer-work="waybill-job"><text class="cw-subtitle">电子面单任务 {{ job.id }}</text><text>{{ waybillStatus(job.status) }}</text><text class="cw-scope">{{ job.carrier_name }} · {{ job.fulfillment_mode==='split'?'拆单':'整单' }} · {{ job.order_no }}</text><text v-if="job.tracking_number" class="cw-scope">实际单号 {{ job.tracking_number }}</text><text v-if="job.last_error" class="cw-scope">{{ job.last_error }}</text>
        <view v-if="['UNKNOWN','DEAD'].includes(job.status)" class="cw-recovery"><text>核对渠道事实后选择恢复动作。恢复动作使用新的决定编号，原签发请求保持原编号。</text><view class="cw-form-field"><text>恢复理由</text><textarea v-model="jobForm(job.id).reason" :maxlength="500" :disabled="operations.busy.value" :adjust-position="true" placeholder="填写本次核对事实与理由" /></view><view v-if="job.status==='UNKNOWN'" class="cw-form-field"><text>渠道确认已签发的真实单号</text><input v-model="jobForm(job.id).tracking" maxlength="64" :disabled="operations.busy.value" placeholder="仅用于人工确认已签发面单" /><text>面单链接（可选）</text><input v-model="jobForm(job.id).label" maxlength="255" :disabled="operations.busy.value" placeholder="渠道返回的公开面单链接" /><text>渠道引用编号（可选）</text><input v-model="jobForm(job.id).reference" maxlength="255" :disabled="operations.busy.value" placeholder="实际渠道引用编号" /></view><view class="cw-controls"><button v-if="job.status==='UNKNOWN' && job.tracking_number" :disabled="operations.busy.value" @tap="recover(job,'APPLY_EXISTING')">应用已存面单</button><button v-if="job.status==='UNKNOWN'" :disabled="operations.busy.value" @tap="recover(job,'CONFIRM_ISSUED')">确认渠道已签发</button><button v-if="!job.tracking_number && job.replay_count<20" :disabled="operations.busy.value" @tap="recover(job,'CONFIRM_RETRY')">核对并允许重试</button><button :disabled="operations.busy.value" @tap="recover(job,'CLOSE_NO_RETRY')">明确关闭且不重试</button></view></view>
      </view>
      <view v-if="operations.bootstrap.value?.data.readiness.city.job" class="cw-card" data-customer-work="city-job"><text class="cw-subtitle">原同城配送任务</text><text>{{ cityStatus(operations.bootstrap.value.data.readiness.city.job.status) }}</text><text class="cw-scope">{{ operations.bootstrap.value.data.readiness.city.job.provider }} · 原任务 {{ operations.bootstrap.value.data.readiness.city.job.job_id }}</text><text v-if="operations.bootstrap.value.data.readiness.city.job.last_error_code" class="cw-scope">{{ operations.bootstrap.value.data.readiness.city.job.last_error_code }}</text><text class="cw-scope">此任务禁止另起编号重复派单。请查询原请求结果，刷新可读取当前渠道状态。</text></view>
    </view>
  </CustomerWorkShell>
</template>
<script setup lang="ts">
import { computed,ref } from 'vue';import CustomerWorkShell from '@/components/customerWork/CustomerWorkShell.vue';
import { useCustomerWork } from '@/composables/useCustomerWork';import { useCustomerWorkOperations } from '@/composables/useCustomerWorkOperations';
import { isCustomerWorkCarriers,isCustomerWorkCouriers,isCustomerWorkDefaults,isCustomerWorkTemplates,customerWorkText } from '@/utils/customerWorkFulfillment';
import { customerWorkImage } from '@/utils/customerWork';
import { customerWorkWechatScan,customerWorkWechatScannerAvailable } from '@/utils/customerWorkWechatScan';
import type { CustomerWorkCarrier,CustomerWorkCourier,CustomerWorkWaybillTemplate,CustomerWorkFulfillmentCart,CustomerWorkWaybillJob,CustomerWorkOperationKind } from '@/types/customerWorkFulfillment';
type Mode='express'|'courier'|'city'|'virtual';const orderNo=ref(''),mode=ref<Mode>('express'),expressType=ref(1),carriers=ref<CustomerWorkCarrier[]>([]),couriers=ref<CustomerWorkCourier[]>([]),templates=ref<CustomerWorkWaybillTemplate[]>([]),carrierIndex=ref(-1),courierIndex=ref(-1),templateIndex=ref(-1),cityIndex=ref(-1),tracking=ref(''),senderName=ref(''),senderPhone=ref(''),senderAddress=ref(''),virtualContent=ref(''),cargoWeight=ref(''),cityRemark=ref(''),split=ref(false),quantities=ref<Record<string,number>>({}),templateLoading=ref(false),scanning=ref(false),error=ref('');
const jobForms=ref<Record<number,{reason:string;tracking:string;label:string;reference:string}>>({});let templateEpoch=0,scanEpoch=0;
const scannerAvailable=ref(customerWorkWechatScannerAvailable());
// #ifndef H5
scannerAvailable.value=typeof uni.scanCode==='function';
// #endif
function clear(){templateEpoch++;scanEpoch++;carriers.value=[];couriers.value=[];templates.value=[];carrierIndex.value=-1;courierIndex.value=-1;templateIndex.value=-1;cityIndex.value=-1;mode.value='express';expressType.value=1;tracking.value='';senderName.value='';senderPhone.value='';senderAddress.value='';virtualContent.value='';cargoWeight.value='';cityRemark.value='';split.value=false;quantities.value={};templateLoading.value=false;scanning.value=false;error.value='';jobForms.value={};}
const manager=useCustomerWork({page:'delivery',query(query){orderNo.value=query.orderId!;},clear,async load(controller){const valid=controller.fence();await operations.load(orderNo.value);if(!valid())return;const authority=operations.bootstrap.value;if(!authority)return;
  const [express,staff,config]=await Promise.all([operations.read('/mobile/work/fulfillment/carriers',isCustomerWorkCarriers),operations.read('/mobile/work/fulfillment/couriers',isCustomerWorkCouriers),operations.read('/mobile/work/fulfillment/defaults',(data):data is {defaults:import('@/types/customerWorkFulfillment').CustomerWorkFulfillmentDefaults}=>!!data&&typeof data==='object'&&isCustomerWorkDefaults((data as {defaults?:unknown}).defaults))]);if(!valid()||operations.bootstrap.value!==authority)return;
  carriers.value=express.data.list;couriers.value=staff.data.list;const defaults=config.data.defaults;senderName.value=defaults.to_name;senderPhone.value=defaults.to_tel;senderAddress.value=defaults.to_add;carrierIndex.value=carriers.value.findIndex(row=>String(row.id)===defaults.config_export_id);mode.value=authority.data.order.product_type===3?'virtual':'express';
}}),operations=useCustomerWorkOperations(manager);
const modes=computed(()=>{const data=operations.bootstrap.value?.data;return [{key:'express' as Mode,title:'快递发货',available:!!data&&(data.actions.manual_delivery.available||data.actions.electronic_waybill.available)&&data.order.product_type===0,reason:data?.actions.manual_delivery.reason||data?.actions.electronic_waybill.reason||'当前商品不使用快递'},{key:'courier' as Mode,title:'平台配送员',available:!!data&&data.actions.manual_delivery.available&&data.order.product_type===0,reason:data?.actions.manual_delivery.reason||'当前订单不可使用平台配送员'},{key:'city' as Mode,title:'第三方同城',available:!!data&&data.actions.city_delivery.available&&!!data.readiness.city.station&&data.readiness.city.providers.some(row=>row.available),reason:data?.actions.city_delivery.reason||'当前订单暂无可用同城渠道'},{key:'virtual' as Mode,title:'虚拟交付',available:!!data&&data.actions.manual_delivery.available&&data.order.product_type===3,reason:data?.actions.manual_delivery.reason||'仅手工虚拟商品可以交付'}];});
const cityProviders=computed(()=>operations.bootstrap.value?.data.readiness.city.providers.filter(row=>row.available)||[]),cityProviderLabels=computed(()=>cityProviders.value.map(row=>row.provider==='dada'?'达达同城':'UU同城'));
const hasPending=computed(()=>operations.pending.value.some(row=>row.root_order_id===operations.bootstrap.value?.data.order.root_order_id));
const canSubmit=computed(()=>{const data=operations.bootstrap.value?.data;if(!data?.readiness.operations.ready)return false;const action=mode.value==='city'?data.actions.city_delivery:mode.value==='express'&&expressType.value===2?data.actions.electronic_waybill:data.actions.manual_delivery;return action.available&&(!split.value||data.actions.split_delivery.available)&&modes.value.some(row=>row.key===mode.value&&row.available);});
function selected(event:{detail:{value:string|number}},length:number){const index=Number(event.detail.value);return Number.isInteger(index)&&index>=0&&index<length?index:-1;}
function chooseMode(value:Mode){if(operations.busy.value||!modes.value.some(row=>row.key===value&&row.available))return;scanEpoch++;scanning.value=false;mode.value=value;if(value==='virtual')split.value=false;error.value='';}
function chooseExpress(value:number){if(operations.busy.value||![1,2].includes(value)||value===2&&!operations.bootstrap.value?.data.actions.electronic_waybill.available)return;scanEpoch++;scanning.value=false;expressType.value=value;templateEpoch++;templates.value=[];templateIndex.value=-1;templateLoading.value=false;if(value===2)void loadTemplates();}
function chooseCarrier(event:{detail:{value:string|number}}){if(operations.busy.value)return;carrierIndex.value=selected(event,carriers.value.length);templateEpoch++;templates.value=[];templateIndex.value=-1;templateLoading.value=false;if(expressType.value===2)void loadTemplates();}
function chooseCourier(event:{detail:{value:string|number}}){if(!operations.busy.value)courierIndex.value=selected(event,couriers.value.length);}function chooseTemplate(event:{detail:{value:string|number}}){if(!operations.busy.value)templateIndex.value=selected(event,templates.value.length);}function chooseCity(event:{detail:{value:string|number}}){if(!operations.busy.value)cityIndex.value=selected(event,cityProviders.value.length);}
async function loadTemplates(){const carrier=carriers.value[carrierIndex.value],authority=operations.bootstrap.value;if(!carrier||!authority||!authority.data.readiness.electronic.ready)return;const version=++templateEpoch,valid=manager.fence();templateLoading.value=true;try{const response=await operations.read('/mobile/work/fulfillment/templates',isCustomerWorkTemplates,{carrier_id:carrier.id});if(!valid()||version!==templateEpoch||carrier.id!==carriers.value[carrierIndex.value]?.id||expressType.value!==2)return;if(response.data.carrier_id!==carrier.id)throw Error('快递公司模板响应不匹配');templates.value=response.data.list;templateIndex.value=templates.value.findIndex(row=>row.temp_id===authority.data.defaults.express_temp_id);}catch(failure){if(valid()&&version===templateEpoch){const code=failure as {status?:unknown;httpStatus?:unknown};if(code.status===403||code.httpStatus===403){manager.invalidate(failure);return;}error.value=failure instanceof Error?failure.message:'当前快递模板读取失败';templates.value=[];templateIndex.value=-1;}}finally{if(valid()&&version===templateEpoch)templateLoading.value=false;}}
function previewTemplate(){const template=templates.value[templateIndex.value];if(operations.current()&&template?.pic&&customerWorkImage(template.pic))uni.previewImage({current:template.pic,urls:[template.pic]});}
function toggle(cart:CustomerWorkFulfillmentCart){if(!operations.busy.value)quantities.value[cart.cart_id]=quantities.value[cart.cart_id]?0:cart.surplus_num;}function quantity(cart:CustomerWorkFulfillmentCart,delta:number){if(!operations.busy.value&&quantities.value[cart.cart_id])quantities.value[cart.cart_id]=Math.max(1,Math.min(cart.surplus_num,quantities.value[cart.cart_id]!+delta));}
async function scan(){if(scanning.value||operations.busy.value||mode.value!=='express'||expressType.value!==1)return;const valid=manager.fence(),version=++scanEpoch,same=()=>valid()&&version===scanEpoch&&mode.value==='express'&&expressType.value===1;scanning.value=true;
  try{let value:string|null=null;
    // #ifdef H5
    value=await customerWorkWechatScan(same);
    // #endif
    // #ifndef H5
    value=await new Promise<string|null>((resolve,reject)=>uni.scanCode({scanType:['barCode'],success:result=>resolve(result.result),fail:failure=>/cancel/iu.test(failure.errMsg||'')?resolve(null):reject(Error('条码扫描未完成，可手动输入'))}));
    // #endif
    if(!same()||value===null)return;value=value.trim();if(!value||!customerWorkText(value,64)||/[\r\n]/u.test(value))throw Error('条码不是有效的快递单号');tracking.value=value;
  }catch(failure){if(same())error.value=failure instanceof Error?failure.message:'条码扫描未完成';}finally{if(same())scanning.value=false;}
}
async function submit(){if(!canSubmit.value||operations.busy.value||hasPending.value)return;error.value='';try{let payload:Record<string,unknown>,kind:CustomerWorkOperationKind;
  if(mode.value==='express'){const carrier=carriers.value[carrierIndex.value];if(!carrier)throw Error('请选择当前快递公司');if(expressType.value===1){const id=tracking.value.trim();if(!id||!customerWorkText(id,64)||/[\r\n]/u.test(id))throw Error('请填写真实有效的快递单号');payload={type:1,express_record_type:1,carrier_id:carrier.id,delivery_id:id};kind=split.value?'split_delivery':'manual_delivery';}
    else{const template=templates.value[templateIndex.value],name=senderName.value.trim(),phone=senderPhone.value.trim(),address=senderAddress.value.trim();if(!template||!name||!phone||!address||!customerWorkText(name,128)||!customerWorkText(phone,32)||phone.length<5||!customerWorkText(address,255))throw Error('请选择当前快递模板并填写完整实际寄件人信息');payload={type:1,express_record_type:2,carrier_id:carrier.id,express_temp_id:template.temp_id,to_name:name,to_tel:phone,to_addr:address};kind=split.value?'electronic_split_waybill':'electronic_waybill';}}
  else if(mode.value==='courier'){const courier=couriers.value[courierIndex.value];if(!courier)throw Error('请选择当前平台配送员');payload={type:2,delivery_type:1,delivery_uid:courier.uid};kind=split.value?'split_delivery':'manual_delivery';}
  else if(mode.value==='city'){const provider=cityProviders.value[cityIndex.value],weight=cargoWeight.value.trim(),remark=cityRemark.value.trim();if(!provider)throw Error('请选择当前真实可用同城渠道');if(!/^(?:[1-9]\d{0,2}|0)(?:\.\d{1,2})?$/u.test(weight)||Number(weight)<=0||Number(weight)>100)throw Error('请填写真实有效的商品重量');if(!customerWorkText(remark,255)||/[\r\n\t]/u.test(remark))throw Error('配送备注须为不超过 255 字的单行内容');payload={type:2,delivery_type:2,station_type:provider.station_type,cargo_weight:weight,delivery_remark:remark};kind=split.value?'city_split_delivery':'city_delivery';}
  else{const content=virtualContent.value.trim();if(!content||!customerWorkText(content,500)||split.value)throw Error('请填写不超过 500 字的实际虚拟交付内容，虚拟交付不能拆单');payload={type:3,fictitious_content:content};kind='manual_delivery';}
  if(split.value){const carts=operations.bootstrap.value?.data.carts||[],cart_ids=carts.filter(cart=>(quantities.value[cart.cart_id]||0)>0).map(cart=>{const amount=quantities.value[cart.cart_id]!;if(!Number.isSafeInteger(amount)||amount<1||amount>cart.surplus_num)throw Error('发货商品数量已变化');return {cart_id:cart.cart_id,cart_num:amount};});if(!cart_ids.length||cart_ids.length>200)throw Error('请选择 1 至 200 项本次发货商品与数量');payload={...payload,cart_ids};}
  const receipt=await operations.submit(kind,payload,'核对本次发货');if(!operations.current()||!receipt)return;if(receipt.outcome==='delivery-recorded'){uni.showToast({title:'发货已记录',icon:'success'});await manager.load();}else if(receipt.outcome==='provider-admitted'){await manager.load();operations.error.value='渠道任务已受理，请查询原任务，尚未确认最终履约结果。';}
 }catch(failure){if(operations.current())error.value=failure instanceof Error?failure.message:'原发货结果待核对';}}
function jobForm(id:number){return jobForms.value[id]??(jobForms.value[id]={reason:'',tracking:'',label:'',reference:''});}
async function recover(job:CustomerWorkWaybillJob,action:'APPLY_EXISTING'|'CONFIRM_ISSUED'|'CONFIRM_RETRY'|'CLOSE_NO_RETRY'){if(operations.busy.value)return;error.value='';try{const fresh=await operations.refreshJob(job.id);if(fresh.data.job.job_revision!==job.job_revision)throw Error('原任务状态已变化，请刷新后重新核对');const form=jobForm(job.id),reason=form.reason.trim();if(!reason||!customerWorkText(reason,500))throw Error('请填写本次恢复的核对理由');const payload:Record<string,unknown>={action,job_id:job.id,expected_job_revision:fresh.data.job.job_revision,reason};if(action==='CONFIRM_ISSUED'){const id=form.tracking.trim();if(!id||!customerWorkText(id,64)||/[\r\n]/u.test(id))throw Error('请填写渠道已签发的真实单号');payload.tracking_number=id;if(form.label.trim()){if(!customerWorkImage(form.label.trim()))throw Error('面单公开链接无效');payload.label_url=form.label.trim();}if(form.reference.trim()){if(!customerWorkText(form.reference.trim(),255))throw Error('渠道引用编号无效');payload.provider_reference=form.reference.trim();}}
  const kind=({APPLY_EXISTING:'waybill_apply_existing',CONFIRM_ISSUED:'waybill_confirm_issued',CONFIRM_RETRY:'waybill_confirm_retry',CLOSE_NO_RETRY:'waybill_close'} as const)[action],receipt=await operations.submit(kind,payload,'核对原面单恢复决定');if(operations.current()&&receipt?.outcome==='job-updated'){await manager.load();operations.error.value='恢复决定已记录，请查询原任务最新状态。';}
 }catch(failure){if(operations.current())error.value=failure instanceof Error?failure.message:'原面单恢复结果待核对';}}
function waybillStatus(value:string){return ({PENDING:'待签发',ENQUEUING:'准备进入签发队列',ENQUEUED:'已进入签发队列',PROCESSING:'渠道签发处理中',RETRYABLE:'等待安全重试',SENT:'面单与发货已确认',UNKNOWN:'签发结果未知',DEAD:'签发失败，待明确恢复',CLOSED:'任务已明确关闭'} as Record<string,string>)[value]||value;}
function cityStatus(value:string){return ({PENDING:'等待派单',PROCESSING:'派单处理中',ADMITTED:'渠道已受理，尚未确认送达',UNKNOWN:'派单结果未知，请查询原请求',REJECTED:'渠道已明确拒绝',REVOKED:'权限已撤销，原任务需核对',CANCELLED:'任务已取消',DELIVERED:'渠道已确认送达'} as Record<string,string>)[value]||value;}
</script>
