<template>
  <CustomerWorkShell title="全站订单查询" :manager="manager" :operations="operations" :domain-busy="financial.busy.value||financialReading" active="orders"><template #recovery><CustomerWorkFinancialRecoveryPanel :operations="financial" /></template>
    <view class="cw-card"><text class="cw-scope">普通筛选读取全站履约订单；售后筛选可包含拆单支付父单。订单详情可核对管理备注与发货，具体动作以当前订单实际资格为准。</text>
      <view class="cw-controls"><picker :range="statusLabels" :value="statusIndex" @change="chooseStatus"><view>状态：{{ statusLabels[statusIndex] }} ⌄</view></picker><picker :range="dateLabels" :value="dateIndex" @change="chooseDate"><view>日期：{{ dateLabels[dateIndex] }} ⌄</view></picker><picker :range="typeLabels" :value="typeIndex" @change="chooseType"><view>类型：{{ typeLabels[typeIndex] }} ⌄</view></picker><picker :range="payLabels" :value="payIndex" @change="choosePay"><view>支付：{{ payLabels[payIndex] }} ⌄</view></picker></view>
      <text v-if="filters.data" class="cw-scope">当前日期：{{ filters.data }}</text><view class="cw-controls"><picker :range="fieldLabels" :value="fieldIndex" @change="chooseField"><view>{{ fieldLabels[fieldIndex] }} ⌄</view></picker><input v-model="keyword" :maxlength="100" placeholder="订单号、用户或商品" @confirm="search" /><button :disabled="manager.loading.value" @tap="search">搜索</button></view><text class="cw-muted">共 {{ count }} 条</text>
    </view>
    <view v-for="order in rows" :key="order.id" class="cw-card"><view class="cw-row"><text class="cw-link" @tap="manager.go('orderDetail',{orderId:order.order_id})">{{ order.order_id }}</text><text class="cw-status">{{ order._status._title }}</text></view><text class="cw-scope">{{ order.type_name }} · {{ order.store_id ? '门店 '+order.store_id : order.supplier_id ? '供应商 '+order.supplier_id : '平台' }} · {{ order._add_time }}</text><view v-for="cart in order.cartInfo" :key="cart.id" class="cw-cart"><image v-if="cart.productInfo.image" class="cw-image" :src="cart.productInfo.image" mode="aspectFill" /><view class="cw-stack"><text>{{ cart.productInfo.store_name }}</text><text class="cw-muted">{{ cart.productInfo.attrInfo.suk }} · {{ cart.cart_num }} 件</text><text>¥{{ cart.truePrice }}</text></view></view><view class="cw-row"><text>{{ order.nickname || order.real_name }} · {{ order.user_phone }}</text><text>实付 ¥{{ order.pay_price }}</text></view><button class="cw-full" @tap="manager.go('orderDetail',{orderId:order.order_id})">查看订单</button><view class="cw-controls"><button v-for="kind in orderKinds" :key="kind" :disabled="manager.loading.value||operations.busy.value||financial.busy.value||financialReading" @tap="openFinancial(order,kind)">{{ CUSTOMER_FINANCIAL_NAMES[kind] }}</button></view></view>
    <view v-if="!rows.length" class="cw-empty">当前筛选暂无订单</view><button v-if="hasMore" class="cw-full" :disabled="paging" @tap="more">{{ paging?'读取中…':'加载更多订单' }}</button>
    <text v-if="financialMessage||financial.error.value" class="cw-scope">{{ financialMessage||financial.error.value }}</text><CustomerWorkFinancialDialog v-if="financialKind&&financial.order.value" :operations="financial" :kind="financialKind" :basis="financial.order.value.data" @close="financialKind=null" @saved="savedFinancial" />
  </CustomerWorkShell>
</template>
<script setup lang="ts">
import { useCustomerWorkOperations } from '@/composables/useCustomerWorkOperations';
import CustomerWorkFinancialRecoveryPanel from '@/components/customerWork/CustomerWorkFinancialRecoveryPanel.vue';import CustomerWorkFinancialDialog from '@/components/customerWork/CustomerWorkFinancialDialog.vue';import {useCustomerWorkFinancialOperations} from '@/composables/useCustomerWorkFinancialOperations';import {CUSTOMER_FINANCIAL_NAMES,customerFinancialNotice} from '@/utils/customerWorkFinancial';
import { computed,ref } from 'vue';import { onReachBottom } from '@dcloudio/uni-app';import CustomerWorkShell from '@/components/customerWork/CustomerWorkShell.vue';import { useCustomerWork } from '@/composables/useCustomerWork';import { parseCustomerWorkQuery,isCustomerWorkPaged,isCustomerWorkOrder,customerWorkDateRange } from '@/utils/customerWork';import type { CustomerWorkOrder } from '@/types/customerWork';
const statusLabels=['全部','待付款','待发货','待收货','待评价','已完成','退款中','已退款','退款记录','已删除','待核销','核销待评价','部分发货','核销订单','已评价或完成'],statusValues=['','0','1','2','3','4','-1','-2','-3','-4','5','6','7','8','9'];
const dateLabels=['全部时间','最近3天','本月','近3个月','近6个月'],typeLabels=['全部类型','普通','秒杀','砍价','拼团','积分','预售','虚拟','新人','其他','核销','自动发货','快递'],typeValues=['','0','1','2','3','4','5','6','7','8','105','106','107'],payLabels=['全部支付','微信','余额','线下','支付宝','积分'],fieldLabels=['综合搜索','用户ID','订单编号','收货人','联系电话','商品标题','商品数量'],fieldValues=['','uid','order_id','real_name','user_phone','title','total_num'];
const orderKinds=['change_price','confirm_offline','refund_create'] as const;
const filters=ref<Record<string,string>>({status:'',is_del:'0'}),keyword=ref(''),dateIndex=ref(0),rows=ref<CustomerWorkOrder[]>([]),count=ref(0),hasMore=ref(false),paging=ref(false),financialKind=ref<'change_price'|'confirm_offline'|null>(null),financialReading=ref(false),financialMessage=ref('');let page=1;
const statusIndex=computed(()=>Math.max(0,statusValues.indexOf(filters.value.status??''))),typeIndex=computed(()=>Math.max(0,typeValues.indexOf(filters.value.type??''))),payIndex=computed(()=>Number(filters.value.pay_type||0)),fieldIndex=computed(()=>Math.max(0,fieldValues.indexOf(filters.value.field_key??'')));
const manager=useCustomerWork({page:'orders',query(query){filters.value={status:'',is_del:'0',...query};keyword.value=query.keyword??'';},clear(){rows.value=[];count.value=0;hasMore.value=false;paging.value=false;page=1;financialKind.value=null;financialReading.value=false;financialMessage.value='';financial.clearDomain();},async load(controller){const valid=controller.fence(),query=parseCustomerWorkQuery('orders',filters.value),response=await controller.read('orders',isCustomerWorkPaged(isCustomerWorkOrder),{...query,page:1,limit:10});if(!valid())return;if(response.data.page!==1||new Set(response.data.list.map(row=>row.id)).size!==response.data.list.length)throw Error('订单分页依据不匹配');rows.value=response.data.list;count.value=response.data.count;hasMore.value=response.data.has_more;}});
const operations=useCustomerWorkOperations(manager),financial=useCustomerWorkFinancialOperations(manager);
async function openFinancial(row:CustomerWorkOrder,kind:typeof orderKinds[number]){if(manager.loading.value||operations.busy.value||financial.busy.value||financialReading.value)return;const valid=manager.fence();if(!valid()||!rows.value.some(value=>value.id===row.id&&value.order_id===row.order_id))return;financialKind.value=null;financialMessage.value='';financialReading.value=true;try{const basis=await financial.loadOrder(row.id,row.order_id);if(!valid())return;if(basis.uid!==row.uid||basis.store_id!==row.store_id||basis.supplier_id!==row.supplier_id)throw Error('订单财务实体归属不匹配');await financial.checkRelevant(basis.payment_order_id);if(!valid())return;if(!basis.actions[kind].available){financialMessage.value=customerFinancialNotice(basis.actions[kind].reason);return;}if(kind==='refund_create')manager.go('refund',{orderId:basis.order_no});else financialKind.value=kind;}catch(failure){if(valid())manager.invalidate(failure);}finally{if(valid())financialReading.value=false;}}
function savedFinancial(){financialKind.value=null;void manager.load();}
function selected(event:{detail:{value:string|number}},values:readonly string[]){const n=Number(event.detail.value);return Number.isInteger(n)&&n>=0&&n<values.length?values[n]:undefined;}
function refresh(){if(manager.loading.value)return;void manager.load();}function chooseStatus(event:{detail:{value:string|number}}){const value=selected(event,statusValues);if(value===undefined)return;filters.value.status=value;filters.value.is_del=value==='-4'?'1':'0';refresh();}function chooseType(event:{detail:{value:string|number}}){const value=selected(event,typeValues);if(value!==undefined){filters.value.type=value;refresh();}}function choosePay(event:{detail:{value:string|number}}){const value=selected(event,['','1','2','3','4','5']);if(value!==undefined){filters.value.pay_type=value;refresh();}}function chooseField(event:{detail:{value:string|number}}){const value=selected(event,fieldValues);if(value!==undefined)filters.value.field_key=value;}function chooseDate(event:{detail:{value:string|number}}){const value=selected(event,['0','1','2','3','4']);if(value===undefined)return;dateIndex.value=Number(value);filters.value.data=customerWorkDateRange(dateIndex.value);refresh();}function search(){filters.value.keyword=keyword.value.trim();refresh();}
async function more(){if(!manager.current()||!manager.context.value||manager.loading.value||paging.value||!hasMore.value)return;const valid=manager.fence(),next=page+1;paging.value=true;try{const response=await manager.read('orders',isCustomerWorkPaged(isCustomerWorkOrder),{...parseCustomerWorkQuery('orders',filters.value),page:next,limit:10});if(!valid())return;if(response.data.page!==next||response.data.count!==count.value||response.data.list.some(row=>rows.value.some(old=>old.id===row.id)))throw Error('订单列表已变化，请刷新');rows.value.push(...response.data.list);hasMore.value=response.data.has_more;page=next;}catch(failure){if(valid())manager.invalidate(failure);}finally{if(valid())paging.value=false;}}onReachBottom(()=>void more());
</script>
