<template>
  <CustomerWorkShell title="订单详情" :manager="manager" :operations="operations" :domain-busy="financial.busy.value" active="orders"><template #recovery><CustomerWorkFinancialRecoveryPanel :operations="financial" /></template><template v-if="order">
    <view class="cw-card"><view class="cw-row"><text class="cw-subtitle">{{ order.order_id }}</text><text class="cw-status">{{ order._status._title }}</text></view><text class="cw-scope">全站经营读取 · {{ order._status._msg }} · {{ order.type_name }}</text><view class="cw-row"><text>下单时间</text><text>{{ order._add_time }}</text></view><view class="cw-row"><text>支付时间</text><text>{{ order._pay_time || '尚未支付' }}</text></view><view class="cw-row"><text>支付方式</text><text>{{ order._status._payType || order.pay_type || '尚未支付' }}</text></view><view class="cw-row"><text>归属</text><text>{{ order.store_id?'门店 '+order.store_id:order.supplier_id?'供应商 '+order.supplier_id:'平台' }}</text></view></view>
    <view class="cw-card"><text class="cw-subtitle">收货与用户</text><text class="cw-scope">用户 {{ order.customer.nickname }}（{{ order.uid }}）</text><view class="cw-row"><text>{{ order.real_name }}</text><text>{{ order.user_phone }}</text></view><text>{{ order.user_address }}</text></view>
    <view class="cw-card"><text class="cw-subtitle">商品与金额</text><view v-for="cart in order.cartInfo" :key="cart.id" class="cw-cart"><image v-if="cart.productInfo.image" class="cw-image" :src="cart.productInfo.image" mode="aspectFill" /><view class="cw-stack"><text>{{ cart.productInfo.store_name }}</text><text class="cw-muted">{{ cart.productInfo.attrInfo.suk }} · {{ cart.cart_num }} 件 · {{ cart.is_gift?'赠品':'' }}</text><text>¥{{ cart.truePrice }} · 小计 ¥{{ cart.sum_true_price }}</text><text class="cw-muted">已退 {{ cart.refund_num }} 件 · 可退 {{ cart.surplus_num }} 件</text></view></view><view class="cw-row"><text>商品金额</text><text>¥{{ order.total_price }}</text></view><view class="cw-row"><text>会员优惠</text><text>¥{{ order.vip_true_price }}</text></view><view class="cw-row"><text>支付运费</text><text>¥{{ order.pay_postage }}</text></view><view class="cw-row"><text>实付</text><text class="cw-money">¥{{ order.pay_price }}</text></view></view>
    <view class="cw-card"><text class="cw-subtitle">履约物流</text><view class="cw-row"><text>{{ order.delivery_name || order.delivery_type || '尚无物流信息' }}</text><text>{{ order.delivery_id }}</text></view><button class="cw-full" @tap="manager.go('logistics',{orderId:order.order_id})">查询物流与包裹</button><view v-for="child in order.split" :key="child.id" class="cw-row cw-divider"><text class="cw-link" @tap="manager.go('orderDetail',{orderId:child.order_id})">子订单 {{ child.order_id }}</text><text>{{ child.total_num }} 件 · ¥{{ child.pay_price }}</text></view></view>
    <view v-if="manager.context.value?.data.capabilities.writeoff_read===true" class="cw-card"><text class="cw-subtitle">普通客户核销</text><text class="cw-scope">按真实物理订单与业务单号重新核对商品、次数、有效窗口及成交快照。</text><view class="cw-controls"><button :disabled="financial.busy.value||operations.busy.value" @tap="manager.go('writeoff',{orderId:order.id,orderNo:order.order_id})">核对并核销</button><button :disabled="financial.busy.value||operations.busy.value" @tap="manager.go('writeoffRecords',{orderId:order.id,orderNo:order.order_id})">实际核销记录</button></view></view>
    <view v-if="order.refund.length" class="cw-card"><text class="cw-subtitle">退款申请</text><view v-for="refund in order.refund" :key="refund.id" class="cw-row"><text class="cw-link" @tap="manager.go('refundDetail',{refundOrderId:refund.order_id})">{{ refund.order_id }}</text><text>{{ refund.refund_num }} 件 · ¥{{ refund.refund_price }}</text></view></view>
    <view class="cw-card"><text class="cw-subtitle">备注与表单</text><text class="cw-scope">用户备注：{{ order.mark || '无' }}</text><text class="cw-scope">管理备注：{{ (operations.remark.value?.data.remark_target.remark ?? order.remark) || '无' }}</text><view v-for="row in formRows" :key="row.name" class="cw-row"><text>{{ row.name }}</text><text>{{ row.value }}</text></view><text v-if="order.refund_reason_wap" class="cw-scope">历史退款：{{ order.refund_reason_wap }} · {{ order.refund_reason_wap_explain }}</text><view class="cw-images"><image v-for="(src,index) in [...order.refund_img,...order.refund_goods_img]" :key="index" :src="src" mode="aspectFit" /></view></view>
    <view class="cw-card" data-financial-actions="order"><text class="cw-subtitle">订单财务</text><template v-if="financial.order.value"><text class="cw-scope">实际付款订单 {{ financial.order.value.data.payment_order_no }} · 当前金额 ¥{{ financial.order.value.data.pay_price }}</text><view class="cw-controls"><button v-for="kind in orderKinds" :key="kind" :disabled="financial.busy.value||operations.busy.value||!financial.order.value.data.actions[kind].available" @tap="openFinancial(kind)">{{ CUSTOMER_FINANCIAL_NAMES[kind] }}</button></view><text v-for="kind in orderKinds" :key="kind+'reason'" class="cw-scope">{{ CUSTOMER_FINANCIAL_NAMES[kind] }}：{{ financial.order.value.data.actions[kind].available?'可核对并提交':customerFinancialNotice(financial.order.value.data.actions[kind].reason) }}</text></template><text v-if="financial.error.value" class="cw-error">{{ financial.error.value }}</text></view>
    <view v-if="operations.remark.value || operations.bootstrap.value" class="cw-card"><text class="cw-subtitle">订单处理</text><view class="cw-controls"><button :disabled="operations.busy.value || !operations.remark.value?.data.remark_target.available" @tap="editingRemark=true">修改管理备注</button><button :disabled="operations.busy.value || !deliveryAvailable" @tap="manager.go('delivery',{orderId:order.order_id})">核对并发货</button></view><text v-if="operations.bootstrap.value && operations.bootstrap.value.data.order.order_id!==order.order_id" class="cw-scope">发货将核对原订单的实际待履约子单 {{ operations.bootstrap.value.data.order.order_id }}。</text><text v-if="!deliveryAvailable" class="cw-scope">{{ operations.bootstrap.value?.data.actions.manual_delivery.reason || operations.bootstrap.value?.data.actions.electronic_waybill.reason || operations.bootstrap.value?.data.actions.city_delivery.reason || operations.error.value }}</text><text v-if="operations.remark.value && !operations.remark.value.data.remark_target.available" class="cw-scope">{{ operations.remark.value.data.remark_target.reason }}</text></view>
    <CustomerWorkOperationPanel v-if="editingRemark && operations.remark.value" :operations="operations" @close="editingRemark=false" @saved="savedRemark" />
    <CustomerWorkFinancialDialog v-if="financialKind&&financial.order.value" :operations="financial" :kind="financialKind" :basis="financial.order.value.data" @close="financialKind=null" @saved="savedFinancial" />
  </template></CustomerWorkShell>
</template>
<script setup lang="ts">
import { computed,ref } from 'vue';import CustomerWorkShell from '@/components/customerWork/CustomerWorkShell.vue';import { useCustomerWork } from '@/composables/useCustomerWork';import { isCustomerWorkOrderDetail,customerWorkFormRows } from '@/utils/customerWork';import type { CustomerWorkOrderDetail } from '@/types/customerWork';
import CustomerWorkOperationPanel from '@/components/customerWork/CustomerWorkOperationPanel.vue';import { useCustomerWorkOperations } from '@/composables/useCustomerWorkOperations';
import CustomerWorkFinancialRecoveryPanel from '@/components/customerWork/CustomerWorkFinancialRecoveryPanel.vue';import CustomerWorkFinancialDialog from '@/components/customerWork/CustomerWorkFinancialDialog.vue';import {useCustomerWorkFinancialOperations} from '@/composables/useCustomerWorkFinancialOperations';import {CUSTOMER_FINANCIAL_NAMES,customerFinancialNotice} from '@/utils/customerWorkFinancial';
const orderKinds=['change_price','confirm_offline','refund_create'] as const;
const order=ref<CustomerWorkOrderDetail|null>(null),orderId=ref(''),editingRemark=ref(false),financialKind=ref<'change_price'|'confirm_offline'|null>(null),formRows=computed(()=>customerWorkFormRows(order.value?.custom_form));
const manager=useCustomerWork({page:'orderDetail',query(query){orderId.value=query.orderId!;},clear(){order.value=null;editingRemark.value=false;financialKind.value=null;financial.clearDomain();},async load(controller){const valid=controller.fence(),id=orderId.value,response=await controller.read(`orders/${encodeURIComponent(id)}`,isCustomerWorkOrderDetail);if(!valid())return;if(response.data.order_id!==id)throw Error('订单业务编号不匹配');order.value=response.data;const actual=await financial.loadOrder(response.data.id,id);if(!valid())return;if(actual.uid!==response.data.uid||actual.store_id!==response.data.store_id||actual.supplier_id!==response.data.supplier_id)throw Error('订单财务实体归属不匹配');await financial.checkRelevant(actual.payment_order_id);if(!valid())return;await operations.loadRemark(id);if(!valid())return;try{await operations.load(id);}catch(failure){if(!valid())return;const status=(failure as {status?:unknown})?.status;if([400,404,422,503].includes(Number(status)))operations.error.value=failure instanceof Error?failure.message:'当前订单暂无可用发货目标';else throw failure;}}}),operations=useCustomerWorkOperations(manager),financial=useCustomerWorkFinancialOperations(manager);
const deliveryAvailable=computed(()=>{const actions=operations.bootstrap.value?.data.actions;return !!actions&&(actions.manual_delivery.available||actions.electronic_waybill.available||actions.city_delivery.available)||!!operations.bootstrap.value?.data.jobs?.some(job=>['UNKNOWN','DEAD'].includes(job.status));});
function savedRemark(){editingRemark.value=false;void manager.load();}
function openFinancial(kind:typeof orderKinds[number]){if(!financial.order.value?.data.actions[kind].available||financial.busy.value||operations.busy.value)return;editingRemark.value=false;if(kind==='refund_create'){manager.go('refund',{orderId:financial.order.value.data.order_no});return;}financialKind.value=kind;}
function savedFinancial(){financialKind.value=null;void manager.load();}
</script>
