<template>
 <CustomerWorkShell title="商品规格管理" :manager="manager" active="products">
  <template #recovery><CustomerWorkProductRecoveryPanel :operations="operations" /></template>
  <template v-if="data"><view class="cw-card"><text class="cw-subtitle">{{ data.product.store_name }}</text><text class="cw-scope">#{{ data.product.id }} · {{ data.product.plate_name }} · {{ data.skus.length }} 个有效基础规格</text><text>合计库存 {{ data.product.stock }} · 销量 {{ data.product.sales }}</text><text v-if="data.product.sku_policy" class="cw-scope">{{ data.product.sku_policy }}</text><text v-if="!data.readiness.writes" class="cw-error">{{ data.readiness.reason || '当前商品写入暂不可用' }}</text></view>
   <view class="cw-card"><view class="cw-controls"><button :disabled="operations.busy.value||!data.product.actions.skus" @tap="selectAll">{{ selected.length===Math.min(data.skus.length,500)&&selected.length?'取消全选':data.skus.length>500?'选择前500项':'全选规格' }}</button><button :disabled="operations.busy.value||!selected.length||!data.product.actions.skus" @tap="bulkVisible=true">批量修改选中规格</button><button :disabled="operations.busy.value||!data.product.actions.skus" @tap="save">保存价格与库存</button></view><text class="cw-muted">选中 {{ selected.length }} 项 · 单次最多修改500项规格，请分批修改后保存。批量修改先更新草稿，再点击保存提交。</text><text v-if="message||operations.error.value" class="cw-error" role="alert">{{ message || operations.error.value }}</text></view>
   <view v-for="sku in data.skus" :key="sku.id" class="cw-card" :data-product-sku-row="sku.id"><view class="cw-row"><button role="checkbox" :aria-checked="selected.includes(sku.id)" :disabled="operations.busy.value||!data.product.actions.skus" @tap="toggle(sku.id)">{{ selected.includes(sku.id)?'已选':'选择' }}</button><text class="cw-subtitle">{{ sku.suk || '默认规格' }}</text></view><text class="cw-scope">规格 #{{ sku.id }} · 条码 {{ sku.bar_code || '未设置' }}</text>
    <label v-for="field in fields" :key="field.key" class="cw-form-field"><text>{{ field.name }}</text><input v-if="data.product.actions.skus&&drafts[sku.unique]" v-model="drafts[sku.unique][field.key]" :type="field.key==='stock'?'number':'digit'" :aria-label="`${sku.suk||'默认规格'} ${field.name}`" :disabled="operations.busy.value||field.key==='stock'&&!sku.stock_editable" /><text v-else>{{ sku[field.key] }}</text></label><text v-if="!sku.stock_editable" class="cw-muted">此规格库存由专用功能维护。</text>
   </view><view v-if="!data.skus.length" class="cw-empty">暂无有效基础规格，请核对商品真实规格配置。</view>
  </template>
  <CustomerWorkProductEditor :visible="bulkVisible" bulk :stock-editable="selectedRows.length>0&&selectedRows.every(row=>row.stock_editable)" :busy="operations.busy.value" @close="bulkVisible=false" @apply="applyBulk" />
 </CustomerWorkShell>
</template>
<script setup lang="ts">
import { computed,ref } from 'vue';
import CustomerWorkShell from '@/components/customerWork/CustomerWorkShell.vue';
import CustomerWorkProductRecoveryPanel from '@/components/customerWork/CustomerWorkProductRecoveryPanel.vue';
import CustomerWorkProductEditor from '@/components/customerWork/CustomerWorkProductEditor.vue';
import { useCustomerWork } from '@/composables/useCustomerWork';
import { useCustomerWorkProductOperations } from '@/composables/useCustomerWorkProductOperations';
import { isCustomerWorkProductSkus,customerWorkProductSkuUpdates,customerWorkCanonicalJson } from '@/utils/customerWorkProductsContract';
import type { CustomerWorkProductSkus } from '@/types/customerWorkProducts';
const fields:{key:'price'|'cost'|'ot_price'|'stock';name:string}[]=[{key:'price',name:'售价'},{key:'cost',name:'成本价'},{key:'ot_price',name:'划线价'},{key:'stock',name:'库存'}];
const data=ref<CustomerWorkProductSkus|null>(null),drafts=ref<Record<string,{price:string;cost:string;ot_price:string;stock:string}>>({}),selected=ref<number[]>([]),bulkVisible=ref(false),message=ref('');let productId=0;
const manager=useCustomerWork({page:'productSkus',query(query){productId=Number(query.productId);},clear(){data.value=null;drafts.value={};selected.value=[];bulkVisible.value=false;message.value='';},async load(controller){const valid=controller.fence(),response=await operations.read(`/mobile/work/products/${productId}/skus`,isCustomerWorkProductSkus);if(!valid())return;if(response.data.product.id!==productId)throw Error('规格响应不属于当前商品');data.value=response.data;drafts.value=Object.fromEntries(response.data.skus.map(sku=>[sku.unique,{price:sku.price,cost:sku.cost,ot_price:sku.ot_price,stock:String(sku.stock)}]));}});
const operations=useCustomerWorkProductOperations(manager),selectedRows=computed(()=>data.value?.skus.filter(row=>selected.value.includes(row.id))??[]);
function toggle(id:number){if(operations.busy.value||!data.value?.product.actions.skus||!data.value.skus.some(row=>row.id===id))return;if(!selected.value.includes(id)&&selected.value.length>=500){message.value='单次最多选择500项规格，请分批修改后保存。';return;}selected.value=selected.value.includes(id)?selected.value.filter(value=>value!==id):[...selected.value,id];}
function selectAll(){if(!data.value||operations.busy.value||!data.value.product.actions.skus)return;const count=Math.min(data.value.skus.length,500);selected.value=selected.value.length===count?[]:data.value.skus.slice(0,count).map(row=>row.id);}
function applyBulk(values:{price:string;cost:string;ot_price:string;stock:string}){if(!data.value||operations.busy.value||!selectedRows.value.length)return;for(const sku of selectedRows.value){const draft=drafts.value[sku.unique];if(!draft)continue;for(const field of fields)if(values[field.key]!==''&&(field.key!=='stock'||sku.stock_editable))draft[field.key]=values[field.key];}bulkVisible.value=false;message.value=`已更新 ${selectedRows.value.length} 项规格草稿，点击保存才会提交。`;}
async function save(){if(!data.value||operations.busy.value||!data.value.product.actions.skus)return;try{const all=customerWorkProductSkuUpdates(data.value.skus,drafts.value),attr_value=all.filter(update=>{const original=data.value!.skus.find(row=>row.unique===update.unique)!;return customerWorkCanonicalJson(update)!==customerWorkCanonicalJson({unique:original.unique,price:original.price,cost:original.cost,ot_price:original.ot_price,stock:original.stock});});if(!attr_value.length){message.value='没有需要保存的改动';return;}if(attr_value.length>500){message.value='单次最多保存500项改动，草稿已保留，请分批修改后保存。';return;}message.value='';const result=await operations.submit('update_skus',[data.value.product],data.value,{attr_value});if(result?.outcome==='skus-updated')await manager.load();}catch(failure){message.value=failure instanceof Error?failure.message:'规格编辑内容无效';}}
</script>
