<template>
 <CustomerWorkShell title="全站商品管理" :manager="manager" active="products">
  <template #recovery><CustomerWorkProductRecoveryPanel :operations="operations" /></template>
  <text class="cw-scope">全站平台、门店及供应商商品 · 库存为有效基础规格合计 · 分类与标签取平台目录</text>
  <view class="cw-controls"><input v-model="keyword" placeholder="商品名称、ID或SKU条码" aria-label="商品搜索" confirm-type="search" :disabled="operations.busy.value" @confirm="search" /><button :disabled="operations.busy.value" @tap="search">搜索</button></view>
  <view class="cw-tabs"><button v-for="tab in tabs" :key="tab.value" :class="{active:type===tab.value}" :disabled="operations.busy.value" @tap="filter(tab.value)">{{ tab.name }}</button></view>
  <template v-if="list">
   <text v-if="!list.readiness.writes" class="cw-error">{{ list.readiness.reason || '当前商品写入暂不可用，仍可核对商品数据。' }}</text>
   <view class="cw-card"><view class="cw-row"><text>共 {{ list.count }} 项 · 已选 {{ selected.length }}/100</text><button :disabled="operations.busy.value||list.list.length>100" @tap="selectAll">{{ selected.length===list.list.length&&selected.length?'取消全选':'全选已加载商品' }}</button></view><text v-if="list.list.length>100" class="cw-muted">一次最多选择100项，请分批选择。</text><view class="cw-controls"><button :disabled="!canBatch('categories')" @tap="openTaxonomy('categories',selectedProducts)">修改分类</button><button :disabled="!canBatch('labels')" @tap="openTaxonomy('labels',selectedProducts)">替换标签</button><button v-if="type==='1'" :disabled="!canBatch('hide')" @tap="showProducts(selectedProducts,0)">批量下架</button><button v-else-if="type==='2'" :disabled="!canBatch('show')" @tap="showProducts(selectedProducts,1)">批量上架</button></view></view>
   <text v-if="message||operations.error.value" class="cw-error" role="alert">{{ message || operations.error.value }}</text>
   <view v-for="product in list.list" :key="product.id" class="cw-card" :data-product-id="product.id">
    <view class="cw-row"><button role="checkbox" :aria-checked="selected.includes(product.id)" :disabled="operations.busy.value" @tap="toggle(product.id)">{{ selected.includes(product.id)?'已选':'选择' }}</button><text class="cw-muted">#{{ product.id }} · {{ product.plate_name }}</text><text class="cw-status">{{ product.is_show?'上架中':'仓库中' }}</text></view>
    <view class="cw-cart"><image v-if="product.image" class="cw-image" :src="product.image" mode="aspectFill" /><view class="cw-stack cw-grow"><text class="cw-subtitle">{{ product.store_name }}</text><text>¥{{ product.price }} · 销量 {{ product.sales }} · 库存 {{ product.stock }}</text><text class="cw-muted">{{ product.spec_type?'多规格':'单规格' }} · {{ product.sku_count }} 个有效规格</text><text class="cw-muted">分类：{{ product.cate_name || '未设置' }}</text><text class="cw-muted">标签：{{ product.store_label_id.length?product.store_label_id.join('、'):'未设置' }}</text></view></view>
    <text v-if="product.sku_policy" class="cw-muted">{{ product.sku_policy }}</text><view class="cw-controls"><button v-if="product.is_show" :disabled="operations.busy.value" @tap="preview(product)">预览商品</button><button :disabled="operations.busy.value||!(product.is_show?product.actions.hide:product.actions.show)" @tap="showProducts([product],product.is_show?0:1)">{{ product.is_show?'下架':'上架' }}</button><button :disabled="operations.busy.value||!product.actions.skus||singleLoading" @tap="edit(product)">{{ product.spec_type?'修改规格价格/库存':'修改价格/库存' }}</button><button :disabled="operations.busy.value||!product.actions.categories" @tap="openTaxonomy('categories',[product])">分类</button><button :disabled="operations.busy.value||!product.actions.labels" @tap="openTaxonomy('labels',[product])">标签</button></view>
   </view>
   <view v-if="!list.list.length" class="cw-empty">暂无符合筛选的商品</view><button v-if="list.has_more" class="cw-full" :disabled="moreBusy||operations.busy.value" @tap="loadMore">{{ moreBusy?'正在读取…':'加载更多' }}</button><text v-else-if="list.list.length" class="cw-muted">已读取全部符合筛选的商品</text>
  </template>
  <CustomerWorkProductTaxonomyDialog :visible="taxonomyVisible" :kind="taxonomyKind" :categories="categories" :labels="labels" :selected="taxonomySelected" :loading="taxonomyLoading" :busy="operations.busy.value" :error="taxonomyError" @close="closeTaxonomy" @submit="saveTaxonomy" />
  <CustomerWorkProductEditor :visible="editorVisible" :sku="editingSku" :stock-editable="editingSku?.stock_editable??false" :busy="operations.busy.value" :message="operations.error.value" @close="editorVisible=false" @apply="saveSingle" />
 </CustomerWorkShell>
</template>
<script setup lang="ts">
import { computed,ref } from 'vue';
import CustomerWorkShell from '@/components/customerWork/CustomerWorkShell.vue';
import CustomerWorkProductRecoveryPanel from '@/components/customerWork/CustomerWorkProductRecoveryPanel.vue';
import CustomerWorkProductTaxonomyDialog from '@/components/customerWork/CustomerWorkProductTaxonomyDialog.vue';
import CustomerWorkProductEditor from '@/components/customerWork/CustomerWorkProductEditor.vue';
import { useCustomerWork } from '@/composables/useCustomerWork';
import { useCustomerWorkProductOperations } from '@/composables/useCustomerWorkProductOperations';
import { isCustomerWorkProductList,isCustomerWorkProductCategories,isCustomerWorkProductLabels,isCustomerWorkProductSkus,customerWorkCanonicalJson,customerWorkProductSkuUpdates } from '@/utils/customerWorkProductsContract';
import type { CustomerWorkProductList,CustomerWorkProduct,CustomerWorkProductMeta,CustomerWorkProductCategory,CustomerWorkProductLabelGroup,CustomerWorkProductSku } from '@/types/customerWorkProducts';
const tabs=[{name:'全部',value:''},{name:'出售中',value:'1'},{name:'仓库中',value:'2'},{name:'已售罄',value:'4'},{name:'库存警告',value:'5'}];
const type=ref(''),keyword=ref(''),list=ref<CustomerWorkProductList|null>(null),selected=ref<number[]>([]),message=ref(''),moreBusy=ref(false),singleLoading=ref(false);
const taxonomyVisible=ref(false),taxonomyKind=ref<'categories'|'labels'>('categories'),taxonomySelected=ref<number[]>([]),taxonomyLoading=ref(false),taxonomyError=ref(''),categories=ref<CustomerWorkProductCategory[]>([]),labels=ref<CustomerWorkProductLabelGroup[]>([]),taxonomyProducts=ref<CustomerWorkProduct[]>([]),taxonomyMeta=ref<CustomerWorkProductMeta|null>(null);
const editorVisible=ref(false),editingSku=ref<CustomerWorkProductSku|null>(null),editingProduct=ref<CustomerWorkProduct|null>(null),editingMeta=ref<CustomerWorkProductMeta|null>(null);let selectorEpoch=0,appliedQuery={type:'',store_name:''};
function clear(){selectorEpoch++;list.value=null;selected.value=[];message.value='';moreBusy.value=false;singleLoading.value=false;taxonomyVisible.value=false;taxonomySelected.value=[];taxonomyLoading.value=false;taxonomyError.value='';categories.value=[];labels.value=[];taxonomyProducts.value=[];taxonomyMeta.value=null;editorVisible.value=false;editingSku.value=null;editingProduct.value=null;editingMeta.value=null;}
const manager=useCustomerWork({page:'products',query(query){type.value=query.type??'';keyword.value=query.keyword??'';},clear,async load(controller){const valid=controller.fence(),query={type:type.value,store_name:keyword.value},response=await operations.read('/mobile/work/products',isCustomerWorkProductList,{page:1,limit:20,...query});if(valid()){appliedQuery=query;append(response.data,1);}}});
const operations=useCustomerWorkProductOperations(manager),selectedProducts=computed(()=>(list.value?.list??[]).filter(row=>selected.value.includes(row.id)));
function append(data:CustomerWorkProductList,page:number){if(data.page!==page||data.limit!==20||page>1&&(data.count!==list.value?.count||data.list.some(row=>list.value?.list.some(old=>old.id===row.id))))throw Error('商品分页已变化，请重新读取');list.value={...data,list:[...(page>1?list.value?.list??[]:[]),...data.list]};}
function search(){if(operations.busy.value)return;message.value='';if(keyword.value.length>100||/[\u0000-\u001f\u007f]/u.test(keyword.value)){message.value='搜索文字无效或超过100字';return;}void manager.load();}
function filter(value:string){if(operations.busy.value)return;if(keyword.value.length>100||/[\u0000-\u001f\u007f]/u.test(keyword.value)){message.value='搜索文字无效或超过100字';return;}type.value=value;search();}
async function loadMore(){if(moreBusy.value||operations.busy.value||!list.value?.has_more)return;const valid=manager.fence(),page=list.value.page+1;moreBusy.value=true;try{const response=await operations.read('/mobile/work/products',isCustomerWorkProductList,{page,limit:20,...appliedQuery});if(valid())append(response.data,page);}catch(failure){if(valid())manager.invalidate(failure);}finally{if(valid())moreBusy.value=false;}}
function toggle(id:number){if(operations.busy.value||!list.value?.list.some(row=>row.id===id))return;if(selected.value.includes(id))selected.value=selected.value.filter(value=>value!==id);else if(selected.value.length<100)selected.value=[...selected.value,id];else message.value='每次最多选择100项商品';}
function selectAll(){if(!list.value||operations.busy.value||list.value.list.length>100)return;selected.value=selected.value.length===list.value.list.length?[]:list.value.list.map(row=>row.id);}
function canBatch(action:'show'|'hide'|'categories'|'labels'){return!!list.value?.readiness.writes&&!operations.busy.value&&selectedProducts.value.length>0&&selectedProducts.value.every(row=>row.actions[action]);}
async function showProducts(products:CustomerWorkProduct[],is_show:0|1){if(!list.value)return;const result=await operations.submit('set_show',products,list.value,{is_show});if(result?.outcome==='products-updated')await manager.load();}
function preview(product:CustomerWorkProduct){if(manager.current()&&manager.context.value&&product.is_show)uni.navigateTo({url:`/pages/goods/detail?id=${product.id}`});}
function closeTaxonomy(){selectorEpoch++;taxonomyVisible.value=false;taxonomyLoading.value=false;categories.value=[];labels.value=[];taxonomyProducts.value=[];taxonomyMeta.value=null;}
async function openTaxonomy(kind:'categories'|'labels',products:CustomerWorkProduct[]){if(operations.busy.value||!products.length||products.length>100)return;const valid=manager.fence(),version=++selectorEpoch;taxonomyKind.value=kind;taxonomyProducts.value=JSON.parse(customerWorkCanonicalJson(products));taxonomySelected.value=products.length===1?[...(kind==='categories'?products[0]!.cate_id:products[0]!.store_label_id)]:[];categories.value=[];labels.value=[];taxonomyError.value='';taxonomyMeta.value=null;taxonomyVisible.value=true;taxonomyLoading.value=true;
 try{if(kind==='categories'){const response=await operations.read('/mobile/work/products/categories',isCustomerWorkProductCategories);if(valid()&&version===selectorEpoch){categories.value=response.data.categories;taxonomyMeta.value=response.data;}}else{const response=await operations.read('/mobile/work/products/labels',isCustomerWorkProductLabels);if(valid()&&version===selectorEpoch){labels.value=response.data.labels;taxonomyMeta.value=response.data;}}}catch(failure){if(valid()&&version===selectorEpoch)taxonomyError.value=failure instanceof Error?failure.message:'目录读取失败';}finally{if(valid()&&version===selectorEpoch)taxonomyLoading.value=false;}
}
async function saveTaxonomy(ids:number[]){if(!taxonomyMeta.value)return;const kind=taxonomyKind.value==='categories'?'replace_categories':'replace_labels',payload=kind==='replace_categories'?{cate_id:ids}:{store_label_id:ids};const result=await operations.submit(kind,taxonomyProducts.value,taxonomyMeta.value,payload);if(result?.outcome==='products-updated'){closeTaxonomy();await manager.load();}}
async function edit(product:CustomerWorkProduct){if(operations.busy.value||singleLoading.value||!product.actions.skus)return;if(product.spec_type===1){manager.go('productSkus',{productId:product.id});return;}const valid=manager.fence();singleLoading.value=true;try{const response=await operations.read(`/mobile/work/products/${product.id}/skus`,isCustomerWorkProductSkus);if(!valid())return;if(response.data.product.id!==product.id||response.data.skus.length!==1||!response.data.product.actions.skus)throw Error('单规格拓扑或编辑权限已变化，请重新读取');editingProduct.value=response.data.product;editingSku.value=response.data.skus[0]!;editingMeta.value=response.data;editorVisible.value=true;}catch(failure){if(valid())manager.invalidate(failure);}finally{if(valid())singleLoading.value=false;}}
async function saveSingle(values:{price:string;cost:string;ot_price:string;stock:string}){if(!editingProduct.value||!editingSku.value||!editingMeta.value)return;try{const attr_value=customerWorkProductSkuUpdates([editingSku.value],{[editingSku.value.unique]:values});const result=await operations.submit('update_skus',[editingProduct.value],editingMeta.value,{attr_value});if(result?.outcome==='skus-updated'){editorVisible.value=false;await manager.load();}}catch(failure){operations.error.value=failure instanceof Error?failure.message:'规格编辑内容无效';}}
</script>
