<template>
  <CustomerWorkShell title="售后详情" :manager="manager" :domain-busy="financial.busy.value" active="refunds"><template #recovery><CustomerWorkFinancialRecoveryPanel :operations="financial" /></template><template v-if="refund"><view class="cw-card"><view class="cw-row"><text class="cw-subtitle">{{ refund.order_id }}</text><text class="cw-status">{{ refund._status.status_name }}</text></view><text class="cw-scope">全站退款申请 · {{ refund._add_time }}</text><text class="cw-link" @tap="manager.go('orderDetail',{orderId:refund.store_order_sn})">查看原订单 {{ refund.store_order_sn }}</text><view class="cw-divider"><view class="cw-row"><text>申请金额</text><text class="cw-money">¥{{ refund.refund_price }}</text></view><view class="cw-row"><text>已退金额</text><text>¥{{ refund.refunded_price }}</text></view><view class="cw-row"><text>退款数量</text><text>{{ refund.refund_num }}</text></view></view></view>
    <view class="cw-card"><text class="cw-subtitle">退款商品</text><view v-for="cart in refund.cartInfo" :key="cart.id" class="cw-cart"><image v-if="cart.productInfo.image" class="cw-image" :src="cart.productInfo.image" mode="aspectFill" /><view class="cw-stack"><text>{{ cart.productInfo.store_name }}</text><text class="cw-muted">{{ cart.productInfo.attrInfo.suk }} · {{ cart.cart_num }} 件</text><text>¥{{ cart.truePrice }}</text></view></view></view>
    <view class="cw-card"><text class="cw-subtitle">原因与凭证</text><text class="cw-scope cw-read-text">原因：{{ refund.refund_reason || '未填写' }}</text><text class="cw-scope cw-read-text">说明：{{ refund.refund_explain || '未填写' }}</text><text class="cw-scope">拒绝理由：{{ refund.refuse_reason || '无' }}</text><text class="cw-scope cw-read-text">管理备注：{{ refund.remark || '无' }}</text><view class="cw-images"><image v-for="(src,index) in [...refund.refund_img,...refund.refund_goods_img]" :key="index" :src="src" mode="aspectFit" /></view></view>
    <view class="cw-card"><text class="cw-subtitle">收货与退回物流</text><view class="cw-row"><text>{{ refund.real_name }}</text><text>{{ refund.user_phone }}</text></view><text class="cw-scope">{{ refund.user_address }}</text><view class="cw-row"><text>{{ refund.refund_express_name || '尚无退回快递' }}</text><text>{{ refund.refund_express }}</text></view><text class="cw-scope">退回联系电话：{{ refund.refund_phone || '未填写' }}</text><button class="cw-full" @tap="manager.go('logistics',{orderId:refund.order_id,type:'refund'})">查询退回物流</button></view>
    <view class="cw-card" data-financial-actions="refund"><text class="cw-subtitle">退款处理</text><template v-if="financial.review.value"><text class="cw-scope">当前申请 {{ financial.review.value.data.refund_no }} · 已核对申请金额 ¥{{ financial.review.value.data.refund_price }}。申请已创建与资金已退回分别核对。</text><text class="cw-scope cw-read-text">管理备注：{{ financial.review.value.data.remark||'无' }}</text><view class="cw-controls"><button v-for="kind in refundKinds" :key="kind" :disabled="financial.busy.value||!financial.review.value.data.actions[kind].available" @tap="openFinancial(kind)">{{ CUSTOMER_FINANCIAL_NAMES[kind] }}</button></view><text v-for="kind in refundKinds" :key="kind+'reason'" class="cw-scope">{{ CUSTOMER_FINANCIAL_NAMES[kind] }}：{{ financial.review.value.data.actions[kind].available?'可核对并提交':customerFinancialNotice(financial.review.value.data.actions[kind].reason) }}</text></template><text v-if="financial.error.value" class="cw-error">{{ financial.error.value }}</text></view>
    <CustomerWorkFinancialDialog v-if="financialKind&&financial.review.value" :operations="financial" :kind="financialKind" :basis="financial.review.value.data" @close="financialKind=null" @saved="savedFinancial" />
    </template></CustomerWorkShell>
</template>
<script setup lang="ts">
import { ref } from 'vue';import CustomerWorkShell from '@/components/customerWork/CustomerWorkShell.vue';import { useCustomerWork } from '@/composables/useCustomerWork';import { isCustomerWorkRefundDetail } from '@/utils/customerWork';import type { CustomerWorkRefundDetail } from '@/types/customerWork';
import CustomerWorkFinancialRecoveryPanel from '@/components/customerWork/CustomerWorkFinancialRecoveryPanel.vue';import CustomerWorkFinancialDialog from '@/components/customerWork/CustomerWorkFinancialDialog.vue';import {useCustomerWorkFinancialOperations} from '@/composables/useCustomerWorkFinancialOperations';import {CUSTOMER_FINANCIAL_NAMES,customerFinancialNotice} from '@/utils/customerWorkFinancial';
const refundKinds=['refund_return','refund_refuse','refund_execute','refund_remark'] as const;
const refund=ref<CustomerWorkRefundDetail|null>(null),refundOrderId=ref(''),financialKind=ref<typeof refundKinds[number]|null>(null);const manager=useCustomerWork({page:'refundDetail',query(query){refundOrderId.value=query.refundOrderId!;},clear(){refund.value=null;financialKind.value=null;financial.clearDomain();},async load(controller){const valid=controller.fence(),id=refundOrderId.value,response=await controller.read(`refunds/${encodeURIComponent(id)}`,isCustomerWorkRefundDetail);if(!valid())return;if(response.data.order_id!==id&&String(response.data.id)!==id)throw Error('退款业务编号不匹配');refund.value=response.data;const actual=await financial.loadRefund(response.data.id,response.data.order_id);if(!valid())return;if(actual.order_id!==response.data.store_order_id||actual.order_no!==response.data.store_order_sn||actual.uid!==response.data.uid)throw Error('退款财务原订单实体不匹配');await financial.checkRelevant(actual.payment_order_id);}}),financial=useCustomerWorkFinancialOperations(manager);
function openFinancial(kind:typeof refundKinds[number]){if(!financial.busy.value&&financial.review.value?.data.actions[kind].available)financialKind.value=kind;}
function savedFinancial(){financialKind.value=null;void manager.load();}
</script>
<style scoped>
.cw-read-text{white-space:pre-wrap;}
</style>
