<template>
  <CustomerWorkShell title="全站售后查询" :manager="manager" :domain-busy="financial.busy.value||financialReading" active="refunds"><template #recovery><CustomerWorkFinancialRecoveryPanel :operations="financial" /></template><view class="cw-card"><text class="cw-scope">全站退款申请 · 每项处理须重新核对实际申请与当前资格</text><view class="cw-tabs"><button v-for="(label,index) in refundLabels" :key="label" :class="{active:filters.refundTypes===refundValues[index]}" :disabled="manager.loading.value" @tap="chooseRefund(index)">{{ label }}</button></view><view class="cw-controls"><picker :range="applyLabels" :value="applyIndex" @change="chooseApply"><view>申请类型：{{ applyLabels[applyIndex] }} ⌄</view></picker><picker :range="dateLabels" :value="dateIndex" @change="chooseDate"><view>日期：{{ dateLabels[dateIndex] }} ⌄</view></picker></view><text v-if="filters.time" class="cw-scope">当前日期：{{ filters.time }}</text><view class="cw-controls"><input v-model="keyword" :maxlength="100" placeholder="退款单号、订单号或收货信息" @confirm="search" /><button :disabled="manager.loading.value" @tap="search">搜索</button></view><text class="cw-muted">共 {{ count }} 条</text></view>
    <view v-for="refund in rows" :key="refund.id" class="cw-card"><view class="cw-row"><text class="cw-link" @tap="manager.go('refundDetail',{refundOrderId:refund.order_id})">{{ refund.order_id }}</text><text class="cw-status">{{ refund._status.status_name }}</text></view><text class="cw-scope">原订单 {{ refund.store_order_sn }} · {{ refund._add_time }}</text><view v-for="cart in refund.cartInfo" :key="cart.id" class="cw-cart"><image v-if="cart.productInfo.image" class="cw-image" :src="cart.productInfo.image" mode="aspectFill" /><view class="cw-stack"><text>{{ cart.productInfo.store_name }}</text><text class="cw-muted">{{ cart.productInfo.attrInfo.suk }} · {{ cart.cart_num }} 件</text><text>¥{{ cart.truePrice }}</text></view></view><view class="cw-row"><text>{{ refund.refund_num }} 件退款</text><text>申请 ¥{{ refund.refund_price }} · 已退 ¥{{ refund.refunded_price }}</text></view><text class="cw-scope">{{ refund.refund_reason }} · {{ refund.refund_explain }}</text><button class="cw-full" @tap="manager.go('refundDetail',{refundOrderId:refund.order_id})">查看售后</button><view class="cw-controls"><button v-for="kind in refundKinds" :key="kind" :disabled="manager.loading.value||financial.busy.value||financialReading" @tap="openFinancial(refund,kind)">{{ CUSTOMER_FINANCIAL_NAMES[kind] }}</button></view></view><view v-if="!rows.length" class="cw-empty">当前筛选暂无退款申请</view><button v-if="hasMore" class="cw-full" :disabled="paging" @tap="more">{{ paging?'读取中…':'加载更多售后' }}</button><text v-if="financialMessage||financial.error.value" class="cw-scope">{{ financialMessage||financial.error.value }}</text><CustomerWorkFinancialDialog v-if="financialKind&&financial.review.value" :operations="financial" :kind="financialKind" :basis="financial.review.value.data" @close="financialKind=null" @saved="savedFinancial" /></CustomerWorkShell>
</template>
<script setup lang="ts">
import { computed,ref } from 'vue';import { onReachBottom } from '@dcloudio/uni-app';import CustomerWorkShell from '@/components/customerWork/CustomerWorkShell.vue';import { useCustomerWork } from '@/composables/useCustomerWork';import { parseCustomerWorkQuery,isCustomerWorkPaged,isCustomerWorkRefund,customerWorkDateRange } from '@/utils/customerWork';import type { CustomerWorkRefund } from '@/types/customerWork';
import CustomerWorkFinancialRecoveryPanel from '@/components/customerWork/CustomerWorkFinancialRecoveryPanel.vue';import CustomerWorkFinancialDialog from '@/components/customerWork/CustomerWorkFinancialDialog.vue';import {useCustomerWorkFinancialOperations} from '@/composables/useCustomerWorkFinancialOperations';import {CUSTOMER_FINANCIAL_NAMES,customerFinancialNotice} from '@/utils/customerWorkFinancial';
const refundLabels=['待审核','待收货','全部待处理','已完成'],refundValues=['0','2','5','6'],applyLabels=['全部','未发货仅退款','退货退款','已发货仅退款','其他申请3','其他申请4'],dateLabels=['全部时间','最近3天','本月','近3个月','近6个月'];
const refundKinds=['refund_return','refund_refuse','refund_execute','refund_remark'] as const;
const filters=ref<Record<string,string>>({refundTypes:'5'}),keyword=ref(''),dateIndex=ref(0),rows=ref<CustomerWorkRefund[]>([]),count=ref(0),hasMore=ref(false),paging=ref(false),financialKind=ref<typeof refundKinds[number]|null>(null),financialReading=ref(false),financialMessage=ref(''),applyIndex=computed(()=>filters.value.apply_type===undefined||filters.value.apply_type===''?0:Number(filters.value.apply_type)+1);let page=1;
const manager=useCustomerWork({page:'refunds',query(query){filters.value={refundTypes:'5',...query};keyword.value=query.order_id??'';},clear(){rows.value=[];count.value=0;hasMore.value=false;paging.value=false;page=1;financialKind.value=null;financialReading.value=false;financialMessage.value='';financial.clearDomain();},async load(controller){const valid=controller.fence(),response=await controller.read('refunds',isCustomerWorkPaged(isCustomerWorkRefund),{...parseCustomerWorkQuery('refunds',filters.value),page:1,limit:10});if(!valid())return;if(response.data.page!==1||new Set(response.data.list.map(row=>row.id)).size!==response.data.list.length)throw Error('售后分页依据不匹配');rows.value=response.data.list;count.value=response.data.count;hasMore.value=response.data.has_more;}}),financial=useCustomerWorkFinancialOperations(manager);
async function openFinancial(row:CustomerWorkRefund,kind:typeof refundKinds[number]){if(manager.loading.value||financial.busy.value||financialReading.value)return;const valid=manager.fence();if(!valid()||!rows.value.some(value=>value.id===row.id&&value.order_id===row.order_id))return;financialKind.value=null;financialMessage.value='';financialReading.value=true;try{const basis=await financial.loadRefund(row.id,row.order_id);if(!valid())return;if(basis.order_id!==row.store_order_id||basis.order_no!==row.store_order_sn||basis.uid!==row.uid)throw Error('退款财务原订单实体不匹配');await financial.checkRelevant(basis.payment_order_id);if(!valid())return;if(!basis.actions[kind].available){financialMessage.value=customerFinancialNotice(basis.actions[kind].reason);return;}financialKind.value=kind;}catch(failure){if(valid())manager.invalidate(failure);}finally{if(valid())financialReading.value=false;}}
function savedFinancial(){financialKind.value=null;void manager.load();}
function refresh(){if(!manager.loading.value)void manager.load();}function chooseRefund(index:number){if(!Number.isInteger(index)||index<0||index>=refundValues.length||manager.loading.value)return;filters.value.refundTypes=refundValues[index]!;refresh();}function chooseApply(event:{detail:{value:string|number}}){const index=Number(event.detail.value);if(!Number.isInteger(index)||index<0||index>5)return;filters.value.apply_type=index===0?'':String(index-1);refresh();}function chooseDate(event:{detail:{value:string|number}}){const index=Number(event.detail.value);if(!Number.isInteger(index)||index<0||index>4)return;dateIndex.value=index;filters.value.time=customerWorkDateRange(index);refresh();}function search(){filters.value.order_id=keyword.value.trim();refresh();}
async function more(){if(!manager.current()||!manager.context.value||manager.loading.value||paging.value||!hasMore.value)return;const valid=manager.fence(),next=page+1;paging.value=true;try{const response=await manager.read('refunds',isCustomerWorkPaged(isCustomerWorkRefund),{...parseCustomerWorkQuery('refunds',filters.value),page:next,limit:10});if(!valid())return;if(response.data.page!==next||response.data.count!==count.value||response.data.list.some(row=>rows.value.some(old=>old.id===row.id)))throw Error('售后列表已变化，请刷新');rows.value.push(...response.data.list);hasMore.value=response.data.has_more;page=next;}catch(failure){if(valid())manager.invalidate(failure);}finally{if(valid())paging.value=false;}}onReachBottom(()=>void more());
</script>
