<template><CustomerWorkShell title="客户核销查询" :manager="manager" :domain-busy="writeoff.busy.value||reading||scanning" active="scanning"><template #recovery><CustomerWorkWriteoffRecoveryPanel :operations="writeoff" /></template><view class="cw-card"><text class="cw-subtitle">扫描或手动输入</text><text class="cw-scope">核销码与会员条码分别核对。自动查询遇到重号或两种命名空间碰撞时会拒绝，须明确选择后重新查询。</text><view class="cw-tabs"><button v-for="item in namespaces" :key="item.value" :class="{active:namespace===item.value}" :disabled="reading||scanning||writeoff.busy.value" @tap="choose(item.value)">{{ item.name }}</button></view><input v-model="value" maxlength="32" placeholder="核销码或会员条码" confirm-type="search" :disabled="reading||scanning||writeoff.busy.value" @confirm="lookup" /><view class="cw-controls"><button :disabled="reading||scanning||writeoff.busy.value||!writeoff.readable()" @tap="scan">{{ scanning?'扫描中…':'扫码' }}</button><button :disabled="reading||scanning||writeoff.busy.value||!writeoff.readable()" @tap="lookup">{{ reading?'查询中…':'查询订单' }}</button></view></view><view v-if="result" class="cw-card"><text class="cw-subtitle">{{ result.lookup_kind==='member-barcode'?'会员待核销订单':'实际核销订单' }}</text><text v-if="!result.orders.length" class="cw-scope">当前没有可核对的订单。</text><view v-for="order in result.orders" :key="order.id" class="cw-stack cw-divider" :data-writeoff-order="order.id"><text>{{ order.order_no }}</text><text class="cw-muted">{{ order.product_type===4?'次卡':'商品' }} · 买家 {{ order.uid===0?'匿名收银顾客':order.uid }} · {{ order.store_id?'门店 '+order.store_id:order.cashier_origin.eligible?'已证明收银来源':'平台' }}</text><text>{{ order.carts.reduce((n,row)=>n+row.write_surplus_times,0) }} 次剩余</text><text v-if="!order.actions.writeoff.available" class="cw-error">{{ customerWriteoffNotice(order.actions.writeoff.reason||order.readiness.reason) }}</text><view class="cw-controls"><button :disabled="reading||writeoff.busy.value" @tap="open(order)">核对商品与次数</button><button :disabled="reading||writeoff.busy.value" @tap="manager.go('writeoffRecords',{orderId:order.id,orderNo:order.order_no})">核销记录</button></view></view></view><text v-if="error||writeoff.error.value" class="cw-error">{{ error||writeoff.error.value }}</text></CustomerWorkShell></template>
<script setup lang="ts">
import {ref,watch} from 'vue';
import {onHide,onUnload} from '@dcloudio/uni-app';
import CustomerWorkShell from '@/components/customerWork/CustomerWorkShell.vue';
import CustomerWorkWriteoffRecoveryPanel from '@/components/customerWork/CustomerWorkWriteoffRecoveryPanel.vue';
import {useCustomerWork} from '@/composables/useCustomerWork';
import {useCustomerWorkWriteoffOperations} from '@/composables/useCustomerWorkWriteoffOperations';
import {decodeCustomerWriteoffScan,writeoffLookupValue,customerWriteoffNotice} from '@/utils/customerWorkWriteoff';
import {customerWorkWechatScan,customerWorkWechatScannerAvailable} from '@/utils/customerWorkWechatScan';
import {createUserCenterRequests,type UserCenterRequests} from '@/api/userCenter';
import type {CustomerWorkWriteoffNamespace,CustomerWorkWriteoffLookup,CustomerWorkWriteoffTarget} from '@/types/customerWorkWriteoff';
type VisibleNamespace=Exclude<CustomerWorkWriteoffNamespace,'legacy-order-id'>;
const namespaces=[{value:'auto' as const,name:'自动核对'},{value:'order-code' as const,name:'订单核销码'},{value:'member-barcode' as const,name:'会员条码'}],namespace=ref<VisibleNamespace>('auto'),value=ref(''),result=ref<CustomerWorkWriteoffLookup|null>(null),reading=ref(false),scanning=ref(false),error=ref('');let routeInput:{namespace:VisibleNamespace;value:string}|null=null,epoch=0,scanRequests:UserCenterRequests|null=null;
const manager=useCustomerWork({page:'scanning',query(query){routeInput=query.value?{namespace:query.namespace as VisibleNamespace,value:query.value}:null;},clear(){epoch++;scanRequests?.abort();scanRequests=null;namespace.value='auto';value.value='';result.value=null;reading.value=false;scanning.value=false;error.value='';writeoff.clearDomain();},async load(){if(!writeoff.readable())throw Error('当前普通客户核销查询入口不可用');const hint=routeInput;routeInput=null;if(hint){namespace.value=hint.namespace;value.value=hint.value;await lookup();}}}),writeoff=useCustomerWorkWriteoffOperations(manager);
function choose(next:VisibleNamespace){if(reading.value||scanning.value||writeoff.busy.value)return;namespace.value=next;result.value=null;error.value='';}
async function lookup(){if(reading.value||scanning.value||writeoff.busy.value||!writeoff.readable())return;const valid=manager.fence(),version=++epoch,ns=namespace.value,text=value.value.trim();result.value=null;error.value='';if(!writeoffLookupValue(ns,text)){error.value='请输入有效的 12 位核销码或不超过 32 字符的会员条码';return;}value.value=text;reading.value=true;try{const response=await writeoff.lookup(ns,text);if(valid()&&version===epoch)result.value=response;}catch(failure){if(valid()&&version===epoch)error.value=failure instanceof Error?customerWriteoffNotice(failure.message):'核销查询需核对';}finally{if(valid()&&version===epoch)reading.value=false;}}
function nativeScan(valid:()=>boolean):Promise<{namespace:VisibleNamespace;value:string}|null>{return new Promise((resolve,reject)=>{uni.scanCode({scanType:['qrCode','barCode'],success:scan=>{if(!valid()){resolve(null);return;}try{const result=typeof scan.result==='string'&&scan.result?decodeCustomerWriteoffScan(scan.result,'native',scan.scanType):null,path=typeof scan.path==='string'&&scan.path?decodeCustomerWriteoffScan('/'+scan.path.replace(/^\//u,''),'native',scan.scanType):null;if(!result&&!path)throw Error('扫码未返回有效核销内容');if(result&&path&&result.value!==path.value)throw Error('扫码结果与页面目标不一致');resolve(path??result);}catch(failure){reject(failure);}},fail:scan=>{if(!valid()||/cancel/iu.test(scan.errMsg??''))resolve(null);else reject(Error('扫码失败，可手动输入'));}});});}
async function scan(){if(reading.value||scanning.value||writeoff.busy.value||!writeoff.readable())return;const fence=manager.fence(),version=++epoch,valid=()=>fence()&&version===epoch,owner=createUserCenterRequests(valid);scanRequests=owner;scanning.value=true;error.value='';result.value=null;try{let decoded:{namespace:VisibleNamespace;value:string}|null=null;
 // #ifdef H5
 if(!customerWorkWechatScannerAvailable())throw Error('请在微信内扫码，或手动输入核销码与会员条码');const raw=await customerWorkWechatScan(valid,{scanTypes:['qrCode','barCode'],rawResult:true,readSignature:url=>owner.request('wechat/config','GET',{url},true)});if(raw!==null)decoded=decodeCustomerWriteoffScan(raw,'wechat');
 // #endif
 // #ifndef H5
 decoded=await nativeScan(valid);
 // #endif
 if(!valid()||!decoded)return;namespace.value=decoded.namespace;value.value=decoded.value;scanning.value=false;await lookup();}catch(failure){if(valid())error.value=failure instanceof Error?customerWriteoffNotice(failure.message):'扫码内容需核对';}finally{owner.abort();if(scanRequests===owner)scanRequests=null;if(valid())scanning.value=false;}}
function open(order:CustomerWorkWriteoffTarget){if(writeoff.readable()&&!reading.value&&!writeoff.busy.value)manager.go('writeoff',{orderId:order.id,orderNo:order.order_no});}
onHide(()=>{routeInput=null;});onUnload(()=>{routeInput=null;});
watch(()=>[manager.auth.uid,manager.auth.token,manager.auth.sessionVersion],()=>{routeInput=null;},{flush:'sync'});watch(()=>manager.error.value,message=>{if(message)routeInput=null;},{flush:'sync'});
</script>
