<template><CustomerWorkShell title="用户详情" :manager="manager" active="users"><template #recovery><CustomerWorkUserRecoveryPanel :operations="operations" /></template>
 <template v-if="data"><view class="cw-card"><view class="cw-cart"><image v-if="data.user.avatar" :src="data.user.avatar" mode="aspectFill" class="cw-image" /><view class="cw-stack cw-grow"><text class="cw-subtitle">{{ data.user.nickname||'未设置昵称' }}</text><text>UID {{ data.user.uid }} · {{ data.user.phone||'未设置手机号' }}</text><text class="cw-status">{{ data.user.deleted?'已删除 · 只读':data.user.status?'正常账户':'已停用账户' }}</text></view></view><view class="cw-row"><text>真实姓名</text><text>{{ data.user.real_name||'未设置' }}</text></view><view class="cw-row"><text>生日</text><text>{{ data.user.birthday||'未设置' }}</text></view><view class="cw-row"><text>身份证号</text><text>{{ data.user.card_id||'未设置' }}</text></view><view class="cw-row"><text>地址</text><text>{{ data.user.addres||'未设置' }}</text></view><view class="cw-row"><text>注册时间</text><text>{{ data.user._add_time||'未设置' }}</text></view></view>
  <view class="cw-grid"><view class="cw-metric"><text>余额</text><text class="cw-money">{{ data.user.now_money===null?'记录异常':'¥'+data.user.now_money }}</text></view><view class="cw-metric"><text>积分</text><text class="cw-money">{{ data.user.integral===null?'记录异常':data.user.integral }}</text></view><view class="cw-metric"><text>未使用且未过期券</text><text class="cw-money">{{ data.user.coupon_num }}</text><button :disabled="operations.busy.value" @tap="editor.wallet(data.user.uid)">查看持有券</button></view></view><text v-for="diagnostic in data.user.financial_diagnostics" :key="diagnostic" class="cw-error">{{ customerWorkUserNotice(diagnostic,'diagnostic') }}</text>
  <view class="cw-card"><text class="cw-subtitle">用户经营资料</text><view class="cw-row"><text>分组</text><text>{{ data.user.group_name||'未分组' }}</text></view><view class="cw-row"><text>等级</text><text>{{ data.user.level_name||'未设等级' }}{{ data.user.level&&!data.user.level_status?'（当前停用）':'' }}</text></view><text>平台标签：{{ data.user.labels.map(label=>label.label_name).join('、')||'未设置' }}</text><view class="cw-divider" /><text>{{ data.user.is_ever_level?(data.user.membership_active?'永久会员':'永久会员标记 · 当前未生效'):data.user.membership_active?`会员有效 · 剩余 ${data.user.svip_over_day??0} 天`:'会员当前未生效' }}</text><text class="cw-scope">付费会员标记：{{ data.user.isMember?'有':'无' }} · {{ data.user.svip_overdue_time }}</text><view class="cw-row"><text>已支付原始订单数</text><text>{{ data.user.order_total_count }}</text></view><view class="cw-row"><text>履约订单有效支付额</text><text>¥{{ data.user.order_total_price }}</text></view><text class="cw-muted">订单数按原始支付订单；金额按实际履约订单及退款条件分别统计。</text></view>
  <text v-if="!data.readiness.writes" class="cw-error">{{ customerWorkUserNotice(data.readiness.reason,'readiness') }}</text><text v-if="operations.error.value" class="cw-error" role="alert">{{ operations.error.value }}</text><view class="cw-card"><text class="cw-subtitle">用户管理</text><view v-for="kind in kinds" :key="kind" class="cw-row"><button :disabled="operations.busy.value||!data.readiness.writes||!data.user.actions[kind].available" @tap="editor.open(kind,[data.user],data)">{{ names[kind] }}</button><text v-if="data.user.actions[kind].reason" class="cw-muted">{{ customerWorkUserNotice(data.user.actions[kind].reason) }}</text></view></view>
 </template>
 <CustomerWorkUserAssignmentDialog :visible="editor.assignmentVisible.value" :kind="assignmentKind" :target-count="editor.users.value.length" :groups="editor.groups.value" :levels="editor.levels.value" :labels="editor.labels.value" :selected="editor.selected.value" :loading="editor.loading.value" :busy="operations.busy.value" :error="editor.error.value||operations.error.value" @close="editor.clear" @submit="editor.save" />
 <CustomerWorkUserMembershipDialog :visible="editor.membershipVisible.value" :permanent="editor.users.value[0]?.is_ever_level===1" :days="editor.users.value[0]?.svip_over_day??null" :busy="operations.busy.value" :error="operations.error.value" @close="editor.clear" @submit="editor.save" />
 <CustomerWorkUserFinanceDialog :visible="editor.financeVisible.value" :kind="editor.kind.value==='adjust_integral'?'adjust_integral':'adjust_money'" :current-value="editor.kind.value==='adjust_integral'?editor.users.value[0]?.integral??null:editor.users.value[0]?.now_money??null" :busy="operations.busy.value" :error="operations.error.value" @close="editor.clear" @submit="editor.save" />
 <CustomerWorkUserCouponDialog :visible="editor.couponVisible.value" :mode="editor.couponMode.value" :uid="editor.walletUid.value" :target-ids="editor.users.value.map(user=>user.uid)" :operations="operations" @close="editor.clear" @grant="editor.grant" />
</CustomerWorkShell></template>
<script setup lang="ts">
import { customerWorkUserNotice } from '@/utils/customerWorkUsers';
import { computed,ref } from 'vue';import CustomerWorkShell from '@/components/customerWork/CustomerWorkShell.vue';import CustomerWorkUserRecoveryPanel from '@/components/customerWork/CustomerWorkUserRecoveryPanel.vue';import CustomerWorkUserAssignmentDialog from '@/components/customerWork/CustomerWorkUserAssignmentDialog.vue';import CustomerWorkUserMembershipDialog from '@/components/customerWork/CustomerWorkUserMembershipDialog.vue';import CustomerWorkUserFinanceDialog from '@/components/customerWork/CustomerWorkUserFinanceDialog.vue';import CustomerWorkUserCouponDialog from '@/components/customerWork/CustomerWorkUserCouponDialog.vue';import { useCustomerWork } from '@/composables/useCustomerWork';import { useCustomerWorkUserOperations,useCustomerWorkUserEditor } from '@/composables/useCustomerWorkUserOperations';import { isCustomerWorkUserDetailData,CUSTOMER_WORK_USER_KINDS,CUSTOMER_WORK_USER_NAMES } from '@/utils/customerWorkUsersContract';import type { CustomerWorkUserDetailData } from '@/types/customerWorkUsers';
const uid=ref(0),data=ref<CustomerWorkUserDetailData|null>(null),kinds=CUSTOMER_WORK_USER_KINDS,names=CUSTOMER_WORK_USER_NAMES;
const manager=useCustomerWork({page:'userDetail',query(query){uid.value=Number(query.uid);},clear(){data.value=null;editor.clear();},async load(controller){const requested=uid.value,valid=controller.fence(),response=await operations.read(`/mobile/work/users/${requested}`,isCustomerWorkUserDetailData);if(valid()){if(response.data.user.uid!==requested)throw Error('详情用户与请求UID不一致');data.value=response.data;}}}),operations=useCustomerWorkUserOperations(manager),editor=useCustomerWorkUserEditor(manager,operations),assignmentKind=computed(()=>['replace_level','replace_group','replace_labels'].includes(editor.kind.value)?editor.kind.value as 'replace_level'|'replace_group'|'replace_labels':'replace_group');
</script>
