<template><CustomerWorkShell title="全站用户管理" :manager="manager" active="users"><template #recovery><CustomerWorkUserRecoveryPanel :operations="operations" /></template>
 <text class="cw-scope">全站用户 · 分组与等级取实际目录 · 标签限平台标签 · 付费会员标记与有效期分别显示</text><view class="cw-controls"><input v-model="keyword" placeholder="昵称、UID或手机号" aria-label="用户搜索" confirm-type="search" :disabled="operations.busy.value" @confirm="search" /><button :disabled="operations.busy.value" @tap="search">搜索</button><button :disabled="operations.busy.value" @tap="openFilter">筛选</button></view>
 <text v-if="message||operations.error.value" class="cw-error" role="alert">{{ message||operations.error.value }}</text>
 <template v-if="list"><text v-if="!list.readiness.writes" class="cw-error">{{ customerWorkUserNotice(list.readiness.reason,'readiness') }}</text><view class="cw-card"><view class="cw-row"><text>共 {{ list.count }} 位 · 已选 {{ selected.length }}/100</text><button :disabled="operations.busy.value||list.list.length>100" @tap="selectAll">{{ selected.length===list.list.length&&selected.length?'取消全选':'全选已加载用户' }}</button></view><text v-if="list.list.length>100" class="cw-muted">一次最多100位，请分批选择；不会截断选择后提交。</text><view class="cw-controls"><button v-for="kind in bulkKinds" :key="kind" :disabled="!canBatch(kind)" @tap="editor.open(kind,selectedUsers,list)">{{ names[kind] }}</button></view></view>
  <view v-for="user in list.list" :key="user.uid" class="cw-card" :data-user-id="user.uid"><view class="cw-row"><button role="checkbox" :aria-checked="selected.includes(user.uid)" :disabled="operations.busy.value" @tap="toggle(user.uid)">{{ selected.includes(user.uid)?'已选':'选择' }}</button><text class="cw-muted">UID {{ user.uid }}</text><text class="cw-status">{{ user.status?'正常账户':'已停用账户' }}</text></view><view class="cw-cart"><image v-if="user.avatar" :src="user.avatar" class="cw-image" mode="aspectFill" /><view class="cw-stack cw-grow"><button class="cw-link" @tap="manager.go('userDetail',{uid:user.uid})">{{ user.nickname||'未设置昵称' }}</button><text>{{ user.phone||'未设置手机号' }}</text><text class="cw-muted">{{ user.group_name||'未分组' }} · {{ user.level_name||'未设等级' }}</text><text class="cw-muted">平台标签：{{ user.labels.map(label=>label.label_name).join('、')||'未设置' }}</text><text>余额 {{ user.now_money===null?'记录异常':'¥'+user.now_money }} · 积分 {{ user.integral===null?'记录异常':user.integral }}</text><text>{{ membership(user) }}</text></view></view><text v-for="diagnostic in user.financial_diagnostics" :key="diagnostic" class="cw-error">{{ customerWorkUserNotice(diagnostic,'diagnostic') }}</text><view class="cw-controls"><button v-for="kind in kinds" :key="kind" :disabled="operations.busy.value||!list.readiness.writes||!user.actions[kind].available" :title="customerWorkUserNotice(user.actions[kind].reason)" @tap="editor.open(kind,[user],list)">{{ names[kind] }}</button><button :disabled="operations.busy.value" @tap="editor.wallet(user.uid)">查看优惠券</button><button @tap="manager.go('userDetail',{uid:user.uid})">用户详情</button></view></view>
  <view v-if="!list.list.length" class="cw-empty">暂无符合筛选的用户</view><button v-if="list.has_more" class="cw-full" :disabled="moreBusy||operations.busy.value" @tap="loadMore">{{ moreBusy?'正在读取…':'加载更多' }}</button><text v-else-if="list.list.length" class="cw-muted">已读取全部符合筛选的用户</text>
 </template>
 <CustomerWorkUserFilterDialog :visible="filterVisible" :groups="filterGroups" :levels="filterLevels" :labels="filterLabels" :value="filters" :loading="filterLoading" :busy="operations.busy.value" :error="filterError" @close="closeFilter" @submit="applyFilter" />
 <CustomerWorkUserAssignmentDialog :visible="editor.assignmentVisible.value" :kind="assignmentKind" :target-count="editor.users.value.length" :groups="editor.groups.value" :levels="editor.levels.value" :labels="editor.labels.value" :selected="editor.selected.value" :loading="editor.loading.value" :busy="operations.busy.value" :error="editor.error.value||operations.error.value" @close="editor.clear" @submit="editor.save" />
 <CustomerWorkUserMembershipDialog :visible="editor.membershipVisible.value" :permanent="editor.users.value[0]?.is_ever_level===1" :days="editor.users.value[0]?.svip_over_day??null" :busy="operations.busy.value" :error="operations.error.value" @close="editor.clear" @submit="editor.save" />
 <CustomerWorkUserFinanceDialog :visible="editor.financeVisible.value" :kind="editor.kind.value==='adjust_integral'?'adjust_integral':'adjust_money'" :current-value="editor.kind.value==='adjust_integral'?editor.users.value[0]?.integral??null:editor.users.value[0]?.now_money??null" :busy="operations.busy.value" :error="operations.error.value" @close="editor.clear" @submit="editor.save" />
 <CustomerWorkUserCouponDialog :visible="editor.couponVisible.value" :mode="editor.couponMode.value" :uid="editor.walletUid.value" :target-ids="editor.users.value.map(user=>user.uid)" :operations="operations" @close="editor.clear" @grant="editor.grant" />
</CustomerWorkShell></template>
<script setup lang="ts">
import { customerWorkUserNotice } from '@/utils/customerWorkUsers';
import { computed,ref } from 'vue';import CustomerWorkShell from '@/components/customerWork/CustomerWorkShell.vue';import CustomerWorkUserRecoveryPanel from '@/components/customerWork/CustomerWorkUserRecoveryPanel.vue';import CustomerWorkUserFilterDialog from '@/components/customerWork/CustomerWorkUserFilterDialog.vue';import CustomerWorkUserAssignmentDialog from '@/components/customerWork/CustomerWorkUserAssignmentDialog.vue';import CustomerWorkUserMembershipDialog from '@/components/customerWork/CustomerWorkUserMembershipDialog.vue';import CustomerWorkUserFinanceDialog from '@/components/customerWork/CustomerWorkUserFinanceDialog.vue';import CustomerWorkUserCouponDialog from '@/components/customerWork/CustomerWorkUserCouponDialog.vue';import { useCustomerWork } from '@/composables/useCustomerWork';import { useCustomerWorkUserOperations,useCustomerWorkUserEditor } from '@/composables/useCustomerWorkUserOperations';import { isCustomerWorkUserList,isCustomerWorkUserGroups,isCustomerWorkUserLevels,isCustomerWorkUserLabels,CUSTOMER_WORK_USER_KINDS,CUSTOMER_WORK_USER_NAMES } from '@/utils/customerWorkUsersContract';import type { CustomerWorkUserList,CustomerWorkUser,CustomerWorkUserKind,CustomerWorkUserGroups,CustomerWorkUserLevels,CustomerWorkUserLabels } from '@/types/customerWorkUsers';
const keyword=ref(''),filters=ref<Record<string,string>>({group_id:'0',level:'0',label_ids:'',isMember:''}),list=ref<CustomerWorkUserList|null>(null),selected=ref<number[]>([]),message=ref(''),moreBusy=ref(false),filterVisible=ref(false),filterLoading=ref(false),filterError=ref(''),filterGroups=ref<CustomerWorkUserGroups['list']>([]),filterLevels=ref<CustomerWorkUserLevels['list']>([]),filterLabels=ref<CustomerWorkUserLabels['list']>([]),kinds=CUSTOMER_WORK_USER_KINDS,names=CUSTOMER_WORK_USER_NAMES,bulkKinds:CustomerWorkUserKind[]=['replace_group','replace_labels','grant_coupons'];let filterEpoch=0,appliedQuery:Record<string,string>={};
function clear(){list.value=null;selected.value=[];message.value='';moreBusy.value=false;closeFilter();editor.clear();}
const manager=useCustomerWork({page:'users',query(query){keyword.value=query.nickname??'';filters.value={group_id:query.group_id??'0',level:query.level??'0',label_ids:query.label_ids??'',isMember:query.isMember??''};},clear,async load(controller){const valid=controller.fence(),query={nickname:keyword.value,...filters.value},response=await operations.read('/mobile/work/users',isCustomerWorkUserList,{page:1,limit:20,...query});if(valid()){appliedQuery=query;append(response.data,1);}}}),operations=useCustomerWorkUserOperations(manager),editor=useCustomerWorkUserEditor(manager,operations),selectedUsers=computed(()=>(list.value?.list??[]).filter(user=>selected.value.includes(user.uid))),assignmentKind=computed(()=>['replace_level','replace_group','replace_labels'].includes(editor.kind.value)?editor.kind.value as 'replace_level'|'replace_group'|'replace_labels':'replace_group');
function membership(user:CustomerWorkUser){return user.is_ever_level?(user.membership_active?'永久会员':'永久会员标记 · 当前未生效'):user.membership_active?`会员有效 · 剩余 ${user.svip_over_day??0} 天`:user.isMember?'有会员标记 · 当前未生效':'无付费会员标记';}
function append(data:CustomerWorkUserList,page:number){if(data.page!==page||data.limit!==20||page>1&&(data.count!==list.value?.count||data.list.some(user=>list.value?.list.some(old=>old.uid===user.uid))))throw Error('用户分页已变化，请重新读取');list.value={...data,list:[...(page>1?list.value?.list??[]:[]),...data.list]};}
function search(){if(operations.busy.value)return;if(Array.from(keyword.value).length>100||/[\u0000-\u001f\u007f]/u.test(keyword.value)){message.value='搜索文字无效或超过100字';return;}void manager.load();}
async function loadMore(){if(moreBusy.value||operations.busy.value||!list.value?.has_more)return;const valid=manager.fence(),page=list.value.page+1;moreBusy.value=true;try{const result=await operations.read('/mobile/work/users',isCustomerWorkUserList,{page,limit:20,...appliedQuery});if(valid())append(result.data,page);}catch(failure){if(valid())manager.invalidate(failure);}finally{if(valid())moreBusy.value=false;}}
function toggle(uid:number){if(operations.busy.value||!list.value?.list.some(user=>user.uid===uid))return;if(selected.value.includes(uid))selected.value=selected.value.filter(id=>id!==uid);else if(selected.value.length<100)selected.value=[...selected.value,uid];else message.value='一次最多选择100位用户';}
function selectAll(){if(!list.value||operations.busy.value)return;if(list.value.list.length>100){message.value='一次最多选择100位用户，请分批选择';return;}selected.value=selected.value.length===list.value.list.length?[]:list.value.list.map(user=>user.uid);}
function canBatch(kind:CustomerWorkUserKind){return!!list.value?.readiness.writes&&!operations.busy.value&&selectedUsers.value.length>0&&selectedUsers.value.every(user=>user.actions[kind].available);}
function closeFilter(){filterEpoch++;filterVisible.value=false;filterLoading.value=false;filterError.value='';filterGroups.value=[];filterLevels.value=[];filterLabels.value=[];}
async function openFilter(){if(operations.busy.value)return;closeFilter();const version=filterEpoch,valid=manager.fence();filterVisible.value=true;filterLoading.value=true;try{const [groups,levels,labels]=await Promise.all([operations.read('/mobile/work/users/groups',isCustomerWorkUserGroups),operations.read('/mobile/work/users/levels',isCustomerWorkUserLevels),operations.read('/mobile/work/users/labels',isCustomerWorkUserLabels,{uid:0})]);if(valid()&&version===filterEpoch){if(labels.data.uid!==0)throw Error('平台标签目录归属无效');filterGroups.value=groups.data.list;filterLevels.value=levels.data.list;filterLabels.value=labels.data.list;}}catch(failure){if(valid()&&version===filterEpoch)filterError.value=failure instanceof Error?failure.message:'筛选目录读取失败';}finally{if(valid()&&version===filterEpoch)filterLoading.value=false;}}
function applyFilter(value:Record<string,string>){if(operations.busy.value)return;filters.value={...value};closeFilter();search();}
</script>
