<template><CustomerWorkShell title="核对原核销结果" :manager="manager" :domain-busy="writeoff.busy.value" active="scanning"><template #recovery><CustomerWorkWriteoffRecoveryPanel :operations="writeoff" /></template><view class="cw-card"><text class="cw-subtitle">{{ legacyId?'历史结果需要重新核对':'原核销编号' }}</text><text v-if="requestKey" class="cw-request-key">{{ requestKey }}</text><text v-if="legacyId" class="cw-scope">旧结果链接只带订单物理编号，没有原操作回执，不能证明核销成功。请读取当前订单的实际核销记录。</text><template v-if="intent"><text class="cw-scope">{{ customerWriteoffResultMessage(state?.result??null) }}</text><text v-if="state?.result?.receipt&&customerWriteoffTerminal(state.result)" class="cw-scope">仅按原编号、完整意图及实际业务证据确认结果。</text><view v-if="state?.result?.execution?.verified" class="cw-stack"><text v-for="row in evidenceRows" :key="row.writeoff_id">实际记录 {{ row.writeoff_id }} · 商品行 {{ row.cart_row_id }} · {{ row.quantity }} 次 · ¥{{ row.writeoff_price }}</text></view><view class="cw-controls"><button :disabled="writeoff.busy.value" @tap="writeoff.check(intent)">查询原结果</button><button v-if="writeoff.readable()" :disabled="writeoff.busy.value" @tap="manager.go('writeoff',{orderId:intent.body.order_id,orderNo:intent.order_no})">读取原订单与剩余次数</button><button v-if="writeoff.readable()" :disabled="writeoff.busy.value" @tap="manager.go('writeoffRecords',{orderId:intent.body.order_id,orderNo:intent.order_no})">分页核销记录</button></view></template><text v-else-if="!legacyId" class="cw-error">此原编号没有属于当前账号的完整本机意图。不能按链接声称核销成功，也不能新建编号补提。</text><button v-if="legacyId&&writeoff.target.value" @tap="manager.go('writeoffRecords',{orderId:writeoff.target.value.data.id,orderNo:writeoff.target.value.data.order_no})">读取历史订单实际记录</button></view><text v-if="writeoff.error.value" class="cw-error">{{ writeoff.error.value }}</text></CustomerWorkShell></template>
<script setup lang="ts">
import {computed,ref} from 'vue';
import CustomerWorkShell from '@/components/customerWork/CustomerWorkShell.vue';
import CustomerWorkWriteoffRecoveryPanel from '@/components/customerWork/CustomerWorkWriteoffRecoveryPanel.vue';
import {useCustomerWork} from '@/composables/useCustomerWork';
import {useCustomerWorkWriteoffOperations} from '@/composables/useCustomerWorkWriteoffOperations';
import {customerWriteoffResultMessage,customerWriteoffTerminal} from '@/utils/customerWorkWriteoff';
import type {CustomerWorkWriteoffRowEvidence} from '@/types/customerWorkWriteoff';
const requestKey=ref(''),legacyId=ref('');
const manager=useCustomerWork({page:'writeoffResult',query(q){requestKey.value=q.requestKey??'';legacyId.value=q.legacyOrderId??'';},clear(){writeoff.clearDomain();},async load(){if(!writeoff.readable())throw Error('当前普通客户核销查询入口不可用');writeoff.refreshPending();if(legacyId.value){await writeoff.resolveLegacy(legacyId.value);return;}const original=writeoff.pending.value.find(i=>i.request_key===requestKey.value);if(original)await writeoff.check(original);}}),writeoff=useCustomerWorkWriteoffOperations(manager),intent=computed(()=>writeoff.pending.value.find(i=>i.request_key===requestKey.value)??null),state=computed(()=>intent.value?writeoff.states.value[intent.value.request_key]:undefined),evidenceRows=computed(()=>state.value?.result?.execution?.verified?(state.value.result.receipt?.evidence.writeoff_rows??[]) as unknown as CustomerWorkWriteoffRowEvidence[]:[]);
</script>
