<template><CustomerWorkShell title="实际核销记录" :manager="manager" :domain-busy="reading||writeoff.busy.value" active="scanning"><template #recovery><CustomerWorkWriteoffRecoveryPanel :operations="writeoff" /></template><view v-if="basis" class="cw-card"><text class="cw-subtitle">订单 {{ basis.order_no }}</text><text class="cw-scope">付款订单 {{ basis.root_order_no }}。客户执行人须有原核销回执证明；买家编号和当前配送员不能证明历史执行人。</text><button :disabled="reading||writeoff.busy.value" @tap="manager.go('writeoff',{orderId:basis.id,orderNo:basis.order_no})">重新核对商品与剩余次数</button></view><view v-if="records" class="cw-card"><text class="cw-subtitle">共 {{ records.count }} 条 · 第 {{ records.page }} 页</text><text v-if="!records.list.length" class="cw-scope">此页没有核销记录。</text><view v-for="row in records.list" :key="row.record_id" class="cw-stack cw-divider" :data-writeoff-record="row.record_id"><text>记录 {{ row.record_id }} · 商品行 {{ row.cart_row_id }}</text><text>{{ row.writeoff_num }} 次 · 实际成交核销金额 ¥{{ row.writeoff_price }}</text><text>{{ customerWriteoffTime(row.created_at) }}</text><text>{{ operatorText(row) }}</text><text v-if="row.operator.kind==='customer'" class="cw-request-key">原编号 {{ row.operator.request_key }}</text></view><view class="cw-controls"><button :disabled="reading||writeoff.busy.value||records.page<=1" @tap="loadPage(records.page-1)">上一页</button><button :disabled="reading||writeoff.busy.value||!records.has_more" @tap="loadPage(records.page+1)">下一页</button></view></view><text v-if="error||writeoff.error.value" class="cw-error">{{ error||writeoff.error.value }}</text></CustomerWorkShell></template>
<script setup lang="ts">
import {computed,ref} from 'vue';
import CustomerWorkShell from '@/components/customerWork/CustomerWorkShell.vue';
import CustomerWorkWriteoffRecoveryPanel from '@/components/customerWork/CustomerWorkWriteoffRecoveryPanel.vue';
import {useCustomerWork} from '@/composables/useCustomerWork';
import {useCustomerWorkWriteoffOperations} from '@/composables/useCustomerWorkWriteoffOperations';
import {customerWriteoffNotice,customerWriteoffTime} from '@/utils/customerWorkWriteoff';
import type {CustomerWorkWriteoffRecord} from '@/types/customerWorkWriteoff';
const orderId=ref(0),orderNo=ref(''),legacyId=ref(''),reading=ref(false),error=ref('');let epoch=0;
const manager=useCustomerWork({page:'writeoffRecords',query(q){legacyId.value=q.legacyOrderId??'';orderId.value=Number(q.orderId??0);orderNo.value=q.orderNo??'';},clear(){epoch++;reading.value=false;error.value='';writeoff.clearDomain();},async load(controller){if(!writeoff.readable())throw Error('当前普通客户核销记录入口不可用');const valid=controller.fence(),actual=legacyId.value?await writeoff.resolveLegacy(legacyId.value):await writeoff.loadTarget(orderId.value,orderNo.value);if(valid()){await writeoff.loadRecords(actual.id,actual.order_no);if(valid())await writeoff.checkRelevant(actual.root_order_id);}}}),writeoff=useCustomerWorkWriteoffOperations(manager),basis=computed(()=>writeoff.target.value?.data??null),records=computed(()=>writeoff.records.value);
async function loadPage(page:number){const target=basis.value;if(reading.value||writeoff.busy.value||!target)return;const valid=manager.fence(),version=++epoch;reading.value=true;error.value='';try{await writeoff.loadRecords(target.id,target.order_no,page);}catch(failure){if(valid()&&version===epoch)error.value=failure instanceof Error?customerWriteoffNotice(failure.message):'记录页面需核对';}finally{if(valid()&&version===epoch)reading.value=false;}}
function operatorText(row:CustomerWorkWriteoffRecord){const op=row.operator;if(op.kind==='customer')return`普通客户执行人 ${op.actor_uid} · 经营身份 ${op.service_id} · 已由原回执证明`;if(op.kind==='admin')return`管理执行人 ${op.admin_id}`;if(op.kind==='staff')return`门店核销员 ${op.staff_id}`;if(op.kind==='delivery')return`配送执行人 ${op.delivery_id}`;return'历史执行人无法证明，保留未知身份';}
</script>
