import { sql } from 'drizzle-orm';
import type { DbClient } from '../lib/di';
import { pricingIdentifier } from './checkoutPricingLockCatalog';
import { CUSTOMER_WORK_SCOPE_LOCK_KEY,CUSTOMER_WORK_SCOPE_OWNER_SETTING,customerWorkScopeCatalogQuery,customerWorkScopeCatalogReady,customerWorkScopeLockInstallationSql,type CustomerWorkScopeCatalog } from './customerWorkScopeLock';
type Query=Pick<DbClient,'execute'>;
export async function inspectCustomerWorkScopeLock(db:Query,schema='public'):Promise<CustomerWorkScopeCatalog>{const[row]=await db.execute(customerWorkScopeCatalogQuery(schema));if(!row)throw Error('CustomerWork scope catalog unavailable');return{tablesSafe:row.tablesSafe===true,absent:row.absent===true,definitionSafe:row.definitionSafe===true,ownerSafe:row.ownerSafe===true,aclSafe:row.aclSafe===true,ownerOid:typeof row.ownerOid==='string'?row.ownerOid:null,functionOids:Array.isArray(row.functionOids)?row.functionOids.filter((v):v is string=>typeof v==='string'):[]};}
export async function installCustomerWorkScopeLock(db:Pick<DbClient,'transaction'>&Partial<Pick<DbClient,'$client'>>,ownerRole:string,schema='public'){
 if(!Object.hasOwn(db,'$client')||!db.$client)throw Error('CustomerWork scope installation requires root maintenance client');pricingIdentifier(ownerRole);pricingIdentifier(schema);
 return db.transaction(async tx=>{await tx.execute(sql`SELECT pg_catalog.set_config(${CUSTOMER_WORK_SCOPE_OWNER_SETTING},${ownerRole},true)`);await tx.execute(sql.raw(customerWorkScopeLockInstallationSql(schema)));const state=await inspectCustomerWorkScopeLock(tx,schema);if(!customerWorkScopeCatalogReady(state))throw Error('CustomerWork scope installation failed verification');return state;},{isolationLevel:'read committed',accessMode:'read write'});
}
/** Pure inspection: does not lock, commission or grant on the request path. */
export async function customerWorkScopeLockReadiness(db:Query,schema='public'){
 const catalog=await inspectCustomerWorkScopeLock(db,schema);if(!customerWorkScopeCatalogReady(catalog))return{ready:false,reason:catalog.absent?'customer_work_scope_not_installed':'customer_work_scope_catalog_unreviewed',catalog};
 const[row]=await db.execute(sql`WITH RECURSIVE identity AS(SELECT oid FROM pg_catalog.pg_roles WHERE rolname IN(current_user,session_user) UNION SELECT usesysid FROM pg_catalog.pg_stat_activity WHERE pid=pg_catalog.pg_backend_pid()),authority(oid) AS(SELECT oid FROM identity UNION SELECT m.roleid FROM pg_catalog.pg_auth_members m JOIN authority a ON a.oid=m.member)
 SELECT NOT EXISTS(SELECT 1 FROM authority a JOIN pg_catalog.pg_roles r ON r.oid=a.oid WHERE r.rolsuper OR r.rolcreatedb OR r.rolcreaterole OR r.rolreplication OR r.rolbypassrls OR r.oid::text=${catalog.ownerOid} OR pg_catalog.has_schema_privilege(r.oid,${schema},'CREATE') OR pg_catalog.has_parameter_privilege(r.oid,'session_replication_role','SET') OR EXISTS(SELECT 1 FROM pg_catalog.pg_database WHERE datdba=r.oid AND datname=current_database()) OR EXISTS(SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname=${schema} AND c.relname IN('store_service','express_company','delivery_service') AND(c.relowner=r.oid OR pg_catalog.has_table_privilege(r.oid,c.oid,'INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') OR pg_catalog.has_any_column_privilege(r.oid,c.oid,'INSERT,REFERENCES') OR EXISTS(SELECT 1 FROM pg_catalog.pg_attribute col WHERE col.attrelid=c.oid AND col.attnum>0 AND NOT col.attisdropped AND NOT(c.relname='store_service' AND col.attname='online') AND pg_catalog.has_column_privilege(r.oid,c.oid,col.attnum,'UPDATE'))))) AS safe,
 (SELECT count(*)=3 AND bool_and(pg_catalog.has_function_privilege(current_user,oid,'EXECUTE')) FROM pg_catalog.pg_proc WHERE oid::text IN(${sql.join(catalog.functionOids.map(id=>sql`${id}`),sql`, `)})) AS executable`);
 const ready=row?.safe===true&&row?.executable===true;return{ready,reason:ready?'':'customer_work_scope_runtime_unreviewed',catalog};
}
async function gate(tx:DbClient,schema:string){if(Object.hasOwn(tx,'$client'))throw Error('CustomerWork locks require caller-owned transaction');const[row]=await tx.execute(sql`SELECT pg_catalog.pg_try_advisory_xact_lock_shared(${CUSTOMER_WORK_SCOPE_LOCK_KEY},oid::int) AS locked FROM pg_catalog.pg_namespace WHERE nspname=${schema}`);if(row?.locked!==true)throw Error('CustomerWork scope maintenance busy');if(!(await customerWorkScopeLockReadiness(tx,schema)).ready)throw Error('CustomerWork lock capability missing or unreviewed');}
export async function acquireCustomerWorkScopeLock(tx:DbClient,uid:number,schema='public'){await gate(tx,schema);if(!Number.isSafeInteger(uid)||uid<1||uid>2147483647)throw Error('Customer work lock identity invalid');await tx.execute(sql`SELECT ${sql.raw(pricingIdentifier(schema))}.customer_work_lock_scope_v1(${uid}::integer)`);}
export async function acquireCustomerWorkCarrierLock(tx:DbClient,carrierId:number,schema='public'){await gate(tx,schema);if(!Number.isSafeInteger(carrierId)||carrierId<1||carrierId>2147483647)throw Error('Customer carrier identity invalid');await tx.execute(sql`SELECT ${sql.raw(pricingIdentifier(schema))}.customer_work_lock_carrier_v1(${carrierId}::integer)`);}
export async function acquireCustomerWorkCourierLock(tx:DbClient,uid:number,schema='public'){await gate(tx,schema);if(!Number.isSafeInteger(uid)||uid<1||uid>2147483647)throw Error('Customer courier identity invalid');await tx.execute(sql`SELECT ${sql.raw(pricingIdentifier(schema))}.customer_work_lock_courier_v1(${uid}::integer)`);}
