import { sql } from 'drizzle-orm';
import type { DbClient } from '../lib/di';
import { pricingIdentifier } from './checkoutPricingLockCatalog';
import { MANAGER_SCOPE_LOCK_KEY,MANAGER_SCOPE_OWNER_SETTING,managerScopeCatalogQuery,managerScopeCatalogReady,managerScopeLockInstallationSql,type ManagerScopeCatalog } from './managerScopeLock';
type Query=Pick<DbClient,'execute'>;
export async function inspectManagerScopeLock(db:Query,schema='public'):Promise<ManagerScopeCatalog>{const[row]=await db.execute(managerScopeCatalogQuery(schema));if(!row)throw Error('Manager scope catalog unavailable');return{tablesSafe:row.tablesSafe===true,absent:row.absent===true,definitionSafe:row.definitionSafe===true,ownerSafe:row.ownerSafe===true,aclSafe:row.aclSafe===true,ownerOid:typeof row.ownerOid==='string'?row.ownerOid:null,functionOids:Array.isArray(row.functionOids)?row.functionOids.filter((v):v is string=>typeof v==='string'):[]};}
export async function installManagerScopeLock(db:Pick<DbClient,'transaction'>&Partial<Pick<DbClient,'$client'>>,ownerRole:string,schema='public'){
 if(!Object.hasOwn(db,'$client')||!db.$client)throw Error('Manager scope installation requires root maintenance client');pricingIdentifier(ownerRole);pricingIdentifier(schema);
 return db.transaction(async tx=>{await tx.execute(sql`SELECT pg_catalog.set_config(${MANAGER_SCOPE_OWNER_SETTING},${ownerRole},true)`);await tx.execute(sql.raw(managerScopeLockInstallationSql(schema)));const state=await inspectManagerScopeLock(tx,schema);if(!managerScopeCatalogReady(state))throw Error('Manager scope installation failed verification');return state;},{isolationLevel:'read committed',accessMode:'read write'});
}
/** Pure inspection: does not lock, commission or grant on the request path. */
export async function managerScopeLockReadiness(db:Query,schema='public'){
 const catalog=await inspectManagerScopeLock(db,schema);if(!managerScopeCatalogReady(catalog))return{ready:false,reason:catalog.absent?'manager_scope_not_installed':'manager_scope_catalog_unreviewed',catalog};
 const[row]=await db.execute(sql`WITH RECURSIVE identity AS(SELECT oid FROM pg_catalog.pg_roles WHERE rolname IN(current_user,session_user) UNION SELECT usesysid FROM pg_catalog.pg_stat_activity WHERE pid=pg_catalog.pg_backend_pid()),authority(oid) AS(SELECT oid FROM identity UNION SELECT m.roleid FROM pg_catalog.pg_auth_members m JOIN authority a ON a.oid=m.member)
 SELECT NOT EXISTS(SELECT 1 FROM authority a JOIN pg_catalog.pg_roles r ON r.oid=a.oid WHERE r.rolsuper OR r.rolcreatedb OR r.rolcreaterole OR r.rolreplication OR r.rolbypassrls OR r.oid::text=${catalog.ownerOid} OR pg_catalog.has_schema_privilege(r.oid,${schema},'CREATE') OR pg_catalog.has_parameter_privilege(r.oid,'session_replication_role','SET') OR EXISTS(SELECT 1 FROM pg_catalog.pg_database WHERE datdba=r.oid AND datname=current_database()) OR EXISTS(SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname=${schema} AND c.relname IN('system_store_staff','express_company') AND(c.relowner=r.oid OR pg_catalog.has_table_privilege(r.oid,c.oid,'INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') OR pg_catalog.has_any_column_privilege(r.oid,c.oid,'INSERT,UPDATE,REFERENCES')))) AS safe,
 (SELECT count(*)=2 AND bool_and(pg_catalog.has_function_privilege(current_user,oid,'EXECUTE')) FROM pg_catalog.pg_proc WHERE oid::text IN(${sql.join(catalog.functionOids.map(id=>sql`${id}`),sql`, `)})) AS executable`);
 const ready=row?.safe===true&&row?.executable===true;return{ready,reason:ready?'':'manager_scope_runtime_unreviewed',catalog};
}
async function gate(tx:DbClient,schema:string){if(Object.hasOwn(tx,'$client'))throw Error('Manager locks require caller-owned transaction');const[row]=await tx.execute(sql`SELECT pg_catalog.pg_try_advisory_xact_lock_shared(${MANAGER_SCOPE_LOCK_KEY},oid::int) AS locked FROM pg_catalog.pg_namespace WHERE nspname=${schema}`);if(row?.locked!==true)throw Error('Manager scope maintenance busy');if(!(await managerScopeLockReadiness(tx,schema)).ready)throw Error('Manager lock capability missing or unreviewed');}
export async function acquireManagerScopeLock(tx:DbClient,uid:number,storeId:number,schema='public'){await gate(tx,schema);if(!Number.isSafeInteger(uid)||uid<1||uid>2147483647||!Number.isSafeInteger(storeId)||storeId<1||storeId>2147483647)throw Error('Manager lock identity invalid');await tx.execute(sql`SELECT ${sql.raw(pricingIdentifier(schema))}.manager_lock_scope_v1(${uid}::integer,${storeId}::integer)`);}
export async function acquireManagerCarrierLock(tx:DbClient,code:string,schema='public'){await gate(tx,schema);await tx.execute(sql`SELECT ${sql.raw(pricingIdentifier(schema))}.manager_lock_carrier_v1(${code}::text)`);}
