import type { Context } from "hono";
import { deleteCookie, getCookie, setCookie } from "hono/cookie";
import type { ScanLoginAudience } from "@/do/TokenBucketDO";

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

function cookieName(audience: ScanLoginAudience, state: string): string | null {
  const normalizedState = state.trim().toLowerCase();
  if (!UUID_PATTERN.test(normalizedState)) return null;
  const prefix = audience === "pc_user"
    ? "__Host-cinashop-pc-oauth-"
    : "__Host-cinashop-kefu-oauth-";
  return prefix + normalizedState;
}

const OPTIONS = {
  httpOnly: true,
  secure: true,
  sameSite: "Lax" as const,
  path: "/" as const,
};

export function setOauthBrowserVerifier(
  c: Context,
  audience: ScanLoginAudience,
  state: string,
  verifier: string,
  maxAge: number,
): void {
  const name = cookieName(audience, state);
  if (!name) throw new Error("Invalid OAuth state generated by server");
  setCookie(c, name, verifier, {
    ...OPTIONS,
    maxAge,
  });
}

export function oauthBrowserVerifier(
  c: Context,
  audience: ScanLoginAudience,
  state: string,
): string {
  const name = cookieName(audience, state);
  return name ? getCookie(c, name) ?? "" : "";
}

export function clearOauthBrowserVerifier(
  c: Context,
  audience: ScanLoginAudience,
  state: string,
): void {
  const name = cookieName(audience, state);
  if (name) deleteCookie(c, name, OPTIONS);
}
